### ISSUE TITLE
Linux-Magazin.de crashes script thread (in <link rel=stylesheet> element code)

### ISSUE THREAD

**Issue by notriddle** [servo/servo#12086] opened 2016-07-01 16:46 UTC
assertion failed: count_cell.get() > 0
### URL:
http://www.linux-magazin.de/NEWS/Erste-Nightly-Build-von-Mozillas-Servo
### Backtrace:
```
frame #0  - 0x0000564834b28cbd - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000564834b28c45 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000564833cdf529 - _<F as alloc..boxed..FnBox<A>>::call_box::hf0c3b19fadfd7b5c
frame #3  - 0x0000564834b1fac8 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hd621272b9fdb199b
frame #4  - 0x0000564834c2704c - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x00005648335220bf - std::panicking::begin_panic::h0bf39f6d43ab9349
frame #6  - 0x0000564833b94660 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::hb21db8d18795ebf5
frame #7  - 0x0000564833b9216b - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h08f0e3f99978b874
frame #8  - 0x0000564833cea474 - script::script_thread::ScriptThread::handle_msg_from_script::hc5820e23bea42e4c
frame #9  - 0x0000564833d3babf - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h4452edec5414c581
frame #10 - 0x0000564833d22ca7 - script::script_thread::ScriptThread::handle_msgs::hc464f81e7cc73576
frame #11 - 0x0000564833cddc17 - std::panicking::try::call::h961f36898b5c34f4
frame #12 - 0x0000564834c4b85b - __rust_try
frame #13 - 0x0000564834c4b7fe - __rust_maybe_catch_panic
frame #14 - 0x0000564833cdee8d - _<F as alloc..boxed..FnBox<A>>::call_box::h607cb71cb911a26b
frame #15 - 0x0000564834c3f824 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #16 - 0x00007fa8d920c554 - start_thread
frame #17 - 0x00007fa8d8d2fdec - __clone
frame #18 - 0x0000000000000000 - <unknown>

```

**Comment by jdm** [comment] 2016-07-01 16:48
Duplicate of https://github.com/servo/servo/issues/12047.

**Closed by jdm** 2016-07-01 16:48 UTC
Labels: A-content/script, I-panic
