### ISSUE TITLE
cannot start servo on debian stretch/sid (yet again the libssl issue)

### ISSUE THREAD

**Issue by liuchong** [servo/servo#12164] opened 2016-07-02 09:51 UTC
error message:

```
./servo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

uname -a:
Linux localhost 4.6.0-1-amd64 #1 SMP Debian 4.6.2-2 (2016-06-25) x86_64 GNU/Linux

on my system, it is libssl.so.1.0.2, not 1.0.0,  and if I just make a link named 1.0.0 point to 1.0.2, it will report the message:

```
./servo: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)
```

so what's wrong is 1.0.2 against 1.0.0?
could it be compiled static linked or compiled as using "libssl.so" without version

**Comment by frewsxcv** [comment] 2016-07-02 14:10
This is probably a duplicate of https://github.com/servo/servo/issues/12015.

**Closed by frewsxcv** 2016-07-02 14:10 UTC
