### ISSUE TITLE
Intermittent CRASH in  /_mozilla/mozilla/service-workers/service-worker-registration.https.html

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#30141] opened 2023-08-19 08:55 UTC
The error seems to be this:

```
     Hey Servo; lets cache something! :)
      assertion failed: !GetCurrentRealmOrNull(*cx).is_null() (thread SW:web-platform.test:8443/_mozilla/mozilla/service-workers/resources/sw.js, at components/script/realms.rs:23)
         0: servo::backtrace::print
         1: servo::main::{{closure}}
         2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:2002:9
            std::panicking::rust_panic_with_hook
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:692:13
         3: std::panicking::begin_panic_handler::{{closure}}
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:577:13
         4: std::sys_common::backtrace::__rust_end_short_backtrace
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
         5: rust_begin_unwind
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
         6: core::panicking::panic_fmt
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
         7: core::panicking::panic
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:114:5
         8: script::dom::eventtarget::EventTarget::dispatch_event
         9: script::dom::serviceworkerglobalscope::ServiceWorkerGlobalScope::dispatch_activate
        10: std::sys_common::backtrace::__rust_begin_short_backtrace
        11: core::ops::function::FnOnce::call_once{{vtable.shim}}
        12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
            <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
            std::sys::unix::thread::Thread::new::thread_start
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys/unix/thread.rs:108:17
        13: start_thread
        14: clone
      Hey Servo; lets cache something! :)
      assertion failed: !GetCurrentRealmOrNull(*cx).is_null() (thread SW:web-platform.test:8443/_mozilla/mozilla/service-workers/resources/sw.js, at components/script/realms.rs:23)
         0: servo::backtrace::print
         1: servo::main::{{closure}}
         2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:2002:9
            std::panicking::rust_panic_with_hook
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:692:13
         3: std::panicking::begin_panic_handler::{{closure}}
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:577:13
         4: std::sys_common::backtrace::__rust_end_short_backtrace
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
         5: rust_begin_unwind
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
         6: core::panicking::panic_fmt
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
         7: core::panicking::panic
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:114:5
         8: script::dom::eventtarget::EventTarget::dispatch_event
         9: script::dom::serviceworkerglobalscope::ServiceWorkerGlobalScope::dispatch_activate
        10: std::sys_common::backtrace::__rust_begin_short_backtrace
        11: core::ops::function::FnOnce::call_once{{vtable.shim}}
        12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
            <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
            std::sys::unix::thread::Thread::new::thread_start
                   at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys/unix/thread.rs:108:17
        13: start_thread
        14: clone
```

**Comment by jdm** [comment] 2023-08-19 14:43
We need to [enter a realm](https://github.com/servo/servo/blob/b45081b121a934deffb774ffb00810d3dcbcdf93/components/script/dom/serviceworkerglobalscope.rs#L444) before we call the dispatch_active method in ServiceWorkerGlobalScope.

**Comment by ss77995ss** [comment] 2023-08-30 14:20
Hi! May I try this one if it still available?

**Comment by jdm** [comment] 2023-08-30 23:19
Please do!

**Comment by ss77995ss** [comment] 2023-08-31 04:16
Thanks!
I've found the `dispatch_activate` in line [#384](https://github.com/servo/servo/blob/b45081b121a934deffb774ffb00810d3dcbcdf93/components/script/dom/serviceworkerglobalscope.rs#L384)
Then according to previous comment. I just need to add `enter_realm` before it or I could add just after line [#375](https://github.com/servo/servo/blob/b45081b121a934deffb774ffb00810d3dcbcdf93/components/script/dom/serviceworkerglobalscope.rs#L375C7-L375C7) so that we can ensure the following code is in the **realm**?

Besides, I should run `tests/wpt/mozilla/tests/mozilla/service-workers/service-worker-registration.https.html` for testing right?

**Comment by jdm** [comment] 2023-08-31 13:10
Adding it after lime 375 looks like it might work! And yes, testing with that file should show the crash before the changes ad no crash after.

**Comment by ss77995ss** [comment] 2023-08-31 18:51
Hi @jdm . I've created the PR for this one and added `enter_realm` but still failed in tests.
Maybe I missed something else?

**Comment by jdm** [comment] 2023-09-01 00:05
This was apparently an intermittent crash, so it didn't happen every time. The fact that the test reports failures isn't a concern, since the service worker implementation in Servo is still very basic.

**Comment by ss77995ss** [comment] 2023-09-01 07:11
Got it! Thanks for the reply. I removed the **WIP** from my PR.
Just curious how do we valid our modification is correct while solving this kind of issue?

**Comment by jdm** [comment] 2023-09-01 20:16
Ideally, we would verify that the crash can be reproduced before making the change, so we're confident that the crash is gone after the change. With this case, we'll close this issue and we'll find out in the future if any crashes are reported by CI (since right now this issue with the "I-intermittent" tag causes them to be suppressed).

**Closed** 2023-09-01 21:43 UTC
Labels: E-easy, A-content/script, I-intermittent

**Comment by ss77995ss** [comment] 2023-09-01 21:46
@jdm I see! Thank you for your support and guidance!
