### ISSUE TITLE
Windows builder needs to taskkill all remaining processes

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#11719] opened 2016-06-10 20:29 UTC
We've had some failures on Windows when there is a runaway servo or unit test process. These will keep a lock on the directory and break either the git or compile steps on all subsequent builds until it's fixed. One idea is to create a taskkill step, similar to the pkill steps on the other machines.

**Comment by aneeshusa** [comment] 2016-06-11 01:26
Dupe of servo/saltfs#351.

**Closed by aneeshusa** 2016-06-11 01:26 UTC
Labels: A-infrastructure, P-windows
