### ISSUE TITLE
servo can't startup

### ISSUE THREAD

**Issue by bumingzzw** [servo/servo#12889] opened 2016-08-16 07:19 UTC
./servo: error while loading shared libraries: libavformat.so.54: cannot open shared object file: No such file or directory
OS: debian unstable

I create a link to libavformat.so.57 as libavformat.so.54 ,  servo also check the version of avformat, tips not a version 54, and can't startup too.

**Comment by bumingzzw** [comment] 2016-08-16 07:21
also, has a problem of libavutils, also not the required version 52 .  in my debian linux,  I had install libavformat version 57 and libavutils version 54.

**Comment by emilio** [comment] 2016-08-16 07:23
This is a dupe of https://github.com/servo/servo/issues/12687, feel free to subscribe there. Thanks for reporting it though! :-)

**Closed by emilio** 2016-08-16 07:23 UTC
