### ISSUE TITLE
How to fix servo app render issue on macOS.

### ISSUE THREAD

**Issue by chenzww** [servo/servo#24258] opened 2019-09-20 23:31 UTC
The Server.app download from 'https//downloadservo.org' site. Every platform render well except on macOS. How to fix it?

![screenshot 2019-09-21 07 28 08](https://user-images.githubusercontent.com/1970731/65363991-74148e80-dc41-11e9-93af-aab0f7d958a3.png)

**Comment by jdm** [comment] 2019-09-20 23:46
I can't reproduce this with the latest build from download.servo.org on macOS 10.14.6:
<img width="1136" alt="Screen Shot 2019-09-20 at 7 45 55 PM" src="https://user-images.githubusercontent.com/27658/65364368-53b3e800-dbdf-11e9-9753-65af7a6a6004.png">

**Comment by nicoabie** [comment] 2020-07-29 01:29
I can't reproduce this with the latest build from download.servo.org on macOS 10.15.6
@chenzww can you still reproduce this issue?

**Comment by jdm** [comment] 2020-07-29 01:42
This is a graphics driver bug on certain classes of macOS drivers. It can be fixed by running the app with `--pref gfx.texture-swizzling.enabled=false`. Closing as a duplicate of #26224.

**Closed by jdm** 2020-07-29 01:42 UTC
Labels: P-mac
