### ISSUE TITLE
`<b>` element is not rendered as bold in serenityos homepage

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#29818] opened 2023-05-31 07:18 UTC
| Firefox | Servo Layout 2013 | Servo Layout 2020 |
| --- | --- | --- |
| ![image](https://github.com/servo/servo/assets/6782666/e9eaec76-d65d-4207-af2b-f55b517c130f) | ![image](https://github.com/servo/servo/assets/6782666/1e340ebe-8b78-4dc1-9467-b2778a1d94bd) | ![image](https://github.com/servo/servo/assets/6782666/73e51dab-2d5f-4b08-b388-eb01a5cfdcdf) |

### How to reproduce

1. Visit https://serenityos.org/
2. Confirm `<b>` element is rendered as bold

#### Environment

macOS 13.4

**Comment by mrego** [comment] 2023-05-31 07:38
It works here on Linux (Layout 2020):
![Screenshot of serenityos.org webpage on Servo Linux build](https://github.com/servo/servo/assets/11602/be89c9ae-721a-4de3-ba0b-da14226cf878)

Dunno if it's something related to the font or not, could you try something simple like next lines to see if there's any difference?
```html
<!DOCTYPE html>
This is <b>bold</b>.
<div style="font-family: sans-serif;">This is <b>bold</b>.</div>
```

**Comment by CYBAI** [comment] 2023-05-31 08:52
ah, thanks for reminder of platforms! I just updated to the issue description that I'm on macOS 13.4.

With checking with the above snippet, this is the result on my end:
![image](https://github.com/servo/servo/assets/6782666/c1c0ec85-8fdd-4765-ba54-b79448d1a6dc)

Looks like the b element in second line is not rendered as bold so it sounds related to the font. 🤔

**Comment by paricbat** [comment] 2023-07-03 17:43
I would like to attempt fixing this issue, can I get some pointers?

**Comment by mrobinson** [comment] 2023-07-04 09:28
I suspect that the issue is related to font selection. Implementing proper font selection means choosing the best font for a given CSS declaration, falling back when the style or character is not available in the chosen font. In some cases, when a  font is chosen with no other alternative that matches the style, the web engine must use a "synthetic bold" or "synthetic italic" approach in order to try to render the glyph properly. In this case, I suspect that the issue is simply one where font selection isn't returning the appropriate font which meets the requirements for a bold style. This could possibly be a bug in `font-kit` or the way that servo is using `font-kit`.

**Comment by paricbat** [comment] 2023-07-04 17:09
I found out that Servo (in my case) chooses to use Noto Sans, but it doesn't find the bold variation, which is for some reason missing, and uses the regular variation instead.

**Comment by mrobinson** [comment] 2024-04-21 13:51
A long time later and I'm fairly certain this is a duplicate of #24554.

**Closed by mrobinson** 2024-04-21 13:51 UTC
