### ISSUE TITLE
assertion failed: !self.Document().needs_reflow() ||    (!for_display && self.Document().needs_paint()) ||    self.window_size.get().is_none() || self.suppress_reflow.get()

### ISSUE THREAD

**Issue by michelca** [servo/servo#18970] opened 2017-10-20 15:48 UTC
assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()
### Servo Version:
Servo 0.0.1-fe16c1d
### Backtrace:
```

WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1024×0 at (0,4820.8))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1024×0 at (0,4820.8))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1024×0 at (0,4820.8))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(NonZero(NonZero(9))) }>: stop_parsing not implemented, full speed ahead!
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1024×0 at (0,4820.8))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1024×0 at (0,4820.8))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1024×0 at (0,4820.8))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: Panic hook called.
WARNING: already borrowed: BorrowMutError
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(NonZero(NonZero(9))) }>: Panic hook called.
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(1×0 at (202.2,459.3))
ERROR: assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()

stack backtrace:
   0:        0x10d89a50e - backtrace::backtrace::trace::h255aedfedc5a51a4
   1:        0x10d89a54c - backtrace::capture::Backtrace::new::haedf38cc9f3a8a26
   2:        0x10d4babc9 - constellation::constellation::log_entry::h434e1fcb90240a43
   3:        0x10d4b9a12 - _$LT$constellation..constellation..FromCompositorLogger$u20$as$u20$log..Log$GT$::log::h7d3a86ce99a95310
   4:        0x10e510162 - log::__log::h266fe076378ff83e
   5:        0x10c513f8f - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::hc2875b4f60a2ba6f
   6:        0x10e534511 - std::panicking::rust_panic_with_hook::he6f3840a88b909da
   7:        0x10c7dde17 - std::panicking::begin_panic::h39a0e4831a6d5bba
   8:        0x10cec2c0c - script::dom::window::Window::reflow::h81fd66a30c8ccf2a
   9:        0x10cf07895 - script::script_thread::ScriptThread::handle_msgs::h0d6f99de9e568907
  10:        0x10c7d5267 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2cf15ad4f75f42c4
  11:        0x10c99fbfd - std::panicking::try::do_call::heccd43ea2522eb39
  12:        0x10e5412bc - __rust_maybe_catch_panic
  13:        0x10cae8735 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h43d9ed5c7c1be35e
  14:        0x10e5332eb - std::sys::imp::thread::Thread::new::thread_start::hf09d45f1d3cac3ae
  15:     0x7fffc041493a - _pthread_body
  16:     0x7fffc0414886 - _pthread_start
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2017-10-20 15:54
@michelca Do you know what page you were looking at?

**Comment by nox** [comment] 2019-03-23 13:24
Duplicate of #14239.

**Closed by nox** 2019-03-23 13:24 UTC
Labels: I-panic
