### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: RecvError

### ISSUE THREAD

**Issue by sbeckeriv** [servo/servo#12079] opened 2016-07-01 15:47 UTC
called `Result::unwrap()` on an `Err` value: RecvError
### URL:

http://understandsolar.com/glass-sphere/
### Backtrace:

```
frame #0  - 0x0000000102c976ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000000102c97651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000000101f68086 - _<F as alloc..boxed..FnBox<A>>::call_box::h6059122298f825d8
frame #3  - 0x0000000102c0b947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x0000000102e7f844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000000102e98786 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x0000000102e80e88 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x0000000102e983df - rust_begin_unwind
frame #8  - 0x0000000102ebf260 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x0000000101f31255 - core::result::unwrap_failed::h36b4b47aa6131a86
frame #10 - 0x0000000101f3933b - script::dom::window::Window::new::hb9c0a7c2d1d19211
frame #11 - 0x0000000101ff32b9 - script::script_thread::ScriptThread::load::hc7bd59fe3f58ffd5
frame #12 - 0x0000000101e8cee5 - script::script_thread::ScriptThread::page_headers_available::h4d14d183813e4a0b
frame #13 - 0x0000000101e88701 - _<script..dom..servohtmlparser..ParserContext as net_traits..AsyncResponseListener>::headers_available::h08671b4eed0191cf
frame #14 - 0x0000000101ff9e28 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::ha2200b1de782800b
frame #15 - 0x0000000101f7395c - script::script_thread::ScriptThread::handle_msg_from_script::hd1f5e7b2423a8c64
frame #16 - 0x0000000101fcfa71 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc67d8b381c013b79
frame #17 - 0x0000000101fb573f - script::script_thread::ScriptThread::handle_msgs::h236c5be60a207bea
frame #18 - 0x0000000101f66907 - std::panicking::try::call::h645a328f039d97c6
frame #19 - 0x0000000102e9b46b - __rust_try
frame #20 - 0x0000000102e9b405 - __rust_maybe_catch_panic
frame #21 - 0x0000000101f67ab4 - _<F as alloc..boxed..FnBox<A>>::call_box::h3db95636eb747818
frame #22 - 0x0000000102e96ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #23 - 0x00007fff978bd99c - _pthread_body
frame #24 - 0x00007fff978bd919 - _pthread_start

```

**Comment by jdm** [comment] 2016-07-01 15:58
I hit #12081 in a debug build on linux while trying to reproduce this.

**Comment by nox** [comment] 2017-10-04 08:19
I hit https://github.com/servo/servo/issues/18298 after a while, but I can't reproduce that parser-related panic. Closing.

**Closed by nox** 2017-10-04 08:19 UTC
Labels: I-panic
