### ISSUE TITLE
Crash on specific bbc.com page

### ISSUE THREAD

**Issue by tobbi** [servo/servo#12633] opened 2016-07-28 18:55 UTC
Page this crash occurs on: http://www.bbc.com/news/world-europe-36912141
OS: Mac OS X 10.

Output on console:
ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:98: document.write is not a function

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:1510: require is not defined

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:1:486: i.write is not a function

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:33: require is not defined

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:6:9: require is not defined

ERROR:js::rust: Error at http://static.bbci.co.uk/frameworks/barlesque/3.20.1/orb/4/script/orb/api.min.js:4:1: define is not defined

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:115: w.document.write is not a function

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:202: require is not defined

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:46: idcta: could not find require module

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:1:1: require is not defined

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:7567: requirejs is not defined

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:368: blqCookieContinueButton is null

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:101: require is not defined

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:2: require is not defined

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:0:2: document.write is not a function

ERROR:js::rust: Error at http://www.bbc.com/news/world-europe-36912141:61:5: define is not defined

ERROR:servo: assertion failed: allocation_size.height < max_texture_size()
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }
ERROR:servo: called `Result::unwrap()` on an `Err` value: RecvError
ERROR:servo: called `Result::unwrap()` on an `Err` value: RecvError
ERROR:servo: called `Result::unwrap()` on an `Err` value: RecvError
ERROR:servo: called `Result::unwrap()` on an `Err` value: RecvError
ERROR:servo: called `Result::unwrap()` on an `Err` value: RecvError
ERROR:servo: called `Result::unwrap()` on an `Err` value: RecvError
ERROR:servo: assertion failed: mach_sys::mach_port_mod_refs(mach_task_self(), self.port,
                             MACH_PORT_RIGHT_SEND, 1) == KERN_SUCCESS
ERROR:servo: called `Result::unwrap()` on an `Err` value: "SendError(..)"

**Comment by jdm** [comment] 2016-07-28 19:00
Looks like the first significant failure is #12192.

**Comment by nox** [comment] 2017-10-04 10:46
Closing as duplicate of #12192.

**Closed by nox** 2017-10-04 10:46 UTC
Labels: I-panic
