### ISSUE TITLE
Intermittent FAIL in /html/webappapis/update-rendering/child-document-raf-order.html

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#33413] opened 2024-09-11 23:48 UTC
```
▶ OK /html/webappapis/update-rendering/child-document-raf-order.html
  │   ▶ FAIL [expected PASS] Ordering of steps in "Update the Rendering" - child document requestAnimationFrame order
  │   │   → assert_array_equals: expected order of notifications lengths differ, expected array ["parent_raf", "first_child_raf", "second_child_raf"] length 3, got ["parent_raf", "first_child_raf", "second_child_raf", "parent_raf", "first_child_raf", "second_child_raf"] length 6
  │   │ 
  │   │ finish<@http://web-platform.test:8000/html/webappapis/update-rendering/child-document-raf-order.html:111:24
  │   │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2622:25
  │   │ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:2669:35
  └   └ step_timeout/<@[http://web-platform.test:8000/resources/testharness.js:123](http://web-platform.test:8000/resources/testharness.js:1234:18)
```
https://github.com/servo/servo/actions/runs/10818220202/job/30013678416
https://github.com/servo/servo/actions/runs/10820284136/job/30020285108
https://github.com/servo/servo/actions/runs/10816747992/job/30010289668

Presumably caused by #33395

**Comment by jdm** [comment] 2024-09-12 00:09
Duplicate of #33028.

**Closed by jdm** 2024-09-12 00:09 UTC
Labels: I-intermittent
