### ISSUE TITLE
./mach test-wpt --manifest-update causes crash on Windows

### ISSUE THREAD

**Issue by saschanaz** [servo/servo#23713] opened 2019-07-05 06:35 UTC
I ran `./mach test-wpt --manifest-update --include /css/geometry` and got:

```
  [23/24] /css/geometry/interfaces.worker.html
[A[K  ▶ CRASH [expected OK] /css/geometry/interfaces.worker.html
  │
  │ gl function was not loaded (thread main, at C:\Users\sasch\Documents\GitHub\servo\target\debug\build\gleam-357519da52645400\out/gl_bindings.rs:1497)
  │ stack backtrace:
  │    0: backtrace::backtrace::trace_unsynchronized<closure> (0x7ff78c1992d2)
  │              at C:\Users\sasch\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.26\src\backtrace\mod.rs:66
  │    1: backtrace::backtrace::trace<closure> (0x7ff78c199200)
  │              at C:\Users\sasch\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.26\src\backtrace\mod.rs:53
  │    2: backtrace::capture::Backtrace::create (0x7ff789eb8bf8)
  │              at C:\Users\sasch\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.26\src\capture.rs:163
  │    3: backtrace::capture::Backtrace::new (0x7ff789eb8b09)
  │              at C:\Users\sasch\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.26\src\capture.rs:126
  │    4: servo::main::{{closure}} (0x7ff788d83287)
  │              at C:\Users\sasch\Documents\GitHub\servo\ports\glutin\main2.rs:116
  │    5: std::panicking::rust_panic_with_hook (0x7ff78a1edae5)
  │              at /rustc/04a3dd8a872633ca1e4c217d11f741cc35cb19a5\/src\libstd\panicking.rs:479
  │    6: std::panicking::begin_panic<str*> (0x7ff78cb23931)
  │              at /rustc/04a3dd8a872633ca1e4c217d11f741cc35cb19a5\src\libstd\panicking.rs:409
  │    7: gleam::ffi_gl::missing_fn_panic (0x7ff789e03b5c)
  │              at C:\Users\sasch\Documents\GitHub\servo\target\debug\build\gleam-357519da52645400\out\gl_bindings.rs:1497
  │    8: gleam::ffi_gl::Gl::GetString (0x7ff789e06583)
  │              at C:\Users\sasch\Documents\GitHub\servo\target\debug\build\gleam-357519da52645400\out\gl_bindings.rs:3940
  │    9: gleam::gl::{{impl}}::get_string (0x7ff789df8a93)
  │              at C:\Users\sasch\.cargo\registry\src\github.com-1ecc6299db9ec823\gleam-0.6.16\src\gl_fns.rs:1757
  │   10: servo::headless_window::Window::new (0x7ff788dd4e1c)
  │              at C:\Users\sasch\Documents\GitHub\servo\ports\glutin\headless_window.rs:113
  │   11: servo::app::App::run (0x7ff788d9a1ec)
  │              at C:\Users\sasch\Documents\GitHub\servo\ports\glutin\app.rs:37
  │   12: servo::main (0x7ff788d41314)
  │              at C:\Users\sasch\Documents\GitHub\servo\ports\glutin\main2.rs:131
  │   13: std::rt::lang_start::{{closure}}<()> (0x7ff788d468e0)
  │              at /rustc/04a3dd8a872633ca1e4c217d11f741cc35cb19a5\src\libstd\rt.rs:64
  │   14: std::panicking::try::do_call<closure,i32> (0x7ff78a1ed437)
  │              at /rustc/04a3dd8a872633ca1e4c217d11f741cc35cb19a5\/src\libstd\panicking.rs:294
  │   15: panic_unwind::__rust_maybe_catch_panic (0x7ff78a1fa352)
  │              at /rustc/04a3dd8a872633ca1e4c217d11f741cc35cb19a5\/src\libpanic_unwind\lib.rs:82
  │   16: std::rt::lang_start_internal (0x7ff78a1eddf2)
  │              at /rustc/04a3dd8a872633ca1e4c217d11f741cc35cb19a5\/src\libstd\rt.rs:48
  │   17: std::rt::lang_start<()> (0x7ff788d468bb)
  │              at /rustc/04a3dd8a872633ca1e4c217d11f741cc35cb19a5\src\libstd\rt.rs:64
  │   18: main (0x7ff788d416b0)
  │   19: __scrt_common_main_seh (0x7ff7910b950c)
  │              at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  │   20: BaseThreadInitThunk (0x7ffbbf985ee4)
  └   21: RtlUserThreadStart (0x7ffbc16e32f1)

  [24/24] No tests running.
[A[KRan 24 tests finished in 15.0 seconds.
  • 0 ran as expected. 0 tests skipped.
  • 24 tests crashed unexpectedly
```

`./mach run` runs well, though.

**Comment by jdm** [comment] 2019-07-05 06:48
This is a duplicate of #20365.

**Closed by jdm** 2019-07-05 06:48 UTC
