### ISSUE TITLE
skia-sys linking  is failing on Ubuntu 14.04

### ISSUE THREAD

**Issue by alwayrun** [servo/servo#3390] opened 2014-09-17 12:46 UTC
```
Following the instruction in the readme, mach build  produce the following errors:

./mach build -v 
       Fresh string_cache_macros v0.0.0 (https://github.com/servo/string-cache#3e5a5178)
       Fresh harfbuzz v0.1.0 (https://github.com/servo/rust-harfbuzz#a502be3d)
       Fresh encoding v0.1.0 (https://github.com/lifthrasiir/rust-encoding#12b6610a)
       Fresh stb_image v0.1.0 (https://github.com/servo/rust-stb-image#f5022de4)
       Fresh macros v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh egl v0.1.0 (https://github.com/servo/rust-egl#48b85e30)
       Fresh phf_mac v0.0.0 (https://github.com/sfackler/rust-phf#fa5d8034)
       Fresh expat-sys v2.1.0 (https://github.com/servo/libexpat#da2ddaf7)
       Fresh freetype-sys v2.4.11 (https://github.com/servo/libfreetype2#5b649916)
       Fresh geom v0.1.0 (https://github.com/servo/rust-geom#2982b770)
       Fresh core_foundation v0.1.0 (https://github.com/servo/rust-core-foundation#9aeaee0b)
       Fresh opengles v0.1.0 (https://github.com/servo/rust-opengles#13cccda1)
       Fresh cocoa v0.1.0 (https://github.com/servo/rust-cocoa#f5da9ccf)
       Fresh png-sys v1.6.3 (https://github.com/servo/libpng?ref=servo#d01f32b4)
       Fresh link_glfw v0.1.0 (file:///home/alwayrun/browser/servo/support/glfw-rs)
       Fresh xlib v0.1.0 (https://github.com/servo/rust-xlib#79904fb4)
       Fresh task_info v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh mozjs-sys v0.0.0 (https://github.com/servo/mozjs#47cd6a4e)
       Fresh freetype v0.1.0 (https://github.com/servo/rust-freetype#fb15dd30)
       Fresh semver v0.0.1 (https://github.com/rust-lang/semver#df163f7b)
       Fresh openssl v0.0.0 (https://github.com/sfackler/rust-openssl.git#cd40d25c)
       Fresh parserutils-sys v0.1.1 (http://github.com/servo/libparserutils#651b636b)
       Fresh phf v0.0.0 (https://github.com/sfackler/rust-phf#fa5d8034)
       Fresh cssparser v0.1.0 (https://github.com/servo/rust-cssparser#42346400)
       Fresh url v0.1.0 (https://github.com/servo/rust-url#678bb4d5)
       Fresh core_graphics v0.1.0 (https://github.com/servo/rust-core-graphics#04bd18a4)
       Fresh skia-sys v0.0.20130412 (https://github.com/servo/skia#6d696712)
       Fresh fontconfig-sys v2.11.1 (https://github.com/servo/libfontconfig#fcc324d2)
       Fresh io_surface v0.1.0 (https://github.com/servo/rust-io-surface#05f10227)
       Fresh glut v0.0.1 (https://github.com/servo/rust-glut#d351eed4)
       Fresh alert v0.1.0 (https://github.com/servo/rust-alert#fdc24f13)
       Fresh png v0.1.0 (https://github.com/servo/rust-png#f3640b37)
       Fresh glfw v0.0.1 (file:///home/alwayrun/browser/servo/support/glfw-rs)
       Fresh js v0.1.0 (https://github.com/servo/rust-mozjs#c9bd6794)
       Fresh string_cache v0.0.0 (https://github.com/servo/string-cache#3e5a5178)
       Fresh hubbub-sys v0.1.2 (https://github.com/servo/libhubbub#6d098939)
       Fresh http v0.1.0-pre (https://github.com/servo/rust-http?ref=servo#13be91d9)
       Fresh core_text v0.1.0 (https://github.com/servo/rust-core-text#e2280222)
       Fresh layers v0.1.0 (https://github.com/servo/rust-layers#e29c5cd6)
       Fresh fontconfig v0.1.0 (https://github.com/servo/rust-fontconfig#6e02b6df)
       Fresh hubbub v0.1.0 (https://github.com/servo/rust-hubbub#c7f868e6)
       Fresh azure v0.1.0 (https://github.com/servo/rust-azure#9c5567b7)
       Fresh util v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh canvas v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh net v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh style v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh msg v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh gfx v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh script_traits v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh script v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh layout_traits v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh compositing v0.0.1 (file:///home/alwayrun/browser/servo)
       Fresh layout v0.0.1 (file:///home/alwayrun/browser/servo)
   Compiling servo v0.0.1 (file:///home/alwayrun/browser/servo)
 Running `rustc /home/alwayrun/browser/servo/src/main.rs --crate-name servo --crate-type bin -g --out-dir /home/alwayrun/browser/servo/target --dep-info /home/alwayrun/browser/servo/target/.fingerprint/servo-506cbc382e949f6a/dep-bin-servo -L /home/alwayrun/browser/servo/target -L /home/alwayrun/browser/servo/target/deps -L /home/alwayrun/browser/servo/target/native/azure-c41fbdcb7d8a35a8 -L /home/alwayrun/browser/servo/target/native/skia-sys-b4948f12eb455974 -L /home/alwayrun/browser/servo/target/native/expat-sys-960770ff581995ad -L /home/alwayrun/browser/servo/target/native/freetype-sys-09026e63257b2d26 -L /home/alwayrun/browser/servo/target/native/stb_image-6bac4bc302c7b4cb -L /home/alwayrun/browser/servo/target/native/task_info-c42fa61add5958ed -L /home/alwayrun/browser/servo/target/native/harfbuzz-83108d8b680b02f7 -L /home/alwayrun/browser/servo/target/native/png-31ffcc7fd7a950a8 -L /home/alwayrun/browser/servo/target/native/png-sys-3be9132c97a4a742 -L /home/alwayrun/browser/servo/target/native/fontconfig-sys-e07b0ca12ad9ea2a -L /home/alwayrun/browser/servo/target/native/style-6b0d88feabee576d -L /home/alwayrun/browser/servo/target/native/http-116f6c0d86ba411c -L /home/alwayrun/browser/servo/target/native/script-577a0ca037baec96 -L /home/alwayrun/browser/servo/target/native/hubbub-sys-0550cdca641790e1 -L /home/alwayrun/browser/servo/target/native/parserutils-sys-7a046be7954d112f -L /home/alwayrun/browser/servo/target/native/js-e564e19f78ac0475 -L /home/alwayrun/browser/servo/target/native/mozjs-sys-f0dc8e6bc658bdbe -L /home/alwayrun/browser/servo/target/native/glut-2758ad400cdfce8d -L /home/alwayrun/browser/servo/target/native/cocoa-c5f608a9b81ea800 --extern gfx=/home/alwayrun/browser/servo/target/deps/libgfx-4666f50622da4c52.rlib --extern url=/home/alwayrun/browser/servo/target/deps/liburl-f240ab718dc73e52.rlib --extern msg=/home/alwayrun/browser/servo/target/deps/libmsg-8a341ffcd719ee9b.rlib --extern util=/home/alwayrun/browser/servo/target/deps/libutil-e0a292a423a6378f.rlib --extern layout=/home/alwayrun/browser/servo/target/deps/liblayout-ac8a66d96015ea79.rlib --extern compositing=/home/alwayrun/browser/servo/target/deps/libcompositing-5171d9e7044d54d3.rlib --extern net=/home/alwayrun/browser/servo/target/deps/libnet-f78301101caca056.rlib --extern script=/home/alwayrun/browser/servo/target/deps/libscript-577a0ca037baec96.rlib --extern servo=/home/alwayrun/browser/servo/target/libservo-506cbc382e949f6a.so --extern servo=/home/alwayrun/browser/servo/target/libservo-506cbc382e949f6a.rlib`
error: linking with `cc` failed: exit code: 1
note: cc '-m32' '-L' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib' '-o' '/home/alwayrun/browser/servo/target/servo' '/home/alwayrun/browser/servo/target/servo.o' '-Wl,--whole-archive' '-lmorestack' '-Wl,--no-whole-archive' '-nodefaultlibs' '-Wl,--gc-sections' '-Wl,--as-needed' '/home/alwayrun/browser/servo/target/libservo-506cbc382e949f6a.rlib' '/home/alwayrun/browser/servo/target/deps/libcompositing-5171d9e7044d54d3.rlib' '/home/alwayrun/browser/servo/target/deps/libalert-be8877fc86877da2.rlib' '/home/alwayrun/browser/servo/target/deps/liblayout-ac8a66d96015ea79.rlib' '/home/alwayrun/browser/servo/target/deps/liblayout_traits-b393f621a30f0204.rlib' '/home/alwayrun/browser/servo/target/deps/libgfx-4666f50622da4c52.rlib' '/home/alwayrun/browser/servo/target/deps/libfontconfig-9abe50e85852e50a.rlib' '/home/alwayrun/browser/servo/target/deps/libharfbuzz-83108d8b680b02f7.rlib' '/home/alwayrun/browser/servo/target/deps/libscript-577a0ca037baec96.rlib' '/home/alwayrun/browser/servo/target/deps/libstyle-6b0d88feabee576d.rlib' '/home/alwayrun/browser/servo/target/deps/libjs-e564e19f78ac0475.rlib' '/home/alwayrun/browser/servo/target/deps/libcssparser-8d42871cc27aaf79.rlib' '/home/alwayrun/browser/servo/target/deps/libcanvas-6f73145f85b74ab3.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libnum-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libgreen-4e7c5e5c.rlib' '/home/alwayrun/browser/servo/target/deps/libhubbub-09d42dd1431ea644.rlib' '/home/alwayrun/browser/servo/target/deps/libscript_traits-d6e4fdc6a8227363.rlib' '/home/alwayrun/browser/servo/target/deps/libmsg-8a341ffcd719ee9b.rlib' '/home/alwayrun/browser/servo/target/deps/libnet-f78301101caca056.rlib' '/home/alwayrun/browser/servo/target/deps/libpng-31ffcc7fd7a950a8.rlib' '/home/alwayrun/browser/servo/target/deps/libutil-e0a292a423a6378f.rlib' '/home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib' '/home/alwayrun/browser/servo/target/deps/libstring_cache-d6c0c32f0a86dfd3.rlib' '/home/alwayrun/browser/servo/target/deps/liblayers-cd2d9de149203322.rlib' '/home/alwayrun/browser/servo/target/deps/libxlib-018345a79ab0592f.rlib' '/home/alwayrun/browser/servo/target/deps/libgeom-0155f508111f5b06.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libnative-4e7c5e5c.rlib' '/home/alwayrun/browser/servo/target/deps/libhttp-116f6c0d86ba411c.rlib' '/home/alwayrun/browser/servo/target/deps/libfreetype-4cd7f4afad7b1066.rlib' '/home/alwayrun/browser/servo/target/deps/liburl-f240ab718dc73e52.rlib' '/home/alwayrun/browser/servo/target/deps/libencoding-c1d6b666cb4ac9e8.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libdebug-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libtest-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libgetopts-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libregex-4e7c5e5c.rlib' '/home/alwayrun/browser/servo/target/deps/libglfw-c167cbe64c0ca6f1.rlib' '/home/alwayrun/browser/servo/target/deps/libsemver-ee0fdf771b0e1274.rlib' '/home/alwayrun/browser/servo/target/deps/libphf-1ce973d9394705fb.rlib' '/home/alwayrun/browser/servo/target/deps/libopenssl-f591436d05d56a5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/librustuv-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libtime-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libserialize-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libterm-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/liblog-4e7c5e5c.rlib' '/home/alwayrun/browser/servo/target/deps/libstb_image-6bac4bc302c7b4cb.rlib' '/home/alwayrun/browser/servo/target/deps/libopengles-766bf643cefe8d2c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libstd-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libsync-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/librustrt-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libcollections-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libunicode-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/liblibc-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/librand-4e7c5e5c.rlib' '/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib/libcore-4e7c5e5c.rlib' '-L' '/home/alwayrun/browser/servo/target/native/harfbuzz-83108d8b680b02f7' '-L' '/home/alwayrun/browser/servo/target/native/azure-c41fbdcb7d8a35a8' '-L' '/home/alwayrun/browser/servo/target/native/script-577a0ca037baec96' '-L' '/home/alwayrun/browser/servo/target/native/js-e564e19f78ac0475' '-L' '/home/alwayrun/browser/servo/target/deps' '-L' '/home/alwayrun/browser/servo/target/native/parserutils-sys-7a046be7954d112f' '-L' '/home/alwayrun/browser/servo/target/native/fontconfig-sys-e07b0ca12ad9ea2a' '-L' '/home/alwayrun/browser/servo/target/native/task_info-c42fa61add5958ed' '-L' '/home/alwayrun/browser/servo/target/native/glut-2758ad400cdfce8d' '-L' '/home/alwayrun/browser/servo/target/native/stb_image-6bac4bc302c7b4cb' '-L' '/home/alwayrun/browser/servo/target/native/skia-sys-b4948f12eb455974' '-L' '/home/alwayrun/browser/servo/target/native/style-6b0d88feabee576d' '-L' '/home/alwayrun/browser/servo/target/native/png-31ffcc7fd7a950a8' '-L' '/home/alwayrun/browser/servo/target/native/mozjs-sys-f0dc8e6bc658bdbe' '-L' '/home/alwayrun/browser/servo/target/native/freetype-sys-09026e63257b2d26' '-L' '/home/alwayrun/browser/servo/target/native/expat-sys-960770ff581995ad' '-L' '/home/alwayrun/browser/servo/target' '-L' '/home/alwayrun/browser/servo/target/native/png-sys-3be9132c97a4a742' '-L' '/home/alwayrun/browser/servo/target/native/http-116f6c0d86ba411c' '-L' '/home/alwayrun/browser/servo/target/native/hubbub-sys-0550cdca641790e1' '-L' '/home/alwayrun/browser/servo/target/native/cocoa-c5f608a9b81ea800' '-L' '/home/alwayrun/browser/servo/.rust' '-L' '/home/alwayrun/browser/servo' '-Wl,-Bdynamic' '-lc' '-lfontconfig' '-lc' '-lglib-2.0' '-lstdc++' '-lpthread' '-lstdc++' '-lz' '-ljsglue' '-lz' '-lstdc++' '-lfreetype' '-lfontconfig' '-lexpat' '-lX11' '-lazure' '-lX11' '-lfreetype' '-lglfw3' '-lrt' '-lXrandr' '-lXi' '-lGL' '-lm' '-ldl' '-lXrender' '-ldrm' '-lXdamage' '-lX11-xcb' '-lxcb-glx' '-lxcb-dri2' '-lxcb-dri3' '-lxcb-present' '-lxcb-sync' '-lxshmfence' '-lXxf86vm' '-lXfixes' '-lXext' '-lX11' '-lpthread' '-lxcb' '-lXau' '-lXdmcp' '-lssl' '-lcrypto' '-lcrypto' '-lcrypto' '-lcrypto' '-lcrypto' '-lcrypto' '-lcrypto' '-lcrypto' '-lpthread' '-lrt' '-lrt' '-lGL' '-ldl' '-lpthread' '-lgcc_s' '-lpthread' '-lc' '-lm' '-lcompiler-rt'
note: /home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib(lldb-fix-r-skia-SkUtils.o): In function `sk_memset16_stub(unsigned short*, unsigned short, int)':
SkUtils.cpp:(.text+0x188): undefined reference to `SkMemset16GetPlatformProc()'
/home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib(lldb-fix-r-skia-SkUtils.o): In function `sk_memset32_stub(unsigned int*, unsigned int, int)':
SkUtils.cpp:(.text+0x1d0): undefined reference to `SkMemset32GetPlatformProc()'
/home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib(r-skia-SkBlitRow_D32.o): In function `SkBlitRow::Factory32(unsigned int)':
SkBlitRow_D32.cpp:(.text+0xd9b): undefined reference to `SkBlitRow::PlatformProcs32(unsigned int)'
/home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib(r-skia-SkBlitRow_D32.o): In function `SkBlitRow::ColorProcFactory()':
SkBlitRow_D32.cpp:(.text+0xdd0): undefined reference to `SkBlitRow::PlatformColorProc()'
/home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib(r-skia-SkBlitRow_D32.o): In function `SkBlitRow::ColorRectProcFactory()':
SkBlitRow_D32.cpp:(.text+0xfe0): undefined reference to `PlatformColorRectProcFactory()'
/home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib(r-skia-SkBlitMask_D32.o): In function `SkBlitMask::BlitLCD16RowFactory(bool)':
SkBlitMask_D32.cpp:(.text+0x200d): undefined reference to `SkBlitMask::PlatformBlitRowProcs16(bool)'
/home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib(r-skia-SkBlitMask_D32.o): In function `SkBlitMask::ColorFactory(SkBitmap::Config, SkMask::Format, unsigned int)':
SkBlitMask_D32.cpp:(.text+0x212a): undefined reference to `SkBlitMask::PlatformColorProcs(SkBitmap::Config, SkMask::Format, unsigned int)'
/home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib(r-skia-SkBlitMask_D32.o): In function `SkBlitMask::RowFactory(SkBitmap::Config, SkMask::Format, SkBlitMask::RowFlags)':
SkBlitMask_D32.cpp:(.text+0x22aa): undefined reference to `SkBlitMask::PlatformRowProcs(SkBitmap::Config, SkMask::Format, SkBlitMask::RowFlags)'
/home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib(r-skia-SkBlitRow_D16.o): In function `SkBlitRow::Factory(unsigned int, SkBitmap::Config)':
SkBlitRow_D16.cpp:(.text+0x10a4): undefined reference to `SkBlitRow::PlatformProcs4444(unsigned int)'
SkBlitRow_D16.cpp:(.text+0x10bc): undefined reference to `SkBlitRow::PlatformProcs565(unsigned int)'
/home/alwayrun/browser/servo/target/deps/libazure-c41fbdcb7d8a35a8.rlib(r-skia-SkBitmapProcState.o): In function `.L577':
SkBitmapProcState.cpp:(.text+0x636d): undefined reference to `SkBitmapProcState::platformProcs()'
collect2: error: ld returned 1 exit status

error: aborting due to previous error
Could not compile `servo`.


Caused by:
  Process didn't exit successfully: `rustc /home/alwayrun/browser/servo/src/main.rs --crate-name servo --crate-type bin -g --out-dir /home/alwayrun/browser/servo/target --dep-info /home/alwayrun/browser/servo/target/.fingerprint/servo-506cbc382e949f6a/dep-bin-servo -L /home/alwayrun/browser/servo/target -L /home/alwayrun/browser/servo/target/deps -L /home/alwayrun/browser/servo/target/native/azure-c41fbdcb7d8a35a8 -L /home/alwayrun/browser/servo/target/native/skia-sys-b4948f12eb455974 -L /home/alwayrun/browser/servo/target/native/expat-sys-960770ff581995ad -L /home/alwayrun/browser/servo/target/native/freetype-sys-09026e63257b2d26 -L /home/alwayrun/browser/servo/target/native/stb_image-6bac4bc302c7b4cb -L /home/alwayrun/browser/servo/target/native/task_info-c42fa61add5958ed -L /home/alwayrun/browser/servo/target/native/harfbuzz-83108d8b680b02f7 -L /home/alwayrun/browser/servo/target/native/png-31ffcc7fd7a950a8 -L /home/alwayrun/browser/servo/target/native/png-sys-3be9132c97a4a742 -L /home/alwayrun/browser/servo/target/native/fontconfig-sys-e07b0ca12ad9ea2a -L /home/alwayrun/browser/servo/target/native/style-6b0d88feabee576d -L /home/alwayrun/browser/servo/target/native/http-116f6c0d86ba411c -L /home/alwayrun/browser/servo/target/native/script-577a0ca037baec96 -L /home/alwayrun/browser/servo/target/native/hubbub-sys-0550cdca641790e1 -L /home/alwayrun/browser/servo/target/native/parserutils-sys-7a046be7954d112f -L /home/alwayrun/browser/servo/target/native/js-e564e19f78ac0475 -L /home/alwayrun/browser/servo/target/native/mozjs-sys-f0dc8e6bc658bdbe -L /home/alwayrun/browser/servo/target/native/glut-2758ad400cdfce8d -L /home/alwayrun/browser/servo/target/native/cocoa-c5f608a9b81ea800 --extern gfx=/home/alwayrun/browser/servo/target/deps/libgfx-4666f50622da4c52.rlib --extern url=/home/alwayrun/browser/servo/target/deps/liburl-f240ab718dc73e52.rlib --extern msg=/home/alwayrun/browser/servo/target/deps/libmsg-8a341ffcd719ee9b.rlib --extern util=/home/alwayrun/browser/servo/target/deps/libutil-e0a292a423a6378f.rlib --extern layout=/home/alwayrun/browser/servo/target/deps/liblayout-ac8a66d96015ea79.rlib --extern compositing=/home/alwayrun/browser/servo/target/deps/libcompositing-5171d9e7044d54d3.rlib --extern net=/home/alwayrun/browser/servo/target/deps/libnet-f78301101caca056.rlib --extern script=/home/alwayrun/browser/servo/target/deps/libscript-577a0ca037baec96.rlib --extern servo=/home/alwayrun/browser/servo/target/libservo-506cbc382e949f6a.so --extern servo=/home/alwayrun/browser/servo/target/libservo-506cbc382e949f6a.rlib` (status=101)
Build completed in 15.62s
```

I am running Ubuntu 14.04 32b. Do you need more information?

**Comment by mbrubeck** [comment] 2016-05-20 04:36
maybe duplicate of #5216?

**Closed by mbrubeck** 2016-05-20 04:36 UTC
Labels: A-build, C-is-this-done
