### ISSUE TITLE
Black screen on Nvidia drivers

### ISSUE THREAD

**Issue by ergpopler** [servo/servo#27744] opened 2020-11-08 02:31 UTC
![servo-pic](https://user-images.githubusercontent.com/64165309/98455547-1fcbb700-2140-11eb-9f0c-78fedc6546a2.png)

As you can see I just get a black screen on the proprietary Nvidia drivers, but with the nouavou(i cant spell it lol) drivers it does work.

I have tried compiling from source & downloaded from https://dl.servo.org 
Both ways result in the same black screen.

I can still interact with the website though. :cry:

**Comment by Darkspirit** [comment] 2020-11-08 02:52
Thanks for the report! This is a duplicate of #26353.

**Comment by ergpopler** [comment] 2020-11-08 03:45
Not exactly, the comments on that one say that the one from https://dl.servo.org work on the nvidia drivers, which they do not.

#27743 fixed the problem for me though :sunglasses:

**Comment by CYBAI** [comment] 2020-11-08 15:12
> #27743 fixed the problem for me though 😎

Per above comment and #27743 merged, let me close this issue. Thanks for the report!

**Closed by CYBAI** 2020-11-08 15:12 UTC
