### ISSUE TITLE
Integrate libsimpleservo into magic leap port

### ISSUE THREAD

**Issue by jdm** [servo/servo#22065] opened 2018-10-31 14:54 UTC
I was able to get a build which links with the following diff:
```diff
diff --git a/Cargo.lock b/Cargo.lock
index 1058bfdac3..77ce164f99 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1906,6 +1906,7 @@ name = "libmlservo"
 version = "0.0.1"
 dependencies = [
  "libservo 0.0.1",
+ "libsimpleservo 0.0.1",
  "log 0.4.5 (registry+https://github.com/rust-lang/crates.io-index)",
  "servo-egl 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)",
  "smallvec 0.6.3 (registry+https://github.com/rust-lang/crates.io-index)",
diff --git a/ports/libmlservo/Cargo.toml b/ports/libmlservo/Cargo.toml
index 793435db09..f66bfab03c 100644
--- a/ports/libmlservo/Cargo.toml
+++ b/ports/libmlservo/Cargo.toml
@@ -13,6 +13,7 @@ bench = false

 [dependencies]
 libservo = { path = "../../components/servo" }
+libsimpleservo = { path = "../libsimpleservo" }
 log = "0.4"
 servo-egl = "0.2"
 smallvec = "0.6"
diff --git a/ports/libmlservo/src/lib.rs b/ports/libmlservo/src/lib.rs
index 08b84ada37..9188dfffa9 100644
--- a/ports/libmlservo/src/lib.rs
+++ b/ports/libmlservo/src/lib.rs
@@ -3,6 +3,7 @@
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

 extern crate egl;
+extern crate simpleservo;
 #[macro_use] extern crate log;
 extern crate servo;
 extern crate smallvec;
diff --git a/ports/libsimpleservo/Cargo.toml b/ports/libsimpleservo/Cargo.toml
index 5af57fe8e6..f942871baf 100644
--- a/ports/libsimpleservo/Cargo.toml
+++ b/ports/libsimpleservo/Cargo.toml
@@ -8,7 +8,7 @@ publish = false

 [lib]
 name = "simpleservo"
-crate-type = ["cdylib"]
+#crate-type = ["cdylib"]
 test = false
 bench = false

diff --git a/ports/libsimpleservo/build.rs b/ports/libsimpleservo/build.rs
index 0ba96d6b7a..60366c9c59 100644
--- a/ports/libsimpleservo/build.rs
+++ b/ports/libsimpleservo/build.rs
@@ -12,7 +12,7 @@ use std::path::Path;

 fn main() {
     let target = env::var("TARGET").unwrap();
-    if target.contains("android") {
+    if target.contains("android") && env::var("SERVO_FAKE_ANDROID").is_err() {
         android_main()
     }
     generate_gl_bindings(&target);
```
If libsimpleservo is a cdylib, libmlservo can't find it because the rustc commandline doesn't include an `--extern simpleservo=...` line.

**Comment by jdm** [comment] 2018-10-31 14:55
@asajeffrey Is there a best practice for identifying if we're building for a real android platform or a fake one like ML?

**Comment by asajeffrey** [comment] 2018-10-31 15:24
@jdm Add a `magicleap` feature to the crate?

**Comment by asajeffrey** [comment] 2018-10-31 15:25
Dupe of #22041?

**Comment by jdm** [comment] 2019-01-25 16:59
I have a branch that compiles but is not yet tested.

**Comment by paulrouget** [comment] 2019-01-26 09:42
I haven't looked at the libmlservo changes, but for the other changes, it looks good to me.

**Closed** 2019-03-04 20:14 UTC
Labels: A-embedding, I-refactor, P-magic leap
