### ISSUE TITLE
The mozbrowserlocationchanged event property should be url, not uri

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#11450] opened 2016-05-26 19:55 UTC
The documentation at https://developer.mozilla.org/en-US/docs/Web/Events/mozbrowserlocationchange describes the details object has having property:

**url** The URL of the new location

but our implementation https://github.com/servo/servo/blob/master/components/script/dom/webidls/BrowserElement.webidl#L66 has a property **uri**.

**Comment by Coder206** [comment] 2016-05-26 19:57
I want to try and fix this

**Comment by ConnorGBrewster** [comment] 2016-05-26 19:57
@Coder206 go for it :)

**Comment by Coder206** [comment] 2016-05-26 19:59
@asajeffrey I change the value DOMString uri; to DOMString url; Is this what you were looking for?

**Comment by asajeffrey** [comment] 2016-05-26 20:03
@Coder206 try it and see :)

Once you've built with `./mach build -r` you'll want to run:
```
./mach test-wpt --release _mozilla/mozilla/mozbrowser
```

You'll probably get a failure, caused by https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowserlocationchange_event.html#L42, you should edit that test to also use url rather than uri.

**Comment by asajeffrey** [comment] 2016-05-26 20:04
By the way, congratulations on being so quick on the draw!

**Comment by Coder206** [comment] 2016-05-26 20:05
@asajeffrey Thanks I was really eager to help out.

**Comment by asajeffrey** [comment] 2016-05-26 20:06
@Coder206 let me know if you hit any problems.

There might be some other `uri`s that should be `url`s, feel free to fix those too :)

**Comment by Coder206** [comment] 2016-05-26 20:06
@asajeffrey So I should also change that second page line 42?

**Comment by Coder206** [comment] 2016-05-26 20:06
@asajeffrey Ok perfect! On it! Just compiling rust right now and trying it for a first time

**Comment by asajeffrey** [comment] 2016-05-26 20:07
Try running the tests without changes, just to make sure they fail, then edit mozbrowserlocationchange_event.html and see if you can get the test to pass again.

**Comment by Coder206** [comment] 2016-05-26 20:07
@asajeffrey Sounds good

**Comment by asajeffrey** [comment] 2016-05-26 20:12
Make sure you mention this issue (#11450) when you file your PR, so that I'll see it.

**Comment by Coder206** [comment] 2016-05-26 20:16
@asajeffrey Ok sounds good! Thanks for your help! I'll get it to you as soon as I can.

**Comment by Coder206** [comment] 2016-05-30 23:52
@asajeffrey I hope you are doing well. I would like and appreciate a little assistance as I am just getting familiar with the workflow I modified the code as you requested and came upon this error. Please note in order to even build the code, I had to make a few modifications elsewhere, in the /htmliframeelement.rs file (line 345, 347 - change uri to url) and comment out line 5 in bluetoothremotegattservice.rs as it was giving a warning and the compiling seemed to have came to a stand still, then:
I came up with this error when I tried the test that you pasted above:

> > CalledProcessError: Command '[u'/mingw64/bin/openssl', 'req', '-config', '/tmp/tmpcb9EuN/openssl.cfg', '-batch', '-new', '-newkey', 'rsa:2048', '-keyout', '/tmp/tmpcb9EuN/cakey.pem', '-out', '/tmp/tmpcb9EuN/careq.pem', '-subj', '/CN=web-platform-tests', '-passout', 'pass:web-platform-tests']' returned non-zero exit status 1
> 
>   File "/f/files/dev/github/servo/python/servo/testing_commands.py", line 315, in test_wpt
>     return self.wptrunner(run_file, **kwargs)
>   File "/f/files/dev/github/servo/python/servo/testing_commands.py", line 335, in wptrunner
>     return run_globals["run_tests"](**kwargs)
>   File "/f/files/dev/github/servo/tests/wpt/run_wpt.py", line 13, in run_tests
>     return run.run_tests(paths=paths, **kwargs)
>   File "/f/files/dev/github/servo/tests/wpt/run.py", line 36, in run_tests
>     success = wptrunner.run_tests(**kwargs)
>   File "/f/files/dev/github/servo/tests/wpt/harness/wptrunner/wptrunner.py", line 155, in run_tests
>     env_options) as test_environment:
>   File "/f/files/dev/github/servo/tests/wpt/harness/wptrunner/environment.py", line 104, in __enter__
>     self.config = self.load_config()
>   File "/f/files/dev/github/servo/tests/wpt/harness/wptrunner/environment.py", line 152, in load_config
>     key_file, certificate = self.ssl_env.host_cert_path(hosts)
>   File "/f/files/dev/github/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 350, in host_cert_path
>     key, cert = self._generate_host_cert(hosts)
>   File "/f/files/dev/github/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 370, in _generate_host_cert
>     self._generate_ca()
>   File "/f/files/dev/github/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 321, in _generate_ca
>     "-passout", "pass:%s" % self.password)
>   File "/f/files/dev/github/servo/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 69, in __call__
>     output=stdout)

Do you have any recommendations/insight/ideas for a next step?

**Comment by jdm** [comment] 2016-05-31 01:22
Oh, I recall seeing other people have difficulties running tests on Windows. @jgraham does ^ look familiar?

**Comment by Coder206** [comment] 2016-05-31 01:39
@jdm Thanks for the heads up!

**Comment by Coder206** [comment] 2016-05-31 01:40
@jdm I am looking forward to having Ubuntu shell in Windows, it will make life simpler (hopefully)...

**Comment by jgraham** [comment] 2016-05-31 12:52
Yeah. If you don't need to test https things, you could try passing in `--ssl-type=none` when you start the tests. Otherwise you might need to install the shining light ssl server, as documented in the [wpt readme](https://github.com/w3c/web-platform-tests#windows-notes). However there may still be difficulties getting paths in the right format, in particular one vs two `\` in the config file paths.

Having said all of that, I'm surprised servo doesn't have some pregenerated certs checked in to the tree somewhere, like gecko. Am I missing them, is there some reason it doesn't work well, or is this an oversight?

**Comment by asajeffrey** [comment] 2016-05-31 13:55
@Coder206 oh you may be hitting problems because the windows build path is quite a bit less explored than the linux or mac build path. As @jgraham suggested, you could try switching off ssl via:
```
./mach build -r
./mach test-wpt --release --ssl-type=none
```
I'd be keen to see your PR even if you can't run the wpt tests yourself, it will be run by the build servers anyway.

Ah computers :)

**Comment by Coder206** [comment] 2016-05-31 21:26
@jgraham @asajeffrey Thank you very much for this. However, it actually lead to more errors I think. (The text was flowing by quickly - couldn't read) I am now hunting those URIs...

**Comment by jdm** [comment] 2016-05-31 21:32
Note that `./mach test-wpt --release --ssl-type=none` will run _all_ the WPT tests, which is overkill in this situation. It should be enough to run `./mach test-wpt --release --ssl-type=none tests/wpt/mozilla/tests/mozilla/mozbrowser/`.

**Comment by Coder206** [comment] 2016-05-31 21:36
@jdm Thanks!

**Comment by Coder206** [comment] 2016-05-31 22:39
@jdm @asajeffrey Is the servo/test/wpt/css-tests/css21_dev/html4 folder full of miswritten CSS code on purpose for testing?

**Comment by jgraham** [comment] 2016-05-31 22:45
Yes, that's the CSS 2.1 testsuite.

**Comment by Coder206** [comment] 2016-05-31 22:49
@jgraham Thanks, I had that in my editor, I thought: "How can this be right, people working on a web engine that have bad syntax.". I accidentally made some changes on some of them, I will restore them.

**Comment by Coder206** [comment] 2016-06-01 00:24
@asajeffrey @jdm @jgraham Please close find my fix for this issue in the PR area

**Comment by paulrouget** [comment] 2016-06-01 01:26
When this lands, please make sure to also fix browser.html: https://github.com/browserhtml/browserhtml/blob/f5b9eabeae6a2416f1049a8b6f76e9bdeb8decdc/src/browser/Navigators/Navigator/WebView/MozBrowserFrame.js#L188

**Comment by Coder206** [comment] 2016-06-01 01:48
@paulrouget Thanks for the tip :)

**Comment by Coder206** [comment] 2016-06-01 02:00
@paulrouget So I will do two PRs, one for Servo, and one for browser.html?

**Comment by paulrouget** [comment] 2016-06-01 02:09
@Coder206 If you can, yes. Otherwise, I can take care of the one in browserhtml.

**Comment by Coder206** [comment] 2016-06-01 02:12
@paulrouget Sounds good. I will work on both browser.html and servo

**Comment by Coder206** [comment] 2016-06-02 20:00
@paulrouget Is browserhtml able to run on Windows 10?

**Comment by metajack** [comment] 2016-06-02 20:02
It runs without `-b` so it looks like OS X, but it works well in my testing.

**Comment by Coder206** [comment] 2016-06-02 20:03
@metajack I am having lots of trouble getting things to work.

**Comment by Coder206** [comment] 2016-06-02 20:06
@metajack Where do I put this line of code: ./mach run -r -- -b -w --resolution=1024x720 --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref dom.quit-on-escape.enabled=false http://localhost:6060 
because npm build-server never ends...

**Comment by metajack** [comment] 2016-06-02 20:14
You have to run npm build-server in another console. It starts a local webserver to serve the content for browserhtml. Then you run servo locaing from that local server.

Alternatively you can run npm run dist or whatever makes the static files and point servo at those. build-server is more useful if you are changing browser.html code since it auto-recompiles to serve the latest version.

**Comment by Coder206** [comment] 2016-06-02 20:38
I getting "Build failed, waiting for other jobs to finish..." around the time of "Compiling webdriver_server v0.0.1 + directory". This is for Servo.

**Comment by KiChjang** [comment] 2016-06-02 20:44
Did you run `./mach build -r` before doing `./mach run -r`?

Also, I suggest focusing on getting your changes in servo merged before working on browser.html stuff. That would give you feedback on how to correctly rename `uri` into `url`. Thanks!

**Comment by Coder206** [comment] 2016-06-02 20:49
@KiChjang It will be hard to do changes on anything on Servo for me now. I am having lots of difficulty compiling and getting things working. It takes me 18 - 25 mins to compile.  
This is only a fraction of the message I received from the compiler when typing ./mach build --release:
"  Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#2af5849a)
   Compiling devtools v0.0.1 (file:///E:/files/dev/github/servo/components/devtools)
   Compiling net v0.0.1 (file:///E:/files/dev/github/servo/components/net)
   Compiling layout_traits v0.0.1 (file:///E:/files/dev/github/servo/components/layout_traits)
   Compiling compositing v0.0.1 (file:///E:/files/dev/github/servo/components/compositing)
   Compiling glutin_app v0.0.1 (file:///E:/files/dev/github/servo/ports/glutin)
   Compiling constellation v0.0.1 (file:///E:/files/dev/github/servo/components/constellation)
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#2af5849a)`"

+ More things that I believe are mach related

**Comment by Coder206** [comment] 2016-06-02 20:51
@KiChjang I deleted the repo on my HDD and cloned it again, the results above are the outcome of a recent clone of 30 mins ago

**Comment by metajack** [comment] 2016-06-02 20:56
How much memory do you have? Have you tried ./mach build -r -j1?

**Comment by Coder206** [comment] 2016-06-02 20:57
I have a 16GB DDR3 memory, and Servo is on a 3Tb HDD

**Comment by metajack** [comment] 2016-06-02 20:58
The output of `./mach build -r -v -j1` might help us track it down. You certainly have enough memory that it shouldn't be that.

**Comment by Coder206** [comment] 2016-06-02 21:03
@metajack I will get back to you with the result of the output.

**Comment by Coder206** [comment] 2016-06-03 01:37
@metajack This is the summary of the failed Servo build. 
"Caused by:
  Process didn't exit successfully: `rustc main.rs --crate-name servo --crate-type bin -C opt-level=3 --cfg feature="webdriver" --cfg feature="webdriver_server" --cfg feature="glutin_app" --cfg feature="max_log_level" --cfg feature="default" --cfg feature="log" --out-dir E:/files/dev/github/servo/target\release --emit=dep-info,link -L dependency=E:/files/dev/github/servo/target\release -L dependency=E:/files/dev/github/servo/target\release\deps --extern style=E:/files/dev/github/servo/target\release\deps\libstyle-eecfbd23e69a1b95.rlib --extern webrender=E:/files/dev/github/servo/target\release\deps\libwebrender-911bab56a6ff1f0e.rlib --extern log=E:/files/dev/github/servo/target\release\deps\liblog-bf16bb9a4912b11d.rlib --extern profile=E:/files/dev/github/servo/target\release\deps\libprofile-f7bf854193c345e8.rlib --extern profile_traits=E:/files/dev/github/servo/target\release\deps\libprofile_traits-a8397508e08d2aaf.rlib --extern devtools_traits=E:/files/dev/github/servo/target\release\deps\libdevtools_traits-4a38e065075839b0.rlib --extern gfx=E:/files/dev/github/servo/target\release\deps\libgfx-430083178b26c50d.rlib --extern script=E:/files/dev/github/servo/target\release\deps\libscript-e6e09f53d5ad9e9b.rlib --extern ipc_channel=E:/files/dev/github/servo/target\release\deps\libipc_channel-6c27df90414d44d9.rlib --extern util=E:/files/dev/github/servo/target\release\deps\libutil-6a316b2b9f256cef.rlib --extern net_traits=E:/files/dev/github/servo/target\release\deps\libnet_traits-f4f0ec4e8342d979.rlib --extern url=E:/files/dev/github/servo/target\release\deps\liburl-0b40538a20d23ae6.rlib --extern webrender_traits=E:/files/dev/github/servo/target\release\deps\libwebrender_traits-a0f9cbca21678e36.rlib --extern webdriver_server=E:/files/dev/github/servo/target\release\deps\libwebdriver_server-823f161b75279e0a.rlib --extern libc=E:/files/dev/github/servo/target\release\deps\liblibc-6b483f9a7097e9a4.rlib --extern layout=E:/files/dev/github/servo/target\release\deps\liblayout-b62da1f1708ec8a5.rlib --extern compositing=E:/files/dev/github/servo/target\release\deps\libcompositing-09e527ac75419044.rlib --extern net=E:/files/dev/github/servo/target\release\deps\libnet-8d2e91c2a0e8ad9c.rlib --extern canvas=E:/files/dev/github/servo/target\release\deps\libcanvas-7db25940e6f6cf33.rlib --extern msg=E:/files/dev/github/servo/target\release\deps\libmsg-abaa9cd228540970.rlib --extern env_logger=E:/files/dev/github/servo/target\release\deps\libenv_logger-bf2abd6bc9475582.rlib --extern glutin_app=E:/files/dev/github/servo/target\release\deps\libglutin_app-347175c7e431ef55.rlib --extern gleam=E:/files/dev/github/servo/target\release\deps\libgleam-b204d275fa67c07c.rlib --extern canvas_traits=E:/files/dev/github/servo/target\release\deps\libcanvas_traits-3fa7dddb0f4bbc43.rlib --extern euclid=E:/files/dev/github/servo/target\release\deps\libeuclid-6b4d3d4689700a32.rlib --extern constellation=E:/files/dev/github/servo/target\release\deps\libconstellation-6192798eda22c49b.rlib --extern browserhtml=E:/files/dev/github/servo/target\release\deps\libbrowserhtml-6f762efe0158c061.rlib --extern script_traits=E:/files/dev/github/servo/target\release\deps\libscript_traits-4d2ac2479c655ae4.rlib --extern devtools=E:/files/dev/github/servo/target\release\deps\libdevtools-d2829a531d1fd3a3.rlib --extern servo=E:/files/dev/github/servo/target\release\libservo.rlib -L native=E:/files/dev/github/servo/.cargo\registry\src\github.com-1ecc6299db9ec823\dbghelp-sys-0.2.0/x86_64 -L native=E:/files/dev/github/servo/target\release\build\hbs-pow-sys-2d4d27c3accaa57b\out\lib -L native=E:/files/dev/github/servo/target\release\build\openssl-d799b404184be4f1\out -L native=E:/files/dev/github/servo/target\release\build\openssl-sys-extras-c284211a61168afa\out -L native=C:\msys64\mingw64\bin -L native=C:\msys64\mingw64\bin -L native=E:/files/dev/github/servo/target\release\build\azure-3f1e896fb87a379c\out -L native=C:/msys64/mingw64/lib -L native=E:/files/dev/github/servo/target\release\build\servo-skia-e2c049e61d4672eb\out -L native=E:/files/dev/github/servo/.cargo\registry\src\github.com-1ecc6299db9ec823\dwmapi-sys-0.1.0/x86_64 -L native=C:/msys64/mingw64/lib -L native=C:/msys64/mingw64/lib -L native=C:/msys64/mingw64/lib -L native=E:/files/dev/github/servo/target\release\build\miniz-sys-60c8d67696f63a43\out -L native=E:/files/dev/github/servo/target\release\build\js-cca5d9cd6e49caa3\out -L native=E:/files/dev/github/servo/target\release\build\mozjs_sys-661d4efe7c7ca939\out/js/src -L native=C:/msys64/mingw64/lib -L native=E:/files/dev/github/servo/target\release\build\angle-7062634bbf237306\out -W unused-extern-crates` (exit code: 101)
"

**Comment by metajack** [comment] 2016-06-03 04:04
Ok, so first off, it appears you are not building in a mingw shell. Notice that your file paths are `E:\foo` instead if `/e/foo`.

Can you tell me what shell you are using and the steps you took to get here?

**Comment by Coder206** [comment] 2016-06-03 11:40
@metajack I am using MINGW64. I search for it (only write "mi") and I find "MinGW-w64 Win64 Shell". I start this program, navigate to Servo's directory (e:files/dev/github/servo) and then I write commands for Servo like: "./mach build -r -v -j1". I remember chatting with @mbrubeck among others from Servo on IRC and I received instructions that opened conhost.exe along side with MINGW64. Please note my system has been re formatted recently.

**Comment by Coder206** [comment] 2016-06-03 19:55
@metajack I used compiled on Linux (Fedora 23) on a virtual machine and I noticed two things: 1. The code compiled 2. Fedora 23 (newest release downloaded yesterday) loads website with Servo (Fedora < 10 seconds; Windows < 5 mins). Please note:

Fedora had access to the same CPU as Windows (same computer).
This Linux distro had access to 3 of my 8 cores and Windows 10 had access to 8 of my 8. 
For both systems, there were few programs open (Terminal and FireFox)

Is this behavior normal for Windows?

**Comment by metajack** [comment] 2016-06-03 20:37
@Coder206 Sorry. Turns out that is a red herring. I just check my own mingw shell and I see windows paths as well.

Your build seems to be failing either when compiling main.rs or linking the final servo binary, and linking is usually the more likely cause. Try this:

`RUSTFLAGS="-Z print-link-args" ./mach build -r -v -j1`

You should see another line of output in the log with the linker invocation.

**Comment by metajack** [comment] 2016-06-03 20:38
Please note that modifying RUSTFLAGS will cause a full recompile. You can also do this with a debug build instead (changing -r to -d) for a faster result.

**Comment by Coder206** [comment] 2016-06-03 21:38
@metajack This time there was no errors...

**Comment by Coder206** [comment] 2016-06-10 23:47
@paulrouget I am able to make modifications to browserHTML but I have no Mac to test with...

**Comment by jdm** [comment] 2016-06-11 07:58
Browser.html works on any operating system; why is Mac a problem in particular?

**Comment by metajack** [comment] 2016-06-11 13:41
@jdm browser.html is currently busted on windows, which is what @Coder206 uses.

**Comment by Coder206** [comment] 2016-06-11 21:12
@jdm @metajack It is also giving errors on Fedora 23.

**Comment by Coder206** [comment] 2016-06-11 21:30
@jdm I apologize for the confusion. I was expecting an answer from @paulrouget, I think he would have better understood my comment.

**Comment by Coder206** [comment] 2016-06-17 01:18
Please consult: #11765

**Comment by KiChjang** [comment] 2016-06-17 03:16
@Coder206 Are you on #servo at `irc.mozilla.org`?

**Comment by Coder206** [comment] 2016-06-17 11:47
@KiChjang I am a little confused on getting my account setup with irc

**Comment by KiChjang** [comment] 2016-06-17 12:24
AFAIK you do not need an account using IRC. Find us in #servo and we'll help you troubleshoot your problems.

**Comment by Coder206** [comment] 2016-06-17 12:46
@KiChjang Thanks!

**Comment by KiChjang** [comment] 2016-06-17 12:59
@Coder206 You can use https://kiwiirc.com/client instead of downloading an IRC client. Be sure to enter `irc.mozilla.org` as the server (the default is `irc.freenode.net`), then enter `/join #servo` on the chatbox at the bottom after you have successfully logged in.

**Comment by Coder206** [comment] 2016-06-17 13:23
@KiChjang I see there are some review request for PR, is the irc a place to share bugs, ask for reviews and talk about the future of Servo?

**Closed** 2016-06-21 03:32 UTC
Labels: A-browserhtml, C-assigned, E-easy
