### ISSUE TITLE
Handle video metadata

### ISSUE THREAD

**Issue by GuillaumeGomez** [servo/servo#11882] opened 2016-06-27 15:31 UTC
An integration can be made [here](https://github.com/servo/servo/blob/5ec01d9dcafe81bfba3cd053015393baae5f3e37/components/script/dom/htmlmediaelement.rs#L89) with the [video-metadata-rs](https://github.com/GuillaumeGomez/video-metadata-rs) crate.

However, like said in the README, `video-metadata-rs` is using the version 3.x of FFMPEG libraries. So the libs have to be built and installed manually (well, I guess it's not really an issue but I prefer to make a note about it). I think it could get downgraded to 2.x version quite easily but I think it's better to use lastest version.

I think I resumed all information about it. If you think I forgot something, please tell me! :smiley: 

I'll start to work on it in the next days.

cc @jdm

**Comment by jdm** [comment] 2016-06-27 15:51
If they're available in standard package managers (apt, dnr, brew, and mingw) then it shouldn't be a problem. Otherwise, it's going to be more difficult, since at minimum there's the cross-platform automated builders to consider.

**Comment by GuillaumeGomez** [comment] 2016-06-27 16:11
That was my point. Otherwise I'll create a 2.8 branch.

**Comment by GuillaumeGomez** [comment] 2016-06-27 16:15
Ah great news, there are packages for [linux](http://ffmpeg.org/download.html#build-linux), [OSX](http://ffmpeg.org/download.html#build-mac) and [windows](http://ffmpeg.org/download.html#build-windows)!

**Comment by est31** [comment] 2016-07-31 03:46
It supports reading metadata of all major codecs inside the Ogg container (opus, vorbis, theora): https://github.com/est31/ogg-metadata

**Comment by clstl** [comment] 2016-07-31 23:24
Had issues compiling on OSX El Capitan today. Had to build ffmpeg from sources and soft link it, so that cargo sees it. The new Homebrew version puts everything in /usr/local (having it in PATH does not seem to help)

**Comment by GuillaumeGomez** [comment] 2016-07-31 23:33
@clstl: Some people reported this issue [here](https://github.com/GuillaumeGomez/video-metadata-rs/issues/17).

**Comment by clstl** [comment] 2016-08-01 00:06
@GuillaumeGomez I cloned from master a few hours ago and the issue was present. Some more people have it as well on OS X. 
[here](https://github.com/servo/servo/issues/12672)

**Comment by metajack** [comment] 2016-08-01 19:27
The issue is that while pkg-config is used to determine if the libraries are there, it only uses the linking information, not the include directories. We just need to add those. I'm working on a patch now.

**Comment by nox** [comment] 2017-09-29 08:18
The crate `audio-video-metadata` currently returns informations about a single track in the passed media, it should return informations about all of them.

**Comment by GuillaumeGomez** [comment] 2017-09-29 08:36
I'm gonna need to take a look (it should return all tracks).

**Comment by est31** [comment] 2017-09-29 13:26
@GuillaumeGomez my ogg metadata crate should return all tracks it can find. If that doesn't work or its not enough, please say so!

**Comment by GuillaumeGomez** [comment] 2017-09-29 19:17
I think the error comes from `audio-video-metadata`. I'll need to investigate!

**Comment by ferjm** [comment] 2018-11-29 11:13
IIUC this was fixed with the addition of servo-media. Please, reopen if you consider that this issue is still valid.

**Closed by ferjm** 2018-11-29 11:13 UTC
Labels: A-content/dom, A-content/media
