### ISSUE TITLE
Unbreakable text should prefer going to the next line instead of overflowing

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#30563] opened 2023-10-17 19:44 UTC
```html
<!DOCTYPE html>
<div style="font: 16px monospace; width: 12ch; background: cyan;">
  1111
  <span style="white-space: nowrap">2222 3333</span>
</div>
```

| Actual | Expected |
| - | - |
| ![](https://github.com/servo/servo/assets/7477678/3c7c4fbf-736a-4a60-87fa-c92b6f6e4433) | ![](https://github.com/servo/servo/assets/7477678/70342f3a-5943-4d44-86eb-1742d26aa3d1) |

**Comment by joshua-holmes** [comment] 2023-10-18 03:00
Hello, I would be happy to take on this task!

**Comment by mrobinson** [comment] 2023-10-18 09:19
@joshua-holmes Thanks for the offer. @Loirooriol and I are currently looking at this.

**Comment by mrobinson** [comment] 2023-10-18 09:20
This might be a duplicate of #30288?

**Comment by joshua-holmes** [comment] 2023-10-18 22:38
> @joshua-holmes Thanks for the offer. @Loirooriol and I are currently looking at this.

Oh ok, great! I noticed @Loirooriol made several tickets regarding layout around the same time as this ticket. Are you both working on all of those tickets at once, or just this one?

**Comment by joshua-holmes** [comment] 2023-10-18 22:39
Oh wait, I see PRs for them all now :) that answers my question! Cheers!

**Closed** 2023-11-01 19:59 UTC
Labels: A-layout/inline, A-layout/2020
