### ISSUE TITLE
Width of container with IFrame inside resets when a link in the IFrame is clicked

### ISSUE THREAD

**Issue by samuknet** [servo/servo#12554] opened 2016-07-22 09:11 UTC
**Width of container with IFrame inside resets when a link in the IFrame is clicked.  The issue only occurs when the container has a transition on the width property.**

**See test case at: [https://samuknet.github.io/test_cases/iframeWidthReset/](https://samuknet.github.io/test_cases/iframeWidthReset/)**

There is an IFrame in a container 'strip'.  The IFrame is styled to have a width and height of 100% of the container.

When the page loads, JavaScript expands the container width to 100vw.  **The issue occurs whens clicking a link inside the IFrame**.  This causes the parent container to unexpectedly revert to the original width, 'resetting' the width property that had been applied with JavaScript.

The parent container has a CSS transition on the width property so that the initial change of width to 100vw is animated.  Crucially, removing this CSS transition stops the container collapsing when clicking a link in the IFrame, suggesting that the issue is related to the transition property.

**Comment by jdm** [comment] 2016-07-22 17:08
Reduced:
*a.html:*
```html
<!doctype html>
<html>
<head>
        <meta charset="utf-8" />
        <style>
        .iframe-container {
            width: 120px;
            background-color: #DD545C;
            transition: width 2s ease-in-out; /* Commenting out this transition property stops the issue occuring*/
        }

        iframe {
            width: 100%;
         }
        </style>
        <script>
                window.addEventListener('load', function() {
                        var container = document.querySelector('.iframe-container');
                        container.style.width = '100vw';
                });
        </script>
</head>

<body>
<article class="iframe-container">
        <iframe src="b.html"></iframe>
</article>
</body>
</html>
```
*b.html:*
```html
<a href="data:text/html,hello">a link</a>
```
```

**Comment by jdm** [comment] 2016-07-22 17:24
Interestingly, this doesn't reproduce if incremental layout is disabled (using `-i`).

**Comment by jdm** [comment] 2016-07-25 22:24
@notriddle I've been flailing around in the layout code trying to figure this out and getting nowhere. Are you interested in taking a crack at it?

**Comment by jdm** [comment] 2016-07-25 22:33
The furthest I got was determining that forcing https://dxr.mozilla.org/servo/rev/24d621145ca9e689b442c6f6afb3a247ab40fc5f/components/style/traversal.rs#168 to execute made the problem disappear.

**Comment by notriddle** [comment] 2016-07-25 22:57
Yes, I'm interested.

**Comment by notriddle** [comment] 2016-07-25 23:44
Seems to be a generic bug related to all replaced content:

```html
<!doctype html>
<html>
<head>
        <meta charset="utf-8" />
        <style>
        .img-container {
            width: 120px;
            background-color: #DD545C;
            transition: width 2s ease-in-out; /* Commenting out this transition property stops the issue occuring*/
        }

        img {
            width: 100%;
         }
        </style>
        <script>
                window.addEventListener('load', function() {
                        var container = document.querySelector('.img-container');
                        container.style.width = '100vw';
                });
        </script>
</head>

<body>
<article class="img-container">
        <img src="data:image/png,">
</article>
<a href="#" onclick="document.getElementsByTagName('img')[0].src = '1'">click me</a>
</body>
</html>
```

**Comment by notriddle** [comment] 2016-07-26 15:35
It also applies to a similarly setup test with color instead of width.

**Comment by notriddle** [comment] 2016-07-26 22:53
It also has nothing to do with replaced content:

```html
<!doctype html>
<html>
<head>
        <meta charset="utf-8" />
        <style>
        .container {
            width: 120px;
            background-color: red;
            transition: background-color 2s ease-in-out; /* Commenting out this transition property stops the issue occuring*/
        }
        </style>
        <script>
                window.addEventListener('load', function() {
                        var container = document.querySelector('.container');
                        container.style.backgroundColor = "black";
                });
                window.setInterval(function() {
                        var container = document.querySelector('.container');
                        console.log(window.getComputedStyle(container).backgroundColor);
                }, 100);
        </script>
</head>

<body>
<article class="container">
<div>a</div>
</article>
<a href="#" onclick="document.getElementsByTagName('div')[0].innerHTML = 'b'">click me</a>
</body>
</html>
```

Current working theory: the fact that getComputedValues() isn't changed by the transition (which is also a bug, by the way) is related to this bug. We're cloning the Arc corresponding to this DOM node, attaching it to the fragment. We perform the animation on the fragment's copy, but not on the node's. When we rebuild the fragment without restyling it, we make a new clone of the node's computed style, which has not been updated by the animation, thus reverting it.

**Comment by jdm** [comment] 2016-07-27 13:17
@notriddle getComputedStyle may be a separate bug, since the original one was fixed by turning off incremental layout, but the most recent test case is not.

**Closed** 2016-07-28 20:52 UTC
Labels: A-layout/incremental, C-has-test
