### ISSUE TITLE
Move overflow-y outside of Mako

### ISSUE THREAD

**Issue by PeterZhizhin** [servo/servo#19183] opened 2017-11-10 21:12 UTC
I think that this should be an easy property to start with. This is a sub issue of #19015.

**Comment by olmanz** [comment] 2017-11-21 10:48
@jdm 
If it's OK for you, I can try this one.

**Comment by KiChjang** [comment] 2017-11-21 11:40
@olmanz I believe @PeterZhizhin is already working on this.

**Comment by emilio** [comment] 2017-11-21 12:39
Yeah, note that this one is actually extra-tricky.

**Comment by KiChjang** [comment] 2017-11-22 09:49
@PeterZhizhin Do you need any help? Any questions?

**Comment by KiChjang** [comment] 2017-11-29 02:40
Unassigning due to lack of response. This issue is now open for anyone to work on!

**Comment by olmanz** [comment] 2017-11-29 08:42
@highfive: assign me

**Comment by olmanz** [comment] 2017-11-30 20:56
I already moved some stuff outside of Mako, as you can see in this commit on my fork:
https://github.com/olmanz/servo/commit/6f0e69fdf6aa56b44229ebd9d9a729a5d1e6bf5e

However, I currently get this message when I build servo with `./mach build --dev`:

```
   Compiling style v0.0.1 (file:///home/olmanz/Schreibtisch/workspaces/Rust/servo/components/style)
error[E0061]: this function takes 1 parameter but 2 parameters were supplied
    --> /home/olmanz/Schreibtisch/workspaces/Rust/servo/target/debug/build/style-fe2cedc35103ef47/out/properties.rs:7826:40
     |
7826 |               specified::Overflow::parse(context, input)
     |                                          ^^^^^^^^^^^^^^ expected 1 parameter
     | 
    ::: components/style/values/specified/box.rs
     |
128  | / define_css_keyword_enum! { Overflow:
129  | |     "visible" => Visible,
130  | |     "hidden" => Hidden,
131  | |     "scroll" => Scroll,
132  | |     "auto" => Auto,
133  | | }
     | |_- defined here
     |
     = note: this error originates in a macro outside of the current crate

error[E0061]: this function takes 1 parameter but 2 parameters were supplied
    --> /home/olmanz/Schreibtisch/workspaces/Rust/servo/target/debug/build/style-fe2cedc35103ef47/out/properties.rs:7937:40
     |
7937 |               specified::Overflow::parse(context, input)
     |                                          ^^^^^^^^^^^^^^ expected 1 parameter
     | 
    ::: components/style/values/specified/box.rs
     |
128  | / define_css_keyword_enum! { Overflow:
129  | |     "visible" => Visible,
130  | |     "hidden" => Hidden,
131  | |     "scroll" => Scroll,
132  | |     "auto" => Auto,
133  | | }
     | |_- defined here
     |
     = note: this error originates in a macro outside of the current crate

error: aborting due to 2 previous errors

error: Could not compile `style`.

To learn more, run the command again with --verbose.
[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
Build FAILED in 0:01:14
```

I found out that the file /target/debug/build/style-fe2cedc35103ef47/out/properties.rs is created by components/style/properties/build.py, but I'm not quite sure how to get rid of this error message.

**Comment by CYBAI** [comment] 2017-12-01 04:10
I think the root cause is the `parse` method duplicated between `define_css_keyword_enum` macro and `add_impls_for_keyword_enum` macro.

The `define_css_keyword_enum` is defined under `style_traits/values.rs` and it will `impl` your enum with a `parse` method with only *one* argument.
https://github.com/servo/servo/blob/b7bb6ffbb85aed4e94f36a71fac112ae64d46911/components/style_traits/values.rs#L388-L416

The `add_impls_for_keyword_enum` is defined under `macro.rs` and it will `impl Parse` which will need *two* arguments. 
https://github.com/servo/servo/blob/b7bb6ffbb85aed4e94f36a71fac112ae64d46911/components/style/macros.rs#L107-L127

Thus, when the `predefined_type` create the file,
https://github.com/servo/servo/blob/b7bb6ffbb85aed4e94f36a71fac112ae64d46911/components/style/properties/helpers.mako.rs#L36-L48

it will generate the file with `specified::Overflow::parse(context, input)`.

So, all you need is passing **needs_context=False** in `predefined_type`.

You can reference to `ScrollSnapType` or `OverscrollBehavior` which are also in `box.mako.rs`.

**Comment by olmanz** [comment] 2017-12-01 10:53
Thanks, that worked!

**Comment by olmanz** [comment] 2017-12-01 17:06
Pull Request is out.
https://github.com/servo/servo/pull/19448

**Comment by jdm** [comment] 2018-01-26 16:16
The previous author is busy in school right now. If anybody would like to tackle this, it is available. See #19448 for prior work.

**Comment by nicknadeau** [comment] 2018-02-04 15:14
I'd like to work on this one if it's still open!

**Comment by jdm** [comment] 2018-02-04 15:24
@nicknadeau Please do!

**Comment by nicknadeau** [comment] 2018-02-08 03:34
So I've done some investigating and just want to make sure I understand correctly.
I'm essentially taking lines 212-216 of box.mako.rs, the overflow-y bit, and feeding it into helpers.predefined_type(...)?
Am I doing the same with overflow-x?

**Comment by jdm** [comment] 2018-02-08 04:24
It's a combination of changing those mako lines to use predefined_type, as well as extracting the actual types that used to be generated by mako into proper Rust definitions in style/values, and ensuring that `./mach build-geckolib` continues to work (based on https://github.com/servo/servo/pull/19448#issuecomment-348661344).

**Comment by emilio** [comment] 2018-02-18 21:36
Hi @nicknadeau, have you managed to make any progress on this?

Thanks!

**Comment by nicknadeau** [comment] 2018-02-18 21:45
Hi @emilio, progress has been a little slow, just got out of midterms. I'll be giving this bug a go over the next few days and I'll update my status by mid-late week and let you know if I have any questions.

I hope that's alright, sorry for the slow start.

**Comment by emilio** [comment] 2018-02-18 21:51
Sounds great, no worries, and thanks! :)

**Comment by nicknadeau** [comment] 2018-02-22 01:46
Ok I've started out on a similar foot to olmanz and used overscroll-behaviour as an example to mimic.
So far I'm passing only a subset of the params into predefined_type and `./mach build` seems to work fine but of course I've not taken care of the gecko bit yet so the gecko build breaks.

I'm just stuck here, I'm really not sure how to deal with some of these params. For instance, I've tried sending gecko_constant_prefix into predefined_type and I get:
`TypeError: __init__() got an unexpected keyword argument 'gecko_constant_prefix'` - triggered by line 455 in declare_longhand.
(sorry I'm working on another PC and don't have the full error msg with me)

So I'm wondering, am I trying to get things like gecko_constant_prefix, custom_consts etc. into predefined_type as well? Is it appropriate to use the single_keyword function to handle the gecko stuff? Sorry, still trying to understand how the code is working.

**Comment by 62mkv** [comment] 2018-02-22 09:38
maybe someone removes E-easy label ? judging by history it's "anything but" easy

**Comment by nicknadeau** [comment] 2018-02-22 13:41
Well to be fair I've only spent ~2 hours on this so far, I'll keep tracing things and see what I can figure out.

**Comment by emilio** [comment] 2018-02-22 15:10
> maybe someone removes E-easy label ? judging by history it's "anything but" easy

FWIW, it should be easier now, the relevant prerequisites have already landed, like https://github.com/servo/servo/pull/19578.

**Comment by emilio** [comment] 2018-02-22 15:12
> So I'm wondering, am I trying to get things like gecko_constant_prefix, custom_consts etc. into predefined_type as well? Is it appropriate to use the single_keyword function to handle the gecko stuff? Sorry, still trying to understand how the code is working.

Sorry I missed this before, you should stop using `gecko_constant_prefix` into `predefined_type`, and then write the conversion manually like we do for other keywords, like `overscroll-behavior`.

**Comment by nicknadeau** [comment] 2018-02-25 18:41
My progress so far:
https://github.com/nicknadeau/servo/commit/97d138dc370e542e5ec0ef04b31541da37238732
https://github.com/nicknadeau/servo/commit/ed6524aa94b03d248bbd90885c7f117e06c66098

In gecko build I get the following error coming from set_overflow_y in gecko.mako.rs
Still trying to figure out what overflow_x.keyword is doing

> Traceback (most recent call last):
...
File  "/home/nick/Desktop/servo/components/style/properties/gecko.mako.rs", line 1535, in render_impl_trait
    ${caller.body().strip()}
File "/home/nick/Desktop/servo/components/style/properties/gecko.mako.rs", line 3105, in body
    $ for value in overflow_x.keyword.values_for('gecko'):
AttributeError: 'NoneType' object has no attribute 'values_for

**Comment by nicknadeau** [comment] 2018-03-21 12:50
I'm sorry guys, I really don't know how to progress from here, I don't understand enough of this code base in terms of the gecko stuff

**Comment by jdm** [comment] 2018-03-22 14:11
@emilio This is probably going to need your attention to answer the previous question.

**Comment by emilio** [comment] 2018-03-22 14:50
Oh, sorry, thanks!

@nicknadeau: So that error means that `overflow_x.keyword` is `None`, which is expected because we're using `predefined_type` instead of `keyword`. That's fine, and the only thing that needs to happen is defining the keyword ourselves like overflow_behavior does:

https://searchfox.org/mozilla-central/rev/c217fbde244344fedfd07b57a740c694a456dbca/servo/components/style/properties/gecko.mako.rs#3423

**Comment by PhilParisot** [comment] 2020-07-02 02:13
Hey @emilio and @jdm, I'd like to try and attempt this issue if that's OK with you. I just finished reading the book.

I'll say hi on #servo on Matrix.

Let me know!

Thanks!

**Comment by emilio** [comment] 2020-07-02 09:33
I think this was effectively done in https://bugzilla.mozilla.org/show_bug.cgi?id=1470695. @jdm do you have any other potential good first issue for @PhilParisot?

**Closed by emilio** 2020-07-02 09:33 UTC
Labels: A-content/css
