### ISSUE TITLE
GL context creation failed (night build)

### ISSUE THREAD

**Issue by 7histle** [servo/servo#12001] opened 2016-07-01 07:33 UTC
~~~
$ ./servo -v 
Servo 0.0.1-4f81384

$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux deepspace 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
~~~
~~~
thread 'main' panicked at 'Failed to create window.: OsError("GL context creation failed")', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x7f6022db256f - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x7f6022dba19b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x7f6022db9dff - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x7f6022c98857 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
   5:     0x7f6022d9fdcc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   6:     0x7f6022dba3e1 - std::panicking::begin_panic::he426e15a3766089a
   7:     0x7f6022da163a - std::panicking::begin_panic_fmt::hdddb415186c241e7
   8:     0x7f6022dba37e - rust_begin_unwind
   9:     0x7f6022df097f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  10:     0x7f6020f8dff0 - core::result::unwrap_failed::hd132ba2b7d75f379
  11:     0x7f6020f8cdf4 - glutin_app::window::Window::new::h750be0f1f60f008a
  12:     0x7f6020f8bdf0 - glutin_app::create_window::hae774cdda1762e66
  13:     0x7f6020f34f45 - servo::main::h6924e5658370f6b5
  14:     0x7f6022db9778 - std::panicking::try::call::h852b0d5f2eec25e4
  15:     0x7f6022dc45db - __rust_try
  16:     0x7f6022dc457e - __rust_maybe_catch_panic
  17:     0x7f6022db921e - std::rt::lang_start::hfe4efe1fc39e4a30
  18:     0x7f601e3cbb44 - __libc_start_main
  19:     0x7f6020f33f09 - <unknown>
  20:                0x0 - <unknown>
~~~

**Comment by YurySolovyov** [comment] 2016-07-01 07:40
Same here running `RUST_BACKTRACE=1 ./runservo.sh`
Running `./servo` executable creates windows that blinks with content for 1 sec and then fills with white color.
![image](https://cloud.githubusercontent.com/assets/2168518/16515013/0b5538d6-3f78-11e6-9495-ed4378bde712.png)
![image](https://cloud.githubusercontent.com/assets/2168518/16515024/1bd7d466-3f78-11e6-8044-86df23954250.png)

**Comment by YurySolovyov** [comment] 2016-07-01 07:46
running as
```
./servo -G gl -b ./build/browserhtml-3e3805f69808f24d/out/index.html makes it not crash
```

**Comment by YurySolovyov** [comment] 2016-07-01 08:01
Actually, it only crashes with webrender enabled

**Comment by nebulade** [comment] 2016-07-01 08:16
Exactly same behavior on ArchLinux:

```
% RUST_BACKTRACE=1 ./runservo.sh
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /usr/lib/libssl.so.1.0.0: no version information available (required by ./servo)
thread 'main' panicked at 'Failed to create window.: OsError("GL context creation failed")', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x55ee9808756f - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x55ee9808f19b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x55ee9808edff - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x55ee97f6d857 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
   5:     0x55ee98074dcc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   6:     0x55ee9808f3e1 - std::panicking::begin_panic::he426e15a3766089a
   7:     0x55ee9807663a - std::panicking::begin_panic_fmt::hdddb415186c241e7
   8:     0x55ee9808f37e - rust_begin_unwind
   9:     0x55ee980c597f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  10:     0x55ee96262ff0 - core::result::unwrap_failed::hd132ba2b7d75f379
  11:     0x55ee96261df4 - glutin_app::window::Window::new::h750be0f1f60f008a
  12:     0x55ee96260df0 - glutin_app::create_window::hae774cdda1762e66
  13:     0x55ee96209f45 - servo::main::h6924e5658370f6b5
  14:     0x55ee9808e778 - std::panicking::try::call::h852b0d5f2eec25e4
  15:     0x55ee980995db - __rust_try
  16:     0x55ee9809957e - __rust_maybe_catch_panic
  17:     0x55ee9808e21e - std::rt::lang_start::hfe4efe1fc39e4a30
  18:     0x7f249898c740 - __libc_start_main
  19:     0x55ee96208f09 - <unknown>
  20:                0x0 - <unknown>
```

Works with `-G gl` but I also see content under heavy flickering, often ending up only white. Just opening a page like ars technica or wikipedia keeps the CPU fully loaded without interaction.

**Comment by jdm** [comment] 2016-07-01 15:31
This is a duplicate of #12053. Thanks for filing it!

**Closed by jdm** 2016-07-01 15:31 UTC
