### ISSUE TITLE
illegal hardware instruction visiting lenovo.com

### ISSUE THREAD

**Issue by grahamc** [servo/servo#14544] opened 2016-12-10 03:25 UTC
Servo 0.0.1-4cb3404

```
$  ./servo -b --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref shell.builtin-key-shortcuts.enabled=false ./browserhtml/out/index.html --device-pixel-ratio=2
./servo: /nix/store/6jjjv5a0d3rx6qc4bs3i11p44dyc261v-servo-rpath/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /nix/store/6jjjv5a0d3rx6qc4bs3i11p44dyc261v-servo-rpath/lib/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /nix/store/6jjjv5a0d3rx6qc4bs3i11p44dyc261v-servo-rpath/lib/libssl.so.1.0.0: no version information available (required by ./servo)
Received Tick when progress was Idle: https://github.com/servo/servo/issues/10322
Received Tick when progress was Idle: https://github.com/servo/servo/issues/10322
getting outside
2
scout-to-render: timer started
getting inside
Getting into BV tabs
getting inside
Getting into BV tabs
ERROR:script::dom::bindings::error: Error at http://display.ugc.bazaarvoice.com/static/Lenovo/en_US/bvapi.js:1:21069 assetsToBeRequested is not defined
Next Day Shipping:
Next Day Shipping:Ships same business day
1
Next Day Shipping:Ships same business day
1
Next Day Shipping:Ships same business day
1
Next Day Shipping:
Next Day Shipping:Ships same business day
1
Next Day Shipping:Ships same business day
1
Next Day Shipping:Ships same business day
1
Next Day Shipping:
Next Day Shipping:Ships same business day
1
Next Day Shipping:Ships same business day
1
Next Day Shipping:Ships same business day
1
https://d.la3-c2-chi.salesforceliveagent.com/chat
572140000000T4o
00D30000000V2Wu
SolutionsJS: No campaign ID's were found
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(7) }"
stack backtrace:
   0:     0x55d82093c0dd - backtrace::backtrace::trace::h90be2828c7ec6b59
   1:     0x55d82093c762 - backtrace::capture::Backtrace::new::h8135b43a33e0c535
   2:     0x55d81f287564 - servo::install_crash_handler::handler::hbe976adb9adcb492
   3:     0x55d820549113 - AsmJSFaultHandler
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f7917c4/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   4:     0x7eff7bbc6e8f - <unknown>
   5:     0x55d8201148e3 - _ZNK13JSCompartment28unsafeUnbarrieredMaybeGlobalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f7917c4/mozjs/js/src/jscompartmentinlines.h:34
                         - _ZNK8JSObject6globalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f7917c4/mozjs/js/src/jsobjinlines.h:427
                         - _ZN2js34GetGlobalForObjectCrossCompartmentEP8JSObject
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f7917c4/mozjs/js/src/jsfriendapi.cpp:357
   6:     0x55d81f8650da - script::dom::bindings::callback::CallSetup::new::h45913405635723e5
   7:     0x55d81f93d5d9 - script::dom::globalscope::GlobalScope::fire_timer::h3f2a5f3d65de793b
   8:     0x55d81facc03c - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h1f5a79bb7fbb3810
   9:     0x55d81fac71b0 - script::script_thread::ScriptThread::handle_msgs::hae2639600700e79d
  10:     0x55d81f63d457 - std::panicking::try::do_call::h43a5dc216f489e46
  11:     0x55d82100761a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  12:     0x55d81f7e7d44 - _<F as alloc..boxed..FnBox<A>>::call_box::h33cc8351c6dd3b0b
  13:     0x55d820ffd7d4 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:605
                         - std::sys_common::thread::start_thread
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/thread.rs:84
  14:     0x7eff7bbbd1f3 - start_thread
  15:     0x7eff7b6e912e - __GI___clone
  16:                0x0 - <unknown>
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(7) }"
stack backtrace:
   0:     0x55d82093c0dd - backtrace::backtrace::trace::h90be2828c7ec6b59
   1:     0x55d82093c762 - backtrace::capture::Backtrace::new::h8135b43a33e0c535
   2:     0x55d81f287564 - servo::install_crash_handler::handler::hbe976adb9adcb492
   3:     0x7eff7b63423f - <unknown>
   4:     0x55d81f2875ef - servo::install_crash_handler::handler::hbe976adb9adcb492
   5:     0x55d820549113 - AsmJSFaultHandler
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f7917c4/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   6:     0x7eff7bbc6e8f - <unknown>
   7:     0x55d8201148e3 - _ZNK13JSCompartment28unsafeUnbarrieredMaybeGlobalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f7917c4/mozjs/js/src/jscompartmentinlines.h:34
                         - _ZNK8JSObject6globalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f7917c4/mozjs/js/src/jsobjinlines.h:427
                         - _ZN2js34GetGlobalForObjectCrossCompartmentEP8JSObject
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f7917c4/mozjs/js/src/jsfriendapi.cpp:357
   8:     0x55d81f8650da - script::dom::bindings::callback::CallSetup::new::h45913405635723e5
   9:     0x55d81f93d5d9 - script::dom::globalscope::GlobalScope::fire_timer::h3f2a5f3d65de793b
  10:     0x55d81facc03c - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h1f5a79bb7fbb3810
  11:     0x55d81fac71b0 - script::script_thread::ScriptThread::handle_msgs::hae2639600700e79d
  12:     0x55d81f63d457 - std::panicking::try::do_call::h43a5dc216f489e46
  13:     0x55d82100761a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  14:     0x55d81f7e7d44 - _<F as alloc..boxed..FnBox<A>>::call_box::h33cc8351c6dd3b0b
  15:     0x55d820ffd7d4 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:605
                         - std::sys_common::thread::start_thread
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/thread.rs:84
  16:     0x7eff7bbbd1f3 - start_thread
  17:     0x7eff7b6e912e - __GI___clone
  18:                0x0 - <unknown>
[1]    5866 illegal hardware instruction  ./servo -b --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref
```

**Comment by jdm** [comment] 2017-01-06 22:17
This looks like the same crash as #14183.

**Comment by nox** [comment] 2017-10-03 10:57
Closing as duplicate of #12072.

**Closed by nox** 2017-10-03 10:57 UTC
Labels: A-content/bindings, A-webcompat, I-crash
