### ISSUE TITLE
Windows servo UI missing elements

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#15255] opened 2017-01-26 22:34 UTC
When I open a recent Servo for Windows nightly, the UI shows this at the top:

![servo_ui_chrome](https://cloud.githubusercontent.com/assets/547158/22353268/8c0b73c6-e484-11e6-8390-cdc92b2924f1.PNG)

Instead of the expected browser.html chrome.

**Comment by emilio** [comment] 2017-01-26 22:38
Seems that this may be related with the font stuff?

**Comment by jonathandturner** [comment] 2017-01-26 23:01
It's possible these are related, but the elements here aren't font elements but other UI elements.

**Comment by codec-abc** [comment] 2017-03-13 14:49
Can you add detail to the bug please? I can't reproduce with neither the nightly nor compiling servo myself. By the way I am running Windows 10.

**Comment by KiChjang** [comment] 2017-03-13 17:35
I can confirm that it also displays this on my Windows 10 laptop. My Linux version of the nightly works fine though.

**Comment by atouchet** [comment] 2017-03-13 18:06
I just tested the latest nightly build with Windows 10 and I am still seeing UI issues.

![Windows UI](https://i.imgur.com/xovvdOq.png "Windows UI")

**Comment by jonathandturner** [comment] 2017-03-13 20:43
Right - I'm seeing the same as @KiChjang and @atouchet.

Other details:
* Running Windows 10
* Running inside of VMware Fusion on a macOS
  * Using the "VMware SVGA 3D" driver

**Comment by codec-abc** [comment] 2017-03-13 21:35
Thanks, about your previous comment are you sure the symbol or the UI aren't made of "characters" because I do have it and they look like missing characters that I have on other pages (for example, the Chinese character ones at the bottom of the servo web page). Right on my home pc I can reproduce the issue but it is weird because the [source code](https://github.com/browserhtml/browserhtml/blob/master/src/Browser/Sidebar/Tab.js#L216) does not even display those characters in Chrome and Firefox. So maybe it is just some weird characters that are not in the font packaged with Windows by default?

**Comment by jonathandturner** [comment] 2017-03-13 22:58
Leaving notes here as I look around.

I noticed that if I install FontAwesome as a system TTF font, it worked fine.  I reconverted it to woff, and the result was a little bigger than the one currently in the repo.  Sure enough, when I tried the new woff, that also worked for me.  Maybe the one that's there now was missing some sigils?

Update is here: https://github.com/browserhtml/browserhtml/pull/1272

**Comment by codec-abc** [comment] 2017-03-13 23:11
Would you mind checking how it renders on FF or Chrome while not having FontAwesome installed system wide? On my home computer the browser.html page render fine in Chrome and Firefox and not Servo. Then, if it some missing sigils why it works on FF & Chrome and Linux and MacOS and not servo?

**Comment by jonathandturner** [comment] 2017-03-13 23:52
@codec-abc - like I said, I don't know why updating the woff fixes the issue on Windows.  I don't understand the code well enough.  I was just experimenting to see if I could fix it.

**Comment by codec-abc** [comment] 2017-03-14 13:34
I opened the 2 woff files (the original one and the one repackaged by you) with fontforge and both contains the glyphs used by the Servo's UI. I have difficulties finding the code that does the work of reading and parsing the woff file. Can you please tell me where I can find it so I find more info on what is going on here.

**Comment by codec-abc** [comment] 2017-03-15 18:55
I tried to reproduce the issue by creating a [small repo](https://github.com/codec-abc/dwrote-test) containing the code that I think cause the problem. Basically, I read a woff file as a Vec<u8> pass it through fontsan (a font sanitizer library) and feed the result to dwrote (a DirectWrite wrapper). Strangely enough it managed to read both the original woff file and the a "fixed" one. Yet yesterday a breakpoint was only it [here](https://github.com/servo/servo/blob/master/components/gfx/platform/windows/font.rs#L261) with the original font file. I am starting to run out of idea to diagnose further this issue so if anyone has some tips on the subject I would gladly take them.

**Comment by codec-abc** [comment] 2017-03-16 16:47
Some update: My previous messages were plain wrong because of a breakpoint hit in Visual studio while the underlying code was not run. That would be funny if only I didn't lost so much time chasing a bug in place where the code actually works. Using good old println! instruction I find the place where the code differ when using the original font vs the "fixed" one. [It is right here](https://github.com/servo/servo/blob/master/components/gfx/platform/windows/font.rs#L57) and it make much more sense as a comment indicate that some external crate only support some "things" on mac. Commenting the two if in the methods make the original font works. But that does not seems the right things to do. So now I have to understand the purpose of those 2 if and the intended behavior and how to fix it for windows.

**Comment by codec-abc** [comment] 2017-03-16 18:17
I have understood the problem quite well. Those [2 checks](https://github.com/servo/servo/blob/master/components/gfx/platform/windows/font.rs#L57) are here to prevent to create a FontInfo structure where we wouldn't be able to return a font family name and a font face name. This is because the underlying library called truetype [is not able to parse all the records properly.](https://github.com/bodoni/truetype/blob/46dd945e8805e34ddb37ca1335f925790ef3d2cc/src/naming_table.rs#L132). The proper things to do would be to add the missing piece in truetype and then remove the check. But please note that the checks seems to not work properly even now. With the modified font file by @jonathandturner that pass the checks and display the missing UI elements I have a font family name and a font face strings of "<unsupported>" which is [the default value for things that the library is not able to parse](https://github.com/bodoni/truetype/blob/46dd945e8805e34ddb37ca1335f925790ef3d2cc/src/naming_table.rs#L147).

**Comment by codec-abc** [comment] 2017-03-21 20:36
I think the PR made to remove this from the windows blockers is great but the underlying issue is still there. As such, I think it would be better if we would leave this open and remove this issue from the windows blockers. Do you agree?

**Comment by jonathandturner** [comment] 2017-03-21 20:58
@codec-abc yes.  Actually, do you want to open a new issue that's specifically that we can't load the old woff file?  That way we can track it as a woff loading issue instead.

**Comment by codec-abc** [comment] 2017-03-22 12:03
@jonathandturner  I created #16078. This one can remain closed.

**Comment by atouchet** [comment] 2017-10-26 02:04
This is an issue again with the latest nightly build.

**Comment by atouchet** [comment] 2017-10-26 02:16
@jonathandturner I updated Servo's version of Browser.html and it seems to have re-broken this in the process. Do you have an idea of whether this would be related to the Font Awesome woff file change you made or something else?

**Comment by atouchet** [comment] 2017-10-26 14:58
Whoops, should probably close this after it's fixed in Servo itself.

**Closed** 2017-10-26 17:37 UTC
Labels: P-windows
