### ISSUE TITLE
assertion failed: address != MAP_FAILED 

### ISSUE THREAD

**Issue by stratacast** [servo/servo#12122] opened 2016-07-01 19:35 UTC
assertion failed: address != MAP_FAILED
### URL:

https://www.youtube.com/
### Backtrace:

```
frame #0  - 0x000055735b096a0d - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x000055735b096995 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000557359811487 - _<F as alloc..boxed..FnBox<A>>::call_box::heccbd09ce30bd77e
frame #3  - 0x000055735b08d818 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
frame #4  - 0x000055735b194dcc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000055735b0a42af - std::panicking::begin_panic::h0bf39f6d43ab9349
frame #6  - 0x000055735b0a6506 - ipc_channel::platform::linux::map_file::h5d9df63f5a68147c
frame #7  - 0x000055735b0a166f - _<ipc_channel..platform..linux..UnixSharedMemory as core..clone..Clone>::clone::h73c087013c7b933e
frame #8  - 0x000055735aa38242 - _<layout..fragment..Fragment as layout..display_list_builder..FragmentDisplayListBuilding>::build_fragment_type_specific_display_items::h54cda67e39950f1d
frame #9  - 0x000055735aa37900 - _<layout..fragment..Fragment as layout..display_list_builder..FragmentDisplayListBuilding>::build_display_list::hf85b575d0f567194
frame #10 - 0x000055735aa514d9 - _<layout..inline..InlineFlow as layout..display_list_builder..InlineFlowDisplayListBuilding>::build_display_list_for_inline::h3c78cacf7ad5f422
frame #11 - 0x000055735aa7a252 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #12 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #13 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #14 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #15 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #16 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #17 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #18 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #19 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #20 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #21 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #22 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #23 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #24 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #25 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #26 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #27 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #28 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #29 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #30 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #31 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #32 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #33 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #34 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #35 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #36 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #37 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #38 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #39 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #40 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #41 - 0x000055735aa7a2a7 - layout::traversal::BuildDisplayList::traverse::h5e6c8179f152510f
frame #42 - 0x000055735aa79f90 - layout::sequential::build_display_list_for_subtree::h9bb4800cb9361120
frame #43 - 0x000055735991d0d2 - layout_thread::LayoutThread::perform_post_main_layout_passes::hbb273dedf7c4ce12
frame #44 - 0x000055735987485f - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::h80c6077d3e4219c9
frame #45 - 0x0000557359878c01 - layout_thread::LayoutThread::handle_reflow::hd8767b85a218f0a2
frame #46 - 0x00005573598645e0 - layout_thread::LayoutThread::handle_request_helper::h8d81064be05c6b00
frame #47 - 0x000055735984b385 - layout_thread::LayoutThread::handle_request::h9b944f2f41c319e5
frame #48 - 0x000055735980f1fa - std::panicking::try::call::h1a5934e90174a4d0
frame #49 - 0x000055735b1b95db - __rust_try
frame #50 - 0x000055735b1b957e - __rust_maybe_catch_panic
frame #51 - 0x000055735981062d - _<F as alloc..boxed..FnBox<A>>::call_box::h2c8a06862bfda3d9
frame #52 - 0x000055735b1ad5a4 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #53 - 0x00007f8dddd8f6f9 - start_thread
frame #54 - 0x00007f8ddd8afb5c - clone
frame #55 - 0x0000000000000000 - <unknown>

```

**Comment by ConnorGBrewster** [comment] 2016-07-03 00:13
I cannot reproduce this on OS X. Possibly related to the other YouTube issues? #11992

**Comment by nox** [comment] 2017-10-04 08:02
I cannot reproduce this either. Closing.

**Closed by nox** 2017-10-04 08:02 UTC
Labels: I-panic
