### ISSUE TITLE
tweakers.net servo crash - assertion failed: window.Document ().can invoke script()

### ISSUE THREAD

**Issue by Jaaap** [servo/servo#32744] opened 2024-07-09 07:54 UTC
**Describe the bug:**
When i visit https://tweakers.net/ in Servo 0.0.1-1c6b74e the page crashes with error:
```
assertion failed: window.Document ().can invoke script()
...
script::dom::bindings::codegen::Bindings::ElementBinding::Element Binding::set_innerTML::{{closure}}
```

**To Reproduce:**
Visit https://tweakers.net/ in the minibrowser

**Platform:**
Servo 0.0.1-1c6b74e
macOS 13.6.7 (22G720) x86

**Comment by jdm** [comment] 2024-07-09 13:58
This is probably a duplicate of #32454, but I'll verify by looking at the full backtrace.

**Closed** 2024-08-16 17:31 UTC
Labels: C-untriaged
