### ISSUE TITLE
https://download.servo.org/ has an expired cert

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#13524] opened 2016-09-30 09:13 UTC
CC @edunham @metajack @larsbergstrom

**Comment by aneeshusa** [comment] 2016-09-30 13:20
Dupe of https://github.com/servo/saltfs/issues/423, but leaving this open for visibility.

**Comment by aneeshusa** [comment] 2016-10-01 21:51
Looks like we have a new cert as of yesterday.

**Closed by aneeshusa** 2016-10-01 21:51 UTC
Labels: A-infrastructure
