### ISSUE TITLE
Measure the heap usage of every DOM object in existence

### ISSUE THREAD

**Issue by jdm** [servo/servo#7084] opened 2015-08-07 19:28 UTC
All our DOM objects have a JS reflector, so the JS engine is aware of all such objects that are live. It would be nice if we could hook into this knowledge and include the measurement of the associated DOM representation when a reflector is measured.

cc @nnethercote

**Comment by nox** [comment] 2015-08-30 22:23
HeapSizeOf is implemented by all of them, isn't it?

**Comment by jdm** [comment] 2015-08-30 22:28
Yes, but the JS engine memory measurement is all in C++.

**Comment by jdm** [comment] 2017-01-03 23:48
This is basically the purpose of the `ObjectPrivateVisitor` API in SpiderMonkey, except that all of the memory gets reported as private memory for the associated object. For this to be really useful to us, we would want to report it associated with the page it originates from instead, rather than just the script thread.

**Comment by jdm** [comment] 2017-01-03 23:48
See also #7037.

**Comment by nox** [comment] 2017-01-03 23:50
Should we somehow use that to implement HeapSizeOf for Runtime in rust-mozjs directly, and just measure that?

**Comment by jdm** [comment] 2017-01-04 00:09
I don't know what you're asking. The API I'm referring to is an argument to AddServoSizeOf which is called from [here](https://github.com/servo/rust-mozjs/blob/15ff1e83446e998112dcde731610e8b60cc32abf/src/jsglue.cpp#L759), but it's also a Gecko-specific API as pointed out in #7037.

**Comment by jdm** [comment] 2018-03-09 18:47
Ok, here's my plan for addressing this issue and #7037:
* add a new class that derives ObjectPrivateVisitor in [jsglue.cpp](https://github.com/servo/rust-mozjs/blob/master/src/jsglue.cpp), and create an instance of it that is passed to JS::AddServoSizeOf
* make CollectServoSizes accept an argument - a function that accepts a `JSObject*` and returns a bool if it's an object that we want to measure
* make the new private visitor use this function: create a function that is passed to the ObjectPrivateVisitor constructor that invokes the new argument - if it returns true, cast the object pointer to `nsISupports*`, set the outparam argument and return true (we're smuggling the pointer we actually care about)
* make CollectServoSizes accept another new argument - a function that accepts a `JSObject*` argument and returns `size_t`
* implement the sizeOfIncludingThis method in the new class by casting the `nsISupports*` pointer to `JSObject*` and calling the new argument
* update glue.rs with the changes to the API of CollectServoSizes
* [using the modified rust-mozjs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#overriding-dependencies) crate, update [get_reports](https://github.com/servo/servo/blob/7ccc58e3ae356108a1d17fa6fdaf07af663912b6/components/script/script_runtime.rs#L322) to pass two new functions:
  * one which calls `is_platform_object` and `is_dom_proxy` on the passed `*mut JSObject` and returns the value (this means that it's an object that we want to measure)
  * one which calls [get_dom_class](https://github.com/servo/servo/blob/7ccc58e3ae356108a1d17fa6fdaf07af663912b6/components/script/dom/bindings/conversions.rs#L342) on the object, then uses the [malloc_size_of](https://doc.servo.org/script/dom/bindings/utils/struct.DOMClass.html#structfield.malloc_size_of) member passing the result of calling [private_from_object](https://doc.servo.org/script/dom/bindings/conversions/fn.private_from_object.html) and returning the computed size
* remove the explicit size computations of the document tree and window from script_thread::collect_reports, as they are now duplicating the other measurements

**Comment by aeweston98** [comment] 2018-03-09 22:39
I would like to contribute to this issue. I am experienced with c++ but new to rust and this code base. Please let me know if I can help out.

**Comment by jdm** [comment] 2018-03-09 23:38
@aeweston98 The actual Rust changes here are not particularly involved; the bits that will be most fiddly will probably be getting the declarations for the C/Rust functions that need to be shared in both languages to match: https://doc.rust-lang.org/book/second-edition/ch19-01-unsafe-rust.html#calling-rust-functions-from-other-languages. You're welcome to give it a shot and ask questions!

**Comment by aeweston98** [comment] 2018-03-10 01:37
@jdm Ok great, can you please assign it to me?

**Comment by aeweston98** [comment] 2018-03-12 13:04
@jdm I have been adding to jsglue.cpp according to your plan above. I now have a few questions:
1. Is there a way I can see the c++ definition for ObjectPrivateVisitor. I found the rust documentation for it, but since the new class will derive from it, it will have to call the constructor of ObjectPrivateVisitor (assuming it takes some arguments)
2. For the functions to be added to the argument list of CollectServoSizes, do you have any preference for use of std::function, or a function pointer, or a typedef of a function pointer.

**Comment by jdm** [comment] 2018-03-12 15:32
1. https://github.com/servo/mozjs/blob/3f38435122538e4b66f88878302f81331c0b6a44/mozjs/js/public/MemoryMetrics.h#L868
2. A typedef'd function pointer will be easiest to read, since it will be repeated in a few places. A std::function won't work, since Rust's FFI won't be able to represent it correctly.

**Comment by aeweston98** [comment] 2018-03-14 00:55
@jdm Question regarding bullet points 2&3 from your plan above: let's call the new function (referred to in bullet 2) passed to CollectServoSizes f. Bullet 3 says that we will invoke f from inside some other function, let’s call it g, which will be passed to the ObjectPrivateVisitor constructor. Because g only takes input parameters JSObject* and nsISupports**, I don’t see how g will have access to f in order to invoke it. Would it be ok to call f in CollectServoSizes, and call g from inside CollectServoSizes if f returns true? My apologies if I have confused what you meant.

**Comment by jdm** [comment] 2018-03-14 13:47
@aeweston98 Oops, I forgot that `g` is a bare function, not a member function of the class. Ok, so what we'll do instead is create a separate C++ method named InitializeMemoryReporter that accepts `f` and stores it in a global variable in `jsglue.cpp`. This method will need a Rust binding in `glue.rs`, and we can call it from Servo in `components/script/lib.rs` in the `init` method. Does that make sense?

**Comment by aeweston98** [comment] 2018-03-14 13:55
@jdm Yes, that is along the same lines as what I was thinking if you see my updated comment above. I will get to work on doing that!

**Comment by aeweston98** [comment] 2018-03-15 04:15
@jdm I have updated jsglue.cpp and glue.rs with the new functions, but I am having issues actually building rust-mozjs. I have attached the output from the build. Based on what I have read the source of the issue is a mismatch in my python packages or versions, however I have not had any success fixing it. I looked for other related issues in the servo project as well, please let me know if you know what is the cause of this. 
[cargo_build_output.txt](https://github.com/servo/servo/files/1813960/cargo_build_output.txt)

**Comment by jdm** [comment] 2018-03-15 15:10
@aeweston98 What python binaries exist in your path? `python`? `python26`? It seems like it can't find a `python2`, so maybe try `export PYTHON=[binary]` where `[binary]` is another python binary that exists in your path?

**Comment by aeweston98** [comment] 2018-03-19 01:19
@jdm I have implemented the new functions in script_runtime.rs and lib.rs. I was wondering what you would recommend doing to test the new code?

**Comment by jdm** [comment] 2018-03-19 01:52
@aeweston98 To test it, I would load a nontrivial page like github.com and save a memory log. Do the same in an unpatched build and compare the results. I would expect to see the dom-tree entries missing and at least as much heap usage recorded in object-private instead in the new log.

**Comment by aeweston98** [comment] 2018-03-19 22:31
@jdm I tested the new code with `./mach run https:/www.google.com -m` but no object-private entries show up. Is that what you mean by memory log? Do I have to add a call to report in get_reports for object-private in order for it to show up?

**Comment by jdm** [comment] 2018-03-20 00:11
Yes, that is what I meant by memory log. If you've updated get_reports like I described in my original plan, I would expect the output to look different from a build based off of the master branch. If it doesn't, I'll probably need to look at your changes to be able to make any useful suggestions.

**Comment by aeweston98** [comment] 2018-03-21 23:45
@jdm I have spent the last two days looking into the reporting, since there was not change in the memory metrics (except the absence of a dom-tree entry because it's calculation was removed from collect_reports). I added some logging in the constructor for the new class which derives from ObjectPrivateVisitor and confirmed that both function pointers that were added are non-null at the time of the constructor being called. However, I also added logging in the new class' implementation of sizeOfIncludingThis and it appears that that function was never called. I traced through the sequence of calls starting from AddServoSizeOf, and found [compartmentStats ](https://github.com/servo/mozjs/blob/3f38435122538e4b66f88878302f81331c0b6a44/mozjs/js/public/MemoryMetrics.h#L688-L693) which has some comment about ObjectPrivateVisitor's value always being zero. 

I wonder if when we call [addToServoSizes](https://github.com/servo/mozjs/blob/3f38435122538e4b66f88878302f81331c0b6a44/mozjs/js/src/vm/MemoryMetrics.cpp#L980) it is skipping over the objectsPrivate value in compartmentStats. 

It could also be the case that I am overcomplicating this and there is some problem in my code. Here are the links to my updated versions of [script_runtime](https://github.com/aeweston98/servo/blob/edcbe20efdf3b9fe2eb1f3c10a6ff852d9e455c4/components/script/script_runtime.rs#L319-L388), [script_thread](https://github.com/aeweston98/servo/blob/edcbe20efdf3b9fe2eb1f3c10a6ff852d9e455c4/components/script/script_thread.rs#L1582-L1614), [jsglue](https://github.com/aeweston98/rust-mozjs/blob/711171d93ee14c607b480f20bc3657f45736a246/src/jsglue.cpp#L447-L475), [jsglue_pt2](https://github.com/aeweston98/rust-mozjs/blob/711171d93ee14c607b480f20bc3657f45736a246/src/jsglue.cpp#L848-L862), [glue](https://github.com/aeweston98/rust-mozjs/blob/711171d93ee14c607b480f20bc3657f45736a246/src/glue.rs#L264-L265). If you could take a look to see if I'm doing something wrong, that would be much appreciated.

**Comment by jdm** [comment] 2018-03-22 03:18
[pass_to_ctor](https://github.com/aeweston98/rust-mozjs/blob/711171d93ee14c607b480f20bc3657f45736a246/src/jsglue.cpp#L466) _should_ be getting called for each object. Have you verified if that is the case? [sizeOfIncludingThis](https://github.com/servo/mozjs/blob/3f38435122538e4b66f88878302f81331c0b6a44/mozjs/js/src/vm/MemoryMetrics.cpp#L489-L493) will only be called if it is behaving as it should.

**Comment by jdm** [comment] 2018-03-22 03:20
It's also worth checking if changing [this](https://github.com/servo/mozjs/blob/3f38435122538e4b66f88878302f81331c0b6a44/mozjs/js/src/vm/MemoryMetrics.cpp#L968) to `FineGrained` makes a difference.

**Comment by aeweston98** [comment] 2018-03-22 15:27
It is calling pass_to_ctor, but pass_to_ctor is returning false every time. Should I be checking `is_platform_object || is_dom_proxy` instead of `is_platform_object && is_dom_proxy` in [MemoryReporter](https://github.com/aeweston98/servo/blob/edcbe20efdf3b9fe2eb1f3c10a6ff852d9e455c4/components/script/lib.rs#L205-L208)?

**Comment by jdm** [comment] 2018-03-22 15:41
Oh, whoops. Yeah, that would definitely do it.

**Comment by aeweston98** [comment] 2018-03-23 21:20
I made that change and now get_size is being called successfully sometimes (I only know this because I put in logging in sizeOfIncludingThis), however the overall memory report function is failing. I have attached a file which contains the stack trace. I went through the functions listed in the trace but I cannot it doesn't identify where the panic occurred. 

One thing I did try is to switch from borrow to try_borrow [here](https://github.com/aeweston98/servo/blob/57b12aaaaf61ad02006014465ed2c93c7ecb1e77/components/malloc_size_of/lib.rs#L278), as this is the last function in servo that was listed in the stack trace and borrow can panic if another object already owns the object. Unfortunately that did not help. 

One thing this issue could potentially be stemming from is how I am [initializing MallocSizeOfOps](https://github.com/aeweston98/servo/blob/edcbe20efdf3b9fe2eb1f3c10a6ff852d9e455c4/components/script/script_runtime.rs#L327-L330).

Here is the aforementioned file: 
[stack_trace.txt](https://github.com/servo/servo/files/1843526/stack_trace.txt)

**Comment by jdm** [comment] 2018-03-24 00:59
Unfortunately it's not a panic that's happening; it is a segfault. This suggests that the memory we're treating as a dom::Event so we can call MallocSizeOf::size_of on it is not actually valid memory somehow.

**Comment by jdm** [comment] 2018-03-24 01:24
Try asserting that [this pointer](https://github.com/servo/servo/compare/master...aeweston98:aew-issue7084#diff-76eeea325fa439a49bf462270af2058eR326) is not null? I don't see anything obviously incorrect in the code, unfortunately :(

**Comment by aeweston98** [comment] 2018-03-24 05:41
@jdm That seems to have done the trick, although I used an if statement and just returned 0 if it was null, since from the logs I could see the pointer is sometimes null and I didn't want to crash the application due to a failed assertion. Is it ok that that pointer is sometimes null? I will also check if switching to FineGrained changes anything in the memory report. I am now seeing an increase in the amount of memory recorded in malloc-heap under js of about 1.5 times the size of the dom-tree entries from the master build memory profile. Thanks for your help!

**Comment by jdm** [comment] 2018-03-24 06:12
We have added checks for null pointers at other places that deal with the DOM bindings, so I'm not too worried about the fact that it appears to be necessary here.

**Comment by aeweston98** [comment] 2018-03-24 20:48
@jdm I edited the Cargo.toml file in servo to use my updated local version of rust-mozjs. Obviously I need to change that back before making a pull request, but my concern is that the servo changes may be tested with the wrong version of rust-mozjs or vice versa. Should I just make both pull requests at the same time and note that each needs to be tested with the other?

**Comment by jdm** [comment] 2018-03-24 21:11
@aeweston98 If you make a pull request for rust-mozjs, then you can have your servo branch use your rust-mozjs branch. After we merge the rust-mozjs changes, the servo PR can be updated to use the published version.

**Comment by aeweston98** [comment] 2018-03-26 02:06
@jdm I created the pull requests for [rust-mozjs](https://github.com/servo/rust-mozjs/pull/409) and [servo](https://github.com/servo/servo/pull/20430). I looked at the web-platform-test docs, and I will try to add some tests for the new code.

**Comment by jdm** [comment] 2018-03-26 02:54
@aeweston98 There's no meaningful tests we can add for your changes, so don't spend any time trying to figure out how to add some :)

**Closed** 2018-03-28 02:44 UTC
Labels: A-content/bindings, B-high-value, B-interesting-project, C-assigned, E-less easy, I-perf-bloat
