### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

### ISSUE THREAD

**Issue by atouchet** [servo/servo#17559] opened 2017-06-29 03:07 UTC
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
### Servo Version:
Servo 0.0.1-62f99de
### Backtrace:
```

WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }>: stop_parsing not implemented, full speed ahead!
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderB

**Comment by atouchet** [comment] 2017-06-29 03:08
Error encountered when trying to load https://www.reddit.com/

**Comment by jdm** [comment] 2017-06-29 04:33
```
assertion failed: self.scroll_root_parents.contains_key(&scroll_root_id) (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /Users/jdm/src/master-servo/components/layout/display_list_builder.rs:247)
stack backtrace:
   0:        0x105197634 - backtrace::backtrace::trace<closure>
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:        0x10519258f - backtrace::capture::Backtrace::new::h08bbd1a61f799546
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:        0x1000f8ee6 - servo::main::{{closure}}
                        at /Users/jdm/src/master-servo/ports/servo/main.rs:129
   3:        0x105aeb456 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
                        at src/libstd/panicking.rs:550
   4:        0x100dbaa85 - std::panicking::begin_panic<&str>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:511
   5:        0x100df6e87 - layout::display_list_builder::{{impl}}::parent_scroll_root_id
                        at /Users/jdm/src/master-servo/components/layout/display_list_builder.rs:247
   6:        0x100df70cc - layout::display_list_builder::{{impl}}::create_base_display_item
                        at /Users/jdm/src/master-servo/components/layout/display_list_builder.rs:261
   7:        0x100d607ee - _$LT$layout..fragment..Fragment$u20$as$u20$layout..display_list_builder..FragmentDisplayListBuilding$GT$::build_display_list_for_background_if_applicable::hb0dc9a97f3b57244
                        at /Users/jdm/src/master-servo/components/layout/display_list_builder.rs:880
   8:        0x100d6882d - _$LT$layout..fragment..Fragment$u20$as$u20$layout..display_list_builder..FragmentDisplayListBuilding$GT$::build_display_list::h884986f39fb9be09
                        at /Users/jdm/src/master-servo/components/layout/display_list_builder.rs:1786
   9:        0x100f560ee - _$LT$layout..block..BlockFlow$u20$as$u20$layout..display_list_builder..BlockFlowDisplayListBuilding$GT$::build_display_list_for_block::hc86ad1f9df481d6d
                        at /Users/jdm/src/master-servo/components/layout/display_list_builder.rs:2653
  10:        0x100f43d58 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::build_display_list::h3ee277fa42bfd2fc
                        at /Users/jdm/src/master-servo/components/layout/block.rs:2139
  11:        0x100d97b4f - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:248
  12:        0x100d97d28 - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:253
  13:        0x100d97d28 - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:253
  14:        0x100d97d28 - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:253
  15:        0x100d97d28 - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:253
  16:        0x100d97d28 - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:253
  17:        0x100d97d28 - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:253
  18:        0x100d97d28 - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:253
  19:        0x100d97d28 - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:253
  20:        0x100d97d28 - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:253
  21:        0x100d97d28 - layout::traversal::{{impl}}::traverse
                        at /Users/jdm/src/master-servo/components/layout/traversal.rs:253
  22:        0x100d8b438 - layout::sequential::build_display_list_for_subtree::hf98e6cfe082d699d
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:96
  23:        0x100b61db4 - layout_thread::{{impl}}::compute_abs_pos_and_build_display_list::{{closure}}
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:931
  24:        0x100aea375 - profile_traits::time::profile<(),closure>
                        at /Users/jdm/src/master-servo/components/profile_traits/time.rs:121
  25:        0x100ac32c4 - layout_thread::{{impl}}::compute_abs_pos_and_build_display_list
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:908
  26:        0x100aca0ae - layout_thread::{{impl}}::perform_post_main_layout_passes
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:1585
  27:        0x100ac9d00 - layout_thread::{{impl}}::perform_post_style_recalc_layout_passes
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:1570
  28:        0x100ac6687 - layout_thread::{{impl}}::handle_reflow
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:1285
```

**Comment by jdm** [comment] 2017-06-29 04:34
Duplicate of #17176.

**Closed by jdm** 2017-06-29 04:34 UTC
