### ISSUE TITLE
Servo does not load CSS at all for a specific website

### ISSUE THREAD

**Issue by cadeyrn** [servo/servo#16471] opened 2017-04-15 06:37 UTC
Hi,

the nightly build of Servo for macOS does not load any css for the website https://www.soeren-hentzschel.at/, please see the attached screenshot. It happens since a few weeks, it worked a few months ago. There were a lot of other style issues but the CSS was loaded.
<img width="1440" alt="bildschirmfoto 2017-04-15 um 08 32 29" src="https://cloud.githubusercontent.com/assets/1100614/25061425/76a0d8a4-21b6-11e7-9b41-ba3a3be8f0d7.png">

macOS: version 10.12.4

===

Related questions:

1. Is there something like mozregression for Servo builds?
2. If not, is there an archive for older Servo builds so that I can say in future bug reports "you introduced a regression in the build from day X"?

**Comment by jdm** [comment] 2017-04-15 11:46
We do not have archived builds available as far as I know, so there's no easy way to bisect by nightly builds.

**Comment by jdm** [comment] 2017-04-15 12:05
This appears to be caused by #14620.

**Comment by jdm** [comment] 2017-04-15 12:06
And it should be fixed by #16069.

**Comment by jdm** [comment] 2017-05-30 17:52
Fixed!

**Closed by jdm** 2017-05-30 17:52 UTC
Labels: A-network, C-reproduced
