### ISSUE TITLE
Upgrade webrender

### ISSUE THREAD

**Issue by jdm** [servo/servo#23510] opened 2019-06-04 15:07 UTC
WIP branch that encounters errors in layout:
https://github.com/servo/servo/compare/master...jdm:wrup

Two particular commits that are making this upgrade difficult:
https://github.com/servo/webrender/commit/717b1a272e8425d3952cc19f6d182b9087495c32
https://github.com/servo/webrender/commit/d33e637ba992afd8e5fe5bef4a8b9b74e941a8bd

The errors are coming from the code in layout/display_list/; our display list is a composite of WR item types and Servo item types, since we have a Servo DL construction pass followed by a WR conversion pass in components/layout/display_list/webrender_helpers.rs. The WR changes suggest that we need to merge these passes and create a WR display list from the start, since the things like SpatialId aren't available when we're creating the Servo display list.

**Comment by pcwalton** [comment] 2019-06-04 15:10
@Gankro Perhaps you could point us in the right direction here?

**Comment by jdm** [comment] 2019-06-04 15:38
Relevant errors:
```
   Compiling layout v0.0.1 (/Users/jdm/src/master-servo/components/layout)
error[E0432]: unresolved import `webrender_api::SpecificDisplayItem`
  --> components/layout/display_list/webrender_helpers.rs:15:22
   |
15 |     PropertyBinding, SpecificDisplayItem,
   |                      ^^^^^^^^^^^^^^^^^^^ no `SpecificDisplayItem` in the root

error[E0412]: cannot find type `LayoutPoint` in module `wr`
   --> components/layout/display_list/conversions.rs:117:21
    |
117 |     type Type = wr::LayoutPoint;
    |                     ^^^^^^^^^^^ not found in `wr`
help: possible candidate is found in another module, you can import it into scope
    |
5   | use webrender_api::units::LayoutPoint;
    |

error[E0063]: missing field `common` in initializer of `webrender_api::display_item::RectangleDisplayItem`
   --> components/layout/display_list/builder.rs:718:17
    |
718 |                 webrender_api::RectangleDisplayItem {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::ImageDisplayItem`
   --> components/layout/display_list/builder.rs:853:17
    |
853 |                 webrender_api::ImageDisplayItem {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::GradientDisplayItem`
   --> components/layout/display_list/builder.rs:974:32
    |
974 |                     let item = webrender_api::GradientDisplayItem {
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::RadialGradientDisplayItem`
   --> components/layout/display_list/builder.rs:990:32
    |
990 |                     let item = webrender_api::RadialGradientDisplayItem {
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing field `common` in initializer of `webrender_api::display_item::BoxShadowDisplayItem`
    --> components/layout/display_list/builder.rs:1033:17
     |
1033 |                 webrender_api::BoxShadowDisplayItem {
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::BorderDisplayItem`
    --> components/layout/display_list/builder.rs:1159:13
     |
1159 |             webrender_api::BorderDisplayItem {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::BorderDisplayItem`
    --> components/layout/display_list/builder.rs:1263:13
     |
1263 |             webrender_api::BorderDisplayItem {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::BorderDisplayItem`
    --> components/layout/display_list/builder.rs:1315:13
     |
1315 |             webrender_api::BorderDisplayItem {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::BorderDisplayItem`
    --> components/layout/display_list/builder.rs:1346:13
     |
1346 |             webrender_api::BorderDisplayItem {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing fields `area`, `common` in initializer of `webrender_api::display_item::LineDisplayItem`
    --> components/layout/display_list/builder.rs:1377:13
     |
1377 |             webrender_api::LineDisplayItem {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `area`, `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::BorderDisplayItem`
    --> components/layout/display_list/builder.rs:1403:13
     |
1403 |             webrender_api::BorderDisplayItem {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing field `common` in initializer of `webrender_api::display_item::RectangleDisplayItem`
    --> components/layout/display_list/builder.rs:1445:17
     |
1445 |                 webrender_api::RectangleDisplayItem {
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `common`

error[E0063]: missing field `common` in initializer of `webrender_api::display_item::RectangleDisplayItem`
    --> components/layout/display_list/builder.rs:1491:13
     |
1491 |             webrender_api::RectangleDisplayItem {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `common`

error[E0063]: missing field `common` in initializer of `webrender_api::display_item::RectangleDisplayItem`
    --> components/layout/display_list/builder.rs:1675:17
     |
1675 |                 webrender_api::RectangleDisplayItem {
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::ImageDisplayItem`
    --> components/layout/display_list/builder.rs:1826:29
     |
1826 |                             webrender_api::ImageDisplayItem {
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::ImageDisplayItem`
    --> components/layout/display_list/builder.rs:1847:25
     |
1847 |                         webrender_api::ImageDisplayItem {
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::ImageDisplayItem`
    --> components/layout/display_list/builder.rs:1878:36
     |
1878 |                 let display_item = webrender_api::ImageDisplayItem {
     |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0560]: struct `webrender_api::display_item::Shadow` has no field named `should_inflate`
    --> components/layout/display_list/builder.rs:2015:25
     |
2015 |                         should_inflate: true,
     |                         ^^^^^^^^^^^^^^ `webrender_api::display_item::Shadow` does not have this field
     |
     = note: available fields are: `offset`, `color`, `blur_radius`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::TextDisplayItem`
    --> components/layout/display_list/builder.rs:2074:17
     |
2074 |                 webrender_api::TextDisplayItem {
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0063]: missing fields `area`, `common` in initializer of `webrender_api::display_item::LineDisplayItem`
    --> components/layout/display_list/builder.rs:2132:13
     |
2132 |             webrender_api::LineDisplayItem {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `area`, `common`

error[E0063]: missing fields `bounds`, `common` in initializer of `webrender_api::display_item::BorderDisplayItem`
    --> components/layout/display_list/builder.rs:2845:13
     |
2845 |             webrender_api::BorderDisplayItem {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `bounds`, `common`

error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> components/layout/display_list/webrender_helpers.rs:190:25
    |
190 |                 builder.push_shadow(/*&self.prim_info(),*/ &space_clip_info, item.shadow);
    |                         ^^^^^^^^^^^ expected 3 parameters

error[E0599]: no method named `bounds` found for type `&display_list::items::BaseDisplayItem` in the current scope
   --> components/layout/display_list/webrender_helpers.rs:198:33
    |
198 |                     self.base().bounds(),
    |                                 ^^^^^^-- help: remove the arguments
    |                                 |
    |                                 field, not a method
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `bounds`, perhaps you need to implement it:
            candidate #1: `image::image::GenericImageView`

error: aborting due to 25 previous errors

Some errors have detailed explanations: E0061, E0063, E0412, E0432, E0560, E0599.
For more information about an error, try `rustc --explain E0061`.
error: Could not compile `layout`.
```

**Comment by Gankro** [comment] 2019-06-04 16:07
Not entirely sure what the issue is here, but you can always dummy initialize a lot of things like SpatialIds/ClipIds and do a fixup pass afterwards. For instance, `SpatialId::root_scroll_node(PipelineId::dummy())`, `ClipId::root(PipelineId::dummy())`.

(`ClipId::invalid()` is a thing I want to kill so i am not advising using that)

https://searchfox.org/mozilla-central/source/gfx/wr/webrender_api/src/api.rs#832
https://searchfox.org/mozilla-central/source/gfx/wr/webrender_api/src/display_item.rs#1102

**Comment by pcwalton** [comment] 2019-06-04 17:19
@Gankro Thanks, that's helpful!

**Comment by jdm** [comment] 2019-06-06 19:14
#23516 might be enough, we just need to address the test failures now.

**Comment by Eijebong** [comment] 2019-07-12 14:25
#23516 has been merged, this can be closed :)

**Closed by Eijebong** 2019-07-12 14:25 UTC
Labels: A-gfx/displaylist, A-webrender
