### ISSUE TITLE
Don't serialize style in `text-decoration` shorthand if it has the initial value

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15790] opened 2017-03-02 02:06 UTC
e.g. `text-decoration: underline solid` should be serialized to just `text-decoration: underline`.

The relevant code is https://github.com/servo/servo/blob/c87524c8888d9c4a1f1eaedb5e3a29886f627697/components/style/properties/shorthand/text.mako.rs#L49-L59

**Comment by upsuper** [comment] 2017-03-02 02:07
Just take the `text_decoration_color` part as a reference. We should do something similar for `text_decoration_style` when it has the initial value `solid`.

**Comment by projektir** [comment] 2017-03-02 03:03
@highfive: assign me

**Comment by projektir** [comment] 2017-03-03 00:55
I started working on this issue and I could use some help. This is how far I got in writing a unit test: https://is.gd/eDsPET

The output I am getting is quite a bit off, seems like text-decoration (and possibly border style) is not being combined correctly: "text-decoration: overline; text-decoration-color: rgb(128, 0, 128); border-style: dotted;".

**Comment by upsuper** [comment] 2017-03-03 01:01
`text-decoration` contains three longhands: `text-decoration-line`, `text-decoration-style` and `text-decoration-color`. All of the three needs to present to have `text-decoration` shorthand get serialized.

Hmm, Servo currently only has `text-decoration` longhand, while Stylo has `text-decoration` shorthand consists of `text-decoration-{line,style,color}` longhands, which could lead to some confusing.

I'm not sure how this is supposed to be tested... @jdm any idea?

**Comment by projektir** [comment] 2017-03-03 01:03
Yeah, I found some setting that provides text-decoration-line for gecko, but for servo, it just becomes text-decoration? I was very confused by it, since the text.mako.rs does have text-decoration-line, but I am unable to "use" it.

I am also unclear on how to set text-decoration-style, as it doesn't seem to be a type, which is why I substituted border-style. Perhaps I didn't figure out something with computed values?

**Comment by jdm** [comment] 2017-03-03 08:00
I bet @manishearth will have better answers for how/if this can be tested.

**Comment by Manishearth** [comment] 2017-03-03 08:09
(We already discussed this in IRC, for this to be testable we'd need to make servo's text-decoration a shorthand as well. Currently text-decoration is excluded from testing because it kinda clashes with a shorthand of the same name, even though the shorthand is gecko only)

**Comment by projektir** [comment] 2017-03-04 00:23
I'm still working on this, and hoping to spend more time on it this weekend. Renaming all instances of text-decoration to text-decoration-line is turning out to be quite the rabbit hole. The latest issues were with CSSStyleDeclaration.

The only thing: I was unable to figure out what to do with cascade_property_custom() in properties/longhand/text.mako.rs. After making servo use text-decoration-line and removing (per what @Manishearth suggested on IRC) custom_cascade="${product == 'servo'}", the compiler just keeps saying the function is not in use and throws an error. I asked about deleting it and was told not to. But I don't know what to do with it or how to put it back in use. I probably need to add cascading to some other place? I had to comment it out for now.

I would like to keep working on this issue since it seems to explore the codebase well, but if someone more experienced needs to take this over, I understand.

**Comment by Manishearth** [comment] 2017-03-04 01:01
Could you push up your code and note the error it emits?

**Comment by projektir** [comment] 2017-03-04 01:13
@Manishearth I pushed them out here: https://github.com/projektir/servo/pull/1

Errors I am getting: http://pastebin.com/kjuTAmFN

**Comment by Manishearth** [comment] 2017-03-04 01:16
Yeah, the problem is that you removed the custom_cascade thing as well. Leave that untouched.

**Comment by projektir** [comment] 2017-03-04 01:21
Ah, it was the comment from xidorn that confused me:

01:15 xidorn I think you can remove custom_cascade and disable_when_testing in the latter code then

I'll try unremoving it, thanks!

**Comment by projektir** [comment] 2017-03-06 03:06
@Manishearth 
text-decoration doesn't shorthand for me. I have an idea as to why that's happening. I checked to make sure, and I'm certain the incoming properties are correct:

[text-decoration-line: overline, text-decoration-style: dotted, text-decoration-color: rgb(128, 0, 128)]
But they shorthand only to:
text-decoration: overline, text-decoration-style: dotted, text-decoration-color: rgb(128, 0, 128)

I'm not sure if I found the right code responsible for shorthanding, but what I found was that the non-Servo code wasn't active. This makes sense, as its running in Servo mode. You said that, during testing, the non-Servo properties also get included, but I don't know how that's going to work, because the non-Servo /code/ is not included, and the non-Servo code seems necessary to correctly parse text-decoration (see my % if product != "servo" additions).

[unless shorthanding is smarter and occurs in some magical code I haven't found. In which case, it'd be useful to know where that resides]

Previously, the shorthand code was limited to Gecko only, so it was never ran with Servo in the first place.

Latest code: https://github.com/projektir/servo/pull/3/files

Perhaps there's a better way to restrict code to non-servo, but somehow enable it in tests. If I remove the % if product != "servo" parts, the code just won't compile since the properties don't exist in Servo. Is it possible to, perhaps, just create two shorthands and assign them to different engines?

**Comment by Manishearth** [comment] 2017-03-06 03:28
> You said that, during testing, the non-Servo properties also get included, but I don't know how that's going to work, because the non-Servo /code/ is not included

During testing, `product` is still `"servo"`, _however_ longhands and shorthands will be included regardless of their product. So during testing the non-servo code won't be included, but the non-servo properties won't be marked as longhands for that shorthand anyway.

I'll try to build your branch locally to see what's wrong.

**Comment by Manishearth** [comment] 2017-03-06 03:35
OH, I see the issue. This is behaving as expected. Yes, this can't be tested directly that way. What you can do is change all of the `product==servo` checks in the shorthand to be something like `product == "servo" or data.testing`.

**Comment by projektir** [comment] 2017-03-06 04:26
Did you mean to say product != "servo" or data.testing? Because that worked.

**Comment by Manishearth** [comment] 2017-03-06 04:27
yes, that 😄

**Closed** 2017-03-09 06:19 UTC
Labels: A-content/css, C-assigned, E-easy
