### ISSUE TITLE
assertion failed: self.get_pending_parsing_blocking_script().is_none() || script.is_none()

### ISSUE THREAD

**Issue by ProMcTagonist** [servo/servo#12380] opened 2016-07-11 06:44 UTC
assertion failed: self.get_pending_parsing_blocking_script().is_none() || script.is_none()
### URL:
https://www.youtube.com/
### Backtrace:
```
frame #0  - 0x00007fe22beb435d - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x00007fe22beb42e5 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x00007fe22b21c069 - _<F as alloc..boxed..FnBox<A>>::call_box::hc555946005547ceb
frame #3  - 0x00007fe22bea6d68 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
frame #4  - 0x00007fe22c221dec - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x00007fe22aa58f5f - std::panicking::begin_panic::h0bf39f6d43ab9349
frame #6  - 0x00007fe22b009da5 - script::dom::document::Document::set_pending_parsing_blocking_script::hc2c8a54781f59f51
frame #7  - 0x00007fe22b0f2b4b - script::dom::htmlscriptelement::HTMLScriptElement::prepare::h351ecd27bde7dc40
frame #8  - 0x00007fe22b1616d6 - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tree_builder..rules..TreeBuilderStep>::step::hdeb03b029754e999
frame #9  - 0x00007fe22b152203 - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tokenizer..interface..TokenSink>::process_token::hdb6ec07962100a38
frame #10 - 0x00007fe22b15163e - _<html5ever..tokenizer..Tokenizer<Sink>>::process_token::headd911ae33b8a21
frame #11 - 0x00007fe22b18e2a1 - _<html5ever..tokenizer..Tokenizer<Sink>>::emit_current_tag::heb27f7c2b4f75604
frame #12 - 0x00007fe22b18a146 - _<html5ever..tokenizer..Tokenizer<Sink>>::step::h99e7351926252628
frame #13 - 0x00007fe22b17cc57 - _<html5ever..tokenizer..Tokenizer<Sink>>::run::h0e962803c394bd47
frame #14 - 0x00007fe22b14d77c - script::dom::servohtmlparser::ServoHTMLParser::parse_sync::hfb335285b73db873
frame #15 - 0x00007fe22aa75a34 - script::dom::document::Document::finish_load::hea8fb9e3713be828
frame #16 - 0x00007fe22b0ce60e - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h71d7672a3472afa1
frame #17 - 0x00007fe22b0cc3db - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h724ec798d0dfe84e
frame #18 - 0x00007fe22b0cc22d - _<script..script_thread..CancellableRunnable<T> as script..script_thread..Runnable>::handler::hfc79b036f5a49d03
frame #19 - 0x00007fe22b227024 - script::script_thread::ScriptThread::handle_msg_from_script::hfac8a5d67415fa31
frame #20 - 0x00007fe22b27a31f - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hcc3e5fcf08d42e0c
frame #21 - 0x00007fe22b2608a6 - script::script_thread::ScriptThread::handle_msgs::hf9fbf9949e23273b
frame #22 - 0x00007fe22b21a757 - std::panicking::try::call::h99112171a9854ab3
frame #23 - 0x00007fe22c245d7b - __rust_try
frame #24 - 0x00007fe22c245d1e - __rust_maybe_catch_panic
frame #25 - 0x00007fe22b21b9cd - _<F as alloc..boxed..FnBox<A>>::call_box::h4410a344b31b72da
frame #26 - 0x00007fe22c239d44 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #27 - 0x00007fe227d0e463 - start_thread
frame #28 - 0x00007fe227835e5c - clone
frame #29 - 0x0000000000000000 - <unknown>

```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-07-11 14:41
Duplicate of #11733. Thanks for reporting it!

**Closed by jdm** 2016-07-11 14:41 UTC
