### ISSUE TITLE
Implement shadow_check_callback

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8333] opened 2015-11-04 17:06 UTC
Our code is in `components/script/script_task.rs`; Gecko's equivalent is at https://mxr.mozilla.org/mozilla-central/source/dom/bindings/DOMJSProxyHandler.cpp?rev=a849e759a0f7#34.

Right now we always return `ShadowCheckFailed`; perhaps @bzbarsky knows if this is simply causing awful performance, or if it also causes detectable behaviour changes.

**Comment by bzbarsky** [comment] 2015-11-04 17:49
I believe returning ShadowCheckFailed means "exception was thrown".  If you also set a pending exception, it will be thrown.  If not, you should get an uncatchable exception.

**Comment by wenderen** [comment] 2015-11-05 08:45
Can I take this?

**Comment by Ms2ger** [comment] 2015-11-05 11:07
Sure, go for it!

**Comment by wenderen** [comment] 2015-11-05 15:12
Looking at the Firefox code, I think the mutable pointer to `c_void` returned by `js::glue::GetProxyHandler` needs to be typecast to `BaseProxyHandler`, on which the `hasOwn` method will be called. But the rust binding for `BaseProxyHandler` is just an [empty enum](https://github.com/servo/rust-mozjs/blob/e2458c40432119693456c73ac0710ff182cfc6d2/src/jsapi_linux_64.rs#L2105). Am I missing something?

**Comment by jdm** [comment] 2015-11-05 15:35
Our equivalent code uses the APIs in [glue.rs](https://github.com/servo/rust-mozjs/blob/master/src/glue.rs#L170) and [jsglue.cpp](https://github.com/servo/rust-mozjs/blob/master/src/jsglue.cpp#L419).

**Comment by jdm** [comment] 2015-11-16 21:02
Sorry, InvokeGetOwnPropertyDescriptor was intended as an example of how we do the casting you mentioned in our glue code. I imagine we would create a similar InvokeHasOwn function for the purposes of this issue.

**Comment by nox** [comment] 2015-12-16 00:11
So https://github.com/servo/rust-mozjs/pull/218 landed, but did we do the necessary smup yet?

**Comment by jdm** [comment] 2016-02-26 15:33
#8563 was proposed to fix this but was missing tests as well as some further integration with SpiderMonkey's proxy code.

**Comment by jdm** [comment] 2016-11-04 18:21
Fixed by https://github.com/servo/servo/commit/4961a513d4cb25eb0caa008dd5f662e67dfebf6d.

**Closed by jdm** 2016-11-04 18:21 UTC
Labels: A-content/bindings
