### ISSUE TITLE
Intermittent timeout in test-css

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#9311] opened 2016-01-14 10:26 UTC
http://build.servo.org/builders/linux-rel/builds/1463/steps/shell_3/logs/stdio
```
...
  /mediaqueries-3_dev/html/min-width-001.htm
  /mediaqueries-3_dev/html/min-width-tables-001.htm

command timed out: 1200 seconds without output running ['./mach', 'test-css', '--release', '--processes', '24', '--log-raw', 'test-css.log'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=1570.058154
```

**Comment by larsbergstrom** [comment] 2016-02-03 17:45
Dupe of #7723?

**Closed** 2016-02-03 17:48 UTC
Labels: I-intermittent
