### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("Send is too large for port") }) }

### ISSUE THREAD

**Issue by AlexSnet** [servo/servo#13364] opened 2016-09-21 23:40 UTC
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("Send is too large for port") }) }
### Servo Version:

Servo 0.0.1-7c0dfd0
### Backtrace:

```

WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }>: FIXME: </script> not fully implemented
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceI
...
```

This report was generated by the browser.html issue reporter.

**Comment by emilio** [comment] 2016-09-21 23:53
Hi, thanks for reporting this, do you have any URL for where this happened? Or it was just browsing normally using browser.html?

**Comment by jdm** [comment] 2016-09-21 23:54
Looks like a duplicate of #13054 . Which operating system was this on?

**Closed** 2017-01-23 18:25 UTC
Labels: I-panic
