### ISSUE TITLE
Webview for Gtk

### ISSUE THREAD

**Issue by nacktech** [servo/servo#27596] opened 2020-08-17 20:01 UTC
Hello Good Morning / Afternoon / Night,
Lately I have been very interested in web technology, especially in Blazor, and I love programming in C # with the .NET core.
With that in mind I went after ways to bring ASP.NET Core technology to desktops, I found some bookstores but the biggest problem I found is that I need to use other languages ​​(like javascript) that make the app very slow and heavy or not I have access to basic system resources like SaveFileDialogs or notifications. With that in mind and a week off, I built the WebToDesktop repository that solved the problem, using Gtk as the main Framework for interface generation and interaction with the basics of the system such as Dialogs, MessageBox and Criacão de Janelas. And with a small Bind with Webkit I got Webview, which for now works very well on Unix-like Systems. The biggest problem now is that I can't run the app on windows because the webkit has lost support and I'm not in the mood to go back to Chromium because of its weight. I would like to know if there is a way to make a servo library that contains a WebView to be used by GTK. I already know the binds I need to do to call Rust functions in C# I just need WebView. If you are curious the project is available on GitLab here: https://gitlab.com/nacktech/WebToDesktop.
I am very excited about the servo in general and would be very interested in using his technology to create graphical interfaces, my next steps would be to make the same repository for other languages and platforms.

**Comment by jdm** [comment] 2020-08-17 20:19
This is a duplicate of https://github.com/servo/servo/discussions/27595 which you opened yesterday, right? Let's continue the discussion there.

**Closed by jdm** 2020-08-17 20:19 UTC

**Comment by nacktech** [comment] 2020-08-17 20:21
oh sorry, my GitHub bugged and submit twice
