### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: RecvError

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11986] opened 2016-07-01 04:55 UTC
called `Result::unwrap()` on an `Err` value: RecvError
### URL:
http://acid3.acidtests.org/
### Backtrace:
```
frame #0  - 0x000000010c53bb4e - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x000000010c53bad1 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000000010b80c506 - _<F as alloc..boxed..FnBox<A>>::call_box::h6059122298f825d8
frame #3  - 0x000000010c4afdc7 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010c723cc4 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000000010c73cc06 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x000000010c725308 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x000000010c73c85f - rust_begin_unwind
frame #8  - 0x000000010c7636e0 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x000000010b7d56d5 - core::result::unwrap_failed::h36b4b47aa6131a86
frame #10 - 0x000000010b875bc1 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc67d8b381c013b79
frame #11 - 0x000000010b859bbf - script::script_thread::ScriptThread::handle_msgs::h236c5be60a207bea
frame #12 - 0x000000010b80ad87 - std::panicking::try::call::h645a328f039d97c6
frame #13 - 0x000000010c73f8eb - __rust_try
frame #14 - 0x000000010c73f885 - __rust_maybe_catch_panic
frame #15 - 0x000000010b80bf34 - _<F as alloc..boxed..FnBox<A>>::call_box::h3db95636eb747818
frame #16 - 0x000000010c73b368 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #17 - 0x00007fff96a3599c - _pthread_body
frame #18 - 0x00007fff96a35919 - _pthread_start

```

**Comment by pavlos256** [comment] 2016-07-01 08:13
Same error but on Wikipedia (the 3rd icon on the start page). Happens every time I tried it. I have to hit Ctrl+C to stop it. [Full logs](https://gist.github.com/pavlos256/dcae199a8d592a105459c8acb70d20f5).

**Comment by jdm** [comment] 2016-07-01 15:33
The error here is a duplicate of #6519. @pavlos256 your logs show that it's #12018 affecting you.

**Closed by jdm** 2016-07-01 15:33 UTC
Labels: A-content/script, I-panic
