### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "SendError(..)"

### ISSUE THREAD

**Issue by p-kraszewski** [servo/servo#15152] opened 2017-01-23 11:35 UTC
called `Result::unwrap()` on an `Err` value: "SendError(..)"
### URL:
https://www.saferinternetday.org/
### Servo Version:
Servo 0.0.1-27a7999
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineN
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2017-01-23 18:24
```
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("Send is too large for port") }) }
(lldb) bt
* thread #18: tid = 0x14ebd3, 0x0000000106f92844 servo`std::panicking::rust_panic + 4 at panicking.rs:586, name = 'ImageCacheThread', stop reason = breakpoint 1.1
  * frame #0: 0x0000000106f92844 servo`std::panicking::rust_panic + 4 at panicking.rs:586
    frame #1: 0x0000000106f92815 servo`std::panicking::rust_panic_with_hook + 437 at panicking.rs:571
    frame #2: 0x0000000106f92605 servo`std::panicking::begin_panic<collections::string::String> + 101 at panicking.rs:517
    frame #3: 0x0000000106f92573 servo`std::panicking::begin_panic_fmt + 147 at panicking.rs:501
    frame #4: 0x0000000106f924d8 servo`std::panicking::rust_begin_panic + 56 at panicking.rs:477
    frame #5: 0x0000000106fbbd01 servo`core::panicking::panic_fmt + 129 at panicking.rs:69
    frame #6: 0x0000000106deb041 servo`core::result::unwrap_failed<std::io::error::Error>(msg=&str at 0x0000000120bff490, error=Error at 0x0000000120bff4a0) + 369 at macros.rs:29
    frame #7: 0x0000000106de58ef servo`core::result::{{impl}}::unwrap<(self=Result<(), std::io::error::Error> at 0x0000000120bff5c0),std::io::error::Error> + 287 at result.rs:745
    frame #8: 0x0000000106dfdaa3 servo`webrender_traits::api::RenderApi::add_image::hfedf504e91c5c62f + 547
    frame #9: 0x000000010098f93b servo`net::image_cache_thread::ImageCache::complete_load::hf0294bd8c297bf77 + 843
    frame #10: 0x000000010098f51e servo`net::image_cache_thread::ImageCache::handle_decoder::h0d28156382773cb3 + 622
    frame #11: 0x000000010098d096 servo`net::image_cache_thread::ImageCache::run::h7727b17fd9e3e0cc + 2006
    frame #12: 0x00000001009917f7 servo`net::image_cache_thread::new_image_cache_thread::_$u7b$$u7b$closure$u7d$$u7d$::h5e874778f1097efd + 87
    frame #13: 0x00000001009653ab servo`_$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h47d524385cebefef + 91
    frame #14: 0x0000000100837faf servo`std::panicking::try::do_call::h1d4bb8546e854fa6 + 303
    frame #15: 0x0000000106f9368b servo`panic_unwind::__rust_maybe_catch_panic + 27 at lib.rs:98
    frame #16: 0x0000000100837acb servo`std::panicking::try::hc99734da327b0947 + 299
    frame #17: 0x00000001008359a7 servo`std::panic::catch_unwind::h007f4cbdb9f8a7db + 103
    frame #18: 0x00000001008370d2 servo`std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hd08c129b871f2682 + 354
    frame #19: 0x00000001008b0444 servo`_$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h1041d342382c0d45 + 68
    frame #20: 0x0000000106f916f5 servo`std::sys::imp::thread::{{impl}}::new::thread_start [inlined] alloc::boxed::{{impl}}::call_once<(),()> + 37 at boxed.rs:615
    frame #21: 0x0000000106f916ef servo`std::sys::imp::thread::{{impl}}::new::thread_start [inlined] std::sys_common::thread::start_thread + 15 at thread.rs:21
    frame #22: 0x0000000106f916e0 servo`std::sys::imp::thread::{{impl}}::new::thread_start + 16 at thread.rs:84
    frame #23: 0x00007fff8cebe899 libsystem_pthread.dylib`_pthread_body + 138
    frame #24: 0x00007fff8cebe72a libsystem_pthread.dylib`_pthread_start + 137
    frame #25: 0x00007fff8cec2fc9 libsystem_pthread.dylib`thread_start + 13
```

**Comment by jdm** [comment] 2017-01-23 18:25
Duplicate of #13054. Thanks for reporting it!

**Closed by jdm** 2017-01-23 18:25 UTC
Labels: C-reproduced, I-panic
