### ISSUE TITLE
Panic on goBack: assertion failed: base_time >= self.timers.borrow().last().unwrap().scheduled_for

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11499] opened 2016-05-30 05:31 UTC
STR:
- servo -w http://wikipedia.org
- click English
- wait a second or two
- go back

```
ERROR:constellation::constellation: Panic: assertion failed: base_time >= self.timers.borrow().last().unwrap().scheduled_for
ERROR:constellation::constellation: Backtrace:
frame #0  - 0x00000001072a94de - backtrace::backtrace::trace::h970e6004c9e40bad
frame #1  - 0x00000001072a9461 - backtrace::capture::Backtrace::new::hcd7fdea4950c7315
frame #2  - 0x000000010689c156 - _<F as alloc..boxed..FnBox<A>>::call_box::h8ec5b5369fd2bc89
frame #3  - 0x000000010729ab3a - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h15058e7226e5e9bb
frame #4  - 0x0000000107510042 - std::panicking::rust_panic_with_hook::hfe203e3083c2b544
frame #5  - 0x00000001062c2cd4 - std::panicking::begin_panic::h4ebf9fe884b2415f
frame #6  - 0x000000010686c7f8 - script::dom::window::Window::handle_fire_timer::he0c0cbaa02d2d9f6
frame #7  - 0x00000001068fba23 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h67c2f9a34ff15192
frame #8  - 0x00000001068e3064 - script::script_thread::ScriptThread::handle_msgs::h3aac8a42e1898215
frame #9  - 0x000000010689a907 - std::panicking::try::call::h258c18e65909931b
frame #10 - 0x000000010752b62b - __rust_try
frame #11 - 0x000000010752b5c5 - __rust_maybe_catch_panic
frame #12 - 0x000000010689bb84 - _<F as alloc..boxed..FnBox<A>>::call_box::hdaa99fc56cf1ed50
frame #13 - 0x00000001075272e8 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
frame #14 - 0x00007fff8afc099c - _pthread_body
frame #15 - 0x00007fff8afc0919 - _pthread_start
```

**Comment by nox** [comment] 2016-05-30 09:45
Duplicate of #9984.

**Closed by nox** 2016-05-30 09:45 UTC
Labels: A-browserhtml/P1, C-duplicate
