### ISSUE TITLE
Intermittent timeout in /html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-auto.html

### ISSUE THREAD

**Issue by Wafflespeanut** [servo/servo#9909] opened 2016-03-08 04:15 UTC
Tests with unexpected results:
      ▶ TIMEOUT [expected OK] /html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-auto.html
      │ 
      │ thread 'LayoutWorker worker 1/12' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:746
      │ stack backtrace:
      │    1:     0x7fd6779a8460 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
      │    2:     0x7fd6779ac71b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
      │    3:     0x7fd6779ac388 - panicking::default_handler::hffa00c845e94c6581nA
      │    4:     0x7fd6779963ac - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
      │    5:     0x7fd677996838 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
      │    6:     0x7fd6779a78d1 - rust_begin_unwind
      │    7:     0x7fd6779e379f - panicking::panic_fmt::h548fe28297c9d83b7mM
      │    8:     0x7fd676f3d7f0 - result::unwrap_failed::h5910243961065323276
      │    9:     0x7fd676f4fac1 - image_cache_thread::ImageCacheThread::find_image_or_metadata::hb1acfe78b133a8c78Qb
      │   10:     0x7fd676248992 - context::LayoutContext<'a>::get_or_request_image_or_meta::ha1d3df10af2139100Je
      │   11:     0x7fd6763a12d7 - fragment::ImageFragmentInfo::new::h386157881826269231
      │   12:     0x7fd6763a0fff - construct::FlowConstructor<'a, 'ln, ConcreteThreadSafeLayoutNode>::build_fragment_for_block::h1599187345687571620
      │   13:     0x7fd6763910cf - construct::FlowConstructor<'a, 'ln, ConcreteThreadSafeLayoutNode>.PostorderNodeMutTraversal<'ln, ConcreteThreadSafeLayoutNode>::process::h14582666686145034496
      │   14:     0x7fd676350f3e - traversal::RecalcStyleAndConstructFlows<'lc>.DomTraversalContext<'ln, ServoLayoutNode<'ln>>::process_postorder::h9b31a4861d877b75kwx
      │   15:     0x7fd67635afea - parallel::top_down_dom::h10997047908290674155
      │   16:     0x7fd6762a65c6 - sys_common::unwind::try::try_fn::h17716865604368154857
      │   17:     0x7fd6779a785b - __rust_try
      │   18:     0x7fd6779a445d - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
      │   19:     0x7fd6762a7d09 - boxed::F.FnBox<A>::call_box::h15825642985119982363
      │   20:     0x7fd6779ab1c9 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
      │   21:     0x7fd673ddb181 - start_thread
      │   22:     0x7fd6738f247c - __clone
      └   23:                0x0 - <unknown>

**Comment by jdm** [comment] 2016-03-08 04:29
Could be a duplicate of #8815.

**Closed** 2016-04-22 16:15 UTC
Labels: A-layout/uncategorized, I-intermittent, I-panic
