### ISSUE TITLE
assertion failed: !self.Document().needs_reflow() ||    (!for_display && self.Document().needs_paint()) ||    self.window_size.get().is_none() || self.suppress_reflow.get()

### ISSUE THREAD

**Issue by nimtiazm** [servo/servo#18288] opened 2017-08-28 20:49 UTC
assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()
### Servo Version:
Servo 0.0.1-5ddc446a64
### Backtrace:
```

WARNING: <Constellation>: creating replacement pipeline for about:failure
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: Panic hook called.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }>: Network error: Internal("Unexpected scheme")
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }>: Resuming an already resumed timer.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }>: stop_parsing not implemented, full speed ahead!
ERROR: assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()

stack backtrace:
   0:        0x10d41119e - backtrace::backtrace::trace::hb2a815d7a25bb200
   1:        0x10d4111dc - backtrace::capture::Backtrace::new::h8d167d15706e03e2
   2:        0x10c3b7159 - constellation::constellation::log_entry::hc3d71a94f87c581b
   3:        0x10c3b5f92 - _$LT$constellation..constellation..FromCompositorLogger$u20$as$u20$log..Log$GT$::log::ha4af64abdd7bae7b
   4:        0x10e0c77a2 - log::__log::hbcef4864c69e0b11
   5:        0x10c0696e6 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h358312fbff696eee
   6:        0x10e0e5b51 - std::panicking::rust_panic_with_hook::h7ead43b379200c35
   7:        0x10c853447 - std::panicking::begin_panic::hd3a90b83681bb743
   8:        0x10cf00364 - script::dom::window::Window::reflow::h9d1352544dc2c34b
   9:        0x10ce77c55 - script::dom::servoparser::ServoParser::do_parse_sync::he4b73cdc53ffc356
  10:        0x10ce77976 - script::dom::servoparser::ServoParser::parse_sync::h74275d215f292ccb
  11:        0x10ce75cd6 - script::dom::servoparser::ServoParser::resume_with_pending_parsing_blocking_script::h0c18c5afff8cfe89
  12:        0x10cd56935 - script::dom::document::Document::process_pending_parsing_blocking_script::hf14e8b2ddb2aa43d
  13:        0x10cd5665a - script::dom::document::Document::pending_parsing_blocking_script_loaded::h49df5c3e337af972
  14:        0x10cdfd33c - _$LT$script..dom..htmlscriptelement..ScriptContext$u20$as$u20$net_traits..FetchResponseListener$GT$::process_response_eof::h4dac3227c7ad58ca
  15:        0x10cf30eeb - _$LT$script..network_listener..ListenerRunnable$LT$A$C$$u20$Listener$GT$$u20$as$u20$script..script_thread..Runnable$GT$::handler::h2334b002c95400b6
  16:        0x10cf36742 - _$LT$script..script_thread..CancellableRunnable$LT$T$GT$$u20$as$u20$script..script_thread..Runnable$GT$::main_thread_handler::h01c066e76ee446ec
  17:        0x10cf52ecc - script::script_thread::ScriptThread::handle_msg_from_script::h36318e80782d24a0
  18:        0x10cf4c365 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc6c12abbeaaaf168
  19:        0x10cf491d2 - script::script_thread::ScriptThread::handle_msgs::hd9cfbf1fb396aa71
  20:        0x10c84a907 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5304fe1956489acb
  21:        0x10ca314ad - std::panicking::try::do_call::hfbc8fa3bf056bb11
  22:        0x10e0e6cec - __rust_maybe_catch_panic
  23:        0x10cb669c5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h5fa8f3962b4a02bb
  24:        0x10e0e2b0b - std::sys::imp::thread::Thread::new::thread_start::hd002bdea82a6ac49
  25:     0x7fffdcea293a - _pthread_body
  26:     0x7fffdcea2886 - _pthread_start
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2017-08-28 21:09
What page were you looking at?

**Comment by nimtiazm** [comment] 2017-08-28 21:23
I just clicked on Reddit from servo startup.

**Comment by nimtiazm** [comment] 2017-08-28 21:25
I'm using macOS Sierra on Mid 2015 MBP.

**Comment by nox** [comment] 2017-10-07 09:31
Closing as duplicate of #14239.

**Closed by nox** 2017-10-07 09:31 UTC
Labels: I-panic
