### ISSUE TITLE
no entry found for key

### ISSUE THREAD

**Issue by ahalam** [servo/servo#12323] opened 2016-07-07 16:18 UTC
no entry found for key
### URL:
https://www.washingtonpost.com/
### Backtrace:
```
frame #0  - 0x0000000106009e8e - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000000106009e11 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000000010451fb24 - _<F as alloc..boxed..FnBox<A>>::call_box::haeff945be1a63d60
frame #3  - 0x0000000105fe88f7 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010605eff4 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000000106077666 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x0000000106060638 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x00000001060772bf - rust_begin_unwind
frame #8  - 0x000000010609e160 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x00000001060a5c05 - core::option::expect_failed::hdb92832549f56a85
frame #10 - 0x0000000105adc715 - _<std..collections..hash..map..HashMap<K, V, S> as core..ops..Index<&'a Q>>::index::h668980d6c6bb8302
frame #11 - 0x0000000105adc501 - gfx::display_list::DisplayList::get_offset_for_item::h2c082eabba4e2de6
frame #12 - 0x0000000105adf2c3 - gfx::display_list::DisplayList::sort::_$u7b$$u7b$closure$u7d$$u7d$::hb722d4f68a1b3266
frame #13 - 0x0000000105add02e - gfx::display_list::DisplayList::new::hc3f8ce09246cce6f
frame #14 - 0x000000010463ca00 - layout_thread::LayoutThread::perform_post_main_layout_passes::h7b5f2ff1da7c5883
frame #15 - 0x0000000104588922 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::ha65b8390660d0026
frame #16 - 0x000000010458ce1b - layout_thread::LayoutThread::handle_reflow::h6771f195a62bbc92
frame #17 - 0x000000010457898d - layout_thread::LayoutThread::handle_request_helper::h1029bbb7e9e50e59
frame #18 - 0x000000010455dd1f - layout_thread::LayoutThread::handle_request::ha13841b9d3ecdc81
frame #19 - 0x000000010451d99a - std::panicking::try::call::h401e4a3a7768c3f1
frame #20 - 0x000000010607a34b - __rust_try
frame #21 - 0x000000010607a2e5 - __rust_maybe_catch_panic
frame #22 - 0x000000010451ed04 - _<F as alloc..boxed..FnBox<A>>::call_box::h8169792cb3dac906
frame #23 - 0x0000000106075dc8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #24 - 0x00007fff94c4699c - _pthread_body
frame #25 - 0x00007fff94c46919 - _pthread_start

```

**Comment by jdm** [comment] 2016-07-07 16:24
Duplicate of #12067. Thanks for reporting it!

**Closed by jdm** 2016-07-07 16:24 UTC
