### ISSUE TITLE
Floating point precision can make intrinsic size smaller than needed

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#30631] opened 2023-10-27 10:30 UTC
```html
<!DOCTYPE html>
<style>
div#wrapper {
  display: inline-block;
  border: solid;
}
div#A {
  display: inline-block;
  width: 128px;
  background: magenta;
  margin-right: 6.4px;
  padding-right: 6.4px;
}
div#B {
  display: inline-block;
  width: 64px;
  background: cyan;
}
</style>
<div id="wrapper"><div id="A">A</div><div id="B">B</div></div>
```

The intrinsic contribution of `#A` is 140.79999px, the one of `#B` is 64.0px, so the wrapper gets an inner size of 204.79999px.

But then `#A` and `#B` don't fit on the same line:

![](https://github.com/servo/servo/assets/7477678/8e4da04a-db49-4e2e-90a8-12a4cc65cd1c)

This makes `css/CSS2/floats-clear/floats-141.xht` fail (the reference is wrong).

I guess using `Au` would fix this.

**Comment by mrobinson** [comment] 2023-11-01 17:21
Closing this as a duplicate of #29819, I think.

**Closed by mrobinson** 2023-11-01 17:21 UTC
Labels: A-layout/2020
