### ISSUE TITLE
Problem building with mach

### ISSUE THREAD

**Issue by seccompgeek** [servo/servo#29830] opened 2023-06-02 06:15 UTC
I get this error when I try running the mach script. I'm not proficient in python, but I was wondering whether anyone has encountered it before. I'd happy to bypass mach and use cargo but I don't know the options to give it.

```
"/home/martin/projects/metaupdate/benchmarks/servo/python/_virtualenv3.8/bin/python" "-m" "pip" "install" "-I" "-r" "/home/martin/projects/metaupdate/benchmarks/servo/python/requirements.txt" failed with error code 1:
Output:
Ignoring dataclasses: markers 'python_version < "3.7"' don't match your environment
Obtaining file:///home/martin/projects/metaupdate/benchmarks/servo/python/tidy (from -r /home/martin/projects/metaupdate/benchmarks/servo/python/requirements.txt (line 35))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/martin/projects/metaupdate/benchmarks/servo/python/tidy/setup.py", line 41, in <module>
          setup(
        File "/home/martin/projects/metaupdate/benchmarks/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/martin/projects/metaupdate/benchmarks/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/martin/projects/metaupdate/benchmarks/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/home/martin/projects/metaupdate/benchmarks/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/home/martin/projects/metaupdate/benchmarks/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 899, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/martin/projects/metaupdate/benchmarks/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/dist.py", line 898, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/home/martin/projects/metaupdate/benchmarks/servo/python/_virtualenv3.8/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mrobinson** [comment] 2023-06-02 07:11
What version of Python do you have and how was it installed?

**Comment by seccompgeek** [comment] 2023-06-02 09:12
Thanks for your reply. I turns out it was the python version. I had Python3.8 and installed 3.11. That seemed to solve that issue.

But now I have another one. When I run ./mach run, I get this error
libEGL warning: DRI3: failed to query the version
libEGL warning: DRI2: failed to authenticate
Failed to translate window coordinates: XError { description: "BadRequest (invalid request code or no such operation)", error_code: 1, request_code: 155, minor_code: 1 } (thread main, at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.3/src/platform_impl/linux/x11/util/geometry.rs:290)

I am running servo through ssh and I'm wondering whether this could be the problem.

**Comment by CYBAI** [comment] 2023-06-02 09:17
Did you run `./mach run` without other arguments? I'm guessing it's caused by no url and results in bad request. How about `./mach run https://servo.org`?

**Comment by mrobinson** [comment] 2023-06-20 19:11
Closing this issue in favor of a new one about the second problem.

**Closed by mrobinson** 2023-06-20 19:11 UTC
