### ISSUE TITLE
Windows nightly uploads are failing

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#16560] opened 2017-04-21 14:05 UTC
http://build.servo.org/builders/windows-msvc-nightly/builds/120/steps/shell__2/logs/stdio

**Comment by aneeshusa** [comment] 2017-04-21 15:11
I'm not sure, but this might be caused by servo/saltfs#640. @larsbergstrom @metajack any ideas?

**Comment by aneeshusa** [comment] 2017-04-21 15:12
If so, the easiest solution is probably to convert the upload script to Python, instead of reinstalling MinGW/MSYS.

**Comment by aneeshusa** [comment] 2017-04-21 15:33
I'm also not sure if we need to re-install s3cmd/what's the best way to do that, given #12231.

**Comment by larsbergstrom** [comment] 2017-04-21 18:49
I'm not sure we wanted to remove msys/mingw, see https://github.com/servo/saltfs/issues/640#issuecomment-296273105

Sorry I missed that earlier issue convo.

I would certainly be in favor of using a python upload script instead (there *must* be one for s3 uploads). I assume the complexity there will mainly be in getting all the secret API keys, etc. in the right places and not being accidentally logged :-)

**Comment by aneeshusa** [comment] 2017-04-21 19:01
Re: https://github.com/servo/saltfs/issues/640#issuecomment-296275810

The script is fairly short, I can do a rewrite today (e.g. before the next set of nightlies). Buildbot takes care of passing credentials as environment variables and not logging them.

**Comment by larsbergstrom** [comment] 2017-04-21 19:02
@aneeshusa Thanks, that's great :-)

**Comment by atouchet** [comment] 2017-04-26 02:03
Has there been any progress on this? The Windows installer hasn't been updated for a week now.

**Comment by aneeshusa** [comment] 2017-04-27 02:20
@atouchet There are open PRs (servo/saltfs#642 and #16565) awaiting review by @larsbergstrom

**Comment by atouchet** [comment] 2017-05-08 16:31
@aneeshusa I don't mean to be a pain but are you still working on this?

**Comment by larsbergstrom** [comment] 2017-05-18 14:40
Should we consider rolling back the manual removal of the mingw stuff for now from the Windows builders until we can do the python2 rewrite?

**Comment by aneeshusa** [comment] 2017-05-18 20:52
I updated the PR, I don't think I actually needed to make any changes for it to work on Python 2 instead of 3 :)

**Comment by atouchet** [comment] 2017-05-24 16:33
I believe this requires https://github.com/servo/saltfs/pull/675 to be merged. The builds on the website are still out of date.

**Comment by atouchet** [comment] 2017-05-26 02:48
@aneeshusa @larsbergstrom @metajack I don't think this has actually been fixed yet. The latest nightly on the Servo website is still a build from last month. Can this issue be re-opened?

**Comment by jdm** [comment] 2017-05-26 03:19
@edunham https://github.com/servo/saltfs/pull/675 is still marked needs deploy. Do you know when we last deployed the latest saltfs changes?

**Comment by atouchet** [comment] 2017-05-29 22:03
@jdm I think this has been fixed now. I just checked the latest installer and it says it is a day old.

**Comment by aneeshusa** [comment] 2017-05-29 22:09
Thanks!

**Closed by aneeshusa** 2017-05-29 22:09 UTC
Labels: A-infrastructure
