### ISSUE TITLE
random-pipeline-closure-probability crashes Servo no matter what the probability is

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11926] opened 2016-06-29 08:59 UTC
```
servo -w -b --pref dom.mozbrowser.enabled --random-pipeline-closure-probability 0.01 Unhandled error occured
ReferenceError: navigator.mozSettings API is not available
ERROR:constellation::constellation: Panic: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }
ERROR:constellation::constellation: Backtrace:
frame #0  - 0x00000001115c4cde - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x00000001115c4c61 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000000010fe4f254 - _<F as alloc..boxed..FnBox<A>>::call_box::h94b9f08681999703
frame #3  - 0x0000000111534407 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h07c9db12619b4331
frame #4  - 0x00000001117a6d44 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x00000001117bfc56 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x00000001117a8388 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x00000001117bf8af - rust_begin_unwind
frame #8  - 0x00000001117e6730 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x000000010fe4085e - core::result::unwrap_failed::hf40cb93f6f31ec3d
frame #10 - 0x000000010feca09f - layout_thread::LayoutThread::exit_now::h62326a5b20f532cf
frame #11 - 0x000000010fea0ce3 - layout_thread::LayoutThread::handle_request_helper::he5115032f091de7d
frame #12 - 0x000000010fe8c3da - layout_thread::LayoutThread::handle_request::h6b9cfff3e3dea437
frame #13 - 0x000000010fe4d0ca - std::panicking::try::call::h8fbada836512492c
frame #14 - 0x00000001117c293b - __rust_try
frame #15 - 0x00000001117c28d5 - __rust_maybe_catch_panic
frame #16 - 0x000000010fe4e434 - _<F as alloc..boxed..FnBox<A>>::call_box::ha0ac872f82745be9
frame #17 - 0x00000001117be3b8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #18 - 0x00007fff9c71299c - _pthread_body
frame #19 - 0x00007fff9c712919 - _pthread_start
```

**Comment by asajeffrey** [comment] 2016-06-29 13:32
OK, ran some tests, indeed with p=0.01, you get a pipeline killed at startup almost always. Running with logging:
```
$ RUST_LOG=constellation=DEBUG ./mach run -b -d --random-pipeline-closure-probability=0.01
/home/ajeffrey/github/asajeffrey/servo/target/debug/build
WARN:constellation::constellation: Randomly closing pipelines.
INFO:constellation::constellation: Using seed 5619439364157530067 for random pipeline closure.
DEBUG:constellation::constellation: constellation got init load URL message
DEBUG:constellation::constellation: constellation got window resize message
DEBUG:constellation::constellation: handle_window_size_msg: 800×600 800×600
DEBUG:constellation::constellation: constellation got set visibility change complete message
DEBUG:constellation::constellation: constellation got set final url message
DEBUG:constellation::constellation: constellation got activate document message
DEBUG:constellation::constellation: Document ready to activate PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }
DEBUG:constellation::constellation: constellation got window resize message
DEBUG:constellation::constellation: handle_window_size_msg: 800×600 800×600
DEBUG:constellation::constellation: constellation got get-pipeline-title message
DEBUG:constellation::constellation: constellation got head parsed message
DEBUG:constellation::constellation: constellation got iframe URL load message PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) } None SubpageId(0)
DEBUG:constellation::constellation: Constellation: loading same-origin iframe, parent url "file:///home/ajeffrey/github/asajeffrey/servo/target/debug/build/browserhtml-a8858e40af5db62a/out/index.html", iframe url "file:///home/ajeffrey/github/asajeffrey/servo/target/debug/build/browserhtml-a8858e40af5db62a/out/components/about/newtab/index.html"
Render took 78.56010299999997ms & will cause frame drop
INFO:constellation::constellation: Not closing mozbrowser pipeline (0,0).
INFO:constellation::constellation: Not closing mozbrowser pipeline (0,0).
INFO:constellation::constellation: Not closing mozbrowser pipeline (0,0).
INFO:constellation::constellation: Randomly closing pipeline (1,0).
```
since random number generator fired 4 times, it looks like browser.html fires off about 400 events at startup. Setting p=0.001 there's no pipelines killed.

It looks like the code is doing what it's meant to, the problem is it's killing the splash page pipeline. As a work-around, is there a way to configure the splash page? Alternatively, I could add some kind of white-listing (e.g. on page URLs) which would control which pipelines were killed.

**Comment by paulrouget** [comment] 2016-06-29 14:16
I see - using about:blank instead of about:newtab makes things easier to debug.

**Comment by asajeffrey** [comment] 2016-06-29 14:25
Are you okay with changing the splash page for the moment?

**Comment by paulrouget** [comment] 2016-06-29 14:45
> Are you okay with changing the splash page for the moment?

Yes.

**Comment by asajeffrey** [comment] 2016-06-29 14:46
OK, we can close this for now, and re-open if you need more control over injected panics.

**Closed by asajeffrey** 2016-06-29 14:46 UTC
