### ISSUE TITLE
Hololens 2 rendering issues with Unity and WebXR - Regression?

### ISSUE THREAD

**Issue by De-Panther** [servo/servo#27286] opened 2020-07-16 04:04 UTC
In the current Firefox Reality in the Microsoft Hololens store, AR session works and rendered as intended.
But the nightly build version ( 13/07 ServoApp_1.1.0.0_x64_arm64 ), has some rendering issues:

- Rendering order.

- Smearing on transparent background.

I took screenshots from the emulator, but as I understood from people with the device, it's the same.

This is how it looks on the store version, you can see that the rendering order is right, and the transparent background is black (as the emulator doesn't show scene mesh by default):
![image](https://user-images.githubusercontent.com/4749703/87624554-bce98680-c730-11ea-8cb0-f8ac000f8397.png)

This is how the same AR session looks in the nightly build. You can see the smearing of the numbers and other objects. You can also see some errors in rendering order, the hand model should be near the user and not behind the floating table:
![image](https://user-images.githubusercontent.com/4749703/87624693-00dc8b80-c731-11ea-9230-75bee60785a1.png)

This is how it looks when I tried to use `WebGLRenderingContext.clear` (`COLOR_BUFFER_BIT` `DEPTH_BUFFER_BIT` and with and without `STENCIL_BUFFER_BIT`) at the frame start. There's no smearing, but the hand is rendered behind the floating table:
![image](https://user-images.githubusercontent.com/4749703/87624869-6f214e00-c731-11ea-99f6-34cb81244c86.png)

As far as I know, on AR mode we shouldn't use clear at the frame start, as in Handheld and Video see through devices, it has the camera image. If we use clear at the frame start, we won't see the camera image.

**Comment by De-Panther** [comment] 2020-07-16 04:39
The demo can be found here:
https://de-panther.github.io/unity-webxr-export/Build/
The clear flags test can be found here:
https://de-panther.github.io/unity-webxr-export/Build/index_hololens_fbo.html

**Comment by jdm** [comment] 2020-07-17 14:26
I can reproduce the AR clearing issues on non-UWP builds in our glwindow backend as well.

**Comment by jdm** [comment] 2020-07-17 14:34
This appears to be a regression from https://github.com/servo/servo/pull/26927, because the 6/27 nightly build does not show any of these issues. cc @asajeffrey

**Comment by asajeffrey** [comment] 2020-07-17 14:38
This looks like our old friend depth/stencil. I'll investigate.

**Comment by asajeffrey** [comment] 2020-07-17 16:45
@jdm when you reproduced with glwindow, was that with a build after https://github.com/servo/servo/pull/27232 was merged? I'm failing to reproduce with glwindow. I'll try it on UWP.

**Comment by jdm** [comment] 2020-07-17 16:51
I did not try with glwindow after #27232.

**Comment by asajeffrey** [comment] 2020-07-17 16:54
OK, that means it's almost certainly depth/stencil. I'll apply a similar fix to the openxr layer manager that I did for the surfman layer manager.

**Comment by asajeffrey** [comment] 2020-07-17 17:41
I reproduced the issue on the HL2, let's see if I can fix it.

**Comment by asajeffrey** [comment] 2020-07-17 19:40
OK, I think there's two things going on here. The easy-to-fix one is to add a depth/stencil texture to each XR layer, which is https://github.com/servo/webxr/pull/185. The harder-to-fix one is that there's GL errors being generated, which is what I think is causing the clear errors.

**Comment by De-Panther** [comment] 2020-07-17 19:43
Is it something on the Unity WebGL side? I'm limited with how much I can manipulate it

**Comment by asajeffrey** [comment] 2020-07-17 19:54
No, it's a problem at our end:
```
RUST: ERROR - canvas::webgl_thread - Last GL operation failed: TexSubImage2D { target: 3553, level: 0, xoffset: 71, yoffset: 54, size: 35x52, format: Alpha, data_type: UnsignedByte, effective_data_type: 5121, unpacking_alignment: 1, alpha_treatment: None, y_axis_treatment: AsIs, pixel_format: None, data: IpcSharedMemory { os... }
```
GL commands are not meant to fail like this!

**Comment by asajeffrey** [comment] 2020-07-17 20:19
The tail end of the WebGL commands:
```
RUST: WARN - canvas::webgl_thread - processing ResizeContext(WebGLContextId(3), 2880x600, WebGLSender(..))
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), ClearColor(0.0, 0.0, 0.0, 1.0), WebGLCommandBacktrace)
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), Scissor(0, 0, 1050, 600), WebGLCommandBacktrace)
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), BindTexture(3553, Some(WebGLTextureId(30))), WebGLCommandBacktrace)
RUST: WARN - canvas::webgl_thread - processing ResizeContext(WebGLContextId(3), 2880x936, WebGLSender(..))
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), ClearColor(0.0, 0.0, 0.0, 1.0), WebGLCommandBacktrace)
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), Scissor(0, 0, 1050, 600), WebGLCommandBacktrace)
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), BindTexture(3553, Some(WebGLTextureId(30))), WebGLCommandBacktrace)
RUST: WARN - script::dom::xrsession - Rendering blank XR frame
RUST: WARN - canvas::webgl_thread - processing WebXRCommand(EndFrame(WebXRLayerManagerId(1), [], WebGLSender(..)))
RUST: WARN - canvas::webgl_thread - processing WebXRCommand(BeginFrame(WebXRLayerManagerId(1), [(ContextId(3), LayerId(0))], WebGLSender(..)))
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), BindTexture(3553, Some(WebGLTextureId(31))), WebGLCommandBacktrace)
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), BindFramebuffer(36160, Explicit(WebGLFramebufferId(1))), WebGLCommandBacktrace)
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), FramebufferTexture2D(36160, 36064, 3553, Some(WebGLTextureId(31)), 0), WebGLCommandBacktrace)
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), BindFramebuffer(36160, Explicit(WebGLFramebufferId(1))), WebGLCommandBacktrace)
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), Clear(17664), WebGLCommandBacktrace)
RUST: WARN - canvas::webgl_thread - processing WebGLCommand(WebGLContextId(3), TexSubImage2D { target: 3553, level: 0, xoffset: 129, yoffset: 1, size: 35x52, format: Alpha, data_type: UnsignedByte, effective_data_type: 5121, unpacking_alignment: 1, alpha_treatment: None, y_axis_treatment: AsIs, pixel_format: None, data: IpcSharedMemory { os... }, WebGLCommandBacktrace)
RUST: ERROR - canvas::webgl_thread - Last GL operation failed: TexSubImage2D { target: 3553, level: 0, xoffset: 129, yoffset: 1, size: 35x52, format: Alpha, data_type: UnsignedByte, effective_data_type: 5121, unpacking_alignment: 1, alpha_treatment: None, y_axis_treatment: AsIs, pixel_format: None, data: IpcSharedMemory { os... }
thread 'WebGL thread' panicked at 'Unexpected WebGL error: 0x502 (1282) [TexSubImage2D { target: 3553, level: 0, xoffset: 129, yoffset: 1, size: 35x52, format: Alpha, data_type: UnsignedByte, effective_data_type: 5121, unpacking_alignment: 1, alpha_treatment: None, y_axis_treatment: AsIs, pixel_format: None, data: IpcSharedMemory { os... }]', components\canvas\webgl_thread.rs:2237:17The program '[3716] ServoApp.exe' has exited with code 0 (0x0).
```

**Comment by asajeffrey** [comment] 2020-07-17 20:23
I think what's going on is that when servo begins a frame, it calls `glBindTexture`, `glBindFramebuffer` and `glFramebufferTexture2D` to update the webxr framebuffer, but this interferes with any current bindings of the framebuffer and texture, which then causes `glTexSubImage2D` to fail.

**Comment by asajeffrey** [comment] 2020-07-17 20:25
I even wrote a `TODO` for myself about this at https://github.com/servo/servo/blob/9cd22a01f78bf1b1e39609fb67ef7464a1ce3831/components/script/dom/xrwebgllayer.rs#L232

**Comment by asajeffrey** [comment] 2020-07-17 23:06
OK, I think #27316 should fix this.

**Comment by De-Panther** [comment] 2020-07-17 23:15
You people are AWESOME

**Comment by asajeffrey** [comment] 2020-07-20 20:35
@De-Panther this fix should be in the next nightly, let us know if this fixed things!

**Comment by De-Panther** [comment] 2020-07-20 20:44
@asajeffrey sure!
I guess it would be on nightly build of 2020-07-21 and up? (not sure about the time zone there)
https://download.servo.org/

**Comment by jdm** [comment] 2020-07-20 20:46
Correct.

**Comment by De-Panther** [comment] 2020-07-21 17:18
The render order issue was fixed, but the smearing is still there
![image](https://user-images.githubusercontent.com/4749703/88085659-d5bdc600-cb8e-11ea-89ac-09e2747391a1.png)

When clearing the framebuffer at the start of the frame, there's no smearing, but Handheld and Video see through devices require to not clear the framebuffer, as they show the camera image at the background...

**Comment by asajeffrey** [comment] 2020-07-21 19:16
OK, reopening the issue.

**Comment by asajeffrey** [comment] 2020-07-22 22:25
So hopefully this is fixed by #27373. It looks fixed with the surfman layer manager, I'm building the HL2 one atm.

**Closed** 2020-07-23 20:34 UTC
Labels: A-xr-zomg, C-reproduced

**Comment by asajeffrey** [comment] 2020-07-23 23:36
The PR which hopefully fixes this has now landed, so the change should be in the next nightly build.

@De-Panther: let me know if it's actually fixed this time!

**Comment by De-Panther** [comment] 2020-07-24 14:44
It works!
Thanks!

I just tested on the emulator
![image](https://user-images.githubusercontent.com/4749703/88403333-1444c200-cdd5-11ea-8cb2-92ef6ab0c066.png)

**Comment by De-Panther** [comment] 2020-07-25 21:31
Can also confirm that it works on a device. Got a recording.
