### ISSUE TITLE
Incorrect values in calc-border-radius-1.htm test.

### ISSUE THREAD

**Issue by glennw** [servo/servo#16764] opened 2017-05-08 07:14 UTC
I started seeing a failure in ```calc-border-radius-1.htm``` when I was testing locally with the elliptical border radius support in https://github.com/servo/webrender/pull/1209.

I logged out the Servo-side display list values for the test case, and it shows:

```
clip ClippingRegion(Complex=[ComplexClippingRegion { rect: TypedRect(512px×256px at (8px,16px)), radii: BorderRadii { top_left: 21px×11px, top_right: 6px×32px, bottom_right: 12px×10px, bottom_left: 29px×3px } }])
```

```
clip ClippingRegion(Complex=[ComplexClippingRegion { rect: TypedRect(512px×256px at (8px,16px)), radii: BorderRadii { top_left: 21px×5px, top_right: 6px×16px, bottom_right: 12px×10px, bottom_left: 29px×3px } }])
```

Note that the border radii for the y-radius in the top left and top right corners don't match.

I haven't looked into it yet at all - but perhaps this is something simple in the ```calc``` support code or parser? cc @emilio in case you have any ideas :)

**Comment by emilio** [comment] 2017-05-08 08:16
I doubt it's calc parsing code given the rendering is correct on a stylo build, but I can take a look... I bet we're resolving percentages against the wrong size in layout.

**Comment by emilio** [comment] 2017-05-08 08:19
Hmm... After a quick look that shouldn't be the case maybe the problem is in the reference? Let me see...

**Comment by emilio** [comment] 2017-05-08 08:54
So yeah, that's the case, we're resolving percentages in border radius sizes against the width of the container instead of against the height.

That's the usual meaning of percentages, but in https://drafts.csswg.org/css-backgrounds-3/#border-radius:

> Percentages:	Refer to corresponding dimension of the border box.

**Closed** 2017-05-08 12:35 UTC
Labels: A-gfx/displaylist, C-has open PR, I-wrong
