### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

### ISSUE THREAD

**Issue by hshristov** [servo/servo#14248] opened 2016-11-16 11:39 UTC
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
### Servo Version:
Servo 0.0.1-07b9dbe
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(4) }>: Panic hook called.
WARNING: <Constellation>: creating replacement pipeline for about:failure
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(4) }
ERROR: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

stack backtrace:
   0:        0x10c82f30e - backtrace::backtrace::trace::h16372ee7bf1517e5
   1:        0x10c82f5fc - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
   2:        0x10b7d80a5 - constellation::constellation::log_entry::h7688487812ed581e
   3:        0x10b7d6f72 - _<constellation..constellation..FromCompositorLogger as log..Log>::log::h58738eb446c241c5
   4:        0x10d02d5e1 - log::__log::h4d9758b2ad9415f2
   5:        0x10b6ce8f0 - servo::main::_{{closure}}::h7b5afb0651e4dbf9
   6:        0x10d0e6a03 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
   7:        0x10d0e68d4 - std::panicking::begin_panic::ha6a0d553db9869ff
   8:        0x10d0e67f2 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
   9:        0x10d0e6757 - rust_begin_unwind
  10:        0x10d113520 - core::panicking::panic_fmt::he441b2ea2036b98a
  11:        0x10c946f08 - core::result::unwrap_failed::hd9b00fcbc53cf383
  12:        0x10c9a13e7 - _<layout..query..LayoutRPCImpl as script_layout_interface..rpc..LayoutRPC>::resolved_style::h0f82f7e4dd232c7a
  13:        0x10bc662e3 - _<script..dom..cssstyledeclaration..CSSStyleDeclaration as script..dom..bindings..codegen..Bindings..CSSStyleDeclarationBinding..CSSStyleDeclarationBinding..CSSStyleDeclarationMethods>::GetPropertyValue::hf1480bdffd5b89f6
  14:        0x10b9672d5 - std::panicking::try::do_call::h025ab6327078820d
  15:        0x10d0e7a2a - __rust_maybe_catch_panic
  16:        0x10be8ca27 - script::dom::bindings::codegen::Bindings::CSSStyleDeclarationBinding::CSSStyleDeclarationBinding::getPropertyValue::h259bbc749375a82f
  17:        0x10c13e2b8 - CallJitMethodOp
  18:        0x10bc35724 - script::dom::bindings::utils::generic_call::h1340dfd48a54a0ad
```
This report was generated by the browser.html issue reporter.

**Comment by emilio** [comment] 2016-11-16 11:54
A dupe of #14231, thanks for reporting it! :)

**Closed by emilio** 2016-11-16 11:54 UTC
