### ISSUE TITLE
browserhtml: crashes entering "q" into address bar of new tab.

### ISSUE THREAD

**Issue by matthiaskrgr** [servo/servo#10005] opened 2016-03-15 11:35 UTC
(**Edit:** test case in https://github.com/servo/servo/issues/10005#issuecomment-196846275)

Start browser html:
````
./mach run --release --browserhtml
/home/matthias/vcs/github/servo_release/target/release/build
compile "/home/matthias/vcs/github/servo_release/resources/shaders/quad.vs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/quad.fs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/blit.vs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/blit.fs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/border.vs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/border.fs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/blend.vs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/blend.fs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/filter.vs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/filter.fs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/box_shadow.vs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/box_shadow.fs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/blur.vs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/blur.fs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/mask.vs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/mask.fs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/debug_font.vs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/debug_font.fs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/debug_color.vs.glsl"
compile "/home/matthias/vcs/github/servo_release/resources/shaders/debug_color.fs.glsl"
ERROR:js::rust: Error at file:///home/matthias/vcs/github/servo_release/target/release/build/browserhtml-6c4c8f086420ecc3/out/components/browser/index.js:4:8053: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available

````

in the current tab, go to www.example.com

````
Render took 20.719880999997258ms & will cause frame drop
.getCanGoBack is not supported by runtime
.getCanGoForward is not supported by runtime
Error: Network request to http://ac.duckduckgo.com/ac/?q=www.example.com&type=list has failed: 
````

now open a new tab ('+' symbol) and enter "q":
````
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: begin <= end', ../src/libcore/str/mod.rs:1651
stack backtrace:
   1:     0x555618590b80 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x555618594f2b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
   3:     0x555618594b98 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x55561857e64c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x55561857ead8 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
   6:     0x55561858fff1 - rust_begin_unwind
   7:     0x5556185cbfcf - panicking::panic_fmt::h548fe28297c9d83b7mM
   8:     0x5556185cc2a8 - panicking::panic::h37bc7af2ced80b6bElM
   9:     0x5556185d38ae - str::slice_error_fail::hba87438346aaf24cbIT
  10:     0x5556176b253d - textinput::TextInput<T>::replace_selection::h11818111879466257859
  11:     0x5556176b084a - textinput::TextInput<T>::handle_keydown::h11627004748632185833
  12:     0x5556176afd30 - dom::htmlinputelement::HTMLInputElement.VirtualMethods::handle_event::hdf788b23c5547f333lY
  13:     0x55561766f15d - dom::eventdispatcher::dispatch_event::h8bd2e7a4dcd509e9abP
  14:     0x5556176181f9 - dom::document::Document::dispatch_key_event::he74bbd494f771eb3bWI
  15:     0x5556177ea585 - script_thread::ScriptThread::handle_event::hf6369a6bf2a686475vo
  16:     0x5556177fdd8c - script_thread::ScriptThread::handle_msg_from_constellation::h8c3d562caaf5ad7fsDn
  17:     0x5556177fc149 - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.174394
  18:     0x5556177e6391 - script_thread::ScriptThread::handle_msgs::ha8bbd4775cd2e78dlsn
  19:     0x5556177abbd7 - sys_common::unwind::try::try_fn::h12978508261700142550
  20:     0x55561858ff7b - __rust_try
  21:     0x55561858cb6d - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  22:     0x5556177acdaa - boxed::F.FnBox<A>::call_box::h12290829966752940180
  23:     0x5556185939d9 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  24:     0x7f8e7b4b3609 - start_thread
  25:     0x7f8e7afd6a4c - clone
  26:                0x0 - <unknown>
thread 'thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } }', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x555618590b80 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x555618594f2b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
   3:     0x555618594b98 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x55561857e64c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x55561857ead8 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
   6:     0x55561858fff1 - rust_begin_unwind
   7:     0x5556185cbfcf - panicking::panic_fmt::h548fe28297c9d83b7mM
   8:     0x5556171596b0 - result::unwrap_failed::h10546953445039740107
   9:     0x555617189e2d - sys_common::unwind::try::try_fn::h9568087773282740994
  10:     0x55561858ff7b - __rust_try
  11:     0x55561858cb6d - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  12:     0x55561718a08a - boxed::F.FnBox<A>::call_box::h2793954341346063323
  13:     0x5556185939d9 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  14:     0x7f8e7b4b3609 - start_thread
  15:     0x7f8e7afd6a4c - clone
  16:                0x0 - <unknown>
thread '<main>' panicked at 'Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }).', /home/matthias/vcs/github/servo_release/components/compositing/compositor.rs:744
stack backtrace:
  thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:746
 1:     0x555618590b80 - sys::backtrace::tracing::imp::writeConstellation::h578d6e47592a4041cHv
' panicked at 'unable to find pipeline - this is a bug   2', ../src/libcore/option.rs:   :704
' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } }',   0x555618594f2b - panicking::default_handler::LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }_' panicked at '$u7b$$u7b$closure$u7d$$u7d$called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }::', closure.44995../src/libcore/result.rs
:  746
 3:     0x555618594b98 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x55561857e64c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x55561857ead8 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
../src/libcore/result.rs:746
   6:     0x555616bc3436 - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h13022890211552902312
   7:     0x555616bfc7bc - Browser::handle_events::h325cbdacdc5ba152Wea
   8:     0x555616bad627 - main::hb2ad826330afabd3Naa
   9:     0x5556185947f4 - sys_common::unwind::try::try_fn::h17074903832088339578
  10:     0x55561858ff7b - __rust_try
  11:     0x55561859428b - rt::lang_start::hc48b7676a10bcd987fA
  12:     0x7f8e7aef457f - __libc_start_main
  13:     0x555616ba31f8 - _start
  14:                0x0 - <unknown>
stack backtrace:
   1:     0x555618590b80 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x555618594f2b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
   3:     0x555618594b98 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x55561857e64c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x55561857ead8 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
   6:     0x55561858fff1 - rust_begin_unwind
   7:     0x5556185cbfcf - panicking::panic_fmt::h548fe28297c9d83b7mM
   8:     0x555616ebf66e - result::unwrap_failed::h2040538994126317178
   9:     0x555616f6db52 - layout_thread::LayoutThread::exit_now::hba5f89c494b4d512rZq
  10:     0x555616f4c3c7 - layout_thread::LayoutThread::handle_request_helper::hcee560565c75e702qPq
  11:     0x555616f37359 - layout_thread::LayoutThread::handle_request::h4af309cb59f0083bPJq
  12:     0x555616f0246a - sys_common::unwind::try::try_fn::h18054357694180393552
  13:     0x55561858ff7b - __rust_try
  14:     0x55561858cb6d - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  15:     0x555616f0336a - boxed::F.FnBox<A>::call_box::h16584364912545432222
  16:     0x5556185939d9 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  17:     0x7f8e7b4b3609 - start_thread
  18:     0x7f8e7afd6a4c - clone
  19:                0x0 - <unknown>
stack backtrace:
   1:     0x555618590b80 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x555618594f2b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
   3:     0x555618594b98 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x55561857e64c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x55561857ead8 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
   6:     0x55561858fff1 - rust_begin_unwind
   7:     0x5556185cbfcf - panicking::panic_fmt::h548fe28297c9d83b7mM
   8:     0x5556185d3474 - option::expect_failed::hce0693d5039c3a72iWO
   9:     0x555616cd6c1f - constellation::Constellation<LTF, STF>::handle_failure_msg::h12736585736956099463
  10:     0x555616c466b4 - constellation::Constellation<LTF, STF>::handle_request::h17559007085080393797
  11:     0x555616c34277 - sys_common::unwind::try::try_fn::h17767182192282328315
  12:     0x55561858ff7b - __rust_try
  13:     0x55561858cb6d - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  14:     0x555616c3526a - boxed::F.FnBox<A>::call_box::h17477127969866589547
  15:     0x5556185939d9 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  16:     0x7f8e7b4b3609 - start_thread
  17:     0x7f8e7afd6a4c - clone
  18:                0x0 - <unknown>
stack backtrace:
   1:     0x555618590b80 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x555618594f2b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
   3:     0x555618594b98 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x55561857e64c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:   thread 'StorageManager  0x55561857ead8' panicked at ' - sys_commoncalled `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })::unwind::', begin_unwind_fmt::../src/libcore/result.rs:h3777a045191296c5Buu
746   
6:     0x55561858fff1 - rust_begin_unwind
   7:     0x5556185cbfcf - panicking::panic_fmt::h548fe28297c9d83b7mM
   8:     0x555616e97cd0 - result::unwrap_failed::h17193303411656183864
   9:     0x555616f6dafb - layout_thread::LayoutThread::exit_now::hba5f89c494b4d512rZq
  10:     0x555616f5107d - layout_thread::LayoutThread::handle_request_helper::hcee560565c75e702qPq
  11:     0x555616f372da - layout_thread::LayoutThread::handle_request::h4af309cb59f0083bPJq
  12:     0x555616f0246a - sys_common::unwind::try::try_fn::h18054357694180393552
  13:     0x55561858ff7b - __rust_try
  14:     0x55561858cb6d - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  15:     0x555616f0336a - boxed::F.FnBox<A>::call_box::h16584364912545432222
  16:     0x5556185939d9 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  17:     0x7f8e7b4b3609 - start_thread
  18:     0x7f8e7afd6a4c - clone
  19:                0x0 - <unknown>
stack backtrace:
   1:     0x555618590b80 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x555618594f2b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
   3:     0x555618594b98 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x55561857e64c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x55561857ead8 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
   6:     0x55561858fff1 - rust_begin_unwind
   7:     0x5556185cbfcf - panicking::panic_fmt::h548fe28297c9d83b7mM
   8:     0x5556171596b0 - result::unwrap_failed::h10546953445039740107
   9:     0x555617189e2d - sys_common::unwind::try::try_fn::h9568087773282740994
  10:     0x55561858ff7b - __rust_try
  11:     0x55561858cb6d - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  12:     0x55561718a08a - boxed::F.FnBox<A>::call_box::h2793954341346063323
  13:     0x5556185939d9 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  14:     0x7f8e7b4b3609 - start_thread
  15:     0x7f8e7afd6a4c - clone
  16:                0x0 - <unknown>
stack backtrace:
   1:     0x555618590b80 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x555618594f2b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
   3:     0x555618594b98 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x55561857e64c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x55561857ead8 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
   6:     0x55561858fff1 - rust_begin_unwind
   7:     0x5556185cbfcf - panicking::panic_fmt::h548fe28297c9d83b7mM
   8:     0x555616dff2be - result::unwrap_failed::h15788789913766787649
   9:     0x555616e63203 - storage_thread::StorageManager::start::h90964dbc2bb60f1axef
  10:     0x555616e5ab08 - sys_common::unwind::try::try_fn::h7994699427080799327
  11:     0x55561858ff7b - __rust_try
  12:     0x55561858cb6d - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  13:     0x555616e5ad9a - boxed::F.FnBox<A>::call_box::h12946475113732053622
  14:     0x5556185939d9 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  15:     0x7f8e7b4b3609 - start_thread
  16:     0x7f8e7afd6a4c - clone
  17:                0x0 - <unknown>
thread 'ImageCacheThread' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x555618590b80 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x555618594f2b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
   3:     0x555618594b98 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x55561857e64c - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x55561857ead8 - sys_common::unwind::begin_unwind_fmt::h3777a045191296c5Buu
   6:     0x55561858fff1 - rust_begin_unwind
   7:     0x5556185cbfcf - panicking::panic_fmt::h548fe28297c9d83b7mM
   8:     0x555616e1957d - result::unwrap_failed::h17612557959320387882
   9:     0x555616df5838 - image_cache_thread::ImageCache::run::h8cce50101d99e794zgc
  10:     0x555616e3726e - sys_common::unwind::try::try_fn::h15377173419488244951
  11:     0x55561858ff7b - __rust_try
  12:     0x55561858cb6d - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  13:     0x555616e37644 - boxed::F.FnBox<A>::call_box::h941295257838395816
  14:     0x5556185939d9 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  15:     0x7f8e7b4b3609 - start_thread
  16:     0x7f8e7afd6a4c - clone
  17:                0x0 - <unknown>
Servo exited with return value 101

````

**Comment by paulrouget** [comment] 2016-03-15 13:04
I can reproduce.

**Comment by lambda** [comment] 2016-03-15 14:10
Also ran into this.

A little bit of debug printing in `replace_selection`:

```rust
                println!("begin.line: {} len: {} begin.index: {}",
                         begin.line,
                         self.lines[begin.line].len(),
                         begin.index);
                println!("end.line: {} len: {} end.index: {}",
                         end.line,
                         self.lines[begin.line].len(),
                         end.index);
                let prefix = &self.lines[begin.line][..begin.index];
                let suffix = &self.lines[end.line][end.index..];
                let lines_prefix = &self.lines[..begin.line];
                let lines_suffix = &self.lines[end.line + 1..];
```

Gives me the following results:

```
begin.line: 0 len: 0 begin.index: 0
end.line: 0 len: 0 end.index: 0
begin.line: 0 len: 1 begin.index: 1
end.line: 0 len: 1 end.index: 1
begin.line: 0 len: 2 begin.index: 2
end.line: 0 len: 2 end.index: 2
begin.line: 0 len: 3 begin.index: 3
end.line: 0 len: 3 end.index: 3
Render took 28.873649999999543ms & will cause frame drop
.getCanGoBack is not supported by runtime
.getCanGoForward is not supported by runtime
Error: Network request to http://ac.duckduckgo.com/ac/?q=test&type=list has failed:
Render took 26.280446000004304ms & will cause frame drop
WebView with id: undefined is not found
WebView with id: undefined is not found
WebView with id: 0 is not found
begin.line: 0 len: 0 begin.index: 0
end.line: 0 len: 0 end.index: 4
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: begin <= end', ../src/libcore/str/mod.rs:1651
```

So it looks like `end.index` wasn't reset when the text field was otherwise cleared out. I haven't yet traced any further to find what causes this.

**Comment by paulrouget** [comment] 2016-03-15 14:22
So it's probably a regression due to https://github.com/servo/servo/commit/a3d77790a600021c95608d1fd54522ef5c72e1f4

/cc @saurvs

**Comment by paulrouget** [comment] 2016-03-15 14:31
Reduced test case:

```html
<input></input>
<script>
  var i = document.querySelector("input");
  i.focus();
  i.value = "xxxxxxxxx";
  i.setSelectionRange(4,5);
  i.value = "";
</script>
```

Once the page has loaded, just press a key.

**Comment by paulrouget** [comment] 2016-03-15 14:56
I think it's just a matter of clearing the selection in `set_content`.

**Comment by saurvs** [comment] 2016-03-15 15:08
I'll PR a fix for this.

**Comment by jdm** [comment] 2016-03-15 15:42
Great!

**Closed** 2016-03-16 20:49 UTC
Labels: A-browserhtml/P1, A-content/dom, C-assigned
