### ISSUE TITLE
Servo crashes on any page with text: FontCacheThread' panicked ... "No buffer space available"

### ISSUE THREAD

**Issue by andrewguertin** [servo/servo#9555] opened 2016-02-05 13:17 UTC
On my machine, when running servo and loading any page with text, servo crashes and prints the following:

thread 'FontCacheThread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 105, message: "No buffer space available" } }', ../src/libcore/result.rs:746

(Followed by some backtraces and other threads crashing, presumably because they can't talk to the crashed FontCacheThread.)

Looking into this further, the sendmsg() call at https://github.com/servo/ipc-channel/blob/master/platform/linux/mod.rs#L182 is returning -ENOBUFS, making https://github.com/servo/servo/blob/master/components/gfx/font_cache_thread.rs#L144 try to unwrap an Err value as described in the error message.

I'm not sure why sendmsg() is returning -ENOBUFS. The man page says "Normally, this does not occur in Linux.", and googling for "ENOBUFS" mostly brings up people having problems with their network drivers.

This is on gentoo linux.

**Comment by jdm** [comment] 2016-02-05 14:53
Cc @pcwalton

**Comment by veddan** [comment] 2016-03-14 22:05
Apparently you can get that error with `msg_controllen > INT_MAX`.

**Comment by andrewguertin** [comment] 2016-03-18 06:24
```
196	            let result = sendmsg(self.fd, &msghdr, 0);
(rr) p msghdr
$27 = {msg_name = 0x0, msg_namelen = 0, msg_iov = 0x7f3876b44240, msg_iovlen = 1,
       msg_control = 0x7f3876bc99c0, msg_controllen = 16, msg_flags = 0}
```
It doesn't appear that `msg_controllen > INT_MAX` is the problem here, unfortunately.

(It took a while to get it right, but I did confirm this is the right `sendmsg` call)

**Comment by andrewguertin** [comment] 2016-03-18 08:03
A bit more debugging has shown I was wrong in my original message: It's actually the `sendmsg()` call at https://github.com/servo/ipc-channel/blob/master/platform/linux/mod.rs#L258 that fails, and the `Err` gets returned a few lines later at https://github.com/servo/ipc-channel/blob/master/platform/linux/mod.rs#L269

**Comment by andrewguertin** [comment] 2016-03-18 08:45
Changing `bytes_per_fragment` at https://github.com/servo/ipc-channel/blob/master/platform/linux/mod.rs#L228 to a hardcoded value of 8000 makes pages load (though slowly, unsurprisingly). The calculated value with the current code seems to be a little over 212000.

**Comment by eddyb** [comment] 2016-03-28 00:18
@andrewguertin the `INT_MAX` case is only if the flags contain `MSG_CMSG_COMPAT`, given what I'm seeing in strace, another possibility I can think of is `sock_kmalloc` returning NULL.
But that can't be the case, as on x64 the kernel has 36 bytes on the stack and only calls `sock_kmalloc` if that's not enough - and ipc-channel has just 24 bytes of "ctl".

*Goes back to the rabbit hole that is the linux kernel.*

**Comment by eddyb** [comment] 2016-03-28 04:14
I couldn't find anything useful in the kernel, but I tried this workaround:
```diff
-                 if error.0 != libc::EMSGSIZE {
+                 if error.0 != libc::EMSGSIZE && error.0 != libc::ENOBUFS {
```

And so far I haven't gotten another error.

**Comment by Manishearth** [comment] 2016-03-28 05:04
Part of the cause is https://github.com/servo/servo/issues/10230

**Comment by eddyb** [comment] 2016-03-28 05:06
@Manishearth I'd argue that `ipc-channel` should be able to deal with large packet sizes without failing horribly, even if those sizes can be optimized somewhere else.

**Comment by Manishearth** [comment] 2016-03-28 05:07
Yes, like I said, this is only part of the cause (and as I mentioned in #10230, fixing #10230 is not a complete fix for this issue)

**Comment by larsbergstrom** [comment] 2016-03-28 15:38
cc @antrik

**Comment by eddyb** [comment] 2016-03-28 15:47
I've started looking at other browsers, and found the following:
Chromium uses `SOCK_SEQPACKET` only for the crash handler, and `SOCK_STREAM` for general IPC.

This is relevant, because `sendmsg` for `SOCK_SEQPACKET` is almost identical to `sendmsg` for `SOCK_DGRAM` and they can both fail to allocate a buffer (in this case, 256kB), resulting in `ENOBUFS`, whereas `SOCK_STREAM` does fragmentation in the kernel and can't really fail in the same way.

Sadly, you can't just change the socket type and be done with it, you end up with just a gray window.

Firefox, OTOH, [uses `SOCK_SEQPACKET` for `gonk/libui` input events](https://dxr.mozilla.org/mozilla-central/rev/63be002b4a803df1122823841ef7633b7561d873/widget/gonk/libui/InputTransport.cpp#121) and [sets `SO_{RCV,SND}BUF` to 32kB](https://dxr.mozilla.org/mozilla-central/rev/63be002b4a803df1122823841ef7633b7561d873/widget/gonk/libui/InputTransport.cpp#130-134).
I'll try that approach and see if it helps.

**Comment by eddyb** [comment] 2016-03-28 16:36
I can't get the error to trigger again, with the changes in servo/ipc-channel#57. Hopefully that's the end of it.

**Closed** 2016-03-29 07:12 UTC
Labels: I-panic, P-linux

**Comment by antrik** [comment] 2016-03-29 21:50
@eddyb I don't think SOCK_STREAM alone could be made to work for the MPSC case. I did vaguely consider using it for the dedicated channel for large messages though (which is what apparently triggered the problem here) -- it's worth investigating the performance implications.

As for the actual ENOBUFS problem, I have had this on my TODO list for a while, as I was sporadically seeing it in the testsuite. However, I didn't consider it a priority, as it is rare on my system (I haven't actually seen it in Servo at all), and I didn't realise it's a regression...

Anyway, as it's intermittent (for me at least) -- and going by what I can gather from the description in the man page -- I tend to think the right way of handling this is simply retrying the `send()` call. This shouldn't be hard to implement: the main challenge will be finding a reliable way of reproducing the issue...

**Comment by eddyb** [comment] 2016-03-29 22:18
@antrik Maybe having a hundred Chromium tabs open would be a start?
FWIW, [just retrying](https://github.com/servo/servo/issues/9555#issuecomment-202224827) didn't solve the issue.
And I haven't gotten it since that attempted fix which made it into master, so I don't know how you'd reproduce it nowadays.

**Comment by antrik** [comment] 2016-04-03 19:56
For the record: after investigating the issue, I don't think that it was in fact related to the use of a dedicated channel. The problem has always existed; and while the dedicated channel might make it *somewhat* more likely to get triggered (because we have one more packet in flight at the same time), I don't think it makes all that much difference. It definitely can get triggered without the dedicated channel as well.
