### ISSUE TITLE
Intermittent failure of/_mozilla/css/position_fixed_a.html

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9181] opened 2016-01-07 06:32 UTC
```
  ▶ FAIL [expected PASS] /_mozilla/css/position_fixed_a.html
  └   → /_mozilla/css/position_fixed_a.html 087766eb19f87af3cb49aec119e22e907464c599
/_mozilla/css/position_fixed_b.html b9b48b9cf8fab296dc24fe522831dc06c4617acc
Testing 087766eb19f87af3cb49aec119e22e907464c599 == b9b48b9cf8fab296dc24fe522831dc06c4617acc
```

**Comment by jdm** [comment] 2016-01-07 07:21
Duplicate of #9106.

**Closed by jdm** 2016-01-07 07:21 UTC
Labels: I-intermittent
