### ISSUE TITLE
Error opening reddit in Windows Servo

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#16923] opened 2017-05-18 04:51 UTC
From the showcase link:

assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()
### Servo Version:
Servo 0.0.1-10cc59dd2e
### Backtrace:
```

WARNING: <Constellation>: creating replacement pipeline for about:failure
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: Panic hook called.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
ERROR: assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()

stack backtrace:
   0:     0x7ff6da6d49bf - memchr::memchr3::h7f7c867ff5b0a3a2
   1:     0x7ff6da6d56a2 - backtrace::capture::Backtrace::new::h5f3de869c0349b3d
   2:     0x7ff6d9ee96ce - <constellation::constellation::FromCom

**Comment by jdm** [comment] 2017-05-31 20:38
This might be #17072.

**Comment by nox** [comment] 2017-10-07 09:32
Closing as duplicate of #14239.

**Closed by nox** 2017-10-07 09:32 UTC
Labels: A-webcompat, I-panic
