### ISSUE TITLE
Passing --nocapture to test-unit doesn't work

### ISSUE THREAD

**Issue by jdm** [servo/servo#20280] opened 2018-03-12 17:59 UTC
`./mach test-unit -p profile --nocapture` yields:
```
error: Unknown flag: '--nocapture'

Usage:
    cargo test [options] [TESTNAME] [--] [<args>...]
```

**Comment by SimonSapin** [comment] 2018-03-12 18:39
Try adding `--` to separate test-program args from cargo args. Or maybe twice to also separate cargo args from mach args.

**Comment by jdm** [comment] 2018-03-12 19:12
Neither `./mach test-unit -p profile -- --nocapture` nor `./mach test-unit -p profile -- -- --nocapture` made a difference.

**Comment by jdm** [comment] 2018-03-12 19:13
Although maybe that's a change that needs to be made to the invocation of cargo from the mach command instead.

**Comment by SimonSapin** [comment] 2018-03-12 22:41
I’ve just looked at the code, `test-unit` does not accept arbitrary arguments or pass them through to cargo. Maybe it should, but in the meantime you can probably use `./mach cargo test` or even `cargo test`.

**Comment by jdm** [comment] 2018-03-12 23:13
Sure, but test-unit does accept an explicit --nocapture argument, so it's surprising that it's broken.

**Comment by SimonSapin** [comment] 2018-03-13 12:30
Oh I missed that, sorry.

It does appear to work for me though:

```
$ ./mach test-unit -p profile --nocapture -v
[…]
     Running `/home/simon/servo/target/debug/deps/profile_tests-131711d7e4e31353 --nocapture`
[…]

**Comment by saito828koki** [comment] 2024-08-17 20:36
As I checked on my local Mac, it seems to be working correctly.

`test-unit` command can accept `--nocapture` arg as it's defined here

https://github.com/servo/servo/blob/20273b062af969152635306c3df2a3a1364ac4d1/python/servo/testing_commands.py#L116-L117

When `--nocapture` is set, it is converted into a flag for cargo test with preceding `--`
https://github.com/servo/servo/blob/20273b062af969152635306c3df2a3a1364ac4d1/python/servo/testing_commands.py#L202-L203 

Could anyone still reproduce this issue or can we close this issue?

**Closed** 2024-08-17 21:51 UTC
Labels: I-bustage, A-testing, L-python
