### ISSUE TITLE
localeCompare() doesn't return the expected value

### ISSUE THREAD

**Issue by apptimise** [servo/servo#13788] opened 2016-10-16 19:11 UTC
Minimal example:

var b = "aZ";
var a= "ab"
var ret = b.localeCompare(a); **// returns -8 on Samsung Internet for Android 4.0**

**Comment by emilio** [comment] 2016-10-16 19:29
Hi, thanks for reporting this :)

**Comment by emilio** [comment] 2016-10-16 19:38
We never call `JS_SetLocaleCallbacks`, so they should use the default. I'll try with a debug build.

**Comment by Ms2ger** [comment] 2016-10-18 08:41
Assigned to @emilio for investigation

**Comment by emilio** [comment] 2016-10-18 14:50
This is not a bug, SpiderMonkey by default (in `js::str_localecompare` returns the difference between the first two different characters, which in this case is -8.

From the ECMA spec this is completely valid:

> The actual return values are implementation-defined to permit implementers to encode additional information in the value, but the function is required to define a total ordering on all Strings. This function must treat Strings that are canonically equivalent according to the Unicode standard as identical and must return 0 when comparing Strings that are considered canonically equivalent.

So I'm closing this, feel free to reopen if anyone disagrees with this diagnostic :)

**Comment by apptimise** [comment] 2016-10-18 20:04
I don't agree. The result of the comparison should be in the range {-1, 0, +1} http://www.w3schools.com/jsref/jsref_localecompare.asp
Even if the return value is "implementation-defined", it should return a positive number. "aZ" is definitely larger than "ab". The problem is the inconsistency. All other browsers return "+1". It should be okay to return "+8" or a positive number, but not "-8"! It changes the whole functionality

**Comment by emilio** [comment] 2016-10-18 22:06
Hmm... Ok, so this is spec compliant (because the spec only requires to define a total order), and the current behavior is the same of `strcoll`, which is sort of the expected thing.

That being said, since nobody else does this, I guess it makes sense to switch.

Seems like the easiest way to get this working is calling compiling SM with `EXPOSE_INTL_API`, so we get the self-hosted `localeCompare`, which ends-up calling http://searchfox.org/mozilla-central/source/js/src/builtin/Intl.cpp#1083.

@jdm, @Ms2ger, do you think that's reasonable? I can try to do that tomorrow, I guess.

**Comment by jdm** [comment] 2016-10-18 23:29
Seems reasonable.

**Closed** 2016-10-25 11:40 UTC
Labels: A-content/script
