### ISSUE TITLE
Servo deosn't load web pages on proxy.

### ISSUE THREAD

**Issue by iampritishpatil** [servo/servo#11994] opened 2016-07-01 06:34 UTC
On ubuntu 16.04 the nightly build from download.servo.org on 1st July 2016 doesn't take system proxy and fails to load any webpages.

**Comment by moiSurGitHub** [comment] 2016-07-08 07:46
I confirm
it's ok if I use proxychains at the beginning of the command
`proxychains ./runservo.sh`

**Comment by nox** [comment] 2017-10-02 08:17
Closing as duplicate of #18673.

**Closed by nox** 2017-10-02 08:17 UTC
Labels: A-network
