### ISSUE TITLE
Jump tag seems to have a performance when you click on one jump tag to another.

### ISSUE THREAD

**Issue by nhirata** [servo/servo#9671] opened 2016-02-17 02:12 UTC
1) ./mach run http://people.mozilla.org/~nhirata/html_tp/jumptag.html
2) click on "Go to Bottom"
3) immediately click "Go to Top"
Expected: you will scroll to the top immediately
Actual: doesn't respond.

**Comment by jdm** [comment] 2016-02-17 03:26
Interestingly it works immediately if you scroll the page.

**Comment by ConnorGBrewster** [comment] 2016-03-19 17:53
Could I work on this one?

**Comment by jdm** [comment] 2016-03-19 21:08
It's available; unfortunately I can't provide any suggestions for where to start investigating.

**Comment by ConnorGBrewster** [comment] 2016-03-20 04:27
After doing a bit of digging and messing around. It seems like the issue is that the view scrolls but when looking for element locations, it thinks the elements are where they were before the scroll happens. You can see this by clicking "Go to bottom" and then hovering your mouse where that link was positioned prior to the scroll and you will see that the cursor will change to the hand indicating that there is a link there.

**Comment by ConnorGBrewster** [comment] 2016-03-20 04:47
It looks like `self.send_viewport_rects_for_all_layers();` needs to be called by the compositor after the scroll is performed. Doing this in the `perform_updates_after_scroll` function seems to fix the issue, although I am not sure if this is the correct location to call that. Does anyone have any insight on where that should be called?

**Comment by jdm** [comment] 2016-03-20 13:33
Cc @glennw for the last question.

**Comment by glennw** [comment] 2016-03-22 02:27
If you look at process_pending_scroll_events(), the perform_updates_after_scroll() is called once for each pending scroll event, but send_viewport_rects_for_all_layers() is only called once after all pending scroll events have been handled.

I don't know this code particularly well, but I guess that's done for performance reasons when multiple scroll events have been queued.

So perhaps the simplest way might be to call send_viewport_rects_for_all_layers() directly after the relevant call to perform_updates_after_scroll() (I guess this is coming from scroll_layer_to_fragment_point_if_necessary or scroll_fragment_to_point?).

**Comment by ConnorGBrewster** [comment] 2016-03-24 03:45
This issue is resolved by PR #10112

**Comment by jdm** [comment] 2016-03-24 03:48
Thanks!

**Closed by jdm** 2016-03-24 03:48 UTC
Labels: A-content/dom
