### ISSUE TITLE
Incorrect serialization of border-radius

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#12655] opened 2016-07-29 13:50 UTC
``` rust
let x = document.createElement("div");
x.style.borderRadius = "1% 2% 3% 4% / 5% 6% 7% 8%"
console.log(x.style.borderRadius);
console.log(x.style.cssText);
```

This should produce the same string as the input. It instead produces `4% 8% 3% 7% 2% 6% 1% 5%`, which is invalid syntax for the property.

I can't find the spec for border-radius serialization so I'm not sure, however. https://drafts.csswg.org/css-backgrounds-3/#border-radius doesn't mention anything. I don't even see a ToCss impl for border-radius so I'm not sure where the code for this is.

cc @SimonSapin

**Comment by craftytrickster** [comment] 2016-08-01 23:51
This happens to be the one shorthand I did not implement here https://github.com/servo/servo/pull/12572 given that I also could not determine a correct way to serialize it either.

After the above PR is merged, the place to implement it will be in the border.mako.rs file.

**Comment by Manishearth** [comment] 2016-08-02 00:41
https://github.com/servo/servo/pull/12680 contains BorderRadius, with serialization, using the basic-shape definition.

The serialization isn't completely correct (it's supposed to print the minimum equivalent thing, currently it just prints everything), but I plan to fix it

**Comment by Manishearth** [comment] 2016-08-02 10:16
Ah, this is because `get_shorthand_appendable_value` doesn't use ToCss definitions in the first place, it just appends the shorthands together. Probably should make it use ToCss, and add ToCss impls for the shorthands, with an autogenerate option for this default.

**Comment by craftytrickster** [comment] 2016-08-02 12:21
ToCss only takes a self parameter and a writeable parameter - https://servo.github.io/rust-cssparser/cssparser/trait.ToCss.html.

The problem is that the Shorthand enum does not actually contain its Longhand values, which is why I did not use that approach.

**Comment by Manishearth** [comment] 2016-08-02 15:01
I looked a bit more at the code.

Wherever the serialization methods are used (once in cssstyledeclaration.rs and once in the ToCss impl of the whole property declaration block), we call `shorthand.longhands()`, collect longhand values from there, and push it in, and treat it as an iterator in the serialize_shorthand methods.

Instead, serialize_shorthand_ should take just the shorthand, and the property decl block, and internally handle everything. Furthermore, we provide `shorthand.longhands_struct()` which provides the longhands struct for the non-CSS-variable serialization case (we still need to iterate through the declarations) otherwise.

We autoimpl ToCss on the `Longhands` structs unless there's a mako parameter asking us not to do so, and use this.

**Comment by Manishearth** [comment] 2016-08-02 15:07
I'll work on this unless someone else wants to pick it up.

**Comment by Manishearth** [comment] 2016-08-02 16:08
Oh, I didn't notice #12572 existed. Sorry!

After #12680 lands, the serialization of border-radius can be done by constructing a `values::computed::basic_shape::BorderRadius` from the longhands and running to_css on that.

**Comment by pyfisch** [comment] 2017-04-11 17:57
I am working on this.

**Closed** 2017-04-14 18:16 UTC
Labels: A-content/css
