### ISSUE TITLE
assertion failed: self.suspended_since.get().is_some()

### ISSUE THREAD

**Issue by danrien** [servo/servo#14749] opened 2016-12-28 02:17 UTC
Was attempting to hit the "back" button after browsing to Ars Technica when this occurred:

assertion failed: self.suspended_since.get().is_some()
### Servo Version:
Servo 0.0.1-37a5e29
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: Message sent to closed pipeline (1,15).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(13) }>: Storage event sent to closed pipeline (1,13).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(13) }>: Storage event sent to closed pipeline (1,13).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(13) }>: Storage event sent to closed pipeline (1,13).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(13) }>: Storage event sent to closed pipeline (1,13).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(13) }>: Storage event sent to closed pipeline (1,13).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(13) }>: Storage event sent to closed pipeline (1,13).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(13) }>: Storage event sent to closed pipeline (1,13).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(13) }>: Storage event sent to closed pipeline (1,13).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(13) }>: Storage event sent to closed pipeline (1,13).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(13) }>: Storage event se
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-12-28 05:36
This is a duplicate of #13716. Thanks for reporting it!

**Closed by jdm** 2016-12-28 05:36 UTC
