### ISSUE TITLE
assertion failed: count_cell.get() > 0

### ISSUE THREAD

**Issue by aaronharder** [servo/servo#12047] opened 2016-07-01 12:55 UTC
assertion failed: count_cell.get() > 0
### URL:
http://i.entropy.cc/
### Backtrace:
```
frame #0  - 0x00000001055526ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000000105552651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000000104823086 - _<F as alloc..boxed..FnBox<A>>::call_box::h6059122298f825d8
frame #3  - 0x00000001054c6947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010573a844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000000010403dae4 - std::panicking::begin_panic::h0bf39f6d43ab9349
frame #6  - 0x00000001046ca262 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h315c5e417b85cb3a
frame #7  - 0x00000001046c7d65 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::hc0416bc7ab472afc
frame #8  - 0x000000010482e95c - script::script_thread::ScriptThread::handle_msg_from_script::hd1f5e7b2423a8c64
frame #9  - 0x000000010488aa71 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc67d8b381c013b79
frame #10 - 0x000000010487073f - script::script_thread::ScriptThread::handle_msgs::h236c5be60a207bea
frame #11 - 0x0000000104821907 - std::panicking::try::call::h645a328f039d97c6
frame #12 - 0x000000010575646b - __rust_try
frame #13 - 0x0000000105756405 - __rust_maybe_catch_panic
frame #14 - 0x0000000104822ab4 - _<F as alloc..boxed..FnBox<A>>::call_box::h3db95636eb747818
frame #15 - 0x0000000105751ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #16 - 0x00007fff8d70499c - _pthread_body
frame #17 - 0x00007fff8d704919 - _pthread_start

```

**Comment by izgzhen** [comment] 2016-07-01 13:36
The assertion failed should be here: https://doc.servo.org/script/dom/document/struct.Document.html#method.decrement_script_blocking_stylesheet_count

I am not familiar with stylesheets implementation but I will try to give some comments before experts come.

**Comment by Manishearth** [comment] 2016-07-01 13:53
Not sure what happened here.

The page first fetches two CSS files, and does an increment/decrement for them.

Then, it hits increment for a third CSS file, but by the time it has reached the decrement call it is already 0.

**Comment by Manishearth** [comment] 2016-07-01 14:02
This is very curious.

I set a watchpoint on the document's count_cell, and breakpoints on the increment_decrement functions (﻿https://github.com/servo/servo/blob/736feec0ad14650e21cb899d01e60d168b3e7e2e/components/script/dom/document.rs#L1218)

For the first two stylesheets I get what I expect, increment, watchpoint, increment, watchpoint, decrement, watchpoint, decrement, watchpoint.

For the third stylesheet, I hit the increment brkpt but the watchpoint is not hit.

This feels like a compiler bug. I'm not sure.

**Comment by eddyb** [comment] 2016-07-01 14:25
Pretty sure this is a dupe of #10254. The disassembly I've seen from @Manishearth looks good (albeit a tad confusing), and it was in debug mode so it couldn't have been an optimization at fault.

**Comment by Manishearth** [comment] 2016-07-01 17:05
I think that issue is multiple problems, so I'll keep this open for now.

**Comment by jdm** [comment] 2016-07-02 15:34
The issue here is based on creating a stylesheet via innerHTML, which creates a document fragment and confuses the logic about when the stylesheet should be considered parser-inserted or not.

**Comment by Manishearth** [comment] 2016-07-02 15:51
Be very wary of memory corruption and whatnot.

This doesn't feel like a logic bug so far, bit I'll do a thorough investigation Monday.

**Comment by jdm** [comment] 2016-07-02 15:53
It is absolutely a logic bug. I see no signs of memory corruption. We have a link element that's created in innerHTML that kicks off a load, then it is cloned, and the clone is inserted into the original document and another load starts. Both loads use the same document and the logic gets all confused.

**Comment by jdm** [comment] 2016-07-02 15:57
This is fixed by the following change:
```
diff --git a/components/script/dom/htmllinkelement.rs b/components/script/dom/htmllinkelement.rs
index 0af0769..2e0dd9a 100644
--- a/components/script/dom/htmllinkelement.rs
+++ b/components/script/dom/htmllinkelement.rs
@@ -194,6 +194,10 @@ impl VirtualMethods for HTMLLinkElement {
 impl HTMLLinkElement {
     fn handle_stylesheet_url(&self, href: &str) {
         let document = document_from_node(self);
+        if !document.is_fully_active() {
+            return;
+        }
+
         match document.base_url().join(href) {
             Ok(url) => {
                 let element = self.upcast::<Element>();
```

**Comment by Manishearth** [comment] 2016-07-02 16:42
> We have a link element that's created in innerHTML that kicks off a load, then it is cloned

Huh. When I looked at it so far I got the appropriate matched number of increments and decrements, just that one of them didn't actually increment (though the document being operated on was the same in all three cases). Will look at again.

**Comment by Manishearth** [comment] 2016-07-04 11:09
Ah, it seems like the increment and decrement are called on different `Document` objects. Not sure if this is a different bug or the same bug that @jdm's comment fixes. I did check for this on Friday, but I guess the addresses looked too similar 😄 

The two documents have the same URLs. I have a [hackily obtained diff](https://gist.github.com/Manishearth/18ad87167f4c7d64125c7ce875523a1b) of the documents, and the difference mostly seems to be in the loading state. Do we replace document dom structs when they finish loading?

Here is the execution of the entropy page, with breakpoints set on increment/decrement, and watchpoints set on the count.

The first half is just two increments and decrements, all on the same document at `0x11ae5f000`, with cell at `0x11ae5f2b8`

```
Thread 26 hit Breakpoint 1, script::dom::document::{{impl}}::increment_script_blocking_stylesheet_count (self=0x11ae5f000)
    at /Users/manishearth/mozilla/voser/components/script/dom/document.rs:1218
warning: Source file is more recent than executable.
1218
(gdb) p self
$1 = (script::dom::document::Document *) 0x11ae5f000
(gdb) n
1219	    pub fn decrement_script_blocking_stylesheet_count(&self) {
(gdb) p count_cell
$2 = (core::cell::Cell<u32> *) 0x11ae5f2b8
(gdb) set language c
Warning: the current language does not match this frame.
(gdb) watch *(int*)0x11ae5f2b8
Hardware watchpoint 3: *(int*)0x11ae5f2b8
(gdb) set language rust
(gdb) c
Continuing.

Thread 26 hit Hardware watchpoint 3: *(int*)0x11ae5f2b8

Old value = 0
New value = 1
core::cell::{{impl}}::set<u32> (self=0x11ae5f2b8, value=1)
    at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcore/cell.rs:211
211	/Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcore/cell.rs: No such file or directory.
(gdb) c
Continuing.
[New Thread 0x1897 of process 2285]

Thread 26 hit Breakpoint 1, script::dom::document::{{impl}}::increment_script_blocking_stylesheet_count (self=0x11ae5f000)
    at /Users/manishearth/mozilla/voser/components/script/dom/document.rs:1218
1218
(gdb) p self
$3 = (script::dom::document::Document *) 0x11ae5f000
(gdb) n
1219	    pub fn decrement_script_blocking_stylesheet_count(&self) {
(gdb) p count_cell
$4 = (core::cell::Cell<u32> *) 0x11ae5f2b8
(gdb) c
Continuing.
[New Thread 0x4813 of process 2285]

Thread 26 hit Hardware watchpoint 3: *(int*)0x11ae5f2b8

Old value = 1
New value = 2
core::cell::{{impl}}::set<u32> (self=0x11ae5f2b8, value=2)
    at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcore/cell.rs:211
211	/Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcore/cell.rs: No such file or directory.
(gdb) c
Continuing.

Thread 26 hit Breakpoint 2, script::dom::document::{{impl}}::decrement_script_blocking_stylesheet_count (self=0x11ae5f000)
    at /Users/manishearth/mozilla/voser/components/script/dom/document.rs:1223
1223	    }
(gdb) p self
$5 = (script::dom::document::Document *) 0x11ae5f000
(gdb) n
1224
(gdb) p count_cell
$6 = (core::cell::Cell<u32> *) 0x11ae5f2b8
(gdb) c
Continuing.
[New Thread 0x18ab of process 2285]

Thread 26 hit Hardware watchpoint 3: *(int*)0x11ae5f2b8

Old value = 2
New value = 1
core::cell::{{impl}}::set<u32> (self=0x11ae5f2b8, value=1)
    at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcore/cell.rs:211
211	/Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcore/cell.rs: No such file or directory.
(gdb) c
Continuing.

Thread 26 hit Breakpoint 2, script::dom::document::{{impl}}::decrement_script_blocking_stylesheet_count (self=0x11ae5f000)
    at /Users/manishearth/mozilla/voser/components/script/dom/document.rs:1223
1223	    }
(gdb) p self
$7 = (script::dom::document::Document *) 0x11ae5f000
(gdb) n
1224
(gdb) p count_cell
$8 = (core::cell::Cell<u32> *) 0x11ae5f2b8
(gdb) c
Continuing.

Thread 26 hit Hardware watchpoint 3: *(int*)0x11ae5f2b8

Old value = 1
New value = 0
core::cell::{{impl}}::set<u32> (self=0x11ae5f2b8, value=0)
    at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcore/cell.rs:211
211	/Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcore/cell.rs: No such file or directory.
(gdb) c
```


At this point, the third script loads, and it increments on a _different_ document (`0x11afb8500`), of course holding a different Cell (`0x11afb87b8`)


```

Thread 26 hit Breakpoint 1, script::dom::document::{{impl}}::increment_script_blocking_stylesheet_count (self=0x11afb8500)
    at /Users/manishearth/mozilla/voser/components/script/dom/document.rs:1218
1218
(gdb) p self
$9 = (script::dom::document::Document *) 0x11afb8500
(gdb) n
1219	    pub fn decrement_script_blocking_stylesheet_count(&self) {
(gdb) p count_cell
$10 = (core::cell::Cell<u32> *) 0x11afb87b8
(gdb) watch *(int*)0x11afb87b8
syntax error in expression, near `)0x11afb87b8'.
(gdb) set language c
(gdb) watch *(int*)0x11afb87b8
Hardware watchpoint 4: *(int*)0x11afb87b8
(gdb) set language rust
(gdb) c
Continuing.
[New Thread 0x1917 of process 2285]
[New Thread 0x1b07 of process 2285]
[New Thread 0x5413 of process 2285]
[New Thread 0x5523 of process 2285]

Thread 26 hit Hardware watchpoint 4: *(int*)0x11afb87b8

Old value = 0
New value = 1
core::cell::{{impl}}::set<u32> (self=0x11afb87b8, value=1)
    at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcore/cell.rs:211
211	/Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcore/cell.rs: No such file or directory.
(gdb) c
Continuing.

Thread 26 hit Breakpoint 2, script::dom::document::{{impl}}::decrement_script_blocking_stylesheet_count (self=0x11ae5f000)
    at /Users/manishearth/mozilla/voser/components/script/dom/document.rs:1223
1223	    }
(gdb) p self
$11 = (script::dom::document::Document *) 0x11ae5f000
(gdb) n
1224
(gdb) p count_cell
$12 = (core::cell::Cell<u32> *) 0x11ae5f2b8
(gdb) c
[crashes]
```

**Comment by Manishearth** [comment] 2016-07-04 11:33
Ah, it's innerHTML. innerHTML creates a temporary document (see `parse_html_fragment`). If that document contains a `<link rel=stylesheet>`, that stylesheet increments the count on the temporary document, but the decrement happens on the real document.

Perhaps in parse_html_fragment we should copy any blocking stylesheet counts back to the main document? I don't think we should be creating documents on innerHTML in the first place anyway.

**Comment by Manishearth** [comment] 2016-07-04 11:35
MWE:

```html
<html>
<body>
<div id=scratch></div>
<script>
document.getElementById('scratch').innerHTML = "<link rel=stylesheet type='text/css' href='example.org' />";
</script>
</body>
</html>
```

**Comment by Ms2ger** [comment] 2016-07-04 11:36
Even if we do keep creating documents, I don't think we should ever load stylesheets in those documents.

**Comment by Manishearth** [comment] 2016-07-04 11:37
Regardless, @jdm's original fix should work too.

**Comment by jdm** [comment] 2016-07-04 13:07
I'm glad to see that we have converged on the same explanation for this issue.

**Comment by jdm** [comment] 2016-07-04 15:29
I have filed https://github.com/whatwg/html/issues/1495 since the spec doesn't differentiate between documents with browsing contexts or not. If it's working as intended then a different fix will be required.

**Closed** 2016-07-05 06:02 UTC
Labels: A-content/dom, C-reproduced, I-panic
