### ISSUE TITLE
milliondollarhomepage.com crashes servo

### ISSUE THREAD

**Issue by tobbi** [servo/servo#15858] opened 2017-03-07 23:18 UTC
URL: http://milliondollarhomepage.com

I am trying the latest nightly build. This is the error message that I got:

`
$ ./servo http://milliondollarhomepage.com
`

`
ERROR:script::dom::bindings::error: Error at http://milliondollarhomepage.com/index_files/:3:9429 Invalid screen name
`

`
ERROR:script::dom::bindings::error: Error at http://milliondollarhomepage.com/index_files/info.json:1:5 __twttr.setFollowersCountAndFollowing is not a function
called `Option::unwrap()` on a `None` value (thread RenderBackend, at src/libcore/option.rs:323)
`

`
ERROR:servo: called `Option::unwrap()` on a `None` value
called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: Other, error: StringError("Unknown Mach error: 46") }) }) (thread main, at src/libcore/result.rs:860)
`

`
ERROR:servo: called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: Other, error: StringError("Unknown Mach error: 46") }) })
assertion failed: mach_sys::mach_port_mod_refs(mach_task_self(), self.port,
                             MACH_PORT_RIGHT_SEND, 1) == KERN_SUCCESS (thread Constellation, at /Users/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.7.0/src/platform/macos/mod.rs:336)
`

`
ERROR:servo: assertion failed: mach_sys::mach_port_mod_refs(mach_task_self(), self.port,
                             MACH_PORT_RIGHT_SEND, 1) == KERN_SUCCESS
`

If there's anything else you need, please tell me.

**Comment by simartin** [comment] 2017-03-11 12:05
I'd like to handle this one

**Comment by nox** [comment] 2017-03-16 12:25
Closing as duplicate of #15884.

**Closed by nox** 2017-03-16 12:25 UTC
