### ISSUE TITLE
OpenHarmony build

### ISSUE THREAD

**Issue by mrego** [servo/servo#30541] opened 2023-10-11 16:41 UTC
@mukilan has been doing an experiment to try to build Servo on OpenHarmony OS (`aarch64-linux-ohos`).

These are the current issues and workarounds:
1. socket2 needs patches for Iovlen type. [GitHub ticket](https://github.com/rust-lang/socket2/issues/451) open but no progress.
2. ipc-channel relies on shm_* functions from libc crate. ohos doesn't have those. Adding features = ['force-inprocess'] in simpleservo/api/Cargo.toml is a workaround to force single process mode like on windows.
3. Compiling freetype-sys requires CMake cross-compilation file to be used:
```
export CMAKE_TOOLCHAIN_FILE_aarch64_linux_ohos=/home/user/dev/ohos/native-linux-x64-3.2.13.5-Release/native/build/cmake/ohos.toolchain.cmake 
``` 
4. Compiling ring crate needs cross compiler to be set correctly (not sure why ~/.cargo/config.toml didn't take effect)
```
export CC_aarch64_linux_ohos=/home/user/dev/ohos/native-linux-x64-3.2.13.5-Release/native/llvm/bin/aarch64-unknown-linux-ohos-clang.sh
```
5. patch components/allocator to disable jemalloc-sys as the native library doesn't support ohos triples
6. The `nix` crate doesn't build since it uses shm_open and other methods not availale on OHOS from libc crate.

Status: Blocked on step 6 - The [nix](https://crates.io/crates/nix) crate doesn't compile because it uses features from C library (e.g shm_open) that are currently unavailable on the ohos target of [libc crate](https://github.com/rust-lang/libc/blob/0d6554f3c2115fb67e53df82a368dac166965cff/src/unix/linux_like/linux/mod.rs#L4178). Unlike other crates below, it doesn't seem this has an easy workaround this since `nix` create is used by multiple dependencies of libservo like winit etc, but needs more investigation.

**Comment by Amanieu** [comment] 2023-10-23 23:07
`shm_open` is not available in the libc crate for ohos targets because OpenHarmony [explicitly chooses not to export these symbols](https://gitee.com/openharmony/docs/blob/master/zh-cn/application-dev/reference/native-lib/third_party_libc/musl-peculiar-symbol.md).

The best way forward would probably be to patch nix to not expose functionality related to shared memory on OpenHarmony.

**Comment by mukilan** [comment] 2023-10-24 07:09
Thanks for the clarification, @Amanieu! For `shm_open` I did assume that was the case as I noticed [android](https://github.com/nix-rust/nix/blob/master/src/sys/mman.rs#L561) also doesn't expose it, so I patched nix locally to follow the same as android. Apart from this, there were many other compilation errors in nix where I had to patch code that was conditional on `target_env=musl ` to be `any(target_env=musl, target_env=ohos)`. A similar fix had to be done in socket2 crate as well.

Not sure if that is the correct fix, but I can open a PR for upstream and add you as reviewer if you don't mind.

Now we are blocked because servo's script_plugin crate requires the `rustc-dev` component and the [prebuilt toolchain](https://gitee.com/openharmony/build/blob/master/prebuilts_download.py) doesn't seem to have this. Do you know how prebuilt rust toolchain is produced?

**Comment by Amanieu** [comment] 2023-10-24 14:43
> Not sure if that is the correct fix, but I can open a PR for upstream and add you as reviewer if you don't mind.

Yes, this is the correct fix.

> Now we are blocked because servo's script_plugin crate requires the rustc-dev component and the [prebuilt toolchain](https://gitee.com/openharmony/build/blob/master/prebuilts_download.py) doesn't seem to have this. Do you know how prebuilt rust toolchain is produced?

Could you use the standard rustup toolchain with -Zbuild-std? This should work in theory but I haven't tried it.

**Comment by Amanieu** [comment] 2024-02-11 10:19
There is ongoing work to promote OpenHarmony to a tier 2 target, at which point it can be installed with rustup without needing -Zbuild-std: https://github.com/rust-lang/rust/pull/120585

**Comment by jschwe** [comment] 2024-02-20 16:40
I tried building servo for ohos today, and it seems we are now actually quite close. I got 718/720 crates compiled.
I'll try to document the current status based on my experiment (including stuff that is already documented in the opening post):

- [ ] Fix `mozjs` build
   - [ ] Add ohos support to [GNU `config.sub`] and/or patch mozjs's vendored version . Status: Submitted patch upstream 
   - [ ] Fix `bindgen` invocation. Status: Have local patch, needs a bit of refactoring before upstreaming. @mukilan has an alternative patch that might be better (haven't looked at it in detail).
- [ ] Fix `bindgen` invocation in `mozangle` build: Status: Have local patch
- [ ] Update `socket2`. Status: Using upstream socket2 `master` works.
- [ ] Bump `egui`, `nix` and `winit`. Status: Blocked on #31278.  It fixed the issues I had with `libc` and `nix`, but since my local base does not match the upstream branch I cherry-picked from, there are still some breakages due to API changes I need to resolve (probably fixed by waiting on the MR to be merged).
- [ ] Minor patches to `components/allocator` and `components/profile` regarding `jemalloc` and profiling
- [ ] Add `force-inprocess` feature on ohos to `ipc_channel`

Temporary workarounds:

- Patch `command_base.py` to not attempt to run `rustup target add`, since ohos is currently a tier 3 target. and  `export RUSTC_BOOTSTRAP=1` to allow `-Zbuild-std` on stable.
- Set of bunch of environment variables : 
<details><summary>ohos.env</summary>
<p>

```
export SDK_BASE=/home/jschwender/tools/ohos-sdk/linux/native-linux-x64-4.0.10.13-Release
export SDK_TARGET_SYSROOT=${SDK_BASE}/native/sysroot

# Preconditions:
# - aarch64-unknown-linux-ohos-clang.sh and *-clang++.sh are in path
# - aarch64-unknown-linux-ohos-ar is in PATH
export CC_aarch64_unknown_linux_ohos=aarch64-unknown-linux-ohos-clang.sh
export CXX_aarch64_unknown_linux_ohos=aarch64-unknown-linux-ohos-clang++.sh
export CC_aarch64_linux_ohos=aarch64-unknown-linux-ohos-clang.sh
#export CC=aarch64-unknown-linux-ohos-clang.sh
#export CXX=aarch64-unknown-linux-ohos-clang++.sh
export CC=${SDK_BASE}/native/llvm/bin/clang
export CXX=${SDK_BASE}/native/llvm/bin/clang++
export CMAKE_TOOLCHAIN_FILE_aarch64_unknown_linux_ohos=${SDK_BASE}/native/build/cmake/ohos.toolchain.cmake
export PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_ohos="${SDK_TARGET_SYSROOT}"
export PKG_CONFIG_PATH_aarch64_unknown_linux_ohos="${SDK_TARGET_SYSROOT}/usr/lib/pkgconfig:${SDK_TARGET_SYSROOT}/usr/share/pkgconfig"
export LIBCLANG_PATH=${SDK_BASE}/native/llvm/lib

export CMAKE_C_COMPILER_aarch64_unknown_linux_ohos=aarch64-unknown-linux-ohos-clang.sh
export CMAKE_CXX_COMPILER_aarch64_unknown_linux_ohos=aarch64-unknown-linux-ohos-clang++.sh


```

</p>
</details>


[GNU `config.sub`]: https://git.savannah.gnu.org/cgit/config.git/tree/config.sub

**Comment by matlu** [comment] 2024-03-06 18:50
@jschwe Can you give it another try now that **Promote OpenHarmony targets to tier 2** has landed?
And share your findings?

Thanks!

**Comment by jschwe** [comment] 2024-03-06 19:30
@matlu I think the tier 2 status for OHOS will arrive in stable Rust 1.78. However, I wasn't blocked on this, I just set `RUSTC_BOOTSTRAP=1` to get nightly features on stable rust and used `-Zbuild-std` to build the standard library from source. I updated my previous comment (3 comments above) with the changes I did, and the current status of each of them. 

I think the main remaining thing that needs to be done is to port the android apk to an OpenHarmony app. I got preempted with a different task, but I'll be in China next week and hope I can grab an OpenHarmony colleague while I'm there and get a quick port running.

**Comment by Amanieu** [comment] 2024-03-06 19:31
Could you test the tier 2 target on a nightly compiler? It should now be available via rustup. It would be good to catch any issues before it reaches stable.

**Comment by jschwe** [comment] 2024-03-11 06:41
> Could you test the tier 2 target on a nightly compiler?

For now I can confirm that `ripgrep` compiles on nightly for `ohos`  and runs fine on an OpenHarmony phone. I haven't tested anything else yet, but I'll message you if I run into any issues.

**Closed** 2024-06-28 14:01 UTC
Labels: A-build
