### ISSUE TITLE
FAIL [expected PASS] /_mozilla/css/list_item_overflow.html

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#9736] opened 2016-02-24 02:24 UTC
```
Ran 4601 tests finished in 229.0 seconds.
  • 4600 ran as expected. 1376 tests skipped.
  • 1 tests failed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected PASS] /_mozilla/css/list_item_overflow.html
  └   → /_mozilla/css/list_item_overflow.html c77b76cb0b21a76ef83bc4af7a4c8e31c0dba544
/_mozilla/css/list_item_overflow_ref.html 29ee0288024e0ed67b3d8fd38f28ab146e32dcb6
Testing c77b76cb0b21a76ef83bc4af7a4c8e31c0dba544 == 29ee0288024e0ed67b3d8fd38f28ab146e32dcb6
```

**Comment by jdm** [comment] 2016-02-24 02:46
Duplicate of #9278.

**Closed by jdm** 2016-02-24 02:46 UTC
Labels: I-intermittent
