### ISSUE TITLE
nightly build doesn't launch on Debian 8.5

### ISSUE THREAD

**Issue by JayVii** [servo/servo#12242] opened 2016-07-04 21:12 UTC
```
Vortex :: ~/Downloads/servo » RUST_BACKTRACE=1 ./runservo.sh

thread 'main' panicked at 'Failed to create window.: OsError("GL context creation failed")', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x7f925984e34f - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x7f9259855f7b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x7f9259855bdf - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x7f92597347c7 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
   5:     0x7f925983bbac - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   6:     0x7f92598561c1 - std::panicking::begin_panic::he426e15a3766089a
   7:     0x7f925983d41a - std::panicking::begin_panic_fmt::hdddb415186c241e7
   8:     0x7f925985615e - rust_begin_unwind
   9:     0x7f925988c75f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  10:     0x7f9257a28000 - core::result::unwrap_failed::hd132ba2b7d75f379
  11:     0x7f9257a26e04 - glutin_app::window::Window::new::h750be0f1f60f008a
  12:     0x7f9257a25e00 - glutin_app::create_window::hae774cdda1762e66
  13:     0x7f92579cf105 - servo::main::h6924e5658370f6b5
  14:     0x7f9259855558 - std::panicking::try::call::h852b0d5f2eec25e4
  15:     0x7f92598603bb - __rust_try
  16:     0x7f925986035e - __rust_maybe_catch_panic
  17:     0x7f9259854ffe - std::rt::lang_start::hfe4efe1fc39e4a30
  18:     0x7f9254e65b44 - __libc_start_main
  19:     0x7f92579ce0c9 - <unknown>
  20:                0x0 - <unknown>
```
System-stats (if necessary, since this is very low-end hardware):
```
CPU: Single core Intel Atom N450
GPU: Intel Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller
Xorg: X.Org 1.16.4
Resolution: 1024x600@60.02hz
GLX Renderer: Mesa DRI Intel IGD
GLX Version: 2.1 Mesa 10.3.2
```

**Comment by jdm** [comment] 2016-07-04 21:13
This is a duplicate of #12053. Thanks for reporting it!

**Closed by jdm** 2016-07-04 21:13 UTC
