### ISSUE TITLE
Tokens not found

### ISSUE THREAD

**Issue by johansigfrids** [servo/servo#13391] opened 2016-09-23 09:42 UTC
Tokens not found
### Servo Version:
Servo 0.0.1-ca30ad7
### Backtrace:
```

WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
WARNING: <Constellation>: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) } handling mozbrowser event after closure.
WARNING: <Constellation>: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) } iterated after closure.
WARNING: <Constellation>: Finding mozbrowser ancestor for pipeline (1,2) after closure.
WARNING: <Constellation>: Finding mozbrowser ancestor for pipeline (1,2) after closure.
WARNING: <Constellation>: Removed forward history after pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) } closure.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(4), index: PipelineIndex(1) }>: FIXME: </script> not fully implemented
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(4), index: PipelineIndex(1) }>: FIXME: </script> not fully implemented
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(4), index: PipelineIndex(1) }>: FIXME: </script> not fully implemented
WARNING: <ScriptThread Pipel
...
```
This report was generated by the browser.html issue reporter.

**Comment by johansigfrids** [comment] 2016-09-23 09:42
This was when loading http://spf13.com/post/joining-go-team-at-google

**Comment by jdm** [comment] 2016-09-23 14:37
Duplicate of #12799. Should be fixed in tomorrow's nightly; thanks for reporting!

**Closed by jdm** 2016-09-23 14:37 UTC
