### ISSUE TITLE
Intermittent failure of etc/ci/manifest_changed.sh

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#11859] opened 2016-06-24 20:51 UTC
http://build.servo.org/builders/android/builds/1563
```
bash ./etc/ci/manifest_changed.sh
 in dir /home/servo/buildbot/slave/android/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['bash', './etc/ci/manifest_changed.sh']
 environment:
  ANDROID_NDK=/home/servo/android/ndk/current/
  ANDROID_SDK=/home/servo/android/sdk/current/
  ANDROID_TOOLCHAIN=/home/servo/android/toolchain/current/
  CARGO_HOME=/home/servo/.cargo
  CCACHE=/usr/bin/ccache
  DISPLAY=:0
  HOME=/home/servo
  PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/home/servo/android/sdk/current/platform-tools:/home/servo/android/toolchain/current/bin
  PWD=/home/servo/buildbot/slave/android/build
  RUST_BACKTRACE=1
  SERVO_CACHE_DIR=/home/servo/.servo
  SHELL=/bin/bash
  TERM=linux
  UPSTART_INSTANCE=
  UPSTART_JOB=buildbot-slave
 using PTY: False
program finished with exit code 1
```

**Comment by jdm** [comment] 2016-06-27 19:10
Looks like this is actually a duplicate of #11858, based on my on-builder debugging:
```
servo@ip-172-31-34-111:~/buildbot/slave/arm32/build$ ./etc/ci/manifest_changed.sh ; echo $?
starting manifest update
Error running mach:

    ['test-wpt', '--manifest-update', '--binary=', 'SKIP_TESTS']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'/usr/bin/openssl', 'ca', '-config', '/tmp/tmpoIirbA/openssl.cfg', '-batch', '-create_serial', '-keyfile', '/tmp/tmpoIirbA/cakey.pem', '-passin', 'pass:web-platform-tests', '-selfsign', '-extensions', 'v3_ca', '-in', '/tmp/tmpoIirbA/careq.pem', '-out', '/tmp/tmpoIirbA/cacert.pem']' returned non-zero exit status 1

  File "/home/servo/buildbot/slave/arm32/build/python/servo/testing_commands.py", line 328, in test_wpt
    return self.wptrunner(run_file, **kwargs)
  File "/home/servo/buildbot/slave/arm32/build/python/servo/testing_commands.py", line 348, in wptrunner
    return run_globals["run_tests"](**kwargs)
  File "/home/servo/buildbot/slave/arm32/build/tests/wpt/run_wpt.py", line 13, in run_tests
    return run.run_tests(paths=paths, **kwargs)
  File "/home/servo/buildbot/slave/arm32/build/tests/wpt/run.py", line 36, in run_tests
    success = wptrunner.run_tests(**kwargs)
  File "/home/servo/buildbot/slave/arm32/build/tests/wpt/harness/wptrunner/wptrunner.py", line 155, in run_tests
    env_options) as test_environment:
  File "/home/servo/buildbot/slave/arm32/build/tests/wpt/harness/wptrunner/environment.py", line 104, in __enter__
    self.config = self.load_config()
  File "/home/servo/buildbot/slave/arm32/build/tests/wpt/harness/wptrunner/environment.py", line 152, in load_config
    key_file, certificate = self.ssl_env.host_cert_path(hosts)
  File "/home/servo/buildbot/slave/arm32/build/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 351, in host_cert_path
    key, cert = self._generate_host_cert(hosts)
  File "/home/servo/buildbot/slave/arm32/build/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 371, in _generate_host_cert
    self._generate_ca()
  File "/home/servo/buildbot/slave/arm32/build/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 332, in _generate_ca
    "-out", cert_path)
  File "/home/servo/buildbot/slave/arm32/build/tests/wpt/web-platform-tests/tools/sslutils/openssl.py", line 70, in __call__
    output=stdout)
1
```

**Comment by asajeffrey** [comment] 2016-06-27 20:14
@jdm: we did start seeing them both at the same time, so it wouldn't be too surprising if it's the same root cause.

**Closed** 2016-06-27 22:15 UTC
Labels: I-intermittent
