### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

### ISSUE THREAD

**Issue by F1NYA** [servo/servo#13559] opened 2016-10-03 14:48 UTC
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
### Servo Version:
Servo 0.0.1-7da20f2
### Backtrace:
```

WARNING: <Constellation>: Finding mozbrowser ancestor for pipeline (1,7) after closure.
WARNING: <Constellation>: Closing pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(7) } twice.
WARNING: <Constellation>: removing pending frame change for failed pipeline
WARNING: <Constellation>: creating replacement pipeline for about:failure
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: layout thread unreachable - leaking layout data
ERROR: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

stack backtrace:
   0:        0x10321848e - backtrace::backtrace::trace::h0e60ef08c7c34e9f
   1:        0x10321877c - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
   2:        0x1032051a5 - constellation::constellation::log_entry::h150b8c3e0e6ed8c6
   3:        0x103204022 - _<constellation..constellation..FromCompositorLogger as log..Log>::log::h733ab0b3b27be21e
   4:        0x103a2d691 - log::__log::h68a9f892b25070c1
   5:        0x10218a920 - servo::main::_{{closure}}::h5e45f4c70b99418d
   6:        0x103a90443 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   7:        0x103a90314 - std::panicking::begin_panic::hfbeda5aad583dc32
   8:        0x103a90232 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
   9:        0x103a90197 - rust_begin_unwind
  10:        0x103abd19d - core::panicking::panic_fmt::h4395919ece15c671
  11:        0x10323cd58 - core::result::unwrap_failed::h554a4e9647bf676d
  12:        0x103282915 - _<layout..query..LayoutRPCImpl as script_layout_interface..rpc..LayoutRPC>::hit_test::ha0d5d694ec9b8b7e
  13:        0x1027f7316 - script::dom::document::Document::handle_mouse_move_event::hae566fecafbcecb4
  14:        0x1029ce137 - script::script_thread::ScriptThread::handle_event::hd307bc1d53962edd
  15:        0x1029aa634 - script::script_thread::ScriptThread::handle_msg_from_constellation::h572b875421464136
  16:        0x102b4f7e2 - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h3b531676f968ec2d
  17:        0x1029a4f96 - script::script_thread::ScriptThread::handle_msgs::h80bbe941d10914cb
  18:        0x102616947 - std::panicking::try::do_call::hb6fdaa2bf6ac6b25
  19:        0x103a9174a - __rust_maybe_catch_panic
  20:        0x1026e7456 - _<F as alloc..boxed..FnBox<A>>::call_box::h0695cf1d19297315
  21:        0x103a8f364 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  22:     0x7fff954a999c - _pthread_body
  23:     0x7fff954a9919 - _pthread_start
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-10-03 16:21
This looks like a duplicate of #13463. Thanks for reporting it!

**Closed by jdm** 2016-10-03 16:21 UTC
