### ISSUE TITLE
assertion failed: self.suspended_since.get().is_some()

### ISSUE THREAD

**Issue by russellsayshi** [servo/servo#13780] opened 2016-10-15 21:14 UTC
assertion failed: self.suspended_since.get().is_some()
### Servo Version:
Servo 0.0.1-697e197
### Backtrace:
```

WARNING: <Constellation>: Closing frame FrameId { namespace_id: PipelineNamespaceId(63), index: FrameIndex(9) } twice.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(63), index: PipelineIndex(10) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: FIXME: </script> not fully implemented
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }/PipelineId { namespace_id: PipelineNamespaceId(63), index: PipelineIndex(1) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }/PipelineId { namespace_id: PipelineNamespaceId(63), index: PipelineIndex(1) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }/PipelineId { namespace_id: PipelineNamespaceId(63), index: PipelineIndex(1) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }/PipelineId { namespace_id: PipelineNamespaceId(63), index: PipelineIndex(4) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }/PipelineId { namespace_id: PipelineNamespaceId(63), index: PipelineIndex(4) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }/PipelineId { namespace_id: PipelineNamespaceId(63), index: PipelineIndex(4) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }/PipelineId { namespace_id: PipelineNamespaceId(63), index: PipelineIndex(7) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(63), index: PipelineIndex(11) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }/PipelineId { namespace_id: PipelineNamespaceId(63), index: PipelineIndex(7) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNames
...
```
This report was generated by the browser.html issue reporter.

**Comment by emilio** [comment] 2016-10-16 12:00
Hi, thanks for reporting this, do you know in which url were you? Otherwise it's going to be really hard to duplicate.

**Comment by jdm** [comment] 2016-10-18 21:15
http://www.bloomberg.com/news/articles/2016-10-18/outspending-wall-street-2-to-1-silicon-valley-takes-washington was one URL from #13824.

**Comment by jdm** [comment] 2016-10-20 19:31
```
I believe I was clicking on the back button multiple times on Ars Technica when I got this error report.
```
from #13859.

**Comment by ConnorGBrewster** [comment] 2016-10-20 21:46
Sound like this may be an issue with history traversal.

**Comment by emilio** [comment] 2016-10-29 20:42
Closing this as a dupe of https://github.com/servo/servo/issues/13716, which was filled before and also contains relevant info and STR.

**Closed by emilio** 2016-10-29 20:42 UTC
Labels: A-constellation, A-content/script, C-duplicate
