### ISSUE TITLE
Android nightly failing again

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#10339] opened 2016-04-01 09:41 UTC
CC @larsbergstrom 
```
 (view as text)

./mach package -r
 in dir /home/servo/buildbot/slave/android-nightly/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['./mach', 'package', '-r']
 environment:
  ANDROID_NDK=/home/servo/android/ndk/current/
  ANDROID_SDK=/home/servo/android/sdk/current/
  ANDROID_TOOLCHAIN=/home/servo/android/toolchain/current/
  CARGO_HOME=/home/servo/.cargo
  CCACHE=/usr/bin/ccache
  DISPLAY=:0
  HOME=/home/servo
  PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/home/servo/android/sdk/current/platform-tools:/home/servo/android/toolchain/current/bin
  PWD=/home/servo/buildbot/slave/android-nightly/build
  RUST_BACKTRACE=1
  SERVO_CACHE_DIR=/home/servo/.servo
  SHELL=/bin/bash
  TERM=linux
  UPSTART_INSTANCE=
  UPSTART_JOB=buildbot-slave
 using PTY: False
   Compiling winapi v0.2.5
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.1
   Compiling walkdir v0.1.5
   Compiling build-apk v0.0.1 (file:///home/servo/buildbot/slave/android-nightly/build/support/android/build-apk)
     Running `/home/servo/buildbot/slave/android-nightly/build/target/debug/build-apk  -o /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release/servo.apk -t /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release -r /home/servo/buildbot/slave/android-nightly/build`
Copying the file "/home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release/libservo.so" to "/home/servo/buildbot/slave/android-nightly/build/support/android/apk/jni/armeabi/libmain.so"
rm -f ./libs/arm64-v8a/lib*.so ./libs/armeabi/lib*.so ./libs/armeabi-v7a/lib*.so ./libs/armeabi-v7a-hard/lib*.so ./libs/mips/lib*.so ./libs/mips64/lib*.so ./libs/x86/lib*.so ./libs/x86_64/lib*.so
rm -f ./libs/arm64-v8a/gdbserver ./libs/armeabi/gdbserver ./libs/armeabi-v7a/gdbserver ./libs/armeabi-v7a-hard/gdbserver ./libs/mips/gdbserver ./libs/mips64/gdbserver ./libs/x86/gdbserver ./libs/x86_64/gdbserver
rm -f ./libs/arm64-v8a/gdb.setup ./libs/armeabi/gdb.setup ./libs/armeabi-v7a/gdb.setup ./libs/armeabi-v7a-hard/gdb.setup ./libs/mips/gdb.setup ./libs/mips64/gdb.setup ./libs/x86/gdb.setup ./libs/x86_64/gdb.setup
[armeabi] Prebuilt       : libmain.so <= jni/armeabi/
cp -f jni/armeabi/libmain.so obj/local/armeabi/libmain.so
[armeabi] Install        : libmain.so => libs/armeabi/libmain.so
install -p ./obj/local/armeabi/libmain.so ./libs/armeabi/libmain.so
/home/servo/android/ndk/r10e/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --strip-unneeded  ./libs/armeabi/libmain.so
Error: Target id 'android-18' is not valid. Use 'android list targets' to get the target ids.
Error while updating the project with the android command
error: Process didn't exit successfully: `/home/servo/buildbot/slave/android-nightly/build/target/debug/build-apk  -o /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release/servo.apk -t /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release -r /home/servo/buildbot/slave/android-nightly/build` (exit code: 1)
Packaging Android exited with return value 1
program finished with exit code 1
elapsedTime=5.288602
```

**Comment by larsbergstrom** [comment] 2016-04-02 00:00
Thanks!

I think this is just a failure to run the android `android` tool with the proper toolkits. I think we can hopefully just steal this from other folks' salt rules :-)

CC @edunham @aneeshusa

**Comment by aneeshusa** [comment] 2016-04-02 00:17
My first guess would be that the menu entries in the output of `android list sdk` have changed. See https://github.com/servo/saltfs/blob/6e59cb1ed42c005e225c184d5809930b0c2c9906/servo-build-dependencies/android.sls#L50 for reference; if the menu entries have changed, 9 will no longer provide the android-18 target. This might happen if we update the SDK, for example.

Have there been any changes on the Android builders lately?

**Comment by aneeshusa** [comment] 2016-04-02 00:21
I just ssh'ed into `servo-linux-cross1` and the output of `android list sdk` indicates that the android-18 target is now 8 in the list, not 9.

However, this shouldn't matter - the proper SDK should already be installed from whenever we set up the builder.

**Comment by larsbergstrom** [comment] 2016-04-02 00:23
Aha! I think that we somewhat-recently upgraded SDK & NDK versions, because I remember having to propagate the changes to the environment variables.

I think that happened with the old builders (which would already have had the original SDKs installed) and now when we provisioned the new ones, the new bits were not installed.

**Comment by aneeshusa** [comment] 2016-04-02 00:23
Nope, checking in the `platforms` subdir shows only `android-19`, not `android-18`, so it looks like this is the cause. The fact that the menu entries changed like that without a version bump is worrying!

I'll put in a PR for a quick fix, but I'll need to rejigger these states to work better long term.

**Comment by aneeshusa** [comment] 2016-04-02 00:27
You're right, [I bumped the SDK version in November](https://github.com/aneeshusa/servo-saltfs/commit/b80f1bd296cef8d63dcb70b2b7517790d41fc39e). Maybe I don't need to fix the states after all.

Are these the first Android builds we've run on the new builders?

**Comment by larsbergstrom** [comment] 2016-04-02 00:28
I think that the rest of the Android stuff is somehow working fine (it got the platform). The nightly build has been broken since the move, though, because though the platform is there the platform build tools are not. Those are only used in the android-nightly build - the others just need the headers to link against, etc.

**Comment by larsbergstrom** [comment] 2016-04-02 00:29
In fact, I think we only need the *NDK* for the rest of the Servo android build! It's only when we build the packaging and java library goop that we touch anything from the SDK.

**Comment by aneeshusa** [comment] 2016-05-25 03:29
servo/saltfs#290 landed and seems to have fixed the compile step: http://build.servo.org/builders/android-nightly/builds/57. Looking into the other failures now.

**Comment by larsbergstrom** [comment] 2016-07-01 20:05
This is working now: http://build.servo.org/builders/android-nightly/builds/96

**Closed by larsbergstrom** 2016-07-01 20:05 UTC
Labels: P-android
