### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "SendError(..)"

### ISSUE THREAD

**Issue by sebastianbiallas** [servo/servo#12176] opened 2016-07-02 17:33 UTC
called `Result::unwrap()` on an `Err` value: "SendError(..)"
### URL:
https://www.youtube.com/watch?v=gMaG7f2XXnM
### Backtrace:
```
frame #0  - 0x000000010c2e76ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x000000010c2e7651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000000010b5b8086 - _<F as alloc..boxed..FnBox<A>>::call_box::h6059122298f825d8
frame #3  - 0x000000010c25b947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010c4cf844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000000010c4e8786 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x000000010c4d0e88 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x000000010c4e83df - rust_begin_unwind
frame #8  - 0x000000010c50f260 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x000000010b38c2f7 - core::result::unwrap_failed::h84d3c1f4e17e69e8
frame #10 - 0x000000010b5052ec - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tree_builder..rules..TreeBuilderStep>::step::hbe4aeca8895fd105
frame #11 - 0x000000010b4e41c0 - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tokenizer..interface..TokenSink>::process_token::h579a596ee4107ff8
frame #12 - 0x000000010b4e3581 - _<html5ever..tokenizer..Tokenizer<Sink>>::process_token::h616ced05c6553b33
frame #13 - 0x000000010b524765 - _<html5ever..tokenizer..Tokenizer<Sink>>::emit_current_tag::h6fdd02043fd36093
frame #14 - 0x000000010b52002e - _<html5ever..tokenizer..Tokenizer<Sink>>::step::h79d847fb9b3f3847
frame #15 - 0x000000010b511b27 - _<html5ever..tokenizer..Tokenizer<Sink>>::run::h791635f37dca2738
frame #16 - 0x000000010b4df22c - script::dom::servohtmlparser::ServoHTMLParser::parse_sync::h3d357a0bc0edb824
frame #17 - 0x000000010b4dee6d - _<&'a script..dom..servohtmlparser..ServoHTMLParser as script..parse..Parser>::parse_chunk::he714ef1dc39b8376
frame #18 - 0x000000010b4de0b3 - _<script..dom..servohtmlparser..ParserContext as net_traits..AsyncResponseListener>::data_available::h73697b125635b0c6
frame #19 - 0x000000010b649db7 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::ha2200b1de782800b
frame #20 - 0x000000010b5c395c - script::script_thread::ScriptThread::handle_msg_from_script::hd1f5e7b2423a8c64
frame #21 - 0x000000010b61fa71 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc67d8b381c013b79
frame #22 - 0x000000010b60573f - script::script_thread::ScriptThread::handle_msgs::h236c5be60a207bea
frame #23 - 0x000000010b5b6907 - std::panicking::try::call::h645a328f039d97c6
frame #24 - 0x000000010c4eb46b - __rust_try
frame #25 - 0x000000010c4eb405 - __rust_maybe_catch_panic
frame #26 - 0x000000010b5b7ab4 - _<F as alloc..boxed..FnBox<A>>::call_box::h3db95636eb747818
frame #27 - 0x000000010c4e6ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #28 - 0x00007fff90a9e99c - _pthread_body
frame #29 - 0x00007fff90a9e919 - _pthread_start

```

**Comment by jdm** [comment] 2016-07-02 21:24
This is a duplicate of #11992. Thanks for reporting it!

**Closed by jdm** 2016-07-02 21:24 UTC
