### ISSUE TITLE
assertion failed: self.suspended_since.get().is_some()

### ISSUE THREAD

**Issue by amilajack** [servo/servo#13979] opened 2016-10-29 20:13 UTC
assertion failed: self.suspended_since.get().is_some()
### Servo Version:
Servo 0.0.1-3ae0a33
### Backtrace:
```

WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(8) } iterated after clo
...
```
This report was generated by the browser.html issue reporter.

**Comment by amilajack** [comment] 2016-10-29 20:14
This was automatically generated. Closing this, as it seems like a dupe of https://github.com/servo/servo/issues/13973

**Comment by emilio** [comment] 2016-10-29 20:44
Yep! Thanks for filling! If you mind confirming, this happened while browsing through the history right?

I'm closing as a dupe of https://github.com/servo/servo/issues/13716.

**Closed by emilio** 2016-10-29 20:44 UTC

**Comment by amilajack** [comment] 2016-10-29 20:47
> If you mind confirming, this happened while browsing through the history right?

I believe so. I remember using the `cmd + [` and `cmd + ]` keys to navigate quickly. I'll do some more testing and I'll confirm this.
