### ISSUE TITLE
Implement display: inline-table

### ISSUE THREAD

**Issue by eefriedman** [servo/servo#8003] opened 2015-10-13 21:29 UTC
Currently, the CSS parser parses inline-table, but layout doesn't do anything interesting with it.  We treat it like a block because of https://github.com/servo/servo/blob/69db83476d02d06658ad084a834abc94f7f008d0/components/layout/construct.rs#L1557 .

Probably a good project for someone interested in digging into layout a bit; this shouldn't require any significant architectural changes.

**Comment by romankl** [comment] 2015-10-25 20:56
Mind me asking, is someone working on it or could I take a look at it?

**Comment by eefriedman** [comment] 2015-10-25 21:19
Nobody is working on it as far as I know.

**Comment by KiChjang** [comment] 2016-01-06 02:51
@romankl How far are you in this?

**Comment by romankl** [comment] 2016-01-06 12:03
@KiChjang sorry for the late update - it's probably better to re-assign it. (I can't find enough time for this one :/ )

**Comment by jdm** [comment] 2016-02-26 15:56
#9355 was an attempt to address this but encountered a bunch of test failures. Any further attempt should investigate what those test failures mean by looking at each test and determining whether they're making use of features we expect to work correctly or not.

**Comment by KiChjang** [comment] 2016-02-26 18:06
The [reftest analyzer](http://hoppipolla.co.uk/410/reftest-analyser-structured.xhtml) should be used when attempting to debug the test failures in #9355

**Comment by danlrobertson** [comment] 2016-03-12 06:03
Is there a good way to get the logs from the PRs tests? I looked at all the links and they either had no logs or yielded 404s. I'll try running them on my local machine

**Comment by jdm** [comment] 2016-03-12 09:28
Unfortunately we have started deleting them automatically after a few days. If you open a rebased version of the PR temporarily we can get a new log for you. For running locally you could look for any testcase using inline-table and use `./mach test-css`.

**Comment by Ms2ger** [comment] 2016-03-12 13:26
I don't think this is an appropriate project for anyone who does not have significant experience with table layout.

**Comment by danlrobertson** [comment] 2016-03-12 16:18
> I don't think this is an appropriate project for anyone who does not have significant experience with table layout.

I do not have significant experience with table layout, but I'm not afraid of digging into some docs, so I'm happy to dig into this issue or move on to another... whatever you all would prefer works for me

**Comment by Ms2ger** [comment] 2016-03-14 10:36
The problem is that there's barely any documentation.

**Comment by danlrobertson** [comment] 2016-03-14 12:30
Ah! That is a problem... I'll look around for another issue then

**Comment by mrobinson** [comment] 2024-12-28 13:37
I'm fairy sure we have support for `display: inline-table` now.

**Closed by mrobinson** 2024-12-28 13:37 UTC
Labels: B-interesting-project, A-layout/inline, A-layout/table
