### ISSUE TITLE
Iframe is not clipped in browserhtml

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#11957] opened 2016-06-30 13:31 UTC
<img width="834" alt="screen shot 2016-06-30 at 7 31 19 am" src="https://cloud.githubusercontent.com/assets/9086315/16489879/a5d804cc-3e94-11e6-9c71-e54b7aaa56d4.png">

**Comment by paulrouget** [comment] 2016-06-30 14:46
This is a regression.

related: #11151 #11358

**Comment by paulrouget** [comment] 2016-07-26 06:48
Dupe of https://github.com/servo/servo/issues/11650

**Closed by paulrouget** 2016-07-26 06:48 UTC
Labels: A-browserhtml/P1, A-webrender
