### ISSUE TITLE
Bizarre rendering on macOS 10.12.1 (16B2555)

### ISSUE THREAD

**Issue by tigt** [servo/servo#14372] opened 2016-11-26 04:31 UTC
## macOS:
Version 10.12.1 (16B2555)
1.6 GHz Intel Core i5
4 GB 1600 MHz DDR3
Intel HD Graphics 6000 1536 MB
(standard density screen)

## Servo:
Servo 0.0.1-bf92d0a

[Screen recording of launch: servo-launch.mp4.zip](https://github.com/servo/servo/files/614048/servo-launch.mp4.zip)

![Screenshot of Servo displaying a whole lotta black, and not much else.](https://cloud.githubusercontent.com/assets/8072522/20638009/0e7ea96c-b367-11e6-9be8-c95f6066a976.png)

**Comment by jdm** [comment] 2016-11-26 13:27
Duplicate of #14259. Thanks for reporting it!

**Closed by jdm** 2016-11-26 13:27 UTC
