### ISSUE TITLE
Layout attached to empty script thread.

### ISSUE THREAD

**Issue by aonorin** [servo/servo#14660] opened 2016-12-21 15:15 UTC
Layout attached to empty script thread.
### Servo Version:
Servo 0.0.1-ae2b74e
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineI
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-12-21 15:17
Duplicate of #14573. Thanks for reporting it!

**Closed by jdm** 2016-12-21 15:17 UTC
