### ISSUE TITLE
GL context creation failed on nightly

### ISSUE THREAD

**Issue by oxwivi** [servo/servo#12220] opened 2016-07-04 13:57 UTC
Unlike the other similar report, there's nothing about SSL in the backtrace:

```
$ RUST_BACKTRACE=1 ./runservo.sh
thread 'main' panicked at 'Failed to create window.: OsError("GL context creation failed")', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x56252528d34f - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x562525294f7b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x562525294bdf - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x5625251737c7 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
   5:     0x56252527abac - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   6:     0x5625252951c1 - std::panicking::begin_panic::he426e15a3766089a
   7:     0x56252527c41a - std::panicking::begin_panic_fmt::hdddb415186c241e7
   8:     0x56252529515e - rust_begin_unwind
   9:     0x5625252cb75f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  10:     0x562523467000 - core::result::unwrap_failed::hd132ba2b7d75f379
  11:     0x562523465e04 - glutin_app::window::Window::new::h750be0f1f60f008a
  12:     0x562523464e00 - glutin_app::create_window::hae774cdda1762e66
  13:     0x56252340e105 - servo::main::h6924e5658370f6b5
  14:     0x562525294558 - std::panicking::try::call::h852b0d5f2eec25e4
  15:     0x56252529f3bb - __rust_try
  16:     0x56252529f35e - __rust_maybe_catch_panic
  17:     0x562525293ffe - std::rt::lang_start::hfe4efe1fc39e4a30
  18:     0x7f9ffeae282f - __libc_start_main
  19:     0x56252340d0c9 - <unknown>
  20:                0x0 - <unknown>
```

**Comment by jdm** [comment] 2016-07-04 16:00
The OpenSSL stuff and the GL context creation are unrelated, so it's fine to mark this one as a duplicate of #12053 .

**Comment by jdm** [comment] 2016-07-04 16:00
Thanks for reporting it!

**Closed by jdm** 2016-07-04 16:00 UTC
