### ISSUE TITLE
Nigthly won't start on some linux distros : fedora 24 / 23, debian testing

### ISSUE THREAD

**Issue by lhirlimann** [servo/servo#12015] opened 2016-07-01 08:27 UTC
```
[ludo@Oulanl ~]$ cd servo/
[ludo@Oulanl servo]$ ./runservo.sh 
./servo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
[ludo@Oulanl servo]$ 
```

**Comment by Manishearth** [comment] 2016-07-01 08:48
You may need to install openssl.

**Comment by lhirlimann** [comment] 2016-07-01 09:39
it's installed : 
[ludo@Oulanl servo]$ rpm -qa |grep openssl
openssl-devel-1.0.2h-1.fc24.x86_64
openssl-1.0.2h-1.fc24.x86_64
openssl-libs-1.0.2h-1.fc24.i686
openssl-libs-1.0.2h-1.fc24.x86_64

**Comment by Manishearth** [comment] 2016-07-01 09:42
Looks like this is a duplicate of https://github.com/servo/servo/issues/12017. We'll look into this, thanks for the report!

**Comment by divingdeer** [comment] 2016-07-01 10:58
I can confirm this issue. It seems the problem is caused by the version of OpenSSL provided by Fedora.

Output of `rpm -qa | grep openssl`:
```
openssl-libs-1.0.2h-1.fc24.x86_64
openssl-devel-1.0.2h-1.fc24.x86_64
openssl-libs-1.0.2h-1.fc24.i686
openssl-1.0.2h-1.fc24.x86_64
```

Output of `/usr/lib64% ls | grep libssl`:
```
libssl3.so
libssl.so
libssl.so.10
libssl.so.1.0.2h
```

I tried to work around the error by linking libssl.so.1.0.0 to libssl.so and libcrypto.so to libcrypto.so.1.0.0

But that does not work either:
```
./servo: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)
./servo: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.1d' not found (required by ./servo)
./servo: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)
```

**Comment by anisse** [comment] 2016-07-01 11:12
The issue is the same on Fedora 23.

**Comment by Coder206** [comment] 2016-07-01 12:26
I had no issues running on a clean version of Fedora 24 by compiling it...

**Comment by lhirlimann** [comment] 2016-07-01 12:31
Same here, it's a packaging issue most likely.

**Comment by Coder206** [comment] 2016-07-01 13:03
@lhirlimann I am also experiencing the issues you described but I am still able to run it if i compile it myself.

**Comment by frewsxcv** [comment] 2016-07-02 15:04
Possibly related issue: https://github.com/sfackler/rust-openssl/issues/401

**Comment by est31** [comment] 2016-07-02 19:25
This sounds like an issue godotengine had where they have built the binaries on an ubuntu travis instance, and then fedora users downloaded and got a similar problem: https://github.com/godotengine/godot/issues/1391

Out of some reason, Fedora has a custom soname for the openssl library, and as the soname gets stored at linking time, the soname the binary has stored differs from the soname that is expected on fedora. It essentially means that there is no binary compatibility between fedora and non fedora programs that dynamically link to openssl. If this is the issue, and it really looks like that, you'd either need to statically link in openssl, or publish a separate build for fedora.

**Comment by RalfJung** [comment] 2016-07-04 12:38
This bug is not specific to Fedora at all. I am getting the same error on Debian testing:

$ ./runservo.sh 
./servo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
$ find /usr/lib -name "libssl*"
/usr/lib/i386-linux-gnu/i686/cmov/libssl.so.1.0.2
/usr/lib/i386-linux-gnu/libssl.so.1.0.2
/usr/lib/x86_64-linux-gnu/libssl3.so.1d
/usr/lib/x86_64-linux-gnu/libssl3.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
/usr/lib/x86_64-linux-gnu/pkgconfig/libssl.pc
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.a

**Comment by est31** [comment] 2016-07-04 16:20
What's the output of `objdump -x /usr/lib/x86_64-linux-gnu/libssl.so | grep SONAME` ?

**Comment by anisse** [comment] 2016-07-04 16:25
SONAME               libssl.so.10

**Comment by ZaWertun** [comment] 2016-07-04 16:26
I have just the same SONAME on Fedora 23.

**Comment by anisse** [comment] 2016-07-04 16:28
FYI:
https://apps.fedoraproject.org/packages/openssl
You can get the RPMs here:
F23:
http://koji.fedoraproject.org/koji/buildinfo?buildID=759832
F24:
http://koji.fedoraproject.org/koji/buildinfo?buildID=759831

**Comment by RalfJung** [comment] 2016-07-04 17:10
@est31 
```
$ objdump -x /usr/lib/x86_64-linux-gnu/libssl.so | grep SONAME
  SONAME               libssl.so.1.0.2
```

**Comment by est31** [comment] 2016-07-04 17:56
Its "libssl.so.1.0.0" for me on ubuntu 16.04, and for me the nightly works. So the issue still seems to be connected to the soname, although not isolated to fedora.

**Comment by ammarnajjar** [comment] 2016-07-04 18:04
+1 
fedora24, same issue:

```bash
$ sudo dnf info openssl
Last metadata expiration check: 1:21:45 ago on Mon Jul  4 18:36:54 2016.
Installed Packages
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2h
Release     : 1.fc24
Size        : 817 k
Repo        : @System
From repo   : @commandline
Summary     : Utilities from the general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.
```
```bash
$ ls -l /usr/lib/libssl*
lrwxrwxrwx. 1 root root   16 May  3 18:32 /usr/lib/libssl.so.10 -> libssl.so.1.0.2h
-rwxr-xr-x. 1 root root 434K May  3 18:32 /usr/lib/libssl.so.1.0.2h
```

```bash
$ objdump -x /usr/lib/libssl.so.1.0.2h | grep SONAME
  SONAME               libssl.so.10
```
and creating a symlink like:
```bash
$ sudo ln -s /usr/lib/libssl.so.1.0.2h /usr/lib/libssl.so.1.0.0
```
does not solve the issue.

**Comment by Shihira** [comment] 2016-07-08 13:36
I have the same issue. I tried to download those so files [here](http://rpm.pbone.net/index.php3/stat/4/idpl/29237132/dir/fedora_22/com/openssl1-1.0.0-2.fc22.x86_64.rpm.html), and extract theme into the servo directory. Then launch Servo with:

```
[shihira Servo]$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD ./runservo.sh
```

Anyway finally it launched, but SSL seems not working though, for some version faults. Hardly load a page.

**Comment by elennaro** [comment] 2016-07-08 14:51
Same issue.
Is there a workaround?

**Comment by meghprkh** [comment] 2016-07-12 20:07
I downloaded the files from above and added them to my ld.conf but it prints something like:
```
[megh@theunknown servo] $ ./runservo.sh 
./servo: /home/megh/Downloads/servo/lib64/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /home/megh/Downloads/servo/lib64/libcrypto.so.1.0.0: no version information available (required by ./servo)
./servo: /home/megh/Downloads/servo/lib64/libssl.so.1.0.0: no version information available (required by ./servo)

Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
```

**Comment by meghprkh** [comment] 2016-07-12 20:11
Okay got a temporary solution, link https://www.reddit.com/r/linux/comments/4qqc6g/servo_developer_preview_builds_available/d4v2dqh

**Comment by ollyja** [comment] 2016-07-19 15:16
Tried last nightly. same issue on Fedora 24.

**Comment by fabiand** [comment] 2016-08-19 14:51
I think the nightlies need to be built against a newer openssl to work smoothly on Fedora.
Maybe another travis job can be added?

**Comment by est31** [comment] 2016-08-19 15:08
One of the ways to solve the soname problems once and for all would be to build flatpaks and distribute them instead: http://flatpak.org/developer.html http://flatpak.org/

openssl would I think be packaged via the runtime, so it could be updated without the intervention of servo. 

The only requirement is that flatpak and the runtime are installed, but fedora already ships with flatpak, and debian based distros have a flatpak ppa.

**Comment by fabiand** [comment] 2016-08-19 15:10
That's actually an awesome idea!

**Comment by anisse** [comment] 2016-09-09 08:57
Why not simply bundle libssl ? This is a nightly, and software you shouldn't be running longer than a day without updating. Or am I missing something ?

**Comment by jdm** [comment] 2016-09-09 12:46
@anisse There's been a lot of discussion on that topic at https://groups.google.com/forum/#!topic/mozilla.dev.servo/3mfkRehXAo4 .

**Comment by dumindu** [comment] 2016-09-28 12:33
This is still happening :(

**Comment by StefanoD** [comment] 2017-01-06 08:03
Same issue with Fedora 25:

> bash-4.3$ sudo dnf info openssl
Installed packages
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2j
Release     : 3.fc25

As someone stated: A flatpack package would be cool!

**Comment by thangarajj** [comment] 2017-01-20 13:54
Can confirm that this issue remains on Fedora 25 on today's build.

**Comment by vatrat** [comment] 2017-02-02 23:32
Issue is still around on Fedora 25. I'll try to compile.

**Comment by ameenross** [comment] 2017-02-22 15:51
Yup, I recently got rid of my Servo clone and started gettings the nightlies. Experiencing this error now.

**Comment by heftig** [comment] 2017-02-22 16:16
Seems that the problem is caused by the nightlies including a static, old, libfontconfig. There are valid caches of version 7 on my system but the nightly can't use them because it needs version 4. So it scans all fonts on startup to build the caches.

After the caches are built once (taking about 5 minutes) further starts are fast.

**Comment by funghetto** [comment] 2017-03-26 17:00
Same on debian sid.

**Comment by gpavinteractiv** [comment] 2017-04-14 13:40
Fedora 25, today's buid : Still

**Comment by mcepl** [comment] 2017-04-18 06:49
The same goes for RHEL-7 … when I do symlinks, it still breaks, because apparently proper symbols are not there.

**Comment by StefanoD** [comment] 2017-04-18 07:26
By the way: You could do a snap package. It is stable (version 1.0+) and runs on Fedora as well.

**Comment by daboross** [comment] 2017-04-20 05:17
I'm not sure if I have a missing dependency or I'm running into this issue, but here's my output for the nightly download:
```
$ ./servo 
./servo: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)
./servo: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.1d' not found (required by ./servo)
./servo: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.1' not found (required by ./servo)
./servo: /usr/lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)
./servo: /usr/lib64/libssl.so.1.0.0: version `OPENSSL_1.0.1' not found (required by ./servo)
$ openssl version
OpenSSL 1.0.2k  26 Jan 2017
$ objdump -x /usr/lib64/libssl.so.1.0.0 | grep SONAME
  SONAME               libssl.so.1.0.0
````

**Comment by juhp** [comment] 2017-04-22 05:55
Or a flatpack :)

So what OS version are the nightly snapshots built on?  And why? :)

**Comment by MGageMorgan** [comment] 2017-04-29 02:48
Will this be fixed by July 1st, 2017? I wanna experience the one thing closest to a browser written in HTML and Rust, but can't because I can't compile or run it (both fail for me).

**Comment by axvr** [comment] 2017-04-29 18:51
This is a problem which has occurred due to the machine which creates the builds using outdated versions (from 2013) of the OpenSSL libraries (libssl and libcrypto on Fedora). There are two solutions to this problem:

1. Build Servo on the system you plan to use it on. This will link the new libraries to your own build of Servo automatically. This is currently the best method to run Servo on systems which do not hold copies of the OpenSSL 1.0.0 libraries.
2. Downgrade your libraries **NOT RECOMMENDED UNDER ANY CIRCUMSTANCE**. This would be difficult to do on Fedora as the repositories do not hold the 1.0.0 packages for the OpenSSL libraries any more (they were available on Fedora 13). These would have to be compiled on your system independent of a package manager, as DNF will not allow you to do so.

**Symbolic linking will not solve this issue** it will simply cause the problem that @daboross was having, where the libraries used by the official nightly build of Servo still do not actually exist on your system.

**Comment by StefanoD** [comment] 2017-04-29 19:10
Naive question: Why is the OpenSSL version of the build server not getting updated? This would be actually the third solution @axvr

**Comment by MGageMorgan** [comment] 2017-04-29 19:12
@axvr It won't build on my machine, tried three times last night :(

I am hijacking libraries from ubuntu debs as per a reddit thread, but Fedora 13? How do you maintain a build machine without updates for eons like that? So the build machine hasn't been updated in 4 YEARS? That's a long time, amigo.

**Comment by StefanoD** [comment] 2017-04-29 19:15
I'm actually puzzled why the build is not some LTS distribution like Ubuntu LTS.

**Comment by MGageMorgan** [comment] 2017-04-29 19:16
@StefanoD No, that's the only logical solution, and it's the one that takes the least amount of time on the part of us and the maintainers. (Apt install or dnf install, anyone?)

**Comment by MGageMorgan** [comment] 2017-04-29 19:19
@StefanoD Maybe it is and everyone just forgot to update it from Ubuntu 12.04

**Comment by jdm** [comment] 2017-04-29 19:27
https://github.com/servo/saltfs/issues/462

**Comment by MGageMorgan** [comment] 2017-04-29 19:33
@jdm Elaborate?

**Comment by jdm** [comment] 2017-04-29 19:42
That is an issue for our build infrastructure titled "Update build machines to use Ubuntu 16.04".

**Comment by MGageMorgan** [comment] 2017-04-29 19:43
@jdm Looking at SaltFS, and that issue, looks like integrating with the init system came crashing down. I don't know much about SaltFS, but if by looking at that says anything to me, it would be that relying on the underlying OS isn't a good idea. Especially because Linux components are always changing if not breaking. 

I'm learning rust, and wondering if my next project should involve init scripts...

**Comment by MGageMorgan** [comment] 2017-04-29 19:44
@jdm yeah. I got that. I feel there should be a way to write the same init script to run on systemd, initd, upstart, etc. Like a binding or something...

**Comment by Asfhy** [comment] 2017-05-08 11:10
I'm on Manjaro Linux (Arch derivate) and I managed to make it run after using prelink on the downloaded servo binary. I mean, my way of getting the nightly build runing is:

1- Download the build
2- Extract the build on the servo folder
3- Use a terminal to navigate to the servo folder and run "sudo prelink servo"
4- Perlink finds the needed libraries and link them to the binary, so it ends in a second or two without errors, now "./servo" opens the window and no more errors about libraries not found are thrown.

**Comment by MGageMorgan** [comment] 2017-05-08 11:37
@Asfy Never heard of it, but I'll go look that up soon. There's a lot more I could do with a tool like that outside the scope of servo if it exists and works.

**Comment by daboross** [comment] 2017-05-12 06:10
Prelink looks like an awesome tool, but sadly it does not fix it on all systems. Output from running `prelink` on the binary on Gentoo:

```
$ sudo prelink servo 
prelink: /usr/lib32/misc/glibc/getconf/POSIX_V7_ILP32_OFFBIG: Using /lib32/ld-linux.so.2, not /lib/ld-linux.so.2 as dynamic linker
prelink: /usr/lib32/misc/glibc/getconf/XBS5_ILP32_OFF32: Using /lib32/ld-linux.so.2, not /lib/ld-linux.so.2 as dynamic linker
prelink: /usr/lib32/misc/glibc/getconf/XBS5_ILP32_OFFBIG: Using /lib32/ld-linux.so.2, not /lib/ld-linux.so.2 as dynamic linker
prelink: /usr/lib32/misc/glibc/getconf/POSIX_V7_ILP32_OFF32: Using /lib32/ld-linux.so.2, not /lib/ld-linux.so.2 as dynamic linker
prelink: /usr/lib32/misc/glibc/getconf/POSIX_V6_ILP32_OFFBIG: Using /lib32/ld-linux.so.2, not /lib/ld-linux.so.2 as dynamic linker
prelink: /usr/lib32/misc/glibc/getconf/POSIX_V6_ILP32_OFF32: Using /lib32/ld-linux.so.2, not /lib/ld-linux.so.2 as dynamic linker
prelink: servo: Could not parse `./servo: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)'
```

**Comment by MGageMorgan** [comment] 2017-05-15 18:25
@dabpross Don't worry, have yet to actually try it ;)

**Comment by MGageMorgan** [comment] 2017-05-15 18:25
*@daboross

**Comment by fabiand** [comment] 2017-06-03 21:02
I've created a small Makefile to build a flatpak wrapping the servo nightlies, see

* https://github.com/fabiand/flatpak-servo
* https://dummdida.tumblr.com/post/161401019450/flatpak-ing-servo-nightly

We could take it from here and use this (or alike) in the servo nightly build process, and push those builds to flathub (once it's back online).

**Comment by StefanoD** [comment] 2017-06-03 21:14
@fabiand Great! I think, you have to make a PR.

**Comment by MGageMorgan** [comment] 2017-06-04 02:02
I think that's awesome. Even if it doesn't make it in, long as it works and is maintained, I would be happier using a tool like this alone than what's currently available. 




Cheers!


M. Gage Morgan


----


Christoffen OSWorks LLC co-founder, CEO, and lead architect. 




/**


* Just note that my opinion will 


* NEVER reflect my company, which I 


* hope to keep neutral in terms of 


* public relations with other entities.


**/







On Sat, Jun 3, 2017 at 5:15 PM -0400, "Stefano" <notifications@github.com> wrote:












@fabiand Great! I think, you have to make a PR.

**Comment by dralley** [comment] 2017-06-29 20:29
What is the progress on this?

**Comment by jdm** [comment] 2017-06-29 21:16
No progress.

**Comment by nox** [comment] 2017-10-02 08:14
Is this still an issue?

**Comment by ojab** [comment] 2017-10-02 08:20
Yep, reproducible on Fedora-26 w/ all updates and latest servo nightly.

**Comment by MGageMorgan** [comment] 2017-10-11 23:03
Wow, missed my July 1st deadline XD

**Comment by ZanderBrown** [comment] 2017-11-04 09:52
This is still reproducible on Fedora 27 (Beta) with the latest nightly

**Comment by jurf** [comment] 2017-12-27 10:58
Nothing changed with F27 coming out of Beta.

**Comment by ZanderBrown** [comment] 2018-01-24 09:45
Just checked latest nightly on F27:
```bash
./servo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by lnicola** [comment] 2018-02-26 08:40
For anyone interested, the official `servo` builds can be tested on Arch by installing `openssl-1.0`. It can be used side by side with `openssl 1.1`.

**Comment by fabiand** [comment] 2018-02-27 09:00
Good idea. That might actually also work on Fedora by `dnf install compat-openssl10`

**Comment by ojab** [comment] 2018-02-27 09:07
Unfortunately it won't help on Fedora, `compat-openssl10` contains `libssl.so.1.0.2m`, while servo requires `libssl.so.1.0.0`.

**Comment by fabiand** [comment] 2018-02-27 09:22
Thanks for testing this so quickly. Darn.

**Comment by RalfJung** [comment] 2018-03-28 08:20
To me this sounds like a build machine issue: For some reason, the machine doing the build uses a pretty old version of libssl. The [OpenSSL website](https://www.openssl.org/source/) says

>  The 0.9.8, 1.0.0 and 1.0.1 versions are now out of support and should not be used.

So, probably what should happen is that the build machine gets updated to a non-legacy version of OpenSSL?

**Comment by ZanderBrown** [comment] 2018-03-28 08:35
Seems reasonable, anyone have the ability to do that?

**Comment by anisse** [comment] 2018-03-28 09:14
@RalfJung @ZanderBrown : this would be a first step indeed, see @jdm 's comment:

> servo/saltfs#462

Note that it does not mean the dogmatic position of not bundling openssl on Linux (but doing it on Mac, Windows) would change; you'd need to reach a consensus on that, too.

**Comment by jdm** [comment] 2018-03-28 13:43
I suspect that we would need to update the version of openSSL we use within the build as well, and that may require updating our Network stack which is an open problem right now.

**Comment by RalfJung** [comment] 2018-03-28 15:37
Servo compiles in my system against OpenSSL 1.1 just fine.

**Comment by jdm** [comment] 2018-03-28 15:50
I've filed https://github.com/servo/saltfs/issues/824 to look into whether we can upgrade the version of OpenSSL that's present on our nightly build machines.

**Comment by roberto68** [comment] 2018-11-19 17:21
same error fedora 29 - it'd be good to bundle that lib into the project

**Comment by northivanastan** [comment] 2018-11-22 22:38
Still have the error on Debian 9.

**Closed** 2019-05-15 21:44 UTC
Labels: P-linux
