### ISSUE TITLE
assertion failed: !self.scroll_roots.contains_key(&scroll_root.id)

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15075] opened 2017-01-17 13:04 UTC
```
$ ./mach run --dev http://www.lenovo.com/be/nl/
```

```
assertion failed: !self.scroll_roots.contains_key(&scroll_root.id) (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at SERVO/components/layout/display_list_builder.rs:144)
stack backtrace:
   0:     0x7fe16fbdcdd1 - backtrace::backtrace::libunwind::trace
                        at SERVO/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:82
                         - backtrace::backtrace::trace<closure>
                        at SERVO/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x7fe16fbdce98 - backtrace::capture::{{impl}}::new
                        at SERVO/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/lib.rs:96
   2:     0x7fe16a8c61eb - servo::main::{{closure}}
                        at SERVO/ports/servo/main.rs:122
   3:     0x7fe1712783f8 - std::panicking::rust_panic_with_hook
                        at RUST/src/libstd/panicking.rs:556
   4:     0x7fe16ee774c3 - std::panicking::begin_panic<&str>
                        at RUST/src/libstd/panicking.rs:517
   5:     0x7fe16eef8c38 - layout::display_list_builder::{{impl}}::add_scroll_root
                        at SERVO/components/layout/display_list_builder.rs:144
   6:     0x7fe16eefc1d0 - layout::display_list_builder::{{impl}}::collect_scroll_root_for_block
                        at SERVO/components/layout/display_list_builder.rs:1869
   7:     0x7fe16eefbcbc - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1816
   8:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
   9:     0x7fe16efe243c - layout::table::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/table.rs:503
  10:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  11:     0x7fe16eefbd70 - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1822
  12:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  13:     0x7fe16ee45fdc - layout::table_wrapper::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/table_wrapper.rs:464
  14:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  15:     0x7fe16eefca28 - layout::display_list_builder::{{impl}}::create_real_stacking_context_for_block
                        at SERVO/components/layout/display_list_builder.rs:1932
  16:     0x7fe16eefbf15 - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1837
  17:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  18:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  19:     0x7fe16eefc4c6 - layout::display_list_builder::{{impl}}::create_pseudo_stacking_context_for_block
                        at SERVO/components/layout/display_list_builder.rs:1900
  20:     0x7fe16eefbeaf - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1832
  21:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  22:     0x7fe16efdae3c - layout::list_item::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/list_item.rs:146
  23:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  24:     0x7fe16eefc4c6 - layout::display_list_builder::{{impl}}::create_pseudo_stacking_context_for_block
                        at SERVO/components/layout/display_list_builder.rs:1900
  25:     0x7fe16eefbeaf - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1832
  26:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  27:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  28:     0x7fe16eefc4c6 - layout::display_list_builder::{{impl}}::create_pseudo_stacking_context_for_block
                        at SERVO/components/layout/display_list_builder.rs:1900
  29:     0x7fe16eefbeaf - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1832
  30:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  31:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  32:     0x7fe16eefbd70 - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1822
  33:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  34:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  35:     0x7fe16eefbd70 - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1822
  36:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  37:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  38:     0x7fe16eefca28 - layout::display_list_builder::{{impl}}::create_real_stacking_context_for_block
                        at SERVO/components/layout/display_list_builder.rs:1932
  39:     0x7fe16eefbf15 - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1837
  40:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  41:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  42:     0x7fe16eefbd70 - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1822
  43:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  44:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  45:     0x7fe16eefbd70 - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1822
  46:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  47:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  48:     0x7fe16eefbd70 - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1822
  49:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  50:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  51:     0x7fe16eefbd70 - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1822
  52:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  53:     0x7fe16ed535ab - layout::flow::{{impl}}::collect_stacking_contexts_for_children
                        at SERVO/components/layout/flow.rs:1118
  54:     0x7fe16eefbd70 - layout::display_list_builder::{{impl}}::collect_stacking_contexts_for_block
                        at SERVO/components/layout/display_list_builder.rs:1822
  55:     0x7fe16eee6dec - layout::block::{{impl}}::collect_stacking_contexts
                        at SERVO/components/layout/block.rs:2198
  56:     0x7fe16ee3da23 - layout::sequential::build_display_list_for_subtree
                        at SERVO/components/layout/sequential.rs:79
  57:     0x7fe16b71ae63 - layout_thread::{{impl}}::compute_abs_pos_and_build_display_list::{{closure}}
                        at SERVO/components/layout_thread/lib.rs:922
  58:     0x7fe16b50bf21 - profile_traits::time::profile<(),closure>
                        at SERVO/components/profile_traits/time.rs:120
  59:     0x7fe16b71a913 - layout_thread::{{impl}}::compute_abs_pos_and_build_display_list
                        at SERVO/components/layout_thread/lib.rs:898
  60:     0x7fe16b722778 - layout_thread::{{impl}}::perform_post_main_layout_passes
                        at SERVO/components/layout_thread/lib.rs:1495
  61:     0x7fe16b721eaa - layout_thread::{{impl}}::perform_post_style_recalc_layout_passes
                        at SERVO/components/layout_thread/lib.rs:1479
  62:     0x7fe16b71ebb0 - layout_thread::{{impl}}::handle_reflow
                        at SERVO/components/layout_thread/lib.rs:1221
  63:     0x7fe16b7185cd - layout_thread::{{impl}}::handle_request_helper::{{closure}}
                        at SERVO/components/layout_thread/lib.rs:661
  64:     0x7fe16b50a89c - profile_traits::time::profile<(),closure>
                        at SERVO/components/profile_traits/time.rs:120
  65:     0x7fe16b717cf9 - layout_thread::{{impl}}::handle_request_helper
                        at SERVO/components/layout_thread/lib.rs:658
  66:     0x7fe16b716b18 - layout_thread::{{impl}}::handle_request
                        at SERVO/components/layout_thread/lib.rs:597
  67:     0x7fe16b715b66 - layout_thread::{{impl}}::start
                        at SERVO/components/layout_thread/lib.rs:506
  68:     0x7fe16b71220d - layout_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at SERVO/components/layout_thread/lib.rs:287
  69:     0x7fe16b50a358 - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script_layout_interface::message::Msg,script_layout_interface::message::Msg,std::sync::mpsc::Sender<script_layout_interface::message::Msg>>
                        at SERVO/components/profile_traits/mem.rs:63
  70:     0x7fe16b712895 - layout_thread::{{impl}}::create::{{closure}}
                        at SERVO/components/layout_thread/lib.rs:286
  71:     0x7fe16b6e902a - std::panic::{{impl}}::call_once<(),closure>
                        at RUST/src/libstd/panic.rs:296
  72:     0x7fe16b57b9b9 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at RUST/src/libstd/panicking.rs:460
  73:     0x7fe17127f37a - panic_unwind::__rust_maybe_catch_panic
                        at RUST/src/libpanic_unwind/lib.rs:98
  74:     0x7fe16b57af93 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at RUST/src/libstd/panicking.rs:436
  75:     0x7fe16b579934 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at RUST/src/libstd/panic.rs:361
  76:     0x7fe16b57a4bb - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at RUST/src/libstd/thread/mod.rs:357
  77:     0x7fe16b607282 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at RUST/src/liballoc/boxed.rs:605
  78:     0x7fe171277084 - alloc::boxed::{{impl}}::call_once<(),()>
                        at RUST/src/liballoc/boxed.rs:615
                         - std::sys_common::thread::start_thread
                        at RUST/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at RUST/src/libstd/sys/unix/thread.rs:84
  79:     0x7fe1683ef183 - start_thread
  80:     0x7fe167f0637c - clone
  81:                0x0 - <unknown>
```

**Comment by jdm** [comment] 2017-01-17 13:17
Duplicate of #14574.

**Closed by jdm** 2017-01-17 13:17 UTC
Labels: A-gfx/displaylist, I-panic
