### ISSUE TITLE
Servo results in a black window when loading github.com

### ISSUE THREAD

**Issue by beingalink** [servo/servo#12066] opened 2016-07-01 14:41 UTC
I clicked github on the start page which results in a black servo window (everything is black, no controls visible --> see [screenshot](https://www.dropbox.com/s/60rdyi4lmpak8oh/Screenshot%202016-07-01%2016.37.48.png?dl=0)).

I'm on macOS 10.11.6 running on my 2008 Macbook.

edit: Servo Version 0.0.1

edit2: having tested some more and the black screen seems to appear quite randomly:

- clicking a link on hackernews (but not always)
- opening a new tab after loading arstechnica homepage

**Comment by bnb** [comment] 2016-07-01 15:13
I downloaded Servo, mounted, opened, saw GitHub as a suggested site and immediately clicked it. It was finished loading for about ~1 second, and then the entire window went Black as well. Exactly the same as the screenshot. 

I'm on a 13 inch MacBook Pro Mid-2010 w/ 2.66GHz Intel Core 2 Duo with NVIDIA GeForce 320M 256 MB and 8 GB 1067 MHz DDR3.

**Comment by jdm** [comment] 2016-07-01 15:16
This sounds like a duplicate of #12041.

**Comment by beingalink** [comment] 2016-08-05 17:22
I started to test again today and I can't reproduce the issue anymore. Of course there are still lots of rendering issues and surfing arstechnica for a while destroys font rendering but the pages always display and I can scroll them (except when servo starts to freeze my Macbook but that's another issue I guess). Thanks for all the hard work!

**Comment by paulrouget** [comment] 2016-08-08 02:03
>  I can't reproduce the issue anymore.

Closing issue then.

> Of course there are still lots of rendering issues and surfing arstechnica for a while destroys font rendering but the pages always display and I can scroll them (except when servo starts to freeze my Macbook but that's another issue I guess)

Thanks for testing! Maybe you can file new issues for these specific problems?

**Closed by paulrouget** 2016-08-08 02:03 UTC
Labels: A-gfx/rendering, A-webrender
