### ISSUE TITLE
Screen corruption when moving window between Retina and normal DPI screen on OS X

### ISSUE THREAD

**Issue by bdewater** [servo/servo#12010] opened 2016-07-01 08:17 UTC
I have a MacBook Pro 13" (from 2015) with Retina screen running OS X 10.11.5 El Capitan and an normal DPI external full HD Dell monitor hooked up, both screens set at 'default for display' resolution in the display preferences. When dragging the browser window between the screens the screen gets corrupted:

Retina to Dell screen enlarges everything while the window stays the same size:
![screen shot 2016-07-01 at 10 06 16](https://cloud.githubusercontent.com/assets/496367/16515764/3a6d38fc-3f74-11e6-88db-35080bb1c2be.png)

Dell screen to Retina makes everything small. The site on the background is https://tweakers.net/nieuws/113087/maker-indiegame-ontslaat-ontwerper-wegens-kopieren-cod-wapens.html, the site I visited before going to reddit and dragging the windows to the other screen. The 'previous site background' sometimes rapidly flashed black.
<img width="1058" alt="screen shot 2016-07-01 at 10 04 56" src="https://cloud.githubusercontent.com/assets/496367/16515756/2fe132f8-3f74-11e6-8cd8-0fa20df0580a.png">

**Comment by jdm** [comment] 2016-07-01 15:14
This is probably the same problem as #12009.

**Comment by nox** [comment] 2017-10-02 08:14
Closing as duplicate of #12009.

**Closed by nox** 2017-10-02 08:14 UTC
Labels: A-gfx/rendering
