### ISSUE TITLE
UWP ver doesn't work due to problems with the cert

### ISSUE THREAD

**Issue by firefoxnightlymozzila** [servo/servo#28871] opened 2022-04-15 05:20 UTC
Found bundle: C:\Users\dude\Desktop\servo\ServoApp_1.2.0.0_x64_arm64.msixbundle
Found certificate: C:\Users\dude\Desktop\servo\ServoApp_1.2.0.0_x64_arm64.cer
Error: The developer certificate "C:\Users\dude\Desktop\servo\ServoApp_1.2.0.0_x64_arm64.cer" has expired. One possible cause is the system clock isn't set to the correct date and time. If the system settings are correct, contact the app owner to re-create a package or bundle with a valid certificate.
Press Enter to continue...:

oh and if i try to force it just crashes

**Comment by jdm** [comment] 2022-11-20 16:46
Duplicate of #28721.

**Closed by jdm** 2022-11-20 16:46 UTC
