### ISSUE TITLE
Crashes on lenta.ru website

### ISSUE THREAD

**Issue by vmakhaev** [servo/servo#12169] opened 2016-07-02 12:04 UTC
When I try to open `lenta.ru`, browser crashes.
It works fine on some other sites.

**Comment by Manishearth** [comment] 2016-07-02 12:04
Could you post the backtrace

**Comment by sbrinkerhoff** [comment] 2016-07-02 13:37
```$ ./Servo.app/Contents/MacOS/run-servo
Unhandled error occured
ReferenceError: navigator.mozSettings API is not available
ERROR:js::rust: Error at file:///Users/xxxxx/Servo.app/Contents/Resources/browserhtml-3e3805f69808f24d/out/components/main.js:7:13639: e.matches[e.items[e.selected]] is undefined

ERROR:js::rust: Error at https://icdn.lenta.ru/assets/shared/xtcore-87a6b762ad7b2b7a75a02e533e3d57d9.js:34:122: xt20 is undefined

thread '<unnamed>' panicked at 'TODO: Handle running out of texture IDs!', ../src/libcore/option.rs:699
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'ImageCacheThread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }', ../src/libcore/result.rs:785
ERROR:constellation::constellation: Panic: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }
ERROR:constellation::constellation: Backtrace:
frame #0  - 0x000000010daf56ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x000000010daf5651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000000010c362ca4 - _<F as alloc..boxed..FnBox<A>>::call_box::haeff945be1a63d60
frame #3  - 0x000000010da69947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010dcdd844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000000010dcf6786 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x000000010dcdee88 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x000000010dcf63df - rust_begin_unwind
frame #8  - 0x000000010dd1d260 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x000000010dc44d99 - core::result::unwrap_failed::hf40cb93f6f31ec3d
frame #10 - 0x000000010dc5ad89 - webrender_traits::api::RenderApi::set_root_stacking_context::h900f4ad7efd0b2a6
frame #11 - 0x000000010c481492 - layout_thread::LayoutThread::perform_post_main_layout_passes::h7b5f2ff1da7c5883
frame #12 - 0x000000010c3cba82 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::ha65b8390660d0026
frame #13 - 0x000000010c3cff8b - layout_thread::LayoutThread::handle_reflow::h6771f195a62bbc92
frame #14 - 0x000000010c3bbb6d - layout_thread::LayoutThread::handle_request_helper::h1029bbb7e9e50e59
frame #15 - 0x000000010c3a0e9f - layout_thread::LayoutThread::handle_request::ha13841b9d3ecdc81
frame #16 - 0x000000010c360b1a - std::panicking::try::call::h401e4a3a7768c3f1
frame #17 - 0x000000010dcf946b - __rust_try
frame #18 - 0x000000010dcf9405 - __rust_maybe_catch_panic
frame #19 - 0x000000010c361e84 - _<F as alloc..boxed..FnBox<A>>::call_box::h8169792cb3dac906
frame #20 - 0x000000010dcf4ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #21 - 0x00007fff8fd8599c - _pthread_body
frame #22 - 0x00007fff8fd85919 - _pthread_start

thread 'Constellation' panicked at 'assertion failed: mach_sys::mach_port_mod_refs(mach_task_self(), self.port,
                             MACH_PORT_RIGHT_SEND, 1) == KERN_SUCCESS', /Users/servo/.cargo/git/checkouts/ipc-channel-8c79851162410a92/master/platform/macos/mod.rs:330
thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:785
thread 'LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:785
thread 'LayoutWorker worker 3/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:785
thread 'LayoutWorker worker 4/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:785
thread 'LayoutWorker worker 5/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:785
thread 'LayoutWorker worker 6/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:785
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:785
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }', ../src/libcore/result.rs:785
```

**Comment by Manishearth** [comment] 2016-07-02 13:38
Thank you!

cc @glennw

**Comment by jdm** [comment] 2016-07-02 14:48
Looks like a duplicate of #12018. Thanks for reporting it!

**Closed by jdm** 2016-07-02 14:48 UTC
Labels: I-panic
