### ISSUE TITLE
assertion failed: allocation_size.width < max_texture_size()

### ISSUE THREAD

**Issue by cbrewster** [servo/servo#12192] opened 2016-07-03 02:42 UTC
```
thread '<unnamed>' panicked at 'assertion failed: allocation_size.width < max_texture_size()', /Users/connor/Development/servo/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/master/src/texture_cache.rs:804
stack backtrace:
   1:        0x101d4097b - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:        0x101d46f1a - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:        0x101d46b2a - std::panicking::default_hook::he0146e6a74621cb4
   4:        0x101ab86ef - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0fcde37d4d058867
   5:        0x101d2e5b4 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   6:        0x101219754 - std::panicking::begin_panic::h0bf39f6d43ab9349
   7:        0x1012da333 - webrender::texture_cache::TextureCache::allocate::hc9fafc665e1da4a5
   8:        0x1012d0236 - webrender::texture_cache::TextureCache::insert::h31e8d0897e772b38
   9:        0x10123eec6 - webrender::frame::Frame::build::h807c40a76c69b1d9
  10:        0x1012c5d85 - webrender::render_backend::RenderBackend::render::h40070fff4375c1da
  11:        0x101269926 - webrender::render_backend::RenderBackend::run::h9987749de8e4e926
  12:        0x1012e1f7f - std::panicking::try::call::hb19907cd84338eec
  13:        0x101d4a1db - __rust_try
  14:        0x101d4a175 - __rust_maybe_catch_panic
  15:        0x1012e2f64 - _<F as alloc..boxed..FnBox<A>>::call_box::h7c04c5c71e1bb530
  16:        0x101d45c58 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  17:     0x7fff9748d99c - _pthread_body
  18:     0x7fff9748d919 - _pthread_start
```

Found on https://mapbox.com

**Comment by nox** [comment] 2017-10-04 17:12
Does this still happen?

**Comment by jdm** [comment] 2017-10-04 23:15
I can't reproduce it.

**Comment by nox** [comment] 2017-10-04 23:18
Closing it, then.

**Closed by nox** 2017-10-04 23:18 UTC
Labels: A-webrender, C-reproduced, I-panic
