### ISSUE TITLE
Panic when using back button

### ISSUE THREAD

**Issue by timvandermeij** [servo/servo#9712] opened 2016-02-20 15:45 UTC
Steps to reproduce (100% of the time for me on Arch Linux x64):

1. Build Servo in release mode: `./mach build --release`
2. Visit the Leiden University homepage: `./mach run --release -- http://www.universiteitleiden.nl`
3. Click the "Over ons" link in the blue menu (any other link will work too)
4. Press the back button (backspace) on your keyboard
5. Notice Servo crashing with the following stack trace:

<pre>
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: base_time >= self.timers.borrow().last().unwrap().next_call', /home/timvandermeij/Documenten/Softwaredevelopment/servo/components/script/timers.rs:253
stack backtrace:
ERROR:js::rust: Error at http://www.universiteitleiden.nl/scripts/main.js:8:21: window.matchMedia is not a function

   1:     0x558516b9d120 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
   2:     0x558516ba009b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
   3:     0x558516b9fd06 - panicking::default_handler::h7ae2e4523ef4c187IFy
   4:     0x558516b88fac - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
   5:     0x5585156b26af - sys_common::unwind::begin_unwind::h2255876783782665235
   6:     0x558515b479aa - dom::window::Window::handle_fire_timer::h94975a378bcad1740pg
   7:     0x558515bb6e7e - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.172712
   8:     0x558515ba23fa - script_thread::ScriptThread::handle_msgs::hf57d19bea947009fbjl
   9:     0x558515b6fec7 - sys_common::unwind::try::try_fn::h12353014526015871128
  10:     0x558516b9c6fb - __rust_try
  11:     0x558516b98c1d - sys_common::unwind::inner_try::hf5df2c554f3d837dFdt
  12:     0x558515b714da - boxed::F.FnBox<A>::call_box::h12758028208235476498
  13:     0x558516b9eb23 - sys::thread::Thread::new::thread_start::h05e6a3d5b147b01bsCx
  14:     0x7f92f46594a3 - start_thread
  15:     0x7f92f4180dcc - clone
  16:                0x0 - <unknown>
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:704
stack backtrace:
   1:     0x558516b9d120 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
   2:     0x558516ba009b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
   3:     0x558516b9fd06 - panicking::default_handler::h7ae2e4523ef4c187IFy
thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } }LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }', ' panicked at '../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }:', 746../src/libcore/result.rs
:746
   4:     0x558516b88fac - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
   5:     0x558516b89698 - sys_common::unwind::begin_unwind_fmt::hd62d57279546b0f2Jft
   6:     0x558516b9c771 - rust_begin_unwind
   7:     0x558516bce08f - panicking::panic_fmt::h27f7225e08792f40qYL
   8:     0x558516bd5534 - option::expect_failed::hd2f3bf5ae63612e0zsO
   9:     0x5585152f6f32 - constellation::Constellation<LTF, STF>::handle_failure_msg::h15132916860460823008
  10:     0x55851526d34e - constellation::Constellation<LTF, STF>::handle_request::h12326144191581072998
  11:     0x55851525b0c7 - export::compositing::constellation::Constellation<LTF, STF>::start::_$u7b$$u7b$closure$u7d$$u7d$::closure.24103
  12:     0x55851525a8f8 - sys_common::unwind::try::try_fn::h2492253055594162308
  13:     0x558516b9c6fb - __rust_try
  14:     0x558516b98c1d - sys_common::unwind::inner_try::hf5df2c554f3d837dFdt
  15:     0x55851525c91a - boxed::F.FnBox<A>::call_box::h842506904514129251
  16:     0x558516b9eb23 - sys::thread::Thread::new::thread_start::h05e6a3d5b147b01bsCx
  17:     0x7f92f46594a3 - start_thread
  18:     0x7f92f4180dcc - clone
  19:                0x0 - <unknown>
stack backtrace:
   1:     0x558516b9d120 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
   2:     0x558516ba009b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
   3:     0x558516b9fd06 - panicking::default_handler::h7ae2e4523ef4c187IFy
   4:     0x558516b88fac - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
   5:     0x558516b89698 - sys_common::unwind::begin_unwind_fmt::hd62d57279546b0f2Jft
   6:     0x558516b9c771 - rust_begin_unwind
   7:     0x558516bce08f - panicking::panic_fmt::h27f7225e08792f40qYL
   8:     0x558515cc07a0 - result::unwrap_failed::h3765488879202930623
   9:     0x558515ceebbc - sys_common::unwind::try::try_fn::h14206235458649783283
  10:     0x558516b9c6fb - __rust_try
  11:     0x558516b98c1d - sys_common::unwind::inner_try::hf5df2c554f3d837dFdt
  12:     0x558515ceee1a - boxed::F.FnBox<A>::call_box::h18404140348438339068
  13:     0x558516b9eb23 - sys::thread::Thread::new::thread_start::h05e6a3d5b147b01bsCx
  14:     0x7f92f46594a3 - start_thread
  15:     0x7f92f4180dcc - clone
  16:                0x0 - <unknown>
stack backtrace:
   1:     0x558516b9d120 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
   2:     0x558516ba009b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
   3:     0x558516b9fd06 - panicking::default_handler::h7ae2e4523ef4c187IFy
   4:     0x558516b88fac - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
   5:     0x558516b89698 - sys_common::unwind::begin_unwind_fmt::hd62d57279546b0f2Jft
   6:     0x558516b9c771 - rust_begin_unwind
   7:     0x558516bce08f - panicking::panic_fmt::h27f7225e08792f40qYL
   8:     0x55851553c0e0 - result::unwrap_failed::h11896031497118501246
   9:     0x55851561a133 - layout_thread::LayoutThread::exit_now::hb24db544b581619aNVq
  10:     0x5585155f167c - layout_thread::LayoutThread::handle_request_helper::hbeefbd077e93e1baILq
  11:     0x5585155dd1c9 - layout_thread::LayoutThread::handle_request::hb2b176332d9340f97Fq
  12:     0x5585155a82ba - sys_common::unwind::try::try_fn::h11509959162076631806
  13:     0x558516b9c6fb - __rust_try
  14:     0x558516b98c1d - sys_common::unwind::inner_try::hf5df2c554f3d837dFdt
  15:     0x5585155a923a - boxed::F.FnBox<A>::call_box::h17667963835025417225
  16:     0x558516b9eb23 - sys::thread::Thread::new::thread_start::h05e6a3d5b147b01bsCx
  17:     0x7f92f46594a3 - start_thread
  18:     0x7f92f4180dcc - clone
  19:                0x0 - <unknown>
thread '<main>' panicked at 'Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }).', /home/timvandermeij/Documenten/Softwaredevelopment/servo/components/compositing/compositor.rs:739
stack backtrace:
   1:     0x558516b9d120 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
   2:     0x558516ba009b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
   3:     0x558516b9fd06 - panicking::default_handler::h7ae2e4523ef4c187IFy
   4:     0x558516b88fac - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
   5:     0x558516b89698 - sys_common::unwind::begin_unwind_fmt::hd62d57279546b0f2Jft
   6:     0x5585151f0296 - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h17155272857897908927
   7:     0x55851522c90c - Browser::handle_events::h1124a6422b46f740ifa
   8:     0x5585151d7dc5 - main::h8517eb49d15e90fbNaa
   9:     0x558516b9f964 - sys_common::unwind::try::try_fn::h9076850075504893162
  10:     0x558516b9c6fb - __rust_try
  11:     0x558516b9f3de - rt::lang_start::h58a22f304b0c1e19Oxy
  12:     0x7f92f40b860f - __libc_start_main
  13:     0x5585151cf408 - _start
  14:                0x0 - <unknown>
thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /home/timvandermeij/Documenten/Softwaredevelopment/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs:166
stack backtrace:
   1:     0x558516b9d120 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
   2:     0x558516ba009b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
   3:     0x558516b9fd06 - panicking::default_handler::h7ae2e4523ef4c187IFy
   4:     0x558516b88fac - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
   5:     0x558515f7639f - sys_common::unwind::begin_unwind::h16595920573307057729
   6:     0x558515f764a0 - platform::linux::surface::PixmapNativeSurface.Drop::drop::hf40f6d62236584a8Hfc
   7:     0x5585151eae74 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.29455::h4b49076b898f006b
   8:     0x5585151eaf75 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.29467::h5e9bf41c1d4d386b
   9:     0x5585151ead0c - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.29455::h4b49076b898f006b
  10:     0x5585151eaf75 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.29467::h5e9bf41c1d4d386b
  11:     0x5585151ead0c - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.29455::h4b49076b898f006b
  12:     0x5585151ecd41 - compositing..compositor..IOCompositor<app..window..Window>::drop.29818::h7cebf03249d807c7
  13:     0x5585151d7ea0 - main::h8517eb49d15e90fbNaa
  14:     0x558516b9f964 - sys_common::unwind::try::try_fn::h9076850075504893162
  15:     0x558516b9c6fb - __rust_try
  16:     0x558516b9f3de - rt::lang_start::h58a22f304b0c1e19Oxy
  17:     0x7f92f40b860f - __libc_start_main
  18:     0x5585151cf408 - _start
  19:                0x0 - <unknown>
thread panicked while panicking. aborting.
Servo exited with return value -4
</pre>

**Comment by ConnorGBrewster** [comment] 2016-05-25 03:58
Dupe of #9984.
Other issue has more information.

**Closed by ConnorGBrewster** 2016-05-25 03:58 UTC
Labels: A-content/script, I-panic
