### ISSUE TITLE
download.servo.org should redirect to HTTPS

### ISSUE THREAD

**Issue by alex** [servo/servo#12119] opened 2016-07-01 19:19 UTC
Right now if you access over HTTP it will server content. Instead it should redirect to HTTPS

**Comment by aneeshusa** [comment] 2016-07-01 19:20
Thanks for reporting! This is a dupe of servo/download.servo.org#1.

**Comment by alex** [comment] 2016-07-01 19:20
Doh, sorry.

**Closed by aneeshusa** 2016-07-01 19:20 UTC
