### ISSUE TITLE
Shift-7 enters "&" instead of "/" on German keyboard

### ISSUE THREAD

**Issue by llogiq** [servo/servo#12189] opened 2016-07-02 22:56 UTC
I just played around with servo a bit and found that I could not enter slashes because [Shift]+[7] inserts "&" instead of "/".

Steps to reproduce:

* get servo nightly for Linux x64
* build servo (because dependencies, copy over the nightly servo binary) 
* run servo/runservo.sh, marvel that it actually runs
* Click on the address bar
* Try to enter "/" on a German keyboard

**Comment by jdm** [comment] 2016-07-02 22:59
This is likely a duplicate of #4144 and should be fixed by #11950.

**Comment by ConnorGBrewster** [comment] 2016-07-22 03:17
Fixed #11950?

**Comment by est31** [comment] 2016-07-26 22:01
Testing this with a german keyboard on commit b41bf4f1f30b8f4eec92909c8971bc02d5422b50 , and confirming that shift-7 enters /. The original bug seems to be fixed. Also pressing z gives z and not y as a qwerty keyboard would.

But I can't enter any of the `<äöüß#+` keys. Note that `<+#` are even **within the ascii set**. Should I file a new bug report for this?

See this image where those keys are positioned: https://en.wikipedia.org/wiki/File:KB_Germany.svg

**Comment by jdm** [comment] 2016-07-27 13:15
Yes, please file a new issue report about that problem. Thanks for confirming this one!

**Closed by jdm** 2016-07-27 13:15 UTC
