### ISSUE TITLE
Servo panics when going back in history and clicking another link

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#8610] opened 2015-11-20 00:49 UTC
STR:
1. Run `./mach run -r http://en.wikipedia.org`
2. Click on any link
3. Hit the backspace key to go back one page in history
4. Click another link

Error log:
```
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: self.suspended_since.get().is_none()', /home/keith/Workspace/servo/components/script/timers.rs:342
stack backtrace:
   1:     0x564d4da8ac60 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x564d4da8d1b5 - panicking::log_panic::_<closure>::closure.39180
   3:     0x564d4da8cc01 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x564d4da793f3 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x564d4c728e9f - sys_common::unwind::begin_unwind::begin_unwind::h17566750670547345052
   6:     0x564d4cb8bdd9 - script_task::_<impl>::handle_msg_from_constellation::hb4242fa824a2cd23uCZ
   7:     0x564d4cb89305 - script_task::_<impl>::handle_msgs::_<closure>::closure.152475
   8:     0x564d4cb6d6e1 - script_task::_<impl>::handle_msgs::h765e7a096412d942fqZ
   9:     0x564d4cb55437 - boxed::_<impl>::call_box::call_box::h13668248650878965143
  10:     0x564d4c731f54 - sys_common::unwind::try::try_fn::try_fn::h3486882077396043177
  11:     0x564d4da8a198 - __rust_try
  12:     0x564d4da8676b - sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r
  13:     0x564d4c7320e4 - boxed::_<impl>::call_box::call_box::h6775911643068664290
  14:     0x564d4da8bca3 - sys::thread::_<impl>::new::thread_start::h89508aa1f401717d8Dw
  15:     0x7feabb3d94a3 - start_thread
  16:     0x7feabbbda13c - clone
  17:                0x0 - <unknown>
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:736
stack backtrace:
   1:     0x564d4da8ac60 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x564d4da8d1b5 - panicking::log_panic::_<closure>::closure.39180
   3:     0x564d4da8cc01 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x564d4da793f3 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x564d4da79aa8 - sys_common::unwind::begin_unwind_fmt::h44d552a66c65968bhcs
   6:     0x564d4da8a331 - rust_begin_unwind
   7:     0x564d4dabab8f - panicking::panic_fmt::h54ca80e608a83d7dwZK
   8:     0x564d4cd0d3bf - pipeline::_<impl>::force_exit::ha5c97d2a6d4a9f7fT0f
   9:     0x564d4c449b00 - constellation::_<impl>::close_pipeline::close_pipeline::h14224206250520487791
  10:     0x564d4c3d564e - constellation::_<impl>::handle_request::handle_request::h3919740813725213010
  11:     0x564d4c3c3227 - boxed::_<impl>::call_box::call_box::h259936311297667648
  12:     0x564d4c3c25f4 - sys_common::unwind::try::try_fn::try_fn::h1667191533889734737
  13:     0x564d4da8a198 - __rust_try
  14:     0x564d4da8676b - sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r
  15:     0x564d4c3c2784 - boxed::_<impl>::call_box::call_box::h6327951202590219566
  16:     0x564d4da8bca3 - sys::thread::_<impl>::new::thread_start::h89508aa1f401717d8Dw
  17:     0x7feabb3d94a3 - start_thread
  18:     0x7feabbbda13c - clone
  19:                0x0 - <unknown>
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:736
stack backtrace:
   1:     0x564d4da8ac60 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x564d4da8d1b5 - panicking::log_panic::_<closure>::closure.39180
   3:     0x564d4da8cc01 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x564d4da793f3 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x564d4da79aa8 - sys_common::unwind::begin_unwind_fmt::h44d552a66c65968bhcs
   6:     0x564d4da8a331 - rust_begin_unwind
   7:     0x564d4dabab8f - panicking::panic_fmt::h54ca80e608a83d7dwZK
   8:     0x564d4c6c7363 - query::_<impl>::mouse_over::hc6e4324be56c2edcpnt
   9:     0x564d4c9f2798 - dom::document::_<impl>::get_nodes_under_mouse::hc9c9a274ae163febDwo
  10:     0x564d4c9f77e1 - dom::document::_<impl>::handle_mouse_move_event::hc9a128b2fc356fb4xJo
  11:     0x564d4cb73014 - script_task::_<impl>::handle_event::h337a223292bd5441Wq0
  12:     0x564d4cb8b194 - script_task::_<impl>::handle_msg_from_constellation::hb4242fa824a2cd23uCZ
  13:     0x564d4cb89305 - script_task::_<impl>::handle_msgs::_<closure>::closure.152475
  14:     0x564d4cb6d6e1 - script_task::_<impl>::handle_msgs::h765e7a096412d942fqZ
  15:     0x564d4cb55437 - boxed::_<impl>::call_box::call_box::h13668248650878965143
  16:     0x564d4c731f54 - sys_common::unwind::try::try_fn::try_fn::h3486882077396043177
  17:     0x564d4da8a198 - __rust_try
  18:     0x564d4da8676b - sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r
  19:     0x564d4c7320e4 - boxed::_<impl>::call_box::call_box::h6775911643068664290
  20:     0x564d4da8bca3 - sys::thread::_<impl>::new::thread_start::h89508aa1f401717d8Dw
  21:     0x7feabb3d94a3 - start_thread
  22:     0x7feabbbda13c - clone
  23:                0x0 - <unknown>
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }Watcher' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:736
stack backtrace:
   1:     0x564d4da8ac60 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x564d4da8d1b5 - panicking::log_panic::_<closure>::closure.39180
   3:     0x564d4da8cc01 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x564d4da793f3 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x564d4da79aa8 - sys_common::unwind::begin_unwind_fmt::h44d552a66c65968bhcs
   6:     0x564d4da8a331 - rust_begin_unwind
   7:     0x564d4dabab8f - panicking::panic_fmt::h54ca80e608a83d7dwZK
   8:     0x564d4cb56522 - boxed::_<impl>::call_box::call_box::h1247736366721043051
   9:     0x564d4c731f54 - sys_common::unwind::try::try_fn::try_fn::h3486882077396043177
  10:     0x564d4da8a198 - __rust_try
  11:     0x564d4da8676b - sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r
  12:     0x564d4c7320e4 - boxed::_<impl>::call_box::call_box::h6775911643068664290
  13:     0x564d4da8bca3 - sys::thread::_<impl>::new::thread_start::h89508aa1f401717d8Dw
  14:     0x7feabb3d94a3 - start_thread
  15:     0x7feabbbda13c - clone
  16:                0x0 - <unknown>
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:736
stack backtrace:
   1:     0x564d4da8ac60 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x564d4da8d1b5 - panicking::log_panic::_<closure>::closure.39180
   3:     0x564d4da8cc01 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:   thread ' LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) } ' panicked at '0xcalled `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"564d4da793f3',  - sys_common::unwind::begin_unwind_inner::src/libcore/result.rsh04ad996baf6f81c7bds:
736
   5:     0x564d4da79aa8 - sys_common::unwind::begin_unwind_fmt::h44d552a66c65968bhcs
   6:     0x564d4da8a331 - rust_begin_unwind
   7:     0x564d4dabab8f - panicking::panic_fmt::h54ca80e608a83d7dwZK
   8:     0x564d4c39498e - compositor::_<impl>::send_viewport_rect_for_layer::send_viewport_rect_for_layer::h10798290059158781876
   9:     0x564d4c3a150e - compositor::_<impl>::composite_specific_target::composite_specific_target::h18154062884699432034
  10:     0x564d4c3a71f1 - compositor::_<impl>::composite::composite::h6931069707368661849
  11:     0x564d4c38227a - compositor::_<impl>::handle_events::handle_events::h17305756351041642916
  12:     0x564d4c3b331c - _<impl>::handle_events::h47777694780fa29cMda
  13:     0x564d4c3688a5 - main::h6ac4149d54e3c2d9Jaa
  14:     0x564d4da8c944 - sys_common::unwind::try::try_fn::h10604132475359592391
  15:     0x564d4da8a198 - __rust_try
  16:     0x564d4da8c5df - rt::lang_start::hd74bfb7a606308914ix
  17:     0x7feabbb1160f - __libc_start_main
  18:     0x564d4c35c508 - _start
  19:                0x0 - <unknown>
stack backtrace:
   1:     0x564d4da8ac60 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x564d4da8d1b5 - panicking::log_panic::_<thread 'closure<main>>' panicked at '::You should have disposed of the pixmap properly with destroy()! This pixmap will leak!closure.39180', 
/home/keith/Workspace/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs:166  
 3:     0x564d4da8cc01 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x564d4da793f3 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
   5:     0x564d4da79aa8 - sys_common::unwind::begin_unwind_fmt::h44d552a66c65968bhcs
   6:     0x564d4da8a331 - rust_begin_unwind
   7:     0x564d4dabab8f - panicking::panic_fmt::h54ca80e608a83d7dwZK
   8:     0x564d4c691b8a - layout_task::_<impl>::lock::h3272a1ab057db0bbNSq
   9:     0x564d4c6b9bb2 - layout_task::_<impl>::handle_request_helper::h8e943826ae19fca2W6q
  10:     0x564d4c6a5b98 - layout_task::_<impl>::handle_request::h182df02dad5bdb48m1q
  11:     0x564d4c675ffa - boxed::_<impl>::call_box::call_box::h18078886455560394372
  12:     0x564d4c675304 - sys_common::unwind::try::try_fn::try_fn::h15793814043348824985
  13:     0x564d4da8a198 - __rust_try
  14:     0x564d4da8676b - sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r
  15:     0x564d4c675494 - boxed::_<impl>::call_box::call_box::h5312207997483143735
  16:     0x564d4da8bca3 - sys::thread::_<impl>::new::thread_start::h89508aa1f401717d8Dw
  17:     0x7feabb3d94a3 - start_thread
  18:     0x7feabbbda13c - clone
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:736
  19:                0x0 - <unknown>
stack backtrace:
   1:     0x564d4da8ac60 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
   2:     0x564d4da8d1b5 - panicking::log_panic::_<closure>::closure.39180
   3:     0x564d4da8cc01 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
   4:     0x564d4da79318 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }  ' panicked at ' called `Result::unwrap()` on an `Err` value: RecvError5', : src/libcore/result.rs : 736 
 0x564d4d156c5f - sys_common::unwind::begin_unwind::begin_unwind::h1315571277216949999
   6:   thread ' LayoutWorker worker 1/3 ' panicked at '0xcalled `Result::unwrap()` on an `Err` value: RecvError564d4d156d60',  - src/libcore/result.rs:platform736::
linux::surface::_<impl>::drop::h29a3cb0d734fb8e5xfc
thread 'LayoutWorker worker 2/3  ' panicked at ' called `Result::unwrap()` on an `Err` value: RecvError7', : src/libcore/result.rs : 736 
 0x564d4c37cd47 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28719thread '::LayoutWorker worker 3/3h304233cac1dc042a' panicked at '
called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:  736 
8:     0x564d4c37ce95 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.28731::hb4fdef0af03ede03
   9:     0x564d4c37cc24 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28719::h304233cac1dc042a
  10:     0x564d4c37ecd3 - compositing..compositor..IOCompositor<app..window..Window>::drop.29096::hcaaf25679afc7cd2
  11:     0x564d4c368bbf - main::h6ac4149d54e3c2d9Jaa
  12:     0x564d4da8c944 - sys_common::unwind::try::try_fn::h10604132475359592391
  13:     0x564d4da8a198 - __rust_try
  14:     0x564d4da8c5df - rt::lang_start::hd74bfb7a606308914ix
  15:     0x7feabbb1160f - __libc_start_main
  16:     0x564d4c35c508 - _start
  17:                0x0 - <unknown>
thread panicked while panicking. aborting.stack backtrace:
   1:     0x564d4da8ac60 - sys::backtrace::tracingthread '::impLayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }Watcher::' panicked at 'writecalled `Result::unwrap()` on an `Err` value: "SendError(..)"::', h23bfa7a49ed99d87Kltsrc/libcore/result.rs
:736
   2:     0x564d4da8d1b5 - panicking::Servo exited with return value -4
```

**Comment by frewsxcv** [comment] 2015-11-20 04:25
Duplicate of #8461

**Closed by frewsxcv** 2015-11-20 04:25 UTC
