### ISSUE TITLE
Build failure for Android target on GNU/Linux

### ISSUE THREAD

**Issue by alanorth** [servo/servo#4628] opened 2015-01-14 12:45 UTC
Building for Android on Fedora 21 with the following tool versions:
- Android SDK r24.0.2
- Android NDK r10d
- Git master (at 221275267e61870ca2bac904149c0b14c63c3ebe)

After building with `./mach build --android`, I get the error:

```
$ RUST_BACKTRACE=1 ./mach build --android
make: Nothing to be done for 'all'.
    Updating git repository `https://github.com/servo/gcc-rs`
   Compiling style v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
   Compiling script v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
   Compiling msg v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
   Compiling devtools_traits v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
   Compiling devtools v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
   Compiling script_traits v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
   Compiling gfx v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
font.rs:139:10: 139:32 warning: use of deprecated item: Use overloaded core::cmp::PartialEq, #[warn(deprecated)] on by default
font.rs:139 impl<'a> Equiv<ShapeCacheEntry> for ShapeCacheEntryRef<'a> {
                     ^~~~~~~~~~~~~~~~~~~~~~
   Compiling layout_traits v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
   Compiling compositing v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
   Compiling glutin_app v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
   Compiling layout v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
css/matching.rs:68:23: 68:35 warning: use of deprecated item: Use overloaded core::cmp::PartialEq, #[warn(deprecated)] on by default
css/matching.rs:68         this_as_query.equiv(other)
                                         ^~~~~~~~~~~~
css/matching.rs:91:10: 91:49 warning: use of deprecated item: Use overloaded core::cmp::PartialEq, #[warn(deprecated)] on by default
css/matching.rs:91 impl<'a> Equiv<ApplicableDeclarationsCacheEntry> for ApplicableDeclarationsCacheQuery<'a> {
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Compiling servo v0.0.1 (file:///home/aorth/src/git/servo/components/servo)
error: linking with `../../support/android-rs-glue/apk-builder/target/apk-builder` failed: exit code: 101
note: ../../support/android-rs-glue/apk-builder/target/apk-builder '-Wl,--as-needed' '-Wl,--allow-multiple-definition' '-L' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib' '-o' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/servo' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/servo.o' '-Wl,--whole-archive' '-lmorestack' '-Wl,--no-whole-archive' '-Wl,--gc-sections' '-nodefaultlibs' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libglutin_app-6ac4695024ae218d.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libglutin-23a503f03b75d100.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libandroid_glue-c5bf5f33a0e6040a.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libgl_common-66a5d21dea94490e.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/libservo-c2b4c7f25b00b452.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libcompositing-4cbd78ce6084c676.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libdevtools-b07a60b503f9aa2d.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/liblayout-c82e682044402f5b.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libscript-f4eb3ab6901a7cf1.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libjs-7a5e44e37945e142.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/liblayout_traits-49eeb1d3e7c2f214.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libcanvas-e756e5cebbb78be6.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libgfx-80ccf902b038fef5.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libfontconfig-c046fa4ca41605a4.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libstyle-1fee32263761297b.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libuuid-7c7b259bcfa9d945.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libharfbuzz-d615f1063bc88db4.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libhtml5ever-80898f0002ba0361.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libscript_traits-87e66fd1f32a99a0.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libdevtools_traits-0e5cff01aa05c276.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libmsg-60a134f75d8740fc.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libnet-b79f05d33f8c799f.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libstb_image-8789d241efd7f3ef.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libutil-441501690bae53b6.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libhyper-890ae9892b5e4aec.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libmime-4b114bc7d7856ad5.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libcookie-03a3f41cb989f010.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libopenssl-089fe2b2f27936a4.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libopenssl-sys-8d5618621883f42c.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/liburl-e5595358222a824d.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libmucell-15aa001c80416321.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libazure-83ae91b5b2ebf272.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/liblayers-9896bcf77fe232f4.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libegl-90ba2a473034ea1d.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libgeom-92d0f13f38b09c46.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libtime-2190589dd2e89ebf.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libstring_cache-1cf14970ab03ef33.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libphf-987a440fbd694b69.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libxxhash-245c85292ece0c63.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libunsafe-any-3d2f45b7c92200ea.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libpng-2a5686ec81c888ef.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/libtest-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/libserialize-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/libgetopts-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/libterm-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/liblog-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/libregex-4e7c5e5c.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libcssparser-7a9a471368ea9b30.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libencoding-5d9283f8df6a2add.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libencoding-index-korean-7f619e1decbc8e76.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libencoding-index-tradchinese-47f074fd879a44ba.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libtext_writer-83aeadef5ad6c975.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libencoding-index-simpchinese-2d7c8c32f7e9f2b2.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libgleam-e5559c03c0bebfba.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libencoding-index-japanese-78d9d2f7567be380.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libencoding-index-singlebyte-e8309dce7b73ab02.rlib' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps/libfreetype-f9e33152a2a3bfec.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/libstd-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/librustrt-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/libcollections-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/liballoc-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/liblibc-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/librand-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/libunicode-4e7c5e5c.rlib' '/home/aorth/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/arm-linux-androideabi/lib/libcore-4e7c5e5c.rlib' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/deps' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/task_info-6e2ef66318f0c437' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/script-f4eb3ab6901a7cf1' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/stb_image-8789d241efd7f3ef' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/style-1fee32263761297b' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/azure-83ae91b5b2ebf272' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/skia-sys-a0c97fb5e4120410' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/freetype-sys-2000ed3efd86d8e0' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/expat-sys-3543c70bfcd7875f' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/harfbuzz-d615f1063bc88db4' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/fontconfig-sys-4770bf8b8048ff82' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/js-7a5e44e37945e142' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/native/mozjs-sys-c58a7d09513f4944' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/build/png-2a5686ec81c888ef/out' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/build/png-sys-a883925b69dc7bc9/out/.libs' '-L' '/home/aorth/src/git/servo/components/servo/target/arm-linux-androideabi/build/time-2190589dd2e89ebf/out' '-L' '/home/aorth/src/git/servo/components/servo/.rust' '-L' '/home/aorth/src/git/servo/components/servo' '-Wl,--whole-archive' '-Wl,-Bstatic' '-Wl,--no-whole-archive' '-Wl,-Bdynamic' '-landroid' '-lEGL' '-lGLESv2' '-landroid' '-llog' '-landroid' '-lmozjs' '-lz' '-ljsglue' '-lstdc++' '-lgcc' '-lc' '-lfontconfig' '-lc' '-lstdc++' '-lstdc++' '-lexpat' '-lfontconfig' '-lEGL' '-lazure' '-lEGL' '-lEGL' '-lz' '-lfreetype' '-ldl' '-llog' '-lgcc' '-lc' '-lm' '-lcompiler-rt'
note: task '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: no such file or directory', /home/larsberg/rust/src/libcore/result.rs:744
stack backtrace:
   1:     0x7ff83b216960 - rt::backtrace::imp::write::hcd80980f0951bf03BOx
   2:     0x7ff83b219820 - failure::on_fail::h0784b2f3b5063f7b1fy
   3:     0x7ff83b2272f0 - unwind::begin_unwind_inner::hbb866c9343c337b3CJc
   4:     0x7ff83b226df0 - unwind::begin_unwind_fmt::hc8ff41ee2219db01ZGc
   5:     0x7ff83b226db0 - rust_begin_unwind
   6:     0x7ff83b258c60 - panicking::panic_fmt::h11d71ece8830accb1tl
   7:     0x7ff83b1d31c0 - result::Result<T, E>::unwrap::h7324392229085769308
   8:     0x7ff83b1c4de0 - main::h2be5494638d7e663laa
   9:     0x7ff83b21a9c0 - rt::start::closure.32131
  10:     0x7ff83b227e80 - rust_try_inner
  11:     0x7ff83b227e70 - rust_try
  12:     0x7ff83b225780 - unwind::try::hf0141b63ff6a0a11Tyc
  13:     0x7ff83b225550 - task::Task::run::hcbcff3a8c16a161bfKb
  14:     0x7ff83b21a670 - rt::start::h62350456819945d7S9x
  15:     0x7ff83b21a5e0 - rt::lang_start::ha29b24b5e36342a7b9x
  16:     0x7ff83b1c65d0 - main
  17:     0x7ff83a3baef0 - __libc_start_main
  18:     0x7ff83b1c4cb0 - <unknown>
  19:                0x0 - <unknown>

error: aborting due to previous error
Could not compile `servo`.

To learn more, run the command again with --verbose.
Build completed in 193.93s
```

**Comment by jdm** [comment] 2015-01-14 15:23
@alanorth Does support/android-rs-glue/apk-builder/target/apk-builder exist? How about all of the .o and .rlib files listed in the `note:` line?

**Comment by jdm** [comment] 2015-01-14 15:23
@mbrubeck @larsbergstrom Is this something you've seen before?

**Comment by mbrubeck** [comment] 2015-01-14 17:09
I haven't seen this.  Maybe @glennw would know.

What versions of the Android SDK and NDK are you using?

**Comment by larsbergstrom** [comment] 2015-01-14 17:15
@alanorth Did you set the ANDROID_ environment variables and augment the PATH exactly as described in the wiki at: https://github.com/servo/servo/wiki/Building-for-Android ?

Our Android (and Gonk) builds are unfortunately extremely "touchy" and sensitive to which variables are / are not set and often fail in somewhat mysterious ways if they are not set perfectly.

**Comment by alanorth** [comment] 2015-01-14 18:44
@jdm Yes, `support/android-rs-glue/apk-builder/target/apk-builder` exists in my Servo build.  Though I'm not sure where the `note:` line is (I'm new to Rust / Servo).

@mbrubeck Android SDK is r24.0.2 and NDK is r10d, the latest as of 2015-01-14.

@larsbergstrom Yes, I setup my build environment exactly as the Building for Android instructions said, and exported all `ANDROID_` variables before build.

**Comment by jdm** [comment] 2015-01-14 19:12
@alanorth It's right under the
```
error: linking with `../../support/android-rs-glue/apk-builder/target/apk-builder` failed: exit
``` line in the log in the original issue description.

**Comment by mbrubeck** [comment] 2015-01-14 19:54
For reference, I'm still on NDK r9d.  I'll try with the newer NDK later and see if I have any problems.

**Comment by Jinwoo-Song** [comment] 2015-04-30 04:23
I have a same problem in building Servo for Android. I'm using NDK r10d in Ubuntu. Is there any hint for resolving this?

**Comment by larsbergstrom** [comment] 2015-05-03 19:38
@Jinwoo-Song I have been unable to reproduce this issue, and our Android builders are on NDK r10c on Ubuntu (see https://github.com/servo/saltfs/blob/master/android-dependencies.sls for how they are set up).

Are the environment variables (both ANDROID_ and the extra PATH entry) added correctly?

Also, did you do `./mach clean` before performing an android build? I've noticed that the Cargo build system is often very bad at dealing with the changed targets.

Sorry for the inconvenience!

**Comment by larsbergstrom** [comment] 2016-07-01 20:13
This should work now. Please reopen if it reproduces.

**Closed by larsbergstrom** 2016-07-01 20:13 UTC
Labels: P-android
