### ISSUE TITLE
assertion failed: `(left != right)`

### ISSUE THREAD

**Issue by lua-rocks** [servo/servo#28407] opened 2021-05-02 17:19 UTC
I downloaded latest linux release from https://servo.org (on Xubuntu 20.04)
Unpacked it and launched: `./servo`
And it says:
```
assertion failed: `(left != right)`
  left: `0x0`,
 right: `0x0` (thread main, at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/surfman-0.4.1/src/platform/generic/egl/surface.rs:179)
```

**Comment by jdm** [comment] 2021-05-02 21:11
EGL is returning NO_SURFACE from https://github.com/servo/surfman/blob/efd6bdbd29c47f6ffd993db33db5cf6b852723c7/surfman/src/platform/generic/egl/surface.rs#L173-L179. I'm not really sure what the next step to investigate is, unfortunately.

**Comment by mrobinson** [comment] 2023-11-09 11:18
This is a duplicate of #27770, I think.

**Closed by mrobinson** 2023-11-09 11:18 UTC
Labels: P-linux, A-gfx/compositing
