### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }

### ISSUE THREAD

**Issue by WardCunningham** [servo/servo#12152] opened 2016-07-02 01:41 UTC
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }
### URL:
http://ward.asia.wiki.org/view/federation-search
### Backtrace:
```
frame #0  - 0x00000001020b86ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x00000001020b8651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000000100925ca4 - _<F as alloc..boxed..FnBox<A>>::call_box::haeff945be1a63d60
frame #3  - 0x000000010202c947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x00000001022a0844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x00000001022b9786 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x00000001022a1e88 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x00000001022b93df - rust_begin_unwind
frame #8  - 0x00000001022e0260 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x000000010091738e - core::result::unwrap_failed::hf40cb93f6f31ec3d
frame #10 - 0x0000000100994e0f - layout_thread::LayoutThread::exit_now::h9c02213ba81aad74
frame #11 - 0x00000001009783a3 - layout_thread::LayoutThread::handle_request_helper::h1029bbb7e9e50e59
frame #12 - 0x0000000100963f1a - layout_thread::LayoutThread::handle_request::ha13841b9d3ecdc81
frame #13 - 0x0000000100923b1a - std::panicking::try::call::h401e4a3a7768c3f1
frame #14 - 0x00000001022bc46b - __rust_try
frame #15 - 0x00000001022bc405 - __rust_maybe_catch_panic
frame #16 - 0x0000000100924e84 - _<F as alloc..boxed..FnBox<A>>::call_box::h8169792cb3dac906
frame #17 - 0x00000001022b7ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #18 - 0x00007fff8d7fc898 - _pthread_body
frame #19 - 0x00007fff8d7fc729 - _pthread_start

```

**Comment by WardCunningham** [comment] 2016-07-02 01:42
this is a different path into #12149

**Comment by ConnorGBrewster** [comment] 2016-07-02 02:19
Thank you for the report, this should be fixed by #12030.

**Comment by jdm** [comment] 2016-07-02 02:51
Reopening because the panic backtraces reported are often not the underlying cause.

**Comment by jdm** [comment] 2016-07-02 02:52
```
(lldb) bt
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
* thread #29: tid = 0x218926, 0x00000001048eda90 servo`rust_panic, stop reason = breakpoint 1.1
  * frame #0: 0x00000001048eda90 servo`rust_panic
    frame #1: 0x00000001048e362d servo`std::panicking::rust_panic_with_hook::h983af77c1a2e581b + 413
    frame #2: 0x000000010101a888 servo`std::panicking::begin_panic<&str>(msg=&str at 0x00000001205f9f90, file_line=0x0000000105f0a588) + 120 at panicking.rs:328
    frame #3: 0x0000000102085f4a servo`script::dom::document::{{impl}}::decrement_script_blocking_stylesheet_count(self=0x000000012085f000) + 106 at <std macros>:3
    frame #4: 0x00000001022077ad servo`script::dom::htmllinkelement::{{impl}}::response_complete(self=0x000000012097e618, status=Result<(), net_traits::NetworkError> at 0x00000001205fa9a8) + 3085 at htmllinkelement.rs:329
    frame #5: 0x00000001022066be servo`net_traits::{{impl}}::process<script::dom::htmllinkelement::StylesheetContext>(self=ResponseAction at 0x00000001205facb8, listener=0x000000012097e618) + 494 at lib.rs:268
    frame #6: 0x0000000102205beb servo`script::network_listener::{{impl}}::handler<net_traits::ResponseAction,script::dom::htmllinkelement::StylesheetContext>(self=0x0000000117c69f80) + 459 at network_listener.rs:64
    frame #7: 0x000000010250573d servo`script::script_thread::{{impl}}::handle_msg_from_script(self=0x00000001205feeb0, msg=MainThreadScriptMsg at 0x00000001205fb428) + 1437 at script_thread.rs:977
    frame #8: 0x000000010259ca39 servo`script::script_thread::{{impl}}::handle_msgs::{{closure}} + 409 at script_thread.rs:803
    frame #9: 0x000000010259c5a6 servo`script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>(self=0x00000001205feeb0, category=NetworkEvent, f=closure at 0x00000001205fbdd0) + 1062 at script_thread.rs:899
    frame #10: 0x000000010256a4be servo`script::script_thread::{{impl}}::handle_msgs(self=0x00000001205feeb0) + 7998 at script_thread.rs:795
    frame #11: 0x0000000102502e8d servo`script::script_thread::{{impl}}::start(self=0x00000001205feeb0) + 29 at script_thread.rs:642
    frame #12: 0x0000000102502e3c servo`script::script_thread::{{impl}}::create::{{closure}}::{{closure}} + 44 at script_thread.rs:480
    frame #13: 0x0000000102502b92 servo`profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(self=0x00000001205ff130, f=closure at 0x00000001205fe8f0, reporter_name=String at 0x00000001205fe8d0, channel_for_reporter=Sender<script::script_thread::MainThreadScriptMsg> at 0x00000001205fe8b8, msg=0x0000000000000020) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>> + 690 at mem.rs:59
    frame #14: 0x00000001024eee47 servo`script::script_thread::{{impl}}::create::{{closure}} + 1687 at script_thread.rs:479
    frame #15: 0x00000001024ed4df servo`util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::ha261492d86c01b55 + 495 at boxed.rs:234
    frame #16: 0x00000001024ed298 servo`std::panic::{{impl}}::call_once<(self=AssertUnwindSafe<closure> at 0x00000001205ff708, _args=<unavailable>),closure> + 136 at panic.rs:251
    frame #17: 0x00000001024ed1ec servo`std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfe27440cc777623d + 92
    frame #18: 0x00000001024edaa5 servo`std::panicking::try::call<closure>(f=0x00000001205ffe98) + 21 at panicking.rs:272
    frame #19: 0x00000001048ff3bc servo`__rust_try + 12
    frame #20: 0x00000001048ff356 servo`__rust_maybe_catch_panic + 38
    frame #21: 0x00000001024ed13e servo`std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::hcd95cd3a8c551981 + 158
    frame #22: 0x00000001024ed090 servo`std::thread::local::{{impl}}::with<core::cell::Cell<usize>,closure,core::result::Result<(self=0x00000001060fa6a0, f=closure at 0x00000001205fff38), Box<Any>>> + 208 at local.rs:211
    frame #23: 0x00000001024ecec0 servo`std::panicking::try<(f=AssertUnwindSafe<closure> at 0x0000000120600218),std::panic::AssertUnwindSafe<closure>> + 192 at panicking.rs:235
    frame #24: 0x00000001024ecd9f servo`std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,(f=AssertUnwindSafe<closure> at 0x00000001206006b8)> + 143 at panic.rs:307
    frame #25: 0x00000001024ecbfd servo`std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h5ebfd442ff8ff2f3 + 349
    frame #26: 0x00000001024edca8 servo`alloc::boxed::{{impl}}::call_box<(self=0x000000011e256000, args=<unavailable>),closure> + 104 at boxed.rs:544
    frame #27: 0x00000001048fae39 servo`std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46 + 57
    frame #28: 0x00007fff8fd62899 libsystem_pthread.dylib`_pthread_body + 138
    frame #29: 0x00007fff8fd6272a libsystem_pthread.dylib`_pthread_start + 137
    frame #30: 0x00007fff8fd66fc9 libsystem_pthread.dylib`thread_start + 13
(lldb) f 3
frame #3: 0x0000000102085f4a servo`script::dom::document::{{impl}}::decrement_script_blocking_stylesheet_count(self=0x000000012085f000) + 106 at <std macros>:3
(lldb) up
frame #4: 0x00000001022077ad servo`script::dom::htmllinkelement::{{impl}}::response_complete(self=0x000000012097e618, status=Result<(), net_traits::NetworkError> at 0x00000001205fa9a8) + 3085 at htmllinkelement.rs:329
   326 	        }
   327
   328 	        if elem.parser_inserted.get() {
-> 329 	            document.decrement_script_blocking_stylesheet_count();
   330 	        }
   331
   332 	        document.finish_load(LoadType::Stylesheet(self.url.clone()));
```
Closing as a duplicate of #12149, as previously reported.

**Closed by jdm** 2016-07-02 02:52 UTC
