### ISSUE TITLE
Properly implement options in EventListener methods

### ISSUE THREAD

**Issue by nox** [servo/servo#11581] opened 2016-06-03 14:14 UTC
According to [the spec](https://dom.spec.whatwg.org/#interface-eventtarget), the methods `addEventListener` and `removeEventListener` shouldn't take just a boolean, but also should accept some specific dictionaries.

Files:
* components/script/dom/eventtarget.rs
* components/script/dom/webidls/EventTarget.webidl

**Comment by GuillaumeGomez** [comment] 2016-06-03 23:00
I take it.

**Comment by KiChjang** [comment] 2016-06-04 00:41
This is a duplicate of #9785, and last I heard, there wasn't consensus on whether or not this is a good idea. cc @Ms2ger

**Closed** 2016-06-04 00:42 UTC
Labels: A-content/dom, C-assigned
