### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

### ISSUE THREAD

**Issue by grahamc** [servo/servo#14541] opened 2016-12-10 03:01 UTC
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
### URL:
https://www.tumblr.com/
### Servo Version:
Servo 0.0.1-4cb3404
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(6), index: PipelineIndex(8) }>: Panic hook called.
WARNING: <Constellation>: creating replacement pipeline for about:failure
ERROR: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

stack backtrace:
   0:     0x55ce91bfa0dd - backtrace::backtrace::trace::h90be2828c7ec6b59
   1:     0x55ce91bfa762 - backtrace::capture::Backtrace::new::h8135b43a33e0c535
   2:     0x55ce91a6e1d4 - constellation::constellation::log_entry::h62c1243922d9c14c
   3:     0x55ce91a6d160 - _<constellation..constellation..FromCompositorLogger as log..Log>::log::h19ce0bb50b7e6aa7
   4:     0x55ce92293dff - log::__log::hb57b61a1a8ce0303
   5:     0x55ce90547d27 - servo::main::_{{closure}}::h1e714f61107224fb
   6:     0x55ce922bcb34 - std::panicking::rust_panic_with_hook
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:452
   7:     0x55ce922bc9f4 - std::panicking::begin_panic<collections::string::String>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   8:     0x55ce922bc919 - std::panicking::begin_panic_fmt
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   9:     0x55ce922bc8a7 - std::panicking::rust_begin_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
  10:     0x55ce922fa9cd - core::panicking::panic_fmt
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
  11:     0x55ce910d5f29 - core::result::unwrap_failed::heddba7ac052debda
  12:     0x55ce91129dbb - _<layout..query..LayoutRPCImpl as script_layout_interface..rpc..LayoutRPC>::hit_test::h139c5a662e7018b9
  13:     0x55ce90b9a900 - script::dom::document::Document::handle_mouse_move_event::h40ab0dfc636e746e
  14:     0x55ce90db1283 - script::script_thread::ScriptThread::handle_event::h6f003613e00bdb9f
  15:     0x55ce90d8bb23 - script::script_thread::ScriptThread::handle_msg_from_constellation::he9cc91c5327b902c
  16:     0x55ce90d8a16d - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h1f5a79bb7fbb3810
  17:     0x55ce90d851b0 - script::script_thread::ScriptThread::handle_msgs::hae2639600700e79d
  18:     0x55ce908fb457 - std::panicking::try::do_call::h43a5dc216f489e46
  19:     0x55ce922c561a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  20:     0x55ce90aa5d44 - _<F as alloc..boxed..FnBox<A>>::call_box::h33cc8351c6dd3b0b
  21:     0x55ce922bb7d4 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:605
                         - std::sys_common::thread::start_thread
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/thread.rs:84
  22:     0x7fb2afbf21f3 - start_thread
  23:     0x7fb2af71e12e - __GI___clone
  24:                0x0 - <unknown>
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-12-13 21:43
I'm having trouble reproducing this. It could be because tumblr's front-page content changes constantly :(

**Comment by jonathandturner** [comment] 2017-07-04 22:37
@jdm - I can repro a very similar error this way:

* In bhtml mode, click on the url bar and go to "polygon.com"
* Scroll down until you see three reviews on the left.
* Wait 5 seconds
* Click the "All Reviews" button

**Comment by jdm** [comment] 2017-07-05 00:11
Me too:
```
Node was being treated as inline, but it has an associated fragment! (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /Users/jdm/src/master-servo/components/layout/query.rs:541)
stack backtrace:
   0:        0x1077e46a4 - backtrace::backtrace::trace<closure>
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:        0x1077eef8f - backtrace::capture::Backtrace::new::h08bbd1a61f799546
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:        0x103199bd3 - servo::main::{{closure}}
                        at /Users/jdm/src/master-servo/ports/servo/main.rs:129
   3:        0x1093d3309 - std::panicking::rust_panic_with_hook::h07a59b4ad630aa5c
                        at src/libstd/panicking.rs:550
   4:        0x107be7ac9 - std::panicking::begin_panic<&str>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:511
   5:        0x107b9297d - _$LT$layout..query..ParentOffsetBorderBoxIterator$u20$as$u20$layout..fragment..FragmentBorderBoxIterator$GT$::process::hd0fc5d99c19adeba
                        at /Users/jdm/src/master-servo/components/layout/query.rs:541
   6:        0x107d9e31a - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::iterate_through_fragment_border_boxes::h502c516c9a40a4d8
                        at /Users/jdm/src/master-servo/components/layout/block.rs:2163
   7:        0x107ccf8fc - layout::sequential::iterate_through_flow_tree_fragment_border_boxes::doit
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:105
   8:        0x107ccfe10 - layout::sequential::iterate_through_flow_tree_fragment_border_boxes::doit
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:124
   9:        0x107ccfe10 - layout::sequential::iterate_through_flow_tree_fragment_border_boxes::doit
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:124
  10:        0x107ccfe10 - layout::sequential::iterate_through_flow_tree_fragment_border_boxes::doit
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:124
  11:        0x107ccfe10 - layout::sequential::iterate_through_flow_tree_fragment_border_boxes::doit
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:124
  12:        0x107ccfe10 - layout::sequential::iterate_through_flow_tree_fragment_border_boxes::doit
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:124
  13:        0x107ccfe10 - layout::sequential::iterate_through_flow_tree_fragment_border_boxes::doit
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:124
  14:        0x107ccfe10 - layout::sequential::iterate_through_flow_tree_fragment_border_boxes::doit
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:124
  15:        0x107ccfe10 - layout::sequential::iterate_through_flow_tree_fragment_border_boxes::doit
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:124
  16:        0x107ccf7fc - layout::sequential::iterate_through_flow_tree_fragment_border_boxes::h570028ef2d5bdbb8
                        at /Users/jdm/src/master-servo/components/layout/sequential.rs:128
  17:        0x10364c7ba - layout::query::process_offset_parent_query<script::layout_wrapper::ServoLayoutNode>
                        at /Users/jdm/src/master-servo/components/layout/query.rs:847
  18:        0x1036bc740 - layout_thread::{{impl}}::respond_to_query_if_necessary
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:1392
  19:        0x1036ba0cd - layout_thread::{{impl}}::handle_reflow
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:1305
  20:        0x1038caacd - layout_thread::{{impl}}::handle_request_helper::{{closure}}
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:675
  21:        0x1037ec4c7 - profile_traits::time::profile<(),closure>
                        at /Users/jdm/src/master-servo/components/profile_traits/time.rs:121
  22:        0x1036b3723 - layout_thread::{{impl}}::handle_request_helper
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:672
  23:        0x1036b2852 - layout_thread::{{impl}}::handle_request
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:644
  24:        0x1036b19d9 - layout_thread::{{impl}}::start
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:561
  25:        0x1036aeb33 - layout_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:290
  26:        0x103589222 - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script_layout_interface::message::Msg,script_layout_interface::message::Msg,std::sync::mpsc::Sender<script_layout_interface::message::Msg>>
                        at /Users/jdm/src/master-servo/components/profile_traits/mem.rs:63
  27:        0x1038ca601 - layout_thread::{{impl}}::create::{{closure}}
                        at /Users/jdm/src/master-servo/components/layout_thread/lib.rs:289
  28:        0x103816147 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  29:        0x1035c26c0 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:364
  30:        0x103558967 - std::panic::{{impl}}::call_once<(),closure>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:296
  31:        0x1035c37e6 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:454
  32:        0x1093d453c - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:98
  33:        0x1035c28fc - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:433
  34:        0x1035c2622 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:361
  35:        0x103817573 - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:363
  36:        0x103860f33 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:652
  37:        0x1093d031b - std::sys::imp::thread::{{impl}}::new::thread_start
                        at src/libstd/sys_common/thread.rs:21
  38:     0x7fffb4e6893a - _pthread_body
  39:     0x7fffb4e68886 - _pthread_start
```
followed by
```
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at src/libcore/result.rs:860)
stack backtrace:
   0:        0x1077e46a4 - backtrace::backtrace::trace<closure>
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:        0x1077eef8f - backtrace::capture::Backtrace::new::h08bbd1a61f799546
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:        0x103199bd3 - servo::main::{{closure}}
                        at /Users/jdm/src/master-servo/ports/servo/main.rs:129
   3:        0x1093d3309 - std::panicking::rust_panic_with_hook::h07a59b4ad630aa5c
                        at src/libstd/panicking.rs:550
   4:        0x1093d3164 - std::panicking::begin_panic<alloc::string::String>
                        at src/libstd/panicking.rs:511
   5:        0x1093d30e2 - std::panicking::begin_panic_fmt::ha268370d12baa79c
                        at src/libstd/panicking.rs:495
   6:        0x1093d3047 - rust_begin_unwind
                        at src/libstd/panicking.rs:471
   7:        0x1093fdf00 - core::panicking::panic_fmt::hd120ccda11abebf7
                        at src/libcore/panicking.rs:71
   8:        0x107d48f08 - core::result::unwrap_failed<std::sys_common::poison::PoisonError<std::sync::mutex::MutexGuard<layout::query::LayoutThreadData>>>
                        at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:29
   9:        0x107addcff - core::result::{{impl}}::unwrap<std::sync::mutex::MutexGuard<layout::query::LayoutThreadData>,std::sys_common::poison::PoisonError<std::sync::mutex::MutexGuard<layout::query::LayoutThreadData>>>
                        at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:738
  10:        0x107b91193 - _$LT$layout..query..LayoutRPCImpl$u20$as$u20$script_layout_interface..rpc..LayoutRPC$GT$::offset_parent::hfbb39563344c52bf
                        at /Users/jdm/src/master-servo/components/layout/query.rs:179
  11:        0x105c89703 - script::dom::window::Window::offset_parent_query::haff24008333cff50
                        at /Users/jdm/src/master-servo/components/script/dom/window.rs:1511
  12:        0x105be76a5 - _$LT$script..dom..htmlelement..HTMLElement$u20$as$u20$script..dom..bindings..codegen..Bindings..HTMLElementBinding..HTMLElementBinding..HTMLElementMethods$GT$::OffsetLeft::h0287ed23ebe1b7ab
                        at /Users/jdm/src/master-servo/components/script/dom/htmlelement.rs:351
  13:        0x104a0ca32 - script::dom::bindings::codegen::Bindings::HTMLElementBinding::HTMLElementBinding::get_offsetLeft::{{closure}}
                        at /Users/jdm/src/master-servo/target/debug/build/script-e76373ee7ebff941/out/Bindings/HTMLElementBinding.rs:873
  14:        0x1047e1907 - core::ops::function::FnOnce::call_once<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:143
  15:        0x10448dd5a - std::panic::{{impl}}::call_once<bool,closure>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:296
  16:        0x10476d7c7 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,bool>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:454
  17:        0x1093d453c - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:98
  18:        0x10465712d - std::panicking::try<bool,std::panic::AssertUnwindSafe<closure>>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:433
  19:        0x1044e5531 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,bool>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:361
  20:        0x103bd5ff0 - js::panic::wrap_panic<std::panic::AssertUnwindSafe<closure>,bool>
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/panic.rs:22
  21:        0x105d7738c - script::dom::bindings::codegen::Bindings::HTMLElementBinding::HTMLElementBinding::get_offsetLeft
                        at /Users/jdm/src/master-servo/target/debug/build/script-e76373ee7ebff941/out/Bindings/HTMLElementBinding.rs:871
  22:        0x10600316a - CallJitGetterOp
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/jsglue.cpp:498
  23:        0x105138c20 - script::dom::bindings::utils::generic_call
                        at /Users/jdm/src/master-servo/components/script/dom/bindings/utils.rs:446
  24:        0x105138e51 - script::dom::bindings::utils::generic_getter
                        at /Users/jdm/src/master-servo/components/script/dom/bindings/utils.rs:462
  25:        0x106478c74 - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  26:        0x10649c11b - CallGetter(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::Value>, JS::Handle<js::Shape*>, JS::MutableHandle<JS::Value>)
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:631
  27:        0x10647c677 - js::GetProperty(JSContext*, JS::Handle<JS::Value>, JS::Handle<js::PropertyName*>, JS::MutableHandle<JS::Value>)
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/NativeObject.cpp:1785
  28:        0x10646e227 - Interpret(JSContext*, js::RunState&)
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:189
  29:        0x106467583 - js::RunScript(JSContext*, js::RunState&)
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  30:        0x106478d92 - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:471
  31:        0x1064790c5 - js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>)
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:517
  32:        0x1063aaa28 - js::fun_apply(JSContext*, unsigned int, JS::Value*)
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:1325
  33:        0x106478c74 - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  34:        0x10611c3b5 - js::jit::DoCallFallback(JSContext*, js::jit::BaselineFrame*, js::jit::ICCall_Fallback*, unsigned int, JS::Value*, JS::MutableHandle<JS::Value>)
                        at /Users/jdm/src/master-servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jit/BaselineIC.cpp:5970
```

**Comment by nox** [comment] 2017-10-07 10:28
I can still reproduce this.

**Comment by dralley** [comment] 2020-03-25 17:07
I can't reproduce this on Tumblr anymore, but this is a very common traceback with several websites, like ArsTechnica.

Since it's filed elsewhere though, and not reproducable with Tumblr, I recommend closing this issue.

**Closed** 2020-03-25 17:28 UTC
Labels: A-layout/inline, C-reproduced, I-panic
