### ISSUE TITLE
Copy and paste does not work correctly on WIndows 10

### ISSUE THREAD

**Issue by CodeGradox** [servo/servo#16459] opened 2017-04-14 16:44 UTC
When I copy a url or text in Windows and paste it into the omibar in Servo, it pastes an empty box character instead of the text. It does the same on any website I visit where I can paste text.

![servo url](https://cloud.githubusercontent.com/assets/8555819/25049418/0493d8b6-2142-11e7-8fb7-219781a03144.png)

**Comment by CodeGradox** [comment] 2017-04-15 18:02
Looks like pressing CTRL + almost any key on the keyboard inserts either that box, space or what seems to be a tab.

**Comment by atouchet** [comment] 2017-06-02 02:40
I tested this out today with #17067 being merged now and I seem to be getting some strange results. If I copy and paste a URL within Servo it pastes the URL twice (ex. copying https://duckduckgo.com/html pastes as https://duckduckgo.com/htmlhttps://duckduckgo.com/html). Also if I try to paste into another application other than Servo nothing shows up. Strangely I can paste into another application just fine but only after closing the Servo browser window. Servo appears to be doing something to interfere with the Windows clipboard. I can't even copy and paste from completely different applications with Servo running now. For example I can't copy text from Firefox to paste into Notepad unless Servo is not running.

**Comment by est31** [comment] 2017-06-02 06:51
cc @DoumanAsh seems your crate is being used on windows?
cc @aweinstock314

**Comment by DoumanAsh** [comment] 2017-06-02 08:49
@est31 Yes.

Just to try it out myself @CodeGradox could please paste your `url/text`
From what Igather there seems to be strange handling of URL... I'll make a quick test.
But what about text?

For now i made simple test https://github.com/DoumanAsh/clipboard-win/commit/3dd2519d783e7147ce2b25ab3923cfc06d665be6 but it works as expected.

I need to take a look at how servo set & paste to/from clipboard.

**Comment by est31** [comment] 2017-06-03 04:14
> clipboard library uses this context and therefore servo now(contrary to older clipboard) has it open during life of program.
> But in most cases it might be better to actually open/close it only during operations.

Interesting, this might be in fact the cause. I'm not sure whether this behaviour is the right one on Linux/Mac, is there a cost in creating a clipboard context on those operating systems?

**Comment by DoumanAsh** [comment] 2017-06-03 05:23
In Windows case you only need to call two WinAPI function corresponding to opening clipboard, and then closing it on dropping context.

In case of Mac you would need to initialize interface toward clipboard server each time.
I'm not aware of implementation details there, but most likely it is sorta process-communication establishment within a system.
A bit more costly than Windows, i guess, but I don't think it is critical

But in case of X11 though you need to do some initialization with spawning thread https://github.com/quininer/x11-clipboard/blob/master/src/lib.rs#L109-L125

**Comment by est31** [comment] 2017-06-05 21:06
Okay, I've filed an issue report against the `rust-clipboard` crate. Its better fixed there, as to not confuse other users.

**Comment by atouchet** [comment] 2017-06-11 15:35
Just realized that this also impacts print screen which makes it so now I can't take screenshots of Servo.

**Comment by DoumanAsh** [comment] 2017-06-11 16:44
@atouchet Hmm... i think it should not. Servo uses only unicode text format when accessing clipboard so it should break only copying\pasting text

**Comment by atouchet** [comment] 2017-06-11 16:53
@DoumanAsh well it doesn't appear to be working now and I know that it did work in the past. I am assuming that #17067 started the problem but I have not verified that.

**Comment by DoumanAsh** [comment] 2017-06-11 17:06
@atouchet Well, I suppose stopping leaving clipboard open on windows will prevent any cod of conflicts so you should wait for that to be resolved first.

**Comment by est31** [comment] 2017-06-19 22:33
I've filed #17413 to fix all clipboard issues on windows. I couldn't test it. If any of you can build servo, could you test it? Replies please in the PR thread.

**Closed** 2017-06-20 02:26 UTC
Labels: A-input, P-windows

**Comment by atouchet** [comment] 2017-06-21 02:37
I tested this out and now I am able to copy and paste URLs into Servo again. However I am still getting that duplicate URL issue I mentioned in my original post. If I try to load the duplicate URL site Servo seems to still work regardless. I am not sure what is happening there.

I also tied copying text from https://www.rust-lang.org/en-US/ and pasting it into the Servo address bar which resulted in empty boxes.

**Comment by DoumanAsh** [comment] 2017-06-21 03:36
@atouchet Do you by any chance has logs from servo? It is rather strange i would say.

**Comment by atouchet** [comment] 2017-06-21 04:54
@DoumanAsh Sorry, I don't have any logs.

**Comment by DoumanAsh** [comment] 2017-06-21 09:01
np, I'll try to build servo myself and see if there is any issue with my clipboard library or something else.
