### ISSUE TITLE
Panic: unknown completed load Stylesheet("https://0.gravatar.com/css/hovercard.css?ver=201627y")

### ISSUE THREAD

**Issue by sankha93** [servo/servo#12259] opened 2016-07-05 10:38 UTC
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }
### URL:
https://thelimbeck.wordpress.com/
### Backtrace:
```
frame #0  - 0x00000001033526ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000000103352651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000000101bbfca4 - _<F as alloc..boxed..FnBox<A>>::call_box::haeff945be1a63d60
frame #3  - 0x00000001032c6947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010353a844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000000103553786 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x000000010353be88 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x00000001035533df - rust_begin_unwind
frame #8  - 0x000000010357a260 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x0000000101bb138e - core::result::unwrap_failed::hf40cb93f6f31ec3d
frame #10 - 0x0000000101c2ee0f - layout_thread::LayoutThread::exit_now::h9c02213ba81aad74
frame #11 - 0x0000000101c123a3 - layout_thread::LayoutThread::handle_request_helper::h1029bbb7e9e50e59
frame #12 - 0x0000000101bfdf1a - layout_thread::LayoutThread::handle_request::ha13841b9d3ecdc81
frame #13 - 0x0000000101bbdb1a - std::panicking::try::call::h401e4a3a7768c3f1
frame #14 - 0x000000010355646b - __rust_try
frame #15 - 0x0000000103556405 - __rust_maybe_catch_panic
frame #16 - 0x0000000101bbee84 - _<F as alloc..boxed..FnBox<A>>::call_box::h8169792cb3dac906
frame #17 - 0x0000000103551ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #18 - 0x00007fff96ed799c - _pthread_body
frame #19 - 0x00007fff96ed7919 - _pthread_start

```

**Comment by sankha93** [comment] 2016-07-05 10:39
This is probably same as #12207. Can someone confirm and close?

**Comment by Manishearth** [comment] 2016-07-05 10:50
MPSC send failed is a generic error that happens after another crash.

Could you run this site under servo directly and paste the full backtrace? I'm unable to repro, perhaps you took some specific steps?

**Comment by Manishearth** [comment] 2016-07-05 11:00
```
ERROR:constellation::constellation: Panic: unknown completed load Stylesheet("https://0.gravatar.com/css/hovercard.css?ver=201627y")
ERROR:constellation::constellation: Backtrace:
frame #0  - 0x000000010415416e - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x00000001041540f1 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x00000001036dc9c6 - _<F as alloc..boxed..FnBox<A>>::call_box::h0565244278d4d59f
frame #3  - 0x0000000104139a17 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h29a42322e413d07a
frame #4  - 0x000000010434a8d4 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000000104363706 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x000000010434bf18 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x000000010436335f - rust_begin_unwind
frame #8  - 0x000000010438a1e0 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x0000000104391c55 - core::option::expect_failed::hdb92832549f56a85
frame #10 - 0x00000001030bd961 - script::document_loader::DocumentLoader::finish_load::haa6a0f6e4f21d44f
frame #11 - 0x00000001030bb601 - script::dom::document::Document::finish_load::h79108e5f80785f26
frame #12 - 0x000000010358fb7f - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h7c12431fee02d203
frame #13 - 0x000000010358e100 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::hb602846cf931084d
frame #14 - 0x00000001036e8051 - script::script_thread::ScriptThread::handle_msg_from_script::h2f0105d83ca8cb85
frame #15 - 0x00000001037413e1 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h2ac27e1c54666fa2
frame #16 - 0x00000001037275a1 - script::script_thread::ScriptThread::handle_msgs::h0c19ebba797b4a30
frame #17 - 0x00000001036db247 - std::panicking::try::call::h10cfb0624f256250
frame #18 - 0x00000001043663eb - __rust_try
frame #19 - 0x0000000104366385 - __rust_maybe_catch_panic
frame #20 - 0x00000001036dc3f4 - _<F as alloc..boxed..FnBox<A>>::call_box::h7f5edb200c5081b6
frame #21 - 0x0000000104361e68 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #22 - 0x00007fff8def6c12 - _pthread_body
frame #23 - 0x00007fff8def6b8f - _pthread_start
```
is what I get after poking at it

**Comment by Manishearth** [comment] 2016-07-05 11:00
YOu have to click on the hamburger menu for this to happen

**Comment by jdm** [comment] 2016-07-05 13:55
Closing as a duplicate of #12075. Thanks for reporting it!

**Closed by jdm** 2016-07-05 13:55 UTC
Labels: C-reproduced, I-panic
