### ISSUE TITLE
Weird font choice for bold text on servo.org

### ISSUE THREAD

**Issue by jdm** [servo/servo#20242] opened 2018-03-08 14:31 UTC
This is what I see on my local build on macOS:
<img width="765" alt="screen shot 2018-03-08 at 9 31 38 am" src="https://user-images.githubusercontent.com/27658/37156248-8b39934c-22b3-11e8-8c33-33bc4f7881c7.png">
Firefox:
<img width="748" alt="screen shot 2018-03-08 at 9 31 44 am" src="https://user-images.githubusercontent.com/27658/37156250-8e2bffb8-22b3-11e8-9a40-4f957f17cc69.png">

**Comment by atouchet** [comment] 2018-03-08 21:35
![servo.org](https://i.imgur.com/BHqE38t.png)

I am not able to reproduce this issue in the latest Windows nightly build.

**Comment by Zirro** [comment] 2018-03-09 13:09
Can verify this with the latest nightly build on macOS 10.13.

**Comment by atouchet** [comment] 2020-05-08 03:41
Is this still an issue?

**Comment by jdm** [comment] 2020-05-08 15:54
Now Servo doesn't show the bold for the text at all:
<img width="746" alt="Screen Shot 2020-05-08 at 11 53 56 AM" src="https://user-images.githubusercontent.com/27658/81423559-9dc3ec80-9122-11ea-86b8-f483e589a5e9.png">

**Comment by atouchet** [comment] 2020-05-08 16:10
Hmm. Maybe that is the same issue as #24554?

**Comment by nicoabie** [comment] 2020-07-29 02:20
It doesn't seem to render the `<b></b>` tag properly

**Comment by mrobinson** [comment] 2024-04-21 14:24
After a small trip to the Wayback Machine I've confirmed that this is a duplicate of #24554 and should be fixed soon.

**Closed by mrobinson** 2024-04-21 14:24 UTC
Labels: A-platform/fonts, P-mac, C-reproduced
