### ISSUE TITLE
Unable to open pdf file.

### ISSUE THREAD

**Issue by YuvrajSinghGitbub** [servo/servo#32713] opened 2024-07-06 12:21 UTC
**The bug:**
Unknown file type (application/pdf). 

**To Reproduce:**
Build from source with `./mach build --release` and opening the file as: `/target/release/serve "path/to/file.pdf`. 

**Platform:**
Manjaro linux (installed deps by following the [build guide](https://github.com/servo/servo/wiki/Building#manual-build-setup)

**Comment by sagudev** [comment] 2024-07-06 13:18
Servo is not able to run pdf.js (pdf viewer writen in javascript that is used in firefox), but when we are able to, this should be easy enough.

**Comment by mrobinson** [comment] 2024-07-06 13:27
Closing as a duplicate of #6098.

**Closed** 2024-07-06 13:27 UTC
Labels: C-untriaged
