### ISSUE TITLE
Correctly set the line offset of inline scripts

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#12744] opened 2016-08-05 12:41 UTC
We currently [set the offset of a script as 0 when its loaded inline](https://github.com/servo/servo/blob/0fc0db67c64bf8ab4593d1f84b8d1be517fa1b74/components/script/dom/window.rs#L949).

This means that if an inline script errors, the line number is given relative to the start of the script, not the start of the html file it's in. This is less useful 😄 

To fix this, we'll probably need to hook into the parser somehow, not sure. There doesn't seem to be any line number data stored in Servo directly.

(Perhaps have create_element take the line number?)

**Comment by jdm** [comment] 2016-08-05 12:53
Duplicate of #11519.

**Closed by jdm** 2016-08-05 12:53 UTC
Labels: A-content/parsers, A-content/script
