### ISSUE TITLE
Panic scrolling around on nytimes.com

### ISSUE THREAD

**Issue by dzbarsky** [servo/servo#10370] opened 2016-04-02 18:07 UTC
```
thread '<unnamed>' panicked at 'index 440 out of range for slice of length 224', ../src/libcore/slice.rs:527
stack backtrace:
   1:        0x1098b8188 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x1098bbd79 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x1098bb9a8 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x1098a6d76 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x1098a7dae - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x1098b7527 - rust_begin_unwind
   7:        0x1098e1960 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x1098e1be1 - slice::slice_index_len_fail::h4697db0943bde2d0iFP
   9:        0x10983ce50 - display_list::BuiltDisplayList::display_list_items::hf8f6508e1771b39aeZf
  10:        0x1097ff00d - scene::Scene::add_display_list::ha7841ffdb1f44bd96hq
  11:        0x1097b0643 - render_backend::RenderBackend::run::haf5bdaa2d8e7fc50xgp
  12:        0x10980bc8c - sys_common::unwind::try::try_fn::h11869116844602375276
  13:        0x1098b74bb - __rust_try
  14:        0x1098b7443 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  15:        0x10980c0da - boxed::F.FnBox<A>::call_box::h16472621618194350535
  16:        0x1098bae5c - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  17:     0x7fff8d430c12 - _pthread_body
  18:     0x7fff8d430b8f - _pthread_start
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x1098b8188 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x1098bbd79 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x1098bb9a8 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x1098a6d76 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x1098a7dae - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x1098b7527 - rust_begin_unwind
   7:        0x1098e1960 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10981d149 - result::unwrap_failed::h14555228155184734041
   thread '9: LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) } ' panicked at ' called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) } ',  ../src/libcore/result.rs : 746 
0x109832056 - api::RenderApi::tick_scrolling_bounce_animations::h65c1a4a8ed906a7eMVb
  10:        0x107e901b8 - compositor::IOCompositor<Window>::composite_specific_target::h4442080814029799969
  11:        0x107e95d61 - compositor::IOCompositor<Window>::composite::h15833295744085712697
  12:        0x107e662dc - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h5911158479959326858
  13:        0x107e9c3f7 - Browser::handle_events::h16f2ea9e5758c56etea
  14:        0x107e508f5 - main::h9cc0aa5bb4f2f2aeqaa
  15:        0x1098bb5b2 - sys_common::unwind::try::try_fn::h13791246699442426615
  16:        0x1098b74bb - __rust_try
  17:        0x1098bb470 - rt::lang_start::h32ace63a1577ce666rz
stack backtrace:
   1:        0x1098b8188 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x1098bbd79 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x1098bb9a8 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x1098a6d76 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x1098a7dae - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x1098b7527 - rust_begin_unwind
   7:        0x1098e1960 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10981d149 - result::unwrap_failed::h14555228155184734041
   9:        0x109831dd7 - api::RenderApi::set_root_stacking_context::h4786830c327da6c8ATb
  10:        0x1080ac232 - layout_thread::LayoutThread::perform_post_main_layout_passes::h9f37390802dd376bQ6r
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
  11:        0x10804ebab - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::h9245e56ec06bd101b3r
  12:        0x1080541d1 - layout_thread::LayoutThread::handle_reflow::h265b6e63f7f2c9a8uHr
  13:        0x108035c02 - layout_thread::LayoutThread::handle_request_helper::h8ada66946b861b672jr
  14:        0x10801c0ca - layout_thread::LayoutThread::handle_request::hcc9862cdad29e05d5dr
  15:        0x107fd052a - sys_common::unwind::try::try_fn::h15941389321738050812
  16:        0x1098b74bb - __rust_try
  17:        0x1098b7443 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  18:        0x107fd11a1 - boxed::F.FnBox<A>::call_box::h4884624359537591615
  19:        0x1098bae5c - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  20:     0x7fff8d430c12 - _pthread_body
  21:     0x7fff8d430b8f - _pthread_start
stack backtrace:
   1:        0x1098b8188 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x1098bbd79 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:thread '746LayoutWorker worker 1/6
' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', thread '../src/libcore/result.rsLayoutWorker worker 3/6:' panicked at '746called `Result::unwrap()` on an `Err` value: RecvError', 
../src/libcore/result.rs:746
thread 'LayoutWorker worker 4/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread '', LayoutWorker worker 5/6../src/libcore/result.rs' panicked at ':called `Result::unwrap()` on an `Err` value: RecvError746', 
../src/libcore/result.rs:746
thread 'LayoutWorker worker 6/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
   3:        0x1098bb9a8 - panicking::default_handler::h1183b2a11c8682560zz
thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
thread '  PaintThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) } ' panicked at '4called `Result::unwrap()` on an `Err` value: "SendError(..)": ',  ../src/libcore/result.rs : 746 
   0x1098a6d76 - sys_common::unwind::begin_unwind_inner::thread 'h1f97bc9e4cfe0396LZtPaintThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }
' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', thread '../src/libcore/result.rsConstellation:' panicked at '746unable to find pipeline - this is a bug
', ../src/libcore/option.rs:704
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
   5:        0x1098a7dae - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x1098b7527 - rust_begin_unwind
   7:        0x1098e1960 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10897ab87 - result::unwrap_failed::h16703076112224150602
Servo exited with return value 101
```

**Comment by emilio** [comment] 2016-04-02 18:09
Dupe of https://github.com/servo/servo/issues/10256

**Closed by emilio** 2016-04-02 18:09 UTC
