### ISSUE TITLE
Images with padding and border-radius are not cropped correctly

### ISSUE THREAD

**Issue by ocerman** [servo/servo#22818] opened 2019-02-03 15:43 UTC
![servo-img-crop](https://user-images.githubusercontent.com/10187350/52178776-af596e80-27d2-11e9-9da2-84b29bee48fa.jpg)
```
<!DOCTYPE html>
<html>
	<head>
		<style>
			img{
				padding: 10px;
				height: 200px;
				border-radius: 50%;
			}
			.b{
				background: #BADA55;
			}
		</style>
	</head>
	<body>
		<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Hrad%C4%8Dansk%C3%A1%2C_Tatra_T3.jpg/320px-Hrad%C4%8Dansk%C3%A1%2C_Tatra_T3.jpg" alt="S">
		<img class="b" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Hrad%C4%8Dansk%C3%A1%2C_Tatra_T3.jpg/320px-Hrad%C4%8Dansk%C3%A1%2C_Tatra_T3.jpg" alt="S">
	</body>
</html>
```

**Comment by jdm** [comment] 2020-04-14 14:50
Looks like a duplicate of #20922, which has more information.

**Closed by jdm** 2020-04-14 14:50 UTC
Labels: A-layout/uncategorized, C-has-manual-testcase
