### ISSUE TITLE
Assertion failure setting parser-blocking pending script

### ISSUE THREAD

**Issue by zopyx** [servo/servo#12116] opened 2016-07-01 19:11 UTC
called `Result::unwrap()` on an `Err` value: "SendError(..)"
### URL:

https://www.zopyx.com/
### Backtrace:

```
frame #0  - 0x000000010cf716ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x000000010cf71651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000000010c242086 - _<F as alloc..boxed..FnBox<A>>::call_box::h6059122298f825d8
frame #3  - 0x000000010cee5947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010d159844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000000010d172786 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x000000010d15ae88 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x000000010d1723df - rust_begin_unwind
frame #8  - 0x000000010d199260 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x000000010c0162f7 - core::result::unwrap_failed::h84d3c1f4e17e69e8
frame #10 - 0x000000010c20a085 - script::dom::window::Window::force_reflow::h1ecf246a1ab42a21
frame #11 - 0x000000010c017f89 - script::dom::window::Window::reflow::hef7e4c464833fd4d
frame #12 - 0x000000010c1b060f - script::script_thread::ScriptThread::parsing_complete::hfbfbd73335d7be14
frame #13 - 0x000000010c169335 - script::dom::servohtmlparser::ServoHTMLParser::parse_sync::h3d357a0bc0edb824
frame #14 - 0x000000010c1688ff - _<script..dom..servohtmlparser..ParserContext as net_traits..AsyncResponseListener>::response_complete::h988a4ff62e7f3b10
frame #15 - 0x000000010c2d3d15 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::ha2200b1de782800b
frame #16 - 0x000000010c24d95c - script::script_thread::ScriptThread::handle_msg_from_script::hd1f5e7b2423a8c64
frame #17 - 0x000000010c2a9a71 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc67d8b381c013b79
frame #18 - 0x000000010c28f73f - script::script_thread::ScriptThread::handle_msgs::h236c5be60a207bea
frame #19 - 0x000000010c240907 - std::panicking::try::call::h645a328f039d97c6
frame #20 - 0x000000010d17546b - __rust_try
frame #21 - 0x000000010d175405 - __rust_maybe_catch_panic
frame #22 - 0x000000010c241ab4 - _<F as alloc..boxed..FnBox<A>>::call_box::h3db95636eb747818
frame #23 - 0x000000010d170ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #24 - 0x00007fff93a0b99c - _pthread_body
frame #25 - 0x00007fff93a0b919 - _pthread_start

```

**Comment by jdm** [comment] 2016-07-02 22:07
```
(lldb) p msg
(&str) $0 = "assertion failed: self.get_pending_parsing_blocking_script().is_none() || script.is_none()"
(lldb) bt
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
* thread #33: tid = 0xf562, 0x00000001041950a0 servo`rust_panic, stop reason = breakpoint 1.1
  * frame #0: 0x00000001041950a0 servo`rust_panic
    frame #1: 0x000000010418ac3d servo`std::panicking::rust_panic_with_hook::h983af77c1a2e581b + 413
    frame #2: 0x000000010101a678 servo`std::panicking::begin_panic<&str>(msg=&str at 0x0000000121e0eea0, file_line=0x0000000105520ad0) + 120 at panicking.rs:328
    frame #3: 0x00000001020860c5 servo`script::dom::document::{{impl}}::set_pending_parsing_blocking_script(self=0x000000012205f000, script=Option<&script::dom::htmlscriptelement::HTMLScriptElement> at 0x0000000121e0ef40) + 213 at <std macros>:3
    frame #4: 0x000000010223dc55 servo`script::dom::htmlscriptelement::{{impl}}::prepare(self=0x000000012a383500) + 8133 at htmlscriptelement.rs:340
    frame #5: 0x0000000102313ed8 servo`script::parse::html::{{impl}}::complete_script(self=0x0000000122041338, node=JS<script::dom::node::Node> at 0x0000000121e10398) + 72 at html.rs:159
    frame #6: 0x00000001022f8519 servo`html5ever::tree_builder::rules::{{impl}}::step<script::dom::bindings::js::JS<script::dom::node::Node>,script::dom::servohtmlparser::Sink>(self=0x0000000122041330, mode=Text, token=Token at 0x0000000121e16eb8) + 55529 at rules.expanded.rs:1461
    frame #7: 0x00000001022de555 servo`html5ever::tree_builder::{{impl}}::process_to_completion<script::dom::bindings::js::JS<script::dom::node::Node>,script::dom::servohtmlparser::Sink>(self=0x0000000122041330, token=Token at 0x0000000121e176c0) + 613 at mod.rs:320
    frame #8: 0x00000001022d9efd servo`html5ever::tree_builder::{{impl}}::process_token<script::dom::bindings::js::JS<script::dom::node::Node>,script::dom::servohtmlparser::Sink>(self=0x0000000122041330, token=Token at 0x0000000121e17b70) + 3405 at mod.rs:418
    frame #9: 0x00000001022d90ce servo`html5ever::tokenizer::{{impl}}::process_token<html5ever::tree_builder::TreeBuilder<script::dom::bindings::js::JS<script::dom::node::Node>, script::dom::servohtmlparser::Sink>>(self=0x0000000122041310, token=Token at 0x0000000121e17cd0) + 654 at mod.rs:233
    frame #10: 0x000000010232768a servo`html5ever::tokenizer::{{impl}}::emit_current_tag<html5ever::tree_builder::TreeBuilder<script::dom::bindings::js::JS<script::dom::node::Node>, script::dom::servohtmlparser::Sink>>(self=0x0000000122041310) + 1162 at mod.rs:392
    frame #11: 0x000000010231eaeb servo`html5ever::tokenizer::{{impl}}::step<html5ever::tree_builder::TreeBuilder<script::dom::bindings::js::JS<script::dom::node::Node>, script::dom::servohtmlparser::Sink>>(self=0x0000000122041310) + 15867 at mod.rs:795
    frame #12: 0x000000010231acd4 servo`html5ever::tokenizer::{{impl}}::run<html5ever::tree_builder::TreeBuilder<script::dom::bindings::js::JS<script::dom::node::Node>, script::dom::servohtmlparser::Sink>>(self=0x0000000122041310) + 628 at mod.rs:334
    frame #13: 0x000000010233bcf5 servo`script::dom::servohtmlparser::{{impl}}::do_parse_sync(self=0x0000000122041300) + 597 at servohtmlparser.rs:342
    frame #14: 0x000000010233ba98 servo`script::dom::servohtmlparser::{{impl}}::parse_sync::{{closure}} + 40 at servohtmlparser.rs:329
    frame #15: 0x000000010233b980 servo`profile_traits::time::profile<(category=ScriptParseHTML, meta=Option<profile_traits::time::TimerMetadata> at 0x0000000121e19c88, profiler_chan=ProfilerChan at 0x0000000121e19c80, callback=closure at 0x0000000121e19c70),closure> + 176 at time.rs:108
    frame #16: 0x00000001022d4407 servo`script::dom::servohtmlparser::{{impl}}::parse_sync(self=0x0000000122041300) + 423 at servohtmlparser.rs:326
    frame #17: 0x000000010233c4fb servo`script::dom::servohtmlparser::{{impl}}::resume(self=0x0000000122041300) + 123 at servohtmlparser.rs:372
    frame #18: 0x000000010208a975 servo`script::parse::{{impl}}::resume(self=0x0000000121e1a310) + 69 at mod.rs:123
    frame #19: 0x0000000101095ea1 servo`script::dom::document::{{impl}}::finish_load(self=0x000000012205f000, load=LoadType at 0x0000000121e1a3c0) + 753 at document.rs:1377
    frame #20: 0x000000010223ab75 servo`script::dom::htmlscriptelement::{{impl}}::response_complete(self=0x00000001278ef818, status=Result<(), net_traits::NetworkError> at 0x0000000121e1a9b0) + 949 at htmlscriptelement.rs:177
    frame #21: 0x000000010224249e servo`net_traits::{{impl}}::process<script::dom::htmlscriptelement::ScriptContext>(self=ResponseAction at 0x0000000121e1acb8, listener=0x00000001278ef818) + 494 at lib.rs:268
    frame #22: 0x00000001022419cb servo`script::network_listener::{{impl}}::handler<net_traits::ResponseAction,script::dom::htmlscriptelement::ScriptContext>(self=0x000000011711f600) + 459 at network_listener.rs:64
    frame #23: 0x0000000102504e8d servo`script::script_thread::{{impl}}::handle_msg_from_script(self=0x0000000121e1eeb0, msg=MainThreadScriptMsg at 0x0000000121e1b428) + 1437 at script_thread.rs:977
    frame #24: 0x000000010259c189 servo`script::script_thread::{{impl}}::handle_msgs::{{closure}} + 409 at script_thread.rs:803
    frame #25: 0x000000010259bcf6 servo`script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>(self=0x0000000121e1eeb0, category=NetworkEvent, f=closure at 0x0000000121e1bdd0) + 1062 at script_thread.rs:899
    frame #26: 0x0000000102569c0e servo`script::script_thread::{{impl}}::handle_msgs(self=0x0000000121e1eeb0) + 7998 at script_thread.rs:795
    frame #27: 0x00000001025025dd servo`script::script_thread::{{impl}}::start(self=0x0000000121e1eeb0) + 29 at script_thread.rs:642
    frame #28: 0x000000010250258c servo`script::script_thread::{{impl}}::create::{{closure}}::{{closure}} + 44 at script_thread.rs:480
    frame #29: 0x00000001025022e2 servo`profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(self=0x0000000121e1f130, f=closure at 0x0000000121e1e8f0, reporter_name=String at 0x0000000121e1e8d0, channel_for_reporter=Sender<script::script_thread::MainThreadScriptMsg> at 0x0000000121e1e8b8, msg=0x0000000000000020) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>> + 690 at mem.rs:59
    frame #30: 0x00000001024ee597 servo`script::script_thread::{{impl}}::create::{{closure}} + 1687 at script_thread.rs:479
    frame #31: 0x00000001024ecc2f servo`util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::hafaaf6f2b930c219 + 495 at boxed.rs:234
    frame #32: 0x00000001024ec9e8 servo`std::panic::{{impl}}::call_once<(self=AssertUnwindSafe<closure> at 0x0000000121e1f708, _args=<unavailable>),closure> + 136 at panic.rs:251
    frame #33: 0x00000001024ec93c servo`std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hddf731400829dee4 + 92
    frame #34: 0x00000001024ed1f5 servo`std::panicking::try::call<closure>(f=0x0000000121e1fe98) + 21 at panicking.rs:272
    frame #35: 0x00000001041a69cc servo`__rust_try + 12
    frame #36: 0x00000001041a6966 servo`__rust_maybe_catch_panic + 38
    frame #37: 0x00000001024ec88e servo`std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::h5d2f32fd37c74af5 + 158
    frame #38: 0x00000001024ec7e0 servo`std::thread::local::{{impl}}::with<core::cell::Cell<usize>,closure,core::result::Result<(self=0x000000010570d830, f=closure at 0x0000000121e1ff38), Box<Any>>> + 208 at local.rs:211
    frame #39: 0x00000001024ec610 servo`std::panicking::try<(f=AssertUnwindSafe<closure> at 0x0000000121e20218),std::panic::AssertUnwindSafe<closure>> + 192 at panicking.rs:235
    frame #40: 0x00000001024ec4ef servo`std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,(f=AssertUnwindSafe<closure> at 0x0000000121e206b8)> + 143 at panic.rs:307
    frame #41: 0x00000001024ec34d servo`std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hfdd025b8c87df1d7 + 349
    frame #42: 0x00000001024ed3f8 servo`alloc::boxed::{{impl}}::call_box<(self=0x000000011de56000, args=<unavailable>),closure> + 104 at boxed.rs:544
    frame #43: 0x00000001041a2449 servo`std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46 + 57
    frame #44: 0x00007fff96855899 libsystem_pthread.dylib`_pthread_body + 138
    frame #45: 0x00007fff9685572a libsystem_pthread.dylib`_pthread_start + 137
    frame #46: 0x00007fff96859fc9 libsystem_pthread.dylib`thread_start + 13
```

**Comment by jdm** [comment] 2016-07-02 22:08
Looks like a likely duplicate of #11733.

**Comment by sviter** [comment] 2017-08-03 13:17
No crash for me on latest servo

**Closed** 2017-08-03 13:29 UTC
Labels: A-content/dom, A-webcompat, C-reproduced, I-panic
