### ISSUE TITLE
loading error google.com

### ISSUE THREAD

**Issue by komawoyo** [servo/servo#16400] opened 2017-04-13 04:58 UTC
latest nightly servo - windows 8.1x64

www.google.com

![image](https://cloud.githubusercontent.com/assets/18315233/24990779/f0e5488e-1fdb-11e7-81ee-179f6d4dad87.png)

**Comment by jdm** [comment] 2017-04-13 06:05
Which country page loads for you when you visit that page in other browsers?

**Comment by jdm** [comment] 2017-04-13 06:14
This looks like it might be an intermittent problem:
```
called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }, at src/libcore/result.rs:859)
stack backtrace:
   0:        0x10cef9721 - backtrace::backtrace::trace::h72c38896da0ad543
   1:        0x10cef1bd3 - backtrace::capture::Backtrace::new::h1ee17dbbfc5d7f69
   2:        0x10c582eef - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::hf283c5b07d6486e3
   3:        0x111daf459 - std::panicking::rust_panic_with_hook::h05996066754c6be9
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:550
   4:        0x111daf304 - std::panicking::begin_panic<collections::string::String>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:511
   5:        0x111daf222 - std::panicking::begin_panic_fmt::he5aad713258a67c3
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:495
   6:        0x111daf187 - rust_begin_unwind
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:471
   7:        0x111dd7660 - core::panicking::panic_fmt::he26d734b771c5b2c
                        at /Users/travis/build/rust-lang/rust/src/libcore/panicking.rs:69
   8:        0x10ef20335 - core::result::unwrap_failed::h7e90e841bf9e1ecd
   9:        0x10ee5b7dd - _$LT$core..result..Result$LT$T$C$$u20$E$GT$$GT$::unwrap::hc46097ab7839f43b
  10:        0x10f0eafb4 - script::dom::document::Document::set_quirks_mode::h43250e4ca1b67567
  11:        0x10fd4b327 - _$LT$script..dom..servoparser..html..Sink$u20$as$u20$html5ever..tree_builder..interface..TreeSink$GT$::set_quirks_mode::hfc1b5e661966b67d
  12:        0x10ed8eec9 - _$LT$html5ever..tree_builder..TreeBuilder$LT$Handle$C$$u20$Sink$GT$$u20$as$u20$html5ever..tree_builder..actions..TreeBuilderActions$LT$Handle$GT$$GT$::set_quirks_mode::h42a810d6eaf0ab80
  13:        0x10ed7089c - _$LT$html5ever..tree_builder..TreeBuilder$LT$Handle$C$$u20$Sink$GT$$u20$as$u20$html5ever..tree_builder..rules..TreeBuilderStep$LT$Handle$GT$$GT$::step::h9d9912711910c0b8
  14:        0x10efcd038 - _$LT$html5ever..tree_builder..TreeBuilder$LT$Handle$C$$u20$Sink$GT$$GT$::process_to_completion::h543c7ca3bcf4b8fd
  15:        0x10ed60241 - _$LT$html5ever..tree_builder..TreeBuilder$LT$Handle$C$$u20$Sink$GT$$u20$as$u20$html5ever..tokenizer..interface..TokenSink$GT$::process_token::hd73b56da5305de62
  16:        0x10fa582e5 - _$LT$html5ever..tokenizer..Tokenizer$LT$Sink$GT$$GT$::process_token::hd17b71ab2108e907
  17:        0x10fa5aa00 - _$LT$html5ever..tokenizer..Tokenizer$LT$Sink$GT$$GT$::process_token_and_continue::hadfcd160300699f6
  18:        0x10fa63ae3 - _$LT$html5ever..tokenizer..Tokenizer$LT$Sink$GT$$GT$::emit_eof::he4d274c2571b672d
  19:        0x10fa63d34 - _$LT$html5ever..tokenizer..Tokenizer$LT$Sink$GT$$GT$::eof_step::h5bdee53bad88f4ec
  20:        0x10fa5ae81 - _$LT$html5ever..tokenizer..Tokenizer$LT$Sink$GT$$GT$::end::hd22ddd7d215ceae1
  21:        0x10fd49ccc - script::dom::servoparser::html::Tokenizer::end::ha19cb57b74150f6f
  22:        0x10e8f7842 - script::dom::servoparser::Tokenizer::end::h880c54e75d406040
  23:        0x10e8f7461 - script::dom::servoparser::ServoParser::finish::hbbb556c7190dee9c
  24:        0x10e8f6911 - script::dom::servoparser::ServoParser::do_parse_sync::h23a0ceac11aeabaf
  25:        0x10fd4ecd7 - script::dom::servoparser::ServoParser::parse_sync::_$u7b$$u7b$closure$u7d$$u7d$::hb0c54fee4c9fc4a5
  26:        0x10f3d7aac - profile_traits::time::profile::hd7bc1d29a312de17
  27:        0x10e8f670b - script::dom::servoparser::ServoParser::parse_sync::ha9fbe14c59c9c531
  28:        0x10e8fa60d - _$LT$script..dom..servoparser..ParserContext$u20$as$u20$net_traits..FetchResponseListener$GT$::process_response_eof::h4a7a7f57fbb5d25e
  29:        0x10efdadfd - _$LT$net_traits..FetchResponseMsg$u20$as$u20$net_traits..Action$LT$T$GT$$GT$::process::hc64cc6ab5bdfd811
  30:        0x10f1b31b1 - _$LT$script..network_listener..ListenerRunnable$LT$A$C$$u20$Listener$GT$$u20$as$u20$script..script_thread..Runnable$GT$::handler::h8aeb188d03c69ad3
  31:        0x10fd8a61f - script::script_thread::ScriptThread::handle_msg_from_script::ha175edeacd453a3a
  32:        0x10fd8710a - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::he7045b0b86200afd
  33:        0x10fd888e1 - script::script_thread::ScriptThread::profile_event::hd47d9b28cdd5f18c
  34:        0x10fd85970 - script::script_thread::ScriptThread::handle_msgs::h421477220785cb44
  35:        0x10fd84065 - script::script_thread::ScriptThread::start::hd64e366ea4b27f65
  36:        0x10f1b7aa4 - _$LT$script..script_thread..ScriptThread$u20$as$u20$script_traits..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h3a093c291e6ddbae
  37:        0x10ed9a8a7 - profile_traits::mem::ProfilerChan::run_with_memory_reporting::hba40730671f4cd81
  38:        0x10e920de1 - _$LT$script..script_thread..ScriptThread$u20$as$u20$script_traits..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::h1e00ff7f78964ddb
  39:        0x10e849f4a - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h8b7e37e62320c5b0
  40:        0x10e28008d - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:454
  41:        0x111db04ba - __rust_maybe_catch_panic
                        at /Users/travis/build/rust-lang/rust/src/libpanic_unwind/lib.rs:98
  42:        0x10e240d73 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:433
  43:        0x10e639b84 - std::panic::catch_unwind::hf40fae72dc5f8d19
  44:        0x10e0aac68 - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:360
  45:        0x10e4712d2 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:640
  46:        0x111dabf74 - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:650
  47:     0x7fff8e492898 - _pthread_body
  48:     0x7fff8e492729 - _pthread_start
```

**Comment by jdm** [comment] 2017-04-13 06:23
This is probably a duplicate of #14637.

**Comment by jdm** [comment] 2019-08-21 19:15
I haven't seen a problem loading the google homepage in years.

**Closed by jdm** 2019-08-21 19:15 UTC
Labels: A-webcompat, I-panic, P-windows
