### ISSUE TITLE
CanvasPaintState::new should take a AntialiasMode not a boolean

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#17668] opened 2017-07-11 14:56 UTC
At the moment, `CanvasPaintState::new` in `components/canvas/canvas_paint_thread.rs ` takes its anti-alias mode argument as a boolean. Really this should be an `AntiAliasMode`. See https://github.com/servo/servo/pull/17609#discussion_r126669932.

**Comment by jdm** [comment] 2017-07-11 15:01
Duplicate of #17661.

**Closed by jdm** 2017-07-11 15:01 UTC
Labels: A-content/canvas, E-easy

**Comment by asajeffrey** [comment] 2017-07-11 15:58
Ah, we both filed this!
