### ISSUE TITLE
Android nightly failing again

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#11195] opened 2016-05-16 10:01 UTC
```
   Compiling winapi-build v0.1.1
   Compiling winapi v0.2.5
   Compiling kernel32-sys v0.2.1
   Compiling walkdir v0.1.5
   Compiling build-apk v0.0.1 (file:///home/servo/buildbot/slave/android-nightly/build/support/android/build-apk)
     Running `/home/servo/buildbot/slave/android-nightly/build/target/debug/build-apk  -o /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release/servo.apk -t /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release -r /home/servo/buildbot/slave/android-nightly/build`
Copying the file "/home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release/libservo.so" to "/home/servo/buildbot/slave/android-nightly/build/support/android/apk/jni/armeabi/libmain.so"
rm -f ./libs/arm64-v8a/lib*.so ./libs/armeabi/lib*.so ./libs/armeabi-v7a/lib*.so ./libs/armeabi-v7a-hard/lib*.so ./libs/mips/lib*.so ./libs/mips64/lib*.so ./libs/x86/lib*.so ./libs/x86_64/lib*.so
rm -f ./libs/arm64-v8a/gdbserver ./libs/armeabi/gdbserver ./libs/armeabi-v7a/gdbserver ./libs/armeabi-v7a-hard/gdbserver ./libs/mips/gdbserver ./libs/mips64/gdbserver ./libs/x86/gdbserver ./libs/x86_64/gdbserver
rm -f ./libs/arm64-v8a/gdb.setup ./libs/armeabi/gdb.setup ./libs/armeabi-v7a/gdb.setup ./libs/armeabi-v7a-hard/gdb.setup ./libs/mips/gdb.setup ./libs/mips64/gdb.setup ./libs/x86/gdb.setup ./libs/x86_64/gdb.setup
[armeabi] Prebuilt       : libmain.so <= jni/armeabi/
cp -f jni/armeabi/libmain.so obj/local/armeabi/libmain.so
[armeabi] Install        : libmain.so => libs/armeabi/libmain.so
install -p ./obj/local/armeabi/libmain.so ./libs/armeabi/libmain.so
/home/servo/android/ndk/r10e/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --strip-unneeded  ./libs/armeabi/libmain.so
Error: Target id 'android-18' is not valid. Use 'android list targets' to get the target ids.
Error while updating the project with the android command
error: Process didn't exit successfully: `/home/servo/buildbot/slave/android-nightly/build/target/debug/build-apk  -o /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release/servo.apk -t /home/servo/buildbot/slave/android-nightly/build/target/arm-linux-androideabi/release -r /home/servo/buildbot/slave/android-nightly/build` (exit code: 1)
Packaging Android exited with return value 1
```

**Comment by aneeshusa** [comment] 2016-05-16 15:35
Dupe of #10339, I have an open PR for this at servo/saltfs#290. This was masked for a while because of an LLVM bug on ARM, but a recent rustup fixed that issue.

**Comment by aneeshusa** [comment] 2016-05-25 03:27
servo/saltfs#290 landed and seems to have fixed the compile step: http://build.servo.org/builders/android-nightly/builds/57. Looking into the other failures now.

**Comment by aneeshusa** [comment] 2016-05-25 03:28
Watch #10339 for updates.

**Closed by aneeshusa** 2016-05-25 03:28 UTC
Labels: A-build, A-infrastructure, P-android
