### ISSUE TITLE
My colemak keyboard layout is not recognized

### ISSUE THREAD

**Issue by juandazapata** [servo/servo#12043] opened 2016-07-01 12:38 UTC
My Colemak keyboard layout is not recognized in Servo. I'm using MacOs El Capitan.

**Comment by fabricedesre** [comment] 2016-07-01 13:01
This should be fixed by https://github.com/servo/servo/pull/11950

**Comment by jdm** [comment] 2016-07-01 14:11
Thanks for reporting the problem! This is a duplicate of #4144, so closing in favour of that one.

**Closed by jdm** 2016-07-01 14:11 UTC
