### ISSUE TITLE
Intermittent failure in XMLHttpRequest/send-entity-body-document.htm

### ISSUE THREAD

**Issue by jdm** [servo/servo#8339] opened 2015-11-04 22:00 UTC
```
  ▶ Unexpected subtest result in /XMLHttpRequest/send-entity-body-document.htm:
  │ FAIL [expected PASS] HTML document, invalid UTF-8
  │   → assert_equals: document should be serialized and sent as text/html;charset=UTF-8 (TEST#1) expected "text/html;charset=UTF-8" but got "text/plain;charset=UTF-8"
  │ 
  │ request/<@http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm:18:1
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  │ request@http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm:13:1
  │ init@http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm:29:42
  └ load@http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm:0:1
```
This should be fixed by #6677.

**Comment by eefriedman** [comment] 2015-11-04 22:17
Duplicate of #8157.

**Closed by eefriedman** 2015-11-04 22:17 UTC
Labels: I-intermittent, P-linux
