### ISSUE TITLE
IFrame in fixed div scrolls down with page, when it should stay fixed.

### ISSUE THREAD

**Issue by samuknet** [servo/servo#13013] opened 2016-08-24 11:11 UTC
When an IFrame is in a fixed div container, scrolling down the page causes the IFrame to be 'scrolled' too, when it should remain in place due the div being CSS `position:fixed;`

Online test case [here](https://samuknet.github.io/test_cases/iframeFixedOnScrollingPage/index.html).

**Comment by jdm** [comment] 2016-08-24 13:21
Note, this only reproduces without webrender enabled. I filed #13015 about how webrender breaks this in totally different ways.

**Comment by glennw** [comment] 2016-08-25 00:21
I can't reproduce #13015 with webrender - it seems to work correctly. But this bug seems to occur the same both with/without webrender enabled for me. I'll look into it today.

**Comment by glennw** [comment] 2016-08-25 01:59
Will be fixed in WR when https://github.com/servo/webrender/pull/368 lands in master.

**Comment by glennw** [comment] 2016-08-29 00:21
Fixed as part of https://github.com/servo/servo/pull/13099

**Closed by glennw** 2016-08-29 00:21 UTC
Labels: A-gfx/rendering
