### ISSUE TITLE
A given font family causes a segfault or a wrong string displayed

### ISSUE THREAD

**Issue by Martiusweb** [servo/servo#2689] opened 2014-06-21 11:47 UTC
I am running a fresh build of servo (commit afb6bf48e) on Archlinux x64.

For a given version of the Roboto font family (front Google), rust either segfaults or displays the next character in the charset (ie "b" is displayed instead of "a").

When I want to display this web page:

```
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
span {
    font-family: "Roboto";
}
</style>
</head>
<body>
    <span>abcdefghijklmnopqrstuvwxyz</span>
    <span>ABCDEFGHIJKLMNOPQRSTUVWXYZ</span>
    <span>0123456789</span>
</body>
</html>
```

You can download the set of TTF fonts causing the bug here:
- http://marti.us/public/TTF-garbled.tgz shows the wrong string,
- http://marti.us/public/TTF-segfault.tgz causes the segfault.

The expected behavior is to display the right string with the right font.

I can always reproduce it on my system, I'll try to test it on an other Linux box.

**Comment by boghison** [comment] 2015-07-05 20:11
Is this still present?

**Comment by dralley** [comment] 2020-04-01 19:52
The page the fonts are served from is dead, and I can't reproduce this with system fonts (Fedora 32), so it's probably best to close this given the age.

**Closed** 2020-04-02 11:34 UTC
Labels: P-linux
