### ISSUE TITLE
Hot spinning on windows shutdown?

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#11307] opened 2016-05-20 22:34 UTC
After #10910, @metajack points out that we may be hot-spinning at shutdown on windows, caused by `window.wait_events().next()` returning `None`. The conversation starts at https://github.com/servo/servo/pull/10910#issuecomment-220718737.

**Comment by asajeffrey** [comment] 2016-05-23 20:08
The issue is that Servo's main event loop is (https://github.com/servo/servo/blob/master/components/servo/main.rs#L77):
```rust
    loop {
        let should_continue = browser.browser.handle_events(window.wait_events());
        if !should_continue {
            break
        }
    };
```
Now, `browser.browser.handle_events` is non-blocking, and only returns `false` when shutdown is complete, so if `window.wait_events` doesn't block, then this is a hot loop. 

The implementation of `window.wait_events` on Windows and MacOS is:
```rust
    fn handle_next_event(&self) -> bool {
        let event = match self.window.wait_events().next() {
            None => {
                warn!("Window event stream closed.");
                return false;
            },
            Some(event) => event,
        };
        ...
    }

```
so if `window.wait_events().next()` returns `None`, then we enter a hot loop.

**Comment by asajeffrey** [comment] 2016-05-23 20:12
Even if we got glutin to never return `None`, I don't see how to get this code to work though, since then `window.wait_events()` will just block indefinitely, so the main loop will never terminate, so Servo will never close.

**Comment by metajack** [comment] 2016-05-23 20:36
So you're saying the hot loop already exists on the other platform.

As for it never closing, It does close because when the constellation is fully shut down, it sends the windowing code a wakeup event. Glutin sees this and passes it off to our event handler, which returns, then we see we're totally done and exit the loop, never calling wait_events again.

**Comment by asajeffrey** [comment] 2016-05-23 20:48
@metajack the other platforms have the same issue under webrender. In non-WR there's a 60fps poll of events instead (https://github.com/servo/servo/blob/master/ports/glutin/window.rs#L413).

The current implementation must be returning `None` from `window.wait_events()` even though there is a wakeup event in the future, which isn't exactly ideal.

**Comment by asajeffrey** [comment] 2016-05-23 21:00
http://tomaka.github.io/glutin/glutin/struct.Window.html#method.wait_events claims the iterator never returns `None`. which is what's causing us grief. Do we at least know that if it does return `None` that there will never be any more events? If so, we can fix this either by returning a 3-valued flag (normal, close or done) rather than a boolean, or by keeping a flag for whether there will ever be any more events.

**Comment by asajeffrey** [comment] 2016-05-23 21:50
A minimal attempt to fix this, but leave as much else alone as possible: https://github.com/asajeffrey/servo/tree/glutin-dont-hotloop-even-if-wait-events-returns-none

This is a bit of a hack, a better approach would be to rewrite the whole glutin interface to use channels to communicate events.

@metajack: submit a PR with the hack? or do a more thorough rewrite?

**Comment by metajack** [comment] 2016-05-24 23:31
@asajeffrey and I discussed out of band that if the hotloop exists on all platforms, we should leave this as is until we do a proper fix (see below). If the hotloop is not consistent, it might make sense to deploy the hack for now.

The right solution appears to be to switch to channels instead of using wait_events(). We can do this on the Servo side by creating a thread which does this coversion. Then we can just select on the two different event stream channels. See #11390 for that work.

**Comment by larsbergstrom** [comment] 2016-07-19 13:43
I think that there are two issues here:

1) The high-level issue identified here with polling for events, due to windowing library limitations

2) Threads panicking and never delivering shutdown messages to the main thread, causing it to continue to poll endlessly.

I believe that #2 is what we're seeing pretty reliably here on Windows. I'm trying to track down better call stacks now.

**Comment by emilio** [comment] 2016-11-04 18:31
If this was the initial issue that @asajeffrey identified here, I identified that too last week and fixed it in #13983, so this should probably be closed.

**Comment by metajack** [comment] 2016-11-04 20:05
Does this fix https://github.com/tomaka/glutin/pull/777/files as well?

The problem I identified there is that when you close the window the HWND is destroyed, so there's no way to wake up the servo event loop since PostMessage to a closed HWND is a no-op. So I used PostThreadMessage instead.

As far as @asajeffrey and I could tell, the real (non-glutin invasive) fix would be to create another thread to unify the event loops.

**Comment by emilio** [comment] 2016-11-06 15:07
Nope, that won't be fixed as far as I know.

**Comment by SaschaNaz** [comment] 2016-11-20 11:47
Is this still being reproduced? The latest Servo build correctly shuts down without spinning on Windows 10 Insider Preview build 14971.

**Comment by larsbergstrom** [comment] 2017-01-06 17:43
Confirmed - thanks!

**Closed by larsbergstrom** 2017-01-06 17:43 UTC
Labels: I-perf-power, P-windows
