### ISSUE TITLE
Newest build crashes on startup with an assertion failed error

### ISSUE THREAD

**Issue by Azeirah** [servo/servo#26148] opened 2020-04-08 18:10 UTC
Downloaded the most recent build, extracted it and it fails with an error when I try to execute it.

md5sum of the build `63ada2efbafefaaadb478c7a2cede87d  servo-latest.tar.gz`

```sh
laura@laura-desktop:~/Downloads/servo$ ./servo
assertion failed: !library.is_null() (thread main, at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/surfman-0.1.4/src/platform/unix/x11/context.rs:44)
```

This is on Linux Mint

```sh
laura@laura-desktop:~/Downloads$ uname -a
Linux laura-desktop 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jdm** [comment] 2020-04-08 18:17
It will be interesting to learn if this goes away when #25853 is merged. Until then, are you running x11 or wayland? This appears to be coming from loading `libGL.so` at runtime in [this code](https://github.com/servo/surfman/blob/0.1/surfman/src/platform/unix/x11/context.rs#L39-L52); perhaps you can figure out what package you can install that will give you the GL libraries you need for your distribution?

**Comment by Darkspirit** [comment] 2020-04-08 18:26
4.15.0-20 is the Linux kernel [version](https://packages.ubuntu.com/bionic/linux-image-4.15.0-20-generic)  of Ubuntu 16.04 and 18.04.
It works for me with Debian Testing, KDE, X11, Intel Iris 6100 (Broadwell GT3).
But I can reproduce the same crash with Ubuntu 20.04, X11+Wayland, Gnome+KDE (=all 4 combinations), Radeon RX480.

**Comment by Darkspirit** [comment] 2020-04-08 18:52
Surfman wants to open the wrong file name.
I have [libGL.so](https://packages.debian.org/search?searchon=contents&keywords=libgl.so) on Debian Testing only because of the [libglvnd-dev](https://packages.debian.org/bullseye/libglvnd-dev). 
`sudo apt install libglvnd-dev` "fixes" the crash on Ubuntu.

**Comment by Azeirah** [comment] 2020-04-09 11:32
> It will be interesting to learn if this goes away when #25853 is merged. Until then, are you running x11 or wayland? This appears to be coming from loading `libGL.so` at runtime in [this code](https://github.com/servo/surfman/blob/0.1/surfman/src/platform/unix/x11/context.rs#L39-L52); perhaps you can figure out what package you can install that will give you the GL libraries you need for your distribution?

I'm using x11. As @Darkspirit suggested, installing `libglvnd-dev` fixes this error for me.

**Closed** 2020-04-09 13:59 UTC
