### ISSUE TITLE
Nightly builds depend on libssl.so.1.0.0

### ISSUE THREAD

**Issue by rillian** [servo/servo#12232] opened 2016-07-04 17:57 UTC
The new nightly servo builds don't work on my Fedora 24 system. They dynamically link `libssl.so.1.0.0` and `libcrypto.so.1.0.0` but my system has `1.0.2h` sonames for these libraries.

Please either link to a more compatible `so.1` soname, or statically link this library (like firefox nightlies do).

**Comment by ZaWertun** [comment] 2016-07-04 18:23
It's a duplicate of #12015

**Comment by jdm** [comment] 2016-07-04 18:40
Thanks for reporting it!

**Closed by jdm** 2016-07-04 18:40 UTC
