### ISSUE TITLE
Navigation causes panics

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#8881] opened 2015-12-07 22:31 UTC
STR:

 - Open google
 - google something
 - go back
 - google something again

I get the following panic

```
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: self.suspended_since.get().is_none()', /home/manishearth/Mozilla/servo/components/script/timers.rs:348
stack backtrace:
   1:     0x7f917b7dead0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3:     0x7f917b7e1440 - panicking::log_panic::hb6d5879621a98ec062x
   4:     0x7f917b7ca0a3 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917a34e1bf - sys_common::unwind::begin_unwind::begin_unwind::h1097998564849796394
   6:     0x7f917a8033d0 - script_task::_<impl>::handle_msg_from_constellation::hc849d2763c97a3abeC1
   7:     0x7f917a8007a5 - script_task::_<impl>::handle_msgs::_<closure>::closure.157956
   8:     0x7f917a7e57e3 - script_task::_<impl>::handle_msgs::hf946f3952c7ffde4mr1
   9:     0x7f917a7ab5d7 - sys_common::unwind::try::try_fn::try_fn::h4487828290051175518
  10:     0x7f917b7ddf78 - __rust_try
  11:     0x7f917b7da33b - sys_common::unwind::try::inner_try::hb614b0fa85d9fb24CMs
  12:     0x7f917a7ad00a - boxed::_<impl>::call_box::call_box::h8691248525593532978
  13:     0x7f917b7e0323 - sys::thread::_<impl>::new::thread_start::h73d591f2e83d6559I5w
  14:     0x7f91773406a9 - start_thread
  15:     0x7f9177b69eec - clone
  16:                0x0 - <unknown>
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:335
stack backtrace:
  thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) } 1thread ': PaintTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) } ' panicked at ' called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) } ',  0x7f917b7dead0 - ../src/libcore/result.rs:sys741
::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3' panicked at ':     called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }0x7f917b7e1440 - panicking', ../src/libcore/result.rs::log_panic:::hb6d5879621a98ec062x
741   4
:     0x7f917b7ca0a3 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917b7ca758thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) } - sys_common::unwind::begin_unwind_fmt::hbd638ea70768c304aPs
' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:741
   6:     0x7f917b7de131 - rust_begin_unwind
   7:     0x7f917b80eb7f - panicking::panic_fmt::h761c3d51c4df5175ZFK
   8:     0x7f917a07ee9d - constellation::_<impl>::handle_failure_msg::handle_failure_msg::h13598374803690613057
   9:     0x7f917a00172a - constellation::_<impl>::handle_request::handle_request::h4973293718417877117
  10:     0x7f9179ff0417 - sys_common::unwind::try::try_fn::try_fn::h13063481173978965566
  11:     0x7f917b7ddf78 - __rust_try
  12:     0x7f917b7da33b - sys_common::unwind::try::inner_try::hb614b0fa85d9fb24CMs
  13:     0x7f9179ff268a - boxed::_<impl>::call_box::call_box::h6160218073359300972
  14:     0x7f917b7e0323 - sys::thread::_<impl>::new::thread_start::h73d591f2e83d6559I5w
  15:     0x7f91773406a9 - start_thread
  16:     0x7f9177b69eec - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x7f917b7dead0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3:     0x7f917b7e1440 - panicking::log_panic::hb6d5879621a98ec062x
   4:     0x7f917b7ca0a3 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917b7ca758 - sys_common::unwind::begin_unwind_fmt::hbd638ea70768c304aPs
   6:     0x7f917b7de131 - rust_begin_unwind
   7:     0x7f917b80eb7f - panicking::panic_fmt::h761c3d51c4df5175ZFK
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }' panicked at '   called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }', 8: ../src/libcore/result.rs:  741
  0x7f917a9b7b12 - sys_common::unwind::try::try_fn::try_fn::h13381529476234937226
   9:     0x7f917b7ddf78 - __rust_try
  10:     0x7f917b7da33b - sys_common::unwind::try::inner_try::hb614b0fa85d9fb24CMs
  11:     0x7f917a9b805a - boxed::_<impl>::call_box::call_box::h12993864265285114303
  12:     0x7f917b7e0323 - sys::thread::_<impl>::new::thread_start::h73d591f2e83d6559I5w
  13:     0x7f91773406a9 - start_thread
  14:     0x7f9177b69eec - clone
  15:                0x0 - <unknown>
stack backtrace:
   1:     0x7f917b7dead0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3:     0x7f917b7e1440 - panicking::log_panic::hb6d5879621a98ec062x
   4:     0x7f917b7ca0a3 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917b7ca758 - sys_common::unwind::begin_unwind_fmt::hbd638ea70768c304aPs
   6:     0x7f917b7de131 - rust_begin_unwind
   7:     0x7f917b80eb7f - panicking::panic_fmt::h761c3d51c4df5175ZFK
   8:     0x7f917a9b7b12 - sys_common::unwind::try::try_fn::try_fn::h13381529476234937226
   9:     0x7f917b7ddf78 - __rust_try
  10:     0x7f917b7da33b - sys_common::unwind::try::inner_try::hb614b0fa85d9fb24CMs
  11:     0x7f917a9b805a - boxed::_<impl>::call_box::call_box::h12993864265285114303
  12:     0x7f917b7e0323 - sys::thread::_<impl>::new::thread_start::h73d591f2e83d6559I5w
  13:     0x7f91773406a9 - start_thread
  14:     0x7f9177b69eec - clone
  15:                0x0 - <unknown>
stack backtrace:
   1:     0x7f917b7dead0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3:     0x7f917b7e1440 - panicking::log_panic::hb6d5879621a98ec062x
   4:     0x7f917b7ca0a3 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917b7ca758 - sys_common::unwind::begin_unwind_fmt::hbd638ea70768c304aPs
   6:     0x7f917b7de131 - rust_begin_unwind
   7:     0x7f917b80eb7f - panicking::panic_fmt::h761c3d51c4df5175ZFK
   8:     0x7f917a9b7b12 - sys_common::unwind::try::try_fn::try_fn::h13381529476234937226
   9:     0x7f917b7ddf78 - __rust_try
  10:     0x7f917b7da33b - sys_common::unwind::try::inner_try::hb614b0fa85d9fb24CMs
  11:     0x7f917a9b805a - boxed::_<impl>::call_box::call_box::h12993864265285114303
  12:     0x7f917b7e0323 - sys::thread::_<impl>::new::thread_start::h73d591f2e83d6559I5w
  13:     0x7f91773406a9 - start_thread
  14:     0x7f9177b69eec - clone
  15:                0x0 - <unknown>
stack backtrace:
   1:     0x7f917b7dead0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3:     0x7f917b7e1440 - panicking::log_panic::hb6d5879621a98ec062x
  thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) } 4: ', ../src/libcore/result.rs:   741 0x7f917b7ca0a3
 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917b7ca758 - sys_common::unwindthread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }' panicked at '::called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }', begin_unwind_fmt::hbd638ea70768c304aPs
../src/libcore/result.rs:  741
 6:     0x7f917b7de131 - rust_begin_unwind
   7:     0x7f917b80eb7f - panicking::panic_fmt::h761c3d51c4df5175ZFK
   8:     0x7f917a2ba265 - layout_task::_<impl>::exit_now::h136d638c206f6fc3VKq
   9:     0x7f917a29d99a - layout_task::_<impl>::handle_request_helper::hfd5663c2f8855a78jAq
  10:     0x7f917a288180 - layout_task::_<impl>::handle_request::h086f933bf56e2dc4Juq
  11:     0x7f917a252aea - sys_common::unwind::try::try_fn::try_fn::h9581937418069073960
  12:     0x7f917b7ddf78 - __rust_try
  13:     0x7f917b7da33b - sys_common::unwind::try::inner_try::hb614b0fa85d9fb24CMs
  14:     0x7f917a253aca - boxed::_<impl>::call_box::call_box::h7795634699286338625
  15:     0x7f917b7e0323 - sys::thread::_<impl>::new::thread_start::h73d591f2e83d6559I5w
  16:     0x7f91773406a9 - start_thread
  17:     0x7f9177b69eec - clone
  18:                0x0 - <unknown>
stack backtrace:
   1:     0x7f917b7dead0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3:     0x7f917b7e1440 - panicking::log_panic::hb6d5879621a98ec062x
   4:     0x7f917b7ca0a3 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917b7ca758 - sys_common::unwind::begin_unwind_fmt::hbd638ea70768c304aPs
   6:     0x7f917b7de131 - rust_begin_unwind
   7:     0x7f917b80eb7f - panicking::panic_fmt::h761c3d51c4df5175ZFK
   8:     0x7f917a2ba265 - layout_task::_<impl>::exit_now::h136d638c206f6fc3VKq
   9:     0x7f917a29d1f1 - layout_task::_<impl>::handle_request_helper::hfd5663c2f8855a78jAq
  10:     0x7f917a288454 - layout_task::_<impl>::handle_request::h086f933bf56e2dc4Juq
  11:     0x7f917a252aea - sys_common::unwind::try::try_fn::try_fn::h9581937418069073960
  12:     0x7f917b7ddf78 - __rust_try
  13:     0x7f917b7da33b - sys_common::unwind::try::inner_try::hb614b0fa85d9fb24CMs
  14:     0x7f917a253aca - boxed::_<impl>::call_box::call_box::h7795634699286338625
  15:     0x7f917b7e0323 - sys::thread::_<impl>::new::thread_start::h73d591f2e83d6559I5w
  16:     0x7f91773406a9 - start_thread
  17:     0x7f9177b69eec - clone
  18:                0x0 - <unknown>
stack backtrace:
   1:     0x7f917b7dead0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3:     0x7f917b7e1440 - panicking::log_panic::hb6d5879621a98ec062x
   4:     0x7f917b7ca0a3 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917b7ca758 - sys_common::unwind::begin_unwind_fmt::hbd638ea70768c304aPs
   6:     0x7f917b7de131 - rust_begin_unwind
   7:     0x7f917b80eb7f - panicking::panic_fmt::h761c3d51c4df5175ZFK
   8:     0x7f917a2ba265 - layout_task::_<impl>::exit_now::h136d638c206f6fc3VKq
   9:     0x7f917a29d1f1 - layout_task::_<impl>::handle_request_helper::hfd5663c2f8855a78jAq
  10:     0x7f917a288454 - layout_task::_<impl>::handle_request::h086f933bf56e2dc4Juq
  11:     0x7f917a252aea - sys_common::unwind::try::try_fn::try_fn::h9581937418069073960
  12:     0x7f917b7ddf78 - __rust_try
  13:     0x7f917b7da33b - sys_common::unwind::try::inner_try::hb614b0fa85d9fb24CMs
  14:     0x7f917a253aca - boxed::_<impl>::call_box::call_box::h7795634699286338625
  15:     0x7f917b7e0323 - sys::thread::_<impl>::new::thread_start::h73d591f2e83d6559I5w
  16:     0x7f91773406a9 - start_thread
  17:     0x7f9177b69eec - clone
  18:                0x0 - <unknown>
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:741
stack backtrace:
   1:     0x7f917b7dead0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3:     0x7f917b7e1440 - panicking::log_panic::hb6d5879621a98ec062x
   4:     0x7f917b7ca0a3 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917b7ca758 - sys_common::unwind::begin_unwind_fmt::hbd638ea70768c304aPs
   6:     0x7f917b7de131 - rust_begin_unwind
   7:     0x7f917b80eb7f - panicking::panic_fmt::h761c3d51c4df5175ZFK
   8:     0x7f917a6d6387 - dom::htmlstyleelement::_<impl>::parse_own_css::he1f2d880ec081df1kVG
   9:     0x7f917a6e8b03 - dom::node::_<impl>::insert::hca2cf1609f12457clKL
  10:     0x7f917a6e0edb - dom::node::_<impl>::pre_insert::hfe58cc6f55c4f94dWIL
  11:     0x7f917a704cff - parse::html::_<impl>::append::hffc3bec2d0c71331U6Z
  12:     0x7f917a7047b1 - tree_builder::actions::_<impl>::insert_appropriately::insert_appropriately::h18108819162991440826
  13:     0x7f917a71b2d0 - tree_builder::rules::_<impl>::step::step::h17380571773333369958
  14:     0x7f917a6fdf71 - tree_builder::_<impl>::process_token::process_token::h7263834143799931975
  15:     0x7f917a6fd1a3 - tokenizer::_<impl>::process_token::process_token::h14698694081404053714
  16:     0x7f917a7306c6 - tokenizer::_<impl>::step::step::h15418223535171525720
  17:     0x7f917a728e07 - tokenizer::_<impl>::run::run::h6281619174821322719
  18:     0x7f917a6f524b - dom::servohtmlparser::_<impl>::parse_sync::h632a246055f9769aM1O
  19:     0x7f917a6f4d4a - dom::servohtmlparser::_<impl>::parse_chunk::hf50fcedbb4910fbeeVO
  20:     0x7f917a6f8c10 - dom::servohtmlparser::_<impl>::data_available::hb9baa04839f46d9f3OO
  21:     0x7f917ad02f26 - _<impl>::process::hce70e10ac83c827f2ud
  22:     0x7f917a8219a7 - network_listener::_<impl>::handler::h10497066926700204202
  23:     0x7f917a7bb3be - script_task::_<impl>::handle_msg_from_script::ha3620ede02a12cd8pF1
  24:     0x7f917a80137d - script_task::_<impl>::handle_msgs::_<closure>::closure.157956
  25:     0x7f917a7e57e3 - script_task::_<impl>::handle_msgs::hf946f3952c7ffde4mr1
  26:     0x7f917a7ab5d7 - sys_common::unwind::try::try_fn::try_fn::h4487828290051175518
  27:     0x7f917b7ddf78 - __rust_try
  28:     0x7f917b7da33b - sys_common::unwind::try::inner_try::hb614b0fa85d9fb24CMs
  29:     0x7f917a7ad00a - boxed::_<impl>::call_box::call_box::h8691248525593532978
  30:     0x7f917b7e0323 - sys::thread::_<impl>::new::thread_start::h73d591f2e83d6559I5w
  31:     0x7f91773406a9 - start_thread
  32:     0x7f9177b69eec - clone
  33:                0x0 - <unknown>
thread '<main>' panicked at 'Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }).', /home/manishearth/Mozilla/servo/components/compositing/compositor.rs:687
stack backtrace:
   1:     0x7f917b7dead0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3:     0x7f917b7e1440 - panicking::log_panic::hb6d5879621a98ec062x
   4:     0x7f917b7ca0a3 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917b7ca758 - sys_common::unwind::begin_unwind_fmt::hbd638ea70768c304aPs
   6:     0x7f9179f93e1c - compositor::_<impl>::handle_events::handle_events::h58285367965573902
   7:     0x7f9179fc85fc - _<impl>::handle_events::h50824e4696ca350aTda
   8:     0x7f9179f7e915 - main::hb77cfbfb032d8741Laa
   9:     0x7f917b7e11e4 - sys_common::unwind::try::try_fn::h8505855046713178995
  10:     0x7f917b7ddf78 - __rust_try
  11:     0x7f917b7e0e86 - rt::lang_start::h45458ea0787b3e00e0x
  12:     0x7f9177a83a3f - __libc_start_main
  13:     0x7f9179f724a8 - _start
  14:                0x0 - <unknown>
thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /home/manishearth/Mozilla/servo/./../.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs:166
stack backtrace:
   1:     0x7f917b7dead0 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
   2:     0x7f917b7e19c5 - panicking::log_panic::_<closure>::closure.40991
   3:     0x7f917b7e1440 - panicking::log_panic::hb6d5879621a98ec062x
   4:     0x7f917b7c9fc8 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
   5:     0x7f917ae7184f - sys_common::unwind::begin_unwind::begin_unwind::h4438296073649004460
   6:     0x7f917ae71950 - platform::linux::surface::_<impl>::dropthread '::h85fafc5ba1537c58jbc
LayoutTask PipelineId { namespace_id: PipelineNamespaceId(4), index: PipelineIndex(1) }   ' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError7:  ', ../src/libcore/result.rsthread ' LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }:' panicked at ' called `Result::unwrap()` on an `Err` value: RecvError 7410x
7f9179f8ea27 - alloc..rc..Rc', ../src/libcore/result.rs:<layers..layers..Layer741
<compositing..compositor_layer..CompositorData>>::drop.28887::h0f6111235162ca0f
   8:     0x7f9179f8eb75 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.28899::h3e777dfd8bd2c29d
   9:     0x7f9179f8e904 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28887::h0f6111235162ca0f
  10:     0x7f9179f8eb75 - collections..vec..Vec<alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>>::drop.28899::h3e777dfd8bd2c29d
  11:     0x7f9179f8e904 - alloc..rc..Rc<layers..layers..Layer<compositing..compositor_layer..CompositorData>>::drop.28887::h0f6111235162ca0f
  12:     0x7f9179f90a41 - compositing..compositor..IOCompositor<app..window..Window>::drop.29264::h864c8306c5430886
  13:     0x7f9179f7ec4f - main::hb77cfbfb032d8741Laa
  14:     0x7f917b7e11e4 - sys_common::unwind::try::try_fn::h8505855046713178995
  15:     0x7f917b7ddf78 - __rust_try
  16:     0x7f917b7e0e86 - rt::lang_start::h45458ea0787b3e00e0x
  17:     0x7f9177a83a3f - __libc_start_main
  18:     0x7f9179f724a8 - _start
  19:                0x0 - <unknown>
thread panicked while panicking. aborting.stack backtrace:
```

**Comment by mbrubeck** [comment] 2015-12-07 22:34
Duplicate of #8461?

**Closed** 2015-12-07 22:34 UTC
Labels: A-constellation, I-panic
