### ISSUE TITLE
unknown completed load Stylesheet("https://0.gravatar.com/css/services.css?ver=201627y")

### ISSUE THREAD

**Issue by hrbrmstr** [servo/servo#12245] opened 2016-07-04 23:31 UTC
unknown completed load Stylesheet("https://0.gravatar.com/css/services.css?ver=201627y")
### URL:
https://rud.is/b/2016/06/16/your-data-vis-spidey-sense-the-need-for-a-robust-utility-belt/
### Backtrace:
```
frame #0  - 0x000000010560174e - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x00000001056016d1 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x00000001048cfd16 - _<F as alloc..boxed..FnBox<A>>::call_box::h6059122298f825d8
frame #3  - 0x0000000105575b57 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x00000001057e98c4 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000000105802806 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x00000001057eaf08 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x000000010580245f - rust_begin_unwind
frame #8  - 0x00000001058292e0 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x0000000105830d85 - core::option::expect_failed::hdb92832549f56a85
frame #10 - 0x000000010410a2c1 - script::document_loader::DocumentLoader::finish_load::hc807fb8cb9c56a2d
frame #11 - 0x0000000104107f81 - script::dom::document::Document::finish_load::h1ce7e49c25d85fc2
frame #12 - 0x0000000104776c5b - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h315c5e417b85cb3a
frame #13 - 0x0000000104774a25 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::hc0416bc7ab472afc
frame #14 - 0x00000001048db5ec - script::script_thread::ScriptThread::handle_msg_from_script::hd1f5e7b2423a8c64
frame #15 - 0x0000000104937711 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc67d8b381c013b79
frame #16 - 0x000000010491d3cf - script::script_thread::ScriptThread::handle_msgs::h236c5be60a207bea
frame #17 - 0x00000001048ce597 - std::panicking::try::call::h645a328f039d97c6
frame #18 - 0x00000001058054eb - __rust_try
frame #19 - 0x0000000105805485 - __rust_maybe_catch_panic
frame #20 - 0x00000001048cf744 - _<F as alloc..boxed..FnBox<A>>::call_box::h3db95636eb747818
frame #21 - 0x0000000105800f68 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #22 - 0x00007fff89bdd99c - _pthread_body
frame #23 - 0x00007fff89bdd919 - _pthread_start

```

**Comment by emilio** [comment] 2016-07-04 23:49
Hi, thanks for reporting this!

I'm closing it though, since it is a duplicate of https://github.com/servo/servo/issues/12075 and presumably should be fixed by #12241 :)

**Closed by emilio** 2016-07-04 23:50 UTC
