### ISSUE TITLE
servo use google search error

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#18163] opened 2017-08-20 19:56 UTC
First I command:
```
./mach run --dev http://www.google.com
```
then log:
```
ERROR:script::dom::bindings::error: Error at https://www.google.com.tw/?gfe_rd=cr&ei=BOiZWdeuMY2u4wLykL6ADw:1:1 document.f.q is undefined
```
but it still load the page, and then I enter something then press enter key to search
then the app crash with with "white screen" said `Could not load the request page: Unexpected sheme`

Full Error log:
```
tigercosmos@ubuntu:~/servo$ ./mach run --dev https://www.google.com
ERROR:script::dom::bindings::error: Error at https://www.google.com.tw/?gfe_rd=cr&ei=wOiZWcmFFJPC4ALOuL-gAg:1:1 document.f.q is undefined
ERROR:script::dom::bindings::error: Error at https://www.google.com.tw/?gfe_rd=cr&ei=wOiZWcmFFJPC4ALOuL-gAg:1:1 q is not defined
assertion failed: !self.is_inline_flex_item() (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }, at /home/tigercosmos/servo/components/layout/block.rs:1491)
stack backtrace:
   0:     0x562bb4ec2704 - backtrace::backtrace::libunwind::trace
                        at /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x562bb4ebc8ef - backtrace::capture::{{impl}}::new
                        at /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x562bae1c70dc - servo::main::{{closure}}
                        at /home/tigercosmos/servo/ports/servo/main.rs:130
   3:     0x562bb4fb43a6 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:611
   4:     0x562bb2553c86 - std::panicking::begin_panic<&str>
                        at /checkout/src/libstd/panicking.rs:571
   5:     0x562bb26b54b0 - layout::block::{{impl}}::assign_inline_position_for_formatting_context
                        at /home/tigercosmos/servo/components/layout/block.rs:1491
   6:     0x562bb26b936d - layout::block::{{impl}}::assign_block_size_for_inorder_child_if_necessary
                        at /home/tigercosmos/servo/components/layout/block.rs:1870
   7:     0x562bb26de621 - layout::block::{{impl}}::assign_block_size_block_base
                        at /home/tigercosmos/servo/components/layout/block.rs:879
                         - layout::flex::{{impl}}::assign_block_size
                        at /home/tigercosmos/servo/components/layout/flex.rs:942
   8:     0x562bb26f5794 - layout::traversal::{{impl}}::process
                        at /home/tigercosmos/servo/components/layout/traversal.rs:283
   9:     0x562bb26ebf9c - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:50
  10:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  11:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  12:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  13:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  14:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  15:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  16:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  17:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  18:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  19:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  20:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  21:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  22:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  23:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  24:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  25:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  26:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  27:     0x562bb26ebf6b - layout::sequential::reflow::doit
                        at /home/tigercosmos/servo/components/layout/sequential.rs:46
  28:     0x562bb26ebc6b - layout::sequential::reflow
                        at /home/tigercosmos/servo/components/layout/sequential.rs:68
  29:     0x562baee033f7 - layout_thread::{{impl}}::solve_constraints
                        at /home/tigercosmos/servo/components/layout_thread/lib.rs:932
  30:     0x562baf0620f8 - layout_thread::{{impl}}::perform_post_style_recalc_layout_passes::{{closure}}
                        at /home/tigercosmos/servo/components/layout_thread/lib.rs:1620
  31:     0x562baef0ed98 - profile_traits::time::profile<(),closure>
                        at /home/tigercosmos/servo/components/profile_traits/time.rs:123
  32:     0x562baee0ba92 - layout_thread::{{impl}}::perform_post_style_recalc_layout_passes
                        at /home/tigercosmos/servo/components/layout_thread/lib.rs:1605
  33:     0x562baee0707e - layout_thread::{{impl}}::handle_reflow
                        at /home/tigercosmos/servo/components/layout_thread/lib.rs:1348
  34:     0x562baf05fe2d - layout_thread::{{impl}}::handle_request_helper::{{closure}}
                        at /home/tigercosmos/servo/components/layout_thread/lib.rs:708
  35:     0x562baef0e9f8 - profile_traits::time::profile<(),closure>
                        at /home/tigercosmos/servo/components/profile_traits/time.rs:123
  36:     0x562baee00403 - layout_thread::{{impl}}::handle_request_helper
                        at /home/tigercosmos/servo/components/layout_thread/lib.rs:705
  37:     0x562baedff425 - layout_thread::{{impl}}::handle_request
                        at /home/tigercosmos/servo/components/layout_thread/lib.rs:677
  38:     0x562baedfe64b - layout_thread::{{impl}}::start
                        at /home/tigercosmos/servo/components/layout_thread/lib.rs:593
  39:     0x562baeebc059 - layout_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at /home/tigercosmos/servo/components/layout_thread/lib.rs:319
  40:     0x562baee33372 - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script_layout_interface::message::Msg,script_layout_interface::message::Msg,std::sync::mpsc::Sender<script_layout_interface::message::Msg>>
                        at /home/tigercosmos/servo/components/profile_traits/mem.rs:63
  41:     0x562baf05f949 - layout_thread::{{impl}}::create::{{closure}}
                        at /home/tigercosmos/servo/components/layout_thread/lib.rs:318
  42:     0x562baef47dba - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  43:     0x562baee44c63 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:364
  44:     0x562baee0e58a - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  45:     0x562baed54e82 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:479
  46:     0x562bb4fbb45c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  47:     0x562baed5497c - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:458
  48:     0x562baee44b05 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  49:     0x562baef49f5e - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:363
  50:     0x562baefb68d3 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:682
  51:     0x562bb4fb305b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
  52:     0x7f27491e86d9 - start_thread
  53:     0x7f2748d0bd7e - __clone
  54:                0x0 - <unknown>
ERROR:servo: assertion failed: !self.is_inline_flex_item()
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }, at /checkout/src/libcore/result.rs:860)
ScriptThread: received a resize msg for a pipeline not in this script thread. This is a bug. (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /checkout/src/libcore/option.rs:819)
stack backtrace:
   0:     0x562bb4ec2704 - backtrace::backtrace::libunwind::trace
                        at /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x562bb4ebc8ef - backtrace::capture::{{impl}}::new
                        at /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x562bae1c70dc - servo::main::{{closure}}
                        at /home/tigercosmos/servo/ports/servo/main.rs:130
   3:     0x562bb4fb43a6 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:611
   4:     0x562bb4fb41c4 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:571
   5:     0x562bb4fb4139 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:521
   6:     0x562bb4fb40ca - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:497
   7:     0x562bb4fe3410 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x562bb24b0ddc - core::result::unwrap_failed<std::sys_common::poison::PoisonError<std::sync::mutex::MutexGuard<layout::query::LayoutThreadData>>>
                        at /checkout/src/libcore/macros.rs:41
   9:     0x562bb255933b - core::result::{{impl}}::unwrap<std::sync::mutex::MutexGuard<layout::query::LayoutThreadData>,std::sys_common::poison::PoisonError<std::sync::mutex::MutexGuard<layout::query::LayoutThreadData>>>
                        at /checkout/src/libcore/result.rs:738
  10:     0x562bb25c73e3 - layout::query::{{impl}}::node_geometry
                        at /home/tigercosmos/servo/components/layout/query.rs:148
  11:     0x562bafae54d2 - script::dom::window::{{impl}}::client_rect_query
                        at /home/tigercosmos/servo/components/script/dom/window.rs:1414
  12:     0x562bafa39789 - script::dom::node::{{impl}}::client_rect
                        at /home/tigercosmos/servo/components/script/dom/node.rs:615
  13:     0x562bb0eaddfd - script::dom::element::{{impl}}::ClientHeight
                        at /home/tigercosmos/servo/components/script/dom/element.rs:2039
  14:     0x562bb160c2b2 - script::dom::bindings::codegen::Bindings::ElementBinding::ElementBinding::get_clientHeight::{{closure}}
                        at /home/tigercosmos/servo/target/debug/build/script-11a815433a47bb39/out/Bindings/ElementBinding.rs:2882
  15:     0x562bb1366fdf - core::ops::function::FnOnce::call_once<closure,()>
                        at /checkout/src/libcore/ops/function.rs:143
  16:     0x562bb102d2fa - std::panic::{{impl}}::call_once<bool,closure>
                        at /checkout/src/libstd/panic.rs:296
  17:     0x562baff886dc - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,bool>
                        at /checkout/src/libstd/panicking.rs:479
  18:     0x562bb4fbb45c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  19:     0x562bafe1f5ed - std::panicking::try<bool,std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:458
  20:     0x562bb12b3c01 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,bool>
                        at /checkout/src/libstd/panic.rs:361
  21:     0x562bb11e7d82 - js::panic::wrap_panic<std::panic::AssertUnwindSafe<closure>,bool>
                        at /home/tigercosmos/servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/panic.rs:22
  22:     0x562bafba185c - script::dom::bindings::codegen::Bindings::ElementBinding::ElementBinding::get_clientHeight
                        at /home/tigercosmos/servo/target/debug/build/script-11a815433a47bb39/out/Bindings/ElementBinding.rs:2880
  23:     0x562bb19ba1f4 - CallJitGetterOp
                        at /home/tigercosmos/servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/jsglue.cpp:498
  24:     0x562baf97ebbe - script::dom::bindings::utils::generic_call
                        at /home/tigercosmos/servo/components/script/dom/bindings/utils.rs:446
  25:     0x562baf97edf1 - script::dom::bindings::utils::generic_getter
                        at /home/tigercosmos/servo/components/script/dom/bindings/utils.rs:462
  26:     0x562bb1d64033 - _ZN2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgsE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
                         - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
  27:     0x562bb1d642c7 - _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:517
  28:     0x562bb1d6438c - _ZN2js10CallGetterEP9JSContextN2JS6HandleINS2_5ValueEEES5_NS2_13MutableHandleIS4_EE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:631
  29:     0x562bb1d64476 - CallGetter
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/NativeObject.cpp:1737
  30:     0x562bb1d647e9 - GetExistingProperty<(js::AllowGC)1u>
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/NativeObject.cpp:1785
                         - NativeGetPropertyInline<(js::AllowGC)1u>
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/NativeObject.cpp:2012
                         - _ZN2js17NativeGetPropertyEP9JSContextN2JS6HandleIPNS_12NativeObjectEEENS3_INS2_5ValueEEENS3_I4jsidEENS2_13MutableHandleIS7_EE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/NativeObject.cpp:2046
  31:     0x562bb19f6a68 - _ZN2js11GetPropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_5ValueEEENS3_I4jsidEENS2_13MutableHandleIS7_EE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/NativeObject.h:1481
  32:     0x562bb1d64dd1 - _ZN2js11GetPropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_5ValueEEEPNS_12PropertyNameENS2_13MutableHandleIS7_EE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobj.h:831
                         - _ZN2js11GetPropertyEP9JSContextN2JS6HandleINS2_5ValueEEENS3_IPNS_12PropertyNameEEENS2_13MutableHandleIS4_EE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:4161
  33:     0x562bb1d574c8 - GetPropertyOperation
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:189
                         - Interpret
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2590
  34:     0x562bb1d63d3f - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  35:     0x562bb1d69dfd - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_16AbstractFramePtrEPS9_
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:679
  36:     0x562bb1d69f67 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:712
  37:     0x562bb1bb7d47 - Evaluate
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4407
  38:     0x562bb1bb926e - Evaluate
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4443
                         - _ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEEE
                        at /home/tigercosmos/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4501
  39:     0x562bb0ec04a7 - script::dom::globalscope::{{impl}}::evaluate_script_on_global_with_result::{{closure}}
                        at /home/tigercosmos/servo/components/script/dom/globalscope.rs:394
  40:     0x562bb04dd7af - profile_traits::time::profile<bool,closure>
                        at /home/tigercosmos/servo/components/profile_traits/time.rs:123
  41:     0x562baf9fadba - script::dom::globalscope::{{impl}}::evaluate_script_on_global_with_result
                        at /home/tigercosmos/servo/components/script/dom/globalscope.rs:378
  42:     0x562bb0eda654 - script::dom::htmlscriptelement::{{impl}}::run_a_classic_script
                        at /home/tigercosmos/servo/components/script/dom/htmlscriptelement.rs:573
  43:     0x562bb0ed9db3 - script::dom::htmlscriptelement::{{impl}}::execute
                        at /home/tigercosmos/servo/components/script/dom/htmlscriptelement.rs:543
  44:     0x562bb0ed75d0 - script::dom::htmlscriptelement::{{impl}}::prepare
                        at /home/tigercosmos/servo/components/script/dom/htmlscriptelement.rs:456
  45:     0x562bb0f09c22 - script::dom::servoparser::{{impl}}::tokenize<closure>
                        at /home/tigercosmos/servo/components/script/dom/servoparser/mod.rs:440
  46:     0x562bb0f08fff - script::dom::servoparser::{{impl}}::do_parse_sync
                        at /home/tigercosmos/servo/components/script/dom/servoparser/mod.rs:395
  47:     0x562bb0f08dc7 - script::dom::servoparser::{{impl}}::parse_sync::{{closure}}
                        at /home/tigercosmos/servo/components/script/dom/servoparser/mod.rs:381
  48:     0x562bb04dccac - profile_traits::time::profile<(),closure>
                        at /home/tigercosmos/servo/components/profile_traits/time.rs:123
  49:     0x562bb0f08cb5 - script::dom::servoparser::{{impl}}::parse_sync
                        at /home/tigercosmos/servo/components/script/dom/servoparser/mod.rs:378
  50:     0x562bb0f0949c - script::dom::servoparser::{{impl}}::parse_bytes_chunk
                        at /home/tigercosmos/servo/components/script/dom/servoparser/mod.rs:420
  51:     0x562bb0f0cf29 - script::dom::servoparser::{{impl}}::process_response_chunk
                        at /home/tigercosmos/servo/components/script/dom/servoparser/mod.rs:688
  52:     0x562bafb24f60 - script::script_thread::{{impl}}::handle_fetch_chunk
                        at /home/tigercosmos/servo/components/script/script_thread.rs:2419
  53:     0x562bafb0b5fc - script::script_thread::{{impl}}::handle_msg_from_constellation
                        at /home/tigercosmos/servo/components/script/script_thread.rs:1206
  54:     0x562bafb08b4e - script::script_thread::{{impl}}::handle_msgs::{{closure}}
                        at /home/tigercosmos/servo/components/script/script_thread.rs:1086
  55:     0x562bafb08ff0 - script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>
                        at /home/tigercosmos/servo/components/script/script_thread.rs:1197
  56:     0x562bafb06070 - script::script_thread::{{impl}}::handle_msgs
                        at /home/tigercosmos/servo/components/script/script_thread.rs:1080
  57:     0x562bafb03e45 - script::script_thread::{{impl}}::start
                        at /home/tigercosmos/servo/components/script/script_thread.rs:915
  58:     0x562bafb01694 - script::script_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at /home/tigercosmos/servo/components/script/script_thread.rs:608
  59:     0x562baf19ce4e - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>>
                        at /home/tigercosmos/servo/components/profile_traits/mem.rs:63
  60:     0x562bb0f36d1b - script::script_thread::{{impl}}::create::{{closure}}
                        at /home/tigercosmos/servo/components/script/script_thread.rs:607
  61:     0x562bb07cc4da - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  62:     0x562bb12bc373 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:364
  63:     0x562bb102965a - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  64:     0x562baff1dda2 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:479
  65:     0x562bb4fbb45c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  66:     0x562bafeef2dc - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:458
  67:     0x562bb12ae495 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  68:     0x562bb07d536e - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:363
  69:     0x562bb0cb7b33 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:682
  70:     0x562bb4fb305b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
  71:     0x7f27491e86d9 - start_thread
  72:     0x7f2748d0bd7e - __clone
  73:                0x0 - <unknown>
stack backtrace:
   0:     0x562bb4ec2704 - backtrace::backtrace::libunwind::trace
                        at /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
ERROR:servo: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
                         - backtrace::backtrace::trace<closure>
                        at /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x562bb4ebc8ef - backtrace::capture::{{impl}}::new
                        at /home/tigercosmos/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x562bae1c70dc - servo::main::{{closure}}
                        at /home/tigercosmos/servo/ports/servo/main.rs:130
   3:     0x562bb4fb43a6 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:611
   4:     0x562bb4fb41c4 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:571
   5:     0x562bb4fb4139 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:521
   6:     0x562bb4fb40ca - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:497
   7:     0x562bb4fe3410 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x562bb4fe347d - core::option::expect_failed
                        at /checkout/src/libcore/option.rs:819
   9:     0x562baf2a2ce4 - core::option::{{impl}}::expect<script::dom::bindings::js::Root<script::dom::window::Window>>
                        at /checkout/src/libcore/option.rs:302
  10:     0x562bafb166e7 - script::script_thread::{{impl}}::handle_resize_inactive_msg
                        at /home/tigercosmos/servo/components/script/script_thread.rs:1649
  11:     0x562bafb0a7b3 - script::script_thread::{{impl}}::handle_msg_from_constellation
                        at /home/tigercosmos/servo/components/script/script_thread.rs:1216
  12:     0x562bafb08b4e - script::script_thread::{{impl}}::handle_msgs::{{closure}}
                        at /home/tigercosmos/servo/components/script/script_thread.rs:1086
  13:     0x562bafb08ff0 - script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>
                        at /home/tigercosmos/servo/components/script/script_thread.rs:1197
  14:     0x562bafb06070 - script::script_thread::{{impl}}::handle_msgs
                        at /home/tigercosmos/servo/components/script/script_thread.rs:1080
  15:     0x562bafb03e45 - script::script_thread::{{impl}}::start
                        at /home/tigercosmos/servo/components/script/script_thread.rs:915
  16:     0x562bafb01694 - script::script_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at /home/tigercosmos/servo/components/script/script_thread.rs:608
  17:     0x562baf19ce4e - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>>
                        at /home/tigercosmos/servo/components/profile_traits/mem.rs:63
  18:     0x562bb0f36d1b - script::script_thread::{{impl}}::create::{{closure}}
                        at /home/tigercosmos/servo/components/script/script_thread.rs:607
  19:     0x562bb07cc4da - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  20:     0x562bb12bc373 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:364
  21:     0x562bb102965a - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  22:     0x562baff1dda2 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:479
  23:     0x562bb4fbb45c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  24:     0x562bafeef2dc - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:458
  25:     0x562bb12ae495 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  26:     0x562bb07d536e - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:363
  27:     0x562bb0cb7b33 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:682
  28:     0x562bb4fb305b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
  29:     0x7f27491e86d9 - start_thread
  30:     0x7f2748d0bd7e - __clone
  31:                0x0 - <unknown>
ERROR:servo: ScriptThread: received a resize msg for a pipeline not in this script thread. This is a bug.
ERROR:constellation::constellation: about:failure failed
ERROR:constellation::constellation: about:failure failed
```

**Comment by mateon1** [comment] 2017-08-20 21:03
I think this is a duplicate of #14813 (same assertion, but that one is about gmail)

**Closed** 2017-08-21 04:28 UTC
