### ISSUE TITLE
assertion failed: self.suspended_since.get().is_some()

### ISSUE THREAD

**Issue by yiwang** [servo/servo#14311] opened 2016-11-21 19:26 UTC
assertion failed: self.suspended_since.get().is_some()
### Servo Version:
Servo 0.0.1-f14e733
### Backtrace:
```

WARNING: <LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(4) }>: update_style_for_animation: No current keyframe found for animation "gb__a" at progress 0.8492423523475857
WARNING: <LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(4) }>: update_style_for_animation: No current keyframe found for animation "gb__a" at progress 0.9346870210684646
WARNING: <Constellation>: Closing frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(7) } twice.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(7) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(7) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(7) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(7) } iterated after closure.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: Message sent to closed pipeline (1,9).
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(7) } iterated after closure.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: Message sent to closed pipeline (1,9).
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(7) } iterated after closure.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: Message sent to closed pipeline (1,9).
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(1), index: FrameIndex(7) } iterated after closure.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: Message sent to closed pipeline (1,9).
WARNING: <Constellation>: Closing frame FrameId { namespace_id: PipelineNamespaceId(13), index: FrameIndex(2) } twice.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-11-21 19:27
Duplicate of #13716. Thanks for reporting it!

**Closed by jdm** 2016-11-21 19:27 UTC
