### ISSUE TITLE
Forgot password link on Github on the wrong place

### ISSUE THREAD

**Issue by sviter** [servo/servo#17468] opened 2017-06-22 09:33 UTC
On Github sign in page Forgot password link is placed lower with Servo then in Firefox on Windows 10.
Servo:
![servo-github](https://user-images.githubusercontent.com/6523067/27427022-26042534-5746-11e7-94fc-58cad13f2970.png)
Firefox:
![firefox-github](https://user-images.githubusercontent.com/6523067/27427033-344b8df8-5746-11e7-9915-92c177661857.png)

Note also there no Github logo with Servo.

**Comment by emilio** [comment] 2017-06-22 09:38
The logo is expected because it uses `<svg>`, which servo doesn't yet support. The link position is a dupe of https://github.com/servo/servo/issues/13683.

Thanks for reporting it though! Closing this as already tracked by #12973 and #13683.

**Closed by emilio** 2017-06-22 09:38 UTC
