### ISSUE TITLE
Illegal constructor exception in /bluetooth/characteristic/getDescriptors/gen-characteristic-is-removed.https.html

### ISSUE THREAD

**Issue by georgeroman** [servo/servo#23059] opened 2019-03-19 17:22 UTC
```
▶ Unexpected subtest result in /bluetooth/characteristic/getDescriptors/gen-characteristic-is-removed.https.html:
  │ FAIL [expected PASS] gen-characteristic-is-removed
  │   → Illegal constructor.
  │ 
  └ @https://web-platform.test:8443/bluetooth/resources/bluetooth-helpers.js:177:10
```

**Comment by jdm** [comment] 2019-03-19 17:30
```html
<script>new DOMException('a', 'b')</script>
```
This runs fine in Firefox and yields the following exception in Servo:
```
[2019-03-19T17:30:03Z ERROR script::dom::bindings::error] Error at file:///tmp/foo2.html:1:1 Illegal constructor.
```

**Comment by jdm** [comment] 2019-03-19 17:32
I think we need to add `Constructor(optional DOMString message = "", optional DOMString name)` to DOMException.webidl like in Firefox: https://searchfox.org/mozilla-central/source/dom/webidl/DOMException.webidl#70

**Comment by jdm** [comment] 2019-03-19 17:33
Oops, this is a duplicate of #22412.

**Closed by jdm** 2019-03-19 17:33 UTC
Labels: A-content/dom, C-has-manual-testcase
