### ISSUE TITLE
Intermittent failure in /_mozilla/mozilla/mozbrowser/iframe_visibility.html

### ISSUE THREAD

**Issue by simartin** [servo/servo#12569] opened 2016-07-23 18:58 UTC
Found during a test run for https://github.com/servo/servo/pull/12565

```
  ▶ Unexpected subtest result in /_mozilla/mozilla/mozbrowser/iframe_visibility.html:
  │ FAIL [expected PASS] Requesting animation frame composites only when frame is visible
  │   → assert_true: expected true got false
  │ 
  │ iframe.onload</<@http://web-platform.test:8000/_mozilla/mozilla/mozbrowser/iframe_visibility.html:58:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1426:20
```

**Comment by KiChjang** [comment] 2016-07-23 21:39
Not an intermittent.

**Comment by jdm** [comment] 2016-07-24 12:57
Duplicate of #11825.

**Closed by jdm** 2016-07-24 12:57 UTC
Labels: I-intermittent
