### ISSUE TITLE
Intermittent panic in webrender during shutdown

### ISSUE THREAD

**Issue by jdm** [servo/servo#32867] opened 2024-07-28 01:44 UTC
```
▶ CRASH [expected FAIL] /html/canvas/element/manual/imagebitmap/imageBitmapRendering-transferFromImageBitmap-webgl.html
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ called `Option::unwrap()` on a `None` value (thread WRSceneBuilder#0, at /home/runner/.cargo/git/checkouts/webrender-c3596abe1cf4f320/9d354ad/webrender/src/scene_builder_thread.rs:517)
  │    0: servoshell::backtrace::print
  │    1: servoshell::panic_hook::panic_hook
  │    2: std::panicking::rust_panic_with_hook
  │    3: std::panicking::begin_panic_handler::{{closure}}
  │    4: std::sys_common::backtrace::__rust_end_short_backtrace
  │    5: rust_begin_unwind
  │    6: core::panicking::panic_fmt
  │    7: core::panicking::panic
  │    8: core::option::unwrap_failed
  │    9: webrender::scene_builder_thread::SceneBuilderThread::process_transaction
  │   10: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  │   11: webrender::scene_builder_thread::SceneBuilderThread::run
  │   12: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   14: std::sys::pal::unix::thread::Thread::new::thread_start
  │   15: <unknown>
  │   16: <unknown>
  │ mozilla::detail::MutexImpl::~MutexImpl: pthread_mutex_destroy failed: Device or resource busy
  │ Caught signal 11thread panicked while processing panic. aborting.
  │ Redirecting call to abort() to mozalloc_abort
```

This comes from https://github.com/servo/webrender/blob/9d354ad/webrender/src/scene_builder_thread.rs#L517, so it looks like there's some missing synchronization with webrender around documents when we're trying to shutdown?

**Comment by jdm** [comment] 2024-07-28 01:53
I believe this is what happens:
* the compositor shuts down and drops its RenderApi member
* the [Drop implementation](https://github.com/servo/webrender/blob/75aefa6f8c51a7cca83dd1aa45881b40bfd71532/webrender/src/render_api.rs#L1372-L1376) for RenderApi runs, sending a ClearNamespace message to the scene builder thread
* the scene builder thread [deletes any documents matching the namespace](https://github.com/servo/webrender/blob/75aefa6f8c51a7cca83dd1aa45881b40bfd71532/webrender/src/scene_builder_thread.rs#L345-L347)
* the scene builder thread processes a pending transaction from before the compositor was shut down, but the associated document no longer exists

**Comment by jdm** [comment] 2024-07-28 01:54
We should be able to avoid this by calling [flush_scene_builder](https://doc.servo.org/webrender/render_api/struct.RenderApi.html#method.flush_scene_builder) before shutting down the compositor.

**Comment by jdm** [comment] 2024-07-28 02:04
This appears multiple times per test run from a quick investigation, so it would be good to remove one known source of intermittent failures from our CI.

**Comment by gterzian** [comment] 2024-07-30 09:35
I am pretty sure that:

- Every `Transaction` we send uses the scene builder thread, and that
- We don't use the [`support_low_priority_transactions`](https://doc.servo.org/webrender/struct.WebRenderOptions.html#structfield.support_low_priority_transactions) option

This means that `SceneBuilderRequest::ClearNamespace` and any `SceneBuilderRequest::Transactions` are sent on the same channel, so "the scene builder thread processes a pending transaction from before the compositor was shut down" should not be possible, unless we send a transaction after we have already dropped the render api, and if we do, it will not be fixed by adding a `SceneBuilderRequest::Flush` before dropping the render api. 


So I think the problem is rather that webgl sends a transaction after compositor has already shut down.

**Closed** 2024-08-06 11:21 UTC
Labels: E-less-complex, I-panic, A-webrender
