### ISSUE TITLE
joint_session should include pending pipelines

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#12784] opened 2016-08-09 10:42 UTC
If the user presses the back button too early, before a pending pipeline is added, we end up thawing/freezing the wrong pipelines.

Run with: `./mach run -d -- -z --pref dom.mozbrowser.enabled /tmp/a.html`

``` html
<iframe mozbrowser="true"></iframe>

<script>
  var iframe = document.querySelector("iframe");
  var once = (elt, event, cb) => {
    var _cb = () => {
      elt.removeEventListener(event, _cb);
      cb();
    }
    elt.addEventListener(event, _cb);
  }
  iframe.addEventListener("mozbrowserloadstart", e => console.log("START"));
  iframe.addEventListener("mozbrowserloadend", e => console.log("END"));
  once(iframe, "mozbrowserloadend", () => {

    var back = () => iframe.goBack();

    once(iframe, "mozbrowserloadstart", back);

    iframe.src = "http://example.com/test";
  });
  iframe.src = "http://example.com";
</script>
```

```
ERROR:servo: assertion failed: self.suspended_since.get().is_none() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at /Users/Paul/git/servo/components/script/timers.rs:230)
ERROR:servo: called `Option::unwrap()` on a `None` value (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at ../src/libcore/option.rs:326)
```

In the above test case, we have 4 pipelines:
- 0,0 top level document, we don't care
- 1,0 about:blank
- 1,1 http://example.com
- 1,2 http://example.com/test

On `goBack()`, `traverse_frame_to_pipeline` is called with 1,0 instead of 1,1.

/cc @ConnorGBrewster

**Comment by ConnorGBrewster** [comment] 2016-08-09 14:00
Good catch! I'll look into figuring out how to include pending pipelines in the jsh.

**Comment by ConnorGBrewster** [comment] 2016-08-09 19:57
So it looks like the issue is that when navigating, we freeze the current pipeline when creating the new pending pipeline. If you traverse before the pipeline is no longer pending, we freeze the current pipeline again, causing the assertion failure.

**Comment by ConnorGBrewster** [comment] 2016-08-11 17:29
@paulrouget this ends up being fixed by #12784 if that lands. The backwards traversal will traverse to `http://example.com` leaving `http://example.com/test` in the session future.

**Comment by paulrouget** [comment] 2016-08-12 01:32
Sounds good to me. Thanks.

**Comment by paulrouget** [comment] 2018-06-06 06:14
@cbrewster is this still relevant?

**Comment by cbrewster** [comment] 2018-06-06 06:35
I don’t believe so.

**Closed by cbrewster** 2018-06-06 06:35 UTC
Labels: A-constellation
