### ISSUE TITLE
Alphabetized imports false positive

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#7830] opened 2015-10-02 13:03 UTC
According to our lint checker, this is not sorted:

```rust
use dom::bindings::codegen::InheritTypes::ElementCast;
use dom::bindings::codegen::InheritTypes::{HTMLElementCast, HTMLTableCellElementDerived};
use dom::bindings::codegen::InheritTypes::HTMLTableRowElementCast;
use dom::bindings::codegen::InheritTypes::NodeCast;
```

The output:

![screen shot 2015-10-02 at 9 02 51 am](https://cloud.githubusercontent.com/assets/416575/10247085/643c2c86-68e4-11e5-85ac-e3b2dc1cdab5.png)

**Comment by frewsxcv** [comment] 2015-10-02 13:04
If I change it to:

```rust
use dom::bindings::codegen::InheritTypes::ElementCast;
use dom::bindings::codegen::InheritTypes::HTMLElementCast;
use dom::bindings::codegen::InheritTypes::HTMLTableCellElementDerived;
use dom::bindings::codegen::InheritTypes::HTMLTableRowElementCast;
use dom::bindings::codegen::InheritTypes::NodeCast;
```

no errors are reported

**Comment by jdm** [comment] 2015-10-02 14:17
Looks like similar confusion to #7412.

**Comment by mbrubeck** [comment] 2016-05-24 00:30
Closing as duplicate of #7412.

**Closed by mbrubeck** 2016-05-24 00:30 UTC
Labels: A-testing, C-duplicate
