### ISSUE TITLE
Panic in MP3 metadata reading on YouTube

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#13497] opened 2016-09-29 01:49 UTC
Go to https://www.youtube.com/watch?v=x0YfEzWWJhs and navigate over a few links. You get a crash. Stack trace:

```
* thread #25: tid = 0xcc32d, 0x0000000101973070 servo`rust_panic, stop reason = breakpoint 1.1
  * frame #0: 0x0000000101973070 servo`rust_panic
    frame #1: 0x0000000101973045 servo`std::panicking::rust_panic_with_hook::hb1322e5f2588b4db + 437
    frame #2: 0x0000000101972e85 servo`std::panicking::begin_panic::hfbeda5aad583dc32 + 101
    frame #3: 0x0000000101972da3 servo`std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf + 147
    frame #4: 0x0000000101972d08 servo`rust_begin_unwind + 56
    frame #5: 0x000000010199fd0e servo`core::panicking::panic_fmt::h4395919ece15c671 + 126
    frame #6: 0x000000010199fc89 servo`core::panicking::panic_bounds_check::he139831fe8feb00a + 105
    frame #7: 0x0000000101467874 servo`mp3_metadata::metadata::get_id3::h1923e6aef8d5e4e7 + 13348
    frame #8: 0x0000000101467f3b servo`mp3_metadata::metadata::read_from_slice::h55364a728ac40138 + 219
    frame #9: 0x0000000100b948f5 servo`audio_video_metadata::metadata::get_format_from_slice::h9398dce1be4ebbac + 4101
    frame #10: 0x000000010086b435 servo`_$LT$script..dom..htmlmediaelement..HTMLMediaElementContext$u20$as$u20$net_traits..AsyncResponseListener$GT$::data_available::hf998e73501f910ff + 373
    frame #11: 0x000000010095b0fa servo`_$LT$script..network_listener..ListenerRunnable$LT$A$C$$u20$Listener$GT$$u20$as$u20$script..script_thread..Runnable$GT$::handler::h42dc3768c7a881e0 + 282
    frame #12: 0x0000000100968ad3 servo`_$LT$script..script_thread..CancellableRunnable$LT$T$GT$$u20$as$u20$script..script_thread..Runnable$GT$::handler::h7b64986152e5873f + 19
    frame #13: 0x0000000100982af6 servo`script::script_thread::ScriptThread::handle_msg_from_script::he40c1ffdcab9b8b5 + 1670
    frame #14: 0x0000000100b1fa9f servo`script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h655b7f961e17302f + 95
    frame #15: 0x000000010097704a servo`script::script_thread::ScriptThread::handle_msgs::hc4ab524548c42ef9 + 20090
    frame #16: 0x000000010053b818 servo`std::panicking::try::do_call::h2b7856705cabc385 + 1448
    frame #17: 0x00000001019742bb servo`__rust_maybe_catch_panic + 27
    frame #18: 0x00000001006c7217 servo`_$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h2a6162fbc8208345 + 167
    frame #19: 0x0000000101971ed5 servo`std::sys::thread::Thread::new::thread_start::h022e3887023c6290 + 37
    frame #20: 0x00007fff948e199d libsystem_pthread.dylib`_pthread_body + 131
    frame #21: 0x00007fff948e191a libsystem_pthread.dylib`_pthread_start + 168
    frame #22: 0x00007fff948df351 libsystem_pthread.dylib`thread_start + 13
```

**Comment by frewsxcv** [comment] 2016-09-29 01:52
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment] 2016-09-29 07:55
Is it with the last version of the crate?

**Comment by Ms2ger** [comment] 2016-09-29 08:35
#13421? #13444 should fix.

**Comment by GuillaumeGomez** [comment] 2016-09-29 09:12
So it isn't.

@pcwalton: Please retry once merged.

**Comment by GuillaumeGomez** [comment] 2016-09-30 13:41
It has been merged. Can you test again please?

**Comment by nox** [comment] 2017-10-05 07:47
I can't reproduce this anymore.

**Closed by nox** 2017-10-05 07:47 UTC
Labels: A-content/parsers, A-content/uncategorized, C-is-this-done, I-panic
