### ISSUE TITLE
Write a lint to flag moving Root values

### ISSUE THREAD

**Issue by jdm** [servo/servo#5724] opened 2015-04-16 19:10 UTC
They should not be moved, because that can change the ordering of the values that get unrooted later. It would be nicer to catch this at compile time than runtime.

**Comment by Manishearth** [comment] 2015-04-20 09:49
So, a `#[no_move]` annotation that works transitively (via a self propagating lint and `walk_ty`).

We ban:

 - `foo(nomove)` but not `foo(&nomove)`
 - Functions which take nomove types by value instead of by reference, same for return types
 - Blocks which have the last expr of type nomove
 - Match arms containing nomove in their patterns. Might require a custom pattern visitor since we want to ignore `ref` and `_`.

Sounds good?

**Comment by Manishearth** [comment] 2015-04-20 09:49
(We can also use this for https://github.com/servo/servo/issues/5737)

**Comment by jdm** [comment] 2015-04-20 12:29
Yes, that sounds like a solid set of rules. Probably should check the capture clauses of `move` closures, too.

**Comment by Manishearth** [comment] 2015-04-20 15:39
... that is going to require a full function visitor :/

**Comment by Manishearth** [comment] 2015-04-20 15:40
I wish rustc could provide hooks for stuff like "move" and "drop" and other intrinsic thingies.

How hard would this be, @kmcallister ? It would greatly simplify humpty_dumpty too.

**Comment by jdm** [comment] 2015-04-20 15:47
I would definitely be fine moving ahead with your rules and filing a follow up for this. We've already got dynamic checks that would notice a no_move value being moved into a closure.

**Comment by Manishearth** [comment] 2015-04-20 15:47
\o/ I don't have to write a visitor :p

**Comment by Manishearth** [comment] 2015-04-26 16:44
https://github.com/Manishearth/rust-tenacious should work.

It uses rustc's internal variable-usage-tracking magic, so I *think* it handles everything including capture clauses.

**Comment by frewsxcv** [comment] 2015-04-26 20:49
https://github.com/servo/servo/issues/3528 is a duplicate of this and can probably be closed

**Comment by Munksgaard** [comment] 2015-04-27 22:02
I just took a look at the code for tenacious, and it looks quite good to me. 

Of course, like with humpty_dumpty, there are things tenacious can't quite handle, most severely functions in other crates and unsafe code, but generic functions are also not handled very. I'm under the impression that that shouldn't be too much of a problem here though, just something to keep in mind, I think.

**Comment by Munksgaard** [comment] 2015-04-27 22:07
For example, this doesn't error, but it probably should:

```rust
#![feature(plugin, custom_attribute)]
#![plugin(tenacious)]

#![deny(moved_no_move)]
#![allow(dead_code, unused)]

fn main() {
    let x = bar(Foo);
}

fn bar<T>(x: T) -> T {
    let y = x;
    y
}


#[derive(Debug)]
#[no_move]
struct Foo;
```

**Comment by Manishearth** [comment] 2015-04-27 22:11
After thinking about it, it does handle generics to the most part, it just has an issue with internally-`unsafe` "safe" functions like `mem::swap()` and `mem::replace()` which take in `&` pointers but move out of them.


It also has an issue with passing a temporary to a generic. `fn bar<T>(t: T) {let x = t; let y = x;}` followed by `bar(make_temporary())` will not be linted. The only way to fix this is to lint on rvalues too (I plan to add a cargo feature for toggling this behavior), but rvalues lead to a lot of noise in the lint (which I'm mostly fine with).

We don't do any of this -- moving a temporary rootything into a generic function which itself moves internally seems ... rare. But we can look into it later.

**Comment by Manishearth** [comment] 2015-04-27 22:14
Our dynamic checks will catch this anyway, so we're probably good.

**Closed** 2015-04-28 05:21 UTC
Labels: A-plugins, I-safety
