### ISSUE TITLE
Implement baseline-source

### ISSUE THREAD

**Issue by Loirooriol** [servo/servo#31875] opened 2024-03-26 11:25 UTC
After #31705 I think it should be quite straightforward to implement `baseline-source`: https://drafts.csswg.org/css-inline/#baseline-source

This will require Stylo changes, so you can follow the instructions from #31723

Basically https://github.com/servo/stylo/blob/bcdebc41b2a2222e9fa5ae6d7d1572025c32dc47/style/properties/longhands/box.mako.rs#L107 needs to change the obsolete `servo-2013` into `servo`

And then https://github.com/servo/servo/blob/d814d0553981777c01409d545e5c1c335b8eb7f4/components/layout_2020/flow/inline.rs#L2145-L2153 needs to check `BaselineSource`, picking the 1st baseline for `BaselineSource::First`, the last baseline for `BaselineSource::Last`, and keep the current logic for `BaselineSource::Auto`.

**Comment by MunishMummadi** [comment] 2024-03-26 14:30
@servo-highfive assign me

**Comment by servo-highfive** [comment] 2024-03-26 14:30
Hey @MunishMummadi! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by MunishMummadi** [comment] 2024-03-26 14:45
Hey @Loirooriol . Can I work on this. If this not intended. Please let me know. Thank you.

**Comment by Loirooriol** [comment] 2024-03-26 14:46
Yes, you can take it!

**Comment by MunishMummadi** [comment] 2024-03-26 17:18
Just to be clear. In stylo I just have replace `servo-2013` with `servo` and update is 
```rust
 fn pick_baseline(&self, baselines: &Baselines) -> Option<Au> {
    // Checking the baseline source
    match self.baseline_source() {
        BaselineSource::First => return baselines.first,
        BaselineSource::Last => return baselines.last,
        BaselineSource::Auto => {
            // The existing logic for `Auto` remains unchanged.
            if let Self::NonReplaced(non_replaced) = self {
                if let NonReplacedFormattingContextContents::Flow(_) = non_replaced.contents {
                    return baselines.last;
                }
            }
            baselines.first
        },
    }
}

```

**Comment by Loirooriol** [comment] 2024-03-26 18:23
Yes, enable the property in Stylo, and update `pick_baseline` here in Servo.

**Comment by MunishMummadi** [comment] 2024-03-26 21:33
I am getting this error `error[E0609]: no field `baseline_source` on type `&servo_arc::Arc<style::properties::ComputedValues>`
    --> components/layout_2020/flow/inline.rs:2152:21
     |
2152 |         match style.baseline_source {
     |                     ^^^^^^^^^^^^^^^ unknown field

For more information about this error, try `rustc --explain E0609`.
error: could not compile `layout_2020` (lib) due to previous error`.

So, I made a little change 
```rust
fn pick_baseline(&self, baselines: &Baselines) -> Option<Au> {
    let baseline_source = match self {
        IndependentFormattingContext::Replaced(_) => BaselineSource::Auto,
        IndependentFormattingContext::NonReplaced(non_replaced) => {
            if let NonReplacedFormattingContextContents::Flow(_) = non_replaced.contents {
                BaselineSource::Last
            } else {
                BaselineSource::First
            }
        }
    };

    match baseline_source {
        BaselineSource::First => baselines.first,
        BaselineSource::Last => baselines.last,
        BaselineSource::Auto => {
            if let IndependentFormattingContext::NonReplaced(non_replaced) = self {
                if let NonReplacedFormattingContextContents::Flow(_) = non_replaced.contents {
                    return baselines.last;
                }
            }
            baselines.first
        },
    }
}
```

**Comment by Loirooriol** [comment] 2024-03-26 21:53
Have you modified Cargo.toml to use https://github.com/servo/stylo/pull/26 ?

See the instructions from https://github.com/servo/servo/issues/31723

**Comment by MunishMummadi** [comment] 2024-03-26 21:55
my bad. I forgot that!!. Sorry for the overlook.

**Comment by MunishMummadi** [comment] 2024-03-27 01:09
Hey @Loirooriol . Can u look at my gist https://gist.github.com/MunishMummadi/de39a9aceefe63057d1efa4059696b91 .

**Comment by Loirooriol** [comment] 2024-03-27 11:38
Try `self.style().baseline_source()`

**Comment by MunishMummadi** [comment] 2024-03-27 13:29
I didn't mentioned that but I tried it . Am i missing something!!!!.
```console
munish@Zoro:~/servo$ ./mach build
No build type specified so assuming `--dev`.
warning: unused import: `std::mem`
 --> components/script/dom/baseaudiocontext.rs:8:5
  |
8 | use std::mem;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `script` (lib) generated 1 warning (run `cargo fix --lib -p script` to apply 1 suggestion)
   Compiling layout_2020 v0.0.1 (/home/munish/servo/components/layout_2020)
error[E0599]: no method named `baseline_source` found for reference `&servo_arc::Arc<style::properties::ComputedValues>` in the current scope
    --> components/layout_2020/flow/inline.rs:2148:28
     |
2148 |         match self.style().baseline_source() {
     |                            ^^^^^^^^^^^^^^^ help: there is a method with a similar name: `clone_baseline_source`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `layout_2020` (lib) due to previous error
      Timing report saved to /home/munish/servo/target/cargo-timings/cargo-timing-20240327T132428Z.html
Failed in 0:00:03
[Warning] Could not generate notification: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
munish@Zoro:~/servo$
```

**Comment by mrobinson** [comment] 2024-03-27 13:45
@MunishMummadi Yes, you need to build Servo using the version of stylo that you modified (https://github.com/servo/stylo/pull/26). In order to do that you need to override the repository URL and branch name to be your fork and branch. Look for all the references to `https://github.com/servo/stylo/` in the root `Cargo.toml` of Servo. Instead of the branch named "2023-09-01" you will need to use your branch "servo2013." When you build the new `baseline_source()` function should be available.

**Comment by mrobinson** [comment] 2024-03-27 13:46
Oh, apologies. I forgot the second part: Once the changes from servo/style#26 are merged, you will then need to undo your changes, but update the version of stylo used in servo using `cargo update -p style` (but *importantly* not until the changes from servo/style#26 are merged).

**Comment by MunishMummadi** [comment] 2024-03-27 13:47
@mrobinson thanks for info. Let me do it .

**Comment by Loirooriol** [comment] 2024-03-27 13:48
@MunishMummadi The error tells you what to do: use `clone_baseline_source()` instead of `baseline_source()`.

**Comment by mrobinson** [comment] 2024-03-27 14:17
> @MunishMummadi The error tells you what to do: use `clone_baseline_source()` instead of `baseline_source()`.

Sorry, @MunishMummadi. I didn't read the error properly. Oriol is correct here and you can ignore my comment.

**Comment by MunishMummadi** [comment] 2024-03-31 04:14
Hey @Loirooriol As the issue is reopened can I know some context. so, that I can work on it

**Comment by Loirooriol** [comment] 2024-03-31 16:19
I reopened because https://github.com/servo/servo/pull/31904 hasn't landed.

**Closed** 2024-04-02 11:21 UTC
Labels: E-less-complex, C-assigned
