### ISSUE TITLE
An element with display: inline-block will cause a containing span's border to be cut off.

### ISSUE THREAD

**Issue by Permutatrix** [servo/servo#13142] opened 2016-08-31 20:24 UTC
While trying to decipher the CSS specification with regard to #12939, I created a document that looked something like this to see how Firefox and Chromium would interpret it:

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    <span id="outer" style="border: 1px solid #000">
      Test 3
      <span id="inner" style="display: inline-block; overflow: hidden; width: 100px; height: 100px">XYZ</span>
    </span>
  </body>
</html>
```

...which is rendered by Firefox like this: 
![Firefox's correct rendering](https://cloud.githubusercontent.com/assets/13004953/18144923/fc5baf96-6f7d-11e6-9b12-8108fb7c969b.png)

...by Chromium like this: 
![Chromium's correct rendering](https://cloud.githubusercontent.com/assets/13004953/18144928/01a4bc40-6f7e-11e6-96b4-c24c299bba55.png)

...and by Servo like this: 
![Servo's incorrect rendering](https://cloud.githubusercontent.com/assets/13004953/18144929/0458e326-6f7e-11e6-81eb-fe199f5b70a9.png)

**Comment by notriddle** [comment] 2016-09-04 05:02
Duplicate of #7681?

**Comment by Permutatrix** [comment] 2016-09-04 05:54
@notriddle That seems likely. I didn't check for duplicates because I wasn't sure how and figured someone else would catch it, like you just did. I hope that was proper etiquette.

**Comment by Permutatrix** [comment] 2016-09-04 06:04
@notriddle I removed the `is_primary_fragment` condition you mentioned in [this comment](https://github.com/servo/servo/issues/7681#issuecomment-205511149) on that issue. It now renders the right half of the border, but it's much too large and disconnected from the left half:
![sr](https://cloud.githubusercontent.com/assets/13004953/18229340/ad0e1a14-722a-11e6-8a9a-5a9c95bcf809.png)

This seems to match the results you described.

**Comment by nox** [comment] 2017-10-04 23:00
Closing as duplicate of #7681.

**Closed by nox** 2017-10-04 23:00 UTC
Labels: A-layout/inline, I-wrong
