### ISSUE TITLE
DOMRefCell<T> already borrowed: BorrowMutError

### ISSUE THREAD

**Issue by grahamc** [servo/servo#14543] opened 2016-12-10 03:09 UTC
DOMRefCell<T> already borrowed: BorrowMutError
### URL:

1. click "duck duck go" in the first page
2. type "google"
3. click google (typing in to the URL bar doesn't seem to work?)
4. search google for "the guardian"
5. Click the result for the guardian

ps: are these useful? I don't mean to spam you all.

### Servo Version:
Servo 0.0.1-4cb3404
### Backtrace:
```

WARNING: update_style_for_animation: No current keyframe found for animation "gb__a" at progress 0.9761809304529848
WARNING: update_style_for_animation: No current keyframe found for animation "gb__a" at progress 0.97619
...
```
This report was generated by the browser.html issue reporter.

**Comment by emilio** [comment] 2016-12-10 03:15
I can confirm they're extremely useful :)

**Comment by jdm** [comment] 2016-12-13 21:39
This is almost certainly the same underlying problem as #14553.

**Comment by nox** [comment] 2017-10-07 10:25
Closing because #14553 was fixed.

**Closed by nox** 2017-10-07 10:25 UTC
Labels: A-webcompat, I-panic
