### ISSUE TITLE
servo.org blank

### ISSUE THREAD

**Issue by matthiaskrgr** [servo/servo#10024] opened 2016-03-16 02:11 UTC
Trying to display servo.org shows a bit of text for a very short moment but then the servo window goes completely blank, no text is shown.

Rendering succeeds however when launching servo with -w until I scroll down the page a bit and then servo crashes (crash looks like #9931 )

**Comment by sm-Fifteen** [comment] 2016-03-17 19:22
Same issue here, although scrolling a bit reveals that some of page does render, but the page has about two windows worth of leading blank space at any given size and the visible part starts at "Contributing".

**Comment by mmatyas** [comment] 2016-03-21 11:35
Also happens on Odroid XU3, using Servo `aa35d772` with ES2 backend.

**Comment by matthiaskrgr** [comment] 2016-03-22 23:34
As of right  now ( 003fdd41769652188a5954e6499f3cb44eef6b10 ), it seems only the upper half of the page is not rendered and the lower part is displayed..

**Comment by matthiaskrgr** [comment] 2016-03-23 00:10
Alright, I tried to reduce the servo.org page.

In this example, only ````<p class='text-muted'>#servo on irc.mozilla.org</p>```` is rendered, and everything inside ````<div class='col-sm-8'>```` is invisible unless webrender is used.
````
<html>
<head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Servo, the parallel browser engine</title>
	<style>
pre {
  overflow: auto;
}
code {
  font-family: monospace, monospace;
  font-size: 1em;
}

/*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css */

html {
  font-size: 10px;
}
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.42857143;
  color: #333;
  background-color: #fff;
}

.col-md-3, .col-sm-8, .col-lg-12 {
  position: relative;
  min-height: 1px;
  padding-right: 15px;
  padding-left: 15px;
}
	</style>
</head>

<body>
<div class='container'>
    <div class='row'>
        <div class='col-sm-8'>

<pre><code>git clone https://github.com/servo/servo
cd servo
./mach build --dev
./mach run tests/html/about-mozilla.html</code></pre>

        </div>
    </div>

            <footer class='text-center'>
                <div class='col-md-3'>
                    <p class='text-muted'>#servo on irc.mozilla.org</p>
                </div>
            </footer>
        </div>
    </div>
</div>

</body>
</html>
````

**Comment by matthiaskrgr** [comment] 2016-03-23 16:39
#10151 might be related.

**Comment by atouchet** [comment] 2017-07-21 05:25
Is this issue still valid? I am not able to reproduce it.

**Comment by nox** [comment] 2017-10-01 00:12
I can't reproduce it either. Closing.

**Closed by nox** 2017-10-01 00:12 UTC
Labels: A-gfx/rendering
