### ISSUE TITLE
Screen shifts to top-right direction

### ISSUE THREAD

**Issue by saschanaz** [servo/servo#20836] opened 2018-05-20 13:31 UTC
![image](https://user-images.githubusercontent.com/3396686/40279392-f7a4d03e-5c7c-11e8-812a-a3fd5fb5a1bd.png)

This is the initial screen when I turn Servo on, and I cannot scroll to the upper position.

On Surface 3, Windows 10, with device recommended 150% scale.

**Comment by jdm** [comment] 2018-05-20 15:59
This looks like a duplicate of #20505.

**Closed** 2018-05-20 22:29 UTC
Labels: P-windows
