### ISSUE TITLE
Add icon to Servo on Windows 

### ISSUE THREAD

**Issue by metajack** [servo/servo#11315] opened 2016-05-21 01:10 UTC
Linux and OS X have icons, but we still don't have one for windows. This should be an easy fix for anyone familiar with Windows development.

**Comment by perlun** [comment] 2016-05-22 20:11
What icon should we use - the same as for Linux and OS X, presumably?

**Comment by metajack** [comment] 2016-05-22 20:12
Yes. It's a placeholder, but it will work for now.

**Comment by perlun** [comment] 2016-05-23 20:44
Alright. I'll give it a try, you can mark the issue as assigned if you like.

**Comment by paulrouget** [comment] 2016-05-31 00:03
Necessary for developer preview, not for June's demo. P1 -> P3.

**Comment by perlun** [comment] 2016-05-31 05:06
@paulrouget - thanks for the clarity. Do we have a timeline for a developer preview? Sounds like "much later"? 😄

**Comment by paulrouget** [comment] 2016-05-31 06:16
> @paulrouget - thanks for the clarity. Do we have a timeline for a developer preview? Sounds like "much later"? 😄

Not much later. Hopefully, by the end of the month.

**Comment by paulrouget** [comment] 2016-05-31 06:17
So yeah, if we can get that fixed soon, that'll make us happy :)

**Comment by KiChjang** [comment] 2016-06-17 00:30
@perlun Are you still planning to work on this?

**Comment by perlun** [comment] 2016-06-17 06:00
@KiChjang Unfortunately, my Windows development is a bit hampered by #9939; I could theoretically try to fix this issue but I have no way to build the code so... If anyone runs out of work and want to do it, feel free.

**Comment by Coder206** [comment] 2016-06-18 18:54
What is the Servo icon?

**Comment by jdm** [comment] 2016-06-18 18:57
https://github.com/servo/servo/blob/master/resources/servo.png

**Comment by Coder206** [comment] 2016-06-18 18:59
@jdm Nice!!

**Comment by Coder206** [comment] 2016-06-18 23:56
@metajack I would like to work on this one, I am running Windows 10. I am not encountering the errors that @perlun has mentioned but I cannot see the icon for Servo.

**Comment by Coder206** [comment] 2016-06-18 23:57
@metajack Is the file below the one that is not working?
File: https://github.com/servo/servo/blob/b5115fc895bb40bce52d39de65a07160935b15fd/ports/glutin/window.rs#L135

**Comment by perlun** [comment] 2016-06-19 19:15
@Coder206 - I'm fine with you taking over this if you can manage to get it done, not too much servo-time for me at the moment. 😢 

So the problem is that the icon is not shown on Windows; the code for doing it is simply not implemented. The line you refer to _seems_ to be related to it, but I suspect it has to be added to the `WindowBuilder` implementation; I would guess that this is the class that handles the OS specific part of "using an icon for a window".

I tried looking both in this repo and in the glutin repo (https://github.com/servo/glutin) for the `WindowBuilder` code, but couldn't find it which is strange. Anyone else know where it is?

----

Anyway, this link has some more details on dealing with icons on Windows: http://stackoverflow.com/questions/30291757/attaching-an-icon-resource-to-a-rust-application
(The `.rc` file approach seems reasonable. You probably have to convert the `.png` to a standard Windows `.ico` file to get it done using that approach, though.)

If you get the `.rc` file approach working, you can probably skip the WindowBuilder stuff I mentioned first altogether. Best of luck! Let us know if you need more help to get it done.

**Comment by Coder206** [comment] 2016-06-19 19:35
@perlun Thanks for the information! :) Means a lot to have something to start off with!

**Comment by Coder206** [comment] 2016-06-19 20:02
Where should the code go for this? In the main.rs?

**Comment by Coder206** [comment] 2016-06-20 10:43
@perlun Did you manage to get the rust-windows project working on your system? Link: https://github.com/klutzy/rust-windows/tree/master/examples

**Comment by Coder206** [comment] 2016-06-20 21:04
@paulrouget Is the fix due in 10 days?

**Comment by Coder206** [comment] 2016-06-20 23:57
Thanks to WindowsBunnyTheAlmightyFloof and durkas, I was able to the example working in Servo. I will do my best to get the bug fixed for developer preview launch

**Comment by Coder206** [comment] 2016-06-21 10:17
@perlun You were right, Windows wanted an ico! Below is a simple project (rust-windows) that shows it is possible to make an icon visible on Windows. Thanks again @perlun for the link! 
@metajack I think it would make a better contrast if the logo was more lighter in color (avoid the color of the system taskbar).

![servo](https://cloud.githubusercontent.com/assets/7758155/16225977/5f7da8e8-3777-11e6-9233-44047e1c0d69.PNG)

**Comment by jdm** [comment] 2016-06-21 12:04
That should be avoided by the updated version from https://github.com/servo/servo/pull/11473#issuecomment-223118097.

**Comment by Coder206** [comment] 2016-06-21 15:45
@jdm Has it been updated yet?

**Comment by Coder206** [comment] 2016-06-21 20:46
Can we assign this one to me?

**Comment by perlun** [comment] 2016-06-21 20:52
@Coder206 - it's unfortunately not possible to assign an issue to someone who's not registered as a contributor to the project at GitHub (i.e. people like you or me 😄). But consider it "implicitly assigned" to you for now.

(@jdm/someone - maybe it would be an idea to set up a GitHub team "without permissions" just to be able to handle stuff like that? I.e. people who are contributing but who don't have review or merge rights or anything like that.)

**Comment by Coder206** [comment] 2016-06-21 20:53
@perlun Sorry I am mean the tag "C-Assigned"

**Comment by Coder206** [comment] 2016-06-21 20:54
@perlun I like the idea of a "without permissions" setup.

**Comment by Coder206** [comment] 2016-06-21 20:54
@larsbergstrom Thanks :)

**Comment by jdm** [comment] 2016-06-21 21:09
@perlun We've discussed that idea in https://github.com/servo/highfive/issues/30 before.

**Comment by KiChjang** [comment] 2016-07-08 10:59
@Coder206 How's this progressing so far?

**Comment by Coder206** [comment] 2016-07-08 11:27
@KiChjang It's going well. I have to just work out a few code issues from the #11969 PR so I hope to complete it all this morning. I am not sure however how would I test this code. Do I just run the build and see if the logo shows up?

**Comment by nox** [comment] 2017-09-24 13:33
Latest attempt at this was in #11969.

**Comment by nox** [comment] 2017-09-24 13:33
I think there are various issues with winres which means this shouldn't be E-Easy.

**Comment by atouchet** [comment] 2018-03-19 02:53
This was fixed in #20316.

**Closed by atouchet** 2018-03-19 02:53 UTC
