### ISSUE TITLE
Intermittent timeout in /_mozilla/webgl/conformance-1.0.3/conformance/canvas/rapid-resizing.html

### ISSUE THREAD

**Issue by jdm** [servo/servo#16221] opened 2017-04-01 04:23 UTC
```
  ▶ TIMEOUT [expected OK] /webgl/conformance-1.0.3/conformance/canvas/rapid-resizing.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ DESCRIPTION: Verifies that rapidly resizing the canvas works correctly.
  │ 
  │ Regression test for Chromium <a href='http://crbug.com/299371'>Issue 299371</a>
  │ 
  │ PASS context exists
  │ PASS program is non-null.
  │ requestAnimationFrame
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ requestAnimFrame: document.hidden = undefined
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  └ requestAnimFrame: document.hidden = undefined

  ▶ Unexpected subtest result in /webgl/conformance-1.0.3/conformance/canvas/rapid-resizing.html:
  └ NOTRUN [expected PASS] Overall test
```

**Comment by nox** [comment] 2018-03-21 12:07
Duplicate of #16215.

**Closed by nox** 2018-03-21 12:07 UTC
Labels: A-content/webgl, I-intermittent
