### ISSUE TITLE
Intermittent CRASH in /webgl/conformance-1.0.3/conformance/glsl/misc/shaders-with-mis-matching-uniforms.html

### ISSUE THREAD

**Issue by wafflespeanut** [servo/servo#17034] opened 2017-05-25 06:40 UTC
▶ CRASH [expected OK] /webgl/conformance-1.0.3/conformance/glsl/misc/shaders-with-mis-matching-uniforms.html
    │ 
    │ VMware, Inc.
    │ Gallium 0.4 on softpipe
    │ 3.3 (Core Profile) Mesa 12.0.1
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform float with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `float' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform float with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform int with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `int' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform int with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform vec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec2' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform vec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform ivec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec2' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform ivec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform bvec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec2' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform bvec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform vec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec3' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform vec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform ivec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec3' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform ivec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform bvec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec3' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform bvec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform vec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec4' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform vec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform ivec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec4' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform ivec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform bvec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec4' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform bvec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform mat2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat2' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform mat2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform mat3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat3' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform mat3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bool and fragment shader with uniform mat4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat4' and type `bool'
    │ 
    │ PASS vertex shader with uniform bool and fragment shader with uniform mat4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform int with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `int' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform int with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform vec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec2' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform vec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform ivec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec2' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform ivec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform bvec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec2' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform bvec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform vec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec3' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform vec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform ivec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec3' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform ivec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform bvec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec3' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform bvec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform vec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec4' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform vec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform ivec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec4' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform ivec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform bvec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec4' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform bvec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform mat2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat2' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform mat2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform mat3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat3' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform mat3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform float and fragment shader with uniform mat4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat4' and type `float'
    │ 
    │ PASS vertex shader with uniform float and fragment shader with uniform mat4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform vec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec2' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform vec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform ivec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec2' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform ivec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform bvec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec2' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform bvec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform vec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec3' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform vec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform ivec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec3' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform ivec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform bvec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec3' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform bvec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform vec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec4' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform vec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform ivec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec4' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform ivec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform bvec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec4' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform bvec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform mat2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat2' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform mat2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform mat3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat3' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform mat3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform int and fragment shader with uniform mat4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat4' and type `int'
    │ 
    │ PASS vertex shader with uniform int and fragment shader with uniform mat4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform ivec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec2' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform ivec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform bvec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec2' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform bvec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform vec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec3' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform vec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform ivec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec3' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform ivec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform bvec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec3' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform bvec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform vec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec4' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform vec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform ivec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec4' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform ivec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform bvec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec4' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform bvec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform mat2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat2' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform mat2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform mat3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat3' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform mat3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec2 and fragment shader with uniform mat4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat4' and type `vec2'
    │ 
    │ PASS vertex shader with uniform vec2 and fragment shader with uniform mat4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform ivec2 and fragment shader with uniform bvec2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec2' and type `ivec2'
    │ 
    │ PASS vertex shader with uniform ivec2 and fragment shader with uniform bvec2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform ivec2 and fragment shader with uniform vec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec3' and type `ivec2'
    │ 
    │ PASS vertex shader with uniform ivec2 and fragment shader with uniform vec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform ivec2 and fragment shader with uniform ivec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec3' and type `ivec2'
    │ 
    │ PASS vertex shader with uniform ivec2 and fragment shader with uniform ivec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform ivec2 and fragment shader with uniform bvec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec3' and type `ivec2'
    │ 
    │ PASS vertex shader with uniform ivec2 and fragment shader with uniform bvec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform ivec2 and fragment shader with uniform vec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec4' and type `ivec2'
    │ 
    │ PASS vertex shader with uniform ivec2 and fragment shader with uniform vec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform ivec2 and fragment shader with uniform ivec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec4' and type `ivec2'
    │ 
    │ PASS vertex shader with uniform ivec2 and fragment shader with uniform ivec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform ivec2 and fragment shader with uniform bvec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec4' and type `ivec2'
    │ 
    │ PASS vertex shader with uniform ivec2 and fragment shader with uniform bvec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform ivec2 and fragment shader with uniform mat2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat2' and type `ivec2'
    │ 
    │ PASS vertex shader with uniform ivec2 and fragment shader with uniform mat2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform ivec2 and fragment shader with uniform mat3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat3' and type `ivec2'
    │ 
    │ PASS vertex shader with uniform ivec2 and fragment shader with uniform mat3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform ivec2 and fragment shader with uniform mat4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat4' and type `ivec2'
    │ 
    │ PASS vertex shader with uniform ivec2 and fragment shader with uniform mat4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bvec2 and fragment shader with uniform vec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec3' and type `bvec2'
    │ 
    │ PASS vertex shader with uniform bvec2 and fragment shader with uniform vec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bvec2 and fragment shader with uniform ivec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec3' and type `bvec2'
    │ 
    │ PASS vertex shader with uniform bvec2 and fragment shader with uniform ivec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bvec2 and fragment shader with uniform bvec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec3' and type `bvec2'
    │ 
    │ PASS vertex shader with uniform bvec2 and fragment shader with uniform bvec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bvec2 and fragment shader with uniform vec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec4' and type `bvec2'
    │ 
    │ PASS vertex shader with uniform bvec2 and fragment shader with uniform vec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bvec2 and fragment shader with uniform ivec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec4' and type `bvec2'
    │ 
    │ PASS vertex shader with uniform bvec2 and fragment shader with uniform ivec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bvec2 and fragment shader with uniform bvec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec4' and type `bvec2'
    │ 
    │ PASS vertex shader with uniform bvec2 and fragment shader with uniform bvec4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bvec2 and fragment shader with uniform mat2 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat2' and type `bvec2'
    │ 
    │ PASS vertex shader with uniform bvec2 and fragment shader with uniform mat2 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bvec2 and fragment shader with uniform mat3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat3' and type `bvec2'
    │ 
    │ PASS vertex shader with uniform bvec2 and fragment shader with uniform mat3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform bvec2 and fragment shader with uniform mat4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `mat4' and type `bvec2'
    │ 
    │ PASS vertex shader with uniform bvec2 and fragment shader with uniform mat4 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec3 and fragment shader with uniform ivec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `ivec3' and type `vec3'
    │ 
    │ PASS vertex shader with uniform vec3 and fragment shader with uniform ivec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec3 and fragment shader with uniform bvec3 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `bvec3' and type `vec3'
    │ 
    │ PASS vertex shader with uniform vec3 and fragment shader with uniform bvec3 with the same name should fail to link
    │ 
    │ test: vertex shader with uniform vec3 and fragment shader with uniform vec4 with the same name should fail to link
    │ *** Error linking program '[object WebGLProgram]':error: uniform `u_uniform' declared as type `vec4' and type `vec3'
    │ 
    │ PASS vertex shader with uniform vec3 and fragment shader with uniform vec4 with the same name should fail to link
    │ already immutably borrowed (thread <unnamed>, at /home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/atomic_refcell-0.1.0/src/lib.rs:198)
    │ stack backtrace:
    │    0:     0x7fbb52afba9c - backtrace::backtrace::trace::haa53f4880ff627c6
    │    1:     0x7fbb52afbf62 - backtrace::capture::Backtrace::new::h5f3de869c0349b3d
    │    2:     0x7fbb51ae9335 - servo::main::{{closure}}::hc2262116bcc3d90c
    │    3:     0x7fbb53b5fa9a - std::panicking::rust_panic_with_hook
    │                         at /checkout/src/libstd/panicking.rs:550
    │    4:     0x7fbb53b5f8e4 - std::panicking::begin_panic<collections::string::String>
    │                         at /checkout/src/libstd/panicking.rs:511
    │    5:     0x7fbb53b5f869 - std::panicking::begin_panic_fmt
    │                         at /checkout/src/libstd/panicking.rs:495
    │    6:     0x7fbb51bf7a8c - <layout::construct::FlowConstructor<'a, ConcreteThreadSafeLayoutNode> as layout::traversal::PostorderNodeMutTraversal<ConcreteThreadSafeLayoutNode>>::process::hd72a7e088fd5762d
    │    7:     0x7fbb51c3b12b - style::traversal::DomTraversal::handle_postorder_traversal::h1766ed300209a11b
    │    8:     0x7fbb51c0c009 - std::panicking::try::do_call::h5e6c314a1363754a
    │    9:     0x7fbb53b66bba - panic_unwind::__rust_maybe_catch_panic
    │                         at /checkout/src/libpanic_unwind/lib.rs:98
    │   10:     0x7fbb51c5350e - <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::h2ee82a74c957c342
    │   11:     0x7fbb531f99f1 - rayon_core::registry::WorkerThread::wait_until::hb8bb0271392b3c70
    │   12:     0x7fbb531f54d1 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc42ae88fee5e8b73
    │   13:     0x7fbb531f5c7b - std::panicking::try::do_call::h0ae761b9e3a0cc1e
    │   14:     0x7fbb53b66bba - panic_unwind::__rust_maybe_catch_panic
    │                         at /checkout/src/libpanic_unwind/lib.rs:98
    │   15:     0x7fbb531f65f7 - <F as alloc::boxed::FnBox<A>>::call_box::h91b4e629ac890bb2
    │   16:     0x7fbb53b5e615 - alloc::boxed::{{impl}}::call_once<(),()>
    │                         at /checkout/src/liballoc/boxed.rs:658
    │                          - std::sys_common::thread::start_thread
    │                         at /checkout/src/libstd/sys_common/thread.rs:21
    │                          - std::sys::imp::thread::{{impl}}::new::thread_start
    │                         at /checkout/src/libstd/sys/unix/thread.rs:84
    │   17:     0x7fbb4f9fe183 - start_thread
    │   18:     0x7fbb4f515bec - clone
    │   19:                0x0 - <unknown>
    │ ERROR:servo: already immutably borrowed
    └ Pipeline failed in hard-fail mode.  Crashing!

**Comment by wafflespeanut** [comment] 2017-05-25 06:40
Occurred in #17021

**Comment by emilio** [comment] 2017-05-25 07:58
Dupe of #16982

**Closed by emilio** 2017-05-25 07:58 UTC
Labels: A-content/webgl, I-intermittent
