### ISSUE TITLE
Page view contents overflow in new-tab screen.

### ISSUE THREAD

**Issue by mason-larobina** [servo/servo#12115] opened 2016-07-01 19:05 UTC
When opening the tab-switcher view the page contents overflows at the top, bottom or both of the "zoomed out" current tab.

See attached photos.

![image](https://cloud.githubusercontent.com/assets/98076/16525523/cd8a49c6-3f7a-11e6-9381-2b47a8fc9a1d.png)

![image](https://cloud.githubusercontent.com/assets/98076/16525525/d201b890-3f7a-11e6-90b3-3a0495124ba1.png)

**Comment by ConnorGBrewster** [comment] 2016-07-01 19:07
Thank you for reporting this!
This is a dupe of #11957

**Closed by ConnorGBrewster** 2016-07-01 19:07 UTC
