### ISSUE TITLE
Id attributes should become global JS variables

### ISSUE THREAD

**Issue by pygy** [servo/servo#12853] opened 2016-08-13 21:14 UTC
I suppose the problem is well known, but I couldn't find an issue about it. Each `id` attribute defined on an element should create a JS global pointing to the element:

```HTML
<!doctype html>
<title>Id attribute should be available as JS globals</title>
<p id="foo">This should be replaced by the script below.<p>
<script>
if(typeof foo !== "undefined")
    foo.innerHTML="Sucessfully updated by setting <code>foo.innerHTML</code>."
</script>
```

[Live here](https://cdn.rawgit.com/pygy/servo-rendering-bugs/db4ef5bb3b8e7c37d7d2e79b113f6f62dbb0e488/id-attr-js-global.html)

**Comment by nox** [comment] 2016-08-13 21:18
Closing as duplicate of https://github.com/servo/servo/issues/8984, but thanks for filing the issue anyway!

**Closed by nox** 2016-08-13 21:18 UTC

**Comment by pygy** [comment] 2016-08-13 21:26
Great, I couldn't find it (lack of specialized vocabulary).

Good to know it is indeed on the radar.
