### ISSUE TITLE
Intermittent timeout of /WebCryptoAPI/import_export/rsa_importKey.worker

### ISSUE THREAD

**Issue by emilio** [servo/servo#13395] opened 2016-09-23 13:48 UTC
```
  ▶ TIMEOUT [expected OK] /WebCryptoAPI/import_export/rsa_importKey.worker
  │ 
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
  │ stack backtrace:
  │    0:        0x1048e245e - backtrace::backtrace::trace::h0e60ef08c7c34e9f
  │    1:        0x1048e274c - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
  │    2:        0x1034dc93c - servo::install_crash_handler::handler::h7801cf2e27f7ace0
  │    3:     0x7fff99b3df19 - _sigtramp
  │    4:        0x1042f40af - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleIP8JSObjectEENS2_6HandleIS5_E
  │    5:        0x1042d1a4d - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleINS2_5ValueEEENS2_6HandleIP8JSObjectE
  │    6:        0x1042b80a4 - _Z12JS_WrapValueP9JSContextN2JS13MutableHandleINS1_5ValueEEE
  │    7:        0x103987558 - std::panicking::try::do_call::h98edadb775d1f202
  │    8:        0x104dafc9a - __rust_maybe_catch_panic
  │    9:        0x103e2a957 - script::dom::bindings::codegen::Bindings::MessageEventBinding::MessageEventBinding::get_data::hda09a99032e4c842
  │   10:        0x103b54464 - script::dom::bindings::utils::generic_call::h7fc847546e37e590
  │   11:        0x1042230bd - 2js3jit18DoCallNativeGetterEP9JSContextN2JS6HandleIP10JSFunctionEENS4_IP8JSObjectEENS3_13MutableHandleINS3_5ValueEE
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
  │ stack backtrace:
  │    0:        0x1048e245e - backtrace::backtrace::trace::h0e60ef08c7c34e9f
  │    1:        0x1048e274c - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
  │    2:        0x1034dc93c - servo::install_crash_handler::handler::h7801cf2e27f7ace0
  │    3:     0x7fff99b3df19 - _sigtramp
  │    4:        0x1034dc9c0 - servo::install_crash_handler::handler::h7801cf2e27f7ace0
  │    5:     0x7fff99b3df19 - _sigtramp
  │    6:        0x1042f40af - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleIP8JSObjectEENS2_6HandleIS5_E
  │    7:        0x1042d1a4d - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleINS2_5ValueEEENS2_6HandleIP8JSObjectE
  │    8:        0x1042b80a4 - _Z12JS_WrapValueP9JSContextN2JS13MutableHandleINS1_5ValueEEE
  │    9:        0x103987558 - std::panicking::try::do_call::h98edadb775d1f202
  │   10:        0x104dafc9a - __rust_maybe_catch_panic
  │   11:        0x103e2a957 - script::dom::bindings::codegen::Bindings::MessageEventBinding::MessageEventBinding::get_data::hda09a99032e4c842
  │   12:        0x103b54464 - script::dom::bindings::utils::generic_call::h7fc847546e37e590
  └   13:        0x1042230bd - 2js3jit18DoCallNativeGetterEP9JSContextN2JS6HandleIP10JSFunctionEENS4_IP8JSObjectEENS3_13MutableHandleINS3_5ValueEE
```

**Comment by jdm** [comment] 2016-09-23 13:49
Dupe of #send-usp.

**Closed by jdm** 2016-09-23 13:49 UTC
Labels: I-intermittent
