### ISSUE TITLE
Store a map of eTLDs to script tasks in the constellation

### ISSUE THREAD

**Issue by jdm** [servo/servo#5322] opened 2015-03-23 03:22 UTC
This will allow us to avoid spawning a new script task per cross-origin iframe if the iframes share the same eTLD.

Blocks #5236.

**Comment by jdm** [comment] 2015-03-23 03:25
This requires making decisions about what happens when navigating a browsing context to a new origin for which there is an existing script task. The current script task code only understands a single root page; if there's no relationship between new newly-navigated context and the existing root page, it could get ugly.

**Comment by asajeffrey** [comment] 2016-09-28 11:59
Dupe of #633? I think we want eTLD+1, not eTLD.

**Comment by asajeffrey** [comment] 2016-12-01 16:14
Closed by #14211.

**Closed by asajeffrey** 2016-12-01 16:14 UTC
Labels: A-constellation
