### ISSUE TITLE
libcrypto and libssl on Fedora 24 do not contain the right stuff.

### ISSUE THREAD

**Issue by pblahman** [servo/servo#12138] opened 2016-07-01 22:21 UTC
First problem was there were not symbolic links for the required librarires.
After "fixing/creating" symbolic links, the contents of libssl and libcrypto do not satisfy the requirements of "servo".
This is on Fedora 24.

[plahman@localhost servo]$ ldd ./servo
./servo: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)
./servo: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.1d' not found (required by ./servo)
./servo: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)
        linux-vdso.so.1 (0x00007ffc29976000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f77978cd000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f77976b7000)
        libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f7797466000)
        libEGL.so.1 => /lib64/libEGL.so.1 (0x00007f7797235000)
        libGL.so.1 => /lib64/libGL.so.1 (0x00007f7796fc5000)
        libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f7796d15000)
        libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f7796ae9000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007f77967a9000)
        libXmu.so.6 => /lib64/libXmu.so.6 (0x00007f779658e000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f779638a000)
        libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007f7796118000)
        libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007f7795cb7000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7795a9b000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7795884000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f77954c1000)
        /lib64/ld-linux-x86-64.so.2 (0x000055c777aca000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f77951b7000)
        libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f779512d000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f7794f05000)
        libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007f7794d03000)
        libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00007f7794afe000)
        libxcb-dri3.so.0 => /lib64/libxcb-dri3.so.0 (0x00007f77948fa000)
        libxcb-present.so.0 => /lib64/libxcb-present.so.0 (0x00007f77946f7000)
        libxcb-randr.so.0 => /lib64/libxcb-randr.so.0 (0x00007f77944e9000)
        libxcb-xfixes.so.0 => /lib64/libxcb-xfixes.so.0 (0x00007f77942e0000)
        libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f77940d6000)
        libxcb-shape.so.0 => /lib64/libxcb-shape.so.0 (0x00007f7793ed2000)
        libxcb-sync.so.1 => /lib64/libxcb-sync.so.1 (0x00007f7793cca000)
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f7793aa8000)
        libxshmfence.so.1 => /lib64/libxshmfence.so.1 (0x00007f77938a5000)
        libgbm.so.1 => /lib64/libgbm.so.1 (0x00007f7793696000)
        libwayland-client.so.0 => /lib64/libwayland-client.so.0 (0x00007f7793487000)
        libwayland-server.so.0 => /lib64/libwayland-server.so.0 (0x00007f7793275000)
        libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f7793065000)
        libglapi.so.0 => /lib64/libglapi.so.0 (0x00007f7792e36000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007f7792c24000)
        libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f7792a20000)
        libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f779281a000)
        libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00007f7792601000)
        libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007f77923fa000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f77921ea000)
        libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f7791fb7000)
        libXt.so.6 => /lib64/libXt.so.6 (0x00007f7791d4e000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f7791b01000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f779181b000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f7791616000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f77913e5000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007f77911df000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f7790fd7000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f7790dbd000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f7790b96000)
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f7790984000)
        libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f779069e000)
        libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f7790487000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f7790214000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007f779000f000)
        libffi.so.6 => /lib64/libffi.so.6 (0x00007f778fe07000)
        libSM.so.6 => /lib64/libSM.so.6 (0x00007f778fbff000)
        libICE.so.6 => /lib64/libICE.so.6 (0x00007f778f9e2000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f778f7d3000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f778f5cf000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007f778f3c9000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f778f1c4000)

**Comment by moosingin3space** [comment] 2016-07-01 22:23
I'm working on making this easier for Fedora users: https://github.com/servo/servo/issues/12102

**Comment by lhirlimann** [comment] 2016-07-02 13:51
this is a dup of 12015

**Comment by est31** [comment] 2016-07-02 14:45
It appears that fedora has a custom soname: https://bugzilla.redhat.com/show_bug.cgi?id=1277662

Godotengine has solved this by statically linking to openssl, even though they knew its not the perfect solution: https://github.com/godotengine/godot/issues/1391

**Comment by jdm** [comment] 2016-07-02 14:59
Duplicate of #12015. Thanks for reporting it!

**Closed by jdm** 2016-07-02 14:59 UTC
