### ISSUE TITLE
Error navigating with Cmd+Right arrow on OS X

### ISSUE THREAD

**Issue by ituxbag** [servo/servo#10266] opened 2016-03-29 12:28 UTC
I have built Servo with `./mach build --release` and then I launched it with `./mach run http://www.google.com` or `./mach run http://en.wikipedia.org`. Now I have clicked on "Access" blue button; when I have pressed the Cmd+Right Arrow
on keyboard, I obtained the following trace:

```
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: base_time >= self.timers.borrow().last().unwrap().scheduled_for', /Users/alessio/Progetti/MozillaWorld/servo-devel/components/script/timers.rs:181
stack backtrace:
   1:        0x10b99fd58 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10b9a3949 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10b9a3578 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10b98e946 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10a4e8114 - sys_common::unwind::begin_unwind::h13117301780999423901
   6:        0x10a64f5c2 - dom::window::Window::handle_fire_timer::hc54f803c12a61caeRto
   7:        0x10a82c771 - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.189207
   8:        0x10a8147be - script_thread::ScriptThread::handle_msgs::hf61b73c37e8e2d97Xot
   9:        0x10a7ad597 - sys_common::unwind::try::try_fn::h8420823865318125002
  10:        0x10b99f08b - __rust_try
  11:        0x10b99f013 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  12:        0x10a7ae8ba - boxed::F.FnBox<A>::call_box::h5430537875394858041
  13:        0x10b9a2a2c - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  14:     0x7fff84f2e99c - _pthread_body
  15:     0x7fff84f2e919 - _pthread_start
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:704
stack backtrace:
   1:        0x10b99fd58 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10b9a3949 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10b9a3578 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10b98e946 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10b98f97e - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10b99f0f7 - rust_begin_unwind
   7:        0x10b9c9550 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10b9d4835 - option::expect_failed::h56e104933d0889c7LpO
   9:        0x10a0662ce - constellation::Constellation<LTF, STF>::handle_failure_msg::h16931619530555521487
  10:        0x109fcb963 - constellation::Constellation<LTF, STF>::handle_request::h2173909658852473369
  11:        0x109fc057b - sys_common::unwind::try::try_fn::h13037996831348070589
  12:        0x10b99f08b - __rust_try
  13:        0x10b99f013 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  14:        0x109fc1931 - boxed::F.FnBox<A>::call_box::h13368149504822482069
  15:        0x10b9a2a2c - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  16:     0x7fff84f2e99c - _pthread_body
  17:     0x7fff84f2e919 - _pthread_start
thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10b99fd58 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10b9a3949 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10b9a3578 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10b98e946 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10b98f97e - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10b99f0f7 - rust_begin_unwind
   7:        0x10b9c9550 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10aaa80b7 - result::unwrap_failed::h4225072807612363996
   9:        0x10aac4b43 - sys_common::unwind::try::try_fn::h8225116906192781313
  10:        0x10b99f08b - __rust_try
  11:        0x10b99f013 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  12:        0x10aac533a - boxed::F.FnBox<A>::call_box::h8755228072363361320
  13:        0x10b9a2a2c - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  14:     0x7fff84f2e99c - _pthread_body
  15:     0x7fff84f2e919 - _pthread_start
thread '<main>' panicked at 'Compositor layer has an unknown pipeline (PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }).', /Users/alessio/Progetti/MozillaWorld/servo-devel/components/compositing/compositor.rs:749
stack backtrace:
   1:        0x10b99fd58 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10b9a3949 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10b9a3578 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10b98e946 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10b98f97e - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x109f4b7e4 - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h10973819332117505010
   7:        0x109f81aa7 - Browser::handle_events::h8ffba38588a67506tea
   8:        0x109f35f75 - main::h9cc0aa5bb4f2f2aeqaa
   9:        0x10b9a3182 - sys_common::unwind::try::try_fn::h13791246699442426615
  10:        0x10b99f08b - __rust_try
  11:        0x10b9a3040 - rt::lang_start::h32ace63a1577ce666rz
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10b99fd58 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10b9a3949 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10b9a3578 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10b98e946 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10b98f97e - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10b99f0f7 - rust_begin_unwind
   7:        0x10b9c9550 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10a0d9165 - result::unwrap_failed::h1838923861604296214
   9:        0x10a0ff5ce - layout_thread::LayoutThread::handle_request::h156bd6bdc3429ce6mbr
  10:        0x10a0b2dda - sys_common::unwind::try::try_fn::h17849909425148360526
  11:        0x10b99f08b - __rust_try
  12:        0x10b99f013 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  13:        0x10a0b3a51 - boxed::F.FnBox<A>::call_box::h10523919007044264683
  14:        0x10b9a2a2c - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  15:     0x7fff84f2e99c - _pthread_body
  16:     0x7fff84f2e919 - _pthread_start
thread 'thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }LayoutWorker worker 1/6' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread 'called `Result::unwrap()` on an `Err` value: RecvErrorthread 'LayoutWorker worker 4/6', ', LayoutWorker worker 5/6thread '' panicked at '' panicked at 'LayoutWorker worker 3/6../src/libcore/result.rs../src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError', ::' panicked at '', 746746../src/libcore/result.rs
../src/libcore/result.rs:stack backtrace:

746:called `Result::unwrap()` on an `Err` value: RecvError
746', 
../src/libcore/result.rs:746
thread 'LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread '', LayoutWorker worker 6/6../src/libcore/result.rs' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError:', 746../src/libcore/result.rs
:746
   1:        0x10b99fd58 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10b9a3949 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10b9a3578 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10b98e946 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10b98f97e - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10b99f0f7 - rust_begin_unwind
   7:        0x10b9c9550 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
Servo exited with return value 101
```

**Comment by jrasanen** [comment] 2016-03-29 12:35
Same as #9984 I think.

**Comment by jrasanen** [comment] 2016-03-29 12:43
Steps:
1. Open Wikipedia
2. Click on a link
3. cmd left arrow to go back.
4. cmd right arrow to go forwards

Result
```
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(4) }' panicked at 'assertion failed: base_time >= self.timers.borrow().last().unwrap().scheduled_for', /Users/jrasanen/Development/servo/components/script/timers.rs:181
stack backtrace:
   1:        0x10c8341d8 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10c837dc9 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10c8379f8 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10c822fd6 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x109f9df57 - sys_common::unwind::begin_unwind::h8398817552005515669
   6:        0x10a94dee2 - timers::OneshotTimers::fire_timer::h16885337415131578052
   7:        0x10a94d945 - dom::window::Window::handle_fire_timer::h87679558f5489908Kso
   8:        0x10aa6d11b - script_thread::ScriptThread::handle_timer_event::had709de57aff427eyBt
   9:        0x10aa6b00b - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.184434
  10:        0x10aa6ab95 - script_thread::ScriptThread::profile_event::h10237933681040494003
  11:        0x10aa3de7e - script_thread::ScriptThread::handle_msgs::h33b2052e66423d77fmt
  12:        0x10a9e74dc - script_thread::ScriptThread::start::h38d48c5e0f4418095lt
  13:        0x10a9e7494 - script_thread::ScriptThread.ScriptThreadFactory::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::closure.183247
  14:        0x10a9e71ec - mem::ProfilerChan::run_with_memory_reporting::h2139071115922930043
  15:        0x10a9d2626 - script_thread::ScriptThread.ScriptThreadFactory::create::_$u7b$$u7b$closure$u7d$$u7d$::closure.182672
  16:        0x10a9d1b87 - util::thread::spawn_named_with_send_on_failure::_$u7b$$u7b$closure$u7d$$u7d$::closure.182659
  17:        0x10a9d1573 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::closure.182648
  18:        0x10a9d14e8 - sys_common::unwind::try::try_fn::h16812424202301723505
  19:        0x10c83350b - __rust_try
  20:        0x10c833493 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  21:        0x10a9d1425 - sys_common::unwind::try::h1848256345259130331
  22:        0x10a9d125e - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::closure.182645
  23:        0x10a9d1da7 - boxed::F.FnBox<A>::call_box::h12713784522260058039
  24:        0x10c836eac - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  25:     0x7fff948de99c - _pthread_body
  26:     0x7fff948de919 - _pthread_start
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:704
stack backtrace:
   1:        0x10c8341d8 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10c837dc9 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10c8379f8 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10c822fd6 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10c823e6e - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10c833577 - rust_begin_unwind
   7:        0x10c85d0b0 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10c864945 - option::expect_failed::h56e104933d0889c7LpO
   9:        0x1099cabff - option::Option<T>::expect::h617314328958622075
  10:        0x109a98734 - constellation::Constellation<LTF, STF>::handle_failure_msg::h8276250153926025702
  11:        0x109949a31 - constellation::Constellation<LTF, STF>::handle_request::h860029324140948878
  12:        0x109940c05 - constellation::Constellation<LTF, STF>::run::h11205822353465524815
  13:        0x10993249d - compositing::constellation::Constellation<LTF, STF>::start::_$u7b$$u7b$closure$u7d$$u7d$::closure.25614
  14:        0x109930d33 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::closure.25603
  15:        0x109930ca8 - sys_common::unwind::try::try_fn::h6161582336292024202
  16:        0x10c83350b - __rust_try
  17:        0x10c833493 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  18:        0x109930be5 - sys_common::unwind::try::h14375118853156895561
  19:        0x109930a1e - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::closure.25581
  20:        0x109932777 - boxed::F.FnBox<A>::call_box::h17880365515976086065
  21:        0x10c836eac - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  22:     0x7fff948de99c - _pthread_body
  23:     0x7fff948de919 - _pthread_start
thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(4) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }', ../src/libcore/result.rs:746
stack backtrace:
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
   1:        0x10c8341d8 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10c837dc9 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10c8379f8 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10c822fd6 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10c823e6e - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10c833577 - rust_begin_unwind
   7:        0x10c85d0b0 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x10b00af57 - result::unwrap_failed::h6066850057366948056
   9:        0x10b038701 - result::Result<T, E>::unwrap::h7692040744230175096
  10:        0x10b09ad5e - gfx::paint_thread::PaintThread<C>::create::_$u7b$$u7b$closure$u7d$$u7d$::closure.36248
  11:        0x10b09a077 - util::thread::spawn_named_with_send_on_failure::_$u7b$$u7b$closure$u7d$$u7d$::closure.36233
  12:        0x10b099a63 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::closure.36222
  13:        0x10b0999d8 - sys_common::unwind::try::try_fn::h9774001906260422929
  14:        0x10c83350b - __rust_try
  15:        0x10c833493 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  16:        0x10b099915 - sys_common::unwind::try::h16401411146662214144
  17:        0x10b09974e - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::closure.36219
  18:        0x10b09a297 - boxed::F.FnBox<A>::call_box::h6032314815111536333
  19:        0x10c836eac - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  20:     0x7fff948de99c - _pthread_body
  21:     0x7fff948de919 - _pthread_start
stack backtrace:
   1:        0x10c8341d8 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10c837dc9 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10c8379f8 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x10c822fd6 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x10c823e6e - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x10c833577 - rust_begin_unwind
   7:        0x10c85d0b0 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x109866db8 - result::unwrap_failed::h10090993388481181680
   9:        0x109866b70 - result::Result<T, E>::unwrap::h9556801202217394361
  10:        0x10985aff9 - compositor::IOCompositor<Window>::send_buffer_requests_for_all_layers::h6791940029197738763
  11:        0x1097efd86 - compositor::IOCompositor<Window>::handle_browser_message::h2540311901428396695
  12:        0x1097ed652 - compositor::IOCompositor<Window>.CompositorEventListener::handle_events::h7362132974127140435
  13:        0x1098ba889 - Browser::handle_events::h7247c3145440718dWea
  14:        0x1097a287d - main::h816805d8d509cd3eMaa
  15:        0x10c837602 - sys_common::unwind::try::try_fn::h13791246699442426615
  16:        0x10c83350b - __rust_try
  17:        0x10c8374c0 - rt::lang_start::h32ace63a1577ce666rz
  18:        0x1098aded9 - main
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
stack backtrace:
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(3) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
Servo exited with return value 101
```

**Comment by jdm** [comment] 2016-03-29 15:37
Looks like a duplicate of #9984. Thanks!

**Closed by jdm** 2016-03-29 15:37 UTC
