### ISSUE TITLE
browserhtml starting link images clickable areas wrong

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#13039] opened 2016-08-25 17:16 UTC
Currently, if you open browserhtml on a recent build and try to click the:

![screen shot 2016-08-25 at 9 41 05 am](https://cloud.githubusercontent.com/assets/547158/17978736/48b7db02-6aac-11e6-9d65-487a517e3ea7.png)

Logo a few things might happen:

* In some areas, you aren't allowed to click at all.
* In other areas, if you click, it loads Demo: Moire

In playing around with this it seems like the clickable regions are offset from the images.  By clicking above the Github logo I can load Github.  Roughly in this region:

![screen shot 2016-08-25 at 10 13 11 am](https://cloud.githubusercontent.com/assets/547158/17978829/b5a1e294-6aac-11e6-9b61-00d48feee461.png)

I'm on Mac OS X 10.11.6 on a Regina Macbook Pro displaying on an external display at (I believe) 1920x1200.

**Comment by KiChjang** [comment] 2016-08-25 17:36
I _think_ this is a duplicate of an issue opened before, but I'm not sure.

cc @emilio

**Comment by KiChjang** [comment] 2016-08-25 17:43
Looks like #12841 fixes the issue, but was never landed for some strange reason...

**Comment by emilio** [comment] 2016-08-25 18:37
Yes, that's fixed by #12841, sorry for not landing it before, it silently bitrotted without any message from the bots.

Closing as a dupe of #12833, but thanks for reporting it! The PR fixing it should land relatively soon :-)

**Closed by emilio** 2016-08-25 18:37 UTC
