### ISSUE TITLE
assertion failed: self.get_pending_parsing_blocking_script().is_none() || script.is_none()

### ISSUE THREAD

**Issue by nc4rrillo** [servo/servo#12282] opened 2016-07-05 23:52 UTC
assertion failed: self.get_pending_parsing_blocking_script().is_none() || script.is_none()
### URL:
http://andy.edinborough.org/CSS-Stress-Testing-and-Performance-Profiling
### Backtrace:
```
frame #0  - 0x000055ae3aff561d - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x000055ae3aff55a5 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000055ae39ffff29 - _<F as alloc..boxed..FnBox<A>>::call_box::hc555946005547ceb
frame #3  - 0x000055ae3ac5a3a8 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
frame #4  - 0x000055ae3aff8d3c - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000055ae398484cf - std::panicking::begin_panic::h0bf39f6d43ab9349
frame #6  - 0x000055ae39df4f55 - script::dom::document::Document::set_pending_parsing_blocking_script::hc2c8a54781f59f51
frame #7  - 0x000055ae39ed8adb - script::dom::htmlscriptelement::HTMLScriptElement::prepare::h351ecd27bde7dc40
frame #8  - 0x000055ae39f46f22 - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tree_builder..rules..TreeBuilderStep>::step::hdeb03b029754e999
frame #9  - 0x000055ae39f37263 - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tokenizer..interface..TokenSink>::process_token::hdb6ec07962100a38
frame #10 - 0x000055ae39f3669e - _<html5ever..tokenizer..Tokenizer<Sink>>::process_token::headd911ae33b8a21
frame #11 - 0x000055ae39f73221 - _<html5ever..tokenizer..Tokenizer<Sink>>::emit_current_tag::heb27f7c2b4f75604
frame #12 - 0x000055ae39f6f0c6 - _<html5ever..tokenizer..Tokenizer<Sink>>::step::h99e7351926252628
frame #13 - 0x000055ae39f61bd7 - _<html5ever..tokenizer..Tokenizer<Sink>>::run::h0e962803c394bd47
frame #14 - 0x000055ae39f3273e - script::dom::servohtmlparser::ServoHTMLParser::parse_sync::hfb335285b73db873
frame #15 - 0x000055ae39864d44 - script::dom::document::Document::finish_load::hea8fb9e3713be828
frame #16 - 0x000055ae39ed6804 - _<script..dom..htmlscriptelement..ScriptContext as net_traits..AsyncResponseListener>::response_complete::h0e0b6fc362fa31af
frame #17 - 0x000055ae39edc3fb - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::hd477eff96e1baf2c
frame #18 - 0x000055ae3a00ae74 - script::script_thread::ScriptThread::handle_msg_from_script::hfac8a5d67415fa31
frame #19 - 0x000055ae3a05c4bf - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hcc3e5fcf08d42e0c
frame #20 - 0x000055ae3a0436a7 - script::script_thread::ScriptThread::handle_msgs::hf9fbf9949e23273b
frame #21 - 0x000055ae39ffe617 - std::panicking::try::call::h99112171a9854ab3
frame #22 - 0x000055ae3b01cccb - __rust_try
frame #23 - 0x000055ae3b01cc6e - __rust_maybe_catch_panic
frame #24 - 0x000055ae39fff88d - _<F as alloc..boxed..FnBox<A>>::call_box::h4410a344b31b72da
frame #25 - 0x000055ae3b010c94 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #26 - 0x00007fca8210a6f9 - start_thread
frame #27 - 0x00007fca81c2ab5c - clone
frame #28 - 0x0000000000000000 - <unknown>

```

**Comment by jdm** [comment] 2016-07-06 03:50
Duplicate of #11733. Thanks for reporting it!

**Closed by jdm** 2016-07-06 03:50 UTC
