### ISSUE TITLE
style/gfx/metrics/script crates serialize build

### ISSUE THREAD

**Issue by jdm** [servo/servo#19422] opened 2017-11-29 15:19 UTC
script depends on metrics, and metrics depends on gfx, and gfx depends on style (script also depends on style). If we move the bits of style that gfx depends upon into style_traits, and possibly the bits of gfx that metrics depends upon into gfx_traits, this should allow more crates to build in parallel.

**Comment by tigercosmos** [comment] 2017-12-01 16:14
The one need to move it one by one or finish it in one time?

**Comment by jdm** [comment] 2017-12-01 16:50
Moving one by one shouldn't hurt anything.

**Comment by tigercosmos** [comment] 2017-12-01 16:52
OK! I will work on this.

**Comment by tigercosmos** [comment] 2017-12-02 05:14
@jdm if some codes in `style` that `gfx` depends is also used by other crate(i.g. `layout`), shall I move it? Or just move codes only depended by `gfx`?

**Comment by tigercosmos** [comment] 2017-12-02 05:20
ummm... I think they should all be moved, otherwise `gfx` still need to wait for `style`

**Comment by jdm** [comment] 2017-12-02 05:51
Exactly. If it's moved from gfx to gfx_traits, the other crates that depend on the move items should be updated to use gfx_traits.

**Comment by tigercosmos** [comment] 2017-12-02 07:21
This issue is much harder than I though before. Actually almost everything depend on each other.

For example, If I want to move `gfx::display_list`, which is used by `metrics` and also the only one `gfx` dependency in `metrics`, since `gfx::display_list` use `gfx::text`, I will also need to move `gfx::text`, and `gfx::text` use lot of `gfx` things, which mean if I want to move `display_list`, I will move almost everything in `gfx`.

So, in this case, we can make sure move more something from `gfx` to `gfx_traits` is impossible.
In fact, I found `style` has the same problem. :(

**Comment by jdm** [comment] 2017-12-02 07:47
Try creating a trait that can replace https://dxr.mozilla.org/servo/source/components/metrics/lib.rs#306-315. That trait can live in gfx_traits, and the implementation in gfx.

**Comment by tigercosmos** [comment] 2017-12-02 16:46
I don't understand. If we move that code to `gfx_traits`.
The relationship would be `metrics` -> `gfx_traits` -> `gfx`.
Do I misunderstand?

**Comment by tigercosmos** [comment] 2017-12-02 17:05
I don't understand. If we move that code to `gfx_traits`.
The relationship would be `metrics` -> `gfx_traits` -> `gfx`.
I thought crate_traits will be independent with crate. Do I misunderstand?

**Comment by jdm** [comment] 2017-12-02 18:22
No, because metrics would depend on gfx_traits, and gfx would depend on gfx_traits.

**Comment by tigercosmos** [comment] 2017-12-02 18:26
That code use `display_list`. But `display_list` is under `gfx`? If we move that code to traits, it still need to call `gfx`?

**Comment by jdm** [comment] 2017-12-02 23:04
The code in metrics is calculating a boolean value using the display list types from gfx. The types do not need to move - we can create a trait in gfx_traits that encapsulates the calculation in a method, and implement the trait on the types in gfx. The code in metrics only needs to refer to the trait.

**Comment by tigercosmos** [comment] 2017-12-19 00:05
@KiChjang NO. I can't handle this. I didn't understand how to do.
If someone is interested in this, feel free to take it. :)

**Comment by streichgeorg** [comment] 2018-01-12 15:23
I'd like to take a shot at this then.

**Comment by jdm** [comment] 2018-01-12 15:42
Please do!

**Comment by streichgeorg** [comment] 2018-01-12 19:39
I opened a pull request for the gfx-metrics part. But style-gfx seems a lot harder because there is non zero amount of metaprogramming in the style crate and I would be really happy about some pointers what's going on there. gfx depends mainly on font_weight and some other font related structs, but I don't really get where they get declared at the moment.

**Comment by jdm** [comment] 2018-01-12 21:09
The various mako.rs files under style/properties/ are Python Mako templates that generate Rust code. font_weight is defined in style/properties/longhand/font.mako.rs, and it invokes Python code from style/properties/helpers.mako.rs. However, it may be possible to modify the imports from gfx to directly import `style::values::computed::font::FontWeight`, for example. If that's the case, then it should be possible to extract those types into style_traits and use `pub use style_traits::whatever::FontWeight;` where they were originally defined.

**Comment by streichgeorg** [comment] 2018-01-22 17:14
I'm working on removing the style dependency from gfx, but am currently stuck fighting the rust compiler. The problem is that `style::computed_values::font_weight::T` has some static methods that gfx needs. But when I create a trait that has static methods it's no longer object safe and cannot be passed around anymore, not even in a `Box`, as I understand it. Is there a nice solution to this.

**Comment by jdm** [comment] 2018-01-23 22:04
Here is what I propose:
* move the [definition](https://github.com/streichgeorg/servo/blob/cfcbe39e44e6d8aeae75b1e8c39254ab3dfcd3dc/components/style/values/computed/font.rs#L40) of FontWeight and its [methods](https://github.com/streichgeorg/servo/blob/cfcbe39e44e6d8aeae75b1e8c39254ab3dfcd3dc/components/style/values/computed/font.rs#L97-L150) into style_traits
* add a `pub use style_traits::FontWeight;` line in `components/style/values/computed/font.rs`

There should be no need to mess with traits for that change; the code in gfx can use the type defined in style_traits directly, and style will continue to use the same type implicitly by reexporting it with the same name in its old location.

**Comment by streichgeorg** [comment] 2018-01-23 22:11
Oh I see, style_traits isn't really all about traits.
Thank you for the help.

**Comment by SimonSapin** [comment] 2018-01-23 22:18
(Renaming those `*_traits` crates might be another easy issue, once we decide what to name them instead :))

**Comment by KiChjang** [comment] 2018-01-25 10:34
Reopening since this seems to not have been solved yet.

**Comment by atouchet** [comment] 2020-04-20 23:03
#19934 was an unfinished PR to address this.

**Comment by SimonSapin** [comment] 2020-04-21 08:36
> the bits of gfx that metrics depends upon into gfx_traits

This was done at some point, meaning that the only intermediate dependency between `style` and `script` is now `script_layout_interface`, which only takes ~6 seconds to compile in release mode on our macOS CI (the slowest):

https://community-tc.services.mozilla.com/tasks/BCyqIQNdTNmcrj7kFW58Ww/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FBCyqIQNdTNmcrj7kFW58Ww%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L2006

![image](https://user-images.githubusercontent.com/291359/79844191-a2b33d00-83bb-11ea-9023-c392c5a35c87.png)

The above is a screenshot of `xdot` with the mouse hovering `style` in order to color the edges connected to it. The graph is of `script` and its recursive `path` dependencies, generated with:

```python
#!/usr/bin/env python3

import json
import os
import subprocess
import sys


def main(crate=None):
    os.chdir(os.path.join(os.path.dirname(__file__), ".."))
    meta = json.loads(subprocess.check_output(["cargo", "metadata", "--format-version", "1"]))
    graph = {}
    for package in meta["packages"]:
        if package["source"] is None: # Lives in this repo
            for dependency in package["dependencies"]:
                if dependency["source"] is None: # Also lives in this repo
                    graph.setdefault(package["name"], []).append(dependency["name"])

    if crate:
        filtered = {}
        seen = set()
        def traverse(name):
            if name not in seen:
                seen.add(name)
                for dependency in graph.get(name, []):
                    filtered.setdefault(name, []).append(dependency)
                    traverse(dependency)
        traverse(crate)
    else:
        filtered = graph
    print("// This is in Graphviz DOT format.")
    print("// Use the 'dot' or 'xdot' tool to visualize.")
    print('digraph "local crates" {')
    for package, dependencies in filtered.items():
        for dependency in dependencies:
            print('  "%s" -> "%s";' % (package, dependency))
    print("}")


if __name__ == "__main__":
    sys.exit(main(*sys.argv[1:]))
```

This feels good enough for me, so closing.

**Closed** 2020-04-21 08:50 UTC
Labels: A-build, I-perf-slow
