### ISSUE TITLE
Initial pull of  git skia fails

### ISSUE THREAD

**Issue by benbucksch** [servo/servo#6132] opened 2015-05-19 09:22 UTC
First time I try to build Servo

$ time nice ./mach build -j4 --release --verbose
    Updating git repository `https://github.com/servo/gleam`
    Updating git repository `https://github.com/servo/rust-x11-clipboard`
    Updating git repository `https://github.com/servo/rust-freetype`
    Updating git repository `https://github.com/servo/rust-egl`
    Updating git repository `https://github.com/servo/skia`
Unable to update https://github.com/servo/skia#d60e6753
Caused by:
  failed to fetch into .../servo/.cargo/git/db/skia-c7a55308e929f530
Caused by:
  [12] Timeout was reached
Build completed in 62.69s

This is reproducible, the fetch fails every time after about roughly 40 seconds. I tried maybe 6 times.
I had no problems fetching other large git repos like rust. I tried on 2 different days (yesterday and today).

**Comment by mattias-ostergren** [comment] 2015-05-19 11:06
I think I have this problem too?

 ./mach build --verbose
    Updating git repository `https://github.com/servo/skia`
Unable to update https://github.com/servo/skia#d60e6753

Caused by:
  failed to fetch into /home/.../servo/.cargo/git/db/skia-c7a55308e929f530

Caused by:
  [12] Timeout was reached
Build completed in 61.33s

(I'm have struggled somewhat with my setup - Ubuntu on Virtualbox behind corporate Firewall - but I am quite sure I have setup my installation properly since I can successfully update other gits. It's just stuck on skia.)

**Comment by glennw** [comment] 2015-05-19 11:10
Searching for the phrase "Timeout was reached" in cargo turns up https://github.com/rust-lang/cargo/issues/1254 and https://github.com/rust-lang/cargo/issues/1087. Not sure if they are relevant but they seem to be related to network conditions and / or proxy / firewall configurations.

**Comment by mattias-ostergren** [comment] 2015-05-19 11:22
I'm not sure what the problem is (in my case). FYI - on my system I performed the following tests (as suggested in above issues):

curl -OL https://crates.io/api/v1/crates/libc/0.1.1/download ran OK in 3 seconds.
wget https://crates.io/api/v1/crates/libgit2-sys/0.1.3/download finished in 9.8 seconds.

**Comment by benbucksch** [comment] 2015-05-19 21:44
Glenn, network problems with the firewall seem unlikely, because the other repos fetch fine, from the very same host https://github.com. Other large repos like rust (300 MB) cloned fine as well (manually, not part of the script).
I'm using a HTTP proxy. For testing, I've disabled that (export http_proxy="" && export https_proxy="") and re-ran. Same issue. Deleted .cargo/git/ and re-ran. Same issue.

**Comment by mattias-ostergren** [comment] 2015-05-20 06:49
Wohoo! After setting the HTTP timeout  to approx 1 hour (by modifying /components/servo/.cargo") I managed to download skia. 
(See issue 1087 as mentioned above).
:-)

However...

Then it failed at a later stage... to be continued... :-/

./mach build --verbose
    Updating git repository `https://github.com/servo/skia`
    Updating git repository `https://github.com/servo/libfreetype2`
    Updating git repository `https://github.com/servo/libexpat`
    Updating git repository `https://github.com/servo/libfontconfig`
    Updating git repository `https://github.com/ecoal95/rust-offscreen-rendering-context`
    Updating git repository `https://github.com/servo/mozjs`
    Updating git repository `https://github.com/reem/rust-mac`
    Updating git repository `https://github.com/servo/glutin`
    Updating git repository `https://github.com/jgraham/webdriver-rust.git`
 Downloading libc v0.1.6
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.6` from https://crates.io/api/v1/crates/libc/0.1.6/download

Caused by:
  Failure when receiving data from the peer

**Comment by benbucksch** [comment] 2015-05-20 11:13
Matthias, could you please tell me again what exactly you modified where?
For me, components/servo/.cargo/ is a directory, with config as the only file in there, and that file has no timeout written in it. Actually, it only android stuff in there.

servo$ ls -la components/servo/.cargo/
-rw-rw-r-- 1 ben ben 184 Mai 16 14:20 config

$ cat components/servo/.cargo/config 
paths = ["../../support/android-rs-glue"]

[target.arm-linux-androideabi]
linker = "../../support/android-rs-glue/apk-builder/target/debug/apk-builder"
ar = "arm-linux-androideabi-ar"

**Comment by mattias-ostergren** [comment] 2015-05-20 12:08
Sorry for being unclear. Updated my previous comment to correct path to config file.
Here is the rows I added. 

[http]
proxy = "http://...<myproxy>.../"
timeout = 3600000
[https]
proxy = "http://...<myproxy>.../"
timeout = 3600000

**Comment by SimonSapin** [comment] 2015-12-04 07:34
Hopefully this is fixed by #8757!

**Closed by SimonSapin** 2015-12-04 07:34 UTC
