### ISSUE TITLE
assertion failed: count_cell.get() > 0

### ISSUE THREAD

**Issue by tupshin** [servo/servo#12133] opened 2016-07-01 20:45 UTC
assertion failed: count_cell.get() > 0
### URL:
http://www.sfgate.com/
### Backtrace:
```
frame #0  - 0x000055c7c1c42a0d - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x000055c7c1c42995 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000055c7c0e14379 - _<F as alloc..boxed..FnBox<A>>::call_box::hc555946005547ceb
frame #3  - 0x000055c7c1c39818 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
frame #4  - 0x000055c7c1d40dcc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000055c7c0656f0f - std::panicking::begin_panic::h0bf39f6d43ab9349
frame #6  - 0x000055c7c0cc94b0 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h71d7672a3472afa1
frame #7  - 0x000055c7c0cc6fbb - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h724ec798d0dfe84e
frame #8  - 0x000055c7c0e1f2c4 - script::script_thread::ScriptThread::handle_msg_from_script::hfac8a5d67415fa31
frame #9  - 0x000055c7c0e7090f - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hcc3e5fcf08d42e0c
frame #10 - 0x000055c7c0e57af7 - script::script_thread::ScriptThread::handle_msgs::hf9fbf9949e23273b
frame #11 - 0x000055c7c0e12a67 - std::panicking::try::call::h99112171a9854ab3
frame #12 - 0x000055c7c1d655db - __rust_try
frame #13 - 0x000055c7c1d6557e - __rust_maybe_catch_panic
frame #14 - 0x000055c7c0e13cdd - _<F as alloc..boxed..FnBox<A>>::call_box::h4410a344b31b72da
frame #15 - 0x000055c7c1d595a4 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #16 - 0x00007fe8f9eda463 - start_thread
frame #17 - 0x00007fe8f9a01e5c - clone
frame #18 - 0x0000000000000000 - <unknown>

```

**Comment by ConnorGBrewster** [comment] 2016-07-01 20:51
Thank you for reporting this!
Closing as a dupe of #12047.

**Closed by ConnorGBrewster** 2016-07-01 20:51 UTC
