### ISSUE TITLE
Element.scrollIntoView is not implemented

### ISSUE THREAD

**Issue by abdullah-if** [servo/servo#28215] opened 2021-02-26 13:06 UTC
Servo is unable to recognize DOM Element's [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) method. ([Specification](https://drafts.csswg.org/cssom-view/#dom-element-scrollintoview))

I found the problem while trying to read Introduction of [The Rust Programming Language Book](https://archlinux.org/packages/extra/x86_64/rust-docs). ([Online version](https://doc.rust-lang.org/book/ch00-00-introduction.html)). Servo was unable to scroll.

Servo version: Servo 0.0.1-31d4f4ab4 (Linux)
Used debug options ```full-backtraces```, ```profile-script-events```.
Thrown following error 
`
[2021-02-26T12:46:36Z ERROR script::dom::bindings::error] Error at https://doc.rust-lang.org/book/book.js:531:23 activeSection.scrollIntoView is not a function
`

**Comment by sou-chon** [comment] 2022-09-28 15:18
I encountered the same problem. Is there any intention to implement this?

**Comment by jdm** [comment] 2022-10-01 01:13
Nobody is actively working on implementing it at this moment.

**Comment by mrobinson** [comment] 2024-04-15 08:49
Duplicate of #24059.

**Closed by mrobinson** 2024-04-15 08:49 UTC
