### ISSUE TITLE
unknown completed load Stylesheet("http://cdn.viafoura.net/56834d9/viafoura.css")

### ISSUE THREAD

**Issue by a-p-** [servo/servo#12172] opened 2016-07-02 14:01 UTC
Build of `master` (1ed06777ee1e69c8b56715c897a5bd66ad9e235e) on OS X 10.11.5.

Unsure if it's a dupe of #12075. (Backtrace here is somewhat deeper.)

URL: http://cbc.ca

```
$ ./mach run http://cbc.ca
ERROR:js::rust: Error at http://www.cbc.ca/g/stats/js/cbc-stats-top.js line 1 > Function:1:14: g is undefined

ERROR:constellation::constellation: Panic: unknown completed load Stylesheet("http://cdn.viafoura.net/56834d9/viafoura.css")
ERROR:constellation::constellation: Backtrace:
frame #0  - 0x0000000106f629b0 - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000000106f6285a - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000000105611115 - util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hca5ffcc1c77bcdb0
frame #3  - 0x0000000105611710 - extern $u22$rust.call$u22$$u20$fn$LP$$u5b$closure$SP$DefId$u20$$u7b$$u20$krate.$u20$47$C$$u20$node.$u20$DefIndex$LP$2388$RP$$u20$$u7d$$u20$0.ipc_channel..ipc..IpcSender$LT$$LP$core..option..Option$LT$msg..constellation_msg..PipelineId$GT$$C$$u20$std..string..String$C$$u20$std..string..String$RP$$GT$$C$$u20$1.core..option..Option$LT$msg..constellation_msg..PipelineId$GT$$u5d$$C$$u20$$LP$$RF$core..any..Any$C$$RP$$RP$::once_shim.212011::h6a715d9640034a44
frame #4  - 0x00000001056116bc - _<F as alloc..boxed..FnBox<A>>::call_box::hf8293425399bf25b
frame #5  - 0x0000000106e28aff - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h84c76f48854dc79e
frame #6  - 0x0000000106e28703 - _<std..thread..local..LocalKey<T>>::with::hf958b9c87c968706
frame #7  - 0x0000000106e28556 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hdc93aa6b58be7923
frame #8  - 0x00000001072dec74 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #9  - 0x00000001072f7d66 - std::panicking::begin_panic::he426e15a3766089a
frame #10 - 0x00000001072e02b8 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #11 - 0x00000001072f79bf - rust_begin_unwind
frame #12 - 0x000000010731e840 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #13 - 0x00000001073262e5 - core::option::expect_failed::hdb92832549f56a85
frame #14 - 0x000000010414cc7f - _<core..option..Option<T>>::expect::h0c5f02652781cd1b
frame #15 - 0x00000001041bde31 - script::document_loader::DocumentLoader::finish_load::hd9ca1a8efff60b87
frame #16 - 0x00000001041b94f2 - script::dom::document::Document::finish_load::h513b8a28835599f4
frame #17 - 0x000000010532aa54 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h99335e5ecc7da19d
frame #18 - 0x00000001053298fd - _<net_traits..ResponseAction as net_traits..Action<T>>::process::h91118dafb7c1129c
frame #19 - 0x0000000105328e2a - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::hc7642cf5ac630e71
frame #20 - 0x000000010562872c - script::script_thread::ScriptThread::handle_msg_from_script::h413421b1243beaa2
frame #21 - 0x00000001056bfa28 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h35f14a0525d04eaf
frame #22 - 0x00000001056bf595 - script::script_thread::ScriptThread::profile_event::h9ef610f70b1466e2
frame #23 - 0x000000010568d4ad - script::script_thread::ScriptThread::handle_msgs::h2219e5b07d4a2d14
frame #24 - 0x0000000105625e7c - script::script_thread::ScriptThread::start::h5bb918ec15aafa28
frame #25 - 0x0000000105625e2b - _<script..script_thread..ScriptThread as script_traits..ScriptThreadFactory>::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h5993f8ca465743fa
frame #26 - 0x0000000105625b81 - profile_traits::mem::ProfilerChan::run_with_memory_reporting::h4983b137e841d1ff
frame #27 - 0x0000000105611e36 - _<script..script_thread..ScriptThread as script_traits..ScriptThreadFactory>::create::_$u7b$$u7b$closure$u7d$$u7d$::hed16a26c598e006f
frame #28 - 0x00000001056104ce - util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::h16001d336bc693df
frame #29 - 0x0000000105610287 - _<std..panic..AssertUnwindSafe<F> as core..ops..FnOnce<()>>::call_once::hecdf32f3f9f78a28
frame #30 - 0x00000001056101db - std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h5d5da48b007463b8
frame #31 - 0x0000000105610a94 - std::panicking::try::call::h29501576f56c25ef
frame #32 - 0x00000001072faa4b - __rust_try
frame #33 - 0x00000001072fa9e5 - __rust_maybe_catch_panic
frame #34 - 0x000000010561012d - std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::haf639960440e636d
frame #35 - 0x000000010561007f - _<std..thread..local..LocalKey<T>>::with::h58926ef58c122971
frame #36 - 0x000000010560feaf - std::panicking::try::h70a4f1151a60f4a9
frame #37 - 0x000000010560fd8e - std::panic::catch_unwind::hc7305bd326702f6a
frame #38 - 0x000000010560fbec - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h4cb80be7d7cf475c
frame #39 - 0x0000000105610c97 - _<F as alloc..boxed..FnBox<A>>::call_box::h267cb02029cc53bb
frame #40 - 0x00000001072f64c8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #41 - 0x00007fff9447f99c - _pthread_body
frame #42 - 0x00007fff9447f919 - _pthread_start

```

**Comment by jdm** [comment] 2016-07-02 14:47
Duplicate of #12075. Thanks for reporting it!

**Closed by jdm** 2016-07-02 14:47 UTC
Labels: I-panic
