### ISSUE TITLE
[Feature request] Please make servo embeddable

### ISSUE THREAD

**Issue by LoveIsGrief** [servo/servo#31300] opened 2024-02-09 13:41 UTC
Searching for "embed" in the wiki, doesn't bring up results. There doesn't seem to be a crate on crates.io allowing one to embed servo into a rust application. If there is one, I cannot seem to find neither the crate, nor the documentation.

There is https://github.com/servo/servo/blob/main/components/servo/lib.rs but there doesn't seem to be a simple example e.g with Qt, slint, or some other framework. The `Servo` implementation also seems to do **a lot** of stuff. For example it has an implementation of history, managing "web views", touch, zoom, pinchzoom, and more.

What would be great:

 - a crate on some registry e.g `libservo` on crates.io
 - embedding documentation (at best generated from the code)
 - example applications built upon the published crate

**Comment by mrobinson** [comment] 2024-02-09 13:58
This looks like a duplicate of #27773. A better embedding story is definitely on the [roadmap](https://github.com/servo/servo/wiki/Roadmap) and of course that includes documentation and examples.

**Closed by mrobinson** 2024-02-09 13:58 UTC
