### ISSUE TITLE
Wikipedia page wrong layout 

### ISSUE THREAD

**Issue by kilobtye** [servo/servo#12748] opened 2016-08-05 16:08 UTC
https://en.wikipedia.org/wiki/Template:Multiple_issues 
![screenshot](https://cloud.githubusercontent.com/assets/4321081/17442042/726c8fce-5b66-11e6-8bd9-bdfa47ce61ef.png)

**Comment by gpoesia** [comment] 2016-09-02 15:11
I could reproduce it and will take a look.

**Comment by gpoesia** [comment] 2016-09-07 20:06
I've reduced the Wikipedia page to this small fragment, which shows the same bug:

```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="UTF-8">
        <title>Template:Multiple issues - Wikipedia, the free encyclopedia</title>
        <style type="text/css">            
            table.ombox {
                margin-left: 50%;
                border: 1px solid #aaa;
                background: #f9f9f9
            }
            .template-documentation {
                border: 1px solid #aaa;
                background-color: #ecfcf4;
            }
        </style>
    </head>
    <body>
        <div class="template-documentation">
            <table class="ombox">
                <tr>
                    <td>
                        If you plan to make breaking changes to this template, move it, or nominate it for deletion, please notify Twinkle's users and maintainers at Wikipedia talk:Twinkle as a courtesy, as this template is used in the standard installation of Twinkle. Thank you!
                    </td>
                </tr>
            </table>
        </div>
    </body>
</html>
```

<img src="https://dl.dropboxusercontent.com/u/10962672/Screenshots%20Servo/table_margin_overflow.png"/>

It seems that the table's margin is not actually constraining its inline size based on its parent's inline size. I'll return to this issue soon.

**Comment by gpoesia** [comment] 2016-09-18 23:20
I've investigated this further, and have some findings. If someone can help me understand what's happening (I see @pcwalton and @Ms2ger have touched the seemingly relevant code).

This is a fragment of the table flow dump for the example above:

```
│  │  │  ├─ Block(7f4c0e4a9190) sc=StackingContextId(0) pos=LogicalRect(H LTR, i1008px×b67.85px, @ (i8px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(1512px×67.85px at (0px,0px)), paint: TypedRect(1512px×67.85px at (0px,0px)) } children=1
│  │  │  │  ├─ ↑↑ Fragment for block: SpecificFragmentInfo::Generic(10) [] border_box=LogicalRect(H LTR, i1008px×b67.85px, @ (i0px,b0px)) border_padding=LogicalMargin(H LTR, i:1px..1px b:1px..1px) damage=STORE_OVERFLOW
│  │  │  │  ├─ TableWrapperFlow: Block(7f4c0e4a8f10) sc=StackingContextId(0) pos=LogicalRect(H LTR, i1008px×b65.85px, @ (i1px,b1px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(1008px×65.85px at (503px,0px)), paint: TypedRect(1008px×65.85px at (503px,0px)) } children=1

```

If my interpretation is correct, the first manifestation of the bug is that in the inline direction, TableWrapperFlow has the same size as its parent, but it shouldn't because of its margin. One of the symptoms is that when resolving the inline size equation:

`inline_start_margin + inline_size + inline_end_margin = available_inline_size`

for the TableWrapperFlow that wraps the table in the above example, `inline_size` is not `Auto` but `Specified(w)`, with `w` being the inline size of TableWrapper's parent div. Thus, the system is overconstrained, and in `BlockFlow::solve_block_inline_size_constraints()`, the value of `inline_end_margin`, which is also specified as 0 at this point, is ignored in order to solve the equation. It gets computed with a negative value (half of the available size, since half of the available size goes to the `inline_start_margin`, and a full available size goes to `inline_size`).

It seems logical to me that `inline_size` should be Auto at that point, and in the final solution it should be `available_width / 2`. So I started seeing why it gets there as `Specified`, and the reason is basically that `table_wrapper.rs:Table::initial_computed_inline_size()` always returns a `MaybeAuto::Specified`, even when `inline_size_from_style` is `MaybeAuto::Auto`. I'd guess there should be a case in which `Auto` is returned, but I'm still not sure how it should look like.

If in `Table::initial_computed_inline_size()` I just return `MaybeAuto::Auto` when `inline_size_from_style` is `MaybeAuto::Auto`, I at least get the text wrapped and the table ending where the div ends:

<img src="https://dl.dropboxusercontent.com/u/10962672/Screenshots%20Servo/wikipedia_issue_half_fix.png" />

Can anyone tell if this is the right direction to go, and other relevant information/code I'm missing?

Thanks!

**Closed** 2017-01-23 18:13 UTC
Labels: A-layout/table, C-assigned
