### ISSUE TITLE
Intermittent crash on /webstorage/storage_session_setitem_quotaexceedederr.html

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#7402] opened 2015-08-27 00:18 UTC
```
Unexpected Results
==================

/webstorage/storage_session_setitem_quotaexceedederr.html
---------------------------------------------------------
CRASH expected TIMEOUT [Parent]
```

https://github.com/servo/servo/pull/7395#issuecomment-135208098

http://build.servo.org/builders/linux2/builds/2913/steps/shell_1/logs/stdio

**Comment by dzbarsky** [comment] 2015-08-27 01:54
Dupe of #7149  (which might be a dupe of #6734 )

**Closed** 2015-08-27 02:56 UTC
Labels: I-intermittent, I-panic
