### ISSUE TITLE
Webrender panic when rendering reddit

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#17857] opened 2017-07-25 21:29 UTC
Opening reddit this morning, I'm seeing a panic on opening the page, with this backtrace:

```
called `Option::unwrap()` on a `None` value (thread RenderBackend, at src/libcore/option.rs:335)
stack backtrace:
   0:        0x11011246e - backtrace::backtrace::trace::h006713205f0720ff
   1:        0x1101124ac - backtrace::capture::Backtrace::new::h24201f216dc48063
   2:        0x10eb41006 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h290abcf3293ce52f
   3:        0x110a47d41 - std::panicking::rust_panic_with_hook::h8b1d36fd0ad99f31
   4:        0x110a47b64 - std::panicking::begin_panic_new::h17d6b9dba1d42378
   5:        0x110a47ab2 - std::panicking::begin_panic_fmt::hb53bf6eaee76ae86
   6:        0x110a47a1a - rust_begin_unwind
   7:        0x110a72d33 - core::panicking::panic_fmt::hd5e9c17a1a223436
   8:        0x110a72c36 - core::panicking::panic::h1e2e80a9188dd0b9
   9:        0x1101f6fd1 - webrender::frame::Frame::flatten_item::h6c9f008a2eeb37fc
  10:        0x1101f4d6b - webrender::frame::Frame::flatten_item::h6c9f008a2eeb37fc
  11:        0x1101f77f9 - webrender::frame::Frame::flatten_root::h7087e3fd2e31849b
  12:        0x1101f27e4 - webrender::frame::Frame::flatten_item::h6c9f008a2eeb37fc
  13:        0x1101f4d6b - webrender::frame::Frame::flatten_item::h6c9f008a2eeb37fc
  14:        0x1101f4d6b - webrender::frame::Frame::flatten_item::h6c9f008a2eeb37fc
  15:        0x1101f4d6b - webrender::frame::Frame::flatten_item::h6c9f008a2eeb37fc
  16:        0x1101f4d6b - webrender::frame::Frame::flatten_item::h6c9f008a2eeb37fc
  17:        0x1101f77f9 - webrender::frame::Frame::flatten_root::h7087e3fd2e31849b
  18:        0x1101eb87b - webrender::frame::Frame::create::h9847891b979563b9
  19:        0x11021d940 - webrender::render_backend::RenderBackend::build_scene::he23c250801fad923
  20:        0x110218d68 - webrender::render_backend::RenderBackend::run::h35a0614ebbf7d0a4
  21:        0x110177ff3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8aeabe9c0b89c087
  22:        0x11017adfd - std::panicking::try::do_call::hf7c13dc6b1ba4652
  23:        0x110a48edc - __rust_maybe_catch_panic
  24:        0x1101a11b5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hc55663ad28489505
  25:        0x110a44ccb - std::sys::imp::thread::Thread::new::thread_start::hf51e3daefc1a980e
  26:     0x7fffd058b93a - _pthread_body
  27:     0x7fffd058b886 - _pthread_start
ERROR:servo: called `Option::unwrap()` on a `None` value
called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: ConnectionReset, error: StringError("No senders exist for this port.") }) }) (thread main, at src/libcore/result.rs:860)
called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: ConnectionReset, error: StringError("No senders exist for this port.") }) }) (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(8), index: PipelineIndex(2) }, at src/libcore/result.rs:860)
stack backtrace:
   0:        0x11011246e - backtrace::backtrace::trace::h006713205f0720ff
   1:        0x1101124ac - backtrace::capture::Backtrace::new::h24201f216dc48063
   2:        0x10eb41006 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h290abcf3293ce52f
   3:        0x110a47d41 - std::panicking::rust_panic_with_hook::h8b1d36fd0ad99f31
   4:        0x110a47b64 - std::panicking::begin_panic_new::h17d6b9dba1d42378
   5:        0x110a47ab2 - std::panicking::begin_panic_fmt::hb53bf6eaee76ae86
   6:        0x110a47a1a - rust_begin_unwind
   7:        0x110a72d33 - core::panicking::panic_fmt::hd5e9c17a1a223436
   8:        0x1108b8640 - core::result::unwrap_failed::h59e23eed601e084a
   9:        0x1108bf4dd - webrender_api::api::RenderApi::get_scroll_node_state::hdc4d59075456456e
  10:        0x10eb2fa5a - _$LT$compositing..compositor..IOCompositor$LT$Window$GT$$GT$::send_viewport_rects::h7496a00e5173e503
  11:        0x10eb31ce2 - _$LT$compositing..compositor..IOCompositor$LT$Window$GT$$GT$::handle_browser_message::hd0a3d1f282783794
  12:        0x10eb15019 - _$LT$servo..Browser$LT$Window$GT$$GT$::handle_events::h05b9eb1ae1442a87
  13:        0x10eb400a5 - servo::main::h4e45335c7bd687fe
  14:        0x110a48edc - __rust_maybe_catch_panic
  15:        0x110a48158 - std::rt::lang_start::h1985d8ccb29264f6
ERROR:servo: called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: ConnectionReset, error: StringError("No senders exist for this port.") }) })
stack backtrace:
   0:        0x11011246e - backtrace::backtrace::trace::h006713205f0720ff
   1:        0x1101124ac - backtrace::capture::Backtrace::new::h24201f216dc48063
   2:        0x10eb41006 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h290abcf3293ce52f
   3:        0x110a47d41 - std::panicking::rust_panic_with_hook::h8b1d36fd0ad99f31
   4:        0x110a47b64 - std::panicking::begin_panic_new::h17d6b9dba1d42378
   5:        0x110a47ab2 - std::panicking::begin_panic_fmt::hb53bf6eaee76ae86
   6:        0x110a47a1a - rust_begin_unwind
   7:        0x110a72d33 - core::panicking::panic_fmt::hd5e9c17a1a223436
   8:        0x1108b8640 - core::result::unwrap_failed::h59e23eed601e084a
   9:        0x1108bdcdb - webrender_api::api::RenderApiSender::create_api::ha5ff1288759a552d
  10:        0x10ed654a0 - _$LT$layout_thread..LayoutThread$u20$as$u20$layout_traits..LayoutThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::heca56c514e21a8b7
  11:        0x10ece163d - std::sys_common::backtrace::__rust_begin_short_backtrace::hac8710bb6f6a3c59
  12:        0x10ece3c6d - std::panicking::try::do_call::hfe01c328de51de8c
  13:        0x110a48edc - __rust_maybe_catch_panic
  14:        0x10ed14285 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h2d490ea0e45ab3ff
  15:        0x110a44ccb - std::sys::imp::thread::Thread::new::thread_start::hf51e3daefc1a980e
  16:     0x7fffd058b93a - _pthread_body
  17:     0x7fffd058b886 - _pthread_start
ERROR:servo: called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: ConnectionReset, error: StringError("No senders exist for this port.") }) })
Servo exited with return value 101
```

**Comment by jonathandturner** [comment] 2017-07-25 21:39
You can also see this error by opening Ars Technica from the gallery and leaving it open for ~10 secs

**Comment by jdm** [comment] 2017-07-25 22:43
This looks like the same panic that I saw in #17840.

**Comment by jdm** [comment] 2017-07-25 22:43
cc @glennw

**Comment by glennw** [comment] 2017-08-15 23:04
I have been unable to reproduce locally, but I believe it should be fixed when https://github.com/servo/webrender/pull/1576 lands in WR and Servo.

**Comment by glennw** [comment] 2017-08-30 10:05
I believe this is resolved now. Please re-open if still occurring.

**Closed by glennw** 2017-08-30 10:05 UTC
Labels: A-webrender, I-panic
