### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: ()

### ISSUE THREAD

**Issue by tesfabpel** [servo/servo#12073] opened 2016-07-01 15:22 UTC
called `Result::unwrap()` on an `Err` value: ()
### URL:
http://www.costasoft.it/
### Backtrace:
```
frame #0  - 0x00007f368e852a0d - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x00007f368e852995 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x00007f368cfcd487 - _<F as alloc..boxed..FnBox<A>>::call_box::heccbd09ce30bd77e
frame #3  - 0x00007f368e849818 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
frame #4  - 0x00007f368e950dcc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x00007f368e96b3e1 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x00007f368e95263a - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x00007f368e96b37e - rust_begin_unwind
frame #8  - 0x00007f368e9a197f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x00007f368e2edfbd - core::result::unwrap_failed::hf71a1e71ac3faa15
frame #10 - 0x00007f368e46aba4 - style::properties::animated_properties::interpolate_transform_list::h7f4c1788f02da86b
frame #11 - 0x00007f368e1c4532 - style::animation::PropertyAnimation::update::hf02c18eb1be3d82f
frame #12 - 0x00007f368e1c1a75 - layout::animation::recalc_style_for_animations::_$u7b$$u7b$closure$u7d$$u7d$::h073ff236611ac9f9
frame #13 - 0x00007f368e1bf53e - layout::animation::recalc_style_for_animations::hc85c91e09ac870f3
frame #14 - 0x00007f368e1bf58e - layout::animation::recalc_style_for_animations::hc85c91e09ac870f3
frame #15 - 0x00007f368e1bf58e - layout::animation::recalc_style_for_animations::hc85c91e09ac870f3
frame #16 - 0x00007f368e1bf58e - layout::animation::recalc_style_for_animations::hc85c91e09ac870f3
frame #17 - 0x00007f368e1bf58e - layout::animation::recalc_style_for_animations::hc85c91e09ac870f3
frame #18 - 0x00007f368e1bf58e - layout::animation::recalc_style_for_animations::hc85c91e09ac870f3
frame #19 - 0x00007f368e1bf58e - layout::animation::recalc_style_for_animations::hc85c91e09ac870f3
frame #20 - 0x00007f368e1bf58e - layout::animation::recalc_style_for_animations::hc85c91e09ac870f3
frame #21 - 0x00007f368d01a4cb - layout_thread::LayoutThread::handle_request_helper::h8d81064be05c6b00
frame #22 - 0x00007f368d0076f6 - layout_thread::LayoutThread::handle_request::h9b944f2f41c319e5
frame #23 - 0x00007f368cfcb1fa - std::panicking::try::call::h1a5934e90174a4d0
frame #24 - 0x00007f368e9755db - __rust_try
frame #25 - 0x00007f368e97557e - __rust_maybe_catch_panic
frame #26 - 0x00007f368cfcc62d - _<F as alloc..boxed..FnBox<A>>::call_box::h2c8a06862bfda3d9
frame #27 - 0x00007f368e9695a4 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #28 - 0x00007f368a574183 - start_thread
frame #29 - 0x00007f368a08b37c - clone
frame #30 - 0x0000000000000000 - <unknown>

```

**Comment by ConnorGBrewster** [comment] 2016-07-01 15:24
Thank you for reporting this! :)
Dupe of #12027

**Comment by Ms2ger** [comment] 2016-07-01 15:24
Thanks for the report; this is #12027.

**Closed by ConnorGBrewster** 2016-07-01 15:24 UTC
