### ISSUE TITLE
location.replace is not implemented

### ISSUE THREAD

**Issue by bzbarsky** [servo/servo#13768] opened 2016-10-14 14:09 UTC
Ran into a page which didn't work because `location.replace` doesn't exist.

**Comment by jdm** [comment] 2016-10-14 14:10
https://github.com/servo/servo/pull/13418/

**Comment by jdm** [comment] 2016-10-14 14:10
Duplicate of #13413. Thanks for filing!

**Closed by jdm** 2016-10-14 14:10 UTC

**Comment by bzbarsky** [comment] 2016-10-14 14:13
For what it's worth, I did search issues for location.replace before filing....  The title of the other one is not very discoverable.
