### ISSUE TITLE
Fonts not rendered with subpixel antialiasing

### ISSUE THREAD

**Issue by gordonbrander** [servo/servo#10199] opened 2016-03-25 23:19 UTC
Here's a screenshot of text rendered in Servo. (I've used a loupe app to magnify the text so you can see the antialiasing pixels). The text is rendered without sub-pixel antialiasing.

<img width="553" alt="screen shot 2016-03-25 at 16 13 39" src="https://cloud.githubusercontent.com/assets/58421/14056087/c642f276-f2a4-11e5-991c-e7be996aadf8.png">

Here's the same page rendered in Firefox. Fonts are rendered with sub-pixel antialiasing.

<img width="658" alt="screen shot 2016-03-25 at 16 14 06" src="https://cloud.githubusercontent.com/assets/58421/14056116/14760924-f2a5-11e5-8bc2-7b2b54b718ee.png">

You can see a significant difference in the resulting text. The text in Servo appears "thin" and weak, whereas text in Firefox, Safari and Chrome has a rounder, fatter feel.

cc @metajack

**Comment by yump** [comment] 2016-07-02 06:56
I don't think it's just a lack of subpixel AA.  That shouldn't make a difference to the weight of the font.  Either the greyscale AA renderer is not gamma correct, or it's using (eugh!) hinting.

**Comment by ConnorGBrewster** [comment] 2016-07-02 18:35
Possibly fixed by #11103?

**Comment by raphlinus** [comment] 2016-08-02 06:08
There's definitely RGB subpixel rendering present in the Firefox screenshot. It also looks like there's anemic gamma in the Servo screenshot. (Many people consider adjusting gamma to be linear-intensity to be "correct" but I disagree with that). It doesn't _look_ like there's a problem with over-hinting, but it's hard to say for sure.

See btw https://www.freetype.org/freetype2/docs/text-rendering-general.html for a little more background on gamma and subpixel AA.

**Comment by notriddle** [comment] 2016-08-02 06:45
Note that I have grayscale AA turned on everywhere. Servo's doing something else wrong, my guess is it's doing anti-aliasing twice or it's simply grabbing an overly-thin font.

![antialiasing](https://cloud.githubusercontent.com/assets/1593513/17319340/df67ca94-5841-11e6-9a2d-51983505b822.png)

**Comment by jonathandturner** [comment] 2016-08-25 16:37
I'm also seeing this.  When the browserhtml startup screen is resized, you can lose the expected anti-aliasing on the fonts.

At some sizes (closer to expected):
![screen shot 2016-08-25 at 9 34 29 am](https://cloud.githubusercontent.com/assets/547158/17977632/54469724-6aa7-11e6-848f-210f36826e59.png)

At other sizes (notices how font rendering loses aliasing/parts of the font render):
![screen shot 2016-08-25 at 9 33 40 am](https://cloud.githubusercontent.com/assets/547158/17977634/56517156-6aa7-11e6-80e1-f7d3391663cc.png)

**Comment by nox** [comment] 2017-10-01 10:42
I cannot reproduce this anymore.

**Closed by nox** 2017-10-01 10:42 UTC
Labels: A-gfx/rendering
