### ISSUE TITLE
Intermittent crash of /css21_dev/html4/margin-bottom-*.htm

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#8945] opened 2015-12-11 23:24 UTC
```
Ran 7097 tests finished in 878.0 seconds.
  • 7096 ran as expected. 8 tests skipped.
  • 1 tests crashed unexpectedly

Tests with unexpected results:
  ▶ CRASH [expected PASS] /css21_dev/html4/margin-bottom-applies-to-002.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:741
  │ stack backtrace:
  │    1:        0x10358dbf8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x10358fcbf - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x10358f762 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x10357b606 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x10357b9ee - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
  │    6:        0x10358d217 - rust_begin_unwind
  │    7:        0x1035b22a0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
  │    8:        0x102c39587 - mem::_<impl>::send::haf009788f0ee7115Bea
  │    9:        0x10279e430 - sys_common::unwind::try::try_fn::try_fn::h6135003471651053147
  │   10:        0x10358d038 - __rust_try
  │   11:        0x10358a13e - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   12:        0x10279f601 - boxed::_<impl>::call_box::call_box::h3509381201889269884
  │   13:        0x10358ef4d - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   14:     0x7fff8416a059 - _pthread_body
  │   15:     0x7fff84169fd6 - _pthread_start
  │ thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
  │ stack backtrace:
  │    1:        0x10358dbf8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x10358fcbf - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x10358f762 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x10357b504 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x10357b9ee - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
  │    6:        0x10358d217 - rust_begin_unwind
  │    7:        0x1035b22a0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
  │    8:        0x1035b259c - panicking::panic::hbe2e3a5159c3d178iEK
  │    9:        0x102354039 - page::_<impl>::window::h813c8df4d8dc356dTuZ
  │   10:        0x10279b504 - script_task::_<impl>::drop::h437e092b646f5d2cLH0
  │   11:        0x10279ef50 - sys_common::unwind::try::try_fn::try_fn::h6135003471651053147
  │   12:        0x10358d038 - __rust_try
  │   13:        0x10358a13e - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   14:        0x10279f601 - boxed::_<impl>::call_box::call_box::h3509381201889269884
  │   15:        0x10358ef4d - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   16:     0x7fff8416a059 - _pthread_body
  │   17:     0x7fff84169fd6 - _pthread_start
  └ thread panicked while panicking. aborting.
```

**Comment by jdm** [comment] 2015-12-13 20:28
Marking this as a duplicate of #8961.

**Closed by jdm** 2015-12-13 20:28 UTC
Labels: I-intermittent
