### ISSUE TITLE
Intermittent CRASH expected TIMEOUT in /css21_dev/html4/counter-reset-increment-002.htm

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#6958] opened 2015-08-04 12:38 UTC
https://github.com/servo/servo/pull/6949
```
10:04.26 TEST_START: Thread-TestrunnerManager-7 /css21_dev/html4/counter-reset-increment-002.htm

(elided output from other runners)

10:13.69 CRASH: Thread-TestrunnerManager-7 pid:8479. Test:None. Minidump anaylsed:False. Signature:[/css21_dev/html4/counter-reset-increment-002.htm]

10:13.69 TEST_END: Thread-TestrunnerManager-7 CRASH, expected TIMEOUT
```

**Comment by jdm** [comment] 2015-08-04 14:44
Duplicate of #6818.

**Closed by jdm** 2015-08-04 14:44 UTC
Labels: A-testing, I-intermittent
