### ISSUE TITLE
Myanmar text doesn't display properly on Ubuntu

### ISSUE THREAD

**Issue by veer66** [servo/servo#12944] opened 2016-08-19 17:04 UTC
On Ubuntu 16.04 with two Myanmar fonts i.e. Noto Sans Myanmar and Padauk installed, Servo Commit 94152523 cannot display Myanmar text properly as shown below:

![myanmar2](https://cloud.githubusercontent.com/assets/370688/17817573/5c8823f4-6669-11e6-9505-da682d35ade3.png)

However it should look somewhat like this:

![myanmar1](https://cloud.githubusercontent.com/assets/370688/17817584/696d530a-6669-11e6-9bff-94d6884705e9.png)

Remark:  Myanmar text was taken from word-break-break-all-007.htm  http://file.veerkesto.net/servo_test/myanmar.html

**Comment by veer66** [comment] 2020-05-11 17:43
Although #4901 was closed, Servo 0.0.1-70d4e142f still doesn't display Myanmar text.

![servo-Screenshot_2020-05-12_00-39-45](https://user-images.githubusercontent.com/370688/81593237-5cb12e00-93e9-11ea-933c-8db789a68c3d.png)

**Comment by jdm** [comment] 2020-05-11 17:47
Updated link: https://file.veer66.rocks/servo_test/myanmar.html
I can't reproduce the problem on macOS.

**Comment by jdm** [comment] 2020-05-11 17:49
Since the page doesn't include any CSS fonts, this looks like a default font fallback issue on Linux.

**Comment by jdm** [comment] 2020-05-11 17:51
The only fallback missing from https://github.com/servo/servo/blob/252197b04a430318de9b9a7ab3c856881500639d/components/gfx/platform/freetype/font_list.rs#L154-L163 that's present in https://searchfox.org/mozilla-central/rev/446160560bf32ebf4cb7c4e25d7386ee22667255/gfx/thebes/gfxPlatformGtk.cpp#217-246 is "Symbola".

**Comment by atouchet** [comment] 2020-05-11 17:55
I am also not able to reproduce the issue in Windows 10:

![Screenshot](https://user-images.githubusercontent.com/26315797/81594501-dc051a00-9375-11ea-8c63-5cfe15b3274b.png)

**Comment by talnetd** [comment] 2020-05-11 23:27
So this is solved?

**Comment by jdm** [comment] 2020-05-11 23:43
No, it still reproduces on Ubuntu.

**Comment by talnetd** [comment] 2020-05-12 00:05
Will try to reproduce with latest ubuntu LTS version.

**Comment by veer66** [comment] 2020-11-30 05:11
Servo 0.0.1-6f6f8488d
OS: Ubuntu 20.04.1 LTS x86_64 
Kernel: 5.4.0-54-generic 

![ภาพ](https://user-images.githubusercontent.com/370688/100571031-b422d700-3304-11eb-9aca-a876d08a8213.png)

**Comment by veer66** [comment] 2021-02-10 05:53
Servo 0.0.1-4a52c94cc
OS: Fedora 33 (KDE Plasma) x86_64

![servo-fedora-33-kde-Screenshot_20210210_125218](https://user-images.githubusercontent.com/370688/107470989-e96a6180-6b9e-11eb-94b4-f769fa233e9f.png)

**Comment by veer66** [comment] 2023-01-17 01:27
Servo 0.0.1-806db676b on openSUSE Leap 15.4 x86_64 

![image](https://user-images.githubusercontent.com/370688/212789915-f2227907-317c-4676-916f-01a4768ad7de.png)

**Comment by veer66** [comment] 2023-01-17 01:32
This is the HTML for testing.

```HTML
<!DOCTYPE html>
<html  lang="en" >
<head>
<meta charset="utf-8">
<title>myanmar</title>
</head>
<body>
<div><span>မြန်မာစာမြန်မာစာ</span></div>
</body>
</html>
```

**Comment by veer66** [comment] 2023-09-12 02:09
# Servo 0.0.1-9b1247b20 on openSUSE LEAP 15.5 X86-64

The window was empty. Even boxes have gone. 

![ภาพ](https://github.com/servo/servo/assets/370688/dd473ccc-ac9c-41ae-bac4-f30b5af67b20)

**Comment by veer66** [comment] 2023-09-15 16:22
# Servo 0.0.1-c78533c1a on MX Linux 23 KDE

The boxes are back.

![image](https://github.com/servo/servo/assets/370688/d1ae10eb-2112-461d-80d5-646a21657833)

**Comment by mrobinson** [comment] 2023-09-15 16:27
I'm fairly sure this is now a duplicate of #25883.

**Comment by mrobinson** [comment] 2024-05-16 14:11
The following HTML seems to render properly on Linux, so I suspect that the issue here is really that we don't have the right fonts in the fallback list. This should be fixed fairly soon.

```html
<!DOCTYPE html>
<html lang="en" class=" zzndpnpnv idc0_350"><script src="myanmar_files/inject.js"></script><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<title>myanmar</title>
</head>
<body>
<div><span style="font-family: 'Noto Sans Myanmar';">မြန်မာစာမြန်မာစာ</span></div>
</body></html>
```

**Comment by veer66** [comment] 2024-05-18 02:13
>  I suspect that the issue here is really that we don't have the right fonts in the fallback list. This should be fixed fairly soon.

When I was reporting this issue in 2016, I thought somewhat similar to what you mentioned. I even made a similar experiment using Noto Sans Myanmar. Perhaps I've overlooked something.

**Closed** 2024-05-27 11:04 UTC
Labels: A-platform/fonts, P-linux
