### ISSUE TITLE
Transparent Rects demo is confined to top left corner

### ISSUE THREAD

**Issue by jdm** [servo/servo#15689] opened 2017-02-22 14:04 UTC
If you run `./mach run --release -b` and click the transparent rects demo, all of the rects congregate in the top left corner. If you run `./mach run --release https://cdn.rawgit.com/servo/servo.org/gh-pages/bhtml-newtab/webrender-demos/transparent_rects.html` it works fine. 

The constellation creates the new pipeline in `handle_script_loaded_url_in_iframe_msg` with a null window size, which gets filled in later when the iframe element is reflowed and sends a message to the constellation. If the iframe's content loads before this occurs (such as when using file:// URLs), the script will run before a resize message is received, so `Window::GetInnerWidth` will return 0 (similar to, but not exactly #15688).

**Comment by jdm** [comment] 2017-02-22 14:04
This also affects the spinning spheres demo.

**Comment by atouchet** [comment] 2018-03-02 20:13
@jdm are you still able to reproduce this? It seems to be fixed in the latest nightly build. I'm not sure if the underlying problem was solved or if it's just harder to trigger now.

**Comment by jdm** [comment] 2018-03-02 20:32
The problem occurs when the page is loaded inside of an iframe.

**Closed** 2018-12-18 15:23 UTC
Labels: A-constellation, A-content/dom
