### ISSUE TITLE
document.write not a function

### ISSUE THREAD

**Issue by netroby** [servo/servo#12428] opened 2016-07-13 02:00 UTC
```
huzhifeng:servo/ $ ./runservo.sh 
Unhandled error occured 
ReferenceError: navigator.mozSettings API is not available
ERROR:js::rust: Error at http://www.cnbeta.com/:3:5: document.write is not a function

ERROR:js::rust: Error at http://www.cnbeta.com/:3:5: document.write is not a function

ERROR:js::rust: Error at http://www.cnbeta.com/rank/show.htm?t=20160713:0:1: document.write is not a function

ERROR:js::rust: Error at http://www.cnbeta.com/poll/show.htm?t=20160713:0:1: document.write is not a function

ERROR:js::rust: Error at http://www.cnbeta.com/:1:6: document.write is not a function

ERROR:js::rust: Error at http://www.cnbeta.com/:1:6: document.write is not a function

ERROR:js::rust: Error at http://www.cnbeta.com/:1:6: document.write is not a function

``

**Comment by notriddle** [comment] 2016-07-13 03:27
Duplicate of #3704.

**Closed by notriddle** 2016-07-13 03:27 UTC
