### ISSUE TITLE
Acid2 rendering is broken. chin and right temple

### ISSUE THREAD

**Issue by gnoireaux** [servo/servo#20724] opened 2018-05-01 01:58 UTC
Servo 0.0.1-847115b on Mac OS, macbook air7.2, 
```
uname -a
Darwin gmba.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

```

`./servo http://acid2.acidtests.org/#top`
renders:
![image](https://user-images.githubusercontent.com/73658/39458226-432af22a-4cf3-11e8-81b1-9c54e0752158.png)

also, scrolling breaks the face further.
![image](https://user-images.githubusercontent.com/73658/39458238-658a8876-4cf3-11e8-95b0-3f18e0639fa9.png)

**Comment by atouchet** [comment] 2018-05-01 03:10
This looks like one of the same issues in #18940.

**Comment by jdm** [comment] 2018-05-01 12:55
Closing as a duplicate of #18940. Thanks for reporting it!

**Closed by jdm** 2018-05-01 12:55 UTC
