### ISSUE TITLE
solid backgrounds are drawn as transparent gradients after visiting certain pages

### ISSUE THREAD

**Issue by Swatinem** [servo/servo#10136] opened 2016-03-23 10:42 UTC
* using browserhtml
* when going to for example github.com
* solid colors are turned into strange half transparent gradients

I can not reproduce this when I visit github.com without browserhtml. I can also not reproduce this when visiting google.com for example. Once things are screwed up that way, it stays that way no matter what other tabs I open in browserhtml

Also, when I open two pages, their content overlaps because apparently the page becomes half transparent.

![bildschirmfoto von 2016-03-23 11-26-59](https://cloud.githubusercontent.com/assets/580492/13982694/c1208e30-f0eb-11e5-8c4d-f4c94d08c520.png)

**Comment by paulrouget** [comment] 2016-03-23 10:45
Most likely a dupe of https://github.com/servo/servo/issues/10115

**Comment by paulrouget** [comment] 2016-03-23 10:52
Bump bhtml P1. This happens quite often.

Again, most likely similar to #10115.

**Comment by pcwalton** [comment] 2016-03-29 00:39
This will be annoying to reproduce without a small test case. Hmm.

**Comment by pcwalton** [comment] 2016-03-29 01:33
Minimal test case:

    <!DOCTYPE html>
    <style>
    body {
        background: black;
    }
    div {
        color: white;
        text-shadow: 0 0 2px gray;
    }
    </style>
    <div>whoa</div>

**Comment by pcwalton** [comment] 2016-03-29 01:37
apitrace says `glCopyTexSubImage2D()` is returning `GL_INVALID_VALUE` on this test case. So there's the undefined behavior.

**Comment by pcwalton** [comment] 2016-03-30 19:11
I'm guessing this is because the texture copies are overwriting the dummy color texture.

**Comment by paulrouget** [comment] 2016-03-31 04:12
@pcwalton https://github.com/servo/webrender/pull/253 doesn't fix this.

**Comment by pcwalton** [comment] 2016-03-31 04:14
There must be two bugs here, because I'm certain that that PR fixes symptoms like these. I guess this must be texture cache corruption from another source.

**Comment by paulrouget** [comment] 2016-03-31 04:15
Let me double check that I'm compiling with the proper version of webrender.

**Comment by paulrouget** [comment] 2016-03-31 04:46
Hm, the latest cargo update didn't include the latest 2 PRs.

**Comment by paulrouget** [comment] 2016-03-31 07:51
Confirmed fixed with the latest wr. Waiting for the cargo update.

**Comment by pcwalton** [comment] 2016-03-31 17:37
Excellent. :)

**Closed** 2016-03-31 19:02 UTC
Labels: A-browserhtml/P1
