### ISSUE TITLE
inline-block causes twitter layout problems

### ISSUE THREAD

**Issue by jrmuizel** [servo/servo#14352] opened 2016-11-23 23:04 UTC
https://people-mozilla.org/~jmuizelaar/bugs/twitter-reduce.html renders wrong in Servo. This is a reduced version of https://people-mozilla.org/~jmuizelaar/webrender/sites/twitter.html

Removing the "display: inline-block" from the Icon class fixes the layout.

@pcwalton

**Comment by stshine** [comment] 2017-03-20 08:29
duplicate of #13683.

**Closed** 2017-03-20 11:53 UTC
Labels: A-layout/inline
