### ISSUE TITLE
Panic when navigating backwards through history

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#10986] opened 2016-05-03 03:47 UTC
Steps:
```
./mach run -d https://wikipedia.org
```
Click on a link
Navigate backwards

Assertion fails here: https://github.com/servo/servo/blob/89b276c889ce76f8fe43c22779835af138472dac/components/script/timers.rs#L181

Backtrace:
```
ERROR:compositing::constellation: Panic: assertion failed: base_time >= self.timers.borrow().last().unwrap().scheduled_for
ERROR:compositing::constellation: Backtrace:
frame #0  - 0x000000010f5e1278 - backtrace::backtrace::trace::h8cb7b0465fa42e9f
frame #1  - 0x000000010f5e112a - backtrace::capture::Backtrace::new::ha2e43e88f310ebee
frame #2  - 0x000000010e4df38f - util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h02929088221f8b46
frame #3  - 0x000000010e4e1b8d - extern $u22$rust.call$u22$$u20$fn$LP$$u5b$closure$SP$DefId$u20$$u7b$$u20$krate.$u20$45$C$$u20$node.$u20$DefIndex$LP$2731$RP$$u20$$u7d$$u20$0.ipc_channel..ipc..IpcSender$LT$$LP$core..option..Option$LT$msg..constellation_msg..PipelineId$GT$$C$$u20$std..string..String$C$$u20$std..string..String$RP$$GT$$C$$u20$1.core..option..Option$LT$msg..constellation_msg..PipelineId$GT$$u5d$$C$$u20$$LP$$RF$$u27$static$u20$core..any..Any$u20$$u2b$$u20$$u27$static$C$$RP$$RP$::once_shim.157434::h8eb86e2740528a94
frame #4  - 0x000000010e4e1b3c - _<F as std..boxed..FnBox<A>>::call_box::hfa23bad530dc8377
frame #5  - 0x000000010f576273 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h01133ea4cd6e4585
frame #6  - 0x000000010f575e23 - _<std..thread..LocalKey<T>>::with::he9fc920aea584817
frame #7  - 0x000000010f575c7a - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h7c8a22ebea1e52ef
frame #8  - 0x000000010ff437d8 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
frame #9  - 0x000000010da25ad7 - std::sys_common::unwind::begin_unwind::h65390c63b501d6ed
frame #10 - 0x000000010e45230f - script::timers::OneshotTimers::fire_timer::heef74cf6b7f5c1d1
frame #11 - 0x000000010e451d68 - script::dom::window::Window::handle_fire_timer::hbe42b1b461d3809a
frame #12 - 0x000000010e5820e4 - script::script_thread::ScriptThread::handle_timer_event::hc1cfd799fa6c4256
frame #13 - 0x000000010e57fcbf - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h9e680ae6f2772b0a
frame #14 - 0x000000010e57f7f0 - script::script_thread::ScriptThread::profile_event::he08ac94603cac4e5
frame #15 - 0x000000010e5512a3 - script::script_thread::ScriptThread::handle_msgs::haacc9a2f304fe228
frame #16 - 0x000000010e4f52ac - script::script_thread::ScriptThread::start::h5f466082d5fe1984
frame #17 - 0x000000010e4f5150 - _<script_thread..ScriptThread as script_traits..ScriptThreadFactory>::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hb2a66ce329461d65
frame #18 - 0x000000010e4f4e91 - profile_traits::mem::ProfilerChan::run_with_memory_reporting::hbe3fc74072d05f3e
frame #19 - 0x000000010e4e237a - _<script_thread..ScriptThread as script_traits..ScriptThreadFactory>::create::_$u7b$$u7b$closure$u7d$$u7d$::h376836bb503682b7
frame #20 - 0x000000010e4decd0 - util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::heb59eb3e917c5b06
frame #21 - 0x000000010e4de4f3 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h5451e0f5cc8da44b
frame #22 - 0x000000010e4de468 - std::sys_common::unwind::try::try_fn::hca2f304c46ad6472
frame #23 - 0x000000010ff551ab - __rust_try
frame #24 - 0x000000010ff55133 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
frame #25 - 0x000000010e4de3a5 - std::sys_common::unwind::try::h9b69ed8320487131
frame #26 - 0x000000010e4de1d1 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h718fa5631ce7ed57
frame #27 - 0x000000010e4deeb7 - _<F as std..boxed..FnBox<A>>::call_box::hf74656283ae82dd3
frame #28 - 0x000000010ff5b2c8 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
frame #29 - 0x00007fff8c64f99c - _pthread_body
frame #30 - 0x00007fff8c64f919 - _pthread_start

thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:785
stack backtrace:
   1:        0x10ff55f48 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:        0x10ff5c245 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:        0x10ff5be5e - std::panicking::default_hook::hc2c969e7453d080c
   4:        0x10f575f89 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h01133ea4cd6e4585
   5:        0x10f575e23 - _<std..thread..LocalKey<T>>::with::he9fc920aea584817
   6:        0x10f575c7a - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h7c8a22ebea1e52ef
   7:        0x10ff437d8 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   8:        0x10ff4510e - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
   9:        0x10ff55217 - rust_begin_unwind
  10:        0x10ff835f0 - core::panicking::panic_fmt::h257ceb0aa351d801
  11:        0x10e111020 - core::result::unwrap_failed::h1e84586c8358d3d5
  12:        0x10e110dac - _<core..result..Result<T, E>>::unwrap::h38e0570cfc9e2572
  13:        0x10e305105 - script::dom::node::OpaqueStyleAndLayoutData::dispose::h99262ad8405b7189
  14:        0x10e304fa9 - _<dom..node..Node as core..ops..Drop>::drop::_$u7b$$u7b$closure$u7d$$u7d$::h27ca9b8799276ab1
  15:        0x10e304f40 - _<core..option..Option<T>>::map::h1d213472f3cd1c1e
  16:        0x10dbcce7b - _<dom..node..Node as core..ops..Drop>::drop::he5926dc01e64649a
  17:        0x10dbccdff - dom..node..Node::drop.123114::h0b3927c365ecc170
  18:        0x10dbccda9 - dom..characterdata..CharacterData::drop.123111::hdecddd04bfe717a2
  19:        0x10df1a585 - dom..text..Text::drop.135568::h547f4e4ce3a436e0
  20:        0x10df1a561 - Box<dom..text..Text>::drop.135565::h915ee96e555893a6
  21:        0x10df19114 - script::dom::bindings::codegen::Bindings::TextBinding::_finalize::hb3264ecc95d58700
  22:        0x10fb4d1bf - _ZN2js2gc5Arena8finalizeI8JSObjectEEmPNS_6FreeOpENS0_9AllocKindEm
  23:        0x10fb0620e - _ZL14FinalizeArenasPN2js6FreeOpEPPNS_2gc11ArenaHeaderERNS2_15SortedArenaListENS2_9AllocKindERNS_11SliceBudgetENS2_10ArenaLists14KeepArenasEnumE
  24:        0x10fb09975 - _ZN2js2gc10ArenaLists30queueForegroundObjectsForSweepEPNS_6FreeOpE
  25:        0x10fb0f7d3 - _ZN2js2gc9GCRuntime22beginSweepingZoneGroupEv
  26:        0x10fb10424 - _ZN2js2gc9GCRuntime15beginSweepPhaseEb
  27:        0x10fb12aca - _ZN2js2gc9GCRuntime23incrementalCollectSliceERNS_11SliceBudgetEN2JS8gcreason6ReasonE
  28:        0x10fb131d4 - _ZN2js2gc9GCRuntime7gcCycleEbRNS_11SliceBudgetEN2JS8gcreason6ReasonE
  29:        0x10fb1369e - _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetEN2JS8gcreason6ReasonE
  30:        0x10fac18da - _ZN2js14DestroyContextEP9JSContextNS_18DestroyContextModeE
  31:        0x10f6240e8 - _<rust..Runtime as std..ops..Drop>::drop::h57f859df41293d7d
  32:        0x10dc27f0c - js..rust..Runtime::drop.124357::h1abc9880d5d586b3
  33:        0x10dfc205f - _<std..rc..Rc<T> as core..ops..Drop>::drop::hafec68e7e99a5651
  34:        0x10dfc1fad - std..rc..Rc<js..rust..Runtime>::drop.137976::h6d9a0ad7e5823bd3
  35:        0x10e4e38b4 - script_thread..ScriptThread::drop_contents.157448::h18d9819c572a76ab
  36:        0x10e4e36db - script_thread..ScriptThread::drop.157445::h18d9819c572a76ab
  37:        0x10e4e1fb8 - _<script_thread..ScriptThread as script_traits..ScriptThreadFactory>::create::_$u7b$$u7b$closure$u7d$$u7d$::h376836bb503682b7
  38:        0x10e4decd0 - util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::heb59eb3e917c5b06
  39:        0x10e4de4f3 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h5451e0f5cc8da44b
  40:        0x10e4de468 - std::sys_common::unwind::try::try_fn::hca2f304c46ad6472
  41:        0x10ff551ab - __rust_try
  42:        0x10ff55133 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  43:        0x10e4de3a5 - std::sys_common::unwind::try::h9b69ed8320487131
  44:        0x10e4de1d1 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h718fa5631ce7ed57
  45:        0x10e4deeb7 - _<F as std..boxed..FnBox<A>>::call_box::hf74656283ae82dd3
  46:        0x10ff5b2c8 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  47:     0x7fff8c64f99c - _pthread_body
  48:     0x7fff8c64f919 - _pthread_start
thread panicked while panicking. aborting.
Servo exited with return value -4
```

**Comment by KiChjang** [comment] 2016-05-03 03:49
Is this #8461 all over again?

**Comment by ConnorGBrewster** [comment] 2016-05-03 03:52
@KiChjang hmm it seems to happen when just navigating backwards without any other action.

**Comment by jdm** [comment] 2016-05-03 04:21
Duplicate of #9984. Thanks for filing it!

**Closed by jdm** 2016-05-03 04:21 UTC
