### ISSUE TITLE
Trouble with starting servo on ssh X11 forwarding

### ISSUE THREAD

**Issue by Disinterpreter** [servo/servo#12476] opened 2016-07-17 11:03 UTC
Trouble with starting servo on ssh X11 forwarding

Details:
`disi@ubuntu:~/servo$ ./servo
Xlib:  extension "XFree86-VidModeExtension" missing on display "localhost:10.0".
thread 'main' panicked at 'Failed to create window.: NoAvailablePixelFormat', ../src/libcore/result.rs:785
note: Run with RUST_BACKTRACE=1 for a backtrace.
`

**Comment by dralley** [comment] 2020-04-01 19:59
Duplicate of https://github.com/servo/servo/issues/13018

(Not strictly, the error is different, but after 4 years the exact error probably isn't relevant anyways.)

Should probably just close this one and track it in one place, if it's still an issue.  X11 forwarding is kind of tricky anyways due to the whole extension mismatch nonsense you have to deal with, so it's not necessarily clear that there is a problem with Servo here.

**Closed** 2020-04-02 11:28 UTC
Labels: I-crash, P-linux
