### ISSUE TITLE
[glutin] x error code=21 major=0 minor=0!

### ISSUE THREAD

**Issue by ivanceras** [servo/servo#6221] opened 2015-05-30 07:40 UTC
I have been following the servo project, but just these few days ago. I can't launch the application anymore.
I always get this glutin error.
I tried it in both of my ubuntu 14.04 workstation, still with the same error.
I also tried doing a fresh git clone, but still got these errors. 

```
uname -a
3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

git pull
./mach build --release

 ./mach run --release tests/html/about-mozilla.html 
[glutin] x error code=21 major=0 minor=0!
[glutin] x error code=22 major=0 minor=0!
[glutin] x error code=23 major=0 minor=0!
[glutin] x error code=26 major=0 minor=0!
[glutin] x error code=27 major=0 minor=0!
[glutin] x error code=28 major=0 minor=0!
[glutin] x error code=30 major=0 minor=0!
[glutin] x error code=33 major=0 minor=0!
[glutin] x error code=48 major=0 minor=0!
thread '<main>' panicked at 'glx::MakeCurrent failed', <...>/servo/.cargo/git/checkouts/glutin-72cd277ab8976bc1/servo/src/x11/window/mod.rs:744
stack backtrace:
   1:     0x7ffa66ca8b69 - sys::backtrace::write::h9171395a47d14ae0h5r
   2:     0x7ffa66cac541 - panicking::on_panic::h3eccc9536989cb30gKw
   3:     0x7ffa66c977f2 - rt::unwind::begin_unwind_inner::h79606db69425a69dqpw
   4:     0x7ffa66676c7e - rt::unwind::begin_unwind::h7167419927025130338
   5:     0x7ffa66679830 - platform::window::Window::make_current::h19a11cc5ec2c998039b
   6:     0x7ffa665d74fe - window::Window::new::h0136f75b79aac4acUna
   7:     0x7ffa65b8296d - main::h3d82ced378541a43paa
   8:     0x7ffa66cb1578 - rust_try_inner
   9:     0x7ffa66cb1565 - rust_try
  10:     0x7ffa66cadd93 - rt::lang_start::h99d1ebf57aaefbc8LEw
  11:     0x7ffa642ceec4 - __libc_start_main
  12:     0x7ffa65b81f88 - <unknown>
  13:                0x0 - <unknown>
[glutin] x error code=50 major=0 minor=0!
Error running mach:

    ['run', '--release', 'tests/html/about-mozilla.html']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'components/servo/target/release/servo', 'tests/html/about-mozilla.html']' returned non-zero exit status 101

  File "<..>/servo/python/servo/post_build_commands.py", line 117, in run
    subprocess.check_call(args, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)


```

**Comment by jdm** [comment] 2015-05-30 19:33
Looks like a duplicate of #6042.

**Comment by nox** [comment] 2015-06-02 10:19
Yes it does. Closing.

**Closed by nox** 2015-06-02 10:19 UTC
Labels: C-duplicate
