### ISSUE TITLE
assertion failed: count_cell.get() > 0

### ISSUE THREAD

**Issue by runarberg** [servo/servo#12117] opened 2016-07-01 19:11 UTC
assertion failed: count_cell.get() > 0
### URL:
http://manisananimal.nfshost.com/
### Backtrace:
```
frame #0  - 0x00000001104d86ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x00000001104d8651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000000010f7a9086 - _<F as alloc..boxed..FnBox<A>>::call_box::h6059122298f825d8
frame #3  - 0x000000011044c947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x00000001106c0844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000000010efc3ae4 - std::panicking::begin_panic::h0bf39f6d43ab9349
frame #6  - 0x000000010f650262 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h315c5e417b85cb3a
frame #7  - 0x000000010f64dd65 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::hc0416bc7ab472afc
frame #8  - 0x000000010f7b495c - script::script_thread::ScriptThread::handle_msg_from_script::hd1f5e7b2423a8c64
frame #9  - 0x000000010f810a71 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc67d8b381c013b79
frame #10 - 0x000000010f7f673f - script::script_thread::ScriptThread::handle_msgs::h236c5be60a207bea
frame #11 - 0x000000010f7a7907 - std::panicking::try::call::h645a328f039d97c6
frame #12 - 0x00000001106dc46b - __rust_try
frame #13 - 0x00000001106dc405 - __rust_maybe_catch_panic
frame #14 - 0x000000010f7a8ab4 - _<F as alloc..boxed..FnBox<A>>::call_box::h3db95636eb747818
frame #15 - 0x00000001106d7ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #16 - 0x00007fff8e46a99c - _pthread_body
frame #17 - 0x00007fff8e46a919 - _pthread_start

```

This was automatically filled out.

**Comment by ConnorGBrewster** [comment] 2016-07-01 19:13
Thank you for the report!
Closing as a dupe of #12047.

**Closed by ConnorGBrewster** 2016-07-01 19:13 UTC
