### ISSUE TITLE
Implement parsing and stylo glue support for legacy gradients

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#15895] opened 2017-03-09 23:36 UTC
See https://bugzilla.mozilla.org/show_bug.cgi?id=1345204#c1

Gecko supports legacy gradients, we should be parsing these. The comment linked to above gives an idea of what needs to be supported.

They probably need to be stored as extra variants on our gradient enum, and when sending to gecko they need to set the legacy gradient flag.

cc @canaltinova

**Comment by upsuper** [comment] 2017-03-11 21:48
Dupe of #15441.

**Closed by upsuper** 2017-03-11 21:48 UTC
Labels: A-content/css, A-stylo, E-less easy
