### ISSUE TITLE
Github block quotes are too narrow

### ISSUE THREAD

**Issue by samlh** [servo/servo#13223] opened 2016-09-10 20:14 UTC
![image](https://cloud.githubusercontent.com/assets/118173/18413117/23af246e-7754-11e6-887b-8d9f466d366f.png)

https://github.com/servo/servo/pull/12989#issuecomment-244847425

Interestingly, the blocks get narrower the further down the page they are.

**Comment by notriddle** [comment] 2016-09-15 08:22
It's float prediction:

```html
<!doctype html>
<style>
.a {
height: 20px;
}
.b {
height: 10px;
width: 50px;
float: right;
}
.c {
border: solid 1px #000;
background: red;
height: 10px;
overflow: auto
}
</style>
<div class=a></div> <!-- represent the header in the Github toolbar -->
<div class=b></div> <!-- represent the buttons in the Github toolbar -->
<div class=a></div>
<div class=b></div>
<div class=a></div>
<div class=b></div>
<div class=c></div> <!-- represent the contents. Notice the lack of a clear -->
```

@pcwalton Weren't you working on a fix for the whole "floats' heights affect the layout of their siblings" problem?

**Comment by notriddle** [comment] 2016-09-15 08:34
More specifically, is this a duplicate of #7551?

**Comment by pcwalton** [comment] 2016-09-15 20:29
It's not—we need to implement the fallback when the speculation fails.

**Comment by notriddle** [comment] 2016-09-15 20:33
Is there already an issue for that?

**Comment by notriddle** [comment] 2016-09-15 20:42
#13284

**Closed** 2016-09-29 19:28 UTC
Labels: A-layout/floats, C-has-test
