### ISSUE TITLE
browser.html displays a blank window

### ISSUE THREAD

**Issue by fabricedesre** [servo/servo#14919] opened 2017-01-09 04:27 UTC
Tested on a release Linux build, when starting with ./mach -r -b 
The main window opens but doesn't display anything.

@paulrouget does that ring a bell?

**Comment by paulrouget** [comment] 2017-01-09 05:05
Same issue here. I'll look for the regression window.

**Comment by paulrouget** [comment] 2017-01-09 08:27
I take that back. I can't reproduce.

@fabricedesre Any message in the terminal?

**Comment by fabricedesre** [comment] 2017-01-09 15:46
No messages by default. When enabling debug logs, I get that:
```
fabrice@fabrice-ThinkPad-X260:~/dev/servo$ RUST_LOG=debug ./mach run -b -r
WARN:constellation::frame: Frame FrameId { namespace_id: PipelineNamespaceId(0), index: FrameIndex(0) } iterated after closure.
WARN:constellation::frame: Frame FrameId { namespace_id: PipelineNamespaceId(0), index: FrameIndex(0) } iterated after closure.
INFO:style::error_reporting: 51:3 Unsupported property declaration: 'width: fit-content;'
INFO:style::error_reporting: 52:3 Unsupported property declaration: 'height: fit-content;'
INFO:style::error_reporting: 60:1 Invalid rule: 'dialog::backdrop {'
INFO:style::error_reporting: 69:3 Unsupported rule: 'dialog:modal {'
INFO:style::error_reporting: 87:8 Unsupported property declaration: 'display: ruby;'
INFO:style::error_reporting: 88:6 Unsupported property declaration: 'display: ruby-text;'
INFO:style::error_reporting: 110:31 Unsupported property declaration: 'text-decoration: dotted underline;'
INFO:style::error_reporting: 122:7 Unsupported property declaration: 'display-outside: break-opportunity;'
INFO:style::error_reporting: 126:1 Invalid rule: '[dir]:dir(ltr), bdi:dir(ltr), input[type=tel]:dir(ltr) {'
INFO:style::error_reporting: 127:1 Invalid rule: '[dir]:dir(rtl), bdi:dir(rtl) {'
INFO:style::error_reporting: 153:1 Invalid rule: ':matches(article, aside, nav, section) h1 {'
INFO:style::error_reporting: 154:1 Invalid rule: ':matches(article, aside, nav, section) :matches(article, aside, nav, section) h1 {'
INFO:style::error_reporting: 155:1 Invalid rule: ':matches(article, aside, nav, section) :matches(article, aside, nav, section) :matches(article, aside, nav, section) h1 {'
INFO:style::error_reporting: 156:1 Invalid rule: ':matches(article, aside, nav, section) :matches(article, aside, nav, section) :matches(article, aside, nav, section) :matches(article, aside, nav, section) h1 {'
INFO:style::error_reporting: 157:1 Invalid rule: ':matches(article, aside, nav, section) :matches(article, aside, nav, section) :matches(article, aside, nav, section) :matches(article, aside, nav, section) :matches(article, aside, nav, section) h1 {'
INFO:style::error_reporting: 159:1 Invalid rule: ':matches(article, aside, nav, section) hgroup > h1 ~ h2 {'
INFO:style::error_reporting: 160:1 Invalid rule: ':matches(article, aside, nav, section) :matches(article, aside, nav, section) hgroup > h1 ~ h2 {'
INFO:style::error_reporting: 161:1 Invalid rule: ':matches(article, aside, nav, section) :matches(article, aside, nav, section) :matches(article, aside, nav, section) hgroup > h1 ~ h2 {'
INFO:style::error_reporting: 162:1 Invalid rule: ':matches(article, aside, nav, section) :matches(article, aside, nav, section) :matches(article, aside, nav, section) :matches(article, aside, nav, section) hgroup > h1 ~ h2 {'
INFO:style::error_reporting: 164:1 Invalid rule: ':matches(article, aside, nav, section) hgroup > h1 ~ h3 {'
INFO:style::error_reporting: 165:1 Invalid rule: ':matches(article, aside, nav, section) :matches(article, aside, nav, section) hgroup > h1 ~ h3 {'
INFO:style::error_reporting: 166:1 Invalid rule: ':matches(article, aside, nav, section) :matches(article, aside, nav, section) :matches(article, aside, nav, section) hgroup > h1 ~ h3 {'
INFO:style::error_reporting: 168:1 Invalid rule: ':matches(article, aside, nav, section) hgroup > h1 ~ h4 {'
INFO:style::error_reporting: 169:1 Invalid rule: ':matches(article, aside, nav, section) :matches(article, aside, nav, section) hgroup > h1 ~ h4 {'
INFO:style::error_reporting: 171:1 Invalid rule: ':matches(article, aside, nav, section) hgroup > h1 ~ h5 {'
INFO:style::error_reporting: 179:1 Invalid rule: ':matches(dir, dl, menu, ol, ul) :matches(dir, dl, menu, ol, ul) {'
INFO:style::error_reporting: 190:1 Invalid rule: ':matches(dir, menu, ol, ul) :matches(dir, menu, ul) {'
INFO:style::error_reporting: 194:1 Invalid rule: ':matches(dir, menu, ol, ul) :matches(dir, menu, ol, ul) :matches(dir, menu, ul) {'
INFO:style::error_reporting: 211:3 Unsupported property declaration: 'visibility: collapse;'
INFO:style::error_reporting: 229:1 Invalid rule: 'table:matches(
  [rules=none i], [rules=groups i], [rules=rows i],
  [rules=cols i], [rules=all i],
  [frame=void i], [frame=above i], [frame=below i],
  [frame=hsides i], [frame=lhs i], [frame=rhs i],
  [frame=vsides i], [frame=box i], [frame=border i]
),
table:matches(
  [rules=none i], [rules=groups i], [rules=rows i],
  [rules=cols i], [rules=all i]
) > tr > :matches(td, th),
table:matches(
  [rules=none i], [rules=groups i], [rules=rows i],
  [rules=cols i], [rules=all i]
) > :matches(thead, tbody, tfoot) > tr > :matches(td, th) {'
INFO:style::error_reporting: 248:1 Invalid rule: ':matches(table, thead, tbody, tfoot, tr) > form {'
INFO:style::error_reporting: 274:3 Unsupported property declaration: 'border-color: ThreeDFace;'
INFO:style::error_reporting: 276:3 Unsupported property declaration: 'min-width: min-content;'
INFO:style::error_reporting: 285:9 Unsupported property declaration: 'object-fit: contain;'
INFO:style::error_reporting: 304:3 Unsupported property declaration: 'object-fit:contain;'
INFO:style::error_reporting: 21:1 Invalid rule: 'ol[type=1], li[type=1] {'
INFO:style::error_reporting: 24:26 Unsupported property declaration: 'list-style-type: lower-roman;'
INFO:style::error_reporting: 25:26 Unsupported property declaration: 'list-style-type: upper-roman;'
INFO:style::error_reporting: 35:1 Invalid rule: ':matches(thead, tbody, tfoot, tr, td, th)[align=absmiddle i] {'
INFO:script_layout_interface::reporter: 4:3 Unsupported @font-face descriptor declaration: 'font-weight: normal;'
INFO:script_layout_interface::reporter: 5:3 Unsupported @font-face descriptor declaration: 'font-style: normal;'
INFO:script_layout_interface::reporter: 10:3 Unsupported property declaration: '-moz-appearance: none;'
INFO:script_layout_interface::reporter: 27:1 Invalid rule: '*::-moz-focus-inner {'
INFO:script_layout_interface::reporter: 73:1 Invalid rule: 'progress::-webkit-progress-inner-element,
progress::-webkit-progress-bar {'
INFO:script_layout_interface::reporter: 81:1 Invalid rule: 'progress::-webkit-progress-value {'
INFO:script_layout_interface::reporter: 85:1 Invalid rule: 'progress::-moz-progress-bar {'
WARN:script::dom::htmlscriptelement: error loading script Internal("Network error")
WARN:html5ever::tree_builder::actions: stop_parsing not implemented, full speed ahead!
INFO:script::dom::window: script: waiting on layout
WARN:constellation::constellation: Pipeline (0,1) has no parent.
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
...
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
INFO:script::dom::window: script: waiting on layout
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
...
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
INFO:script::dom::bindings::refcounted: tracing live refcounted references
INFO:script::dom::bindings::refcounted: removing 4 refcounted references
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:glutin_app::window: Window event stream closed.
WARN:profile_traits::mem: Error communicating with the memory profiler thread: Broken pipe (os error 32)
WARN:profile_traits::mem: Error communicating with the memory profiler thread: Broken pipe (os error 32)
WARN:glutin_app::window: Window event stream closed.
INFO:script::dom::bindings::refcounted: tracing live refcounted references
INFO:script::dom::bindings::refcounted: removing 0 refcounted references
WARN:constellation::timer_scheduler: TimerProxy thread terminated.
```

**Comment by paulrouget** [comment] 2017-01-10 07:31
@fabricedesre Only with bhtml?

**Comment by fabricedesre** [comment] 2017-01-10 15:38
Yes, loading a url directly works as expected.

**Comment by rookwood101** [comment] 2017-01-11 15:21
I think I know why this is happening. After looking at the browser.html resources, some of them appear to have upper case letters, but the files are being linked to using lower case only. Therefore on Windows everything might work fine, however on Linux, it being case sensitive, the page is not loading.

**Comment by fabricedesre** [comment] 2017-01-11 15:47
You may be right. Damn OS/X case insensitive FS. There was massive renaming in https://github.com/browserhtml/browserhtml/commit/e81dc431d1ac3c283b15bd1aa281e10d7e498f6e and I did not check everything but that's likely the culprit.

**Comment by Gozala** [comment] 2017-01-12 16:31
> You may be right. Damn OS/X case insensitive FS.

I've being burned by that too many times :(

> There was massive renaming in browserhtml/browserhtml@e81dc43 and I did not check everything but that's likely the culprit.

In fact those paths are irrelevant as during deployment they get bundled into a single js file and pushed to [cargo branch](https://github.com/browserhtml/browserhtml/tree/crate) as such. Only thing that could be and turns out is the problem is that path to that `.js` file was not updated in [index.html](https://github.com/browserhtml/browserhtml/blob/master/index.html#L23). 

I have submitted a fix browserhtml/browserhtml#1263

**Comment by paulrouget** [comment] 2017-01-13 01:45
Fixed by https://github.com/browserhtml/browserhtml/pull/1263

**Closed** 2017-01-13 01:45 UTC

**Comment by fabricedesre** [comment] 2017-01-13 05:39
That still needs a cargo update in servo no?
https://github.com/servo/servo/blob/master/Cargo.lock#L233 still points to https://github.com/browserhtml/browserhtml/commit/cbb020096c77f5d2547e575c0e19003a6d2a614a

**Comment by paulrouget** [comment] 2017-01-13 05:52
Yep. Thanks for the PR.
