### ISSUE TITLE
Why dev mode run 'hello world' so slow

### ISSUE THREAD

**Issue by sunxfancy** [servo/servo#9288] opened 2016-01-13 09:41 UTC
I build servo in dev mode, and run the `tests/html/hello.html`. It costs 30+s to render it.
In release mode, it costs 2s.
I'd like to know why and work with the Performance issues, please help me have a start.

**Comment by sunxfancy** [comment] 2016-01-13 10:25
```
sxf@sxf-PC:/mnt/data/workspace/Rust/servo$ ./mach run --dev tests/html/hello.html -p 1
_category_                          _incremental?_ _iframe?_             _url_                  _mean (ms)_   _median (ms)_      _min (ms)_      _max (ms)_       _events_ 
Compositing                             N/A          N/A                  N/A                        0.0531          0.0438          0.0012          0.1660               4

_category_                          _incremental?_ _iframe?_             _url_                  _mean (ms)_   _median (ms)_      _min (ms)_      _max (ms)_       _events_ 
Compositing                             N/A          N/A                  N/A                        0.2745          0.0438          0.0012          1.1604               5
Layout                                  yes          yes     file:///mnt/data/workspace/Rus          1.3036          1.3036          1.3036          1.3036               1
Layout                                  no           yes     file:///mnt/data/workspace/Rus      18685.9941      18685.9941      18685.9941      18685.9941               1
+ Style Recalc                          no           yes     file:///mnt/data/workspace/Rus      18682.0973      18682.0973      18682.0973      18682.0973               1
| + Text Shaping                        no           yes     file:///mnt/data/workspace/Rus          0.0447          0.0447          0.0447          0.0447               1
+ Restyle Damage Propagation            yes          yes     file:///mnt/data/workspace/Rus          0.0027          0.0027          0.0027          0.0027               1
+ Restyle Damage Propagation            no           yes     file:///mnt/data/workspace/Rus          0.0061          0.0061          0.0061          0.0061               1
+ Generated Content Resolution          yes          yes     file:///mnt/data/workspace/Rus          0.0022          0.0022          0.0022          0.0022               1
+ Generated Content Resolution          no           yes     file:///mnt/data/workspace/Rus          0.4341          0.4341          0.4341          0.4341               1
+ Primary Layout Pass                   yes          yes     file:///mnt/data/workspace/Rus          1.0216          1.0216          1.0216          1.0216               1
+ Primary Layout Pass                   no           yes     file:///mnt/data/workspace/Rus          1.4170          1.4170          1.4170          1.4170               1
| + Parallel Warmup                     yes          yes     file:///mnt/data/workspace/Rus          0.0012          0.0012          0.0012          0.0012               1
| + Parallel Warmup                     no           yes     file:///mnt/data/workspace/Rus          0.0047          0.0047          0.0047          0.0047               1
+ Display List Construction             yes          yes     file:///mnt/data/workspace/Rus          0.0634          0.0634          0.0634          0.0634               1
+ Display List Construction             no           yes     file:///mnt/data/workspace/Rus          0.1235          0.1235          0.1235          0.1235               1
+ Painting Per Tile                     N/A          N/A                  N/A                        3.5311          0.0763          0.0211         14.0032               4
Painting                                N/A          N/A                  N/A                       16.7982         16.7982         16.7982         16.7982               1
```

**Comment by jdm** [comment] 2016-01-13 14:49
Huh, 18s for style recalculation, according to that profile.

**Comment by metajack** [comment] 2016-01-13 15:23
Both those times are way too slow, release and debug.

But man, that style recalc time is insane!

cc @pcwalton

**Comment by shssoichiro** [comment] 2016-01-14 03:22
@sunxfancy What platform are you on (OS, CPU, RAM)? My results are much different on OS X 10.11.

    $ ./mach run --dev tests/html/hello.html -p 1
    _category_                          _incremental?_ _iframe?_             _url_                  _mean (ms)_   _median (ms)_      _min (ms)_      _max (ms)_       _events_
    Compositing                             N/A          N/A                  N/A                        1.6965          3.2707          0.1223          3.2707               2
    Layout                                  yes          yes     file:///Users/holmerj/Document          0.7109          0.7109          0.7109          0.7109               1
    Layout                                  no           yes     file:///Users/holmerj/Document         11.8227         11.8227         11.8227         11.8227               1
    + Style Recalc                          no           yes     file:///Users/holmerj/Document          7.1599          7.1599          7.1599          7.1599               1
    | + Text Shaping                        no           yes     file:///Users/holmerj/Document          0.0733          0.0733          0.0733          0.0733               1
    + Restyle Damage Propagation            yes          yes     file:///Users/holmerj/Document          0.0032          0.0032          0.0032          0.0032               1
    + Restyle Damage Propagation            no           yes     file:///Users/holmerj/Document          0.0030          0.0030          0.0030          0.0030               1
    + Generated Content Resolution          yes          yes     file:///Users/holmerj/Document          0.0033          0.0033          0.0033          0.0033               1
    + Generated Content Resolution          no           yes     file:///Users/holmerj/Document          0.2901          0.2901          0.2901          0.2901               1
    + Primary Layout Pass                   yes          yes     file:///Users/holmerj/Document          0.4048          0.4048          0.4048          0.4048               1
    + Primary Layout Pass                   no           yes     file:///Users/holmerj/Document          1.7917          1.7917          1.7917          1.7917               1
    | + Parallel Warmup                     yes          yes     file:///Users/holmerj/Document          0.0017          0.0017          0.0017          0.0017               1
    | + Parallel Warmup                     no           yes     file:///Users/holmerj/Document          0.0067          0.0067          0.0067          0.0067               1
    + Display List Construction             yes          yes     file:///Users/holmerj/Document          0.0837          0.0837          0.0837          0.0837               1
    + Display List Construction             no           yes     file:///Users/holmerj/Document          0.1416          0.1416          0.1416          0.1416               1
    + Painting Per Tile                     N/A          N/A                  N/A                        0.2945          0.0269          0.0181          3.1922              12
    Painting                                N/A          N/A                  N/A                      137.7863        137.7863        137.7863        137.7863               1

**Comment by sunxfancy** [comment] 2016-01-14 03:31
Ubuntu 14.04
core: 3.13.0-74-generic
Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
x86_64 architecture
8G RAM
@shssoichiro

**Comment by sunxfancy** [comment] 2016-01-14 03:34
Maybe we can run the performance tests on travis-ci, it has the same architecture as my computer.

**Comment by farodin91** [comment] 2016-05-14 16:54
My servo is also slow on my pc.
```./mach
 run --dev tests/html/hello.html -p 1                                          :(
_category_                          _incremental?_ _iframe?_             _url_                  _mean (ms)_   _median (ms)_      _min (ms)_      _max (ms)_       _events_ 
Compositing                             N/A          N/A                  N/A                        0.0387          0.0731          0.0043          0.0731               2
+ Style Recalc                          no           yes     file:///home/farodin91/Git/ser        271.6309        271.6309        271.6309        271.6309               1
| + Text Shaping                        no           yes     file:///home/farodin91/Git/ser          0.1984          0.1984          0.1984          0.1984               1
+ Restyle Damage Propagation            no           yes     file:///home/farodin91/Git/ser          0.0054          0.0054          0.0054          0.0054               1
+ Generated Content Resolution          no           yes     file:///home/farodin91/Git/ser          0.4654          0.4654          0.4654          0.4654               1
+ Float Placement Speculation           no           yes     file:///home/farodin91/Git/ser          0.0151          0.0151          0.0151          0.0151               1
| + Parallel Warmup                     no           yes     file:///home/farodin91/Git/ser          0.0039          0.0039          0.0039          0.0039               1

_category_                          _incremental?_ _iframe?_             _url_                  _mean (ms)_   _median (ms)_      _min (ms)_      _max (ms)_       _events_ 
Compositing                             N/A          N/A                  N/A                       11.7973         16.4365          0.0043         30.6753               4
Layout                                  yes          yes     file:///home/farodin91/Git/ser          0.3345          0.3285          0.2713          0.4580               5
Layout                                  no           yes     file:///home/farodin91/Git/ser        614.6039        614.6039        614.6039        614.6039               1
+ Style Recalc                          no           yes     file:///home/farodin91/Git/ser        271.6309        271.6309        271.6309        271.6309               1
| + Text Shaping                        no           yes     file:///home/farodin91/Git/ser          0.1984          0.1984          0.1984          0.1984               1
+ Restyle Damage Propagation            yes          yes     file:///home/farodin91/Git/ser          0.0067          0.0065          0.0044          0.0093               5
+ Restyle Damage Propagation            no           yes     file:///home/farodin91/Git/ser          0.0054          0.0054          0.0054          0.0054               1
+ Generated Content Resolution          yes          yes     file:///home/farodin91/Git/ser          0.0051          0.0044          0.0040          0.0066               5
+ Generated Content Resolution          no           yes     file:///home/farodin91/Git/ser          0.4654          0.4654          0.4654          0.4654               1
+ Float Placement Speculation           yes          yes     file:///home/farodin91/Git/ser          0.0005          0.0005          0.0003          0.0006               5
+ Float Placement Speculation           no           yes     file:///home/farodin91/Git/ser          0.0151          0.0151          0.0151          0.0151               1
+ Primary Layout Pass                   no           yes     file:///home/farodin91/Git/ser        339.8111        339.8111        339.8111        339.8111               1
+ Store Overflow                        yes          yes     file:///home/farodin91/Git/ser          0.0015          0.0012          0.0011          0.0022               5
+ Store Overflow                        no           yes     file:///home/farodin91/Git/ser          0.0198          0.0198          0.0198          0.0198               1
| + Parallel Warmup                     no           yes     file:///home/farodin91/Git/ser          0.0039          0.0039          0.0039          0.0039               1
+ Display List Construction             yes          yes     file:///home/farodin91/Git/ser          0.0061          0.0058          0.0013          0.0115               5
+ Display List Construction             no           yes     file:///home/farodin91/Git/ser          0.1141          0.1141          0.1141          0.1141               1
+ Painting Per Tile                     N/A          N/A                  N/A                        0.1519          0.0570          0.0230          0.9659              12
Painting                                N/A          N/A                  N/A                        7.4885          8.2567          0.0062         14.2028               3```

**Comment by farodin91** [comment] 2016-05-14 16:57
Arch linux
Intel® Core™ i7-965 Processor Extreme Edition (8M Cache, 3.20 GHz, 6.40 GT/s Intel® QPI)
x86_64 architecture
GPU: GTX 560 TI
6G RAM

**Comment by nox** [comment] 2017-09-30 22:00
Closing because the issue isn't much actionable. We are aware of pretty serious perf deficiencies in debug mode right now but we don't have the bandwidth to fix them at the moment.

**Closed by nox** 2017-09-30 22:00 UTC
Labels: I-perf-slow
