### ISSUE TITLE
Loading nytimes.com crashes servo

### ISSUE THREAD

**Issue by staktrace** [servo/servo#6480] opened 2015-06-26 20:36 UTC
I built servo using the tarball provided for the Whistler training session (OS X). When running the release build like so:

./mach run -r http://www.nytimes.com/ -Z show-parallel-layout

it would open the window, do some work, and then crash with the output:

kats@kgupta-air servo$ ./mach run -r http://www.nytimes.com
ERROR:js::rust: Error at http://a1.nyt.com/assets/homepage/20150615-165652/js/homepage/ad-loader.js:0: TypeError: document.write is not a function

Servo exited with return value -5

Running with --debug and dumping a backtrace in lldb gave me this:

```
Process 12020 stopped
thread #6: tid = 0x81a16f, 0x00007fff9a0fb4c4 CoreFoundation`CFRelease + 724, name = 'PaintWorker, stop reason = EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)
    frame #0: 0x00007fff9a0fb4c4 CoreFoundation`CFRelease + 724
CoreFoundation`CFRelease + 724:
-> 0x7fff9a0fb4c4:  jmp    0x7fff9a0fb4ca            ; CFRelease + 730
   0x7fff9a0fb4c6:  int3
   0x7fff9a0fb4c7:  jmp    0x7fff9a0fb4ca            ; CFRelease + 730
   0x7fff9a0fb4c9:  int3
(lldb) bt
thread #6: tid = 0x81a16f, 0x00007fff9a0fb4c4 CoreFoundation`CFRelease + 724, name = 'PaintWorker, stop reason = EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)
    frame #0: 0x00007fff9a0fb4c4 CoreFoundation`CFRelease + 724
    frame #1: 0x000000010127c03d servo`platform::surface::NativeSurface::upload::hb193b64744120d95T1b + 141
    frame #2: 0x0000000100fc5d25 servo`paint_task::WorkerThread::main::h912535136a6a86f3nTd + 8069
    frame #3: 0x0000000100fc3b77 servo`boxed::F.FnBox$LT$A$GT$::call_box::h14583547123408321915 + 919
    frame #4: 0x0000000100fc3188 servo`rt::unwind::try::try_fn::h16850418705927787855 + 88
    frame #5: 0x00000001014f6d09 servo`rust_try_inner + 9
    frame #6: 0x00000001014f6cf6 servo`rust_try + 6
    frame #7: 0x00000001014efa86 servo`rt::unwind::try::inner_try::h27133e9e14aca845Z7v + 134
    frame #8: 0x0000000100fc33e3 servo`boxed::F.FnBox$LT$A$GT$::call_box::h15197967370409347583 + 323
    frame #9: 0x00000001014f3a9e servo`sys::thread::Thread::new::thread_start::hd4ea41c9b4c4555dywv + 158
    frame #10: 0x00007fff8f865899 libsystem_pthread.dylib`_pthread_body + 138
    frame #11: 0x00007fff8f86572a libsystem_pthread.dylib`_pthread_start + 137
    frame #12: 0x00007fff8f869fc9 libsystem_pthread.dylib`thread_start + 13
```

**Comment by staktrace** [comment] 2015-06-26 20:43
Here's a backtrace from a debug build: https://gist.github.com/staktrace/fdc98cae963c1d7be1a0

**Comment by dzbarsky** [comment] 2015-07-18 21:11
Can you still reproduce this?  Seems like it works for me.

**Comment by mrobinson** [comment] 2016-04-12 17:59
@notriddle Do you think this is fixed by https://github.com/servo/rust-layers/commit/7556d2420c5afe95b23149289840c2dc659321fb?

**Comment by cyplo** [comment] 2017-06-17 18:24
Does this still reproduce ? (does not have Mac to see)

**Comment by staktrace** [comment] 2017-06-19 13:21
If I follow the STR now I get slightly different results. The window opens with some garbage but then the webpage gets painted. The console output shows a bunch of backtraces, but servo itself doesn't crash.. until I start scrolling. As soon as I scroll, the window closes and servo exits with return value 101. Here's the full output from the run, from servo cset e41b7d06b473544755902be2c1334a7622c84940

[servo.txt](https://github.com/servo/servo/files/1085025/servo.txt)

**Comment by nox** [comment] 2017-09-30 13:24
This doesn't crash anymore for me.

**Closed by nox** 2017-09-30 13:24 UTC
Labels: A-gfx/compositing, I-crash, P-mac
