### ISSUE TITLE
After a lot of scrolling, lines of text start to dance up and down by a single pixel.

### ISSUE THREAD

**Issue by jcdyer** [servo/servo#3534] opened 2014-09-30 20:14 UTC
When scrolling through a long page (http://en.wikipedia.org/wiki/Washington_Irving), lines of text start shifting up and down by one pixel.  Not all at once, each line shifts independently of the others.

It may be triggered by moving the window.  It also seems to peg the CPU for several (15-20) seconds.

Seen on a servo built from master checked out today.

Output: 

    work@waller:~/src/servo$ ./mach -lwashirv.log --verbose run http://en.wikipedia.org/wiki/Washington_Irving    
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    Bad header encountered. TODO: handle this better.
    ERROR:js::rust: Error at http://bits.wikimedia.org/en.wikipedia.org/load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector&*:1: TypeError: ua is undefined

    evaluate_script failed
    Bad header encountered. TODO: handle this better.

In spite of (trying to) enable verbose logging as specified in `mach run --help`, the logfile is created, but empty.

**Comment by mbrubeck** [comment] 2016-05-20 04:44
Can't reproduce this in more recent builds. Maybe fixed by #7161 and related changes.

**Closed by mbrubeck** 2016-05-20 04:44 UTC
Labels: A-layout/uncategorized, C-is-this-done, I-wrong
