### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "SendError(..)"

### ISSUE THREAD

**Issue by jlgeering** [servo/servo#17064] opened 2017-05-27 15:46 UTC
called `Result::unwrap()` on an `Err` value: "SendError(..)"
### Servo Version:
Servo 0.0.1-a03d0b8
### Backtrace:
```

WARNING: <Constellation>: creating replacement pipeline for about:failure
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }>: Resuming an already resumed timer.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: Panic hook called.
ERROR: called `Result::unwrap()` on an `Err` value: "SendError(..)"

stack backtrace:
   0:        0x107434b4e - backtrace::backtrace::trace::h1e1118131f7ae175
   1:        0x1074352ec - backtrace::capture::Backtrace::new::h5f3de869c0349b3d
   2:        0x10653ba36 - constellation::constellation::log_entry::h4fc38d97bd2942f8
   3:        0x10653aa42 - _$LT$constellation..constellation..FromCompositorLogger$u20$as$u20$log..Log$GT$::log::hf61ff9ca26ca376c
   4:        0x107ffea2e - log::__log::h9f11f10c4eda10fa
   5:        0x10636c6b0 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h3bf1221e86291536
   6:        0x10802ee36 - std::panicking::rust_panic_with_hook::h2bd2f0b446f0face
   7:        0x10802ec94 - std::panicking::begin_panic::h1732f61ecaaa434e
   8:        0x10802ec02 - std::panicking::begin_panic_fmt::h2948dd4668f99175
   9:        0x10802eb67 - rust_begin_unwind
  10:        0x108057030 - core::panicking::panic_fmt::hb2e726f3b579b19d
  11:        0x106b7f0e0 - core::result::unwrap_failed::h0e6b15fac8662022
  12:        0x106e43b6f - script::dom::window::Window::force_reflow::h296ce92397854efc
  13:        0x106e466dd - script::dom::window::Window::reflow::hd5b1aa57c50d46eb
  14:        0x106cabc00 - script::dom::cssstyledeclaration::CSSStyleDeclaration::get_property_value::h3d914ebd17af7807
  15:        0x1069f8cb0 - std::panicking::try::do_call::h37bad19d0c9dbb39
  16:        0x10802ff0a - __rust_maybe_catch_panic
  17:        0x106f12ebc - script::dom::bindings::codegen::Bindings::CSSStyleDeclarationBinding::CSSStyleDeclarationBinding::get_opacity::h93e7b47c22a7698d
  18:        0x106c58e71 - script::dom::bindings::utils::generic_call::hd175d46f42d77dda
  19:        0x107b2b63e - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
  20:        0x107b473ac - CallGetter(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::Value>, JS::Handle<js::Shape*>, JS::MutableHandle<JS::Value>)
  21:        0x107b41e2e - js::NativeGetProperty(JSContext*, JS::Handle<js::NativeObject*>, JS::Handle<JS::Value>, JS::Handle<jsid>, JS::MutableHandle<JS::Value>)
  22:        0x1079f6426 - JS_ForwardGetPropertyTo(JSContext*, JS::Handle<JSObject*>, JS::Handle<jsid>, JS::Handle<JS::Value>, JS::MutableHandle<JS::Value>)
  23:        0x106c582bf - script::dom::bindings::utils::get_property_on_prototype::h1ae4f1f613d25025
  24:        0x1069c7e7f - std::panicking::try::do_call::h1083874aa1826e5e
  25:        0x10802ff0a - __rust_maybe_catch_panic
  26:        0x106f4feea - script::dom::bindings::codegen::Bindings::CSSStyleDeclarationBinding::CSSStyleDeclarationBinding::get::hadbfa9adb80bcb59
  27:        0x1076c09cd - ForwardingProxyHandler::get(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::Value>, JS::Handle<jsid>, JS::MutableHandle<JS::Value>) const
  28:        0x107ac7815 - js::Proxy::get(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::Value>, JS::Handle<jsid>, JS::MutableHandle<JS::Value>)
  29:        0x107b4ca59 - js::GetProperty(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::Value>, JS::Handle<jsid>, JS::MutableHandle<JS::Value>)
  30:        0x107b2066b - Interpret(JSContext*, js::RunState&)
  31:        0x107b1851a - js::RunScript(JSContext*, js::RunState&)
  32:        0x107b2b992 - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
  33:        0x1077d7104 - js::jit::DoCallFallback(JSContext*, js::jit::BaselineFrame*, js::jit::ICCall_Fallback*, unsigned int, JS::Value*, JS::MutableHandle<JS::Value>)
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2017-05-29 02:25
Were there any actions you took on the website before this problem occurred? I haven't been able to reproduce it by loading arstechnica and scrolling up and down the page.

**Comment by jdm** [comment] 2017-05-29 06:23
```
ERROR:servo: called `Option::unwrap()` on a `None` value
servo was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 52429 stopped
* thread #29, stop reason = breakpoint 1.1
    frame #0: 0x0000000102466e94 servo`std::panicking::rust_panic at panicking.rs:580 [opt]
(lldb) bt
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
* thread #29, stop reason = breakpoint 1.1
  * frame #0: 0x0000000102466e94 servo`std::panicking::rust_panic at panicking.rs:580 [opt]
    frame #1: 0x0000000102466e54 servo`std::panicking::rust_panic_with_hook at panicking.rs:565 [opt]
    frame #2: 0x0000000102466c45 servo`std::panicking::begin_panic<collections::string::String> at panicking.rs:511 [opt]
    frame #3: 0x0000000102466bb3 servo`std::panicking::begin_panic_fmt at panicking.rs:495 [opt]
    frame #4: 0x0000000102466b18 servo`std::panicking::rust_begin_panic at panicking.rs:471 [opt]
    frame #5: 0x000000010248efe1 servo`core::panicking::panic_fmt at panicking.rs:69 [opt]
    frame #6: 0x000000010248eee5 servo`core::panicking::panic at panicking.rs:49 [opt]
    frame #7: 0x00000001009456e8 servo`script::dom::window::{{impl}}::handler [inlined] core::option::{{impl}}::unwrap<&alloc::rc::Rc<js::rust::Runtime>> at macros.rs:21 [opt]
    frame #8: 0x00000001009456dc servo`script::dom::window::{{impl}}::handler at window.rs:298 [opt]
    frame #9: 0x00000001009456cb servo`script::dom::window::{{impl}}::handler(self=&0x11ce7ad80) at window.rs:1951 [opt]
    frame #10: 0x0000000100995725 servo`script::script_thread::{{impl}}::handle_msg_from_script(self=<unavailable>, msg=<unavailable>) at script_thread.rs:1180 [opt]
    frame #11: 0x000000010098f825 servo`script::script_thread::{{impl}}::handle_msgs::{{closure}} at script_thread.rs:993 [opt]
    frame #12: 0x000000010098b0a1 servo`script::script_thread::{{impl}}::handle_msgs at script_thread.rs:1102 [opt]
    frame #13: 0x000000010098ae9e servo`script::script_thread::{{impl}}::handle_msgs(self=<unavailable>) at script_thread.rs:986 [opt]
    frame #14: 0x00000001004a5138 servo`std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> at script_thread.rs:826 [opt]
    frame #15: 0x00000001004a5130 servo`std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> [inlined] script::script_thread::{{impl}}::create::{{closure}}::{{closure}} at script_thread.rs:581 [opt]
    frame #16: 0x00000001004a5130 servo`std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> at mem.rs:63 [opt]
    frame #17: 0x00000001004a4fd9 servo`std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> at script_thread.rs:580 [opt]
    frame #18: 0x00000001004a4c2b servo`std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>(f=<unavailable>) at backtrace.rs:136 [opt]
    frame #19: 0x00000001004cee4e servo`std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> [inlined] std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()> at mod.rs:336 [opt]
    frame #20: 0x00000001004cee36 servo`std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> [inlined] std::panic::{{impl}}::call_once<(),closure> at panic.rs:296 [opt]
    frame #21: 0x00000001004cee36 servo`std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>(data=<unavailable>) at panicking.rs:454 [opt]
    frame #22: 0x0000000102467ebb servo`panic_unwind::__rust_maybe_catch_panic at lib.rs:98 [opt]
    frame #23: 0x000000010067c867 servo`alloc::boxed::{{impl}}::call_box<(),closure> at panicking.rs:433 [opt]
    frame #24: 0x000000010067c82c servo`alloc::boxed::{{impl}}::call_box<(),closure> [inlined] std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> at panic.rs:361 [opt]
    frame #25: 0x000000010067c82c servo`alloc::boxed::{{impl}}::call_box<(),closure> [inlined] std::thread::{{impl}}::spawn::{{closure}}<closure,()> at mod.rs:335 [opt]
    frame #26: 0x000000010067c7ee servo`alloc::boxed::{{impl}}::call_box<(),closure>(self=&0x1156a6000, args=<unavailable>) at boxed.rs:648 [opt]
    frame #27: 0x00000001024639f6 servo`std::sys::imp::thread::{{impl}}::new::thread_start [inlined] alloc::boxed::{{impl}}::call_once<(),()> at boxed.rs:658 [opt]
    frame #28: 0x00000001024639f3 servo`std::sys::imp::thread::{{impl}}::new::thread_start [inlined] std::sys_common::thread::start_thread at thread.rs:21 [opt]
    frame #29: 0x0000000102463980 servo`std::sys::imp::thread::{{impl}}::new::thread_start at thread.rs:84 [opt]
    frame #30: 0x000000010688e93b libsystem_pthread.dylib`_pthread_body + 180
    frame #31: 0x000000010688e887 libsystem_pthread.dylib`_pthread_start + 286
    frame #32: 0x000000010688e08d libsystem_pthread.dylib`thread_start + 13
(lldb) frame 8
frame #8: 0x00000001009456dc servo`script::dom::window::{{impl}}::handler at window.rs:298 [opt]
   295 	    }
   296
   297 	    pub fn get_cx(&self) -> *mut JSContext {
-> 298 	        self.js_runtime.borrow().as_ref().unwrap().cx()
   299 	    }
   300
   301 	    pub fn dom_manipulation_task_source(&self) -> DOMManipulationTaskSource {
```

**Comment by zspitzer** [comment] 2017-05-30 01:38
just tried the nightly build on win10 and opening the ars homepage froze/crashed my desktop

**Comment by jlgeering** [comment] 2017-05-31 06:20
no special actions, just opening the page (as far as I remember)

**Comment by nox** [comment] 2017-10-07 10:06
Closing as duplicate of #14958.

**Closed by nox** 2017-10-07 10:06 UTC
Labels: A-webcompat, C-reproduced, I-panic
