### ISSUE TITLE
Transform interpolation can panic

### ISSUE THREAD

**Issue by iwehrman** [servo/servo#12151] opened 2016-07-02 01:16 UTC
The following is reproducible every time on my system, a 5k iMac running OS X 10.11.5, running v0.0.1.

Here's a screenshot that seems to have slightly more info than the error report below:
http://cloud.wehrman.org/3O3L1I2K2Q12

---

called `Result::unwrap()` on an `Err` value: RecvError
### URL:
https://superhuman.com/
### Backtrace:
```
frame #0  - 0x00000001089906ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000000108990651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000000107c61086 - _<F as alloc..boxed..FnBox<A>>::call_box::h6059122298f825d8
frame #3  - 0x0000000108904947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x0000000108b78844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000000108b91786 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x0000000108b79e88 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x0000000108b913df - rust_begin_unwind
frame #8  - 0x0000000108bb8260 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x0000000107c2a255 - core::result::unwrap_failed::h36b4b47aa6131a86
frame #10 - 0x0000000107c3233b - script::dom::window::Window::new::hb9c0a7c2d1d19211
frame #11 - 0x0000000107cec2b9 - script::script_thread::ScriptThread::load::hc7bd59fe3f58ffd5
frame #12 - 0x0000000107b85ee5 - script::script_thread::ScriptThread::page_headers_available::h4d14d183813e4a0b
frame #13 - 0x0000000107b81701 - _<script..dom..servohtmlparser..ParserContext as net_traits..AsyncResponseListener>::headers_available::h08671b4eed0191cf
frame #14 - 0x0000000107cf2e28 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::ha2200b1de782800b
frame #15 - 0x0000000107c6c95c - script::script_thread::ScriptThread::handle_msg_from_script::hd1f5e7b2423a8c64
frame #16 - 0x0000000107cc8a71 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc67d8b381c013b79
frame #17 - 0x0000000107cae73f - script::script_thread::ScriptThread::handle_msgs::h236c5be60a207bea
frame #18 - 0x0000000107c5f907 - std::panicking::try::call::h645a328f039d97c6
frame #19 - 0x0000000108b9446b - __rust_try
frame #20 - 0x0000000108b94405 - __rust_maybe_catch_panic
frame #21 - 0x0000000107c60ab4 - _<F as alloc..boxed..FnBox<A>>::call_box::h3db95636eb747818
frame #22 - 0x0000000108b8fee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #23 - 0x00007fff8862299c - _pthread_body
frame #24 - 0x00007fff88622919 - _pthread_start

```

**Comment by ConnorGBrewster** [comment] 2016-07-02 01:18
Thank you for this report!
Closing as a dupe of  #12135.

**Comment by jdm** [comment] 2016-07-02 02:46
I don't see any evidence that this is a duplicate of that one. The acid3 failure is well-known and has lots of duplicates filed, but the underlying cause of the panic here hasn't been determined.

**Comment by jdm** [comment] 2016-07-02 02:48
```
  * frame #0: 0x00000001048eda90 servo`rust_panic
    frame #1: 0x00000001048e362d servo`std::panicking::rust_panic_with_hook::h983af77c1a2e581b + 413
    frame #2: 0x00000001048fc6d7 servo`std::panicking::begin_panic::he426e15a3766089a + 103
    frame #3: 0x00000001048e4c29 servo`std::panicking::begin_panic_fmt::hdddb415186c241e7 + 169
    frame #4: 0x00000001048fc330 servo`rust_begin_unwind + 32
    frame #5: 0x00000001049231b1 servo`core::panicking::panic_fmt::hf4e16cb7f0d41a25 + 129
    frame #6: 0x0000000102c8f09d servo`core::result::unwrap_failed<(msg=&str at 0x00000001235f8980, error=<unavailable>)> + 285 at macros.rs:29
    frame #7: 0x0000000102f7f77a servo`core::result::{{impl}}::unwrap<style::values::computed::LengthOrPercentage,(self=Result<style::values::computed::LengthOrPercentage, ()> at 0x00000001235f89e8)> + 138 at result.rs:723
    frame #8: 0x0000000102f7f350 servo`style::properties::animated_properties::interpolate_transform_list(from_list=&[style::properties::longhands::transform::computed_value::ComputedOperation] at 0x00000001235f91c8, to_list=&[style::properties::longhands::transform::computed_value::ComputedOperation] at 0x00000001235f91b8, time=0.081665415153431994) + 3072 at properties.rs:26358
    frame #9: 0x000000010286bb11 servo`style::properties::animated_properties::{{impl}}::interpolate(self=0x00000001235fb710, other=0x00000001235fb728, time=0.081665415153431994) + 849 at properties.rs:26527
    frame #10: 0x000000010285460f servo`style::properties::animated_properties::{{impl}}::update<style::properties::ServoComputedValues>(self=0x00000001235fb708, style=0x00000001244a8e50, progress=0.081665415153431994) + 1295 at properties.rs:25460
    frame #11: 0x0000000102853905 servo`style::animation::{{impl}}::update<style::properties::ServoComputedValues>(self=0x00000001235fb708, style=0x00000001244a8e50, time=0.092031445994507521) + 549 at animation.rs:327
    frame #12: 0x0000000102852c58 servo`style::animation::update_style_for_animation<script_layout_interface::restyle_damage::RestyleDamage,style::selector_impl::ServoSelectorImpl>(context=0x00000001235fd208, animation=0x0000000124c6a300, style=0x0000000124f2f790, damage=Option<&mut script_layout_interface::restyle_damage::RestyleDamage> at 0x00000001235fc638) + 14024 at animation.rs:669
    frame #13: 0x000000010284aabf servo`layout::animation::recalc_style_for_animations::{{closure}}(fragment=0x0000000124f2f788) + 319 at animation.rs:133
    frame #14: 0x00000001028dd13d servo`layout::block::{{impl}}::mutate_fragments(self=0x0000000124f2f610, mutator=&mut FnMut<(&mut layout::fragment::Fragment)> at 0x00000001235fc858) + 45 at block.rs:2177
    frame #15: 0x000000010284a826 servo`layout::animation::recalc_style_for_animations(context=0x00000001235fd208, flow=&mut Flow at 0x00000001235fc970, animations=0x0000000123822298) + 102 at animation.rs:130
    frame #16: 0x000000010284a92e servo`layout::animation::recalc_style_for_animations(context=0x00000001235fd208, flow=&mut Flow at 0x00000001235fcaa0, animations=0x0000000123822298) + 366 at animation.rs:144
    frame #17: 0x000000010284a92e servo`layout::animation::recalc_style_for_animations(context=0x00000001235fd208, flow=&mut Flow at 0x00000001235fcbd0, animations=0x0000000123822298) + 366 at animation.rs:144
    frame #18: 0x000000010284a92e servo`layout::animation::recalc_style_for_animations(context=0x00000001235fd208, flow=&mut Flow at 0x00000001235fcd00, animations=0x0000000123822298) + 366 at animation.rs:144
    frame #19: 0x000000010284a92e servo`layout::animation::recalc_style_for_animations(context=0x00000001235fd208, flow=&mut Flow at 0x00000001235fce30, animations=0x0000000123822298) + 366 at animation.rs:144
    frame #20: 0x000000010284a92e servo`layout::animation::recalc_style_for_animations(context=0x00000001235fd208, flow=&mut Flow at 0x00000001235fcf60, animations=0x0000000123822298) + 366 at animation.rs:144
    frame #21: 0x0000000100c35987 servo`layout_thread::{{impl}}::tick_animations::{{closure}} + 135 at lib.rs:1302
    frame #22: 0x0000000100c35819 servo`profile_traits::time::profile<(category=LayoutStyleRecalc, meta=Option<profile_traits::time::TimerMetadata> at 0x00000001235fd0e8, profiler_chan=ProfilerChan at 0x00000001235fd0e0, callback=closure at 0x00000001235fd0c0),closure> + 217 at time.rs:108
    frame #23: 0x0000000100c356a8 servo`layout_thread::{{impl}}::tick_animations(self=0x00000001235fea68, rw_data=0x00000001239dc098) + 568 at lib.rs:1298
    frame #24: 0x0000000100a3ab87 servo`layout_thread::{{impl}}::tick_all_animations(self=0x00000001235fea68, possibly_locked_rw_data=0x00000001235fe9f8) + 103 at lib.rs:1282
    frame #25: 0x00000001009ea042 servo`layout_thread::{{impl}}::handle_request_helper(self=0x00000001235fea68, request=Msg at 0x00000001235fd8a0, possibly_locked_rw_data=0x00000001235fe9f8) + 370 at lib.rs:631
    frame #26: 0x00000001009bdb3b servo`layout_thread::{{impl}}::handle_request(self=0x00000001235fea68, possibly_locked_rw_data=0x00000001235fe9f8) + 2171 at lib.rs:554
    frame #27: 0x000000010096f9b2 servo`layout_thread::{{impl}}::start(self=LayoutThread at 0x00000001235fea68) + 370 at lib.rs:480
    frame #28: 0x000000010096f7e6 servo`layout_thread::{{impl}}::create::{{closure}}::{{closure}} + 118 at lib.rs:271
    frame #29: 0x0000000100965b80 servo`profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(self=0x00000001235ffdf0, f=closure at 0x00000001235ff2b8, reporter_name=String at 0x00000001235ff2a0, channel_for_reporter=Sender<script_layout_interface::message::Msg> at 0x00000001235ff288, msg=0x00000001235ff2c0) -> script_layout_interface::message::Msg,script_layout_interface::message::Msg,std::sync::mpsc::Sender<script_layout_interface::message::Msg>> + 912 at mem.rs:59
    frame #30: 0x000000010093a5a7 servo`layout_thread::{{impl}}::create::{{closure}} + 2071 at lib.rs:270
    frame #31: 0x0000000100931b0f servo`util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::hd0d21376fcf9c5eb + 495 at boxed.rs:234
    frame #32: 0x00000001009318c8 servo`std::panic::{{impl}}::call_once<(self=AssertUnwindSafe<closure> at 0x0000000123600008, _args=<unavailable>),closure> + 136 at panic.rs:251
    frame #33: 0x000000010093181c servo`std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h7eaf7bd445960064 + 92
    frame #34: 0x00000001009320c5 servo`std::panicking::try::call<closure>(f=0x0000000123600498) + 21 at panicking.rs:272
    frame #35: 0x00000001048ff3bc servo`__rust_try + 12
    frame #36: 0x00000001048ff356 servo`__rust_maybe_catch_panic + 38
    frame #37: 0x00000001009314ae servo`std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::h6fef2ed6ce63a17e + 158
    frame #38: 0x0000000100931390 servo`std::thread::local::{{impl}}::with<core::cell::Cell<usize>,closure,core::result::Result<(self=0x00000001060fa6a0, f=closure at 0x0000000123600538), Box<Any>>> + 208 at local.rs:211
    frame #39: 0x00000001009311c0 servo`std::panicking::try<(f=AssertUnwindSafe<closure> at 0x0000000123600718),std::panic::AssertUnwindSafe<closure>> + 192 at panicking.rs:235
    frame #40: 0x000000010093109f servo`std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,(f=AssertUnwindSafe<closure> at 0x00000001236009b8)> + 143 at panic.rs:307
    frame #41: 0x0000000100930efd servo`std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h69150e9b731fb117 + 349
    frame #42: 0x0000000100932328 servo`alloc::boxed::{{impl}}::call_box<(self=0x000000011ee51280, args=<unavailable>),closure> + 104 at boxed.rs:544
    frame #43: 0x00000001048fae39 servo`std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46 + 57
    frame #44: 0x00007fff8fd62899 libsystem_pthread.dylib`_pthread_body + 138
    frame #45: 0x00007fff8fd6272a libsystem_pthread.dylib`_pthread_start + 137
    frame #46: 0x00007fff8fd66fc9 libsystem_pthread.dylib`thread_start + 13
```

**Comment by jdm** [comment] 2016-07-02 02:49
```
frame #8: 0x0000000102f7f350 servo`style::properties::animated_properties::interpolate_transform_list(from_list=&[style::properties::longhands::transform::computed_value::ComputedOperation] at 0x00000001235f91c8, to_list=&[style::properties::longhands::transform::computed_value::ComputedOperation] at 0x00000001235f91b8, time=0.081665415153431994) + 3072 at properties.rs:26358
   26355	                (&TransformOperation::Translate(fx, fy, fz),
   26356	                 &TransformOperation::Translate(tx, ty, tz)) => {
   26357	                    let ix = fx.interpolate(&tx, time).unwrap();
-> 26358	                    let iy = fy.interpolate(&ty, time).unwrap();
   26359	                    let iz = fz.interpolate(&tz, time).unwrap();
   26360	                    result.push(TransformOperation::Translate(ix, iy, iz));
   26361	                }
```
cc @notriddle

**Closed** 2016-07-03 14:26 UTC
Labels: A-content/css, C-reproduced, I-panic
