### ISSUE TITLE
White space should be required on both sides of '+' and '-' in calc()

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15486] opened 2017-02-10 04:54 UTC
White space should be required on both sides of `+` and `-` inside `calc()` (while there is no such requirement for `*` and `/`). So declarations like `width: calc(2em+ 2px)` should be invalid.

Test code:
```html
<!DOCTYPE HTML>
<div style="width: calc(2em+ 2px)"></div>
<script>
alert(`${document.querySelector('div').style.width}`);
</script>
```

Spec: https://drafts.csswg.org/css-values-3/#calc-syntax

This can either be an issue in `impl CalcLengthOrPercentage` or an issue in servo/rust-cssparser.

@SimonSapin WDYT?

**Comment by upsuper** [comment] 2017-02-10 09:54
Then the relevant code should be https://github.com/servo/servo/blob/master/components/style/values/specified/length.rs#L555-L574

And it sounds like this should be an easy one?

**Comment by radhika2896** [comment] 2017-02-12 04:56
Hi, I would like to work on this.

**Comment by upsuper** [comment] 2017-02-12 07:18
Great! Feel free to ask questions here if anything is unclear to you.

**Comment by radhika2896** [comment] 2017-02-22 00:20
Is the fix to be done in the highlighted code?

**Comment by upsuper** [comment] 2017-02-22 00:23
Ah, there is no easy way to generate a permlink to a piece of code on GitHub :/

It should be https://github.com/servo/servo/blob/19978f2/components/style/values/specified/length.rs#L580-L592

**Comment by radhika2896** [comment] 2017-02-22 00:33
Hi just to clarify,
all these are possible errors right,

1) calc(2em- 2px)
2) calc(2em +2px)

**Comment by upsuper** [comment] 2017-02-22 00:37
Yes, both of the two you listed are invalid and should be rejected.

**Comment by radhika2896** [comment] 2017-02-22 00:41
Actually, this applies to '*' and '/', so there should be a change in the '*' and '/' methods too right?

**Comment by upsuper** [comment] 2017-02-22 00:42
No, it doesn't apply to `*` and `/`. These two can be used without whitespace around per spec.

**Comment by radhika2896** [comment] 2017-02-22 01:09
Should I be removing this requirement, such that there is no requirement for whitespace before and after of '+' and '-'?

**Comment by upsuper** [comment] 2017-02-22 01:12
No, you should add the enforcement of the requirement in Servo's parsing code. Servo currently incorrectly accepts that kind of invalid expressions as valid. That is what should be fixed in this issue.

**Comment by radhika2896** [comment] 2017-02-22 01:13
Ok thanks, for clarifying.

**Comment by radhika2896** [comment] 2017-03-05 17:15
How can I test, if my implementation for the fix works?

**Comment by upsuper** [comment] 2017-03-06 01:28
I think you can add a new unit test in servo/tests/unit/style/parsing/ (probably create a new file length.rs) and test things like `assert!(parse(Length::parse, "calc(1px+ 2px)").is_err());`.

**Comment by radhika2896** [comment] 2017-03-06 17:31
Hi i would like to clarify something, what does this mean? 
_ => return Err(())

**Comment by upsuper** [comment] 2017-03-06 23:43
It means in any case that doesn't match anything above it (`_` matches anything), return a value `Err(())`, which means an error happens during parsing.

**Comment by radhika2896** [comment] 2017-03-07 17:31
How do I run the test you have provided above?

**Comment by upsuper** [comment] 2017-03-07 22:04
You can run `./mach test-unit -p style` to test after you add the corresponding test.

**Comment by radhika2896** [comment] 2017-03-08 00:34
What would the necessary imports be for this particular test case? Because I added the file in the respective location, but when I run the tests, it doesn't appear.

**Comment by upsuper** [comment] 2017-03-08 00:45
If you are adding new file (as I suggested above), you would also need to add a new line in https://github.com/servo/servo/blob/master/tests/unit/style/parsing/mod.rs to allow compiler to find it.

**Comment by radhika2896** [comment] 2017-03-08 00:49
which library should I import for 'Length' to be recognized?

**Comment by upsuper** [comment] 2017-03-08 00:50
Probably `use style::values::specified::length::Length;` or just `use style::values::specified::length::*;` in your new file since it is testing that mod.

**Comment by radhika2896** [comment] 2017-03-08 00:54
rather than running all the tests in style, is it possible to just run the test file length.rs?

**Comment by upsuper** [comment] 2017-03-08 00:56
I guess not. But it doesn't seem to me running all tests in style takes too long.

**Comment by radhika2896** [comment] 2017-03-08 00:58
The problem is, each time I make a change to a file, I feel I need to build it again to save the new changes. So when i do ./mach build it takes 5-10 minutes

**Comment by upsuper** [comment] 2017-03-08 01:00
You can just run `./mach test-unit -p style` without `./mach build`. Unit tests build fewer crates than a normal build.

**Comment by upsuper** [comment] 2017-03-08 01:02
So from IRC:
> mach test-unit <test-name> works, too.
> It will run all tests that /contain/ that name

It might be what you want.

**Comment by radhika2896** [comment] 2017-03-08 01:04
Ok. So far I have the implementation for the fix working, because i tested it by making a wpt test, that uses the calc function. It works there, but now I have to write the above test case.

**Comment by radhika2896** [comment] 2017-03-08 01:10
For the above test case, I get the following error:
error[E0425]: cannot find function `parse` in this scope
assert!(parse(Length::parse, "calc(1px+ 2px)").is_err());
             ^^^^^ not found in this scope

**Comment by upsuper** [comment] 2017-03-08 01:11
Add `use parsing::parse;`...

**Comment by radhika2896** [comment] 2017-03-08 01:12
I tried that, but the error still persists. This time it tells me that there is no parse function that is associated with Length. 

error: no associated item named `parse` found for type `style::values::specified::Length` in the current scope

**Comment by upsuper** [comment] 2017-03-08 01:15
I think I said
```rust
use style::values::specified::length::Length;
```
not
```rust
use style::values::specified::Length;
```

**Comment by KiChjang** [comment] 2017-03-08 01:16
@radhika2896 Can you open a PR for your WIP code? It's fine if it's not finished, it's just much easier for us to tell you where the problem is if there is some code for us to see.

**Comment by radhika2896** [comment] 2017-03-08 01:38
I am not exactly sure how to create a PR at this point, because I have just forked this repo on my local machine.

**Comment by radhika2896** [comment] 2017-03-08 14:01
Is the problem fixed?

**Comment by nox** [comment] 2017-03-08 14:02
@radhika2896 Yes the PR is currently pending in queue.

**Comment by radhika2896** [comment] 2017-03-08 14:04
What was the problem with the test case?

**Comment by nox** [comment] 2017-03-08 14:05
Missing `parsing::parse` import, then I couldn't find `parse`, so I rewrote it without it. Then reviewing another PR I found `parsing::parse`, reused it in your test, but removed another import that was needed, thus failing to compile again. I'm bad. It's all fixed now.

**Comment by radhika2896** [comment] 2017-03-08 14:09
ok thanks! is my test case updated? like can i git pull?

**Closed** 2017-03-08 14:50 UTC
Labels: A-content/css, C-assigned
