### ISSUE TITLE
Build error on El Capitan

### ISSUE THREAD

**Issue by dongz9** [servo/servo#10201] opened 2016-03-26 03:50 UTC
Hi,

I met the following error message when building servo:

```
In file included from /usr/include/sys/types.h:121:
/usr/include/sys/_types/_pid_t.h:30:31: error: cannot combine with previous 'type-name' declaration specifier
typedef __darwin_pid_t        pid_t;
                              ^
./confdefs.h:16:15: note: expanded from macro 'pid_t'
#define pid_t int
              ^
4 errors generated.
configure: failed program was:
#line 12469 "configure"
#include "confdefs.h"
 #include <stdio.h>
                             #include <string.h>
                             #include <zlib.h>
int main() {
 #if ZLIB_VERNUM < 0x1230
                             #error "Insufficient zlib version (0x1230 required)."
                             #endif
; return 0; }
configure: error: Insufficient zlib version for --with-system-zlib (1.2.3 required)
```

Any idea how to fix it?

**Comment by KiChjang** [comment] 2016-03-26 04:41
It looks like your version of zlib is outdated. Have you tried updating it?

**Comment by dongz9** [comment] 2016-03-26 04:59
I've installed homebrew/dupes/zlib, which is 1.2.8. I guess the build system didn't find it? Is there anyway to configure which zlib to use?

**Comment by dongz9** [comment] 2016-03-26 05:37
Umm, I checked OSX's default zlib version, which is 1.2.5.

```
#define ZLIB_VERSION "1.2.5"
#define ZLIB_VERNUM 0x1250
#define ZLIB_VER_MAJOR 1
#define ZLIB_VER_MINOR 2
#define ZLIB_VER_REVISION 5
#define ZLIB_VER_SUBREVISION 0
```

This makes me really confusing now...

**Comment by dongz9** [comment] 2016-03-26 15:45
I just took a closer look, the solution turns out to set CPP=clang -E (the default value is gcc -E). Anyway, the original error message was really confusing...

**Comment by perlun** [comment] 2016-03-26 16:58
Hmm, that's weird; I built Servo on El Capitan just a few days ago. Got a build error first (but a different one than this :smile:) but after resolving that, it worked fine. I guess I could try rebuilding from latest `master` but it'll take some time.

**Comment by perlun** [comment] 2016-03-26 18:37
Rebuilt here - worked fine, the resulting binary seems to work also.

dongz9 - could you include some more details from the build error? From what I can tell in the posted log, the error you're seeing is from some `autoconf`/`configure` script, likely a dependency coming from some create (I am yet too unfamiliar with the `servo` code base to be able to give more details than that...).

**Comment by andrewdavidmackenzie** [comment] 2016-07-12 22:46
Just did the debug build (first attempt ever) and it all built fine with no errors and runs fine also.

**Comment by nox** [comment] 2017-10-01 10:41
I cannot reproduce this.

**Closed by nox** 2017-10-01 10:41 UTC
Labels: A-build, P-mac
