### ISSUE TITLE
Servo Tech Demo closes as soon as I open it (Windows 10 64 bit)

### ISSUE THREAD

**Issue by RonTilby** [servo/servo#16546] opened 2017-04-20 18:16 UTC
The Servo Tech Demo closes itself after flashing a window.
My system info:
Windows 10 64-bit, Intel Core i5-4460 CPU, 8.0GB RAM
Intel HD Graphics 4600
Graphics Driver Provider: Intel Corporation
Driver Date: 3/8/2017
Driver Version: 20.19.15.4624

What additional information would be useful?

**Comment by atouchet** [comment] 2017-04-20 21:33
This might be a duplicate of #16393.

**Comment by jdm** [comment] 2017-04-20 22:40
Yeah, let's track this there.

**Closed by jdm** 2017-04-20 22:40 UTC
