### ISSUE TITLE
Can't scroll overflow:scroll elements

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#10434] opened 2016-04-06 12:48 UTC
Here is a test case:

```html
<style>

  main {
    height: 300px;
    width: 250px;
    background-image: linear-gradient(to bottom, red, blue);
    overflow: scroll;
  }

  div {
    margin-top: 200px;
    height: 200px;
    width: 200px;
    overflow: scroll;
  }

  p {
    height: 250px;
    background-image: linear-gradient(to bottom, white, black);
    margin: 0;
  }

</style>
<main>
  <div>
    <p></p>
  </div>
</main>
```

**Comment by pcwalton** [comment] 2016-04-07 00:19
Duplicate of #2742.

This will likely require a lot of work.

**Comment by paulrouget** [comment] 2016-04-07 04:29
@pcwalton: if it's not something we can realistically fix by June, please let me know, we can probably work around that.

**Comment by paulrouget** [comment] 2016-04-13 09:17
Re-opening. I don't think this is fixed.

**Comment by pcwalton** [comment] 2016-04-13 17:43
Yeah, WR doesn't support overflow:scroll scrolling yet.

**Comment by paulrouget** [comment] 2016-04-14 02:58
> Yeah, WR doesn't support overflow:scroll scrolling yet.

Ok. So I will work around that.

P1 -> P3.

**Comment by pcwalton** [comment] 2016-05-03 16:34
Fixed by #10717

**Closed** 2016-05-03 16:34 UTC
Labels: A-browserhtml/P3
