### ISSUE TITLE
intermittent crash ("Connection reset by peer" from create_api) in /html/semantics/embedded-content/the-canvas-element/2d.getcontext.shared.html, /html/semantics/scripting-1/the-template-element/template-element/node-document-changes.html, /dom/traversal/TreeWalker-walking-outside-a-tree.html, /XMLHttpRequest/responseText-status.html, /_mozilla/css/line_break_nowrap.html

### ISSUE THREAD

**Issue by metajack** [servo/servo#13480] opened 2016-09-28 12:42 UTC
```
 ▶ CRASH [expected FAIL] /css21_dev/html4/vertical-align-007.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at ../src/libcore/result.rs:799)
  │ stack backtrace:
  │    0:     0x7fa759924c8d - backtrace::backtrace::trace::h0e60ef08c7c34e9f
  │    1:     0x7fa759925312 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
  │    2:     0x7fa75846e9cd - servo::main::_{{closure}}::h911afab4cc009f33
  │    3:     0x7fa759f03745 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
  │    4:     0x7fa759f03612 - std::panicking::begin_panic::hfbeda5aad583dc32
  │    5:     0x7fa759f03550 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
  │    6:     0x7fa759f034d1 - rust_begin_unwind
  │    7:     0x7fa759f3ff5c - core::panicking::panic_fmt::h4395919ece15c671
  │    8:     0x7fa759a8964f - core::result::unwrap_failed::h3191a47cbfbe2a26
  │    9:     0x7fa759a8ad20 - webrender_traits::api::_<impl webrender_traits..RenderApiSender>::create_api::h74e2147a94b73b3e
  │   10:     0x7fa7587e10f7 - _<layout_thread..LayoutThread as layout_traits..LayoutThreadFactory>::create::_{{closure}}::hcbdf224d94fa1d3a
  │   11:     0x7fa75875c796 - std::panicking::try::do_call::h032f92c4e6f5b87e
  │   12:     0x7fa759f0c0c6 - __rust_maybe_catch_panic
  │   13:     0x7fa758783e44 - _<F as alloc..boxed..FnBox<A>>::call_box::h018a2ddf52f3d72e
  │   14:     0x7fa759f01d80 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  │   15:     0x7fa756378183 - start_thread
  │   16:     0x7fa755e8f37c - clone
  │   17:                0x0 - <unknown>
  │ ERROR:servo: called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
  └ Pipeline failed in hard-fail mode.  Crashing!
```

**Comment by metajack** [comment] 2016-09-28 12:46
This may be related to the WR switch in automation done in #13382

**Comment by Wafflespeanut** [comment] 2016-09-30 02:15
Similar to #13479

**Comment by Manishearth** [comment] 2016-10-09 08:59
Same crash happened with another test too http://build.servo.org/builders/linux-rel-css/builds/102/steps/test/logs/stdio

**Comment by Manishearth** [comment] 2016-10-09 09:00
Looks like this is another webrender crash @glennw

**Comment by jdm** [comment] 2017-10-20 18:00
Given:
```
  │ called `Option::unwrap()` on a `None` value (thread RenderBackend, at /checkout/src/libcore/option.rs:335)
  │ stack backtrace:
  │    0:     0x7f31135c01dc - backtrace::backtrace::trace::h3049d3b23f5565ad
  │    1:     0x7f31135c0212 - backtrace::capture::Backtrace::new::h48230b597774155d
  │    2:     0x7f3112403f55 - servo::main::{{closure}}::hb00f84d652c2eb89
  │    3:     0x7f3114775bb6 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7f3114775a44 - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7f3114775949 - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7f31147758da - std::panicking::rust_begin_panic
  │                         at /checkout/src/libstd/panicking.rs:498
  │    7:     0x7f31147851d0 - core::panicking::panic_fmt
  │                         at /checkout/src/libcore/panicking.rs:71
  │    8:     0x7f3114785106 - core::panicking::panic
  │                         at /checkout/src/libcore/panicking.rs:51
  │    9:     0x7f311371711b - webrender::render_backend::RenderBackend::run::h7c321a1c4e8899f0
  │   10:     0x7f311369ccc3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8c39dc6dc355b660
  │   11:     0x7f311369da35 - std::panicking::try::do_call::h114f30809a75c08a
  │   12:     0x7f311477ccfc - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:99
  │   13:     0x7f31136b97b2 - <F as alloc::boxed::FnBox<A>>::call_box::heb4069ec3f4fc2fb
  │   14:     0x7f31147748cb - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /checkout/src/liballoc/boxed.rs:772
  │                          - std::sys_common::thread::start_thread
  │                         at /checkout/src/libstd/sys_common/thread.rs:24
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   15:     0x7f31104cd183 - start_thread
  │   16:     0x7f310fbd7ffc - clone
  │   17:                0x0 - <unknown>
```
I suspect:
* https://github.com/servo/webrender/blob/56a452d64e759977619b37c9e971f944114948d2/webrender/src/render_backend.rs#L448
* https://github.com/servo/webrender/blob/56a452d64e759977619b37c9e971f944114948d2/webrender/src/render_backend.rs#L515
* https://github.com/servo/webrender/blob/56a452d64e759977619b37c9e971f944114948d2/webrender/src/render_backend.rs#L544
* https://github.com/servo/webrender/blob/56a452d64e759977619b37c9e971f944114948d2/webrender/src/render_backend.rs#L561
* https://github.com/servo/webrender/blob/56a452d64e759977619b37c9e971f944114948d2/webrender/src/render_backend.rs#L565

**Comment by jdm** [comment] 2017-11-10 19:51
Shoot, I didn't mean to close this in #18986. No wonder more of these failures have been preventing builds from merging.

**Comment by jdm** [comment] 2017-11-10 20:30
I wonder if this is caused by https://github.com/servo/ipc-channel/issues/29 (based on my reading of https://blog.netherlabs.nl/articles/2009/01/18/the-ultimate-so_linger-page-or-why-is-my-tcp-not-reliable).

**Comment by emilio** [comment] 2017-11-11 02:31
https://github.com/servo/ipc-channel/pull/179 has a repro for this

**Comment by jdm** [comment] 2018-02-26 21:48
Finally got some more useful debug output:
```
  ▶ CRASH [expected OK] /custom-elements/htmlconstructor/newtarget.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ CloneApi message response was dropped while Webrender was still alive: io error: Connection reset by peer (os error 104) (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(NonZero(NonZero(4))) }, at /home/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/681e181/webrender_api/src/api.rs:725)
  │ stack backtrace:
  │    0:     0x7ffbb146b02c - backtrace::backtrace::trace::hb73e73c3fa21d7b2
  │    1:     0x7ffbb146a1d2 - backtrace::capture::Backtrace::new::h8a585c120187c23d
  │    2:     0x7ffbaebba61b - servo::main::{{closure}}::h6e00f8e2e4856eb6
  │    3:     0x7ffbb1478b65 - std::panicking::rust_panic_with_hook::haa00f5a9417cd684
  │                         at libstd/panicking.rs:577
  │    4:     0x7ffbb14789ee - std::panicking::begin_panic::ha956683198499384
  │                         at libstd/panicking.rs:537
  │    5:     0x7ffbb14788ea - std::panicking::begin_panic_fmt::h587e116719f14631
  │                         at libstd/panicking.rs:521
  │    6:     0x7ffbb0c197d5 - webrender_api::api::RenderApiSender::create_api::hbf8b5e1d4e21a22c
  │    7:     0x7ffbaee06ec9 - layout_thread::LayoutThread::new::h763ce17e6e8edb15
  │    8:     0x7ffbaee556a8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h099360ab24870f60
  │    9:     0x7ffbaef14dc7 - _ZN3std9panicking3try7do_call17hcf064867f61355aaE.llvm.4521503C
  │   10:     0x7ffbb14a18ae - __rust_maybe_catch_panic
  │                         at libpanic_unwind/lib.rs:102
  │   11:     0x7ffbaee6059a - <F as alloc::boxed::FnBox<A>>::call_box::h7670dfa4723d8bf5
  │   12:     0x7ffbb148c5fb - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h13f1b0bf377a9f5b
  │                         at /checkout/src/liballoc/boxed.rs:798
  │                          - std::sys_common::thread::start_thread::hb5b6e0447b9691dc
  │                         at libstd/sys_common/thread.rs:24
  │                          - std::sys::unix::thread::Thread::new::thread_start::hcaff0bef1a01c624
  │                         at libstd/sys/unix/thread.rs:90
  │   13:     0x7ffbada9d183 - start_thread
  │   14:     0x7ffbac364ffc - clone
  │   15:                0x0 - <unknown>
  │ ERROR:servo: CloneApi message response was dropped while Webrender was still alive: io error: Connection reset by peer (os error 104)
  │ Pipeline failed in hard-fail mode.  Crashing!
  └ thread panicked while processing panic. aborting.
```
So this definitely looks like a bug in ipc-channel, since the target of the WR API message is still alive, and there should be no way for the sender that was provided for the sync response to be dropped before sending the reply message.

**Comment by emilio** [comment] 2018-02-26 22:20
I think we should just probably use `mpsc` in Servo too. We have too many random intermittents related to ipc-channel, and I don't think Servo's multiprocess mode scales / is tested very well right now, unfortunately.

**Closed** 2019-11-28 03:03 UTC
Labels: I-intermittent
