### ISSUE TITLE
Typing quickly results in garbage input

### ISSUE THREAD

**Issue by whitequark** [servo/servo#12039] opened 2016-07-01 11:40 UTC
I was running the Transparent Rectangles demo fullscreen, which caused it to run at ~27FPS (as reported on stdout). During that, I started typing "github" in the URL bar. I type pretty quickly, evidently too quickly for Servo because that's what this resulted in:
![2362](https://cloud.githubusercontent.com/assets/54771/16520593/9a25a020-3f80-11e6-8336-55f68a04e2ec.png)

**Comment by ConnorGBrewster** [comment] 2016-07-02 03:53
After doing a bit of research into this issue, I believe the issue is on the browser.html end with `setSelectionRange`

**Comment by paulrouget** [comment] 2016-07-18 11:30
I hit this bug pretty often. bhtml race maybe. bhtml issue: https://github.com/browserhtml/browserhtml/issues/1189

**Comment by ConnorGBrewster** [comment] 2016-07-18 13:31
I believed this is fixed https://github.com/browserhtml/browserhtml/pull/1166

**Comment by jdm** [comment] 2016-07-18 13:33
Closing, in that case.

**Closed by jdm** 2016-07-18 13:33 UTC
Labels: A-browserhtml, A-input, I-race
