### ISSUE TITLE
assertion failed: count_cell.get() > 0

### ISSUE THREAD

**Issue by szagi3891** [servo/servo#12170] opened 2016-07-02 12:08 UTC
assertion failed: count_cell.get() > 0 ### URL: http://wiadomosci.onet.pl/ ### Backtrace: ``` frame #0 - 0x00007fb333387d8d - backtrace::backtrace::trace::hccde8df28b4db2a2 frame #1 - 0x00007fb333387d15 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8 frame #2 - 0x00007fb332555359 - _<F as alloc..boxed..FnBox<A>>::call_box::hc555946005547ceb frame #3 - 0x00007fb33337eb98 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01 frame #4 - 0x00007fb33348614c - std::panicking::rust_panic_with_hook::h983af77c1a2e581b frame #5 - 0x00007fb331d97edf - std::panicking::begin_panic::h0bf39f6d43ab9349 frame #6 - 0x00007fb33240a490 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h71d7672a3472afa1 frame #7 - 0x00007fb332407f9b - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h724ec798d0dfe84e frame #8 - 0x00007fb3325602a4 - script::script_thread::ScriptThread::handle_msg_from_script::hfac8a5d67415fa31 frame #9 - 0x00007fb3325b18ef - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hcc3e5fcf08d42e0c frame #10 - 0x00007fb332598ad7 - script::script_thread::ScriptThread::handle_msgs::hf9fbf9949e23273b frame #11 - 0x00007fb332553a47 - std::panicking::try::call::h99112171a9854ab3 frame #12 - 0x00007fb3334aa95b - __rust_try frame #13 - 0x00007fb3334aa8fe - __rust_maybe_catch_panic frame #14 - 0x00007fb332554cbd - _<F as alloc..boxed..FnBox<A>>::call_box::h4410a344b31b72da frame #15 - 0x00007fb33349e924 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46 frame #16 - 0x00007fb32f09c183 - start_thread frame #17 - 0x00007fb32ebb337c - clone frame #18 - 0x0000000000000000 - <unknown> ```

```
ERROR:constellation::constellation: Panic: assertion failed: count_cell.get() > 0
ERROR:constellation::constellation: Backtrace:
frame #0  - 0x00007fb333387d8d - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x00007fb333387d15 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x00007fb332555359 - _<F as alloc..boxed..FnBox<A>>::call_box::hc555946005547ceb
frame #3  - 0x00007fb33337eb98 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
frame #4  - 0x00007fb33348614c - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x00007fb331d97edf - std::panicking::begin_panic::h0bf39f6d43ab9349
frame #6  - 0x00007fb33240a490 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h71d7672a3472afa1
frame #7  - 0x00007fb332407f9b - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h724ec798d0dfe84e
frame #8  - 0x00007fb3325602a4 - script::script_thread::ScriptThread::handle_msg_from_script::hfac8a5d67415fa31
frame #9  - 0x00007fb3325b18ef - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hcc3e5fcf08d42e0c
frame #10 - 0x00007fb332598ad7 - script::script_thread::ScriptThread::handle_msgs::hf9fbf9949e23273b
frame #11 - 0x00007fb332553a47 - std::panicking::try::call::h99112171a9854ab3
frame #12 - 0x00007fb3334aa95b - __rust_try
frame #13 - 0x00007fb3334aa8fe - __rust_maybe_catch_panic
frame #14 - 0x00007fb332554cbd - _<F as alloc..boxed..FnBox<A>>::call_box::h4410a344b31b72da
frame #15 - 0x00007fb33349e924 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #16 - 0x00007fb32f09c183 - start_thread
frame #17 - 0x00007fb32ebb337c - clone
frame #18 - 0x0000000000000000 - <unknown>

ERROR:constellation::constellation: Panic: called `Result::unwrap()` on an `Err` value: RecvError
ERROR:constellation::constellation: Backtrace skipped (run with -Z full-backtraces to see every backtrace).
```

There is also the problem with this method of reporting errors.
I add a screenshot.
https://postimg.org/image/lm5lgq44h/

**Comment by nox** [comment] 2016-07-02 12:13
Thanks for the report! Closing as a duplicate of #12047.

**Closed by nox** 2016-07-02 12:13 UTC
