### ISSUE TITLE
pre-built nightly Servo snapshot couldn't run on Fedora 24

### ISSUE THREAD

**Issue by NTMan** [servo/servo#12090] opened 2016-07-01 17:00 UTC
$ ./runservo.sh 
./servo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by friesoft** [comment] 2016-07-01 17:03
```
[friedreb@thor servo]$ uname -a
Linux thor 4.5.7-300.fc24.x86_64 #1 SMP Wed Jun 8 18:12:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
[friedreb@thor servo]$ ldd servo | grep "not found"
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
```

```
[friedreb@thor servo]$ ls -la /usr/lib64/libssl.so*
lrwxrwxrwx. 1 root root     16  3. Mai 18:32 /usr/lib64/libssl.so.10 -> libssl.so.1.0.2h
-rwxr-xr-x. 1 root root 467680  3. Mai 18:32 /usr/lib64/libssl.so.1.0.2h
[friedreb@thor servo]$ ls -la /usr/lib64/libcrypto.so.*
lrwxrwxrwx. 1 root root      19  3. Mai 18:32 /usr/lib64/libcrypto.so.10 -> libcrypto.so.1.0.2h
-rwxr-xr-x. 1 root root 2485120  3. Mai 18:32 /usr/lib64/libcrypto.so.1.0.2h
```

**Comment by jbriggs-zvelo** [comment] 2016-07-01 17:15
And when I tried to make it use Fedora's newer version it failed with:

> ./servo: /usr/local/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)
> ./servo: /usr/local/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.1d' not found (required by ./servo)
> ./servo: /usr/local/lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./servo)

**Comment by moosingin3space** [comment] 2016-07-01 17:27
I am planning on contributing a flatpak builder for Servo sometime this weekend, which should resolve this for Fedora >= 23.

**Comment by jdm** [comment] 2016-07-02 14:59
Duplicate of #12015. Thanks for reporting it!

**Closed by jdm** 2016-07-02 14:59 UTC
