### ISSUE TITLE
assertion failed: !self.Document().needs_reflow() ||    (!for_display && self.Document().needs_paint()) ||    self.window_size.get().is_none() || self.suppress_reflow.get()

### ISSUE THREAD

**Issue by esiqveland** [servo/servo#19189] opened 2017-11-12 12:25 UTC
Panic:
```
assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()
```
OS is windows 10.
### URL:
https://www.nrk.no/norge/risikerer-livet-ved-a-krysse-t-baneskinner-1.13774301

### Servo Version:
Servo 0.0.1-9d05552

This might be same as #18970 but I have a URL to provide.
### Backtrace:
```

WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×16 at (783,3578.0166))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(16×0 at (783,3578.0166))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×16 at (783,3562.0166))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×0 at (707.9167,3722.15))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(25×0 at (682.9167,3722.15))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×25 at (707.9167,3722.15))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(25×0 at (707.9167,3722.15))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×25 at (707.9167,3697.15))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(181×0 at (73.566666,4938.3335))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(22×0 at (51.566666,4938.3335))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(22.066666×0 at (254.56667,4938.3335))
WARNING: <Constellation>: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(NonZero(NonZero(9))) } got layout tick after closure.
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×0 at (0,1))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×0 at (0,1))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×0 at (0,1))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×0 at (783,3578.0166))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(16×0 at (767,3578.0166))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×16 at (783,3578.0166))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(16×0 at (783,3578.0166))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×16 at (783,3562.0166))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×0 at (707.9167,3722.15))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(25×0 at (682.9167,3722.15))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×25 at (707.9167,3722.15))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(25×0 at (707.9167,3722.15))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×25 at (707.9167,3697.15))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(181×0 at (73.566666,4938.3335))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(22×0 at (51.566666,4938.3335))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(22.066666×0 at (254.56667,4938.3335))
WARNING: <Constellation>: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(NonZero(NonZero(9))) } got layout tick after closure.
WARNING: Panic hook called.
WARNING: already borrowed: BorrowMutError
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(NonZero(NonZero(7))) }>: Panic hook called.
ERROR: assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()

stack backtrace:
   0:     0x7ff7a92681c6 - <no info>
   1:     0x7ff7a926880e - <no info>
   2:     0x7ff7a8fa590b - <no info>
   3:     0x7ff7a8fa3892 - <no info>
   4:     0x7ff7a98f02f9 - <no info>
   5:     0x7ff7a802f22a - <no info>
   6:     0x7ff7a9928654 - <no info>
   7:     0x7ff7a8370762 - <no info>
   8:     0x7ff7a8aa554f - <no info>
   9:     0x7ff7a8b0255e - <no info>
  10:     0x7ff7a8af7dcc - <no info>
  11:     0x7ff7a83682f8 - <no info>
  12:     0x7ff7a84c7fd9 - <no info>
  13:     0x7ff7a9929842 - <no info>
  14:     0x7ff7a862fd6b - <no info>
  15:     0x7ff7a9926d1c - <no info>
  16:     0x7ffd347e1fe4 - BaseThreadInitThunk
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2017-11-12 13:51
I have not been able to reproduce this on macOS yet. I've tried loading that page directly in the Servo nightly downlod and scrolling vertically up and down the page, but no panic occurs.

**Comment by esiqveland** [comment] 2017-11-14 12:24
Works for me on macOS as well.
I'll check again on windows 10 later today.

**Comment by nox** [comment] 2019-03-23 13:25
Duplicate of #14239.

**Closed by nox** 2019-03-23 13:25 UTC
Labels: I-panic
