### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "SendError(..)"

### ISSUE THREAD

**Issue by jeffparsons** [servo/servo#18082] opened 2017-08-15 05:31 UTC
called `Result::unwrap()` on an `Err` value: "SendError(..)"
### URL:
https://stileeducation.com/
### Servo Version:
Servo 0.0.1-b50cf33
### Backtrace:
```

WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
ERROR: called `Result::unwrap()` on an `Err` value: "SendError(..)"

stack backtrace:
   0:        0x107deac5e - backtrace::backtrace::trace::h15d769766aa71ae0
   1:        0x107deadec - backtrace::capture::Backtrace::new::hde1afc496271e12d
   2:        0x106270c19 - constellation::constellation::log_entry::hc60ffaf2b8a0de43
   3:        0x10626fc32 - _$LT$constellation..constellation..FromCompositorLogger$u20$as$u20$log..Log$GT$::log::hb085a8ba70ec667a
   4:        0x107fdd25e - log::__log::h9babd36d99ae110e
   5:        0x106155a60 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h2d732856f9776e1f
   6:        0x1080000e6 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
   7:        0x107ffff44 - std::panicking::begin_panic::h69fe06a9d67b6165
   8:        0x107fffeb2 - std::panicking::begin_panic_fmt::haf8695bfb6c52436
   9:        0x107fffe17 - rust_begin_unwind
  10:        0x10802b7a0 - core::panicking::panic_fmt::hfedd6515bcee8bb1
  11:        0x1068a8340 - core::result::unwrap_failed::he02056d3c716db25
  12:        0x106b77f91 - script::dom::window::Window::force_reflow::ha42a612958881cbb
  13:        0x106b7a57d - script::dom::window::Window::reflow::h34bf9b0c5a6ba7cb
  14:        0x1069d1025 - script::dom::cssstyledeclaration::CSSStyleDeclaration::get_property_value::h7c5ab31320cf0290
  15:        0x106bd2230 - script::script_thread::ScriptThread::handle_msg_from_constellation::he8f5318321a0e090
  16:        0x106bcef2c - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hdeb532fbaf883e62
  17:        0x106bcb1db - script::script_thread::ScriptThread::handle_msgs::had90faa4ac3794d3
  18:        0x1066603a7 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbc61873337296b9e
  19:        0x106682efd - std::panicking::try::do_call::h1340531f44a9a1be
  20:        0x10800126a - __rust_maybe_catch_panic
  21:        0x1068aa036 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::he16a1d9998534c85
  22:        0x107ffd295 - std::sys::imp::thread::Thread::new::thread_start::h993b7e5cb7871f66
  23:     0x7fffdf2da93a - _pthread_body
  24:     0x7fffdf2da886 - _pthread_start
```
This report was generated by the browser.html issue reporter.

**Comment by DominoTree** [comment] 2017-08-26 19:07
Seems to load without issue on 0.0.1-1e0ebf1c1a under OSX

**Comment by sviter** [comment] 2017-08-27 17:26
Got on the same site with latest nightly servo for wondows build

assertion failed: !self.Document().needs_reflow() ||
    (!for_display && self.Document().needs_paint()) ||
    self.window_size.get().is_none() || self.suppress_reflow.get()
### URL:

### Servo Version:
Servo 0.0.1-08b9588
### Backtrace:
```

WARNING: <Constellation>: BrowsingContext BrowsingContextId { namespace_id: PipelineNamespaceId(0), index: BrowsingContextIndex(1) } iterated after closure.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }>: Resuming an already resumed timer.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }>: Resuming an already resumed timer.
WARNING: <Constellation>: BrowsingContext BrowsingContextId { namespace_id: PipelineNamespaceId(1), index: BrowsingContextIndex(0) } iterated after closure.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: Pipeline

**Comment by nox** [comment] 2017-10-07 09:32
@sviter That's an unrelated issue, see #14239.

**Comment by nox** [comment] 2017-10-07 10:07
Closing as duplicate of #17064.

**Comment by nox** [comment] 2017-10-07 10:07
Closing as duplicate of #17064.

**Closed by nox** 2017-10-07 10:07 UTC
Labels: I-panic
