### ISSUE TITLE
Keyboard events & input elements ignore OS keyboard layout 

### ISSUE THREAD

**Issue by Gozala** [servo/servo#8767] opened 2015-12-01 21:14 UTC
I use Dvorak keyboard layout on OSX 10.11.2 and typing into input element seems to type as if I was typing in QUERTY. Also all keyboard events seem to ignore keyboard layout.

**Comment by metajack** [comment] 2015-12-01 21:15
That's odd. You'd think the OS would translate the events before sending them. Maybe this is a bug in Glutin?

**Comment by jdm** [comment] 2015-12-01 21:22
Duplicate of #4144.

**Closed by jdm** 2015-12-01 21:22 UTC
