### ISSUE TITLE
Facebook blinks and is unusable

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#11903] opened 2016-06-28 19:49 UTC
In the last week or so, I noticed a regression where Facebook started to blink on the main page.  Each time it blinked, it took away your ability to input your login, rendering the page unusable (or practically unusable)

I have a video of this if anyone is interested. 

I'm on OS X 10.11.5.

**Comment by pcwalton** [comment] 2016-06-29 00:06
This is because Servo is spawning 2,000+ threads when opening that site

**Comment by pcwalton** [comment] 2016-06-29 00:28
Facebook is opening an infinite loop of iframes to https://www.facebook.com/intern/common/referer_frame.php. This is causing Servo to exhaust resources.

**Comment by jdm** [comment] 2016-06-29 01:15
That would be fixed by https://github.com/servo/servo/pull/11321.

**Comment by ConnorGBrewster** [comment] 2016-07-02 00:13
This is still not fixed by #11321/#11934

**Comment by nox** [comment] 2017-10-02 07:47
Is this still true?

**Comment by jonathandturner** [comment] 2017-10-02 15:02
@nox - hard to tell, Facebook doesn't seem to be working anymore in the latest nightly.

**Comment by atouchet** [comment] 2018-03-06 23:58
I am not able to reproduce this issue.

**Comment by dralley** [comment] 2020-03-24 19:41
Seems like it can be closed?

**Closed** 2020-03-24 20:39 UTC
Labels: C-is-this-done, I-perf-bloat, I-perf-slow
