### ISSUE TITLE
Use RangeError for TextEncoder/TextDecoder

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#5620] opened 2015-04-09 17:09 UTC
Blocks #5601.

* Spec: <https://encoding.spec.whatwg.org/#dom-textdecoder>, <https://encoding.spec.whatwg.org/#dom-textencoder>.
* Code: `components/script/dom/textdecoder.rs`, `components/script/dom/textencoder.rs`, `components/script/dom/bindings/error.rs`.
* Test: possibly `/encoding/api-replacement-encodings.html`, `/encoding/textencoder-constructor-non-utf.html`.

To fix this bug, you'll first need to implement `RangeError` exceptions. This should be analogous to the `TypeError` implementation that already exists in `components/script/dom/bindings/error.rs`. I'd extend `get_error_message` to accept one error number for `TypeError` and one for `RangeError`, and create a second static like `ERROR_FORMAT_STRING` that uses `JSEXN_RANGEERR`.

Then you'll need to return `Err(Error::Range)` in the places that currently have TODO/FIXME comments mentioning "RangeError".

Bonus point for writing additional tests for the case where the encoding argument is not an encoding at all.

**Comment by aneeshusa** [comment] 2015-04-09 22:29
I'd like to give this a try.

**Comment by jdm** [comment] 2015-04-09 23:44
Go for it!

**Comment by aneeshusa** [comment] 2015-04-10 10:09
A few questions about the tests.
- Test naming: I had to change some of the test description strings in order to get the tests to pass. The test logic itself in the functions passed to test() is fine, but for some reason the test name is affecting the test results.
    - Is changing the test names the correct way to fix this, or is there a better way to do it? The test logic looks fine as is, and changing the name is not intuitive at all and took me a long time to guess. The function passed to test() should encode all of the necessary information, so I don't see why the test name should be a factor.
    - Out of curiousity, why/how does this work?  I think that having a 'not' present in the name is setting whether or not the test is expected to PASS or FAIL, but I'm not sure - I couldn't find the name field being accessed in any meaningful way in the test runner.
- GBK Encoding: This is a special case, and it's the only test that doesn't work after twiddling test names.
    - [The spec](https://encoding.spec.whatwg.org/#gbk) says that the gbk decoder is the gb18030 decoder.
    - [The encoding crate we use](https://github.com/lifthrasiir/rust-encoding/blob/9223065eca184caa5d8f40efaae7bbde10e0f897/src/label.rs#L217-L227) lumps them together and says that the gbk labels map to gb18030, which I think is reasonable.
    - Our tests say that [each encoding should map to itself](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/encoding/textencoder-constructor-non-utf.html#L19), which is also reasonable. This implies gbk should map to the gbk decoder, which happens to be the gbk18030 decoder under the hood.
    - Firefox reports a gbk decoder for gbk, as does Chromium.
    - Should I change the test case or should we consider this an upstream bug?

I'll look into writing the not-even-an-encoding test cases once I get the current set to pass.

**Comment by jdm** [comment] 2015-04-10 12:47
@aneeshusa: Expected test result come from the ini files under tests/wpt/meta, like http://mxr.mozilla.org/servo/source/tests/wpt/metadata/encoding/api-replacement-encodings.html.ini . If you're seeing output like "PASS expected FAIL", that means that your changes are causing the checks to succeed, but the ini files currently record an expected failure instead. Does that clear it up?

**Comment by aneeshusa** [comment] 2015-04-10 19:12
OK, thanks, that's a much better explanation than name-changing voodoo. I've gotten the rest of the tests to pass, what should I do about the gbk test (see my previous comment)?

**Comment by aneeshusa** [comment] 2015-04-10 19:13
Also, is there an official way to only run certain wpt tests? I've been using a hacky solution, but if there's a better way that would be much appreciated.

**Comment by Ms2ger** [comment] 2015-04-10 19:37
`./mach test-wpt --include ...`; I'll need to investigate what's up with gbk

**Comment by jdm** [comment] 2015-04-10 19:51
You can also just run `./mach test tests/wpt/web-platform-tests/subdir` or even `./mach test tests/wpt/web-platform-tests/path/to/file.html`.

**Comment by aneeshusa** [comment] 2015-04-10 19:53
Also, as far as I can tell the rust-encoding crate is [wrong](https://github.com/lifthrasiir/rust-encoding/blob/master/src/codec/utf_16.rs#L34) about [the whatwg name for utf-16le and utf-16](https://encoding.spec.whatwg.org/#names-and-labels), so I'll put in a PR upstream.

**Comment by aneeshusa** [comment] 2015-04-10 19:55
Perfect, the --include option is what I was looking for. Thanks!

**Comment by aneeshusa** [comment] 2015-04-10 19:57
Btw, my thoughts on gbk are that gbk should map to gbk instead of gbk18030, as per the spec.

**Comment by Ms2ger** [comment] 2015-04-12 08:17
Gbk looks like it needs an upstream fix, yeah.

**Comment by aneeshusa** [comment] 2015-04-12 23:58
Just put in [the PR for utf-16le](https://github.com/lifthrasiir/rust-encoding/pull/82). Working on gbk right now, and investigating a potential issue with hz-gb-2312.

**Comment by aneeshusa** [comment] 2015-04-13 04:51
The utf-16le PR just got merged, and I also just put in [a PR to fix GBK encoding](https://github.com/lifthrasiir/rust-encoding/pull/83).

**Comment by lifthrasiir** [comment] 2015-04-13 05:02
cc me

**Comment by aneeshusa** [comment] 2015-04-13 05:20
I just tried to bump the components/script crate's version dependency on the encoding crate to 0.2.30, which includes the utf-16le changes so I could test if they worked. Unfortunately, something is limiting the version number to 0.2.25, and I haven't been able to figure out which crate is the cause; the error message [isn't very informative](https://github.com/rust-lang/cargo/issues/782) and grep isn't helping either. Does anyone know what the impediment is?

**Comment by aneeshusa** [comment] 2015-04-13 06:15
Also, I opened [an issue](https://github.com/lifthrasiir/rust-encoding/issues/84) for a deviation from the spec for hz-gb-2312; if the current implementation is kept it isn't too hard to work around in servo (just an extra pattern in a match statement), so I'm not too worried about which way that goes.

**Comment by Ms2ger** [comment] 2015-04-13 08:47
I would suggest just fixing the `RangeError` issue, and your upstream changes will be pulled in at some point later.

**Closed** 2015-04-14 15:23 UTC
Labels: A-content/bindings, A-content/dom, C-assigned, E-easy, I-wrong
