### ISSUE TITLE
Intermittent OK in /html/browsers/origin/cross-origin-objects/cross-origin-objects-on-new-window.html, /html/browsers/origin/cross-origin-objects/cross-origin-objects.html

### ISSUE THREAD

**Issue by gterzian** [servo/servo#26299] opened 2020-04-24 06:52 UTC

**Comment by CYBAI** [comment] 2020-04-24 06:59
```
  ▶ OK [expected TIMEOUT] /html/browsers/origin/cross-origin-objects/cross-origin-objects-on-new-window.html
```

**Comment by yvt** [comment] 2021-07-18 08:49
I suspect that this is caused by #24972. Premature `load` firing causes a message to be sent to a document that is still loading and thus unable to receive it.

**Comment by yvt** [comment] 2021-08-04 16:11
Actually, fixing #15727 should be enough. We already have a mechanism to delay the containing document's `load` event until the iframe's `load` event is fired, but this obviously doesn't work if the iframe fires another `load` event.

**Comment by jdm** [comment] 2021-08-07 21:07
Fixed by #28560.

**Closed by jdm** 2021-08-07 21:07 UTC
Labels: I-intermittent

**Comment by yvt** [comment] 2021-08-10 16:49
`/html/browsers/origin/cross-origin-objects/cross-origin-objects.html` is still too slow and [causes a timeout](https://github.com/yvt/servo/runs/3287126628?#step:6:1129) in CI:

```
2 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected OK] b'/html/browsers/origin/cross-origin-objects/cross-origin-objects.html'
  │ 
  └ error: XDG_RUNTIME_DIR not set in the environment.
```

According to profiling, much of the execution time is spent inside [the `JS_GC` call](https://github.com/servo/servo/blob/cc1f89863ce0e93ff7ce4f4855bd888df67a51fb/components/script/dom/window.rs#L2198-L2202) in `Window::suspend`. In my testing, removing this call shortened the test execution time by 68% with no visible harmful effects.

What would be the downside of removing this call?

**Comment by jdm** [comment] 2021-08-11 02:14
I believe the risk is potentially leaking significant amounts of layout memory. We stash pointers to memory in DOM nodes that need to be returned to the layout thread to be freed, and any DOM nodes that are not GCed before the containing window object ends up leaking memory.

I don't claim this is a great outcome, but that's why it's important at the moment.

**Comment by yvt** [comment] 2021-08-11 16:50
I see, thanks for the explanation!
