### ISSUE TITLE
Fixed table layout with explicit width for last child is incorrect

### ISSUE THREAD

**Issue by jdm** [servo/servo#16324] opened 2017-04-09 22:52 UTC
This is the underlying reason why the WPT results table is always cut off.
```html
<style>
table {
    table-layout:fixed;
    width:100%;
}

table td:last-child {
    width:50%;
}
</style>
<table>
  <tr>
    <td>Result</th>
    <td>Message</th>
  </tr>
</table>
```
Servo:
<img width="1025" alt="screen shot 2017-04-10 at 8 51 41 am" src="https://cloud.githubusercontent.com/assets/27658/24841574/f7d3cb4c-1dca-11e7-87e4-4c6559141a20.png">
Firefox:
<img width="1395" alt="screen shot 2017-04-10 at 8 52 05 am" src="https://cloud.githubusercontent.com/assets/27658/24841579/ffb9427e-1dca-11e7-86a2-1da927890c89.png">

**Comment by jdm** [comment] 2017-04-09 22:56
https://drafts.csswg.org/css2/tables.html#fixed-table-layout

**Comment by stshine** [comment] 2017-04-10 09:30
Looks like percentage width is not handled correctly.

**Comment by KiChjang** [comment] 2017-04-24 06:41
This has been annoying me for so long, I decided to take a look at it.

Something to note here - in Servo, the first and second column both have the same width as the table itself, so something is clearly wrong here.

**Comment by KiChjang** [comment] 2017-04-24 07:46
This should be the relevant spec: https://drafts.csswg.org/css-tables-3/#distributing-width-to-columns

**Comment by stshine** [comment] 2017-04-24 07:57
I kinda believe that this bug is caused by trying to follow the CSS Table level 3 spec. Note that the CSS Table spec is marked as not ready for implementation, so if you find there is any contradiction between it and CSS2, please follow CSS2 behavior.

**Comment by KiChjang** [comment] 2017-04-24 07:58
... but it looks like we shouldn't be following that part of the spec at all, since it is talking about distributing __excess__ width, not the __used__ width of the columns, which is defined here https://drafts.csswg.org/css-tables-3/#width-distribution-algorithm.

**Comment by KiChjang** [comment] 2017-04-24 08:47
I'm actually quite confused at this point - why do we special-case fixed table layouts? Auto table layouts are computed in `table_flow.rs`, but in the case of fixed table layouts, they're all computed in `table.rs`, and to add on that, we're also following the "distributing excess widths to columns" algorithm when assigning inline sizes in `table.rs`, which is wrong.

@pcwalton perhaps you can weigh in here?

**Comment by pcwalton** [comment] 2017-04-24 21:05
There's no good reason why fixed table is done in a different place from auto table. The reasons are historical. They should be moved to the same place.

**Closed** 2017-04-28 19:31 UTC
Labels: A-layout/table, A-webcompat, C-assigned, C-has-manual-testcase
