### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: RecvError

### ISSUE THREAD

**Issue by wongmjane** [servo/servo#11998] opened 2016-07-01 07:24 UTC
called `Result::unwrap()` on an `Err` value: RecvError
### URL:
http://acid3.acidtests.org/
### Backtrace:
```
frame #0  - 0x0000555b4dbd4a0d - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000555b4dbd4995 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000555b4cda6379 - _<F as alloc..boxed..FnBox<A>>::call_box::hc555946005547ceb
frame #3  - 0x0000555b4dbcb818 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
frame #4  - 0x0000555b4dcd2dcc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000555b4dced3e1 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x0000555b4dcd463a - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x0000555b4dced37e - rust_begin_unwind
frame #8  - 0x0000555b4dd2397f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x0000555b4cd7122d - core::result::unwrap_failed::h36b4b47aa6131a86
frame #10 - 0x0000555b4ce04618 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hcc3e5fcf08d42e0c
frame #11 - 0x0000555b4cde9af7 - script::script_thread::ScriptThread::handle_msgs::hf9fbf9949e23273b
frame #12 - 0x0000555b4cda4a67 - std::panicking::try::call::h99112171a9854ab3
frame #13 - 0x0000555b4dcf75db - __rust_try
frame #14 - 0x0000555b4dcf757e - __rust_maybe_catch_panic
frame #15 - 0x0000555b4cda5cdd - _<F as alloc..boxed..FnBox<A>>::call_box::h4410a344b31b72da
frame #16 - 0x0000555b4dceb5a4 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #17 - 0x00007f28b72c2483 - start_thread
frame #18 - 0x00007f28b6deb6dc - clone
frame #19 - 0x0000000000000000 - <unknown>

```

**Comment by jdm** [comment] 2016-07-01 15:40
This is a duplicate of #6519. Thanks for reporting it!

**Closed by jdm** 2016-07-01 15:40 UTC
