### ISSUE TITLE
Transition between HiDPI and normal resolution screen fails

### ISSUE THREAD

**Issue by djc** [servo/servo#13505] opened 2016-09-29 09:01 UTC
When dragging the Servo window (latest Nightly build) from my HiDPI (mid-2014 rMBP) laptop screen to a normal-density screen, the content appears to be oversized (probably by 4x?).

This is on macOS Sierra.

**Comment by nox** [comment] 2017-10-04 07:53
Closing as duplicate of #12009.

**Closed by nox** 2017-10-04 07:53 UTC
Labels: A-frontend, P-mac
