### ISSUE TITLE
Building Servo on osx 10.11 requires to manually set export OPENSSL_INCLUDE_DIR

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#7303] opened 2015-08-21 08:08 UTC
When I build servo on osx 10.11, I need to set  `OPENSSL_INCLUDE_DIR`:

```sh
export OPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2d_1/include/
```

Otherwise, I get this error:

```
failed to run custom build command for `openssl-sys v0.6.4`
Process didn't exit successfully: `/Users/paul/github/servo/target/release/build/openssl-sys-765ddf9de3c5179c/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/lib
cargo:rustc-link-lib=ssl
cargo:rustc-link-lib=crypto
cargo:rustc-link-lib=z
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
CARGO_MANIFEST_DIR = Some("/Users/paul/github/servo/.cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.4")
OUT_DIR = Some("/Users/paul/github/servo/target/release/build/openssl-sys-765ddf9de3c5179c/out")
OPT_LEVEL = Some("3")
PROFILE = Some("release")
release 3
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O3" "-c" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "-o" "/Users/paul/github/servo/target/release/build/openssl-sys-765ddf9de3c5179c/out/src/openssl_shim.o" "/Users/paul/github/servo/
.cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.4/src/openssl_shim.c"


command did not execute successfully, got: exit code: 1



--- stderr
/Users/paul/github/servo/.cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.4/src/openssl_shim.c:1:10: fatal error: 'openssl/hmac.h' file not found
#include <openssl/hmac.h>
         ^
1 error generated.
thread '<main>' panicked at 'explicit panic', /Users/paul/github/servo/.cargo/registry/src/github.com-0a35038f75765ae4/gcc-0.3.12/src/lib.rs:510
```

**Comment by frewsxcv** [comment] 2015-08-21 15:20
Related issue upstream: https://github.com/sfackler/rust-openssl/issues/255

**Comment by k4rtik** [comment] 2015-10-08 02:50
relinking openssl with brew as mentioned at https://github.com/sfackler/rust-openssl/issues/255#issuecomment-145092826 seems to fix this.

**Comment by bobbwhy** [comment] 2016-03-12 18:14
I installed openssl with brew and tried a variation of the above export command but with reference changed to point to the update brew listed directory 
**still no luck.**

`brew list openssl`
`/usr/local/Cellar/openssl/1.0.2g/bin/c_rehash
/usr/local/Cellar/openssl/1.0.2g/bin/openssl
/usr/local/Cellar/openssl/1.0.2g/include/openssl/ (75 files)
/usr/local/Cellar/openssl/1.0.2g/lib/libcrypto.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2g/lib/libssl.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2g/lib/engines/ (12 files)
/usr/local/Cellar/openssl/1.0.2g/lib/pkgconfig/ (3 files)
/usr/local/Cellar/openssl/1.0.2g/lib/ (4 other files)
/usr/local/Cellar/openssl/1.0.2g/share/man/ (1575 files)`

then 
`export OPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2g/include/`
and then : 
`sudo ./mach build --dev`
still same error `openssl/hmac.h` file not found.
I also tried 
`export OPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2g/include/openssl`
just to be sure.. no luck.

appreciate any help.. thanks !

**Comment by bobbwhy** [comment] 2016-03-12 18:46
ok scratch that ... `brew link --force openssl` as suggested in the thread link helpfully provided by frewsxcv ...   test ran .. thanks!

**Comment by frewsxcv** [comment] 2016-04-16 23:34
Closing as duplicate of https://github.com/servo/servo/issues/7930

**Closed by frewsxcv** 2016-04-16 23:34 UTC
Labels: P-mac
