### ISSUE TITLE
Move IFrameLoadInfo struct and IFrameSandboxState enum to script_traits

### ISSUE THREAD

**Issue by jdm** [servo/servo#8841] opened 2015-12-05 01:45 UTC
These are only used by code in `compositing/` and `script/`, so they're prime candidates for moving into the `script_traits/` crate. This will improve the compilation time if we ever need to modify them.

Code: `components/msg/constellation_msg.rs`, `components/script_traits/lib.rs`

**Comment by fstr** [comment] 2015-12-07 20:09
I'd like to do this one.

Is this a duplicate of #8839 ?

**Comment by KiChjang** [comment] 2015-12-07 20:11
This is more inclusive than #8839, but thanks for telling us! This issue is yours.

**Comment by fstr** [comment] 2015-12-07 21:10
While I'm at it:
Shouldn't IframeLoadInfo be renamed to I**F**rameLoadInfo to be consistent?

**Comment by jdm** [comment] 2015-12-07 21:23
Yep!

**Comment by fstr** [comment] 2015-12-07 21:42
The script_traits component requires the msg component.
https://github.com/servo/servo/blob/master/components/script_traits/Cargo.toml#L11

The msg component `components/msg/constellation_msg.rs` requires the IframeLoadInfo though, which was now moved to the scripts_traits component.
https://github.com/servo/servo/blob/master/components/msg/constellation_msg.rs#L299

This causes a cyclic package dependency. Now I'm not sure how to resolve it.

**Comment by KiChjang** [comment] 2015-12-07 21:50
Create a trait, say, `LoadInfo` in `constellation_msg.rs`, and change `ScriptLoadedURLInFrame` to instead take in a `LoadInfo` as its parameter. Then do `impl LoadInfo for IFrameLoadInfo` (which should now be located at `script_traits`).

**Comment by jdm** [comment] 2015-12-08 06:44
Ack, you're right, I missed that dependency. A trait is overkill for this; thanks for investigating though!

**Comment by jdm** [comment] 2016-01-09 14:59
Now that #8833 and #8835 are solved, the problems mentioned earlier no longer exist.

**Comment by fmmartins** [comment] 2016-01-11 16:10
Can I pick this one? 

`IFrameSandboxState` is lacking documentation, so when I move it to `script_traits/lib.rs` the compiler will complain as this lib has the attribute `#![deny(missing_docs)]` at the top. Should I leave as it is and add a `#[warn(missing_docs)]` on `IFrameSandboxState` enum?

**Comment by jdm** [comment] 2016-01-11 16:28
You can add `/// Whether the sandbox attribute is present for an iframe element`.

**Comment by fmmartins** [comment] 2016-01-11 16:33
Cool, thanks, wasn't sure what to put. Will run the tests and send PR

**Comment by jdm** [comment] 2016-01-11 16:37
There shouldn't be any need to run tests - if it builds, that's good enough for a refactor like this that just involves moving code around.

**Closed** 2016-01-11 20:48 UTC
Labels: C-assigned, E-easy, I-refactor
