### ISSUE TITLE
Google logo doesn't align center on google.com

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#26883] opened 2020-06-12 07:38 UTC
Visit [google.com](https://google.com)

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/6782666/84477693-fe6aba00-acca-11ea-9b57-6b7d1ce70c15.png">

Built with latest master (54d2b7d) on macOS 10.14.6

**Comment by atouchet** [comment] 2020-06-12 13:49
Duplicate of #26096.

**Closed by atouchet** 2020-06-12 13:49 UTC
Labels: C-needs minimized testcase

**Comment by CYBAI** [comment] 2020-06-12 15:58
@atouchet oh, thanks! didn't notice there's an existing one!
