### ISSUE TITLE
Panic in `interpolate_transform_list`

### ISSUE THREAD

**Issue by davezatch** [servo/servo#12027] opened 2016-07-01 10:07 UTC
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }
### URL:
https://uberall.com/en/
### Backtrace:
```
frame #0  - 0x0000000106e416ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000000106e41651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x00000001056aeca4 - _<F as alloc..boxed..FnBox<A>>::call_box::haeff945be1a63d60
frame #3  - 0x0000000106db5947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x0000000107029844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000000107042786 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x000000010702ae88 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x00000001070423df - rust_begin_unwind
frame #8  - 0x0000000107069260 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x00000001056a038e - core::result::unwrap_failed::hf40cb93f6f31ec3d
frame #10 - 0x000000010571de0f - layout_thread::LayoutThread::exit_now::h9c02213ba81aad74
frame #11 - 0x00000001057013a3 - layout_thread::LayoutThread::handle_request_helper::h1029bbb7e9e50e59
frame #12 - 0x00000001056ecf1a - layout_thread::LayoutThread::handle_request::ha13841b9d3ecdc81
frame #13 - 0x00000001056acb1a - std::panicking::try::call::h401e4a3a7768c3f1
frame #14 - 0x000000010704546b - __rust_try
frame #15 - 0x0000000107045405 - __rust_maybe_catch_panic
frame #16 - 0x00000001056ade84 - _<F as alloc..boxed..FnBox<A>>::call_box::h8169792cb3dac906
frame #17 - 0x0000000107040ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #18 - 0x00007fff8b25c99c - _pthread_body
frame #19 - 0x00007fff8b25c919 - _pthread_start

```

**Comment by Manishearth** [comment] 2016-07-01 10:09
The actual stacktrace is

```
ERROR:constellation::constellation: Panic: called `Result::unwrap()` on an `Err` value: ()
ERROR:constellation::constellation: Backtrace:
frame #0  - 0x00000001112af5ee - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x00000001112af571 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000000010fb0fb04 - _<F as alloc..boxed..FnBox<A>>::call_box::h616a2e79f16f295a
frame #3  - 0x000000011121f197 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf0802d30a2c12199
frame #4  - 0x00000001114950a4 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x00000001114adfe6 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x00000001114966e8 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x00000001114adc3f - rust_begin_unwind
frame #8  - 0x00000001114d4ac0 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x00000001107f6675 - core::result::unwrap_failed::hf71a1e71ac3faa15
frame #10 - 0x0000000110965d1f - style::properties::animated_properties::interpolate_transform_list::h54135f97de011227
frame #11 - 0x00000001106e5614 - style::animation::PropertyAnimation::update::h781b7e66eed000d5
frame #12 - 0x00000001106e33c1 - layout::animation::recalc_style_for_animations::_$u7b$$u7b$closure$u7d$$u7d$::hf57191c4de89713f
frame #13 - 0x00000001106e0daa - layout::animation::recalc_style_for_animations::h38618fb7c5cdbefa
frame #14 - 0x00000001106e0dec - layout::animation::recalc_style_for_animations::h38618fb7c5cdbefa
frame #15 - 0x00000001106e0dec - layout::animation::recalc_style_for_animations::h38618fb7c5cdbefa
frame #16 - 0x00000001106e0dec - layout::animation::recalc_style_for_animations::h38618fb7c5cdbefa
frame #17 - 0x00000001106e0dec - layout::animation::recalc_style_for_animations::h38618fb7c5cdbefa
frame #18 - 0x00000001106e0dec - layout::animation::recalc_style_for_animations::h38618fb7c5cdbefa
frame #19 - 0x00000001106e0dec - layout::animation::recalc_style_for_animations::h38618fb7c5cdbefa
frame #20 - 0x00000001106e0dec - layout::animation::recalc_style_for_animations::h38618fb7c5cdbefa
frame #21 - 0x000000010fb628ce - layout_thread::LayoutThread::handle_request_helper::hf1a115257f482e58
frame #22 - 0x000000010fb4e02a - layout_thread::LayoutThread::handle_request::h0166eb7e49682076
frame #23 - 0x000000010fb0d97a - std::panicking::try::call::h63fc14833164b9cc
frame #24 - 0x00000001114b0ccb - __rust_try
frame #25 - 0x00000001114b0c65 - __rust_maybe_catch_panic
frame #26 - 0x000000010fb0ece4 - _<F as alloc..boxed..FnBox<A>>::call_box::hb356c299f5f34320
frame #27 - 0x00000001114ac748 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #28 - 0x00007fff90002c12 - _pthread_body
frame #29 - 0x00007fff90002b8f - _pthread_start

```

**Comment by jdm** [comment] 2016-07-02 22:38
This is a duplicate of #12151. Thanks for reporting it!

**Closed by jdm** 2016-07-02 22:38 UTC
Labels: A-content/css, I-panic
