### ISSUE TITLE
xml:lang="ja" is not supported.

### ISSUE THREAD

**Issue by nhirata** [servo/servo#9670] opened 2016-02-17 02:02 UTC
./mach run http://people.mozilla.org/~nhirata/html_tp/utf16j-find.html
Should show : 
あ
い
う
え
お

あ
い
う
え
お

あ
い
う
え
お

あ
い
う
え
お

Actual:
<img width="770" alt="screen shot 2016-02-16 at 6 01 38 pm" src="https://cloud.githubusercontent.com/assets/1091409/13097609/607105c2-d4d7-11e5-9a0d-0163c1ebca2c.png">

**Comment by frewsxcv** [comment] 2016-02-17 02:03
Possibly a duplicate of https://github.com/servo/servo/issues/6414

**Comment by SimonSapin** [comment] 2016-02-17 05:21
The important part is not `xml:lang="ja"`, it’s that the file starts with bytes FF FE which is the Byte Order Mark for UTF-16-LE.

Since https://github.com/servo/html5ever/commit/2f4f64bbba1dfa4d5bd410260b90de0ffe7846a3 / https://github.com/servo/html5ever/pull/188 there is support for this in html5ever, but we still need to change Servo to use that new bytes-based API.

**Comment by Ms2ger** [comment] 2016-02-17 08:22
Dupe

**Closed by Ms2ger** 2016-02-17 08:22 UTC
