### ISSUE TITLE
Float position error

### ISSUE THREAD

**Issue by Vednier** [servo/servo#13807] opened 2016-10-17 21:20 UTC
Float position error
### Backtrace:

```
 WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 1 , index: PipelineIndex 9  }>: stop_parsing not implemented, full speed ahead!
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 1 , index: PipelineIndex 9  }>: stop_parsing not implemented, full speed ahead!
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 1 , index: PipelineIndex 9  }>: stop_parsing not implemented, full speed ahead!
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 1 , index: PipelineIndex 9  }>: stop_parsing not implemented, full speed ahead!
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 1 , index: PipelineIndex 9  }>: stop_parsing not implemented, full speed ahead!
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 11 , index: PipelineIndex 5  }>: FIXME:  /script> not fully implemented
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 11 , index: PipelineIndex 5  }>: FIXME:  /script> not fully implemented
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 11 , index: PipelineIndex 5  }>: FIXME:  /script> not fully implemented
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 11 , index: PipelineIndex 5  }>: FIXME:  /script> not fully implemented
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 11 , index: PipelineIndex 5  }>: FIXME:  /script> not fully implemented
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 11 , index: PipelineIndex 5  }>: FIXME:  /script> not fully implemented
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 11 , index: PipelineIndex 5  }>: FIXME:  /script> not fully implemented
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 11 , index: PipelineIndex 5  }>: FIXME:  /script> not fully implemented
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 11 , index: PipelineIndex 5  }>: FIXME:  /script> not fully implemented
WARNING: ScriptThread PipelineId { namespace_id: PipelineNamespaceId 11 , index ...     
```

This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-10-17 22:11
https://dxr.mozilla.org/servo/rev/887507b6f86bf4e763f49f12b48ee94029fc9e13/components/layout/floats.rs#246

**Comment by jdm** [comment] 2016-10-17 22:12
I have not been able to reproduce the problem by visiting that URL yet.

**Comment by jdm** [comment] 2017-01-04 00:17
This is probably a duplicate of #11424.

**Comment by nox** [comment] 2017-10-05 13:02
Closing as duplicate of #11424.

**Closed by nox** 2017-10-05 13:02 UTC
Labels: A-webcompat, C-duplicate, I-panic
