### ISSUE TITLE
Spurious script rebuilds with shared target directory with build-cef

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#9794] opened 2016-02-28 16:18 UTC
As seen in: http://build.servo.org/builders/mac-rel-wpt/builds/1966, despite sharing a target directory, runing `./mach build-cef -r` after a `./mach build -r`, it still takes 14 minutes and 43 seconds. This time is because the script crate believes that it has been changed and needs to re-run the build. Here's a sample fingerprint output:

```
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for script v0.0.1 (file:///Users/larsberg/servo/components/servo): precalculated components have changed: 1456675029.000000000s (/Users/larsberg/servo/components/script/parser.out) != 145644786\
6.000000000s (/Users/larsberg/servo/components/script/dom/element.rs)
```

Does not seem to be the same as #7936.

I'm not really sure what this file is (yet), but am looking into it.

CC: @jdm @ms2ger @alexcrichton @metajack

**Comment by larsbergstrom** [comment] 2016-02-28 16:22
This happens on linux, too: http://build.servo.org/builders/linux-rel/builds/2126

**Comment by larsbergstrom** [comment] 2016-02-28 16:26
Interesting, in another run (I've been switching between a normal and CEF build), this time from normal -> CEF, I got:
```
[larsberg@lbergstrom servo]$ RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info ./mach build-cef -r 2>&1 | tee fingerprint-cef-log.txt
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for embedding v0.0.1 (file:///Users/larsberg/servo/ports/cef): failed to read `/Users/larsberg/servo/target/release/.fingerprint/embedding-532c6397928d6611/lib-embedding`
INFO:cargo::ops::cargo_rustc::fingerprint:   cause: No such file or directory (os error 2)
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for devtools v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (devtools_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (devtools_traits v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for msg v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (util v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (util v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for devtools_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (msg v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (msg v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for style v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (style_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (style_traits v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for style_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (util v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (util v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for glutin_app v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (compositing v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (compositing v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for net_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (msg v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (msg v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for compositing v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (canvas v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (canvas v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for script_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (canvas_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (canvas_traits v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for canvas_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (gfx_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (gfx_traits v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for gfx_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (msg v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (msg v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for canvas v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (canvas_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (canvas_traits v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for layout_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (gfx v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (gfx v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for gfx v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (canvas_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (canvas_traits v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for servo v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (canvas v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (canvas v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for script v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (canvas v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (canvas v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for layout v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (canvas v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (canvas v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for webdriver_server v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (compositing v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (compositing v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for profile v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (profile_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (profile_traits v0.0.1 (file:///Users/larsberg/servo/components/servo))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for net v0.0.1 (file:///Users/larsberg/servo/ports/cef): new (devtools_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef)) != old (devtools_traits v0.0.1 (file:///Users/larsberg/servo/components/servo))
```

**Comment by larsbergstrom** [comment] 2016-02-28 16:59
And here' s a run of `./mach build -r` with fingerprinting just after a `./mach build-cef -r`:
```
-index`
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for servo v0.0.1 (file:///Users/larsberg/servo/components/servo): new (canvas v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (canvas v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for net_traits v0.0.1 (file:///Users/larsberg/servo/components/servo): new (msg v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (msg v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for msg v0.0.1 (file:///Users/larsberg/servo/components/servo): new (util v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (util v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for devtools v0.0.1 (file:///Users/larsberg/servo/components/servo): new (devtools_traits v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (devtools_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for devtools_traits v0.0.1 (file:///Users/larsberg/servo/components/servo): new (msg v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (msg v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for compositing v0.0.1 (file:///Users/larsberg/servo/components/servo): new (canvas v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (canvas v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for gfx_traits v0.0.1 (file:///Users/larsberg/servo/components/servo): new (msg v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (msg v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for canvas_traits v0.0.1 (file:///Users/larsberg/servo/components/servo): new (gfx_traits v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (gfx_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for gfx v0.0.1 (file:///Users/larsberg/servo/components/servo): new (canvas_traits v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (canvas_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for style_traits v0.0.1 (file:///Users/larsberg/servo/components/servo): new (util v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (util v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for style v0.0.1 (file:///Users/larsberg/servo/components/servo): new (style_traits v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (style_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for script_traits v0.0.1 (file:///Users/larsberg/servo/components/servo): new (canvas_traits v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (canvas_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for canvas v0.0.1 (file:///Users/larsberg/servo/components/servo): new (canvas_traits v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (canvas_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for layout_traits v0.0.1 (file:///Users/larsberg/servo/components/servo): new (gfx v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (gfx v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for layout v0.0.1 (file:///Users/larsberg/servo/components/servo): new (canvas v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (canvas v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for script v0.0.1 (file:///Users/larsberg/servo/components/servo): new (canvas v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (canvas v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for profile v0.0.1 (file:///Users/larsberg/servo/components/servo): new (profile_traits v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (profile_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for glutin_app v0.0.1 (file:///Users/larsberg/servo/components/servo): new (compositing v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (compositing v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for net v0.0.1 (file:///Users/larsberg/servo/components/servo): new (devtools_traits v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (devtools_traits v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for webdriver_server v0.0.1 (file:///Users/larsberg/servo/components/servo): new (compositing v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (compositing v0.0.1 (file:///Users/larsberg/servo/ports/cef))
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for servo v0.0.1 (file:///Users/larsberg/servo/components/servo): new (canvas v0.0.1 (file:///Users/larsberg/servo/components/servo)) != old (canvas v0.0.1 (file:///Users/larsberg/servo/components/servo))
   Compiling style_traits v0.0.1 (file:///Users/larsberg/servo/componen
```

**Comment by larsbergstrom** [comment] 2016-02-28 17:14
Maybe related to https://github.com/rust-lang/cargo/issues/2383 ?

**Comment by alexcrichton** [comment] 2016-02-29 19:07
This is probably related to how Cargo stores the "package id" for path dependencies. Right now it incorrectly changes the package id depending on which path dependency is the root package being built. That explains the differences in paths you're seeing here.

I've reopened https://github.com/rust-lang/cargo/issues/497 which I believe is the underlying issue here.

**Comment by larsbergstrom** [comment] 2016-02-29 21:13
Thanks for looking into it, @alexcrichton! This would save a *ton* of time on our build machines.

I'm also open to restructuring our various Cargo.toml files, if that's the "correct" fix (or the one that puts us on a better path to only-one-Cargo-toml).

**Comment by alexcrichton** [comment] 2016-02-29 21:17
One way you *may* be able to get around this is to always have the same "root" package and then use `cargo test -p` or `cargo build -p` to build only selective portions of the graph.

**Comment by alexcrichton** [comment] 2016-03-01 00:47
@larsbergstrom it looks like the first error is legit:

```
precalculated components have changed: 1456675029.000000000s (/Users/larsberg/servo/components/script/parser.out) != 1456447866.000000000s (/Users/larsberg/servo/components/script/dom/element.rs)
```

Namely, `parser.out` appears to be [set here](https://github.com/servo/servo/blob/802abf4247b7553a2ab0599e5d3a8ab053f59c54/components/script/dom/bindings/codegen/ply/ply/yacc.py#L74) which is later [turned into a logger](https://github.com/servo/servo/blob/802abf4247b7553a2ab0599e5d3a8ab053f59c54/components/script/dom/bindings/codegen/ply/ply/yacc.py#L3089-L3093). That should probably be in the `OUT_DIR`, or the `build.rs` for the script crate should print out `cargo:rerun-if-changed` for the input files.

That's not the entire story here, however, as I think there's something more subtle at play here. Haven't yet tracked it down yet.

**Comment by alexcrichton** [comment] 2016-03-01 05:08
Aha, found it! I couldn't reproduce because it turns out this was a regression introduced by https://github.com/rust-lang/cargo/pull/2279. This also confirms to me that my suspected fix is indeed the route I would like to take to fix it. Time to clean up the commit and send a PR. Thanks for the cc @larsbergstrom!

**Comment by Ms2ger** [comment] 2016-03-01 08:51
Got rid of `parser.out` in https://github.com/servo/servo/pull/9817

**Comment by larsbergstrom** [comment] 2016-03-01 14:06
@alexcrichton Awesome, thanks a ton for looking into this! It'll really help decrease our CI cycle times.

**Comment by nox** [comment] 2016-03-01 14:56
> This also confirms to me that my suspected fix is indeed the route I would like to take to fix it.

Do you mean the part where we only build specific parts of the graph? Because that's an ugly work-around, I don't see why geckolib and Servo should be driven by the same top-level Cargo.toml file. :(

**Comment by larsbergstrom** [comment] 2016-03-01 14:58
@nox I was assuming Alex meant it was:

> This is probably related to how Cargo stores the "package id" for path dependencies. Right now it incorrectly changes the package id depending on which path dependency is the root package being built.

**Comment by nox** [comment] 2016-03-01 14:58
Oh, disregard me then.

**Closed** 2016-03-05 08:12 UTC
Labels: A-build, A-content/script
