### ISSUE TITLE
Intermittent timeout of /html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-002.html

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9463] opened 2016-01-30 00:18 UTC
```
Tests with unexpected results:
  ▶ TIMEOUT [expected FAIL] /html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-002.html
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })', ../src/libcore/result.rs:688
  │ stack backtrace:
  │    1:     0x7f3fc7edf1b0 - sys::backtrace::tracing::imp::write::hd273f86d5325347aweu
  │    2:     0x7f3fc7ee20c5 - panicking::default_handler::_<closure>::closure.42335
  │    3:     0x7f3fc7ee1b6f - panicking::default_handler::h907ce0af740f5f06spy
  │    4:     0x7f3fc7ecb0d6 - sys_common::unwind::begin_unwind_inner::ha417239bcab1f2ff56s
  │    5:     0x7f3fc7ecb838 - sys_common::unwind::begin_unwind_fmt::hac4637ed0b5bb49eb6s
  │    6:     0x7f3fc7ede811 - rust_begin_unwind
  │    7:     0x7f3fc7f157af - panicking::panic_fmt::he5f9c513e9167673LnK
  │    8:     0x7f3fc67b3e0c - constellation::Constellation<LTF, STF>::handle_request::h17911856205817768967
  │    9:     0x7f3fc679e3f7 - export::compositing::constellation::Constellation<LTF, STF>::start::_<closure>::closure.22535
  │   10:     0x7f3fc679dc53 - sys_common::unwind::try::try_fn::h7760926197616253908
  │   11:     0x7f3fc7ede658 - __rust_try
  │   12:     0x7f3fc7eda93b - sys_common::unwind::try::inner_try::h62f00e3d34dbb509D3s
  │   13:     0x7f3fc679fc3a - boxed::F.FnBox<A>::call_box::h14536320264203813412
  │   14:     0x7f3fc7ee0933 - sys::thread::Thread::new::thread_start::hb3a0514b9d87669e1mx
  │   15:     0x7f3fc4469181 - start_thread
  │   16:     0x7f3fc3f8047c - __clone
  └   17:                0x0 - <unknown>
```

**Comment by jdm** [comment] 2016-04-22 15:41
Duplicate of #8815.

**Closed by jdm** 2016-04-22 15:41 UTC
Labels: I-intermittent
