### ISSUE TITLE
Support using --features argument with --android in mach

### ISSUE THREAD

**Issue by connorimes** [servo/servo#8173] opened 2015-10-23 20:14 UTC
Currently you can't run a command like:
<pre>
./mach build -d --features "energy-profiling" --android
</pre>
Instead we need to run:
<pre>
./mach build -d --features "energy-profiling" --target=arm-linux-androideabi
</pre>
It's not a big deal, but would be a nice addition to support features when specifying android.

**Comment by connorimes** [comment] 2015-10-23 20:29
FYI, when running the first command, the error is:
<pre>
Invalid arguments.

Usage:
    cargo build [options]
</pre>

**Comment by mbrubeck** [comment] 2015-10-23 20:40
The relevant code is in [build_commands.py](https://github.com/servo/servo/blob/6f59acdd0a5c3f37b243daa8dcc30908f3f3bfd3/python/servo/build_commands.py#L125-L247).

The problem is that the `--features` option from the command line is passed through to cargo as part of the `params` variable, while [this code](https://github.com/servo/servo/blob/6f59acdd0a5c3f37b243daa8dcc30908f3f3bfd3/python/servo/build_commands.py#L213-L217) adds a second `--features` argument.  Cargo requires all features to be passed in a single argument.

This could be fixed by adding an explicit `@CommandArgument('--features', ...)` to this command, and using this to initialize the `features` list instead of initializing it to an empty list. It can use [`nargs='+'`](https://docs.python.org/3/library/argparse.html#nargs) like [this `--include` argument](https://github.com/servo/servo/blob/6f59acdd0a5c3f37b243daa8dcc30908f3f3bfd3/python/servo/testing_commands.py#L202) to allow a list of values.

**Comment by nxnfufunezn** [comment] 2015-10-24 08:54
I can do this if you want..

**Closed** 2015-10-30 18:08 UTC
Labels: A-mach, C-assigned, E-easy, L-python
