### ISSUE TITLE
servo doesn'r run at all

### ISSUE THREAD

**Issue by Fiedzia** [servo/servo#6255] opened 2015-06-02 09:53 UTC
Tested on ubuntu 14.10,
commit ec79881471bf3e952f40ee7021b561532a9020c6
compiled fine, but when trying to run it, I'm getting this:

./mach run ./mach run --release tests/html/about-mozilla.html
[glutin] x error code=21 major=0 minor=0!
[glutin] x error code=22 major=0 minor=0!
[glutin] x error code=23 major=0 minor=0!
[glutin] x error code=26 major=0 minor=0!
[glutin] x error code=27 major=0 minor=0!
[glutin] x error code=28 major=0 minor=0!
[glutin] x error code=30 major=0 minor=0!
[glutin] x error code=33 major=0 minor=0!
[glutin] x error code=48 major=0 minor=0!
thread '<main>' panicked at 'glx::MakeCurrent failed', /home/mdziardziel/git/servo/.cargo/git/checkouts/glutin-72cd277ab8976bc1/servo/src/x11/window/mod.rs:744
stack backtrace:
   1:     0x7f16d18a4b93 - sys::backtrace::write::h2057a56abbba7b15Fcs
   2:     0x7f16d18a84d1 - panicking::on_panic::h2be90c511aa31517uXw
   3:     0x7f16d189382a - rt::unwind::begin_unwind_inner::hc37996f90d433aa1eDw
   4:     0x7f16d08ba03e - rt::unwind::begin_unwind::h1037884550193857589
   5:     0x7f16d08bcbc0 - platform::window::Window::make_current::h4af835a59d1a6801xfc
   6:     0x7f16d086c71e - window::Window::new::h70ccfc298bb54454Vna
   7:     0x7f16d06fad5d - main::h3d82ced378541a43paa
   8:     0x7f16d18ad428 - rust_try_inner
   9:     0x7f16d18ad415 - rust_try
  10:     0x7f16d18a9d23 - rt::lang_start::hd01ce9da2687b0ddySw
  11:     0x7f16cf13aec4 - __libc_start_main
  12:     0x7f16d06fa368 - <unknown>
  13:                0x0 - <unknown>
[glutin] x error code=50 major=0 minor=0!
Error running mach:

    ['run', './mach', 'run', '--release', 'tests/html/about-mozilla.html']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '['components/servo/target/release/servo', './mach', 'run', 'tests/html/about-mozilla.html']' returned non-zero exit status 101

  File "/home/mdziardziel/git/servo/python/servo/post_build_commands.py", line 74, in run
    subprocess.check_call(args, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by nox** [comment] 2015-06-02 10:19
Duplicate of #6042.

**Closed by nox** 2015-06-02 10:19 UTC
Labels: C-duplicate
