### ISSUE TITLE
Hovering links in wikipedia underlines wrong area

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#18164] opened 2017-08-20 23:10 UTC
In the screenshot below I hovered over the "Lundomys molitor" link in the feature article section and instead of underlining that link the underline was put at a different location on the screen (here it's showing above the "Main page" link on the left):

![screen shot 2017-08-21 at 11 07 34 am](https://user-images.githubusercontent.com/547158/29499249-4ce50c46-8661-11e7-91be-eb904bb9f633.png)

**Comment by SimonSapin** [comment] 2017-08-21 12:31
Maybe related to https://github.com/servo/servo/issues/12105 ?

**Comment by peterbb** [comment] 2017-09-12 03:16
After downloading a page from Wikipedia and removing most of the code, I've come up with a minimal example which seems to produce the error:

    <!DOCTYPE html>
    <html>
        <head>
            <style>
                .mw-body-content {
                    position: relative;
                    z-index: 0
                }
            </style>
        </head>
        <body>
            <div class="mw-body-content">
                Lorem ipsum dolor sit amet, <a href="">consectetur adipiscing elit</a>, sed do eiusmod.
            </div>
        </body>
    </html>

Rendered as:
![image](https://user-images.githubusercontent.com/789911/30306563-24e3cc9a-9779-11e7-83e1-3ab29e3cbac1.png)

**Comment by xhallix** [comment] 2017-09-15 13:43
For me, all the links are swapped in the same way , so I guess this is a duplicate of https://github.com/servo/servo/issues/12105 as @SimonSapin already pointed out

**Comment by nox** [comment] 2017-10-04 08:13
Closing as duplicate of #12105.

**Comment by jdm** [comment] 2017-10-04 08:38
I'm not convinced this is a duplicate yet.

**Comment by dralley** [comment] 2020-03-25 14:18
This appears to be fixed w/ the minimal test case.

**Closed** 2020-03-25 14:26 UTC
Labels: A-layout/text, C-has-manual-testcase
