### ISSUE TITLE
assertion failed: count_cell.get() > 0

### ISSUE THREAD

**Issue by choudanu4** [servo/servo#12201] opened 2016-07-03 20:27 UTC
assertion failed: count_cell.get() > 0
### URL:
http://www.androidpolice.com/2016/07/03/lego-city-my-city-2-mixes-elements-from-sim-city-and-sandbox-games-for-kid-friendly-fun/

### What didn't load:
The disqus comments section, the embedded youtube link, and the ads did not load before the issue arose. 

### Backtrace:
```
frame #0  - 0x0000564bac54844d - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000564bac5483d5 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000564bab718509 - _<F as alloc..boxed..FnBox<A>>::call_box::hc555946005547ceb
frame #3  - 0x0000564bac53f218 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc61828c8a9f6df01
frame #4  - 0x0000564bac64680c - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000564baaf5ae3f - std::panicking::begin_panic::h0bf39f6d43ab9349
frame #6  - 0x0000564bab5cd640 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h71d7672a3472afa1
frame #7  - 0x0000564bab5cb14b - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h724ec798d0dfe84e
frame #8  - 0x0000564bab723454 - script::script_thread::ScriptThread::handle_msg_from_script::hfac8a5d67415fa31
frame #9  - 0x0000564bab774a9f - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hcc3e5fcf08d42e0c
frame #10 - 0x0000564bab75bc87 - script::script_thread::ScriptThread::handle_msgs::hf9fbf9949e23273b
frame #11 - 0x0000564bab716bf7 - std::panicking::try::call::h99112171a9854ab3
frame #12 - 0x0000564bac66b01b - __rust_try
frame #13 - 0x0000564bac66afbe - __rust_maybe_catch_panic
frame #14 - 0x0000564bab717e6d - _<F as alloc..boxed..FnBox<A>>::call_box::h4410a344b31b72da
frame #15 - 0x0000564bac65efe4 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #16 - 0x00007fd350f08183 - start_thread
frame #17 - 0x00007fd350a1e37c - clone
frame #18 - 0x0000000000000000 - <unknown>

```

**Comment by jdm** [comment] 2016-07-04 02:16
This is a duplicate of #12047. Thanks for reporting it!

**Closed by jdm** 2016-07-04 02:16 UTC
