### ISSUE TITLE
iframe's contentWindow property is null right after creating iframe

### ISSUE THREAD

**Issue by sole** [servo/servo#7162] opened 2015-08-11 17:15 UTC
I'm trying to make sure I don't access an iframe before it's ready so I'm adding a listener to its contentWindow 'load' event. [This code](https://github.com/sole/servo-gradient/blob/ebc6df7ead590dfbe765db922219ae3421a99ae7/js/main.js#L15-L17) works fine in Firefox:

```javascript
fr.contentWindow.addEventListener('load', function() {
	fr.contentWindow.postMessage('hey', '*');
});
```
but it fails in Servo with 
`
ERROR:js::rust: Error at file:///Users/sole/data/servodemos/gradient/js/main.js:17: TypeError: fr.contentWindow is null
`

I tried just modifying the `onload` property on the iframe and *that* works instead!

```javascript
fr.onload = function() {
	console.log('hello');
};
```

**Comment by Manishearth** [comment] 2015-08-11 17:22
This is mostly a dupe of #5500 (different bug, same source)

**Comment by jdm** [comment] 2015-08-11 18:18
Thanks for reporting this! We already track this in #5500 (and specifically #5240), and I don't think there's any new information present here, so I'll close this as a duplicate.

**Closed by jdm** 2015-08-11 18:18 UTC
Labels: A-content/dom, I-wrong
