### ISSUE TITLE
Reddit fails during layout

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#18471] opened 2017-09-12 22:14 UTC
Opening reddit on the latest nightly, I see:

```
Received Tick when progress was Idle: https://github.com/servo/servo/issues/10322
Received Tick when progress was Idle: https://github.com/servo/servo/issues/10322
called `Option::unwrap()` on a `None` value (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }, at src/libcore/option.rs:335)
stack backtrace:
   0:        0x10f8f007e - backtrace::backtrace::trace::hffbde36f4c49322f
   1:        0x10f8f00bc - backtrace::capture::Backtrace::new::h80e07836b14bc45d
   2:        0x10e64d628 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h8b1c9fab91ffe947
   3:        0x11060d8d1 - std::panicking::rust_panic_with_hook::h39b7827c1b4b8104
   4:        0x11060d774 - std::panicking::begin_panic::he02bfa10c7d2e5b4
   5:        0x11060d642 - std::panicking::begin_panic_fmt::h755b0110abbcd591
   6:        0x11060d5aa - rust_begin_unwind
   7:        0x11063ba33 - core::panicking::panic_fmt::hc292af45e1f004da
   8:        0x11063b936 - core::panicking::panic::h4a49b545ff1384a2
   9:        0x10f45d82b - _$LT$layout..fragment..Fragment$u20$as$u20$layout..display_list_builder..FragmentDisplayListBuilding$GT$::build_display_list_for_background_if_applicable::hfdd7d37a0c8d7817
  10:        0x10f4646c5 - _$LT$layout..fragment..Fragment$u20$as$u20$layout..display_list_builder..FragmentDisplayListBuilding$GT$::build_display_list::hac5b7915fabfc321
  11:        0x10f44fef4 - _$LT$layout..block..BlockFlow$u20$as$u20$layout..flow..Flow$GT$::build_display_list::h54fd15ffdfdfaddc
  12:        0x10f4add6a - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  13:        0x10f4addb2 - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  14:        0x10f4addb2 - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  15:        0x10f4addb2 - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  16:        0x10f4addb2 - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  17:        0x10f4addb2 - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  18:        0x10f4addb2 - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  19:        0x10f4addb2 - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  20:        0x10f4addb2 - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  21:        0x10f4addb2 - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  22:        0x10f4addb2 - layout::traversal::BuildDisplayList::traverse::h384a48235aafb789
  23:        0x10f495dd2 - layout::sequential::build_display_list_for_subtree::h97ea51c98329833e
  24:        0x10e8cc6b3 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::h1a37207e076770ba
  25:        0x10e8c6e17 - layout_thread::LayoutThread::handle_reflow::h91c62341fcf5aee4
  26:        0x10e8b92ac - layout_thread::LayoutThread::handle_request_helper::h9c7564bb0557cdef
  27:        0x10e8b463b - _$LT$layout_thread..LayoutThread$u20$as$u20$layout_traits..LayoutThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::hd3aefedf5413e64a
  28:        0x10e81628d - std::sys_common::backtrace::__rust_begin_short_backtrace::ha4951ebb58163d1c
  29:        0x10e81772d - std::panicking::try::do_call::h0fae9157167e9ed4
  30:        0x11060eb0c - __rust_maybe_catch_panic
  31:        0x10e8498f5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h2e572240bc01f08b
  32:        0x11060a82b - std::sys::imp::thread::Thread::new::thread_start::hf86051f13e2a9156
  33:     0x7fff8f48e93a - _pthread_body
  34:     0x7fff8f48e886 - _pthread_start
ERROR:servo: called `Option::unwrap()` on a `None` value
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }, at src/libcore/result.rs:906)
stack backtrace:
   0:        0x10f8f007e - backtrace::backtrace::trace::hffbde36f4c49322f
   1:        0x10f8f00bc - backtrace::capture::Backtrace::new::h80e07836b14bc45d
   2:        0x10e64d628 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h8b1c9fab91ffe947
   3:        0x11060d8d1 - std::panicking::rust_panic_with_hook::h39b7827c1b4b8104
   4:        0x11060d774 - std::panicking::begin_panic::he02bfa10c7d2e5b4
   5:        0x11060d642 - std::panicking::begin_panic_fmt::h755b0110abbcd591
   6:        0x11060d5aa - rust_begin_unwind
   7:        0x11063ba33 - core::panicking::panic_fmt::hc292af45e1f004da
   8:        0x10f42c996 - core::result::unwrap_failed::ha5a64cae08bd7ca2
   9:        0x10f493e06 - _$LT$layout..query..LayoutRPCImpl$u20$as$u20$script_layout_interface..rpc..LayoutRPC$GT$::hit_test::h9aea6e8f0b7256dc
  10:        0x10ee65153 - script::dom::document::Document::handle_mouse_move_event::h3bf8bcd0213c6ddd
  11:        0x10f073afb - script::script_thread::ScriptThread::handle_event::h54d153133cb3ea90
  12:        0x10f05ca43 - script::script_thread::ScriptThread::handle_msg_from_constellation::h97f43bae8a55e4e9
  13:        0x10f05b64c - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hfbaad58db0ef4be4
  14:        0x10f057cf2 - script::script_thread::ScriptThread::handle_msgs::h95c93529e92dbb68
  15:        0x10e944167 - std::sys_common::backtrace::__rust_begin_short_backtrace::h890d7da998215f97
  16:        0x10ea61e9d - std::panicking::try::do_call::h90ef51a8539fdc93
  17:        0x11060eb0c - __rust_maybe_catch_panic
  18:        0x10ec4d785 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h15a3b91d3717078f
  19:        0x11060a82b - std::sys::imp::thread::Thread::new::thread_start::hf86051f13e2a9156
  20:     0x7fff8f48e93a - _pthread_body
  21:     0x7fff8f48e886 - _pthread_start
ERROR:servo: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
```

**Comment by mateon1** [comment] 2017-09-12 22:22
I think this might be a duplicate of #17176. The panic message is different, but the panic happens in the same function, `build_display_list_for_background_if_applicable`.

**Comment by ferjm** [comment] 2018-02-16 11:31
I was not able to reproduce this panic and #17176 was recently fixed, so I assume that this was indeed a duplicate. Please, reopen the issue if you find the panic again.

**Closed by ferjm** 2018-02-16 11:31 UTC
Labels: A-gfx/displaylist, I-panic
