### ISSUE TITLE
unknown completed load Stylesheet("https://secure.gravatar.com/css/hovercard.css?ver=2016Julaa")

### ISSUE THREAD

**Issue by st3fan** [servo/servo#12075] opened 2016-07-01 15:28 UTC
unknown completed load Stylesheet("https://secure.gravatar.com/css/hovercard.css?ver=2016Julaa")
### URL:

https://www.computest.nl/blog/startencrypt-considered-harmful-today/
### Backtrace:

```
frame #0  - 0x00000001070946ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000000107094651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000000106365086 - _<F as alloc..boxed..FnBox<A>>::call_box::h6059122298f825d8
frame #3  - 0x0000000107008947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010727c844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000000107295786 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x000000010727de88 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x00000001072953df - rust_begin_unwind
frame #8  - 0x00000001072bc260 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x00000001072c3d05 - core::option::expect_failed::hdb92832549f56a85
frame #10 - 0x0000000105b9fab1 - script::document_loader::DocumentLoader::finish_load::hc807fb8cb9c56a2d
frame #11 - 0x0000000105b9d751 - script::dom::document::Document::finish_load::h1ce7e49c25d85fc2
frame #12 - 0x000000010620bf9b - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h315c5e417b85cb3a
frame #13 - 0x0000000106209d65 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::hc0416bc7ab472afc
frame #14 - 0x000000010637095c - script::script_thread::ScriptThread::handle_msg_from_script::hd1f5e7b2423a8c64
frame #15 - 0x00000001063cca71 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc67d8b381c013b79
frame #16 - 0x00000001063b273f - script::script_thread::ScriptThread::handle_msgs::h236c5be60a207bea
frame #17 - 0x0000000106363907 - std::panicking::try::call::h645a328f039d97c6
frame #18 - 0x000000010729846b - __rust_try
frame #19 - 0x0000000107298405 - __rust_maybe_catch_panic
frame #20 - 0x0000000106364ab4 - _<F as alloc..boxed..FnBox<A>>::call_box::h3db95636eb747818
frame #21 - 0x0000000107293ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #22 - 0x00007fff82eb199c - _pthread_body
frame #23 - 0x00007fff82eb1919 - _pthread_start

```

**Comment by jdm** [comment] 2016-07-01 15:54
Tried to reproduce in a debug build on OS X and hit #12081 first.

**Comment by jdm** [comment] 2016-07-02 22:16
@mbrubeck This assertion seems to be part of the ASCII fast-path code added in #11273.

**Comment by jdm** [comment] 2016-07-02 22:51
http://cbc.ca/ is the URL I was able to reproduce this with after disabling #12081.

**Comment by jdm** [comment] 2016-07-02 22:56
My investigations here show a very similar stack to #12047. I suspect this problem will be fixed when that is fixed.

**Comment by nox** [comment] 2017-10-04 08:22
I can't reproduce this on either website.

**Closed by nox** 2017-10-04 08:22 UTC
Labels: A-content/dom, C-reproduced, I-panic
