### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "SendError(..)"

### ISSUE THREAD

**Issue by jonathandturner** [servo/servo#17116] opened 2017-06-01 00:12 UTC
Seeing the below when opening reddit in a recent nightly.  Seems different enough from https://github.com/servo/servo/issues/17113 to file as a separate issue.

called `Result::unwrap()` on an `Err` value: "SendError(..)"
### Servo Version:
Servo 0.0.1-71a4dae-dirty
### Backtrace:
```

WARNING: <Constellation>: creating replacement pipeline for about:failure
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }>: Resuming an already resumed timer.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: Panic hook called.
ERROR: called `Result::unwrap()` on an `Err` value: "SendError(..)"

stack backtrace:
   0:        0x10901fd2e - backtrace::backtrace::trace::h15d769766aa71ae0
   1:        0x10901febc - backtrace::capture::Backtrace::new::hde1afc496271e12d
   2:        0x108440ba9 - constellation::constellation::log_entry::h010d128f1d0b3bfd
   3:        0x10843fbc2 - _$LT$constellation..constellation..FromCompositorLogger$u20$as$u20$log..Log$GT$::log::h0f1710d1030ea40b
   4:        0x109f5f12e - log::__log::h9babd36d99ae110e
   5:        0x1082e40f0 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h3eb9c088b479c914
   6:        0x109f87d56 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
   7:        0x109f87bb4 - std::panicking::begin_panic::h69fe06a9d67b6165
   8:        0x109f87b22 - std::panicking::begin_panic_fmt::haf8695bfb6c52436
   9:        0x109f87a87 - rust_begin_unwind
  10:        0x109fb33c0 - core::panicking::panic_fmt::hfedd6515bcee8bb1
  11:        0x108943600 - core::result::unwrap_failed::h5f5701175b9b20aa
  12:        0x108c0be44 - script::dom::window::Window::force_reflow::h0e43c9eca4f862fc
  13:        0x108c0e3cd - script::dom::window::Window::reflow::h5fd1383556e3b75a
  14:        0x108c0ed60 - script::dom::window::Window::offset_parent_query::h4aa3626b72357dc5
  15:        0x108aefba9 - _$LT$script..dom..htmlelement..HTMLElement$u20$as$u20$script..dom..bindings..codegen..Bindings..HTMLElementBinding..HTMLElementBinding..HTMLElementMethods$GT$::OffsetWidth::h83ff1be6dc41b47e
  16:        0x108876ff8 - std::panicking::try::do_call::hbfa679c7ecdf1523
  17:        0x109f88e8a - __rust_maybe_catch_panic
  18:        0x108dc53ac - script::dom::bindings::codegen::Bindings::HTMLElementBinding::HTMLElementBinding::get_offsetWidth::h6a66814f60325603
  19:        0x108a26531 - script::dom::bindings::utils::generic_call::hd2e0cf1c828068c3
  20:        0x10960fe54 - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
  21:        0x109632f7b - CallGetter(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::Value>, JS::Handle<js::Shape*>, JS::MutableHandle<JS::Value>)
  22:        0x109613857 - js::GetProperty(JSContext*, JS::Handle<JS::Value>, JS::Handle<js::PropertyName*>, JS::MutableHandle<JS::Value>)
  23:        0x109605407 - Interpret(JSContext*, js::RunState&)
  24:        0x1095fe763 - js::RunScript(JSContext*, js::RunState&)
  25:        0x10960ff72 - js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct)
  26:        0x1092b4475 - js::jit::DoCallFallback(JSContext*, js::jit::BaselineFrame*, js::jit::ICCall_Fallback*, unsigned int, JS::Value*, JS::MutableHandle<JS::Value>)
```
This report was generated by the browser.html issue reporter.

**Comment by nox** [comment] 2017-10-07 10:07
Closing as duplicate of #17064.

**Closed by nox** 2017-10-07 10:07 UTC
Labels: A-webcompat, I-panic
