### ISSUE TITLE
Servo w/ Browser.html seems to scroll off the bottom with Wikipdia

### ISSUE THREAD

**Issue by ekr** [servo/servo#12246] opened 2016-07-04 23:56 UTC
Revision:
f9e058d5e7ca3bf47b29016f5fb275e0271dce9f

![screen shot 2016-07-04 at 4 53 45 pm](https://cloud.githubusercontent.com/assets/1111457/16571070/1af51b16-4208-11e6-8998-ea96b3d3a8be.png)

I can scroll way past this so that the screen is totally white, but this seemed like the clearest example.

**Comment by ConnorGBrewster** [comment] 2016-07-05 00:25
Closing as a dupe of #10206.
Thank you for reporting this!

**Closed by ConnorGBrewster** 2016-07-05 00:25 UTC
