### ISSUE TITLE
iframe not rendered without initial `src` attribute

### ISSUE THREAD

**Issue by mmatyas** [servo/servo#8607] opened 2015-11-19 16:33 UTC
The contents of an iframe are not rendered if its `src` attribute has no initial value, even if it's set later by JavaScript code. The page itself loads "correctly", eg. JS code on the iframe'd page does run, but nothing shows up on the container site.

Here's a small example, first the main page:

```html
<html>
<body>
	<iframe id="myframe"></iframe>
	<script>
		var frame = document.getElementById("myframe");
		frame.src = "iframe.html";
	</script>
</body>
</html>
```

and the iframe:

```html
<html>
<body>

Hello iFrame!

</body>
</html>
```

Opening the main page in eg. Firefox does load the second page too, and if I remember correctly, this feature also worked in Servo once.

This example is also available here: https://mmatyas.github.io/tests/iframe/

**Comment by jdm** [comment] 2015-11-19 16:36
Thanks for filing this! It looks like a duplicate of #7826 to me.

**Comment by jdm** [comment] 2015-11-19 16:37
The fact that we don't support `<iframe><iframe>` right now is a separate issue, however. Please file that independently?

**Closed by jdm** 2015-11-19 16:36 UTC

**Comment by mmatyas** [comment] 2015-11-20 10:52
Hm, but iframes do seem to work for me.
