### ISSUE TITLE
Issues with the ```C-assigned``` label do not actually have an assignee

### ISSUE THREAD

**Issue by webmaven** [servo/servo#12155] opened 2016-07-02 03:09 UTC
eg. 19 of the issues with the ```E-easy``` label also have the ```C-assigned``` label, but none of them actually have assignees: 
https://github.com/servo/servo/issues?q=is%3Aopen+label%3AE-easy+label%3AC-assigned+no%3Aassignee

**Comment by ConnorGBrewster** [comment] 2016-07-02 03:10
@webmaven we have no way to assign people unless they are apart of the Servo organization. As a workaround we use the C-assigned label to mark that the issue is assigned.

**Comment by webmaven** [comment] 2016-07-02 03:36
Have you considered creating a group with read-only permissions in the organization, and having a bot automatically add Github users to that group?

I can think of two possible policies for triggering the bot:

- Whenever any user not already in the organization takes an action like creating an issue or commenting on an issue
- When a user that **does** have write permissions gives an explicit signal such as leaving a comment that contains something like ```:ok: @user``` or ```:angel: @user```

Optionally, if you have an explicit trigger, the bot can also assign the indicated user to the issue the comment was added to, saving a step.

Thoughts?

**Comment by aneeshusa** [comment] 2016-07-02 03:55
@webmaven this is being tracked over at https://github.com/servo/highfive/issues/30, where it looks like we are looking at a similar solution. I'm going to close this but feel free to chime in over there!

**Closed by aneeshusa** 2016-07-02 03:55 UTC

**Comment by webmaven** [comment] 2016-07-02 04:02
👍
