### ISSUE TITLE
Fix as many clippy problems as possible

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#31500] opened 2024-03-04 22:19 UTC
Steps: 

1. Get Servo building and running locally following project documentation at http://github.com/servo/servo.
2. Run `./mach cargo-clippy`
3. Fix an issue by understanding what the error means and correcting the issue. For instance
```
warning: redundant field names in struct initialization
   --> components/remutex/lib.rs:168:13
    |
168 |             data: data,
    |             ^^^^^^^^^^ help: replace it with: `data`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names
    = note: `#[warn(clippy::redundant_field_names)]` on by default
```
    In this case `data: data` can just be replaced with `data`.
4. Open an pull request with your fix, filling out the template, and giving it a full name like the following "clippy: Fix a redundant field warning in `components/remutex/lib.rs`. 
5. Include a link to this issue in your pull request description body.

<h3>As this issue is large enough to be worked on in parallel, please don't ask to assign it to yourself. If you want to post fixes for a particular section of code, just check the PRs linked here to make sure that you are fixing different issues.</h3>

***NOTE: The warnings for [missing safety documentation](https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc) for unsafe code is already handled in PR #33748. Please ignore those.***

**Comment by servo-highfive** [comment] 2024-03-04 22:19
Hi! If you have any questions regarding this issue, feel free to make a comment here, or ask it in [Zulip](https://servo.zulipchat.com/).

If you intend to work on this issue, then add `@servo-highfive: assign me` to your comment, and I'll assign this to you. :smile:

**Comment by pranayrauni** [comment] 2024-03-05 06:50
Hi I want to work on this issue. 

@servo-highfive: assign me

**Comment by servo-highfive** [comment] 2024-03-05 06:50
Hey @pranayrauni! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by mnaibei** [comment] 2024-03-05 09:28
Hi @mrobinson, I am an Outreachy applicant and I would like to undertake this project.

**Comment by Payne680** [comment] 2024-03-05 13:56
@mrobinson Please I will love to work on this task but can you give some resources on how to successfully run the project locally ?

**Comment by Loirooriol** [comment] 2024-03-06 09:21
BTW, some of the clippy warnings can be fixed automatically, e.g.

```
CARGO_BUILD_RUSTC=rustc cargo clippy --fix -p layout_2020 --broken-code
```

will apply some fixes automatically in the `layout_2020` crate (and its tests). But some warnings need to be addressed manually.

Note that this can mess up the formatting, so remember to run `./mach fmt` afterwards.

**Comment by mrobinson** [comment] 2024-03-06 10:10
> BTW, some of the clippy warnings can be fixed automatically, e.g.
> 
> ```
> CARGO_BUILD_RUSTC=rustc cargo clippy --fix -p layout_2020 --broken-code
> ```
> 
> will apply some fixes automatically in the `layout_2020` crate (and its tests). But some warnings need to be addressed manually.
> 
> Note that this can mess up the formatting, so remember to run `./mach fmt` afterwards.

I do not recommend using `clippy --fix` as a new contributor actually. Sometimes it can change the logical meaning of the code that it changes, so it is better to do the fix manually. It's also a good way to start understanding a bit of the Servo code.

**Comment by eerii** [comment] 2024-03-07 20:51
I'm going to copy this here since now the big pr is split into multiple ones, and it can be helpful so people looking to fix new warnings can know where to continue:

The prs above are fixes for most warnings until `net` is compiled, **excluding**:
- `result_unit_err`: use a custom `Error` type instead of `Result<_, ()>`
- `missing_safety_doc`: unsafe function's docs miss `# Safety` section

They also hopefully remove all clippy **errors** until `script` is compiled, so more warnings can be caught.

The next steps to tackle would be:
- Fix the remaining `net` warnings
- Create proper `Error` types for the first warnings
- Write safety documentation (probably best to leave it for someone that is familiar with the unsafe code in the project)
- Work with `canvas`, `webdriver_server` and a few small others before tackling the big ones, which are `script`, `layout` and `layout2020`. `script` alone has 27358 warnings and 433 errors, so it will be the biggest undertaking

**Comment by eerii** [comment] 2024-03-12 16:19
With this last prs we are a bit closer to cleaning the clippy warnings. These should include every warning that is not part of `script`, excluding the same error type and safety comment issues as before. now that `script` is next, you can see that it contains all warnings created by codegen code, so that will be trickier.

**Comment by jahielkomu** [comment] 2024-05-02 10:17
Hello everyone.
Is it just me or is ```./mach cargo-clippy``` actually producing an error?

**Comment by sagudev** [comment] 2024-05-02 10:18
What error?

**Comment by jahielkomu** [comment] 2024-05-02 10:31
> What error?

Thanks for asking @sagudev.
I have pasted what I get in this pastebin, https://paste.mozilla.org/Ea3ohjZt

It might be an isolated incident on my end.
Kindly advise how to go about it.

**Comment by jahielkomu** [comment] 2024-05-02 10:41
> This is due to #32208, you might need to do `mach clean` and `mach bootstrap` again (also make sure to have stable internet connection).

Alright, thanks again.
Let me do that.

**Comment by hieudo-dev** [comment] 2024-05-29 04:28
Hi everyone! I'm looking to make contributions to the servo project and stumbled upon this issue. Judging from the most recent PRs it seems like all of the work has been completed already but I see the issue is still open. 

I'm wondering if someone can let me know if there's any beginner friendly work left to do here or should I wait until there are more beginner issues available (since this is the only one left tagged with `E-less-complex` or `B-newcomer` ?
Thanks in advance!

**Comment by Otom-obhazi** [comment] 2024-10-08 14:01
@mrobinson Please I will love to work on this task

**Comment by willypuzzle** [comment] 2024-12-15 19:15
could I work on this? How does it work?

**Comment by jdm** [comment] 2024-12-15 19:19
Since we now forbid any new clippy warnings on CI, I think this issue has already been completed.

**Closed by jdm** 2024-12-15 19:19 UTC
Labels: E-less-complex, B-newcomer
