### ISSUE TITLE
Interesting License Agreement... 🤭

### ISSUE THREAD

**Issue by aetinx** [servo/servo#28907] opened 2022-07-22 20:00 UTC
This is really funny, but I'm not sure if this was planned...

<img width="254" alt="image" src="https://user-images.githubusercontent.com/65425469/180518112-35e38dc9-ec78-4213-aa2f-7b77c285d5b3.png">

**Comment by ejaz4** [comment] 2022-07-26 23:12
That's a placeholder for later.

**Comment by atouchet** [comment] 2022-10-10 22:34
Dupe of #21720.

**Closed by atouchet** 2022-10-10 22:34 UTC
