### ISSUE TITLE
Crash when running Servo

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#13209] opened 2016-09-08 21:30 UTC
Seburo on IRC just tried to run Servo, but encountered this crash:

```
execve("./runservo.sh", ["./runservo.sh"], [/* 60 vars */]) = 0
brk(NULL)                               = 0x130a000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2ade4f000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=96851, ...}) = 0
mmap(NULL, 96851, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fa2ade37000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa2ad863000
mprotect(0x7fa2ada23000, 2093056, PROT_NONE) = 0
mmap(0x7fa2adc22000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7fa2adc22000
mmap(0x7fa2adc28000, 14848, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fa2adc28000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2ade36000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2ade35000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2ade34000
arch_prctl(ARCH_SET_FS, 0x7fa2ade35700) = 0
mprotect(0x7fa2adc22000, 16384, PROT_READ) = 0
mprotect(0x606000, 4096, PROT_READ)     = 0
mprotect(0x7fa2ade51000, 4096, PROT_READ) = 0
munmap(0x7fa2ade37000, 96851)           = 0
brk(NULL)                               = 0x130a000
brk(0x132b000)                          = 0x132b000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=10219008, ...}) = 0
mmap(NULL, 10219008, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fa2acea4000
close(3)                                = 0
execve("/usr/local/sbin/sh", ["sh", "./runservo.sh"], [/* 60 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/local/bin/sh", ["sh", "./runservo.sh"], [/* 60 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/sbin/sh", ["sh", "./runservo.sh"], [/* 60 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/bin/sh", ["sh", "./runservo.sh"], [/* 60 vars */]) = -1 ENOENT (No such file or directory)
execve("/sbin/sh", ["sh", "./runservo.sh"], [/* 60 vars */]) = -1 ENOENT (No such file or directory)
execve("/bin/sh", ["sh", "./runservo.sh"], [/* 60 vars */]) = 0
brk(NULL)                               = 0x56071128d000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f38d8570000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=96851, ...}) = 0
mmap(NULL, 96851, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f38d8558000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f38d7f84000
mprotect(0x7f38d8144000, 2093056, PROT_NONE) = 0
mmap(0x7f38d8343000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7f38d8343000
mmap(0x7f38d8349000, 14848, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f38d8349000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f38d8557000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f38d8556000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f38d8555000
arch_prctl(ARCH_SET_FS, 0x7f38d8556700) = 0
mprotect(0x7f38d8343000, 16384, PROT_READ) = 0
mprotect(0x560711092000, 8192, PROT_READ) = 0
mprotect(0x7f38d8572000, 4096, PROT_READ) = 0
munmap(0x7f38d8558000, 96851)           = 0
getuid()                                = 1000
getgid()                                = 1000
getpid()                                = 6992
rt_sigaction(SIGCHLD, {0x560710e86540, ~[RTMIN RT_1], SA_RESTORER, 0x7f38d7fb94a0}, NULL, 8) = 0
geteuid()                               = 1000
brk(NULL)                               = 0x56071128d000
brk(0x5607112ae000)                     = 0x5607112ae000
getppid()                               = 6990
stat("/home/paul/servo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat(".", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("./runservo.sh", O_RDONLY)         = 3
fcntl(3, F_DUPFD, 10)                   = 10
close(3)                                = 0
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
geteuid()                               = 1000
getegid()                               = 1000
rt_sigaction(SIGINT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGINT, {0x560710e86540, ~[RTMIN RT_1], SA_RESTORER, 0x7f38d7fb94a0}, NULL, 8) = 0
rt_sigaction(SIGQUIT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGQUIT, {SIG_DFL, ~[RTMIN RT_1], SA_RESTORER, 0x7f38d7fb94a0}, NULL, 8) = 0
rt_sigaction(SIGTERM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTERM, {SIG_DFL, ~[RTMIN RT_1], SA_RESTORER, 0x7f38d7fb94a0}, NULL, 8) = 0
read(10, "#!/usr/bin/env sh\n./servo -w -b "..., 8192) = 192
read(10, "", 8192)                      = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f38d85569d0) = 6993
wait4(-1, Received Tick when progress was Idle: https://github.com/servo/servo/issues/10322
Received Tick when progress was Idle: https://github.com/servo/servo/issues/10322
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }"
stack backtrace:
   0:     0x55eb0bc8ec6d - backtrace::backtrace::trace::h0e60ef08c7c34e9f
   1:     0x55eb0bc8f2f2 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
   2:     0x55eb0b9bd3c4 - servo::install_crash_handler::handler::hcbccd0415fed145a
   3:     0x55eb0cad0993 - AsmJSFaultHandler
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   4:     0x7ff1e4ead3cf - <unknown>
   5:     0x55eb0c710b03 - _ZNK13JSCompartment28unsafeUnbarrieredMaybeGlobalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartmentinlines.h:34
                         - _ZNK8JSObject6globalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsobjinlines.h:427
                         - _ZN2js34GetGlobalForObjectCrossCompartmentEP8JSObject
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsfriendapi.cpp:357
   6:     0x55eb0c09686a - script::dom::bindings::callback::CallSetup::new::hd9ad248e1c5f4649
   7:     0x55eb0c38b9b5 - script::dom::window::Window::handle_fire_timer::ha7999f02b0501a4b
   8:     0x55eb0c41854a - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h8779b79c040017c7
   9:     0x55eb0c3c77a4 - script::script_thread::ScriptThread::handle_msgs::h218f3f114ad144d6
  10:     0x55eb0bea6db7 - std::panicking::try::do_call::h61db1234041e07c9
  11:     0x55eb0d38e976 - __rust_maybe_catch_panic
  12:     0x55eb0bfdce64 - _<F as alloc..boxed..FnBox<A>>::call_box::h61c39ac95534a7f9
  13:     0x55eb0d384d40 - std::sys::thread::Thread::new::thread_start::h5b631f48cd23f128
  14:     0x7ff1e4ea36f9 - start_thread
  15:     0x7ff1e49c3b5c - clone
  16:                0x0 - <unknown>
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }"
stack backtrace:
   0:     0x55eb0bc8ec6d - backtrace::backtrace::trace::h0e60ef08c7c34e9f
   1:     0x55eb0bc8f2f2 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
   2:     0x55eb0b9bd3c4 - servo::install_crash_handler::handler::hcbccd0415fed145a
   3:     0x7ff1e48f249f - <unknown>
   4:     0x55eb0b9bd44f - servo::install_crash_handler::handler::hcbccd0415fed145a
   5:     0x55eb0cad0993 - AsmJSFaultHandler
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   6:     0x7ff1e4ead3cf - <unknown>
   7:     0x55eb0c710b03 - _ZNK13JSCompartment28unsafeUnbarrieredMaybeGlobalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartmentinlines.h:34
                         - _ZNK8JSObject6globalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsobjinlines.h:427
                         - _ZN2js34GetGlobalForObjectCrossCompartmentEP8JSObject
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsfriendapi.cpp:357
   8:     0x55eb0c09686a - script::dom::bindings::callback::CallSetup::new::hd9ad248e1c5f4649
   9:     0x55eb0c38b9b5 - script::dom::window::Window::handle_fire_timer::ha7999f02b0501a4b
  10:     0x55eb0c41854a - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h8779b79c040017c7
  11:     0x55eb0c3c77a4 - script::script_thread::ScriptThread::handle_msgs::h218f3f114ad144d6
  12:     0x55eb0bea6db7 - std::panicking::try::do_call::h61db1234041e07c9
  13:     0x55eb0d38e976 - __rust_maybe_catch_panic
  14:     0x55eb0bfdce64 - _<F as alloc..boxed..FnBox<A>>::call_box::h61c39ac95534a7f9
  15:     0x55eb0d384d40 - std::sys::thread::Thread::new::thread_start::h5b631f48cd23f128
  16:     0x7ff1e4ea36f9 - start_thread
  17:     0x7ff1e49c3b5c - clone
  18:                0x0 - <unknown>
[{WIFSIGNALED(s) && WTERMSIG(s) == SIGILL && WCOREDUMP(s)}], 0, NULL) = 6993
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=6993, si_uid=1000, si_status=SIGILL, si_utime=5241, si_stime=494} ---
rt_sigreturn({mask=[]})                 = 6993
write(2, "Illegal instruction (core dumped"..., 34Illegal instruction (core dumped)
) = 34
exit_group(132)                         = ?
+++ exited with 132 +++
```

**Comment by frewsxcv** [comment] 2016-09-08 21:32
This was their first time running Servo.

**Comment by frewsxcv** [comment] 2016-09-08 21:33
From IRC:

> If it helps, I am running Ubuntu 16.04.  The only change I have made is uninstalling Ubuntu Fx to replace it with a Mozilla build of Nightly.

**Comment by jdm** [comment] 2016-09-08 23:22
A crash under `CallSetup::new` via `GetGlobalForObjectCrossCompartment` is super weird. Maybe we're missing a compartment somewhere?

**Comment by jdm** [comment] 2017-01-06 22:19
Looks like the same crash as #14183.

**Comment by nox** [comment] 2017-10-03 10:58
Closing as duplicate of #12072.

**Closed by nox** 2017-10-03 10:58 UTC
Labels: A-content/bindings, I-crash
