### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("Send is too large for port") }) }

### ISSUE THREAD

**Issue by ksnyde** [servo/servo#14309] opened 2016-11-21 12:53 UTC
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("Send is too large for port") }) }
### Servo Version:
Servo 0.0.1-dd611ef
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(7), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(7), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(7), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(7), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(8), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(8), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(8), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(8), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(8), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(8), index: PipelineIndex(1) }>: stop_parsing not implemented, full spe
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-11-21 14:29
Duplicate of #13054, and there's more information there. Thanks for reporting it!

**Closed by jdm** 2016-11-21 14:29 UTC
Labels: I-panic
