### ISSUE TITLE
Possible intermittent timeout: 2dcontext/drawing-images-to-the-canvas/drawimage_canvas_12.html

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#8292] opened 2015-11-02 08:30 UTC
https://github.com/servo/servo/pull/7400#issuecomment-152944992

```
Summary
=======

Ran 213586 tests (3577 parents, 210009 subtests)
Expected results: 212885
Unexpected results: 1 (TIMEOUT: 1)
Skipped: 700

Unexpected Results
==================

/2dcontext/drawing-images-to-the-canvas/drawimage_canvas_12.html
----------------------------------------------------------------
TIMEOUT [Parent]
```

**Comment by jdm** [comment] 2015-11-02 13:21
Duplicate of #7787.

**Closed by jdm** 2015-11-02 13:21 UTC
Labels: I-intermittent

**Comment by SimonSapin** [comment] 2015-11-02 18:05
Ah, my search query was too specific. Thanks!
