### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "SendError(..)"

### ISSUE THREAD

**Issue by leuction** [servo/servo#15286] opened 2017-01-28 22:37 UTC
called `Result::unwrap()` on an `Err` value: "SendError(..)"
### Servo Version:
Servo 0.0.1-d4ee8a3
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(3), index: PipelineIndex(41) }>: stop_parsing not implemented, full speed ahead!
WARNING: <Constellation>: Sending layout exit message failed (Bogus destination port.).
WARNING: <Constellation>: creating replacement pipeline for about:failure
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(3), index: PipelineIndex(41) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(3), index: PipelineIndex(41) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(3), index: PipelineIndex(41) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(3), index: PipelineIndex(41) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(3), index: PipelineIndex(41) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(3), index: PipelineIndex(41) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Panic hook called.
WARN
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2017-01-28 23:16
Do you know what page you were looking at?

**Comment by jdm** [comment] 2017-03-16 08:25
Closing due to lack of information to reproduce the failure.

**Closed by jdm** 2017-03-16 08:25 UTC
Labels: I-panic
