### ISSUE TITLE
Misleading names of `start_sending_sniffed` and friends

### ISSUE THREAD

**Issue by izgzhen** [servo/servo#12462] opened 2016-07-15 14:38 UTC
In `net/resource_thread.rs`, `start_sending_sniffed` and similarly named functions have names looking misleading to me: `start_sending_sniffed` only takes a `partial_body` and "sniffs", but not actually sending the payload.

Also, `_opt` suffix of `start_sending_sniffed_opt` and `start_sending_opt` look weird to me. What does `_opt` mean here? `raw_content_type_options`?

**Comment by jdm** [comment] 2016-07-15 14:45
_opt  was intended to reflect the fact that it returns an error value if it couldn't send, iirc.

**Comment by izgzhen** [comment] 2016-07-15 14:48
as @aneeshusa mentioned in irc, non-`_opt` version uses `unwrap` and looks not used anywhere. So maybe it is good to drop.

**Comment by jdm** [comment] 2016-07-15 15:09
Also since start_sending_sniffed_opt calls start_sending_opt, it definitely does send the payload.

**Comment by izgzhen** [comment] 2016-07-15 15:13
but
```
fn start_sending_opt(start_chan: LoadConsumer, metadata: Metadata,
                     network_error: Option<NetworkError>) -> Result<ProgressSender, ()> {
```

doesn't look like a byte-sending something to me :$

**Comment by jdm** [comment] 2016-07-15 15:27
Oh right, start_sending_opt is the start of the sending process which only sends the header, not the actual response content.

**Comment by izgzhen** [comment] 2016-07-16 00:29
@jdm I added a E-easy tag, thinking it might be a good starter task

**Comment by jdm** [comment] 2016-07-16 00:43
I'm removing it until we have a good idea for a replacement name :)

**Comment by nox** [comment] 2017-10-04 11:03
I can't find any of these function names anymore in the tree. Closing.

**Closed by nox** 2017-10-04 11:03 UTC
Labels: I-cleanup
