### ISSUE TITLE
./mach run ./tests/html/about-mozilla.html does not work as expected after cloning (and building)

### ISSUE THREAD

**Issue by awlnx** [servo/servo#4883] opened 2015-02-10 03:36 UTC
Error running mach:

    ['run', './tests/html/about-mozilla.html']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 2] No such file or directory

  File "/home/alec/dev/servo/python/servo/post_build_commands.py", line 78, in run
    subprocess.check_call(args, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception

**Comment by awlnx** [comment] 2015-02-10 04:31
I should probably mention that I did actually check that the file exists. Also This occurs for every file

**Comment by awlnx** [comment] 2015-02-10 04:56
subproccess(args, env=env)
subproccess calls ./components/servo/target/servo. This is missing in my directory.

**Comment by jdm** [comment] 2015-02-10 11:26
This looks like a duplicate of #4874.

**Comment by jdm** [comment] 2015-02-10 11:26
Oh wait, you say you built but the binary's missing? What's up with that?

**Comment by awlnx** [comment] 2015-02-10 19:11
I'm  not sure. A fresh clone and build fixed the issue. It might be worth noting that mach did not output a nonzero exit code or an error message on the failed build.

**Comment by jdm** [comment] 2015-02-10 19:16
Ok. We can reopen if you come across the problem again.

**Closed by jdm** 2015-02-10 19:16 UTC
