### ISSUE TITLE
TODO: Revive Issue #29713 to improve the organization and documentation of internal APIs

### ISSUE THREAD

**Issue by brutusyhy** [servo/servo#34027] opened 2024-10-26 14:01 UTC
**Describe the new feature:**
I am new to servo's codebase, and I would like to start contributing to it with things like code refactoring, which will hopefully help me develop a better grasp of how things work. I have come across Issue #29713 under the Code Health project, and I think implementing this proposal would significantly smooth the learning curves for newcomers to understand and contribute to the code by providing a more predictable API pattern and documentation location. I would like to do what I can if people think this is a good idea, although I would really appreciate some guidance on how to start with it.

**Comment by mrobinson** [comment] 2024-10-28 08:39
This seems like a duplicate of #29713? I don't think we need more than one issue open for the same topic.

I would say the first step toward working on this issue is to take stock of all of the crates in `components/shared` and to see what crates they depend on and what crates depend on them. Is there a pattern there that can be documented somehow. For instance, do all `component_shared` crates expose an API for other crates to interact with `component`? How close are we to that point?

I know there is one exception, which is that `compositor_shared` are the parts of the compositor API that depend on the `constellation` and `script` traits as well whereas `webrender_shared` are the parts of the compositor API that don't depend on the constellation. Maybe in that case we either try to remove the `script`/`constellation` dependencies from `compositor_shared` or turn these crates into something like `compositor_api` and `compositor_constellation_api`.

**Closed by mrobinson** 2024-10-28 08:39 UTC
Labels: B-feature-tracking, C-untriaged
