### ISSUE TITLE
assertion failed: self.suspended_since.get().is_some()

### ISSUE THREAD

**Issue by IgorNikolov** [servo/servo#13893] opened 2016-10-22 15:51 UTC
assertion failed: self.suspended_since.get().is_some()
### Servo Version:
Servo 0.0.1-9cbac40
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) } closed.
WARNING: <ScriptThread PipelineId { namespace_
...
```
This report was generated by the browser.html issue reporter.

**Comment by emilio** [comment] 2016-10-29 20:43
Dupe of https://github.com/servo/servo/issues/13716, thanks for reporting!

**Closed by emilio** 2016-10-29 20:43 UTC
