### ISSUE TITLE
Children of nodes with 'pointer-events: none' set don't receive event if they have 'pointer-events: all' set

### ISSUE THREAD

**Issue by Gozala** [servo/servo#11003] opened 2016-05-04 16:07 UTC
Here is a code to reproduce it:

```
servo "data:text/html,<div style='pointer-events: none'><button style='pointer-events: all' onmousedown='document.body.style.background=\'red\'' onmouseup='document.body.style.background=null'>Click me</button></div>"
```

Clicking a button should make window background go red, but it does not.

**Comment by paulrouget** [comment] 2016-05-09 19:07
iirc, `all` is a a SVG-related value. You want to use `auto`.

**Comment by Gozala** [comment] 2016-05-09 19:16
> iirc, all is a a SVG-related value. You want to use auto.

It seems that `pointerEvents: auto` does work. This bug is still valid though as `pointeEvens: all`  does work in all other engines.

**Comment by nox** [comment] 2017-10-02 17:40
This is still an issue.

**Comment by jdm** [comment] 2024-12-11 03:04
Duplicate of #7375.

**Closed by jdm** 2024-12-11 03:04 UTC
Labels: A-content/dom, C-has-manual-testcase, A-input
