### ISSUE TITLE
Print paths for errors occurring in the servo crate

### ISSUE THREAD

**Issue by nox** [servo/servo#9895] opened 2016-03-07 14:20 UTC
```
± ./mach build
   Compiling servo v0.0.1 (file:///Users/nox/src/servo/components/servo)
lib.rs:89:9: 89:15 error: unresolved import `export::gleam::gl`. Maybe a missing `extern crate export`? [E0432]
lib.rs:89 pub use export::gleam::gl;
```

Our `mach` tool should print `components/servo/lib.rs` instead of `lib.rs`.

**Comment by tigercosmos** [comment] 2017-10-19 17:14
Where is the related scripts to handle this? I search "Compiling", but not found in `.py`. Maybe I use wrong keyword?

**Comment by jdm** [comment] 2017-10-19 17:34
https://github.com/servo/servo/blob/fe16c1d5c3c9084da0ccb85af599d6ec0f8ab20b/python/servo/build_commands.py#L320-L323 is the code that invokes the cargo build. I'm not sure how we would accomplish this besides post-processing the output from the build, checking for lines that start with `lib.rs`, and rewriting them with the relative path instead.

**Comment by tigercosmos** [comment] 2017-10-19 18:02
Seems cargo has supported the feature. 
It will show the full path. @jdm shall we close this?
```
tigercosmos@ubuntu:~/servo$ ./mach build
   Compiling gfx v0.0.1 (file:///home/tigercosmos/servo/components/gfx)
error[E0433]: failed to resolve. Use of undeclared type or module `ptr`
  --> /home/tigercosmos/servo/components/gfx/platform/freetype/font_list.rs:29:44
   |
29 |             let mut family: *mut FcChar8 = ptr::null_mut();
   |                                            ^^^ Use of undeclared type or module `ptr`
```

**Comment by jdm** [comment] 2017-10-19 18:33
@tigercosmos This is specifically referring to compilation errors from components/servo/lib.rs.

**Comment by tigercosmos** [comment] 2017-10-20 13:52
I don't know how to reproduce.
```
tigercosmos@ubuntu:~/servo$ ./mach build -d
   Compiling libservo v0.0.1 (file:///home/tigercosmos/servo/components/servo)
error[E0433]: failed to resolve. Use of undeclared type or module `mem`
   --> /home/tigercosmos/servo/components/servo/lib.rs:517:44
    |
517 |                         mem_profiler_chan: mem::ProfilerChan,
    |                                            ^^^ Use of undeclared type or module `mem`

error: aborting due to previous error

error: Could not compile `libservo`.

To learn more, run the command again with --verbose.
Build FAILED in 0:00:04
```

**Comment by nox** [comment] 2017-10-20 13:59
Insert a syntax error in `ports/geckolib/lib.rs` and run `./mach build-geckolib`

**Comment by tigercosmos** [comment] 2017-10-20 14:20
I got the result. So, does it occur on every `**/lib.rs`?
```
error: expected one of `!` or `::`, found `#`
  --> lib.rs:24:1
   |
22 | ee
   |   - expected one of `!` or `::` here
23 | // FIXME(bholley): This should probably go away once we harmonize the allocators.
24 | #[no_mangle]
   | ^ unexpected token
```

**Comment by jdm** [comment] 2017-10-20 14:53
No, only the top-level crate, I guess. Probably ports/glutin would show a similar result for a regular build?

**Comment by tigercosmos** [comment] 2017-10-22 09:29
No command `./mach build-glutin` and seems `glutin` will be unforked?

**Comment by jdm** [comment] 2017-10-22 13:51
./mach build uses ports/glutin.

**Comment by tigercosmos** [comment] 2017-10-22 18:58
Seems relate to rust-lang/cargo#694

If it is not a dependency, it will only show the path of where `cargo build`. Not a absolute path.

We set `ports/geckolib` as the root in the following code
https://github.com/servo/servo/blob/a296e386af21b50409e78dd3a34ea6a5fd36d4bf/python/servo/build_commands.py#L456-L457

I guess that's why it will only show `lib.rs`, because the root is not in `servo`

**Closed** 2017-11-03 15:08 UTC
Labels: A-mach, I-papercut, L-python
