### ISSUE TITLE
Github closed status icon bleeds

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#7639] opened 2015-09-15 18:25 UTC
When opening https://github.com/servo/servo/issues/1 (on Linux):

![](https://cloud.githubusercontent.com/assets/1617736/9885683/260f9c14-5c04-11e5-9996-ce287421ac9d.png)

The element is a CSS circle via `border-radius` (the icon is from https://octicons.github.com/ and is basically a `:before` element containing U+F084 with a custom font)

**Comment by rvolgers** [comment] 2015-09-16 23:07
I'm investigating this a bit, even though it might be overambitious.

There is a general problem with bleed when two [anti-aliased shapes overlap](https://www.imperialviolet.org/2009/09/02/anti-aliased-clipping.html), but this looks a bit more severe to me.

It might be a result of the background being rendered using a clipping path generated by the simple `push_rounded_rect_clip` while the border path is generated by `draw_border` and its legion of helper functions. I don't immediately see any reason why these would generate different paths though.

**Comment by bjwbell** [comment] 2015-09-17 01:20
@rvolgers it could be related to https://github.com/servo/servo/pull/7577.

On Wed, Sep 16, 2015 at 4:07 PM, rvolgers <notifications@github.com> wrote:

> I'm investigating this a bit, even though it might be overambitious.
>
> There is a general problem with bleed when two anti-aliased shapes overlap
> <https://www.imperialviolet.org/2009/09/02/anti-aliased-clipping.html>,
> but this looks a bit more severe to me.
>
> It might be a result of the background being rendered using a clipping
> path generated by the simple push_rounded_rect_clip while the border path
> is generated by draw_border and its legion of helper functions. I don't
> immediately see any reason why these would generate different paths though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/servo/servo/issues/7639#issuecomment-140920917>.
>



-- 
-- Regards
Bryan

**Comment by rvolgers** [comment] 2015-09-17 19:30
The problem is that the background is rendered using a clip path that has anti-aliasing, while the border is rendered using a path fill with anti-aliasing disabled. 

I'm not really sure why anti-aliasing is disabled (it looks ugly) but I'm sure there's good reason, since it's done explicitly for just about every draw call. 

So I'm assuming anti-aliasing should remain disabled, and the clipping should also be done with anti-aliasing disabled. This can be set using an optional boolean argument to Skia's `Canvas::clipPath`, but unfortunately libazure hardcodes that argument to `true` in `DrawTargetSkia::PushClip`.

I could add the boolean argument to the corresponding methods in `libazure` and the `azure` crate, and then pass `false` as the last argument in the various `push_clip` calls in `gfx::PaintContext`, but I have no idea how to deal with backwards compat concerns (and I'd have to see where I submit patches to libazure).

**Comment by bjwbell** [comment] 2015-09-17 22:13
@rvolgers What does Gecko do, i.e. AA for background & border or no-AA for both?
Gecko seems to usually antialias but not always ([nsCSSRenderingBorders.cpp#1622](http://mxr.mozilla.org/mozilla-central/source/layout/base/nsCSSRenderingBorders.cpp#1622)).

I'd avoid altering libazure, getting a patch accepted for all the backends and merged can't be trivial. 

I'd do the following:
1. Try and enable AA for borders. There's probably scenarios where AA isn't possible (maybe acid2). 
2. If enabling AA for borders isn't feasible then change the background rendering to use a filled rounded rect and put a TODO note in the background rendering code describing the issues with AA.

Gecko:
* DrawBorder - [nsCSSRenderingBorders.cpp#1521](http://mxr.mozilla.org/mozilla-central/source/layout/base/nsCSSRenderingBorders.cpp#1521)
* [SnapLineToDevicePixelsForStroking](http://mxr.mozilla.org/mozilla-central/ident?i=SnapLineToDevicePixelsForStroking) seems relevant.

**Comment by rvolgers** [comment] 2015-09-18 09:12
Gecko anti-aliases everything. So does webkit. I'm not sure to what degree they perform pixel snapping of positions, sizes and radii before rendering (servo's `PaintContext` does it for just about everything at the moment). 

Enabling anti-aliasing everywhere breaks 13 reftests, I haven't looked at the details. It's worth noting that servo already has switches to disable anti-aliasing for reftests in some cases (text rendering, and one other thing that I can't remember), so I'm not sure how big of a deal this is. 

Now about possible solutions to the problem that remains with full anti-aliasing.

Gecko actually only draws the background *inside* the border if the border is opaque as an optimization (not sure why that would be faster? anyway...), so you don't get a bleed outside the border. You *do* however get a seam inside the border. They fix this by drawing the background out to 1px inside the border instead. See `NS_STYLE_BG_CLIP_MOZ_ALMOST_PADDING` in `layout/base/nsCSSRendering.cpp`. At this point it seems they covered enough of the situations that people actually used that people stopped filing bugs about it. Surprisingly enough I think this seems like the sanest thing to do. 

Relevant links:
https://bugzilla.mozilla.org/show_bug.cgi?id=466572
https://bugzilla.mozilla.org/show_bug.cgi?id=704399
... and many duplicates and semi-duplicates. 

Webkit appears to have attempted to solve this by clever painting and compositing ordering. You essentially have to first paint everything (all backgrounds and borders) without clipping and then clear out the transparent parts in one final step at the end. Downsides are that this requires a temporary bitmap, you have to render the border using clipping as well (so it doesn't work for dashed borders), and it requires munging together background drawing with border drawing. 

Relevant links:
http://neugierig.org/software/chromium/notes/2010/07/clipping.html
https://bugs.webkit.org/show_bug.cgi?id=28820

**Comment by bjwbell** [comment] 2015-09-18 17:35
Fantastic writeup, thanks.
And I thought we were almost done with implementing the border code...

It's completely up to you how much you want to implement to close this
issue.
Is it alright if I add your writeup to the wiki? We'll be referring to it
for a long time.

For the failing reftests we'll have to look at each one and see if it's a
real issue or not.
For at least one the reftest will need to be changed
(tests/ref/borders_b.html).



On Fri, Sep 18, 2015 at 2:12 AM, rvolgers <notifications@github.com> wrote:

> Gecko anti-aliases everything. So does webkit. I'm not sure to what degree
> they perform pixel snapping of positions, sizes and radii before rendering
> (servo's PaintContext does it for just about everything at the moment).
>
> Enabling anti-aliasing everywhere breaks 13 reftests, I haven't looked at
> the details. It's worth noting that servo already has switches to disable
> anti-aliasing for reftests in some cases (text rendering, and one other
> thing that I can't remember), so I'm not sure how big of a deal this is.
>
> Now about possible solutions to the problem that remains with full
> anti-aliasing.
>
> Gecko actually only draws the background *inside* the border if the
> border is opaque as an optimization (not sure why that would be faster?
> anyway...), so you don't get a bleed outside the border. You *do* however
> get a seam inside the border. They fix this by drawing the background out
> to 1px inside the border instead. See NS_STYLE_BG_CLIP_MOZ_ALMOST_PADDING
> in layout/base/nsCSSRendering.cpp. At this point it seems they covered
> enough of the situations that people actually used that people stopped
> filing bugs about it. Surprisingly enough I think this seems like the
> sanest thing to do.
>
> Relevant links:
> https://bugzilla.mozilla.org/show_bug.cgi?id=466572
> https://bugzilla.mozilla.org/show_bug.cgi?id=704399
> ... and many duplicates and semi-duplicates.
>
> Webkit appears to have attempted to solve this by clever painting and
> compositing ordering. You essentially have to first paint everything (all
> backgrounds and borders) without clipping and then clear out the
> transparent parts in one final step at the end. Downsides are that this
> requires a temporary bitmap, you have to render the border using clipping
> as well (so it doesn't work for dashed borders), and it requires munging
> together background drawing with border drawing.
>
> Relevant links:
> http://neugierig.org/software/chromium/notes/2010/07/clipping.html
> https://bugs.webkit.org/show_bug.cgi?id=28820
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/servo/servo/issues/7639#issuecomment-141389088>.
>



-- 
-- Regards
Bryan

**Comment by rvolgers** [comment] 2015-09-21 22:19
So far I've implemented two things:

1. Enable anti-aliasing for all border drawing. I was going to enable it for all draw operations but I'm not actually convinced that's needed, so I'd rather keep this change minimal. 
2. Fixed the `background-clip: padding-box` implementation for rounded corners (basically switched the order of two code blocks that were the wrong way around).

And I'm working on:

3. Change `display_list_builder.rs` to apply a small tweak to the border coordinates when rounded corners are present and we can do this tweak without causing other rendering artifacts. This should fix the problem for many cases. 

I'm planning to submit these changes in a single PR as a decently self-contained bandaid for this bug. Is that OK or should some of this stuff be split out?

Longer term there is going to have to be some refactoring and it will probably end up being closer to the Chrome approach. Mostly this is motivated by the changes that would be needed to implement correct clipping of content when combining `overflow: hidden` with rounded corners; according to the spec content should clip to the rounded corners, that is currently not done. I have some ideas for this but I'm not sure when/if I will have time to do that work. 

> Is it alright if I add your writeup to the wiki? We'll be referring to it for a long time.

Of course.

**Comment by bjwbell** [comment] 2015-09-21 22:42
One PR is fine, split into 3 commits. Similar to how https://github.com/servo/servo/pull/7577/commits is split into two commits (technically I should have flipped the order to prevent the build failing).  

I'm looking forward to seeing your PR. 

You might want to add an option/flag in `servo::util::opts::Opt` to enable/disable anti-aliasing.

**Comment by rvolgers** [comment] 2015-09-23 21:09
After reviewing the reftests it turns out enabling anti-aliasing causes a bunch of new bleed artifacts. In particular, `./tests/wpt/css-tests/css21_dev/html4/border-seams-001.htm` now fails with exactly the kind of ugly seam I'd been trying to avoid. 

I'm probably going to submit a PR for the unrelated bugfix and fix some more semi-related issues (such as content not clipping to the rounded area when `overflow: hidden` is set) while I familiarize myself some more with this code, and just leave this issue on the backburner until I come up with something that could work. If someone else wants to work on it I'd be happy to chat and/or review. 

One thing people who are interested in refactoring this code should probably read is the [CSS Backgrounds and Borders Module Level 3](https://drafts.csswg.org/css-backgrounds-3/) draft. It's not final yet, but it shows where things are going and in addition has some nice clarifications about border-related things from previous specs.

**Comment by bjwbell** [comment] 2015-09-24 15:46
Sorry to hear, it's not an easy problem. I'm still working on fixing https://github.com/servo/servo/issues/7589.

**Comment by nox** [comment] 2017-09-30 09:52
This doesn't bleed anymore.

**Closed by nox** 2017-09-30 09:52 UTC
Labels: A-gfx/rendering
