### ISSUE TITLE
Servo on Linux doesn't exit after a while

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#5384] opened 2015-03-26 14:20 UTC
Happens sometimes when playing with servo-shell.

STR:
- Open servo-shell (confirmed in release mode)
- Open a couple of sites and click around (I did mobile Facebook and then Github)
- Try to close it from the launcher (Unity?) or the close button on the window, it doesn't work.

ESC/Ctrl-C on the terminal both work

cc @glennw

**Comment by tdaede** [comment] 2015-03-27 20:30
This also happens to me, but Servo also becomes totally unresponsive to any other events as well, such as scrolling, clicking, or resizing.

**Comment by zmike** [comment] 2015-05-16 14:26
Duplicate of #5789 most likely

**Comment by dralley** [comment] 2020-03-24 19:10
Can it still be reproduced?  The other bug mentioned as a possible duplicate should have been closed 5 years ago, as it was based on a Mesa bug merged way back when.

**Comment by jdm** [comment] 2020-03-24 19:27
Haven't seen any reports of this, closing optimistically.

**Closed by jdm** 2020-03-24 19:27 UTC
Labels: A-embedding, P-linux
