### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: RecvError

### ISSUE THREAD

**Issue by fyee** [servo/servo#13048] opened 2016-08-26 06:33 UTC
called `Result::unwrap()` on an `Err` value: RecvError
### Servo Version:
Servo 0.0.1-9b4713f
### Backtrace:
```

WARNING: <Constellation>: Finding mozbrowser ancestor for pipeline (1,4) after closure.
WARNING: <Constellation>: Closing pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(4) } twice.
WARNING: <Constellation>: removing pending frame change for failed pipeline
WARNING: <Constellation>: creating replacement pipeline for about:failure
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Panic hook called.
WARNING: failed to deliver network data: ()
WARNING: failed to deliver network data: ()
WARNING: failed to deliver network data: ()
WARNING: failed to deliver network data: ()
WARNING: failed to deliver network data: ()
WARNING: failed to deliver network data: ()
WARNING: failed to deliver network data: ()
WARNING: failed to deliver network data: ()
WARNING: failed to deliver network data: ()
ERROR: called `Result::unwrap()` on an `Err` value: RecvError

stack backtrace:
   0:        0x10abb4aae - backtrace::backtrace::trace::h22a738598d75d447
   1:        0x10abb4dbc - backtrace::capture::Backtrace::new::h1a277804460ccff5
   2:        0x10a58d8d5 - constellation::constellation::log_entry::h8e012ed7abc376d9
   3:        0x10a58c4c2 - _<constellation..constellation..FromCompositorLogger as log..Log>::log::hacb1d3564836d339
   4:        0x10ac31ab1 - log::__log::h34a513f1b21e1173
   5:        0x109309c16 - servo::main::_{{closure}}::h5d02d94265372533
   6:        0x10ac4a793 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   7:        0x10ac4a664 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   8:        0x10ac4a572 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   9:        0x10ac4a4d7 - rust_begin_unwind
  10:        0x10ac78730 - core::panicking::panic_fmt::hc5789f4e80194729
  11:        0x1098f0746 - core::result::unwrap_failed::h3e79b7b152b9c363
  12:        0x109dbbe3b - script::script_thread::shut_down_layout::h6041cfee7c50088a
  13:        0x109de320f - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::hfcee7c11be5a904a
  14:        0x109d88fff - script::script_thread::ScriptThread::handle_msgs::h30d23479eada487c
  15:        0x109792507 - std::panicking::try::do_call::h25457b92b20282f8
  16:        0x10ac4b63a - __rust_maybe_catch_panic
  17:        0x1099326c6 - _<F as alloc..boxed..FnBox<A>>::call_box::hce59fcce8d5a71d5
  18:        0x10ac49595 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  19:     0x7fff9822f99c - _pthread_body
  20:     0x7fff9822f919 - _pthread_start
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-08-26 14:52
Closing as a duplicate of #13046, which shows the same problem.

**Comment by jdm** [comment] 2016-08-26 14:53
Thanks for reporting it!

**Closed by jdm** 2016-08-26 14:52 UTC
Labels: A-content/script, I-panic
