### ISSUE TITLE
border-image is too liberal in what it accepts

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#15770] opened 2017-02-28 20:02 UTC
After I added support for relative URIs to stylo, we got some test failures:

```
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property - got "url(\"border.png\") 27 27 27 27 / 1 / 0 stretch", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property when testing subproperty 'border-image-source' - got "url(\"border.png\")", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property when testing subproperty 'border-image-slice' - got "27 27 27 27", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property when testing subproperty 'border-image-width' - got "1", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property when testing subproperty 'border-image-outset' - got "0", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property when testing subproperty 'border-image-repeat' - got "stretch", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property - got "url(\"border.png\") 27 27 27 27 / 1 / 0 stretch", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property when testing subproperty 'border-image-source' - got "url(\"border.png\")", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property when testing subproperty 'border-image-slice' - got "27 27 27 27", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property when testing subproperty 'border-image-width' - got "1", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property when testing subproperty 'border-image-outset' - got "0", expected ""
invalid value 'url('border.png') 27 27 27 27 /' not accepted for 'border-image' property when testing subproperty 'border-image-repeat' - got "stretch", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property - got "url(\"border.png\") 1 / 1 / 0 stretch", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property when testing subproperty 'border-image-source' - got "url(\"border.png\")", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property when testing subproperty 'border-image-slice' - got "1", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property when testing subproperty 'border-image-width' - got "1", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property when testing subproperty 'border-image-outset' - got "0", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property when testing subproperty 'border-image-repeat' - got "stretch", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property - got "url(\"border.png\") 1 / 1 / 0 stretch", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property when testing subproperty 'border-image-source' - got "url(\"border.png\")", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property when testing subproperty 'border-image-slice' - got "1", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property when testing subproperty 'border-image-width' - got "1", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property when testing subproperty 'border-image-outset' - got "0", expected ""
invalid value 'url('border.png') 1 /' not accepted for 'border-image' property when testing subproperty 'border-image-repeat' - got "stretch", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property - got "url(\"border.png\") 1 / 1 / 0 stretch", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property when testing subproperty 'border-image-source' - got "url(\"border.png\")", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property when testing subproperty 'border-image-slice' - got "1", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property when testing subproperty 'border-image-width' - got "1", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property when testing subproperty 'border-image-outset' - got "0", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property when testing subproperty 'border-image-repeat' - got "stretch", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property - got "url(\"border.png\") 1 / 1 / 0 stretch", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property when testing subproperty 'border-image-source' - got "url(\"border.png\")", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property when testing subproperty 'border-image-slice' - got "1", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property when testing subproperty 'border-image-width' - got "1", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property when testing subproperty 'border-image-outset' - got "0", expected ""
invalid value '1 / url('border.png')' not accepted for 'border-image' property when testing subproperty 'border-image-repeat' - got "stretch", expected ""
```

Basically, none of these shorthand values should be accepted.

cc @canaltinova

**Comment by canaltinova** [comment] 2017-03-01 15:00
I'm working on this.

**Comment by canaltinova** [comment] 2017-03-01 15:48
Oh, I think we can mark this as an easy issue. The relevant code is [here.](https://dxr.mozilla.org/servo/rev/57ff19ec838bf1bbccd6d0dafe069c3351f5b1e5/components/style/properties/shorthand/border.mako.rs#213-226)

The problem is this `input.try` is always returning `Ok`. We need to check and return `Err(())` if `w` and `o` variables are none before `Ok((w, o))`.

**Comment by canaltinova** [comment] 2017-03-01 16:02
And the reason we need to return `Err(())` here because we need to say to parser that [this](https://dxr.mozilla.org/servo/rev/57ff19ec838bf1bbccd6d0dafe069c3351f5b1e5/components/style/properties/shorthand/border.mako.rs#214) `/` should not parsed.  In that way, for example `url('border.png') 27 27 27 27 /` won't be parsed because `/` will remain unparsed.

**Comment by jdm** [comment] 2017-03-01 19:31
@snehasi Take a look at this issue! @canaltinova and others should be able to answer any questions you might have.

I'm marking this as assigned optimistically, so that it doesn't disappear before @snehasi has a chance to see it.

**Comment by snehasi** [comment] 2017-03-02 06:54
Yes, I'll start working on it.

**Comment by snehasi** [comment] 2017-03-02 07:01
@riya16079

**Closed** 2017-03-14 20:57 UTC
Labels: A-content/css, A-stylo, C-assigned, E-easy, I-wrong
