### ISSUE TITLE
Bug on spinning.html with webrender

### ISSUE THREAD

**Issue by negge** [servo/servo#11759] opened 2016-06-16 13:44 UTC
Using master servo with -w (webrender), the spinning.html drops some of the rectangles.  This can be seen with the commands:

without webrender:
`./mach run -r -- https://people.xiph.org/~negge/spinning.html`
https://people.xiph.org/~negge/servo_spinning_nowr.png

with webrender:
`./mach run -r -w -- https://people.xiph.org/~negge/spinning.html`
https://people.xiph.org/~negge/servo_spinning_wr_bug.png

**Comment by larsbergstrom** [comment] 2016-06-30 00:18
I saw this on some Android devices, too. Seemed to be tied to the border radius, as the problem went away on that device (Samsung Galaxy Tab 2) if I removed it:
https://github.com/larsbergstrom/webrender-demos/blob/use_raf/transparent_rects.html#L82

**Comment by ConnorGBrewster** [comment] 2016-06-30 00:42
I set the rotation to a static `-24deg` and while resizing the window, it looks like the ones on the edge are being clipped prior to the rotation happening. It also looks like some of them get culled away before they are fully out of the view.
![spinning_clip_issue](https://cloud.githubusercontent.com/assets/9086315/16473302/0ed3748c-3e29-11e6-8ffe-e4c8e2268f6d.gif)

**Comment by ConnorGBrewster** [comment] 2016-06-30 00:55
Adding P1 as I assume we want all the linked demos on the newtab page to work properly. Feel free to change it if it shouldn't be P1.

**Comment by jdm** [comment] 2016-06-30 03:12
This doesn't feel like it impacts the demo in a meaningful way, so I'm dropping the "omg terrible user experience must fix" label :)

**Comment by ConnorGBrewster** [comment] 2016-06-30 17:28
Better gif of the original issue:
![spinning_issue](https://cloud.githubusercontent.com/assets/9086315/16497737/bfd6b6a4-3eb5-11e6-985a-92e3ca8defb5.gif)

**Comment by nox** [comment] 2017-10-02 07:26
Closing as duplicate of #11970.

**Closed by nox** 2017-10-02 07:26 UTC
Labels: A-webrender
