### ISSUE TITLE
Tokens not found

### ISSUE THREAD

**Issue by Macmee** [servo/servo#13343] opened 2016-09-21 03:13 UTC
Tokens not found
### URL:
http://reddit6.com
### Servo Version:
Servo 0.0.1-7c0dfd0
### Backtrace:
```

WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }>: FIXME: </script> not fully implemented
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }>: Warning at http://reddit6.com/l.js:994:0: Using //@ to indicate sourceMappingURL pr
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-09-21 11:59
@Macmee Do you have any steps to reproduce this? I pushed some random buttons on reddit6.com but didn't come across anything suspicious.

**Comment by jdm** [comment] 2016-09-21 12:01
That being said, the panic message suggests that this is a duplicate of #12799 and will be fixed by #13311.

**Comment by jdm** [comment] 2016-09-23 14:37
This should be fixed in tomorrow's nightly. Thanks for reporting it!

**Closed by jdm** 2016-09-23 14:37 UTC
Labels: I-panic
