### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by ryanmitchell** [servo/servo#12006] opened 2016-07-01 08:11 UTC
index out of bounds: the len is 0 but the index is 0
### URL:
http://www.bbc.co.uk/news
### Backtrace:
```
frame #0  - 0x000000010ce016ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x000000010ce01651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x000000010b66eca4 - _<F as alloc..boxed..FnBox<A>>::call_box::haeff945be1a63d60
frame #3  - 0x000000010cd75947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010cfe9844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000000010d002786 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x000000010cfeae88 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x000000010d0023df - rust_begin_unwind
frame #8  - 0x000000010d029260 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x000000010d0293e0 - core::panicking::panic_bounds_check::h14f942e6ac026712
frame #10 - 0x000000010c3a4d5f - style::keyframes::KeyframesAnimation::from_keyframes::he442a72709c63fad
frame #11 - 0x000000010b720263 - _<style..selector_matching..Stylist<Impl>>::add_stylesheet::h92b16ac9c7fcb28e
frame #12 - 0x000000010b6db062 - layout_thread::LayoutThread::handle_reflow::h6771f195a62bbc92
frame #13 - 0x000000010b6c7b6d - layout_thread::LayoutThread::handle_request_helper::h1029bbb7e9e50e59
frame #14 - 0x000000010b6ace9f - layout_thread::LayoutThread::handle_request::ha13841b9d3ecdc81
frame #15 - 0x000000010b66cb1a - std::panicking::try::call::h401e4a3a7768c3f1
frame #16 - 0x000000010d00546b - __rust_try
frame #17 - 0x000000010d005405 - __rust_maybe_catch_panic
frame #18 - 0x000000010b66de84 - _<F as alloc..boxed..FnBox<A>>::call_box::h8169792cb3dac906
frame #19 - 0x000000010d000ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #20 - 0x00007fff8a93599c - _pthread_body
frame #21 - 0x00007fff8a935919 - _pthread_start

```

**Comment by jdm** [comment] 2016-07-01 15:34
Duplicate of #11999. Will be fixed by #12008. Thanks for reporting it!

**Closed by jdm** 2016-07-01 15:34 UTC
