### ISSUE TITLE
GitHub glyphicons / octicons / font icons don't show up

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#9479] opened 2016-02-01 05:18 UTC
https://github.com/blog/1106-say-hello-to-octicons

Would improve our ability to dogfood :dog: 

# Servo

![screen shot 2016-02-01 at 12 15 38 am](https://cloud.githubusercontent.com/assets/416575/12709355/1ce02b68-c879-11e5-927f-2108afc8012f.png)

# Chrome

![screen shot 2016-02-01 at 12 15 51 am](https://cloud.githubusercontent.com/assets/416575/12709356/1e0e91aa-c879-11e5-846d-3558d764044d.png)

**Comment by frewsxcv** [comment] 2016-02-01 05:19
Possibly related to https://github.com/servo/servo/issues/7762

**Comment by Arthur2e5** [comment] 2016-05-05 17:20
Note: GitHub has switched to SVGs for these icons instead of using webfont glyphicons. Consider using https://octicons.github.com/ to reproduce the bug.

**Comment by carols10cents** [comment] 2016-07-01 16:56
Since github has switched to SVGs, I think this is now a duplicate of #9998.

**Closed** 2016-07-01 16:59 UTC
Labels: I-wrong
