### ISSUE TITLE
text-align: justify is not incremental layout safe (whitespace changes size as cursor moves)

### ISSUE THREAD

**Issue by kaksmet** [servo/servo#10499] opened 2016-04-09 15:35 UTC
Affects: articles on hltv.org (e.g. http://www.hltv.org/news/17505-bodyy-replaces-ex6tenz-in-g2)

Description: When the cursor is moved vertically text whitespace changes size. Moving it horizontally does not seem to trigger this behaviour.

This is on OS X with webrender enabled.

![bug](https://cloud.githubusercontent.com/assets/1777894/14404514/9150b64a-fe78-11e5-8e5c-a9bb18c7bf32.gif)

**Comment by frewsxcv** [comment] 2016-04-09 17:00
Probably a duplicate of https://github.com/servo/servo/issues/6203

**Comment by kaksmet** [comment] 2016-04-09 17:44
Here is a reduced test case:

```html
<style>
div {
	text-align: justify;
}
a:hover {
}
</style>
<div>
	<p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur lacus
        mauris, dapibus in nisi id, lobortis imperdiet neque. Pellentesque
        vestibulum quam sed enim mattis, non sollicitudin velit porta. Cras
        pellentesque ante ut facilisis sagittis. Vestibulum volutpat arcu in tempor
        vestibulum. Etiam tristique, lectus vel interdum dapibus, nisl turpis
        facilisis dolor, posuere egestas arcu augue a nibh. Nulla eget posuere
        nisi. Aliquam lacinia mi at accumsan tincidunt. Sed facilisis enim sed
        pharetra maximus. Mauris a dolor vestibulum, ultricies mi quis, aliquet
        neque. Cras molestie elit sed sapien fermentum, nec hendrerit erat finibus.
    </p>
    <a href="">HOVER ME</a>
</div>

```

**Comment by frewsxcv** [comment] 2016-04-09 20:05
[This *might* be the relevant section in `layout` causing the expansion](https://github.com/servo/servo/blob/0a1efe4578e43c4ffc2f90ff0118660899a83ac4/components/layout/inline.rs#L995-L998)

**Comment by Shiroy** [comment] 2016-04-09 22:16
The issue #10207 may be related too.

**Comment by kaksmet** [comment] 2016-04-12 11:34
I think [this](https://github.com/servo/servo/blob/0a1efe4578e43c4ffc2f90ff0118660899a83ac4/components/layout/inline.rs#L1106-L1107) is the cause.
From what I can see the extra space between words is added on each layout, causing it to accumulate.

**Comment by mbrubeck** [comment] 2016-05-04 21:38
This was previously filed as #6502, but I thought it was fixed by #7821.  I'm not sure if it regressed again, or was never actually fixed.  Investigating.

**Comment by mbrubeck** [comment] 2016-05-05 15:44
@kaksmet:

> I think [this](https://github.com/servo/servo/blob/0a1efe4578e43c4ffc2f90ff0118660899a83ac4/components/layout/inline.rs#L1106-L1107) is the cause.
From what I can see the extra space between words is added on each layout, causing it to accumulate.

That's correct.  To fix this, we could add a new `extra_word_spacing: Au` field to [TextRun][1] with an initial value of Au(0).  Instead of modifying the GlyphStore, `justify_inline_fragments` would only make the TextRun mutable and update this field.  (`InlineFlow::set_inline_fragment_positions` might also need to reset it to zero for non-justified lines, if they were previously justified.)

Then the code that renders the glyphs can add this extra spacing to the "advance" of each space glyph.  There are two code paths that need to do this: [one for webrender][3] and [one for non-webrender][2].

[1]: https://github.com/servo/servo/blob/95a1f7668cba3e903b2cee73caef121d286e9c3c/components/gfx/text/text_run.rs#L24-L36
[2]: https://github.com/servo/servo/blob/95a1f7668cba3e903b2cee73caef121d286e9c3c/components/gfx/paint_context.rs#L1800-L1814
[3]: https://github.com/servo/servo/blob/95a1f7668cba3e903b2cee73caef121d286e9c3c/components/layout/webrender_helpers.rs#L394-L406

**Comment by kaksmet** [comment] 2016-05-05 15:54
@mbrubeck That seems pretty straightforward. I'll start working on a fix for this tonight.

**Comment by kaksmet** [comment] 2016-05-09 22:26
@mbrubeck 
Is there a way to detect if the line has been changed from justified to non-justified in `InlineFlow::set_inline_fragment_positions`? Currently I reset `extra_word_spacing` for non-justified lines every time it's called.
My changes look [this](https://github.com/servo/servo/compare/master...kaksmet:justify-fix) for the moment.

I also seem to be hitting two other bugs.
The first one is that the words are jumping around between reflows. Most easily reproduced when resizing the window but also happens when hovering the link.
I'm not sure if this is caused by my changes or if it previously was hidden by the bug my changes fixes.
![bouncing](https://cloud.githubusercontent.com/assets/1777894/15129783/3c6590a4-1644-11e6-9ce6-daca496c5245.gif)

The other bug seems to be clipping related and occurs both with and without webrender.
![clipping](https://cloud.githubusercontent.com/assets/1777894/15129831/968e4cce-1644-11e6-9cc7-85b80e08e48a.gif)

Any thoughts on what is causing these bugs?

**Comment by mbrubeck** [comment] 2016-05-09 23:24
> Is there a way to detect if the line has been changed from justified to non-justified in InlineFlow::set_inline_fragment_positions?

For each ScannedTextFragmentInfo you could do `if info.run.extra_word_spacing != Au(0) { *Arc::make_mut(&mut info.run) = Au(0); }`. This at least avoids calling `make_mut` when it's not needed.

> the words are jumping around between reflows

I think this is caused by my suggestion of resetting the extra word spacing in `set_inline_fragment_positions`.  This is too late, since the line breaking and `slack_inline_size` calculation was already done using the old word spacing.  Instead, try resetting `extra_word_spacing` to zero in `Fragment::reset_text_range_and_inline_size` which is called at the start of `LineBreaker::reflow_fragment`.

> The other bug seems to be clipping related and occurs both with and without webrender.

I've seen similar issues before... Have you checked whether this also happens on master?

**Comment by kaksmet** [comment] 2016-05-10 12:43
> Instead, try resetting extra_word_spacing to zero in `Fragment::reset_text_range_and_inline_size`

Thanks, that fixed it.

> I've seen similar issues before... Have you checked whether this also happens on master?

Yes, it also happens on master.

**Closed** 2016-05-10 21:11 UTC
Labels: A-layout/text, C-assigned, C-has-test, I-wrong
