### ISSUE TITLE
Segfault on Android since #19011

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#19058] opened 2017-10-30 09:51 UTC
Happens at startup. Managed to bisect to #19011

/cc @SimonSapin @mbrubeck

I don't have much information. I'm struggling to get a backtrace.

**Comment by paulrouget** [comment] 2017-10-30 09:53
I don't use the "official" Android build mechanism. So I might be missing something about the allocator.

**Comment by SimonSapin** [comment] 2017-10-30 12:17
I think that part of the problem is that we need to define a `extern fn ft_free(mem: FT_Memory, ptr: *mut c_void)` function that deallocates without knowing what size was used to allocate that pointer. The standard Rust APIs require a size to be known during deallcation, and using `malloc_usable_size` of that seems suspicious.

I’m working on a PR to make `freetype/font_context.rs` use C-level jemalloc functions directly. (Platforms where we use FreeType also happen to be platforms where we use jemalloc.) Hopefully that will help with that segfault.

**Comment by paulrouget** [comment] 2017-10-30 12:37
Is there a way for me to confirm that this is indeed the issue?

**Comment by SimonSapin** [comment] 2017-10-30 12:39
Without a backtrace, I don’t know.

**Comment by SimonSapin** [comment] 2017-10-30 14:03
@paulrouget Try with https://github.com/servo/servo/pull/19061 ?

**Comment by SimonSapin** [comment] 2017-10-30 19:12
Oops, before actually closing this, @paulrouget can you confirm if this segfault still happens?

**Comment by paulrouget** [comment] 2017-10-31 11:16
#43a4f01647 doesn't crash. Thank you so much :)

**Closed** 2017-10-31 11:18 UTC
