### ISSUE TITLE
GstPlayer crash on https://mozilla.com/firefox

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#22280] opened 2018-11-27 23:45 UTC
Running servo on https://mozilla.com/firefox produces:
```
** (servo:11858): WARNING **: GstPlayer: scaletempo element not available. Audio pitch will not be preserved during trick modes

(servo:11858): GStreamer-CRITICAL **: gst_element_get_bus: assertion 'GST_IS_ELEMENT (element)' failed

(servo:11858): GStreamer-CRITICAL **: gst_bus_create_watch: assertion 'GST_IS_BUS (bus)' failed

(servo:11858): GLib-CRITICAL **: g_source_set_callback: assertion 'source != NULL' failed
Stack trace
stack backtrace:
   0:     0x55ce4a517c7c - backtrace::backtrace::trace::h34a5004b5e0f1dc7
   1:     0x55ce4a516f12 - <backtrace::capture::Backtrace as core::default::Default>::default::hae829d87a5db9150
   2:     0x55ce4a516f88 - backtrace::capture::Backtrace::new::hcbbf9ea3df342ffc
   3:     0x55ce4883b04a - servo::install_crash_handler::handler::h30f7ca45a0085785
   4:     0x55ce4b0535ac - WasmFaultHandler
                        at /home/ajeffrey/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/wasm/WasmSignalHandlers.cpp:1494
   5:     0x7f3e00a7238f - <unknown>
   6:     0x7f3e017eecc4 - g_source_attach
   7:     0x7f3e022d851c - gst_player_main
                        at ../subprojects/gst-plugins-bad/gst-libs/gst/player/gstplayer.c:2910
   8:     0x7f3e01817c54 - <unknown>
   9:     0x7f3e00a686b9 - start_thread
  10:     0x7f3dff30141c - clone
  11:                0x0 - <unknown>
Stack trace
stack backtrace:
   0:     0x55ce4a517c7c - backtrace::backtrace::trace::h34a5004b5e0f1dc7
   1:     0x55ce4a516f12 - <backtrace::capture::Backtrace as core::default::Default>::default::hae829d87a5db9150
   2:     0x55ce4a516f88 - backtrace::capture::Backtrace::new::hcbbf9ea3df342ffc
   3:     0x55ce4883b04a - servo::install_crash_handler::handler::h30f7ca45a0085785
   4:     0x55ce4b0535ac - WasmFaultHandler
                        at /home/ajeffrey/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/wasm/WasmSignalHandlers.cpp:1494
   5:     0x7f3e00a7238f - <unknown>
   6:     0x55ce4883b0d2 - servo::install_crash_handler::handler::h30f7ca45a0085785
   7:     0x55ce4b0535ac - WasmFaultHandler
                        at /home/ajeffrey/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.2/mozjs/js/src/wasm/WasmSignalHandlers.cpp:1494
   8:     0x7f3e00a7238f - <unknown>
   9:     0x7f3e017eecc4 - g_source_attach
  10:     0x7f3e022d851c - gst_player_main
                        at ../subprojects/gst-plugins-bad/gst-libs/gst/player/gstplayer.c:2910
  11:     0x7f3e01817c54 - <unknown>
  12:     0x7f3e00a686b9 - start_thread
  13:     0x7f3dff30141c - clone
  14:                0x0 - <unknown>
Stack trace
```

**Comment by ferjm** [comment] 2018-11-28 06:40
CC @sdroege @ceyusa

**Comment by sdroege** [comment] 2018-11-28 13:03
The crash and everything comes from here: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/blob/master/gst-libs/gst/player/gstplayer.c#L2917

There should probably be some more assertions in that code. In your case the problem seems to be that you simply don't have the `playbin` element available, see line 2898 a bit above. You need to at least gst-plugins-base properly installed in addition to gst-plugins-bad.

**Comment by jdm** [comment] 2018-11-28 15:55
@asajeffrey Was this on Magic Leap in particular? I can't reproduce this in macOS.

**Comment by asajeffrey** [comment] 2018-11-28 20:55
It was on Linux.

**Comment by atouchet** [comment] 2018-11-28 21:46
The page crashes Servo for me in Windows 10.

**Comment by ferjm** [comment] 2018-11-29 08:34
@asajeffrey @atouchet could you confirm that you don't have `gst-plugins-base` installed, please?

**Comment by asajeffrey** [comment] 2018-11-29 15:20
I don't have `gst-plugins-base` installed.

**Comment by atouchet** [comment] 2018-11-29 17:51
Does gst-plugins-bas come with the GStreamer installer? If so I may have it installed.

**Comment by ferjm** [comment] 2019-04-16 15:57
https://github.com/servo/media/pull/167 was already merged and used in Servo.

**Closed by ferjm** 2019-04-16 15:57 UTC
Labels: A-content/media, I-crash, P-linux, P-windows
