### ISSUE TITLE
Part of the GitHub diffstat is incorrectly rendered as RTL when it's not

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#7016] opened 2015-08-06 01:55 UTC
Minimal testcase:

    <!DOCTYPE html>
    <style>
    .text-diff-added {
        color: green;
        font: 13px Helvetica;
    }
    .text-diff-deleted {
        color: red;
        font: 13px Helvetica;
    }
    </style>
    <body><span class="text-diff-added">+1</span><span class="text-diff-deleted">−114</span>

Notice that the minus sign is a high Unicode character, not `-`. On my system, this triggers creation of a new text run, since Helvetica does not have a glyph for that character.

I believe that the problem is that `bidi_level` is incorrectly set based on `paragraph_bytes_processed` in `scan_for_runs`, even when there's no bidi present.

@mbrubeck -- what is `paragraph_bytes_processed` intended to do?

**Comment by mbrubeck** [comment] 2015-08-06 03:12
This is a duplicate of #6978 which has a fix in the queue (#6998).

> @mbrubeck -- what is `paragraph_bytes_processed` intended to do?

`paragraph_bytes_processed` is a byte index into the string passed to `unicode_bidi::process_text` (and thus also an index into the bidi levels array it returns).  This string parameter used to be named `paragraph` until servo/unicode-bidi#12, but I forgot to rename this variable when the other variable names changed.

**Closed** 2015-08-06 03:13 UTC
Labels: A-layout/text, I-wrong
