### ISSUE TITLE
[FR] check for build requirement

### ISSUE THREAD

**Issue by metux** [servo/servo#19624] opened 2017-12-22 09:41 UTC
./mach should check for build requirements early, in order to avoid later breaks, and print easily
understandable error messages.

checks should be done eg. for
* llvm (especially the compiler-specific headers - there already had been reports on that, and I got hit by that myself)
* pkgconfig
* zlib-dev
* make
* virtualenv
* libfreetype6-dev
* libexpat1-dev
* libfontconfig1-dev
* mesa-common-dev
* git
...

**Comment by metux** [comment] 2017-12-23 01:59
I'd suggest as a first start, collect the individual steps (eg. apt-get calls) in dist-specific scripts, w/ somewhat  canonical names (eg. bootstrap-debian-<releasename>, etc). Later add some dist-detect magic which calls the right script.

**Comment by metux** [comment] 2017-12-23 02:01
In later iterations we could also consider using dist-provided 3rd-party packages instead of bundled ones.
Unless there is a hard need for building specific versions on our own, dist packages should be preferred.

**Comment by tigercosmos** [comment] 2017-12-24 15:46
Could `mach bootstrap` solve the problem?
>  Install required packages for building.

**Comment by jdm** [comment] 2017-12-28 18:02
That is the idea, but it is not yet a supported or recommended command to run outside of our automated build infrastructure.

**Comment by mrobinson** [comment] 2023-06-22 10:41
This issue seems like a duplicate of #12674.

**Closed by mrobinson** 2023-06-22 10:41 UTC
Labels: A-mach, A-build
