### ISSUE TITLE
Calling current_styles before or during styling

### ISSUE THREAD

**Issue by alexvistyazh** [servo/servo#13975] opened 2016-10-29 11:07 UTC
Calling current_styles before or during styling
### Servo Version:
Servo 0.0.1-e4fcc06
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(10) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(5), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <Constellation>: Closing frame FrameId { namespace_id: PipelineNamespaceId(19), index: FrameIndex(0) } twice.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(19), index: PipelineIndex(1) }>: sto
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-10-29 20:45
This looks like a duplicate of #13962. Thanks for reporting it!

**Closed by jdm** 2016-10-29 20:45 UTC
Labels: I-panic
