### ISSUE TITLE
Crash when visit http://acid3.acidtests.org/

### ISSUE THREAD

**Issue by 0x391F** [servo/servo#34748] opened 2024-12-23 08:01 UTC
**Describe the bug:**
Visit http://acid3.acidtests.org/
**To Reproduce:**
Servo crash

**Platform:**
Windows 11 Enterprise LTSC 2024 x64 (24H2)

**Comment by jdm** [comment] 2024-12-23 08:43
Duplicate of #6519.

**Closed by jdm** 2024-12-23 08:43 UTC
Labels: C-untriaged
