### ISSUE TITLE
put servo issued by `./mach test` into background

### ISSUE THREAD

**Issue by xudifsd** [servo/servo#10567] opened 2016-04-13 12:10 UTC
when I run test using `./mach test`, it will keep starting servo, and my current window keeps losing focus, I can't work or even write a tweet to complain, it's so annoying, can we put that test into background?

**Comment by jdm** [comment] 2016-04-13 12:50
This is the behaviour for the reference tests in particular (`./mach test-css` and certain tests in `./mach test-wpt`), which currently do not support being executed without a window that steals the focus unfortunately.

**Comment by gsnedders** [comment] 2016-04-19 22:44
This is essentially just a dupe of #9513.

**Comment by frewsxcv** [comment] 2016-04-29 20:03
Duplicate of https://github.com/servo/servo/issues/10836 as well

**Closed by frewsxcv** 2016-04-29 20:03 UTC
Labels: A-testing
