### ISSUE TITLE
Make WebXR an optional feature

### ISSUE THREAD

**Issue by frc4533-lincoln** [servo/servo#34195] opened 2024-11-09 05:00 UTC
**Describe the new feature:**
Add a `webxr` feature on all crates that depend on `webxr` and/or `webxr-api`.
It could be enabled by default. 

WebXR is rarely used, but is a hard requirement for the `canvas` crate.
Additionally `webxr-api` is required by:
 - `canvas_traits`
 - `constellation`
 - `embedder_traits`
 - `script_traits`
 - and all crates that depend on them...

**Comment by msub2** [comment] 2024-11-09 05:28
There's an existing PR for this at #33526, I'm not sure if it's stalled out because they weren't sure how to add tests for it or if they just haven't gotten back to it.

**Comment by sagudev** [comment] 2024-11-09 16:55
it waits for some script refactors that would modularize script and allow more separate script moduls (such as webgpu and webxr to be in separate script crates).

**Comment by jdm** [comment] 2024-11-09 18:22
I don't think it makes sense to wait on the script refactoring. I think that's also going to be a compex project.

**Comment by frc4533-lincoln** [comment] 2024-11-09 18:28
@msub2 Sorry; I should've looked a little harder.
@sagudev Thanks for letting me know.

Happy to see all the great work going on with Servo.

**Comment by sagudev** [comment] 2024-11-13 20:55
Duplicate of https://github.com/servo/servo/issues/33464

**Closed** 2024-11-13 20:56 UTC
Labels: B-feature-tracking, C-untriaged
