### ISSUE TITLE
iframes eventually crash on resize

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#1675] opened 2014-02-12 01:36 UTC
~~~
./servo ../src/test/html/simple_iframe.html
~~~

Resize the window a lot and eventually Servo will crash with

~~~
task '<unnamed>' failed at 'assertion failed: `(left == right) && (right == left)` (left: `1281u32`, right: `0u32`)', /home/keegan/proj/servo/servo/src/support/layers/rust-layers/platform/linux/surface.rs:247
~~~

This assertion happens on

``` .rs
glXBindTexImageEXT(native_context.display,
                   cast::transmute(glx_pixmap),
                   GLX_FRONT_EXT,
                   ptr::null());
assert_eq!(gl2::get_error(), NO_ERROR);
```

and the error code `1281 = 0x0501` is `gl2::INVALID_VALUE`.

cc @pcwalton

**Comment by glennw** [comment] 2015-01-27 01:49
Unable to reproduce, so closing for now.

**Closed by glennw** 2015-01-27 01:49 UTC
Labels: A-gfx/uncategorized, I-crash
