### ISSUE TITLE
Servo full recompilation when switching between desktop and mobile compilation targets

### ISSUE THREAD

**Issue by MortimerGoro** [servo/servo#18050] opened 2017-08-11 18:38 UTC
It seems that Servo does a full compilation when switching between mobile and desktop compilation targets.

Example after a finished android compilation:
`./mach build --release --android` : No need to compile anything
`./mach build --release`:  Recompiles desktop.
`./mach build --release --android`: Recompiles everything again even if I force stop the previous command

Is there any way to avoid this?

**Comment by nox** [comment] 2018-11-27 09:59
Duplicate of #20380.

**Closed** 2018-11-27 14:05 UTC
Labels: A-build
