### ISSUE TITLE
web.basemark.com won't start, no error shown

### ISSUE THREAD

**Issue by Pryx** [servo/servo#15392] opened 2017-02-05 20:15 UTC
Tested current master, built and tested with both release and debug option on Arch Linux.

When you go to [web.basemark.com](http://web.basemark.com) and click start, Servo shows white screen and nothing happens. Interestingly enough no error is shown.

**Comment by jdm** [comment] 2017-02-05 20:35
When I run it I see "Could not load the requested page: connection reset".

**Comment by jdm** [comment] 2017-02-05 20:51
`curl https://web.basemark.com` shows me the page source. When I `cargo install` the rural and rget crates (which are based on `reqwest` and rely on `hyper`, like Servo), both of those tools take over a minute to retrieve the page source. Something very strange is going on.

**Comment by nox** [comment] 2017-10-07 16:01
@jdm I can't reproduce your issue anymore.

**Comment by atouchet** [comment] 2020-06-16 23:22
I am able to start and complete the benchmark using a recent nightly build.

![Screenshot](https://user-images.githubusercontent.com/26315797/84837551-43edf680-afed-11ea-8aaf-22886f85bc95.png)

**Comment by jdm** [comment] 2020-06-16 23:47
Looks like we can close it, then!

**Closed by jdm** 2020-06-16 23:47 UTC
Labels: A-network, A-webcompat
