### ISSUE TITLE
unexpected crash in 2d.composite.uncovered.nocontext.copy.html

### ISSUE THREAD

**Issue by avadacatavra** [servo/servo#15897] opened 2017-03-10 00:37 UTC
{"status": "CRASH", "stack": null, "subtest": null, "action": "test_result", "test": "/2dcontext/compositing/2d.composite.uncovered.nocontext.copy.html", "line": 64503, "message": null, "expected": "OK"}

http://build.servo.org/builders/linux-rel-wpt/builds/2790

**Comment by jdm** [comment] 2017-03-10 02:21
Could you include the full output from the test here?

**Comment by KiChjang** [comment] 2017-03-10 07:51
Duplicate of #15898.

**Closed by KiChjang** 2017-03-10 07:51 UTC
Labels: I-intermittent
