### ISSUE TITLE
assertion failed: rect.size.height >= Zero::zero()

### ISSUE THREAD

**Issue by mateon1** [servo/servo#20029] opened 2018-02-12 12:08 UTC
Found with domato

```html
<div style="border-collapse: collapse; overflow-y: hidden; border-top: inset">
```

```gdb
VMware, Inc.
softpipe
3.3 (Core Profile) Mesa 17.3.0-devel
assertion failed: rect.size.height >= Zero::zero() (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }, at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/euclid-0.16.4/src/rect.rs:252)
stack backtrace:
   0:     0x55555bd5f6f4 - backtrace::backtrace::libunwind::trace::h79984cabe80721dc
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h10c59b076f73358b
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x55555bd56e7c - backtrace::capture::Backtrace::new::haef9cefb7535bc7c
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x55555597ca36 - servo::main::{{closure}}::h35a26859ef4691ad
                        at ports/servo/main.rs:146
   3:     0x55555bd72b35 - std::panicking::rust_panic_with_hook::haa00f5a9417cd684
                        at libstd/panicking.rs:577
   4:     0x5555588ca0b7 - std::panicking::begin_panic::he901a527e19d0f9d
                        at /checkout/src/libstd/panicking.rs:537
   5:     0x5555588d79be - <euclid::rect::TypedRect<T, U>>::inner_rect::ha2921bda0f1707df
                        at /shared/dev/rust/servo/<panic macros>:3
   6:     0x55555898be1b - <layout::block::BlockFlow as layout::display_list::builder::BlockFlowDisplayListBuilding>::setup_clip_scroll_node_for_overflow::h68d8aa756af6a13e
                        at components/layout/display_list/builder.rs:2715
   7:     0x55555898aea5 - <layout::block::BlockFlow as layout::display_list::builder::BlockFlowDisplayListBuilding>::setup_clipping_for_block::h0ddc2224d4ef6458
                        at components/layout/display_list/builder.rs:2569
   8:     0x55555898a8ca - <layout::block::BlockFlow as layout::display_list::builder::BlockFlowDisplayListBuilding>::collect_stacking_contexts_for_block::he2c97c3d477dcd17
                        at components/layout/display_list/builder.rs:2499
   9:     0x555558987a4a - <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts::h6773e5ed21bce540
                        at components/layout/block.rs:2146
  10:     0x5555588aad24 - layout::flow::BaseFlow::collect_stacking_contexts_for_children::h396c59e02832340f
                        at components/layout/flow.rs:1137
  11:     0x55555898a9d3 - <layout::block::BlockFlow as layout::display_list::builder::BlockFlowDisplayListBuilding>::collect_stacking_contexts_for_block::he2c97c3d477dcd17
                        at components/layout/display_list/builder.rs:2512
  12:     0x555558987a4a - <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts::h6773e5ed21bce540
                        at components/layout/block.rs:2146
  13:     0x5555588aad24 - layout::flow::BaseFlow::collect_stacking_contexts_for_children::h396c59e02832340f
                        at components/layout/flow.rs:1137
  14:     0x55555898a9d3 - <layout::block::BlockFlow as layout::display_list::builder::BlockFlowDisplayListBuilding>::collect_stacking_contexts_for_block::he2c97c3d477dcd17
                        at components/layout/display_list/builder.rs:2512
  15:     0x555558987a4a - <layout::block::BlockFlow as layout::flow::Flow>::collect_stacking_contexts::h6773e5ed21bce540
                        at components/layout/block.rs:2146
  16:     0x555558991ec5 - layout::sequential::build_display_list_for_subtree::hef3892f5ab8b5837
                        at components/layout/sequential.rs:73
  17:     0x5555560ed775 - layout_thread::LayoutThread::compute_abs_pos_and_build_display_list::{{closure}}::h7698b070ef3f8e8f
                        at components/layout_thread/lib.rs:977
  18:     0x5555562a9ebe - profile_traits::time::profile::hb16a70b55b1906ac
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:125
  19:     0x55555601538d - layout_thread::LayoutThread::compute_abs_pos_and_build_display_list::h1ed30d231868eb29
                        at components/layout_thread/lib.rs:960
  20:     0x55555601b1c9 - layout_thread::LayoutThread::perform_post_main_layout_passes::hbe483b14399fe714
                        at components/layout_thread/lib.rs:1607
  21:     0x55555601b006 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::h26adb72f295bdcd5
                        at components/layout_thread/lib.rs:1591
  22:     0x5555560183e0 - layout_thread::LayoutThread::handle_reflow::h3e5f94e915e29975
                        at components/layout_thread/lib.rs:1311
  23:     0x5555560ecd84 - layout_thread::LayoutThread::handle_request_helper::{{closure}}::h9d073627c741bb9c
                        at components/layout_thread/lib.rs:696
  24:     0x5555562aa415 - profile_traits::time::profile::hcc8dfd56aebbc1cc
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:125
  25:     0x5555560125f2 - layout_thread::LayoutThread::handle_request_helper::he181f0b19e3ae497
                        at components/layout_thread/lib.rs:693
  26:     0x5555560115a9 - layout_thread::LayoutThread::handle_request::he53e1b2280a200f7
                        at components/layout_thread/lib.rs:639
  27:     0x5555560107ff - layout_thread::LayoutThread::start::h5c412997379e0a96
                        at components/layout_thread/lib.rs:552
  28:     0x5555560ebf81 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::{{closure}}::h5930d8f259803103
                        at components/layout_thread/lib.rs:313
  29:     0x555556026d9e - profile_traits::mem::ProfilerChan::run_with_memory_reporting::hbaad2e5643a26133
                        at /shared/dev/rust/servo/components/profile_traits/mem.rs:63
  30:     0x5555560ec52e - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::h8ab68700ae327b9f
                        at components/layout_thread/lib.rs:312
  31:     0x55555632d1c4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8bd49049bf17985d
                        at /checkout/src/libstd/sys_common/backtrace.rs:133
  32:     0x55555605232b - std::thread::Builder::spawn::{{closure}}::{{closure}}::hf8a3feaf8876ec66
                        at /checkout/src/libstd/thread/mod.rs:406
  33:     0x555556250524 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4c528c0e819d990c
                        at /checkout/src/libstd/panic.rs:293
  34:     0x55555614e7a4 - std::panicking::try::do_call::h2563547fe5c092e4
                        at /checkout/src/libstd/panicking.rs:479
  35:     0x55555bd9b93e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  36:     0x55555614e5dc - std::panicking::try::hb5ff300c91983e16
                        at /checkout/src/libstd/panicking.rs:458
  37:     0x55555625095c - std::panic::catch_unwind::hc3030ada97e47c49
                        at /checkout/src/libstd/panic.rs:358
  38:     0x555556052178 - std::thread::Builder::spawn::{{closure}}::hf893242e5b9d9228
                        at /checkout/src/libstd/thread/mod.rs:405
  39:     0x555556052385 - <F as alloc::boxed::FnBox<A>>::call_box::h0501c3a31e02a809
                        at /checkout/src/liballoc/boxed.rs:788
  40:     0x55555bd8667b - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h13f1b0bf377a9f5b
                        at /checkout/src/liballoc/boxed.rs:798
                         - std::sys_common::thread::start_thread::hb5b6e0447b9691dc
                        at libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::hcaff0bef1a01c624
                        at libstd/sys/unix/thread.rs:90
  41:     0x7ffff6eb0493 - start_thread
  42:     0x7ffff5479abe - __clone
  43:                0x0 - <unknown>
ERROR:servo: assertion failed: rect.size.height >= Zero::zero()
called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }, at libcore/result.rs:916)
stack backtrace:
   0:     0x55555bd5f6f4 - backtrace::backtrace::libunwind::trace::h79984cabe80721dc
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h10c59b076f73358b
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x55555bd56e7c - backtrace::capture::Backtrace::new::haef9cefb7535bc7c
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x55555597ca36 - servo::main::{{closure}}::h35a26859ef4691ad
                        at ports/servo/main.rs:146
   3:     0x55555bd72b35 - std::panicking::rust_panic_with_hook::haa00f5a9417cd684
                        at libstd/panicking.rs:577
   4:     0x55555bd729be - std::panicking::begin_panic::ha956683198499384
                        at libstd/panicking.rs:537
   5:     0x55555bd728ba - std::panicking::begin_panic_fmt::h587e116719f14631
                        at libstd/panicking.rs:521
   6:     0x55555bd72852 - rust_begin_unwind
                        at libstd/panicking.rs:497
   7:     0x55555bda70f0 - core::panicking::panic_fmt::h1d64949939b0af2f
                        at libcore/panicking.rs:71
   8:     0x555557e3b587 - core::result::unwrap_failed::h3a5a16f3b2b4e294
                        at /checkout/src/libcore/macros.rs:23
   9:     0x555557e01b4a - <core::result::Result<T, E>>::unwrap::hcb7207b101927cd7
                        at /checkout/src/libcore/result.rs:782
  10:     0x55555694d80a - script::dom::window::Window::force_reflow::h117701292c186b33
                        at components/script/dom/window.rs:1250
  11:     0x55555717aa01 - script::script_thread::ScriptThread::handle_resize_event::hf4b097491a76ca1e
                        at components/script/script_thread.rs:2526
  12:     0x55555717753a - script::script_thread::ScriptThread::handle_event::h689aa339c275dfaa
                        at components/script/script_thread.rs:2288
  13:     0x555557160d4a - script::script_thread::ScriptThread::handle_msgs::h2a853b1b6b42fe5e
                        at components/script/script_thread.rs:925
  14:     0x55555716055b - script::script_thread::ScriptThread::start::hc085fdd56db9ef8f
                        at components/script/script_thread.rs:901
  15:     0x5555573418cc - <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}::h6718222298e372d7
                        at components/script/script_thread.rs:582
  16:     0x555557c7d8a4 - profile_traits::mem::ProfilerChan::run_with_memory_reporting::hba4fe948a17d9248
                        at /shared/dev/rust/servo/components/profile_traits/mem.rs:63
  17:     0x555557341eb9 - <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::hc52fa1e83a118225
                        at components/script/script_thread.rs:581
  18:     0x555558679124 - std::sys_common::backtrace::__rust_begin_short_backtrace::h604d88dfe7211f59
                        at /checkout/src/libstd/sys_common/backtrace.rs:133
  19:     0x55555827604b - std::thread::Builder::spawn::{{closure}}::{{closure}}::h8cece30a0117d41b
                        at /checkout/src/libstd/thread/mod.rs:406
  20:     0x5555571aa454 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h915406fcc949d604
                        at /checkout/src/libstd/panic.rs:293
  21:     0x555556d14994 - std::panicking::try::do_call::hd1bff7f5c8aaf409
                        at /checkout/src/libstd/panicking.rs:479
  22:     0x55555bd9b93e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  23:     0x555556c6355c - std::panicking::try::hbcd5814247b8593a
                        at /checkout/src/libstd/panicking.rs:458
  24:     0x5555571dcc6c - std::panic::catch_unwind::h4be360fdf9fffe17
                        at /checkout/src/libstd/panic.rs:358
  25:     0x555558274e28 - std::thread::Builder::spawn::{{closure}}::hb1b86bbe9a2a6aa2
                        at /checkout/src/libstd/thread/mod.rs:405
  26:     0x555558276315 - <F as alloc::boxed::FnBox<A>>::call_box::h16a105ec805d69cb
                        at /checkout/src/liballoc/boxed.rs:788
  27:     0x55555bd8667b - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h13f1b0bf377a9f5b
                        at /checkout/src/liballoc/boxed.rs:798
                         - std::sys_common::thread::start_thread::hb5b6e0447b9691dc
                        at libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::hcaff0bef1a01c624
                        at libstd/sys/unix/thread.rs:90
  28:     0x7ffff6eb0493 - start_thread
  29:     0x7ffff5479abe - __clone
  30:                0x0 - <unknown>
ERROR:servo: called `Result::unwrap()` on an `Err` value: "SendError(..)"
WARNING: YOU ARE LEAKING THE WORLD (at least one JSRuntime and everything alive inside it, that is) AT JS_ShutDown TIME.  FIX THIS!
^CServo exited with return value -2
```

**Comment by pyfisch** [comment] 2018-02-12 22:02
this is another failure (besides the flexbox ones) caused by #19942

**Comment by dralley** [comment] 2020-03-25 16:58
This test snippet is still failing

**Comment by dralley** [comment] 2020-04-14 19:10
@jdm This issue appears to be a duplicate of https://github.com/servo/servo/issues/23093

There's more detail on that one.

**Closed** 2020-04-14 19:30 UTC
Labels: A-layout/block, C-has-manual-testcase, I-panic
