### ISSUE TITLE
Crash on Demo: Evil Ad

### ISSUE THREAD

**Issue by friedelwolff** [servo/servo#14183] opened 2016-11-12 11:22 UTC
I got this crash when viewing ./demos/evil_ad/physics/with-ad.html

As far as I remember there was no interaction (mouse/keyboard) at the time of the crash.

```
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(30) }"
stack backtrace:
   0:     0x557e80373bbd - backtrace::backtrace::trace::h16372ee7bf1517e5
   1:     0x557e80374242 - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
   2:     0x557e7f09c2e4 - servo::install_crash_handler::handler::hd221f6da40259b0e
   3:     0x557e801a3803 - AsmJSFaultHandler
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   4:     0x7f6f8f56e17f - <unknown>
   5:     0x557e7fd6efd3 - _ZNK13JSCompartment28unsafeUnbarrieredMaybeGlobalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartmentinlines.h:34
                         - _ZNK8JSObject6globalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsobjinlines.h:427
                         - _ZN2js34GetGlobalForObjectCrossCompartmentEP8JSObject
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsfriendapi.cpp:357
   6:     0x557e7f76023a - script::dom::bindings::callback::CallSetup::new::h35d64f8822e184d1
   7:     0x557e7f81aba6 - script::dom::globalscope::GlobalScope::fire_timer::h12d363cd150ec05c
   8:     0x557e7fb3ef64 - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::hd0bd397d54ad8158
   9:     0x557e7f992434 - script::script_thread::ScriptThread::handle_msgs::h831a39b83948db01
  10:     0x557e7f4f23e7 - std::panicking::try::do_call::h126bdcce98720636
  11:     0x557e80cfc35a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  12:     0x557e7f6c4114 - _<F as alloc..boxed..FnBox<A>>::call_box::hce6b3fd124b7c005
  13:     0x557e80cf2274 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:605
                         - std::sys_common::thread::start_thread
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/common/thread.rs:21
                         - std::sys::thread::{{impl}}::new::thread_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/thread.rs:84
  14:     0x7f6f8f5655bc - start_thread
  15:     0x7f6f8f08a62c - __clone
  16:                0x0 - <unknown>
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(30) }"
stack backtrace:
   0:     0x557e80373bbd - backtrace::backtrace::trace::h16372ee7bf1517e5
   1:     0x557e80374242 - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
   2:     0x557e7f09c2e4 - servo::install_crash_handler::handler::hd221f6da40259b0e
   3:     0x7f6f8efc65cf - <unknown>
   4:     0x557e7f09c36f - servo::install_crash_handler::handler::hd221f6da40259b0e
   5:     0x557e801a3803 - AsmJSFaultHandler
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
   6:     0x7f6f8f56e17f - <unknown>
   7:     0x557e7fd6efd3 - _ZNK13JSCompartment28unsafeUnbarrieredMaybeGlobalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartmentinlines.h:34
                         - _ZNK8JSObject6globalEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsobjinlines.h:427
                         - _ZN2js34GetGlobalForObjectCrossCompartmentEP8JSObject
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsfriendapi.cpp:357
   8:     0x557e7f76023a - script::dom::bindings::callback::CallSetup::new::h35d64f8822e184d1
   9:     0x557e7f81aba6 - script::dom::globalscope::GlobalScope::fire_timer::h12d363cd150ec05c
  10:     0x557e7fb3ef64 - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::hd0bd397d54ad8158
  11:     0x557e7f992434 - script::script_thread::ScriptThread::handle_msgs::h831a39b83948db01
  12:     0x557e7f4f23e7 - std::panicking::try::do_call::h126bdcce98720636
  13:     0x557e80cfc35a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  14:     0x557e7f6c4114 - _<F as alloc..boxed..FnBox<A>>::call_box::hce6b3fd124b7c005
  15:     0x557e80cf2274 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:605
                         - std::sys_common::thread::start_thread
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/common/thread.rs:21
                         - std::sys::thread::{{impl}}::new::thread_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/thread.rs:84
  16:     0x7f6f8f5655bc - start_thread
  17:     0x7f6f8f08a62c - __clone
  18:                0x0 - <unknown>
./runservo.sh: line 2: 30999 Illegal instruction     ./servo -b --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref shell.builtin-key-shortcuts.enabled=false ./browserhtml/out/index.html
```

**Comment by jdm** [comment] 2017-01-06 22:14
This looks like the same crash as #12456.

**Comment by nox** [comment] 2017-10-03 10:57
Closing as duplicate of #12072.

**Closed by nox** 2017-10-03 10:57 UTC
Labels: A-content/bindings, I-crash
