### ISSUE TITLE
assertion failed: self.suspended_since.get().is_some()

### ISSUE THREAD

**Issue by friedelwolff** [servo/servo#13859] opened 2016-10-20 19:23 UTC
I believe I was clicking on the back button multiple times on Ars Technica when I got this error report.

assertion failed: self.suspended_since.get().is_some()
### Servo Version:
Servo 0.0.1-6c28d44
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(14) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(14) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(14) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(14) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(15) }>: FIXME: </script> not fully implemented
WARNING: <ScriptThread PipelineId 
...
```
This report was generated by the browser.html issue reporter.

**Comment by jdm** [comment] 2016-10-20 19:31
This is a duplicate of #13780. Thanks for reporting it!

**Closed by jdm** 2016-10-20 19:31 UTC
