### ISSUE TITLE
It doesn't work at all in my pc.

### ISSUE THREAD

**Issue by machenity** [servo/servo#16474] opened 2017-04-15 12:51 UTC
I downloaded windows-build msi file and installed, but it doesn't work at all.
Whenever I launch it, a window is showed but it disappeared soon.
I'm using pc with windows 10 64bit.

**Comment by jdm** [comment] 2017-04-15 13:58
Sounds like a duplicate of #16393.

**Closed by jdm** 2017-04-15 13:58 UTC
