### ISSUE TITLE
`getPropertyValue` can't read `outline`

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo#20903] opened 2018-06-02 19:06 UTC
```html
<style>
  #out {
    outline: .2em solid red;
  }
</style>
<span id="out">
  <span id="in">link</span>
  <span id="in">href</span>
</span>
<script>
  var val = window.getComputedStyle(document.querySelector("#out")).getPropertyValue('outline');
  console.log(val);
</script>
```
should get `rgb(255, 0, 0) solid 2.66667px`, but log nothing in Servo.

related code:
https://github.com/servo/servo/blob/5683f09a0b4ed1ca6a5f2075060b36b3ccc0ca36/components/script/dom/cssstyledeclaration.rs#L228-L232

https://github.com/servo/servo/blob/5683f09a0b4ed1ca6a5f2075060b36b3ccc0ca36/components/script/dom/cssstyledeclaration.rs#L211

**Comment by emilio** [comment] 2018-06-02 19:17
That's because outline is a shorthand, and we return the empty string for those.

I think we should support shorthands in getComputedStyle and I'm doing related work in FF, but FF also returns the empty string.

**Comment by mrobinson** [comment] 2020-05-09 11:40
I'm going to close this as a duplicate of #22838, which seems to have a bit more information.

**Closed by mrobinson** 2020-05-09 11:40 UTC
Labels: A-content/script, C-has-manual-testcase
