### ISSUE TITLE
Text animation doesn't stop

### ISSUE THREAD

**Issue by atouchet** [servo/servo#26460] opened 2020-05-07 05:16 UTC
URL: https://vercel.com/keyboard

Steps to reproduce:

1. Load https://vercel.com/keyboard in Servo.
2. The text animation no longer stops when it's supposed to and the animation keeps looping.

This issue first occurred in the 2020-05-02 nightly build. Tested in Windows 10.

Regression range: https://github.com/servo/servo/compare/6fb75c2b9eb3825932a22b1c7a6d7ce03809fbb2...d08c4fff15cb5f6a8840621e848c9de22fcc3439

**Comment by atouchet** [comment] 2020-05-07 05:17
This regression is likely due to #26362.

cc @mrobinson

**Comment by mrobinson** [comment] 2020-05-07 08:15
Reduced test case:
```
 <style>
 .paragraph {
     opacity: 0;
     animation: fade-in 600ms ease-in forwards;
     animation-delay: 0.5s;
 }
 @keyframes fade-in {
     to { opacity:1; }
 }
 </style>
<p class="paragraph">Animating Text</p>
```

The issue is we are no longer keeping animations around after they finish so they infinitely retrigger. This should theoretically be fixed by proper implementation of `animation-fill-mode`.

**Closed** 2020-05-17 20:15 UTC
Labels: C-has-manual-testcase
