### ISSUE TITLE
[Bug]: Arabic and Persian characters rendered in horizontal reverse

### ISSUE THREAD

**Issue by radiumatic** [servo/servo#32451] opened 2024-06-06 12:35 UTC
**Describe the bug:**
A clear and concise description of the bug.

Persian and Arabic characters are incorrectly rendered. Letters are (wrongly) placed from left to right, so 

```سلام``` 

reads 

```مالس```. 

(The way Markdown handles RTL is way broken, I had to split the words and the main line to avoid the overall English to be rendered in RTL)

![image](https://github.com/servo/servo/assets/71447191/50a28efe-9bd9-4a37-ae72-b242305776e2)
The above should read 

"فارسی". (Farsi)

**To Reproduce:**
Steps to reproduce the behavior.

1. Go to https://wikipedia.org. 

**Platform:**
Specify OS, distribution, and hardware platform.

Linux, Fedora 39, X64 and Servo version 0.0.1-5f538b8.

**Comment by mrobinson** [comment] 2024-06-06 13:33
I believe this is a duplicate of #25881.

**Closed by mrobinson** 2024-06-06 13:33 UTC
Labels: C-untriaged
