### ISSUE TITLE
'position: fixed' vs 'overflow: scroll'

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#7293] opened 2015-08-20 08:09 UTC
http://smfr.org/misc/css/stacking/css-escher.html (reproduced below) renders with a few issues:
- [ ] The black-border element’s contents should scroll, because of `overflow-y: scroll`. They don’t at least on Linux.
- [ ] When scrolling the main document, the green element should not move on the screen with the rest of the content, because of `position: fixed`.
- [ ] The green element should not clipped by `overflow-y` since the containing block of elements with `position: fixed` is the viewport:
  
  https://drafts.csswg.org/css2/visufx.html#overflow
  
  > This property specifies whether content of a block container element is clipped when it overflows the element's box. It affects the clipping of all of the element's content except any descendant elements (and their respective content and descendants) whose containing block is the viewport or an ancestor of the element
- [ ] The blue elements should not be visible "over" the black border. The `overflow` clipping area should be the [padding edge](https://drafts.csswg.org/css2/box.html#box-dimensions) (inside the border) not the border edge.
  
  https://drafts.csswg.org/css2/visufx.html#overflow-clipping
  
  > Whenever overflow occurs, the 'overflow' property specifies whether a box is clipped to its padding edge, and if so, whether a scrolling mechanism is provided to access any clipped out content. 

The [stacking / z-ordering](https://drafts.csswg.org/css2/zindex.html) seems correct, though.

CC @pcwalton @glennw

``` html
<!DOCTYPE html>

<html>
<head>
    <style>
        body {
            height: 2000px;
        }
        .container {
            position: relative;
            height: 300px;
            width: 300px;
            border: 4px solid black;
            overflow-y: scroll;
            z-index: 0;
            resize: both;
        }

        .contents {
            height: 1000px;
        }

        .box {
            position: relative;
            height: 100px;
            width: 100px;
            margin: 10px;
            background-color: blue;
        }

        .fixed {
            position: fixed;
            background-color: green;
            left: 50px;
            top: 200px;
            height: 200px;
            width: 200px;
        }
    </style>
</head>
<body>

    <p>Try scrolling the overflow area, and the main document</p>

    </div>
    <div class="container">
        <div class="contents">
            <div class="fixed"></div>
            <div class="box"></div>
            <div class="box"></div>
            <div class="box"></div>
            <div class="box"></div>
            <div class="box"></div>
        </div>
    </div>
</body>
</html>
```

**Comment by mrobinson** [comment] 2017-03-24 09:18
Looks like with all the WebRender and stacking context improvements, this was fixed in the process. I'm going to close this, but feel free to open it again if you detect a problem or a regression.

**Closed by mrobinson** 2017-03-24 09:18 UTC
Labels: A-layout/uncategorized
